/* ============================ guides ============================
   Short pieces for the Học tab, written to be read on a phone: full
   sentences, one idea at a time, each paragraph leading into the next.
   `tags` are INTERESTS ids so the home screen can suggest guides. */
const GUIDES = [

/* ------------------------------------------------------------ tarot ---- */
{ id: 'tarot-overview', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Toàn cảnh bộ bài và lộ trình học', en: 'The deck at a glance and how to learn it' },
  intro: { vi: 'Bộ tarot gồm 78 lá và được chia thành hai nhóm. Năm mươi sáu lá Ẩn Phụ mô tả những việc xảy ra trong đời sống hằng ngày, còn hai mươi hai lá Ẩn Chính kể lại hành trình lớn của một kiếp người. Bài học này dựng sẵn bộ khung đó cho bạn, để mỗi lá bạn học về sau đều tìm được đúng chỗ đứng của nó.', en: 'A tarot deck has 78 cards in two parts. The twenty-two Major Arcana tell the great journey of a life, while the fifty-six Minor Arcana speak about the things that happen every day. This lesson gives you the frame, so that every card you learn later has a clear place in it.' },
  sections: [
    { h: { vi: '22 lá Ẩn Chính', en: 'The 22 Major Arcana' }, p: { vi: 'Nhóm Ẩn Chính mang số thứ tự từ 0 là Gã Khờ cho tới 21 là Thế Giới. Mỗi lá trong nhóm này ghi lại một bài học lớn, có thể là một khởi đầu, một lựa chọn, một mất mát, một niềm hy vọng, hoặc một lần hoàn tất. Khi một lá Ẩn Chính rơi vào trải bài, câu chuyện bạn hỏi thường có sức nặng lớn hơn bạn hình dung, và nó cũng nằm ngoài tầm tay bạn nhiều hơn.', en: 'The Majors are numbered from 0, The Fool, to 21, The World. Each one is a big lesson: a beginning, a choice, a loss, a hope, or a completion. When a Major appears in a spread, the matter you are asking about is usually more important than it looks, and less in your hands than you would like.' } },
    { h: { vi: '56 lá Ẩn Phụ', en: 'The 56 Minor Arcana' }, p: { vi: 'Nhóm Ẩn Phụ được chia thành bốn chất, và mỗi chất gồm mười bốn lá: từ Át đến Mười, tiếp theo là bốn lá hoàng gia gồm Tiểu Đồng, Kỵ Sĩ, Nữ Hoàng và Đức Vua. Gậy thuộc nguyên tố lửa và nói về hành động, đam mê cùng công việc. Cốc thuộc nước và nói về cảm xúc, tình yêu cùng các mối quan hệ. Kiếm thuộc khí và nói về suy nghĩ, lời nói cùng xung đột. Tiền thuộc đất và nói về tiền bạc, sức khỏe cùng những việc cụ thể. Nhóm Ẩn Phụ kể lại câu chuyện thường ngày, tức là phần đời mà bạn có thể thay đổi được.', en: 'The Minors come in four suits of fourteen cards: Ace to Ten, then the four court cards, Page, Knight, Queen and King. Wands belong to fire and speak of action, passion and work. Cups belong to water and speak of feelings, love and relationships. Swords belong to air and speak of thought, words and conflict. Pentacles belong to earth and speak of money, health and practical matters. The Minors tell the story of everyday life, which means the things you can actually change.' } },
    { h: { vi: 'Chặng một của hành trình Gã Khờ (0–7)', en: 'The Fool\'s Journey, part one (0–7)' }, p: { vi: 'Bạn hoàn toàn có thể đọc 22 lá Ẩn Chính như một câu chuyện liền mạch. Gã Khờ mang số 0 chính là bạn ở thời điểm mới lên đường, hai bàn tay trắng nhưng vẫn tin vào cuộc đời. Dọc đường, cậu gặp lần lượt những người dạy cậu cách sống giữa thế giới bên ngoài. Nhà Ảo Thuật (1) chỉ cho cậu thấy cậu đã có sẵn mọi công cụ cần dùng. Nữ Tư Tế (2) dạy cậu lắng nghe tiếng nói bên trong. Hoàng Hậu (3) mang đến tình thương và sự nuôi dưỡng, còn Hoàng Đế (4) đặt ra kỷ luật và trật tự. Giáo Hoàng (5) đại diện cho truyền thống và cho người thầy. Tới Người Yêu (6), cậu đối diện lựa chọn đầu tiên của trái tim, và tới Cỗ Xe (7), cậu tự cầm cương lần đầu và giành được chiến thắng.', en: 'You can read the 22 Majors as one continuous story. The Fool (0) is you at the start of the road, empty-handed but trusting life. Along the way he meets the people who teach him how to live in the outer world. The Magician (1) shows him that he already has every tool he needs. The High Priestess (2) teaches him to listen inward. The Empress (3) is love and nurture, and The Emperor (4) is discipline and order. The Hierophant (5) stands for tradition and the teacher. With The Lovers (6) he faces the heart\'s first real choice, and with The Chariot (7) he takes the reins for the first time and wins.' } },
    { h: { vi: 'Chặng hai (8–14): quay về phía nội tâm', en: 'Part two (8–14): turning inward' }, p: { vi: 'Sau chiến thắng đó, Gã Khờ hiểu ra rằng sức mạnh thật sự không hề ồn ào. Sức Mạnh (8) là sự dịu dàng đủ sức thuần phục một con sư tử. Ẩn Sĩ (9) đánh dấu lúc cậu rút vào cô độc để hiểu chính mình. Bánh Xe (10) nhắc cậu rằng đời có lúc lên lúc xuống, và không phải điều gì cũng do cậu quyết định. Công Lý (11) buộc cậu trả lời cho những việc cậu đã làm. Người Treo Ngược (12) dạy cậu biết dừng lại và nhìn sự việc từ một góc khác. Tử Thần (13) là cái kết cần thiết để một khởi đầu mới có chỗ, còn Tiết Độ (14) là thế cân bằng cậu tìm được sau tất cả.', en: 'Having won, he learns that real strength makes no noise. Strength (8) is the gentleness that can tame a lion. The Hermit (9) is his retreat into solitude to understand himself. The Wheel (10) reminds him that life rises and falls, and that not everything is his to decide. Justice (11) makes him answer for what he has done. The Hanged Man (12) teaches him to stop and look at things another way. Death (13) is the ending that makes a new start possible, and Temperance (14) is the balance he finds after all of it.' } },
    { h: { vi: 'Chặng ba (15–21): qua bóng tối tới ánh sáng', en: 'Part three (15–21): darkness and light' }, p: { vi: 'Chặng cuối vừa khó nhất vừa đẹp nhất. Ác Quỷ (15) là tất cả những gì đang trói chân cậu: thói quen, ham muốn và nỗi sợ. Tòa Tháp (16) là lúc mọi thứ dựng trên nền giả đổ sập xuống. Khi cơn bão qua đi, Ngôi Sao (17) đem hy vọng trở lại. Mặt Trăng (18) là đoạn đường mờ sương mà cậu phải dò bằng linh cảm. Sau đó Mặt Trời (19) mang tới niềm vui trong trẻo khi bóng tối đã nằm lại phía sau. Phán Xét (20) là tiếng gọi thức tỉnh, lúc cậu nhìn lại toàn bộ chặng đường. Cuối cùng Thế Giới (21) đánh dấu ngày cậu về tới nơi, trọn vẹn và sẵn sàng lên đường một lần nữa với con số 0.', en: 'The last stretch is the hardest, and also the most beautiful. The Devil (15) is everything that binds him: habits, cravings and fears. The Tower (16) is the collapse of all that was built on false ground. After the storm, The Star (17) brings hope back. The Moon (18) is the foggy road he must walk by instinct. Then The Sun (19) brings clear joy once the darkness is behind him. Judgement (20) is the wake-up call, when he looks back over the whole road. And The World (21) is his arrival, whole and ready to set out once more as 0.' } },
    { h: { vi: 'Một trải bài giữ giá trị trong bao lâu', en: 'How long a reading holds true' }, p: { vi: 'Tarot không dự đoán trọn một đời người. Theo cách hiểu chung của những người đọc bài lâu năm, một trải bài thường phản ánh khoảng ba tháng sắp tới, tức là một mùa. Các trải bài lớn như Celtic Cross có thể nhìn xa tới sáu tháng, còn lá rút mỗi sáng chỉ nói về đúng ngày hôm đó. Qua mốc thời gian này, hoặc ngay khi bạn đã đổi quyết định và hoàn cảnh đã khác đi, các lá bài cũng đổi theo. Vì vậy bạn không nên hỏi lại cùng một câu quá sớm, nhưng sau vài tháng thì một trải bài mới là hoàn toàn hợp lý. Muốn chắc chắn, bạn hãy nói to khung thời gian trước khi xào bài, ví dụ "trải bài này dành cho ba tháng tới".', en: 'Tarot does not predict a whole life. By the common understanding of long-time readers, a spread usually reflects the next three months or so, one season. Large spreads like the Celtic Cross can look up to six months ahead, while a card drawn each morning speaks only about that day. Past that point, or as soon as you have changed your decision and your circumstances have changed, the cards change too. So do not ask the same question again too soon, but after a few months a fresh reading is entirely reasonable. To be sure, say the time frame out loud before you shuffle: "this reading is for the next three months".' } },
    { h: { vi: 'Lộ trình học của khóa này', en: 'How to learn in this course' }, p: { vi: 'Bạn hãy học nhóm Ẩn Chính trước, theo đúng trật tự câu chuyện vừa kể. Mỗi ngày bạn mở một lá, đọc trang của lá đó, rồi tự kể lại bằng lời của mình vì sao lá này nối tiếp lá trước. Sau hai mươi hai ngày, bạn chuyển sang nhóm Ẩn Phụ và học lần lượt từng chất, từ Át đến Đức Vua. Mỗi buổi sáng, bạn rút một lá và viết một câu về điều bạn nghĩ lá đó muốn nói, sau đó bạn mới đọc trang của nó. Bạn nên để phần Trải bài lại sau cùng, khi các lá đã trở thành những gương mặt quen thuộc.', en: 'Learn the Majors first, in the order of the story above. Each day, open one card, read its page, then retell in your own words why this card follows the one before. After twenty-two days, move on to the Minors and take them one suit at a time, from Ace to King. Each morning, draw a card and write one line about what you think it is saying, and only then read its page. Leave the Spreads section for last, once the cards have become familiar faces.' } }
  ] },
{ id: 'tarot-start', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Những bước đầu tiên với tarot', en: 'Getting started with tarot' },
  intro: { vi: 'Bạn không cần thuộc lòng cả 78 lá trước lần rút đầu tiên. Thứ bạn thật sự cần chỉ gồm một bộ bài, một câu hỏi rõ ràng và một thói quen nhỏ lặp lại mỗi ngày. Bốn bước dưới đây đã đủ để bạn khởi đầu.', en: 'You do not need to memorise all 78 cards before your first draw. What you really need is one deck, one clear question and a small daily habit. The four steps below are enough to begin.' },
  sections: [
    { h: { vi: 'Gắn bó với một bộ bài duy nhất', en: 'Use one deck only' }, p: { vi: 'Bạn nên khởi đầu với bộ Rider–Waite–Smith, hoặc với một bộ được vẽ dựa theo bộ đó. Phần lớn sách và video đều lấy hình ảnh của bộ này làm chuẩn, và cả 78 lá đều có tranh minh họa, nên bức tranh sẽ dạy bạn trước khi bạn kịp thuộc nghĩa.', en: 'Start with the Rider–Waite–Smith deck or one drawn after it. Most books and videos assume its pictures, and all 78 cards are illustrated, so the pictures teach you before you have learned the meanings.' } },
    { h: { vi: 'Nắm bộ khung trước khi học nghĩa', en: 'Structure first, meanings later' }, p: { vi: 'Bạn hãy nắm bộ khung trước tiên: 22 lá Ẩn Chính chứa những bài học lớn, còn 56 lá Ẩn Phụ mô tả đời sống hằng ngày và được chia thành bốn chất. Gậy thuộc lửa và chỉ hành động, Cốc thuộc nước và chỉ cảm xúc, Kiếm thuộc khí và chỉ suy nghĩ, Tiền thuộc đất và chỉ thế giới vật chất. Khi bộ khung này đã nằm trong đầu, bạn có thể đoán khá đúng nghĩa của một lá mà bạn chưa từng học.', en: 'Get the skeleton first: the 22 Majors are the big lessons, and the 56 Minors are daily life, divided into four suits. Wands are fire and action, Cups are water and feeling, Swords are air and thought, Pentacles are earth and the material world. Once you know this frame, you can make a fair guess at a card you have never studied.' } },
    { h: { vi: 'Duy trì thói quen một lá mỗi ngày', en: 'One card a day' }, p: { vi: 'Mỗi buổi sáng, bạn rút một lá. Bạn ghi lại những gì bạn nhìn thấy trên tranh và điều bạn nghĩ lá đó muốn nói, rồi sau đó bạn mới tra nghĩa. Khoảng cách giữa phán đoán của bạn và lời sách viết chính là nơi bạn học được nhiều nhất. Đến buổi tối, bạn nhìn lại và đối chiếu xem lá bài khớp với ngày của bạn tới mức nào.', en: 'Every morning, pull one card. Write down what you see and what you think it is saying, and only then look up the meaning. The gap between your guess and the book is where most of the learning happens. In the evening, look back and see how well the card matched your day.' } },
    { h: { vi: 'Chất lượng câu hỏi định đoạt câu trả lời', en: 'The question shapes the answer' }, p: { vi: 'Một câu hỏi tốt sẽ đổi lấy một câu trả lời tốt. Câu "Mình cần biết gì về chuyện này?" luôn hiệu quả hơn câu "Có nên hay không?", và câu "Mình nên làm gì để đạt được điều này?" hiệu quả hơn câu "Khi nào?". Một lá bài trả lời rất tốt cho câu hỏi cái gì, trả lời kém cho câu hỏi có hay không, và gần như không trả lời được câu hỏi khi nào.', en: 'A good question earns a good answer. "What do I need to know about this?" always works better than "Should I or not?", and "What should I do to…?" works better than "When?". A single card answers what very well, answers yes-or-no poorly, and can hardly answer when at all.' } }
  ] },
{ id: 'tarot-reversed', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Bạn có nên đọc lá ngược hay không?', en: 'Reversed cards: should you read them?' },
  intro: { vi: 'Không có luật nào bắt bạn phải đọc lá ngược. Nhiều người đọc lá ngược, nhiều người bỏ qua, và cả hai cách đều tạo ra những trải bài tốt. Điều quan trọng là bạn chọn lấy một cách và giữ nguyên cách đó.', en: 'There is no rule that forces you to read reversed cards. Many readers do, many do not, and both ways produce good readings. What matters is that you choose one way and keep to it.' },
  sections: [
    { h: { vi: 'Cách thứ nhất: bỏ qua lá ngược', en: 'Way one: no reversals' }, p: { vi: 'Theo cách này, mỗi lá bài vốn đã chứa sẵn một mặt sáng và một mặt tối. Bạn nhìn vào câu hỏi và vào các lá xung quanh để biết mặt nào đang lên tiếng. Có một mẹo nhỏ rất hiệu quả: bạn thêm chữ "quá" vào trước một từ khóa tích cực và bạn sẽ nhận được từ khóa tiêu cực tương ứng. Tự tin quá mức trở thành kiêu ngạo, và chủ động quá mức trở thành áp đặt.', en: 'In this way, every card already has a bright side and a shadow side. You look at the question and at the neighbouring cards to tell which side is speaking. There is a small trick that works very well: put the word "too" in front of a positive keyword and you get the negative one. Too confident becomes arrogant, too active becomes pushy.' } },
    { h: { vi: 'Cách thứ hai: có đọc lá ngược', en: 'Way two: with reversals' }, p: { vi: 'Nếu bạn chọn đọc lá ngược, bạn hãy hiểu lá ngược là năng lượng của lá đang bị chặn lại, bị trì hoãn, hoặc đang quay vào bên trong. Lá ngược không đồng nghĩa với điều xấu. Ví dụ, lá Mười Kiếm ngược thường mang nghĩa rằng phần tệ nhất đã qua.', en: 'If you do read reversals, think of them as the card\'s energy being blocked, delayed, or turned inward. Reversed does not mean bad. The Ten of Swords reversed, for example, usually means that the worst is already over.' } },
    { h: { vi: 'Giữ nguyên cách bạn đã chọn', en: 'Pick one way and keep it' }, p: { vi: 'Bạn nên quyết định trước khi xào bài. Nếu bạn đổi cách đọc giữa chừng chỉ vì bạn không thích câu trả lời, bạn đang tự lừa chính mình, và trải bài sẽ không còn nói được điều gì đáng tin.', en: 'Decide before you shuffle. If you switch halfway simply because you dislike the answer, you are fooling yourself, and the spread can no longer tell you anything you can trust.' } }
  ] },
{ id: 'tarot-court', cat: 'tarot', badge: 'conv', tags: ['tarot', 'love'],
  title: { vi: 'Lá hoàng gia chỉ một con người hay một tính cách?', en: 'Court cards: a person or a trait?' },
  intro: { vi: 'Mười sáu lá hoàng gia, gồm Tiểu Đồng, Kỵ Sĩ, Nữ Hoàng và Đức Vua của bốn chất, là phần gây khó nhất cho người mới. Nguyên nhân nằm ở chỗ chúng có thể mang ba nghĩa cùng lúc: một con người cụ thể, một phần trong chính bạn, hoặc một cách hành xử.', en: 'The sixteen court cards, the Page, Knight, Queen and King of each suit, are the hardest part for beginners. The reason is that they can carry three meanings at once: a specific person, a part of yourself, or a way of behaving.' },
  sections: [
    { h: { vi: 'Ý nghĩa của bốn cấp bậc', en: 'Four ranks' }, p: { vi: 'Tiểu Đồng chỉ một người trẻ, một tin nhắn, hoặc bước đầu tiên khi học một điều mới. Kỵ Sĩ chỉ hành động và sự di chuyển, đôi khi hơi quá mức. Nữ Hoàng đã làm chủ chất của mình từ bên trong. Đức Vua thể hiện chất đó ra bên ngoài và nắm quyền quyết định.', en: 'The Page is a young person, a message, or the first step of learning something new. The Knight is action and movement, sometimes a little too much of it. The Queen has mastered the suit from within. The King expresses the suit outwardly and holds the authority to decide.' } },
    { h: { vi: 'Khi câu hỏi của bạn nhắm vào một người', en: 'When you ask about a person' }, p: { vi: 'Một lá hoàng gia mô tả tính cách chứ không cố định tuổi tác hay giới tính. Nữ Hoàng Kiếm hoàn toàn có thể là một người đàn ông sắc sảo. Vì vậy bạn hãy nhìn vào chất trước tiên: Gậy nóng và hăng hái, Cốc giàu cảm xúc, Kiếm thiên về lý trí, còn Tiền thiên về thực tế.', en: 'A court card describes character rather than a fixed age or gender. The Queen of Swords can perfectly well be a sharp-minded man. So look at the suit first: Wands are hot and eager, Cups are emotional, Swords are rational, and Pentacles are practical.' } }
  ] },

/* -------------------------------------------------------- lenormand ---- */
{ id: 'len-vs-tarot', cat: 'lenormand', badge: 'doc', tags: ['lenormand'],
  title: { vi: 'Những điểm phân biệt Lenormand với tarot', en: 'How Lenormand differs from tarot' },
  intro: { vi: 'Lenormand là bộ bài gồm 36 lá, và mỗi lá là một vật cụ thể như Kỵ Mã, Cỏ Ba Lá, Con Thuyền hay Ngôi Nhà. Khác biệt lớn nhất so với tarot nằm ở chỗ bạn không đọc từng lá riêng lẻ, bạn đọc các lá đứng cạnh nhau giống như đọc một câu văn.', en: 'Lenormand is a deck of 36 cards, and each card is a concrete thing: the Rider, the Clover, the Ship, the House. The biggest difference from tarot is that you do not read one card at a time; you read the cards standing next to each other, the way you would read a sentence.' },
  sections: [
    { h: { vi: 'Mỗi lá tương ứng với một danh từ', en: 'Each card is a noun' }, p: { vi: 'Tarot trao cho bạn một khung cảnh nhiều tầng nghĩa, còn Lenormand chỉ trao cho bạn một từ duy nhất. Lá Thư có nghĩa là một lá thư, và Chìa Khóa có nghĩa là sự mở ra hoặc sự chắc chắn. Nghĩa thật sự chỉ xuất hiện khi bạn nối các từ đó lại với nhau. Ví dụ, Kỵ Mã đứng cạnh Lá Thư cho biết một tin nhắn đang trên đường tới.', en: 'Tarot gives you a scene with many layers of meaning, while Lenormand gives you a single word. The Letter means a letter, and the Key means opening, or certainty. The real meaning only appears when you join the words together. The Rider next to the Letter, for instance, means a message that is on its way.' } },
    { h: { vi: 'Lenormand không dùng lá ngược', en: 'There are no reversals' }, p: { vi: 'Lenormand không đọc lá ngược. Thay vào đó, mỗi lá đã mang sẵn một sắc thái tích cực, trung tính hoặc tiêu cực. Lá đứng bên cạnh có nhiệm vụ làm dịu hoặc làm nặng thêm sắc thái đó.', en: 'Lenormand does not use reversals. Instead, every card carries a built-in tone: positive, neutral or negative. The card beside it softens or sharpens that tone.' } },
    { h: { vi: 'Nguồn gốc của bộ bài', en: 'Where the deck comes from' }, p: { vi: 'Bộ bài này khởi đầu là một trò chơi bàn cờ ở Đức vào năm 1799, và nó chỉ mang tên bà Lenormand sau khi bà qua đời. Trên mỗi lá đều in kèm một lá bài Tây thuộc bộ 36 lá, và đó là tương ứng thật sự duy nhất của Lenormand. Lenormand không có tương ứng nào với cung hoàng đạo, vì vậy các bảng cung mà bạn gặp trên mạng đều do từng tác giả tự nghĩ ra.', en: 'The deck began as a German board game in 1799 and only took Mlle Lenormand\'s name after her death. Every card carries a playing card from the 36-card pack, and that is Lenormand\'s only real correspondence. Lenormand has no zodiac correspondences; the sign tables you see online are each author\'s own invention.' } },
    { h: { vi: 'Tầm nhìn thời gian của Lenormand', en: 'How far Lenormand sees' }, p: { vi: 'Lenormand nói về những chuyện cụ thể và ở gần. Một dòng ba lá hoặc năm lá thường bao phủ khoảng vài ngày tới vài tuần sắp tới, ô vuông chín lá bao phủ khoảng một đến ba tháng, còn Grand Tableau 36 lá thường được đọc cho sáu tháng đến một năm. Bản thân các lá cũng mang thời gian riêng: Kỵ Mã tính bằng ngày, Con Thuyền tính bằng tuần đến tháng, Cái Cây đi chậm và tính bằng tháng, còn Mỏ Neo mang nghĩa lâu dài. Muốn rõ ràng, bạn hãy nói to khung thời gian trước khi xào bài, rồi đọc mọi lá bên trong khung đó.', en: 'Lenormand speaks about concrete, near things. A line of three or five cards usually covers the next days to weeks, the nine-card box about one to three months, and the 36-card Grand Tableau is generally read for six months to a year. The cards themselves carry time: the Rider is days, the Ship weeks to months, the Tree slow and counted in months, the Anchor lasting. To be clear, say the time frame out loud before you shuffle, then read every card inside it.' } }
  ] },
{ id: 'len-pairs', cat: 'lenormand', badge: 'doc', tags: ['lenormand'],
  title: { vi: 'Cách đọc hai lá và ba lá', en: 'Reading two and three cards' },
  intro: { vi: 'Đây là bài tập cơ bản nhất của Lenormand, và cũng là kỹ năng bạn sẽ dùng suốt về sau. Hai lá ghép lại tạo thành một ý, còn ba lá ghép lại tạo thành một câu chuyện nhỏ.', en: 'This is the most basic Lenormand exercise, and also the skill you will keep using for the rest of your practice. Two cards together make one idea, and three cards together make a small story.' },
  sections: [
    { h: { vi: 'Hai lá', en: 'Two cards' }, p: { vi: 'Lá thứ nhất giữ vai trò chủ đề, còn lá thứ hai mô tả chủ đề đó. Ngôi Nhà đứng trước Trái Tim nói về một gia đình ấm áp. Nếu Trái Tim đứng trước Ngôi Nhà, ý nghĩa chuyển thành tình cảm hướng về mái ấm, tức là mong muốn ổn định. Như bạn thấy, chỉ cần đổi thứ tự là nghĩa đã khác đi.', en: 'The first card is the subject, and the second card describes it. The House before the Heart speaks of a warm family home. But if the Heart comes before the House, it becomes love turned toward home, a wish to settle down. As you can see, swapping the order changes the meaning.' } },
    { h: { vi: 'Ba lá', en: 'Three cards' }, p: { vi: 'Với ba lá, bạn có hai hướng đọc. Hướng thứ nhất lấy lá giữa làm trọng tâm và để hai lá hai bên bổ nghĩa cho nó. Hướng thứ hai đọc từ trái sang phải theo trục quá khứ, hiện tại và tương lai. Bạn hãy chọn hướng đọc trước khi rút bài.', en: 'With three cards you have two ways to read. The first treats the middle card as the focus, with the two outer cards describing it. The second reads from left to right as past, present and future. Choose your way before you draw.' } },
    { h: { vi: 'Bài tập luyện hằng ngày', en: 'Daily practice' }, p: { vi: 'Mỗi buổi sáng, bạn rút ba lá và viết đúng một câu. Đến buổi tối, bạn kiểm tra lại xem câu đó đúng tới mức nào. Sau khoảng một tháng, bạn sẽ đọc được các cặp lá mà không cần tra cứu gì thêm.', en: 'Each morning, draw three cards and write a single sentence. In the evening, check how well that sentence held up. After about a month, you will be reading pairs without looking anything up.' } }
  ] },

/* ------------------------------------------------------------ astro ---- */
{ id: 'astro-big3', cat: 'astro', badge: 'doc', tags: ['astro'],
  title: { vi: 'Cung Mặt Trời, Mặt Trăng và cung Mọc', en: 'Sun, Moon and Rising' },
  intro: { vi: 'Khi bạn nói "mình là Sư Tử", bạn đang nói về cung Mặt Trời của mình. Nhưng cung Mặt Trời chỉ là một phần của bản đồ sao. Có hai phần nữa cũng quan trọng không kém, đó là cung Mặt Trăng và cung Mọc.', en: 'When you say "I am a Leo", you are talking about your Sun sign. But the Sun sign is only one part of the birth chart. Two other parts matter just as much: the Moon sign and the Rising sign.' },
  sections: [
    { h: { vi: 'Mặt Trời: bạn là ai', en: 'The Sun: who you are' }, p: { vi: 'Cung Mặt Trời được tính từ ngày sinh của bạn. Nó nói về cái tôi, về hướng sống và về con người mà bạn muốn trở thành. Ứng dụng này tính cung Mặt Trời cho bạn ngay khi bạn nhập ngày sinh.', en: 'Your Sun sign comes from your date of birth. It speaks of your core self, your direction in life, and the person you want to become. This app works out your Sun sign as soon as you enter your birthday.' } },
    { h: { vi: 'Mặt Trăng: bạn cảm thấy thế nào', en: 'The Moon: how you feel' }, p: { vi: 'Để biết cung Mặt Trăng, bạn cần giờ sinh gần đúng. Mặt Trăng nói về cảm xúc, thói quen và những gì bạn cần để thấy an toàn. Nhiều người nhận ra mình trong cung Mặt Trăng còn rõ hơn cả cung Mặt Trời.', en: 'To know your Moon sign, you need a roughly correct birth time. The Moon speaks of your feelings, your habits, and what you need in order to feel safe. Many people recognise themselves in their Moon sign even more clearly than in their Sun sign.' } },
    { h: { vi: 'Cung Mọc: người khác thấy bạn ra sao', en: 'Rising: how others see you' }, p: { vi: 'Cung Mọc đòi hỏi giờ sinh và nơi sinh chính xác, vì nó đổi sau mỗi hai giờ. Đây là ấn tượng đầu tiên bạn để lại, là phong cách và vẻ ngoài của bạn. Nếu muốn có một bản đồ sao đầy đủ, bạn cần cả ba thứ: ngày sinh, giờ sinh và nơi sinh.', en: 'The Rising sign needs your exact birth time and place, because it changes every two hours. It is the first impression you leave, your style, your appearance. If you want a full birth chart, you need all three: the date, the time and the place of birth.' } }
  ] },
{ id: 'astro-elements', cat: 'astro', badge: 'doc', tags: ['astro', 'tarot'],
  title: { vi: 'Bốn nguyên tố và ba tính chất', en: 'Four elements and three modes' },
  intro: { vi: 'Mười hai cung hoàng đạo được chia theo hai cách. Nguyên tố cho biết một cung được "làm bằng gì", còn tính chất cho biết cung ấy "chuyển động ra sao". Khi nắm được hai cách chia này, bạn sẽ hiểu bất kỳ cung nào nhanh hơn rất nhiều.', en: 'The twelve signs are divided in two ways. The element tells you what a sign is "made of", and the mode tells you how that sign "moves". Once you know these two divisions, you will understand any sign much faster.' },
  sections: [
    { h: { vi: 'Bốn nguyên tố', en: 'The four elements' }, p: { vi: 'Lửa gồm Bạch Dương, Sư Tử và Nhân Mã: hành động, nhiệt huyết và tự tin. Đất gồm Kim Ngưu, Xử Nữ và Ma Kết: thực tế, bền bỉ và gắn với vật chất. Khí gồm Song Tử, Thiên Bình và Bảo Bình: suy nghĩ, giao tiếp và ý tưởng. Nước gồm Cự Giải, Bọ Cạp và Song Ngư: cảm xúc, trực giác và ký ức. Trong tarot, bốn nguyên tố này tương ứng với bốn chất: Gậy là lửa, Tiền là đất, Kiếm là khí và Cốc là nước.', en: 'Fire holds Aries, Leo and Sagittarius: action, heat and confidence. Earth holds Taurus, Virgo and Capricorn: practical, steady and tied to the material world. Air holds Gemini, Libra and Aquarius: thought, communication and ideas. Water holds Cancer, Scorpio and Pisces: feeling, intuition and memory. In tarot, the four elements match the four suits: Wands are fire, Pentacles are earth, Swords are air and Cups are water.' } },
    { h: { vi: 'Ba tính chất', en: 'The three modes' }, p: { vi: 'Các cung khởi đầu là Bạch Dương, Cự Giải, Thiên Bình và Ma Kết. Mỗi cung mở ra một mùa mới, nên chúng giỏi bắt đầu mọi việc. Các cung cố định là Kim Ngưu, Sư Tử, Bọ Cạp và Bảo Bình. Chúng giữ và duy trì, đôi khi hơi bướng. Các cung biến đổi là Song Tử, Xử Nữ, Nhân Mã và Song Ngư. Chúng thích nghi, linh hoạt và biết cách kết thúc.', en: 'The cardinal signs are Aries, Cancer, Libra and Capricorn. Each one opens a new season, so they are good at starting things. The fixed signs are Taurus, Leo, Scorpio and Aquarius. They hold and maintain, and can be a little stubborn. The mutable signs are Gemini, Virgo, Sagittarius and Pisces. They adapt, stay flexible, and know how to bring things to a close.' } }
  ] },
{ id: 'astro-moon', cat: 'astro', badge: 'conv', tags: ['astro', 'manifest'],
  title: { vi: 'Chu kỳ trăng và cách dùng nó', en: 'The Moon cycle and how to use it' },
  intro: { vi: 'Mặt Trăng đi hết một vòng trong khoảng 29 ngày rưỡi, từ trăng non đến trăng tròn rồi trở lại trăng non. Nhiều người dùng vòng quay này như một nhịp sống: có lúc để gieo, có lúc để nhìn lại, và có lúc để buông. Đây là một thói quen đẹp chứ không phải một quy luật, nên bạn hãy thử và giữ lại những gì hợp với mình.', en: 'The Moon completes one cycle in about twenty-nine and a half days, from new to full and back to new again. Many people use this turning as a rhythm for life: there is a time to plant, a time to look back, and a time to let go. It is a lovely habit rather than a law, so try it and keep whatever suits you.' },
  sections: [
    { h: { vi: 'Trăng non: gieo hạt', en: 'New Moon: planting' }, p: { vi: 'Vào đêm trăng non, bầu trời tối nhất và vòng quay mới bắt đầu. Đây là lúc thích hợp để bạn viết ra điều mình muốn bắt đầu trong tháng này. Hãy viết ngắn và cụ thể, chẳng hạn "mình sẽ tập thể dục ba buổi mỗi tuần" thay vì "mình sẽ khỏe hơn". Một ý định rõ ràng sẽ dễ theo đuổi hơn rất nhiều.', en: 'On the night of the new Moon the sky is at its darkest and a new cycle begins. This is a good moment to write down what you want to start this month. Keep it short and specific, for example "I will exercise three times a week" rather than "I will get healthier". A clear intention is far easier to follow through.' } },
    { h: { vi: 'Trăng tròn: nhìn lại', en: 'Full Moon: looking back' }, p: { vi: 'Khoảng hai tuần sau, trăng tròn là lúc sáng nhất trong tháng. Những gì bạn gieo từ đầu chu kỳ bây giờ đã lộ rõ, nên đây là thời điểm để nhìn lại: điều gì đang tiến triển, điều gì cần buông. Nhiều người thích rút bài vào đêm trăng tròn, vì cảm xúc lúc này thường rõ ràng và dễ gọi tên hơn.', en: 'About two weeks later, the full Moon is the brightest point of the month. Whatever you planted at the start of the cycle has now come to light, so this is the time to look back: what is moving forward, and what needs to be released. Many people like to draw cards on a full-Moon night, because feelings tend to be clearer and easier to name.' } },
    { h: { vi: 'Trăng khuyết: dọn dẹp và nghỉ', en: 'Waning Moon: clearing and rest' }, p: { vi: 'Từ trăng tròn cho đến trăng non tiếp theo, ánh trăng nhỏ dần. Đây là quãng để bạn dọn dẹp, kết thúc những việc dang dở và cho mình nghỉ ngơi. Bạn không nên bắt đầu việc lớn trong giai đoạn này; hãy để dành sức cho vòng quay mới.', en: 'From the full Moon to the next new Moon, the light shrinks night by night. This is the stretch for clearing up, finishing what is unfinished, and giving yourself some rest. It is not the time to start anything big; save your energy for the next cycle.' } },
    { h: { vi: 'Cách dùng cho gọn', en: 'A simple way to use it' }, p: { vi: 'Bạn chỉ cần nhớ ba mốc: trăng non để đặt ý định, trăng tròn để nhìn lại, và trăng khuyết để buông. Ứng dụng luôn hiển thị pha trăng của hôm nay trên trang chủ, nên bạn không cần tự tính.', en: 'You only need to remember three points: the new Moon to set an intention, the full Moon to look back, and the waning Moon to let go. The app always shows today\'s Moon phase on the home screen, so you never have to work it out yourself.' } }
  ] },
{ id: 'astro-retro', cat: 'astro', badge: 'doc', tags: ['astro', 'work'],
  title: { vi: 'Sao Thủy nghịch hành là gì', en: 'What Mercury retrograde means' },
  intro: { vi: 'Ba hoặc bốn lần mỗi năm, Sao Thủy nhìn từ Trái Đất có vẻ như đang đi lùi trong khoảng ba tuần. Thật ra hành tinh không hề lùi; đó chỉ là hiệu ứng góc nhìn khi hai hành tinh vượt qua nhau trên quỹ đạo.', en: 'Three or four times a year, Mercury appears from Earth to move backwards for about three weeks. The planet is not really reversing; it is a trick of perspective as the two planets pass each other in their orbits.' },
  sections: [
    { h: { vi: 'Vì sao người ta hay đổ lỗi cho nó', en: 'Why it gets the blame' }, p: { vi: 'Trong chiêm tinh, Sao Thủy gắn với giao tiếp, đi lại, hợp đồng và máy móc. Vì vậy, mỗi khi Sao Thủy nghịch hành, người ta thường đổ lỗi cho nó về những tin nhắn bị hiểu lầm, những chuyến đi trễ giờ hay chiếc điện thoại bỗng dưng hỏng.', en: 'In astrology, Mercury is linked to communication, travel, contracts and machines. So whenever Mercury goes retrograde, people tend to blame it for misread messages, late journeys and the phone that suddenly stops working.' } },
    { h: { vi: 'Cách dùng cho có ích', en: 'A useful way to treat it' }, p: { vi: 'Bạn có thể xem giai đoạn này như một lời nhắc nhở nhẹ nhàng: đọc lại tin nhắn trước khi gửi, sao lưu dữ liệu, kiểm tra kỹ hợp đồng, và liên lạc lại với những người cũ nếu cần. Nhưng đừng hoãn cả cuộc đời chỉ vì một hành tinh; những việc quan trọng vẫn có thể làm được, chỉ cần cẩn thận hơn một chút.', en: 'You can treat this period as a gentle reminder: re-read a message before sending it, back up your data, check contracts carefully, and reconnect with old contacts if you need to. But do not put your whole life on hold because of one planet; important things can still be done, just with a little more care.' } }
  ] },

/* --------------------------------------------------------- manifest ---- */
{ id: 'mani-what', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Manifestation là gì', en: 'What manifestation is' },
  intro: { vi: 'Manifestation là việc bạn nói rõ điều mình muốn, tin rằng điều đó có thể xảy ra, và hành động như thể nó đang trên đường đến. Phần "hành động" là phần người ta hay quên nhất, nhưng lại là phần quan trọng nhất.', en: 'Manifestation means naming clearly what you want, believing that it is possible, and acting as if it is already on its way. The "acting" part is the one people forget most often, and it is also the part that matters most.' },
  sections: [
    { h: { vi: 'Nó làm được gì cho bạn', en: 'What it can do for you' }, p: { vi: 'Khi bạn gọi tên mục tiêu một cách rõ ràng, bộ não sẽ bắt đầu để ý những cơ hội liên quan mà trước đây bạn bỏ qua. Bạn sẽ dám mở lời, dám nộp đơn và dám hẹn gặp. Đó chính là cách "vũ trụ đáp lại" theo nghĩa thực tế nhất.', en: 'When you name a goal clearly, your mind starts noticing the related chances you used to walk past. You dare to speak up, to apply, to ask for the meeting. That is what "the universe answering" looks like in the most practical sense.' } },
    { h: { vi: 'Nó không làm được gì', en: 'What it cannot do' }, p: { vi: 'Manifestation không thay đổi được người khác, và cũng không thay thế được việc học, việc làm hay việc đi khám bệnh. Nếu có ai nói rằng bạn ốm hay nghèo là vì "rung động thấp", thì họ đang đổ lỗi cho bạn chứ không phải đang dạy bạn.', en: 'Manifestation cannot change other people, and it does not replace studying, working, or seeing a doctor. If someone tells you that you are sick or poor because of "low vibration", they are blaming you, not teaching you.' } },
    { h: { vi: 'Điều tâm lý học đã kiểm chứng', en: 'What psychology has confirmed' }, p: { vi: 'Ba phần của manifest có nền tảng nghiên cứu vững: đặt mục tiêu rõ ràng làm tăng khả năng đạt được; hình dung mình đang làm từng bước giúp bạn bắt tay vào việc; và kế hoạch "nếu… thì…" làm tăng gấp đôi tỷ lệ hoàn thành. Phần không có bằng chứng là ý tưởng rằng suy nghĩ tự nó thay đổi được thế giới bên ngoài. Nabu giữ phần đầu và bỏ phần sau.', en: 'Three parts of manifesting rest on solid research: setting a clear goal raises the odds of reaching it; picturing yourself doing each step gets you started; and if-then plans double completion rates. The part without evidence is the idea that thought alone changes the outside world. Nabu keeps the first part and drops the second.' } },
    { h: { vi: 'Bắt đầu như thế nào', en: 'How to begin' }, p: { vi: 'Hãy viết một câu ở thì hiện tại, chẳng hạn: "Mình đang làm công việc mình thích, với mức lương đủ để sống thoải mái." Mỗi sáng bạn đọc lại câu ấy, rồi trong ngày làm một việc nhỏ hướng về nó. Chỉ cần vậy là bạn đã bắt đầu đúng cách.', en: 'Write one sentence in the present tense, for example: "I am doing work I enjoy, and it pays me enough to live comfortably." Read it every morning, then do one small thing during the day that moves toward it. That alone is a proper start.' } }
  ] },
{ id: 'mani-script', cat: 'manifest', badge: 'conv', tags: ['manifest', 'love', 'work'],
  title: { vi: 'Viết kịch bản (scripting)', en: 'Scripting' },
  intro: { vi: 'Scripting là cách bạn viết một trang nhật ký như thể điều mình mong muốn đã xảy ra rồi. Bạn càng viết cụ thể, càng tả rõ mình thấy gì, nghe gì và cảm thấy gì, thì bài tập càng có tác dụng.', en: 'Scripting means writing a diary page as if the thing you want has already happened. The more specific you are about what you see, hear and feel, the better the exercise works.' },
  sections: [
    { h: { vi: 'Viết như thế nào', en: 'How to write it' }, p: { vi: 'Bạn dùng thì hiện tại hoặc quá khứ gần, ví dụ: "Hôm nay mình vừa ký hợp đồng mới. Sếp bắt tay mình và nói rằng…". Bạn kết bài bằng một lời cảm ơn. Hãy viết liền trong mười phút và đừng dừng lại để sửa.', en: 'Use the present or the recent past tense, for example: "Today I signed the new contract. My manager shook my hand and said…". End the page with a word of thanks. Write for ten minutes without stopping to edit.' } },
    { h: { vi: 'Viết khi nào', en: 'When to write' }, p: { vi: 'Nhiều người thích viết vào đêm trăng non hoặc tối hôm trước một ngày quan trọng. Thật ra, bất cứ lúc nào bạn có được mười phút yên tĩnh đều là thời điểm tốt.', en: 'Many people like to write on a new-Moon night or the evening before an important day. In truth, any ten quiet minutes will do.' } },
    { h: { vi: 'Khi viết về người khác', en: 'When writing about other people' }, p: { vi: 'Hãy viết về cảm giác mà bạn muốn có trong tình yêu, thay vì viết rằng một người cụ thể phải yêu bạn. Mỗi người đều có ý chí riêng của họ. Một câu như "mình được yêu một cách nhẹ nhàng và rõ ràng" sẽ mở ra nhiều cánh cửa hơn là một cái tên.', en: 'Write about the feeling you want to have in love, rather than writing that a specific person must love you. Everyone has a will of their own. A line like "I am loved gently and clearly" opens more doors than a single name ever will.' } }
  ] },
{ id: 'mani-369', cat: 'manifest', badge: 'own', tags: ['manifest'],
  title: { vi: 'Phương pháp 369', en: 'The 369 method' },
  intro: { vi: 'Với phương pháp này, bạn viết câu khẳng định của mình ba lần vào buổi sáng, sáu lần vào buổi chiều và chín lần vào buổi tối. Nó lan truyền từ TikTok và thường được gắn với tên Tesla, dù ông chưa bao giờ dạy điều này.', en: 'With this method, you write your affirmation three times in the morning, six times in the afternoon and nine times at night. It spread from TikTok and is often linked to Tesla, although he never taught anything of the kind.' },
  sections: [
    { h: { vi: 'Vì sao nó có tác dụng với một số người', en: 'Why it works for some people' }, p: { vi: 'Tác dụng không đến từ con số, mà đến từ việc bạn nhắc mình về một mục tiêu đến mười tám lần mỗi ngày. Sự lặp lại đều đặn biến mục tiêu ấy thành ưu tiên thật sự trong đầu bạn.', en: 'The effect does not come from the numbers; it comes from reminding yourself of one goal eighteen times a day. That steady repetition turns the goal into a real priority in your mind.' } },
    { h: { vi: 'Cách làm gọn nhất', en: 'The leanest version' }, p: { vi: 'Bạn chọn một câu ngắn, dưới mười lăm chữ, và giữ nó trong hai mươi mốt ngày. Nếu lỡ quên một ngày, bạn cứ tiếp tục chứ đừng bắt đầu lại từ đầu. Ứng dụng có sẵn bảng đếm để bạn chạm mỗi lần viết xong.', en: 'Choose one short sentence, under fifteen words, and keep it for twenty-one days. If you miss a day, simply carry on rather than starting over. The app has a counter you can tap each time you finish a line.' } }
  ] },
{ id: 'mani-gratitude', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Biết ơn và câu khẳng định', en: 'Gratitude and affirmations' },
  intro: { vi: 'Đây là hai thói quen đơn giản nhất, và cũng là hai thói quen được tâm lý học ủng hộ nhiều nhất. Mỗi tối, bạn ghi ba điều mình biết ơn. Mỗi sáng, bạn nói một câu khẳng định.', en: 'These are the two simplest habits, and also the two with the strongest backing from psychology. Each night, you write down three things you are grateful for. Each morning, you say one affirmation.' },
  sections: [
    { h: { vi: 'Biết ơn cho cụ thể', en: 'Be specific about gratitude' }, p: { vi: 'Lòng biết ơn chỉ có tác dụng khi nó cụ thể. Thay vì viết "biết ơn gia đình", bạn hãy viết "biết ơn vì mẹ gọi hỏi mình ăn cơm chưa lúc bảy giờ tối". Ba điều như thế mỗi tối, ghi vào sổ, là đủ để thay đổi cách bạn nhìn một ngày.', en: 'Gratitude only works when it is specific. Instead of writing "grateful for my family", write "grateful that mum called at seven to ask if I had eaten". Three lines like that each night, in a notebook, are enough to change how you see a day.' } },
    { h: { vi: 'Câu khẳng định phải tin được', en: 'An affirmation you can believe' }, p: { vi: 'Câu khẳng định chỉ có ích khi bạn tin được nó. Nếu bạn nói "mình là triệu phú" trong lúc tài khoản trống, bạn sẽ chỉ thấy giả tạo. Nhưng câu "mình đang học cách quản lý tiền tốt hơn mỗi tuần" thì tin được, và chính niềm tin ấy sẽ kéo bạn đi.', en: 'An affirmation only helps when you can believe it. If you say "I am a millionaire" while your account is empty, it will only feel fake. But "I am learning to handle money better every week" is believable, and that belief is what moves you forward.' } }
  ] },
{ id: 'mani-woop', cat: 'manifest', badge: 'conv', tags: ['manifest', 'work', 'love'],
  title: { vi: 'Phương pháp WOOP', en: 'The WOOP method' },
  intro: { vi: 'WOOP là cách manifest có nhiều bằng chứng nhất, được nghiên cứu hơn hai mươi năm trong tâm lý học. Bốn chữ cái là bốn bước: Wish (mong muốn), Outcome (kết quả), Obstacle (trở ngại) và Plan (kế hoạch). Điểm khác biệt của nó là bạn không chỉ mơ về điều mình muốn, mà còn nhìn thẳng vào thứ đang cản mình.', en: 'WOOP is the manifesting method with the most evidence behind it, studied for over twenty years in psychology. The four letters are four steps: Wish, Outcome, Obstacle and Plan. What makes it different is that you do not only dream about what you want; you also look straight at what stands in your way.' },
  sections: [
    { h: { vi: 'Wish: chọn một mong muốn', en: 'Wish: choose one wish' }, p: { vi: 'Chọn một điều bạn thật sự muốn trong bốn tuần tới, đủ thử thách nhưng có thể làm được. Viết nó bằng ba đến sáu chữ, ví dụ: "tập chạy ba buổi mỗi tuần" hay "nói chuyện thẳng thắn với mẹ".', en: 'Pick one thing you truly want within the next four weeks, challenging but doable. Write it in three to six words, for example "run three times a week" or "have the honest talk with mum".' } },
    { h: { vi: 'Outcome: tưởng tượng kết quả', en: 'Outcome: imagine the result' }, p: { vi: 'Nhắm mắt lại và hình dung điều tốt nhất khi mong muốn ấy thành sự thật. Bạn cảm thấy gì? Ai đang ở đó? Hãy để hình ảnh ấy sống động trong một phút. Đây là phần giống với manifest thông thường.', en: 'Close your eyes and picture the best thing about that wish coming true. What do you feel? Who is there? Let the image stay vivid for a minute. This is the part that looks like ordinary manifesting.' } },
    { h: { vi: 'Obstacle: gọi tên trở ngại bên trong', en: 'Obstacle: name the inner obstacle' }, p: { vi: 'Hỏi mình: thứ gì trong chính mình hay cản mình nhất? Không phải thời tiết hay người khác, mà là thói quen, nỗi sợ hay cảm giác của bạn. Ví dụ: "mình hay nằm lướt điện thoại sau bữa tối" hay "mình sợ mẹ buồn". Nghiên cứu cho thấy bước này chính là thứ làm giấc mơ biến thành hành động.', en: 'Ask yourself: what inside me gets in the way most? Not the weather or other people, but your own habit, fear or feeling. For example "I lie on the phone after dinner" or "I am afraid of upsetting mum". Research shows this step is what turns a dream into action.' } },
    { h: { vi: 'Plan: nếu… thì…', en: 'Plan: if… then…' }, p: { vi: 'Viết một câu theo mẫu "Nếu [trở ngại] xuất hiện, thì mình sẽ [hành động]". Ví dụ: "Nếu ăn tối xong mình muốn cầm điện thoại, thì mình sẽ đi giày vào trước." Câu này nên ngắn và cụ thể đến mức bạn có thể làm ngay không cần nghĩ. Mỗi sáng đọc lại cả bốn bước trong hai phút.', en: 'Write one sentence in the form "If [obstacle] shows up, then I will [action]". For example: "If I want to grab my phone after dinner, then I will put my shoes on first." Keep it short and so concrete that you can do it without thinking. Each morning, reread all four steps in two minutes.' } }
  ] },
{ id: 'mani-vision', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Bảng tầm nhìn và cách hình dung đúng', en: 'Vision boards and visualising well' },
  intro: { vi: 'Bảng tầm nhìn là một tấm bảng hay một trang ảnh gom lại những gì bạn muốn cuộc sống mình có. Nó có tác dụng thật khi bạn dùng nó để nhắc mình hành động mỗi ngày, và mất tác dụng khi bạn chỉ ngắm nó. Tâm lý học đã chỉ ra một điều quan trọng: hình dung quá trình có ích hơn nhiều so với chỉ hình dung kết quả.', en: 'A vision board is a board or a page of pictures that gathers what you want your life to hold. It works when you use it to remind yourself to act every day, and stops working when you only look at it. Psychology has shown one important thing: picturing the process helps far more than picturing only the result.' },
  sections: [
    { h: { vi: 'Sáu góc của một cuộc sống', en: 'Six corners of a life' }, p: { vi: 'Chia bảng thành sáu ô: tình cảm, công việc và tiền, sức khỏe, gia đình và bạn bè, học hỏi, và nghỉ ngơi. Mỗi ô dán một hai hình ảnh cụ thể của chính bạn, không phải ảnh người nổi tiếng. Ô nào bạn không nghĩ ra gì để dán thì đó chính là chỗ đáng suy nghĩ nhất.', en: 'Divide the board into six boxes: love, work and money, health, family and friends, learning, and rest. In each box place one or two concrete pictures of your own life, not photos of celebrities. The box you cannot fill is the one most worth thinking about.' } },
    { h: { vi: 'Hình dung quá trình, không chỉ kết quả', en: 'Picture the process, not only the result' }, p: { vi: 'Trong một nghiên cứu nổi tiếng với sinh viên trước kỳ thi, nhóm hình dung mình đang ngồi học mỗi ngày đạt điểm cao hơn nhóm chỉ hình dung mình nhận điểm A. Vì vậy, khi nhìn bảng, hãy dành một phút hình dung chính mình đang làm công việc dẫn tới bức ảnh đó: đang gửi hồ sơ, đang tập, đang nói lời cần nói.', en: 'In a well-known study of students before an exam, the group that pictured themselves studying each day scored higher than the group that only pictured getting an A. So when you look at the board, spend a minute picturing yourself doing the work that leads to each picture: sending the application, training, saying the thing that needs saying.' } },
    { h: { vi: 'Đặt bảng ở đâu và xem khi nào', en: 'Where to keep it and when to look' }, p: { vi: 'Đặt bảng ở nơi bạn thấy mỗi sáng, hoặc làm thành ảnh nền điện thoại. Nhìn nó một phút vào buổi sáng, rồi tự hỏi: hôm nay mình làm một việc nhỏ nào cho ô nào? Cứ ba tháng, gỡ những gì không còn đúng và dán thêm cái mới.', en: 'Keep the board where you see it every morning, or make it your phone wallpaper. Look at it for a minute in the morning, then ask: which small thing do I do today, for which box? Every three months, take down what no longer fits and add what is new.' } }
  ] },
{ id: 'mani-moon', cat: 'manifest', badge: 'conv', tags: ['manifest', 'astro'],
  title: { vi: 'Manifest theo trăng', en: 'Manifesting with the Moon' },
  intro: { vi: 'Nhiều người thích gắn việc manifest với chu kỳ Mặt Trăng, vì nó cho bạn một nhịp đều đặn: mỗi tháng có một lúc để gieo và một lúc để buông. Trăng non là lúc đặt ý định. Trăng tròn là lúc nhìn lại và buông bỏ những gì không còn hợp. Ứng dụng luôn hiển thị kỳ trăng hôm nay ở trang chủ.', en: 'Many people like to tie manifesting to the cycle of the Moon, because it gives a steady rhythm: every month has a time to plant and a time to let go. The new Moon is for setting intentions. The full Moon is for looking back and releasing what no longer fits. The app shows the current Moon phase on the home screen.' },
  sections: [
    { h: { vi: 'Nghi thức trăng non', en: 'The new Moon ritual' }, p: { vi: 'Chọn một buổi tối yên tĩnh trong ba ngày quanh trăng non. Thắp một ngọn nến hay chỉ cần tắt bớt đèn. Viết tối đa ba ý định cho tháng tới, mỗi ý định là một câu ở thì hiện tại và có hành động đi kèm. Đọc to lên một lần, gấp tờ giấy lại và để ở nơi bạn thấy hằng ngày.', en: 'Choose a quiet evening within three days of the new Moon. Light a candle, or simply dim the lights. Write at most three intentions for the coming month, each one sentence in the present tense with an action attached. Read them aloud once, fold the paper, and keep it where you see it daily.' } },
    { h: { vi: 'Nghi thức trăng tròn', en: 'The full Moon ritual' }, p: { vi: 'Hai tuần sau, vào đêm trăng tròn, mở tờ giấy ra và đọc lại. Ghi bên cạnh mỗi ý định: đã làm được gì, đã học được gì. Rồi viết ra một điều bạn muốn buông, chẳng hạn một thói quen, một nỗi lo hay một mối bận tâm. Xé tờ giấy buông bỏ ấy, hoặc gạch đi thật đậm. Việc này đơn giản nhưng làm đầu óc nhẹ đi rõ rệt.', en: 'Two weeks later, on the full Moon night, unfold the paper and reread it. Next to each intention, write what you did and what you learned. Then write one thing you want to release, such as a habit, a worry or a preoccupation. Tear up that release note, or cross it out heavily. It is simple, and it visibly lightens the mind.' } },
    { h: { vi: 'Nếu bạn bận', en: 'If you are busy' }, p: { vi: 'Không cần nến, không cần pha lê, không cần đúng giờ. Điều làm nên tác dụng là bạn ngồi xuống đều đặn hai lần mỗi tháng để nhìn lại đời mình. Mặt Trăng chỉ là cái lịch đẹp để nhắc bạn làm điều đó.', en: 'No candle, no crystals, no exact hour needed. What creates the effect is sitting down twice a month, reliably, to look at your life. The Moon is simply a beautiful calendar that reminds you to do it.' } }
  ] },
{ id: 'mani-action', cat: 'manifest', badge: 'conv', tags: ['manifest', 'work'],
  title: { vi: 'Từ ý định đến hành động', en: 'From intention to action' },
  intro: { vi: 'Khoảng cách lớn nhất trong manifest không nằm giữa bạn và vũ trụ, mà nằm giữa ý định và việc làm đầu tiên. Ba công cụ dưới đây đến từ tâm lý học về thói quen và được kiểm chứng ở hàng trăm nghiên cứu: kế hoạch "nếu thì", bước hai phút, và chuỗi ngày.', en: 'The widest gap in manifesting is not between you and the universe; it is between the intention and the first act. The three tools below come from the psychology of habits and have been tested in hundreds of studies: the if-then plan, the two-minute step, and the streak.' },
  sections: [
    { h: { vi: 'Kế hoạch "nếu… thì…"', en: 'The if-then plan' }, p: { vi: 'Gắn hành động vào một thời điểm hoặc một tình huống cụ thể: "Nếu là 7 giờ sáng thứ Hai, thì mình mở hồ sơ xin việc." Người có kế hoạch kiểu này làm được điều mình định gấp hai đến ba lần so với người chỉ có mục tiêu chung chung. Lý do là bạn quyết định trước, nên đến lúc đó không cần lấy ý chí ra nữa.', en: 'Tie the action to a specific time or situation: "If it is 7 a.m. on Monday, then I open the job application." People with plans like this follow through two to three times more often than people with only a general goal. The reason is that the decision was made in advance, so no willpower is needed in the moment.' } },
    { h: { vi: 'Bước hai phút', en: 'The two-minute step' }, p: { vi: 'Thu nhỏ việc đầu tiên đến mức chỉ mất hai phút: không phải "viết sách" mà là "mở tệp và viết một câu"; không phải "tập gym" mà là "thay đồ tập". Việc bắt đầu là phần khó nhất, và khi đã bắt đầu, bạn thường làm nhiều hơn dự định.', en: 'Shrink the first act until it takes two minutes: not "write the book" but "open the file and write one sentence"; not "go to the gym" but "change into gym clothes". Starting is the hardest part, and once started you usually do more than planned.' } },
    { h: { vi: 'Chuỗi ngày và cách không đứt chuỗi', en: 'The streak, and how not to break it' }, p: { vi: 'Đánh dấu mỗi ngày bạn làm việc nhỏ ấy. Một chuỗi mười ngày tự nó tạo động lực để có ngày thứ mười một. Quy tắc duy nhất: không bao giờ bỏ hai ngày liên tiếp. Bỏ một ngày là chuyện bình thường; bỏ hai ngày là bắt đầu một thói quen mới theo hướng ngược lại.', en: 'Mark every day you do the small act. A ten-day streak creates its own pull toward day eleven. The one rule: never miss two days in a row. Missing one day is normal; missing two is the start of a new habit in the wrong direction.' } }
  ] },
{ id: 'mani-letgo', cat: 'manifest', badge: 'conv', tags: ['manifest', 'love'],
  title: { vi: 'Buông bỏ và không bám víu', en: 'Letting go and not clinging' },
  intro: { vi: 'Trong hầu hết các trường phái manifest đều có lời khuyên "đặt ý định rồi buông". Nghe có vẻ mâu thuẫn, nhưng nó có lý: khi bạn kiểm tra kết quả mỗi giờ, bạn sống trong thiếu thốn và lo âu, và chính sự lo âu ấy làm bạn hành động vụng về. Buông không phải là bỏ cuộc. Buông là làm phần việc của mình rồi để phần còn lại diễn ra.', en: 'Almost every school of manifesting gives the advice "set the intention, then let go". It sounds contradictory, but it makes sense: when you check for results every hour, you live in lack and anxiety, and that anxiety makes you act clumsily. Letting go is not giving up. It is doing your part and letting the rest unfold.' },
  sections: [
    { h: { vi: 'Ba dấu hiệu bạn đang bám víu', en: 'Three signs you are clinging' }, p: { vi: 'Bạn xem điện thoại liên tục để chờ một tin nhắn. Bạn đọc lại câu khẳng định với cảm giác sợ hãi thay vì nhẹ nhõm. Bạn đặt hạnh phúc của mình vào một người hay một ngày cụ thể. Khi thấy những dấu hiệu này, hãy dừng lại và hít thở ba hơi thật chậm.', en: 'You check your phone constantly waiting for one message. You reread your affirmation with fear instead of relief. You place your happiness on one person or one specific date. When you notice these signs, stop and take three slow breaths.' } },
    { h: { vi: 'Cách buông trong thực tế', en: 'How to let go in practice' }, p: { vi: 'Viết mong muốn ra giấy rồi cất đi, và chỉ mở lại mỗi tuần một lần. Thay hành động chờ đợi bằng một hành động khác có ích: đi bộ, gặp bạn, làm việc. Nhắc mình một câu ngắn: "Mình đã làm phần của mình." Và giữ cho cuộc sống của bạn đầy đủ ngay cả khi điều ấy chưa đến.', en: 'Write the wish down and put it away, opening it only once a week. Replace waiting with another useful action: a walk, a friend, work. Remind yourself with one short line: "I have done my part." And keep your life full even before it arrives.' } },
    { h: { vi: 'Khi điều bạn muốn không đến', en: 'When what you want does not come' }, p: { vi: 'Đôi khi điều ấy không đến, và đó không phải lỗi của bạn hay của "rung động". Hãy hỏi ba câu: mình đã học được gì, mình muốn giữ lại điều gì từ trải nghiệm này, và mong muốn tiếp theo của mình là gì. Người manifest giỏi không phải người luôn có được thứ mình muốn, mà là người luôn biết rõ mình muốn gì tiếp theo.', en: 'Sometimes it does not come, and that is not your fault or a matter of "vibration". Ask three questions: what did I learn, what do I want to keep from this experience, and what is my next wish. A good manifester is not someone who always gets what they want, but someone who always knows what they want next.' } }
  ] },
{ id: 'mani-limits', cat: 'manifest', badge: 'own', tags: ['manifest'],
  title: { vi: 'Giới hạn và sự thật thà', en: 'Limits and honesty' },
  intro: { vi: 'Nabu không hứa rằng manifestation làm được mọi thứ. Theo cách Nabu nhìn, đây là một công cụ giúp bạn biết rõ mình muốn gì và can đảm hơn để đi lấy nó. Bảng dưới đây giúp bạn tự kiểm tra xem mình đang dùng nó đúng hay sai.', en: 'Nabu does not promise that manifestation can do everything. The way Nabu sees it, it is a tool that helps you know what you want and be braver about going for it. The checklist below helps you see whether you are using it well or badly.' },
  sections: [
    { h: { vi: 'Dấu hiệu bạn đang dùng sai', en: 'Signs you are using it badly' }, p: { vi: 'Bạn chờ đợi thay vì hành động. Bạn tự trách mình mỗi khi chuyện xấu xảy ra. Bạn tiêu tiền vào những khóa học hứa hẹn một "bí mật". Bạn tránh đi bác sĩ hoặc tránh những cuộc nói chuyện thẳng thắn vì sợ "hút năng lượng xấu".', en: 'You wait instead of acting. You blame yourself whenever something bad happens. You spend money on courses that promise a "secret". You avoid the doctor, or avoid honest conversations, for fear of "attracting bad energy".' } },
    { h: { vi: 'Dấu hiệu bạn đang dùng đúng', en: 'Signs you are using it well' }, p: { vi: 'Bạn thấy rõ hơn mình muốn gì. Bạn dám mở lời hơn trước. Bạn bớt sợ hãi. Và bạn vẫn làm việc, vẫn đi khám, vẫn tiết kiệm như bình thường. Manifestation là thứ được thêm vào cuộc sống của bạn, chứ không thay thế nó.', en: 'You are clearer about what you want. You speak up more than before. You are less afraid. And you still work, still see the doctor, still save money as usual. Manifestation is something added to your life, not something that replaces it.' } }
  ] },

/* ---------------------------------------------------------- fortune ---- */
{ id: 'mani-tools', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Nến, đá và màu sắc: dùng sao cho đúng', en: 'Candles, stones and colours: using them well' },
  intro: { vi: 'Nến và đá không có phép màu, và mọi nguồn nghiêm túc đều nói vậy. Chúng có ích theo một cách rất người: một ngọn nến thắp lên là một tín hiệu "bây giờ mình tập trung", một viên đá trong túi là một lời nhắc nhỏ về điều mình đã chọn. Bảng dưới là các tương ứng truyền thống được nhiều người dùng chung; hãy xem chúng như ngôn ngữ biểu tượng, không phải lời hứa.', en: 'Candles and stones have no magic, and every serious source says so. They help in a very human way: a lit candle is a signal that says "now I focus", a stone in the pocket is a small reminder of what you chose. The table below lists the traditional correspondences most people share; treat them as a language of symbols, not a promise.' },
  sections: [
    { h: { vi: 'Nến theo màu', en: 'Candles by colour' }, p: { vi: 'Trắng dùng cho mọi ý định và để làm sạch. Xanh lá cho tiền bạc và phát triển. Hồng cho tình yêu và yêu bản thân. Đỏ cho đam mê và dũng khí. Vàng cho thành công và tự tin. Tím cho trực giác và đời sống tinh thần. Xanh dương cho bình an, chữa lành và giao tiếp. Cam cho sáng tạo. Đen cho bảo vệ và buông bỏ. Không có nến đúng màu thì nến trắng thay được tất cả.', en: 'White for any intention and for cleansing. Green for money and growth. Pink for love and self-love. Red for passion and courage. Yellow for success and confidence. Purple for intuition and spiritual life. Blue for calm, healing and communication. Orange for creativity. Black for protection and release. Without the right colour, a white candle stands in for all of them.' } },
    { h: { vi: 'Đá theo mục đích', en: 'Stones by purpose' }, p: { vi: 'Thạch anh hồng cho tình yêu và dịu dàng với chính mình. Citrine cho sung túc và niềm vui. Thạch anh trắng để khuếch đại và làm rõ ý định. Thạch anh tím cho bình tĩnh và trực giác. Aventurine xanh cho may mắn và cơ hội mới. Pyrite cho tiền bạc và ý chí. Tourmaline đen cho bảo vệ. Selenite để làm sạch các viên khác. Carnelian cho năng lượng và can đảm. Đá mặt trăng cho khởi đầu mới. Một viên bạn thích cầm còn hơn mười viên mua theo danh sách.', en: 'Rose quartz for love and gentleness with yourself. Citrine for abundance and joy. Clear quartz to amplify and clarify an intention. Amethyst for calm and intuition. Green aventurine for luck and new chances. Pyrite for money and will. Black tourmaline for protection. Selenite to cleanse the others. Carnelian for energy and courage. Moonstone for new beginnings. One stone you like to hold beats ten bought from a list.' } },
    { h: { vi: 'Một nghi thức nhỏ, đủ dùng', en: 'A small ritual that is enough' }, p: { vi: 'Viết ý định ra một dòng, ở thì hiện tại. Thắp nến, cầm viên đá, đọc dòng ấy ba lần chậm rãi. Ngồi thêm hai phút hình dung mình đang làm bước đầu tiên. Tắt nến, cất đá vào túi hoặc bàn làm việc. Nghi thức có tác dụng vì nó lặp lại, không phải vì nó dài; năm phút mỗi tối trong một tháng hơn hẳn một buổi lễ lớn một lần.', en: 'Write the intention in one line, in the present tense. Light the candle, hold the stone, read the line three times slowly. Sit two more minutes picturing yourself doing the first step. Put the candle out, keep the stone in a pocket or on your desk. A ritual works because it repeats, not because it is long; five minutes each evening for a month beats one big ceremony.' } },
    { h: { vi: 'An toàn và thật thà', en: 'Safety and honesty' }, p: { vi: 'Không bao giờ để nến cháy khi rời khỏi phòng hay đi ngủ, và để xa rèm, giấy, tóc. Rửa đá bằng nước sạch; một số đá như selenite và malachite không chịu nước, chỉ lau khô. Không có viên đá nào thay được bác sĩ, thuốc hay một cuộc trò chuyện khó. Nếu ai bán cho bạn "đá chữa bệnh", hãy giữ tiền lại.', en: 'Never leave a candle burning when you leave the room or go to sleep, and keep it away from curtains, paper and hair. Rinse stones with clean water; some, like selenite and malachite, do not take water and should only be wiped. No stone replaces a doctor, medicine or a hard conversation. If someone sells you a "healing stone", keep your money.' } }
  ] },

{ id: 'fort-numerology', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Thần số học: số đường đời', en: 'Numerology: your life path number' },
  intro: { vi: 'Số đường đời được tính từ ngày sinh của bạn. Bạn cộng các chữ số của ngày, tháng và năm cho đến khi còn một chữ số, nhưng giữ nguyên các số 11, 22 và 33. Ứng dụng sẽ tính sẵn cho bạn ở mục Tôi.', en: 'Your life path number comes from your date of birth. You add the digits of the day, the month and the year until a single digit remains, keeping 11, 22 and 33 as they are. The app works it out for you under Me.' },
  sections: [
    { h: { vi: 'Cách tính', en: 'How to count' }, p: { vi: 'Giả sử bạn sinh ngày 12 tháng 3 năm 1995. Ngày là 1 cộng 2 bằng 3. Tháng là 3. Năm là 1 cộng 9 cộng 9 cộng 5 bằng 24, rút gọn thành 2 cộng 4 bằng 6. Cộng ba kết quả lại, ta được 3 cộng 3 cộng 6 bằng 12, rút gọn thành 3. Vậy số đường đời của bạn là 3. Riêng tháng 11 và các ngày 11, 22 thì giữ nguyên, không rút gọn.', en: 'Suppose you were born on 12 March 1995. The day is 1 plus 2, which gives 3. The month is 3. The year is 1 plus 9 plus 9 plus 5, which gives 24, reduced to 2 plus 4, which gives 6. Add the three results and you get 3 plus 3 plus 6, which is 12, reduced to 3. So your life path is 3. Month 11 and days 11 and 22 stay as they are and are not reduced.' } },
    { h: { vi: 'Đọc con số thế nào', en: 'How to read the number' }, p: { vi: 'Hãy xem con số như một chủ đề xuyên suốt cuộc đời bạn, chứ không phải một bản án. Số 1 học cách tự lập, số 2 học cách hợp tác, số 7 học cách tin người. Các số bậc thầy 11, 22 và 33 mang bài học của số rút gọn tương ứng là 2, 4 và 6, nhưng với áp lực lớn hơn.', en: 'Treat the number as a theme running through your life, not as a verdict. A 1 learns independence, a 2 learns cooperation, a 7 learns to trust people. The master numbers 11, 22 and 33 carry the lessons of their reduced digits, 2, 4 and 6, but with greater pressure.' } },
    { h: { vi: 'Nên hiểu nó ra sao', en: 'How to hold it' }, p: { vi: 'Thần số học hiện đại ra đời vào đầu thế kỷ hai mươi, dựa trên ý tưởng gán số cho chữ cái có từ thời Pythagoras. Chưa có nghiên cứu nào chứng minh rằng nó dự đoán được đời người, nên bạn hãy dùng nó như một tấm gương để suy nghĩ về chính mình.', en: 'Modern numerology arose in the early twentieth century, built on the Pythagorean idea of giving numbers to letters. No study has shown that it predicts a life, so use it as a mirror for thinking about yourself.' } }
  ] },
{ id: 'fort-palm', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Xem chỉ tay từ đầu', en: 'Palm reading from the start' },
  intro: { vi: 'Xem chỉ tay là đọc tính cách và những khuynh hướng của một người từ hình dáng bàn tay, các đường và các gò trên lòng bàn tay. Cách xem phổ biến ở phương Tây đi theo một thứ tự rõ ràng: nhìn hình dáng tay trước, rồi ba đường chính, rồi các đường phụ, và cuối cùng là các gò. Bài này đi đúng thứ tự đó.', en: 'Palm reading means reading character and tendencies from the shape of the hand, the lines and the mounts of the palm. The common Western way follows a clear order: look at the hand shape first, then the three major lines, then the minor lines, and finally the mounts. This guide follows that order.' },
  sections: [
    { h: { vi: 'Xem tay nào', en: 'Which hand to read' }, p: { vi: 'Tay thuận cho biết con người hiện tại của bạn: những gì bạn đã làm với những điều mình có. Tay còn lại cho biết những gì bạn mang theo từ khi sinh ra: khuynh hướng, tiềm năng, những điều chưa được dùng đến. Khi hai tay rất khác nhau, đó là dấu hiệu bạn đã tự thay đổi mình nhiều. Hãy xem cả hai tay và so sánh.', en: 'The dominant hand shows who you are now: what you have done with what you were given. The other hand shows what you were born with: tendencies, potential, things not yet used. When the two hands differ a lot, you have changed yourself a great deal. Read both hands and compare.' } },
    { h: { vi: 'Bốn hình dáng tay', en: 'The four hand shapes' }, p: { vi: 'Nhìn lòng bàn tay vuông hay dài, và ngón tay ngắn hay dài so với lòng bàn tay. Tay Đất có lòng bàn tay vuông và ngón ngắn: thực tế, chắc chắn. Tay Khí có lòng bàn tay vuông và ngón dài: hay nghĩ, hay nói. Tay Lửa có lòng bàn tay dài và ngón ngắn: nhiệt tình, thích dẫn đầu. Tay Nước có lòng bàn tay dài và ngón dài: nhạy cảm, giàu trực giác. Hình dáng tay là nền để hiểu mọi thứ còn lại; ví dụ một đường tim cong trên tay Nước sẽ nói về cảm xúc mạnh hơn nhiều so với trên tay Đất.', en: 'Look at whether the palm is square or long, and whether the fingers are short or long compared with the palm. The Earth hand has a square palm and short fingers: practical, solid. The Air hand has a square palm and long fingers: thoughtful, talkative. The Fire hand has a long palm and short fingers: enthusiastic, likes to lead. The Water hand has a long palm and long fingers: sensitive, intuitive. The shape is the base for everything else; a curved heart line on a Water hand speaks of far stronger feelings than the same line on an Earth hand.' } },
    { h: { vi: 'Ba đường chính', en: 'The three major lines' }, p: { vi: 'Đường tim nằm trên cùng và nói về tình cảm. Đường trí nằm giữa và nói về cách bạn nghĩ. Đường sinh mệnh vòng quanh gốc ngón cái và nói về sức sống, không phải tuổi thọ. Với mỗi đường, bạn xem ba điều: đường dài hay ngắn, sâu hay mờ, và điểm bắt đầu cùng điểm kết thúc nằm ở đâu. Trên bản đồ bàn tay của ứng dụng, chạm vào từng đường để đọc các cách hiểu thường gặp.', en: 'The heart line sits at the top and speaks of feelings. The head line runs through the middle and speaks of how you think. The life line curves around the thumb and speaks of vitality, not lifespan. For each line, check three things: long or short, deep or faint, and where it begins and ends. On the palm map in the app, tap each line to read the common interpretations.' } },
    { h: { vi: 'Các đường phụ', en: 'The minor lines' }, p: { vi: 'Không phải ai cũng có đủ các đường này, và thiếu một đường không phải là điều xấu. Đường sự nghiệp chạy dọc giữa bàn tay và nói về con đường công việc. Đường mặt trời hướng lên ngón áp út và nói về sáng tạo, sự công nhận. Đường sức khỏe chạy chéo lên gò ngón út và nói về sức khỏe, việc làm ăn. Các đường hôn nhân là những vạch ngắn ở cạnh bàn tay dưới ngón út và nói về những mối quan hệ sâu sắc. Ngoài ra còn có vòng Kim Tinh, một đường cong nhỏ phía trên đường tim, cho thấy người rất nhạy cảm; và các vòng cổ tay, theo cách xem cũ là dấu hiệu của sức khỏe và may mắn.', en: 'Not everyone has all of these, and missing one is not a bad sign. The fate line runs up the middle of the palm and speaks of the work path. The Sun line points to the ring finger and speaks of creativity and recognition. The health line runs diagonally to the little-finger mount and speaks of health and business. The marriage lines are short marks on the edge of the palm under the little finger and speak of deep relationships. There is also the girdle of Venus, a small curve above the heart line that shows a very sensitive person, and the bracelets at the wrist, which the old reading takes as signs of health and luck.' } },
    { h: { vi: 'Các gò trên bàn tay', en: 'The mounts of the palm' }, p: { vi: 'Gò là những phần đầy lên của lòng bàn tay, mỗi gò mang tên một hành tinh. Dưới bốn ngón là gò Mộc Tinh (tham vọng), gò Thổ Tinh (kỷ luật), gò Thái Dương (sáng tạo) và gò Thủy Tinh (giao tiếp). Gốc ngón cái là gò Kim Tinh (tình cảm, sức sống). Cạnh ngoài phía dưới là gò Mặt Trăng (trí tưởng tượng). Giữa gốc ngón cái và ngón trỏ là gò Hỏa Tinh (can đảm). Gò đầy đặn nghĩa là phẩm chất đó mạnh; gò phẳng nghĩa là nó yếu hơn; gò quá cao nghĩa là phẩm chất đó đang lấn át. Trong ứng dụng, bấm "Các gò" trên bản đồ bàn tay để chạm vào từng gò.', en: 'Mounts are the fleshy pads of the palm, each named after a planet. Under the four fingers sit the mounts of Jupiter (ambition), Saturn (discipline), Apollo (creativity) and Mercury (communication). The base of the thumb is the mount of Venus (affection, vitality). The outer lower edge is the mount of the Moon (imagination). Between the thumb and the index finger is the mount of Mars (courage). A full mount means the quality is strong; a flat one means it is weaker; an over-high one means it dominates. In the app, press "Mounts" on the palm map to tap each one.' } },
    { h: { vi: 'Các dấu hiệu nhỏ trên đường', en: 'Small marks on the lines' }, p: { vi: 'Chuỗi mắt xích trên một đường cho thấy giai đoạn năng lượng bị phân tán. Đảo nhỏ, tức một đoạn đường tách đôi rồi nhập lại, thường được đọc là một thời kỳ khó khăn ở lĩnh vực của đường đó. Chỗ đứt là một thay đổi lớn. Chẻ nhánh ở cuối đường nghĩa là năng lượng chia ra nhiều hướng. Hình sao là một sự kiện bất ngờ, hình chữ thập là một trở ngại, còn hình vuông bao quanh chỗ đứt được xem là dấu bảo vệ. Hãy đọc những dấu này một cách nhẹ nhàng: bàn tay thay đổi theo năm tháng, và đường nét hôm nay không phải bản án.', en: 'A chain on a line shows a period of scattered energy. An island, where the line splits and rejoins, is usually read as a hard stretch in the area that line covers. A break is a big change. A fork at the end means the energy divides into several directions. A star is an unexpected event, a cross an obstacle, and a square around a break is taken as a sign of protection. Read these marks gently: hands change over the years, and what is there today is not a sentence.' } },
    { h: { vi: 'Một lần xem gồm những bước nào', en: 'The steps of a reading' }, p: { vi: 'Bước một: cầm cả hai tay, nhìn hình dáng và độ mềm cứng. Bước hai: nhìn tay không thuận để hiểu nền tảng, rồi tay thuận để hiểu hiện tại. Bước ba: đọc ba đường chính, từ đường tim xuống đường sinh mệnh. Bước bốn: đọc các đường phụ có mặt, bỏ qua những đường không có. Bước năm: nhìn các gò nổi nhất, và ghép tất cả thành một câu chuyện ngắn về con người ấy. Người xem tay lâu năm luôn nói ít hơn những gì họ thấy, và không bao giờ nói về bệnh tật hay cái chết.', en: 'Step one: hold both hands, look at the shape and the firmness. Step two: read the non-dominant hand for the base, then the dominant hand for the present. Step three: read the three major lines, from the heart line down to the life line. Step four: read whichever minor lines are present, and skip the ones that are not. Step five: look at the fullest mounts, and bring everything together into a short story about the person. Experienced readers always say less than they see, and never speak of illness or death.' } },
    { h: { vi: 'Nên hiểu nó ra sao', en: 'How to hold it' }, p: { vi: 'Xem chỉ tay đã có ở Ấn Độ, Trung Quốc và châu Âu từ hàng nghìn năm, và mỗi nơi có cách xem riêng. Cách được mô tả ở đây là cách phổ biến ở phương Tây. Chưa có bằng chứng khoa học cho nó, vì vậy bạn hãy xem đây như một cuộc trò chuyện thú vị về tính cách, không phải một lời tiên tri.', en: 'Palm reading has existed in India, China and Europe for thousands of years, and each place has its own rules. The version described here is the common Western one. There is no scientific evidence for it, so treat it as an enjoyable conversation about character, not a prophecy.' } }
  ] },
{ id: 'fort-playing', cat: 'fortune', badge: 'conv', tags: ['fortune', 'tarot'],
  title: { vi: 'Bói bài Tây 52 lá', en: 'Reading with playing cards' },
  intro: { vi: 'Bài Tây và tarot có chung một gốc: cả hai đều lớn lên từ bộ bài bốn chất du nhập vào châu Âu ở thế kỷ 14. Tarot ra đời ở Ý vào thế kỷ 15 khi người ta thêm 22 lá bài chủ vào bộ bốn chất ấy, và những lá chủ đó về sau trở thành Ẩn Chính. Vì vậy 52 lá bài Tây gần như trùng với 56 lá Ẩn Phụ của tarot, chỉ thiếu một lá hình ở mỗi chất. Nhưng bói bài Tây không chỉ là tarot rút gọn: giới xem bài đã có bộ nghĩa truyền thống riêng cho 52 lá từ hàng trăm năm, và đây mới là cách hầu hết người bói bài Tây vẫn dùng.', en: 'Playing cards and tarot share one root: both grew out of the four-suit deck that reached Europe in the 14th century. Tarot appeared in Italy in the 15th century when 22 trump cards were added to that four-suit deck, and those trumps later became the Majors. So the 52 playing cards line up almost exactly with the 56 tarot Minors, missing only one court card per suit. Yet reading playing cards is not just tarot shortened: fortune tellers have had their own traditional meanings for the 52 cards for hundreds of years, and that is still how most playing-card readers work.' },
  sections: [
    { h: { vi: 'Hai cách đọc, nên chọn cách nào', en: 'Two ways to read, which to choose' }, p: { vi: 'Theo cách truyền thống, mỗi lá có một nghĩa riêng, ví dụ Chín Cơ là lá ước nguyện, Át Bích là kết thúc, Mười Rô là tiền bạc và một chuyến đi. Theo cách của tarot, bạn đọc lá bài Tây bằng nghĩa của lá Ẩn Phụ cùng chất cùng số. Cả hai cách đều được những người đọc bài lâu năm công nhận, nhưng họ khuyên một điều: bạn hãy chọn một cách và dùng nhất quán trong cả trải bài, và không trộn hai bộ nghĩa trong cùng một lần xem. Nếu bạn đã học tarot, cách thứ hai giúp bạn bắt đầu ngay; nếu bạn muốn học đúng truyền thống bói bài Tây, bạn hãy học bộ nghĩa riêng.', en: 'The traditional way: every card carries its own meaning, for example the Nine of Hearts is the wish card, the Ace of Spades an ending, the Ten of Diamonds money and a journey. The tarot way: read each playing card with the meaning of the Minor of the same suit and number. Experienced readers accept both, but they give one piece of advice: pick one way and use it consistently through a whole spread, never mixing the two sets of meanings in one reading. If you already know tarot, the second way lets you start at once; if you want the true playing-card tradition, learn its own meanings.' } },
    { h: { vi: 'Bốn chất', en: 'The four suits' }, p: { vi: 'Cơ nói về tình cảm, gia đình và những gì bạn yêu; tương ứng với Cốc. Rô nói về tiền bạc, công việc và tin tức; tương ứng với Tiền. Chuồn nói về hành động, kế hoạch và bạn bè; tương ứng với Gậy. Bích nói về khó khăn, lo lắng và những lời cảnh báo; tương ứng với Kiếm. Hầu hết người đọc bài, dù theo cách nào, đều bắt đầu bằng việc thuộc bốn chất này trước.', en: 'Hearts speak of love, family and what you care for; they match Cups. Diamonds speak of money, work and news; they match Pentacles. Clubs speak of action, plans and friends; they match Wands. Spades speak of trouble, worry and warnings; they match Swords. Whichever way they read, most readers begin by learning these four suits by heart.' } },
    { h: { vi: 'Số và lá hình', en: 'Numbers and court cards' }, p: { vi: 'Át là khởi đầu của chất, các lá từ Hai đến Mười kể một câu chuyện từ mở đầu tới trọn vẹn, và Mười là kết quả đầy đủ. Ba lá hình chỉ người: J là người trẻ hoặc một tin tức, Q là người phụ nữ, K là người đàn ông hoặc người có quyền. Trong bộ nghĩa truyền thống, màu của lá hình cũng gợi ý ngoại hình hoặc tính cách: lá đỏ chỉ người tóc sáng hay tính ấm áp, lá đen chỉ người tóc sẫm hay tính nghiêm nghị.', en: 'The Ace begins a suit, Two to Ten tell a story from start to completion, and the Ten is the full result. The three court cards stand for people: the Jack is a young person or a piece of news, the Queen a woman, the King a man or someone in authority. In the traditional meanings the colour of a court card also hints at looks or temperament: red cards for fair or warm people, black cards for dark or stern ones.' } },
    { h: { vi: 'Cách học được người đọc bài lâu năm khuyên', en: 'How experienced readers suggest learning' }, p: { vi: 'Bước một: bạn thuộc bốn chất và câu chuyện từ Át tới Mười, vì với hai điều này bạn đã đoán được nghĩa gần đúng của mọi lá. Bước hai: bạn học riêng mười hai lá hình như mười hai con người. Bước ba: bạn học những lá đặc biệt của bộ nghĩa truyền thống, như Chín Cơ, Át Bích, Chín Bích, Mười Rô. Bước bốn: bạn tập trải ba lá cho một câu hỏi rồi mới tăng dần, và bạn ghi lại từng lần xem để so với thực tế. Bước năm: bạn tập đọc cặp lá, vì trong bói bài Tây lá bên cạnh đổi nghĩa của lá đứng giữa, giống như trong Lenormand.', en: 'Step one: learn the four suits and the Ace-to-Ten story, because with those two things you can already guess a fair meaning for every card. Step two: learn the twelve court cards as twelve people. Step three: learn the special cards of the traditional set, such as the Nine of Hearts, the Ace of Spades, the Nine of Spades and the Ten of Diamonds. Step four: practise three-card readings for one question before you grow the spread, and write each reading down to compare with what happens. Step five: practise pairs, because in playing-card reading the neighbouring card changes the card in the middle, just as in Lenormand.' } },
    { h: { vi: 'Lenormand dùng bài Tây ra sao', en: 'How Lenormand uses playing cards' }, p: { vi: 'Mỗi lá Lenormand đều in kèm một lá bài Tây từ bộ 36 lá, từ Sáu đến Át. Đó là tương ứng thật sự duy nhất của Lenormand, và nó đã có trên bài từ năm 1799. Bộ 36 lá này cũng là bộ mà nhiều người bói bài Tây ở châu Âu dùng thay cho bộ 52 lá.', en: 'Every Lenormand card carries a playing card from the 36-card pack, from Six to Ace. That is Lenormand\'s only real correspondence, and it has been printed on the cards since 1799. The same 36-card pack is what many European playing-card readers use instead of the full 52.' } },
    { h: { vi: 'Bói bài Tây nhìn được bao lâu', en: 'How long a playing-card reading holds' }, p: { vi: 'Bói bài Tây theo lối truyền thống thường được xem là nói về vài tuần tới khoảng ba tháng, giống tarot. Không có quy ước thời gian nào được mọi sách đồng ý: có người đọc Cơ và Rô là chuyện đến nhanh, Chuồn và Bích là chuyện chậm hơn; có người lấy số trên lá làm số ngày hay tuần. Cách an toàn mà người đọc lâu năm khuyên là tự chốt khung thời gian ngay trước khi xào, ví dụ "bài này cho tháng tới", rồi đọc mọi lá trong khung ấy, và xem lại khi khung ấy đã qua.', en: 'A traditional playing-card reading is usually taken to cover the next few weeks to about three months, much like tarot. No timing convention is shared by every book: some readers take Hearts and Diamonds as fast and Clubs and Spades as slower, others read the number on a card as days or weeks. The safe habit experienced readers suggest is to fix the time frame just before you shuffle, for example "this reading is for the coming month", read every card inside it, and read again once that window has passed.' } }
  ] },
{ id: 'fort-animals', cat: 'fortune', badge: 'doc', tags: ['fortune', 'astro'],
  title: { vi: '12 con giáp', en: 'The 12 zodiac animals' },
  intro: { vi: 'Mỗi năm âm lịch mang tên một con giáp, và vòng con giáp lặp lại sau mười hai năm. Ứng dụng tính con giáp của bạn theo năm sinh ở mục Tôi, còn vòng con giáp đầy đủ nằm trong phần Bói toán.', en: 'Each lunar year carries the name of an animal, and the cycle repeats every twelve years. The app works out your animal from your birth year under Me, and the full wheel lives in the Fortune telling section.' },
  sections: [
    { h: { vi: 'Lưu ý về Tết', en: 'A note about Tết' }, p: { vi: 'Năm con giáp bắt đầu từ Tết chứ không phải từ ngày 1 tháng 1. Vì vậy, nếu bạn sinh vào tháng 1 hoặc đầu tháng 2, bạn có thể thuộc con giáp của năm trước. Ứng dụng tính theo năm dương, nên bạn hãy kiểm tra lại nếu sinh trước Tết.', en: 'The animal year begins at Lunar New Year, not on 1 January. So if you were born in January or early February, you may belong to the previous year\'s animal. The app counts by the calendar year, so double-check if you were born before Tết.' } },
    { h: { vi: 'Tam hợp và tứ hành xung', en: 'Trios and clashes' }, p: { vi: 'Theo truyền thống, mười hai con giáp chia thành bốn nhóm tam hợp, là những bộ ba dễ hợp nhau, và ba nhóm tứ hành xung, là những bộ bốn dễ va chạm. Đây là chuyện tính cách chung và "hợp tuổi" trong văn hóa, chứ không phải khoa học. Bạn đừng để chuyện "khắc tuổi" quyết định hôn nhân thay cho hai người trong cuộc.', en: 'By tradition, the twelve animals form four trios that get on easily, and three groups of four that tend to clash. This is about general character and cultural "compatibility", not science. Do not let a "clashing year" decide a marriage instead of the two people involved.' } },
    { h: { vi: 'Tử vi thì khác', en: 'Tử vi is something else' }, p: { vi: 'Tử vi đẩu số cần giờ sinh và lập một lá số gồm mười hai cung với hơn một trăm sao. Đó là một hệ thống riêng và sâu hơn con giáp rất nhiều. Nabu xem tử vi trong buổi hẹn riêng, chứ không tính trong ứng dụng này.', en: 'Tử vi, Vietnamese astrology, needs the hour of birth and builds a chart of twelve palaces with more than a hundred stars. It is a separate and much deeper system than the animals. Nabu reads tử vi in a private session, not inside this app.' } }
  ] },
{ id: 'fort-tea', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Bài trà', en: 'Tealeaf fortune telling' },
  intro: { vi: 'Bạn uống một tách trà lá cho đến gần cạn, xoay tách ba vòng, úp lên đĩa, rồi nhìn những hình mà lá trà để lại trong lòng tách. Cách xem này đến từ châu Âu thế kỷ mười bảy, khi trà mới được đưa sang từ Trung Quốc.', en: 'You drink a cup of loose-leaf tea almost to the bottom, swirl it three times, turn it over onto the saucer, then look at the shapes the leaves have left inside. The practice comes from seventeenth-century Europe, when tea had just arrived from China.' },
  sections: [
    { h: { vi: 'Chuẩn bị', en: 'Getting ready' }, p: { vi: 'Bạn dùng trà lá rời, không dùng túi lọc, và chọn một chiếc tách sáng màu có lòng tròn. Trong lúc uống, bạn nghĩ về câu hỏi của mình. Khi còn một ngụm cuối, bạn xoay tách ba vòng bằng tay trái, úp nhanh lên đĩa, đợi vài giây rồi lật lại.', en: 'Use loose leaves rather than a tea bag, and pick a light-coloured cup with a round bowl. While you drink, think about your question. When one sip remains, swirl the cup three times with your left hand, turn it quickly onto the saucer, wait a few seconds, then turn it back.' } },
    { h: { vi: 'Đọc theo vị trí', en: 'Reading by position' }, p: { vi: 'Hình nằm gần miệng tách nói về chuyện sắp tới. Hình ở giữa tách nói về vài tuần sau. Hình dưới đáy nói về chuyện xa hơn, hoặc về gốc rễ của vấn đề. Hình gần quai liên quan trực tiếp đến bạn, còn hình đối diện quai nói về người khác và những chuyện bên ngoài.', en: 'Shapes near the rim speak of what is coming soon. Shapes in the middle speak of a few weeks ahead. Shapes at the bottom speak of things further away, or of the root of the matter. Shapes near the handle concern you directly, while shapes opposite the handle speak of other people and outside events.' } },
    { h: { vi: 'Vài hình thường gặp', en: 'Some common shapes' }, p: { vi: 'Con chim là tin tức. Trái tim là tình cảm. Chiếc nhẫn là cam kết hay hôn nhân. Chìa khóa là một cánh cửa đang mở. Đường thẳng là một chuyến đi. Cái cây là thành công đến dần. Đám mây là sự rối rắm, chưa rõ ràng. Một chữ cái là tên của ai đó, và một con số là số ngày hoặc số tháng.', en: 'A bird is news. A heart is love. A ring is commitment or marriage. A key is a door opening. A straight line is a journey. A tree is success arriving gradually. A cloud is confusion, something not yet clear. A letter is someone\'s name, and a number is a count of days or months.' } },
    { h: { vi: 'Đọc với tinh thần nào', en: 'The right spirit' }, p: { vi: 'Bài trà là một cách kể chuyện qua hình ảnh, giống như nhìn mây trên trời. Nó gợi ý chứ không phán xét. Hình mà bạn nhìn thấy đầu tiên thường là hình quan trọng nhất.', en: 'Tealeaf fortune telling is a way of telling a story through pictures, much like watching clouds. It suggests; it does not judge. The shape you notice first is usually the one that matters most.' } }
  ] },
];
