/* ==================== Lenormand card text — English ==================== */
/* Meanings follow the mainstream Petit Lenormand tradition. This is a different
   system from tarot with a different grammar, and it is deliberately kept apart
   from the tarot half of this site: nothing here comes from Thu Anh's tarot
   teaching, and the two should not be blended when you read. */

const LEN = { en: {}, vi: {} };

Object.assign(LEN.en, {

1: { name: 'Rider', card: '9 of Hearts', tone: 'pos', person: true,
  kw: { pos: ['news', 'arrival', 'movement', 'a visitor', 'an approach', 'sport'],
        neg: ['restlessness', 'news that unsettles', 'someone who does not stay'] },
  scene: 'A rider on horseback, moving across the card. He is coming towards something, and he is carrying something — the message is not his own.',
  core: 'The Rider is the card of incoming news and of things arriving from outside. Something is on its way to you: a message, a person, an opportunity, a piece of information. It is fast — the Rider is one of the quickest cards in the deck. On its own it is neutral good news; the card standing next to it tells you what the news is about.',
  love: 'A message from someone, a first approach, or a young man entering the picture. Contact is coming — but the Rider brings news, not commitment.',
  work: 'An offer, an interview invitation, a delivery, a courier, anything sales or sport related. Movement in a situation that had been still.',
  who: 'A young man, an athlete, a messenger, a delivery driver — someone active, quick, and passing through rather than settling.',
  time: 'Very fast. One to three days, sometimes the same day.',
  combo: [['+ Heart', 'A love message, a confession of feeling, a declaration arriving.'],
          ['+ Letter', 'Written news specifically — an email, a text, a formal document.'],
          ['+ Coffin', 'Bad news arriving, or news that ends something.']] },

2: { name: 'Clover', card: '6 of Diamonds', tone: 'pos',
  kw: { pos: ['small luck', 'a lucky break', 'a brief chance', 'relief', 'lightness'],
        neg: ['it does not last', 'gambling', 'a fluke you cannot repeat'] },
  scene: 'A clover growing low to the ground. It is small, and it is easy to miss if you are not looking down.',
  core: 'The Clover is luck — but small, quick luck. A window opens and it does not stay open long. This card says yes, but yes to something modest and temporary rather than something that changes your life. Its great value in a reading is that it lightens whatever sits beside it: even a heavy card gets easier next to the Clover.',
  love: 'A pleasant moment, a flirtation, a bit of good fortune in a relationship. Not the card of a lasting bond — enjoy it as it is.',
  work: 'A small opportunity, a modest win, a problem that unexpectedly resolves itself. Take it now; it will not wait.',
  who: 'Someone lighthearted, lucky, not serious. Fun to be around, not someone to build on.',
  time: 'Very short. Hours to a few days. If you are waiting for the moment, the moment is now.',
  combo: [['+ Fish', 'A small windfall — money that arrives unexpectedly.'],
          ['+ Clouds', 'Luck that gets confused or missed. The chance came and you did not see it.'],
          ['+ Ring', 'A lucky commitment, or a short-lived agreement.']] },

3: { name: 'Ship', card: '10 of Spades', tone: 'neu',
  kw: { pos: ['travel', 'distance', 'trade', 'a journey', 'foreign matters', 'progress'],
        neg: ['longing', 'someone far away', 'leaving', 'emotional distance'] },
  scene: 'A ship under full sail, on open water, heading away from where it started.',
  core: 'The Ship is distance and departure. It covers literal travel, foreign countries, imports and trade, and also the emotional version: someone or something being far away, and the longing that comes with it. The Ship is always in motion, so it says the situation is moving — but slowly, and away from where it is now.',
  love: 'A long-distance relationship, someone who lives far away, or a person who is emotionally elsewhere. It can also mean a relationship that begins on a trip.',
  work: 'Import/export, international work, travel for the job, or a career that moves you somewhere new. Progress that takes time to arrive.',
  who: 'A foreigner, a traveller, someone who lives abroad, a merchant. Or the person in your life who is always leaving.',
  time: 'Slow. Weeks to months — or "when the journey happens."',
  combo: [['+ Heart', 'Long-distance love, or a romance that starts while travelling.'],
          ['+ House', 'Moving house, relocating, or a home abroad.'],
          ['+ Coffin', 'A journey that ends, or a departure that closes something for good.']] },

4: { name: 'House', card: 'King of Hearts', tone: 'neu',
  kw: { pos: ['home', 'family', 'security', 'stability', 'property', 'tradition'],
        neg: ['stuck in the familiar', 'family pressure', 'too conservative'] },
  scene: 'A solid house with its door shut and its windows lit. It is not going anywhere.',
  core: 'The House is your base — the physical home, the family, and the sense of safety that comes from both. It is one of the most stable cards in the deck, and it grounds whatever sits beside it. Where the Ship goes out, the House stays. It often points to a matter that is domestic or private rather than public.',
  love: 'A relationship with a settled, domestic quality — living together, meeting the family, building something to live inside. Safe rather than exciting.',
  work: 'Working from home, a family business, real estate and property, or a job that offers security over ambition.',
  who: 'A family member, a father figure, a landlord, someone traditional and dependable.',
  time: 'Stable and unhurried. About four weeks, or "when you are at home."',
  combo: [['+ Ring', 'Marriage, moving in together, a property contract.'],
          ['+ Mice', 'The home is being eroded — loss of property, stress at home, or a family draining you.'],
          ['+ Fish', 'Family money, property income, financial security.']] },

5: { name: 'Tree', card: '7 of Hearts', tone: 'neu',
  kw: { pos: ['health', 'growth', 'roots', 'depth', 'life force', 'connection'],
        neg: ['slowness', 'illness', 'stagnation', 'something long-standing'] },
  scene: 'A single tree with a heavy canopy and a thick trunk. Its roots are the part of it you cannot see.',
  core: 'The Tree is the health card, and also the card of deep, slow growth. Everything about the Tree takes time — it does not do anything quickly. It speaks of what is rooted: long-standing conditions, deep bonds, ancestry, and the body itself. In a reading it says "this is real and it is deep" and simultaneously "this will not resolve fast."',
  love: 'A deep, slow-growing bond, sometimes a karmic or family-like connection. Not fireworks — roots.',
  work: 'A career that grows slowly and steadily, healthcare work, or something you will still be doing in ten years.',
  who: 'A doctor or healer, a relative, someone patient and deeply rooted.',
  time: 'Very slow. Months to years. The Tree is the card that says "not yet."',
  combo: [['+ Coffin', 'The classic health warning pair — illness, or a condition ending.'],
          ['+ Sun', 'Strong health, vitality, recovery.'],
          ['+ Mountain', 'A blockage that has been there a long time; slow healing, chronic delay.']] },

6: { name: 'Clouds', card: 'King of Clubs', tone: 'neg',
  kw: { pos: ['it will pass', 'clearing', 'a temporary fog'],
        neg: ['confusion', 'doubt', 'lack of clarity', 'trouble', 'something obscured'] },
  scene: 'Two banks of cloud — one dark, one bright. Traditionally the dark side shows where the trouble is.',
  core: 'The Clouds are confusion, doubt, and things you cannot see clearly. This is not disaster — it is fog. Something in the situation is unclear, either because information is missing or because someone is muddled. Classically the card has a direction: what the dark side points to is the troubled part, and what the bright side points to is the part that clears.',
  love: 'Mixed signals, an unclear relationship, someone who does not know their own mind. This is the situationship card of the Lenormand deck.',
  work: 'A confusing situation at work, unclear instructions, a decision made without enough information.',
  who: 'Someone unclear, moody, or evasive — not necessarily dishonest, just impossible to read.',
  time: 'Uncertain, and that is the point. One to three days for the fog to lift.',
  combo: [['+ Heart', 'Confused feelings, an unclear romance, mixed signals in love.'],
          ['+ Key', 'The confusion resolves — clarity arrives, the fog lifts.'],
          ['+ Fox', 'The confusion is deliberate. Someone is muddying the water on purpose.']] },

7: { name: 'Snake', card: 'Queen of Clubs', tone: 'neg', person: true,
  kw: { pos: ['wisdom', 'sensuality', 'a necessary detour', 'transformation'],
        neg: ['betrayal', 'a rival', 'complication', 'a lie', 'a winding path'] },
  scene: 'A snake coiled in a long S. It never travels in a straight line, and it is beautiful.',
  core: 'The Snake is complication — and specifically complication with a person behind it. Traditionally it is another woman, a rival, or someone acting against your interests. More broadly it is anything that does not go straight: a detour, an entanglement, a lie, a complicated route to the thing you want. The Snake is not stupid; it is the card of intelligence used for its own ends.',
  love: 'A third person, a rival, an affair, or a relationship with a serious complication in it. Desire that is real but not simple.',
  work: 'Office politics, a colleague working against you, a deal with a hidden condition, a complicated process.',
  who: 'A woman who complicates things — a rival, an ex, a manipulator. Or simply a clever, sensual, difficult person.',
  time: 'Delayed and winding. It will not go in a straight line, so allow longer than you think.',
  combo: [['+ Heart', 'A rival in love, or a seduction. Someone else is in the picture.'],
          ['+ Ring', 'A complicated commitment, an affair inside a marriage, a contract with a trap in it.'],
          ['+ Woman', 'Very literally: another woman is involved.']] },

8: { name: 'Coffin', card: '9 of Diamonds', tone: 'neg',
  kw: { pos: ['a clean ending', 'transformation', 'closure', 'letting go'],
        neg: ['loss', 'illness', 'grief', 'the end of something', 'stagnation'] },
  scene: 'A closed coffin. The thing inside it is finished, and the lid is down.',
  core: 'The Coffin is an ending. It is the card of things that are over: a relationship, a job, a phase of life, sometimes a period of illness. It is rarely literal death in a modern reading — but it is genuinely final. Read it honestly rather than softening it, and read what comes next to it, because the Coffin describes what ended and the neighbour describes what it makes room for.',
  love: 'A relationship ending, feelings that have died, or a period of grief. If you asked whether it is over, this card says it is.',
  work: 'A job ending, a project cancelled, a business closing. Also burnout — energy that has run out.',
  who: 'Someone in mourning, someone withdrawn, or a person who has emotionally shut down.',
  time: 'A closing period, around eight weeks — or "when it ends," which may be already.',
  combo: [['+ Heart', 'The end of a relationship, or heartbreak.'],
          ['+ Stork', 'An ending that becomes a change for the better — the classic transformation pair.'],
          ['+ Tree', 'A health matter, or a long-standing condition reaching its end.']] },

9: { name: 'Bouquet', card: 'Queen of Spades', tone: 'pos',
  kw: { pos: ['a gift', 'an invitation', 'charm', 'beauty', 'appreciation', 'a nice offer'],
        neg: ['flattery', 'surface charm', 'a gesture with nothing behind it'] },
  scene: 'A bouquet, wrapped and ready to be handed to someone. Its whole purpose is to be given away.',
  core: 'The Bouquet is a pleasant offer — a gift, an invitation, a compliment, a kindness arriving. It is one of the friendliest cards in the deck and it sweetens whatever it touches. Its one caution is that a bouquet is a surface: it is beautiful, it is genuinely nice, and it does not by itself prove depth. Somebody is being lovely to you. Whether they mean it is the next card.',
  love: 'Being courted. Compliments, gifts, an invitation, someone making an effort to charm you. A very good sign in a crush reading.',
  work: 'Recognition, a bonus, a well-received presentation, an invitation to something. Creative and aesthetic work.',
  who: 'A charming, well-mannered, attractive person. Someone who makes things pleasant.',
  time: 'Soon and pleasantly — around nine days.',
  combo: [['+ Heart', 'A romantic gesture — flowers, a gift, a declaration of affection.'],
          ['+ Fox', 'Flattery with a motive. The charm is a tactic.'],
          ['+ Ring', 'A proposal, an engagement gift, a lovely offer with commitment behind it.']] },

10: { name: 'Scythe', card: 'Jack of Diamonds', tone: 'neg',
  kw: { pos: ['a decisive cut', 'harvest', 'clean removal', 'surgery'],
        neg: ['sudden loss', 'danger', 'an abrupt end', 'something breaking off'] },
  scene: 'A scythe with the blade raised. It only works one way: fast, and all at once.',
  core: 'The Scythe is the sudden cut. Where the Coffin is an ending that settles, the Scythe is an ending that happens in a moment, without warning and usually without discussion. It is also decision — the card of finally cutting something off. Its defining quality is speed: whatever it touches happens abruptly. Traditionally the direction the blade points shows what is being cut.',
  love: 'A sudden break-up, being cut off, or a decision made without warning. Also the card of finally ending something yourself.',
  work: 'Redundancy, a contract cancelled, a project killed. Also surgery, and any work involving blades or precision.',
  who: 'Someone decisive and abrupt. A surgeon, a dentist, or a person who ends things without a conversation.',
  time: 'Instant. Now, or with no warning at all.',
  combo: [['+ Heart', 'A sudden break-up, or a decision to end a relationship.'],
          ['+ Tree', 'Surgery, or an abrupt health event.'],
          ['+ Ring', 'A contract cancelled, a marriage ended, an agreement broken.']] },

11: { name: 'Whip', card: 'Jack of Clubs', tone: 'neg',
  kw: { pos: ['discipline', 'physical energy', 'repetition that builds', 'sex'],
        neg: ['arguments', 'conflict', 'repetition', 'the same fight again', 'abuse'] },
  scene: 'Two rods crossed. Nothing here happens once — the Whip is always a repeated motion.',
  core: 'The Whip is conflict and repetition. The key word is *again*: the same argument, the same pattern, the same cycle. It covers rows, criticism, and the wearing quality of a fight that keeps restarting. Its other face is physical: sport, exercise, hard training, and sexuality. Both readings share the same engine — something done over and over.',
  love: 'Repeated arguments, a relationship that keeps having the same fight. In a different key: strong physical chemistry.',
  work: 'Conflict with a colleague, criticism, repetitive work, physical labour. A dispute that keeps reopening.',
  who: 'Someone argumentative, physical, or hot-tempered. An athlete, a trainer, or a person you keep clashing with.',
  time: 'Drawn out and repeating. It will happen more than once before it is done.',
  combo: [['+ Heart', 'A stormy relationship — passion and fighting in the same place.'],
          ['+ Clouds', 'An argument that goes nowhere because nobody is clear.'],
          ['+ Coffin', 'The fighting ends — or the relationship ends because of the fighting.']] },

12: { name: 'Birds', card: '7 of Diamonds', tone: 'neu',
  kw: { pos: ['conversation', 'a pair', 'a phone call', 'negotiation', 'liveliness'],
        neg: ['gossip', 'anxiety', 'chatter', 'nerves', 'talking instead of doing'] },
  scene: 'Two small birds, both talking at once. There are always two of them, and they are always noisy.',
  core: 'The Birds are talk. Phone calls, conversations, negotiations, gossip, and the nervous chatter in your own head. Because there are two birds, the card also means a pair — two people, a couple, a duo, or two of anything. It is short and busy rather than deep, and it carries a background hum of anxiety.',
  love: 'A conversation with someone, a phone call, or a couple. Also nervousness about a relationship, and other people talking about it.',
  work: 'Meetings, phone calls, negotiations, media and communication work. Or office gossip.',
  who: 'A talkative, sociable, anxious person. Two people. Siblings. Someone in sales or media.',
  time: 'Quick but flustered. Twelve hours to twelve days.',
  combo: [['+ Heart', 'A conversation about feelings, or a couple.'],
          ['+ Clouds', 'Gossip and confusion — people talking without knowing.'],
          ['+ Ring', 'Negotiating a commitment, or two people agreeing terms.']] },

13: { name: 'Child', card: 'Jack of Spades', tone: 'pos', person: true,
  kw: { pos: ['a new beginning', 'innocence', 'a child', 'something small', 'fresh energy'],
        neg: ['immaturity', 'naivety', 'inexperience', 'too new to trust'] },
  scene: 'A small child, standing on its own. Everything about it is early.',
  core: 'The Child is beginnings and smallness. It means an actual child, and it means anything at its very start: a new relationship, a new job, a new idea. Whatever it touches becomes younger and smaller — a small amount, a small problem, an early stage. Its honest edge is inexperience: the Child is genuine, but it does not yet know what it is doing.',
  love: 'A new relationship, or one still in its early stage. Innocent, sincere feelings — and not yet mature ones. Also literally: a child, or pregnancy.',
  work: 'A new job, a trainee, a small project, a fresh start. Working with children or education.',
  who: 'A child, a young person, someone naive or new. Someone childlike in the good sense, and in the difficult one.',
  time: 'The very beginning of something. Short and early.',
  combo: [['+ Heart', 'New love, a young romance, innocent feelings.'],
          ['+ Stork', 'Pregnancy, a birth, or a new beginning that changes everything.'],
          ['+ Snake', 'Naivety being taken advantage of.']] },

14: { name: 'Fox', card: '9 of Clubs', tone: 'neg', person: true,
  kw: { pos: ['cleverness', 'strategy', 'self-protection', 'the day job'],
        neg: ['deception', 'a trick', 'self-interest', 'a false friend', 'a mistake'] },
  scene: 'A fox, watching. It is not hunting yet — it is calculating.',
  core: 'The Fox is cunning and self-interest. Someone is acting for their own benefit, and they are being clever about it. It ranges from harmless strategy to outright deception, and the neighbouring card tells you which. The Fox is also, in most traditions, the card of *the job* — the thing you do for money, the daily grind. And it warns of error: something in the situation is not what it is being presented as.',
  love: 'Someone with an agenda, a person who is not being straight with you, or a relationship where one side is playing a game.',
  work: 'Your job itself, a difficult colleague, office politics, or a mistake in the work. Read carefully before signing.',
  who: 'A clever, self-serving person. A colleague, a rival, a con artist — or simply a strategist.',
  time: 'Do not trust the schedule. Later than promised, or not when they said.',
  combo: [['+ Heart', 'Insincere affection, or love with an ulterior motive.'],
          ['+ Bouquet', 'Flattery used as a tool.'],
          ['+ Key', 'The trick is exposed — the truth about it comes out.']] },

15: { name: 'Bear', card: '10 of Clubs', tone: 'neu', person: true,
  kw: { pos: ['strength', 'power', 'protection', 'authority', 'money', 'a provider'],
        neg: ['domination', 'jealousy', 'someone controlling', 'weight', 'excess'] },
  scene: 'A large bear. Its presence alone changes the room — nothing about it is subtle.',
  core: 'The Bear is power. It covers strength, protection, and the person in the situation who has the authority: a boss, a mother figure, a person who holds the resources. It is also the card of substantial money and of physical bulk. The Bear protects what is his, which is its virtue and its problem — the shadow of the Bear is possessiveness and control.',
  love: 'A protective, strong partner — or a possessive, jealous one. Someone older or more powerful in the relationship.',
  work: 'Your boss, a person with authority, a large sum of money, finance and management. Strength you can rely on.',
  who: 'A boss, a mother, an older or larger person, someone in authority. Powerful, protective, hard to argue with.',
  time: 'Long and heavy. Months rather than weeks.',
  combo: [['+ Fish', 'Substantial money — a large sum, wealth, an investment.'],
          ['+ Heart', 'Protective love, or a jealous and controlling one.'],
          ['+ Snake', 'A power struggle, or a jealous rival.']] },

16: { name: 'Stars', card: '6 of Hearts', tone: 'pos',
  kw: { pos: ['hope', 'clarity', 'guidance', 'a clear path', 'inspiration', 'many'],
        neg: ['scattered', 'a dream with no plan', 'spread too thin', 'night'] },
  scene: 'A night sky full of stars, one brighter than the rest. You can navigate by them.',
  core: 'The Stars are clarity, hope, and direction. This is the card that says the path is visible: you can see where you are going and the situation is well-starred. It carries a spiritual, intuitive quality and it multiplies — many stars means many of whatever sits beside it. Its weakness is that stars are far away; the Stars show the direction beautifully and do not do the walking.',
  love: 'A hopeful, well-aspected relationship. Someone you idealise. Clarity about what you actually want.',
  work: 'A clear plan, a good direction, creative and technological work, online and digital matters. Many small opportunities.',
  who: 'An inspiring, spiritual, or visionary person. Someone you look up to.',
  time: 'At night, or clearly signposted. Around sixteen days.',
  combo: [['+ Heart', 'A hopeful, beautiful love. Clarity about your feelings.'],
          ['+ Clouds', 'The direction is lost — hope obscured, a plan gone foggy.'],
          ['+ Key', 'Certainty and clarity together: the answer is yes and it is clear.']] },

17: { name: 'Stork', card: 'Queen of Hearts', tone: 'pos',
  kw: { pos: ['change', 'improvement', 'moving', 'a new phase', 'birth', 'return'],
        neg: ['restlessness', 'change for its own sake', 'instability'] },
  scene: 'A stork on long legs, mid-migration. It goes, and then it comes back.',
  core: 'The Stork is change — and, unlike most change cards, it is change for the better. It covers moving house, changing jobs, a shift in a relationship, and literal birth. Storks migrate, so the card also carries return: something coming back, or a cyclical shift. Where the Coffin ends and the Scythe cuts, the Stork transforms — the thing does not stop, it becomes something else.',
  love: 'A relationship changing form — becoming official, moving in, or shifting to a new phase. Improvement.',
  work: 'A job change, a promotion, a move to a new department or city. A welcome change of circumstance.',
  who: 'Someone in transition, a mother, a midwife. A person who has recently changed a great deal.',
  time: 'A change of season — around seventeen days, or spring.',
  combo: [['+ House', 'Moving house. Very literal.'],
          ['+ Child', 'Pregnancy or a birth — the classic pair.'],
          ['+ Coffin', 'A change that ends something, or an ending that turns into a change.']] },

18: { name: 'Dog', card: '10 of Hearts', tone: 'pos', person: true,
  kw: { pos: ['a friend', 'loyalty', 'trust', 'faithfulness', 'familiarity', 'support'],
        neg: ['dependence', 'blind loyalty', 'staying out of habit', 'only a friend'] },
  scene: 'A dog, sitting and waiting. It has been there the whole time.',
  core: 'The Dog is loyalty and friendship. It is one of the warmest cards in the deck and it points to someone reliable — a friend, a partner who stays, a person who has proven themselves. Read literally it often just means *a friend*, which in a love reading is important information: the Dog is affectionate and constant, but it is not the card of romance. It is the card of the person who will still be there.',
  love: 'A faithful partner, or someone who loves you as a friend. In a crush reading, be honest: the Dog can mean loyal devotion, and it can mean the friend zone.',
  work: 'A trustworthy colleague, a reliable working relationship, a long-standing client. Support you can count on.',
  who: 'A friend, a loyal partner, a supporter. Someone familiar and safe.',
  time: 'Steady and dependable. It will happen when it always happens.',
  combo: [['+ Heart', 'A loving friendship, or a friend who becomes more.'],
          ['+ Snake', 'A false friend — betrayal by someone you trusted.'],
          ['+ Ring', 'A loyal commitment; a friendship that becomes a partnership.']] },

19: { name: 'Tower', card: '6 of Spades', tone: 'neu',
  kw: { pos: ['authority', 'structure', 'an institution', 'perspective', 'boundaries'],
        neg: ['isolation', 'loneliness', 'coldness', 'bureaucracy', 'being shut out'] },
  scene: 'A tall stone tower standing alone. You can see a long way from the top, and there is nobody up there with you.',
  core: 'The Tower is the institution and the solitary height. It covers official bodies — government, corporations, hospitals, courts — and the formal, impersonal way they operate. On the personal side it is isolation: standing apart, keeping a boundary, being alone by choice or by circumstance. It carries authority, longevity, and a certain coldness.',
  love: 'Emotional distance, someone who keeps a wall up, or a relationship that is formal rather than warm. Also being single, and often being fine with it.',
  work: 'A large organisation, official procedure, government or legal matters, a senior position. Long-term and bureaucratic.',
  who: 'An authority figure, an official, a solitary person. Someone reserved and self-contained.',
  time: 'Long and institutional. Slow because a system is involved.',
  combo: [['+ Heart', 'Love kept at a distance, or a lonely heart.'],
          ['+ Ring', 'An official contract — legal marriage, a corporate agreement.'],
          ['+ Garden', 'The private meets the public — going public with something, or an institution in the news.']] },

20: { name: 'Garden', card: '8 of Spades', tone: 'neu',
  kw: { pos: ['the public', 'a gathering', 'community', 'networking', 'a meeting', 'social life'],
        neg: ['exposure', 'no privacy', 'superficial contact', 'a crowd'] },
  scene: 'A public garden with a path running through it. Anyone may walk here.',
  core: 'The Garden is the public sphere. It is where you are seen: social gatherings, parties, networking, the internet, reputation, and anything that happens in front of other people. It is neither good nor bad on its own — it simply says this matter is not private. Whatever card stands next to the Garden becomes public knowledge or takes place among people.',
  love: 'Meeting someone socially, a relationship that is public, or one conducted in a group of mutual friends. Online dating.',
  work: 'Networking, an event, public-facing work, marketing, your professional reputation. A meeting with several people.',
  who: 'A sociable person, the public itself, a crowd, a group of friends.',
  time: 'When people gather. Summer, or at the event.',
  combo: [['+ Heart', 'A public romance, or meeting someone at a social event.'],
          ['+ Birds', 'People are talking. Gossip in a group.'],
          ['+ Fish', 'Business among people — commerce, a market, income from the public.']] },

21: { name: 'Mountain', card: '8 of Clubs', tone: 'neg',
  kw: { pos: ['endurance', 'a challenge worth climbing', 'permanence'],
        neg: ['a blockage', 'delay', 'an obstacle', 'distance', 'someone cold'] },
  scene: 'A mountain range, snow on the peaks. It is not going to move for you.',
  core: 'The Mountain is the obstacle. Something big is in the way and it will not shift easily — a delay, a blockage, a hard barrier between you and what you want. It is also distance and coldness: a person who is unreachable, a situation that is frozen. The Mountain does not say never. It says not this way, and not soon.',
  love: 'A blocked relationship, a serious obstacle between two people, or someone emotionally cold and unreachable. Long delays.',
  work: 'A stalled project, a blocked promotion, bureaucratic delay, a serious professional obstacle.',
  who: 'A cold, distant, or obstructive person. An enemy, or simply someone immovable.',
  time: 'Blocked. Indefinite delay — do not plan around it.',
  combo: [['+ Heart', 'A blocked relationship, or a heart that has gone cold.'],
          ['+ Key', 'The obstacle is overcome — the block clears. A very good pair.'],
          ['+ Clover', 'A lucky break past the obstacle, though a small one.']] },

22: { name: 'Crossroads', card: 'Queen of Diamonds', tone: 'neu',
  kw: { pos: ['choice', 'options', 'freedom', 'alternatives', 'a decision'],
        neg: ['indecision', 'divided', 'too many options', 'no clear path'] },
  scene: 'A path splitting in two, with a signpost. Both directions are real.',
  core: 'The Crossroads is choice. There is more than one option available, and the outcome depends on which you take. It is genuinely neutral: the card does not say which road is better, only that a decision is yours to make. It also means multiplicity — two of something, alternatives, and sometimes a person keeping their options open.',
  love: 'A choice between two people, or a decision about whether to continue. Also someone who has not chosen yet — which is its own answer.',
  work: 'A choice between offers, a career decision, a fork in a project. Multiple options open.',
  who: 'Someone undecided, someone with options, a person who has not committed.',
  time: 'It depends on your decision. The timing is in your hands.',
  combo: [['+ Heart', 'A choice in love, or someone deciding between two people.'],
          ['+ Coffin', 'The decision is to end it.'],
          ['+ Clouds', 'A choice made in confusion — you cannot see the options clearly.']] },

23: { name: 'Mice', card: '7 of Clubs', tone: 'neg',
  kw: { pos: ['it stops once you see it', 'a small problem, caught early'],
        neg: ['loss', 'erosion', 'stress', 'theft', 'something being eaten away'] },
  scene: 'Mice at work on something. No single bite matters; the accumulation does.',
  core: 'The Mice are gradual loss. Something is being eaten away — money, energy, health, trust, time. The damage is not dramatic and that is precisely why it is dangerous: it happens a little at a time and is easy not to notice until a lot is gone. The Mice also mean stress and anxiety, and theft. Whatever card sits beside them is being diminished.',
  love: 'Trust or affection slowly draining away. A relationship that is being worn down rather than broken. Stress corroding a bond.',
  work: 'Money leaking, small ongoing losses, stress, burnout, or something being taken. Check the details.',
  who: 'Someone who drains you. An anxious person, or a petty thief.',
  time: 'Ongoing and gradual. It is happening right now, slowly.',
  combo: [['+ Fish', 'Money being lost — leaking funds, debt, theft.'],
          ['+ Heart', 'Love wearing away, or heartache and stress.'],
          ['+ Tree', 'Health being eroded by stress.']] },

24: { name: 'Heart', card: 'Jack of Hearts', tone: 'pos',
  kw: { pos: ['love', 'affection', 'romance', 'warmth', 'sincerity', 'the heart'],
        neg: ['sentimentality', 'love without action', 'being ruled by feeling'] },
  scene: 'A single red heart, unmistakable. There is nothing else on the card.',
  core: 'The Heart is love — the emotion itself, in its clearest form. It covers romance, affection, warmth, kindness, and genuine feeling. It is one of the least ambiguous cards in the deck: where the Heart appears, real feeling is present. What it does not tell you is what anyone will *do* about that feeling — the Heart is emotion, not commitment. For commitment, look to the Ring.',
  love: 'Love, plainly. Real affection, romance, and sincerity. In a crush reading this is the card you want.',
  work: 'Work you love, a job done with genuine care, good relationships with colleagues. Charity and caring work.',
  who: 'A warm, loving, generous person. The beloved.',
  time: 'Soon and warmly. Summer, or when the feeling is right.',
  combo: [['+ Ring', 'Love and commitment together — the strongest relationship pair in the deck.'],
          ['+ Clouds', 'Confused feelings, unclear love, mixed signals.'],
          ['+ Mountain', 'Blocked love — real feeling that cannot get through.']] },

25: { name: 'Ring', card: 'Ace of Clubs', tone: 'pos',
  kw: { pos: ['commitment', 'a contract', 'marriage', 'a partnership', 'a promise', 'a cycle'],
        neg: ['a binding you cannot leave', 'a repeating cycle', 'obligation without love'] },
  scene: 'A gold ring — a closed circle. It has no end, which is exactly the point.',
  core: 'The Ring is commitment and the agreement that holds it: marriage, a contract, a partnership, a promise given. Because a ring is a closed circle, it also means cycles — something coming round again, a pattern repeating, an ongoing arrangement. It says a bond exists. Whether that bond is loving is a separate question, and the Heart is the card that answers it.',
  love: 'Commitment, a serious relationship, engagement, marriage. Or a relationship that keeps cycling back round.',
  work: 'A contract, a business partnership, a binding agreement, an ongoing arrangement. Read the terms.',
  who: 'A partner, a spouse, a business associate. Someone bound to you by agreement.',
  time: 'A full cycle — around a year, or when the contract comes round.',
  combo: [['+ Heart', 'A committed, loving relationship. Engagement or marriage.'],
          ['+ Scythe', 'A contract broken, an engagement ended, a commitment cut.'],
          ['+ Snake', 'A complicated commitment — a trap in the contract, or an affair within a marriage.']] },

26: { name: 'Book', card: '10 of Diamonds', tone: 'neu',
  kw: { pos: ['knowledge', 'study', 'learning', 'expertise', 'research'],
        neg: ['a secret', 'something hidden', 'information you do not have yet'] },
  scene: 'A closed book with a clasp. Everything it knows is on the inside.',
  core: 'The Book has two faces and they are the same face: knowledge, and knowledge withheld. Closed, it is a secret — something you have not been told, information deliberately kept from you, a hidden aspect of the situation. Opened, it is study, education, expertise, and research. In a reading it very often means simply: you do not have the full picture yet.',
  love: 'A secret in the relationship, or something you have not been told. Also a person who does not open up easily.',
  work: 'Study, training, qualifications, research, or specialist expertise. Also confidential information at work.',
  who: 'A private, educated, secretive person. A teacher, a student, a researcher.',
  time: 'Unknown — the timing has not been revealed. Ask again when more is known.',
  combo: [['+ Heart', 'A secret love, or hidden feelings.'],
          ['+ Key', 'The secret comes out. Hidden knowledge revealed.'],
          ['+ Fox', 'Something is being deliberately hidden from you.']] },

27: { name: 'Letter', card: '7 of Spades', tone: 'neu',
  kw: { pos: ['a message', 'a document', 'written news', 'communication', 'a record'],
        neg: ['bad news in writing', 'paperwork', 'something said only on paper'] },
  scene: 'A sealed letter. Somebody wrote this down on purpose.',
  core: 'The Letter is written communication: a message, a text, an email, a document, a certificate, paperwork. Where the Rider brings news, the Letter is the news itself, in a form you can keep. It is neutral — the card next to it says whether the message is welcome. Its quiet implication is that this is *recorded*: something is being put in writing rather than merely said.',
  love: 'A message from someone, a text, a letter. Words on a screen rather than a conversation face to face.',
  work: 'A contract, a report, an application, an offer letter, documentation. Anything official on paper.',
  who: 'A writer, an administrator, or simply the person who texts rather than calls.',
  time: 'When the message arrives — a few days.',
  combo: [['+ Heart', 'A love letter, a message about feelings, a written confession.'],
          ['+ Coffin', 'Bad news in writing — a termination, a formal ending.'],
          ['+ Ring', 'A contract, an official document, marriage paperwork.']] },

28: { name: 'Man', card: 'Ace of Hearts', tone: 'neu', person: true,
  kw: { pos: ['the man in question', 'the male querent', 'a partner', 'him'],
        neg: ['—'] },
  scene: 'A man, standing and facing forward. He is the subject, not a symbol.',
  core: 'The Man is a person, not a quality. If the querent is a man, this card is him; if the question is about a man, this card is that man. He is the anchor point of the reading — the cards nearest him describe him, the direction he faces shows what he is turned towards, and what lies behind him is his past. Do not interpret the Man as a meaning. Locate him, and read what surrounds him.',
  love: 'Him — the man you are asking about, or your male partner. The cards next to him are his state of mind.',
  work: 'A male colleague, boss, or client. The man in the professional situation.',
  who: 'A man, usually an adult. In a same-sex reading, whichever partner the reader assigns to this card at the start.',
  time: 'Whenever he acts. His timing, not yours.',
  combo: [['Man + Heart', 'He is in love, or feeling affection.'],
          ['Man + Clouds', 'He is confused, or hiding his state of mind.'],
          ['Man + Woman', 'The two of them together — proximity shows how close they actually are.']] },

29: { name: 'Woman', card: 'Ace of Spades', tone: 'neu', person: true,
  kw: { pos: ['the woman in question', 'the female querent', 'a partner', 'her'],
        neg: ['—'] },
  scene: 'A woman, standing and facing forward. She is the subject, not a symbol.',
  core: 'The Woman is a person, not a quality. If the querent is a woman, this card is her; if the question is about a woman, this card is that woman. She anchors the reading in the same way the Man does — read the cards around her as her circumstances, her feelings, and what she is facing. Distance between the Man and the Woman on the table is meaningful information all by itself.',
  love: 'Her — the woman you are asking about, or your female partner. The cards next to her describe her position.',
  work: 'A female colleague, boss, or client. The woman in the professional situation.',
  who: 'A woman, usually an adult. In a same-sex reading, whichever partner the reader assigns to this card at the start.',
  time: 'Whenever she acts. Her timing, not yours.',
  combo: [['Woman + Heart', 'She is in love, or feeling affection.'],
          ['Woman + Snake', 'A rival is close to her, or she is the complication.'],
          ['Woman + Mountain', 'She is blocked, distant, or unreachable.']] },

30: { name: 'Lily', card: 'King of Spades', tone: 'neu', person: true,
  kw: { pos: ['maturity', 'peace', 'wisdom', 'experience', 'harmony', 'an older man'],
        neg: ['coldness', 'an age gap', 'sexuality', 'something past its season'] },
  scene: 'A white lily, fully open. It is not a young flower.',
  core: 'The Lily is maturity — peace, wisdom, and the calm that comes from having lived a while. It points to older people, long-established situations, and matters handled with dignity. Traditionally it carries two further readings that sit oddly together and both belong: it is a card of virtue and purity, and it is the deck\'s card of sexuality. Read it as maturity in whichever sense the neighbouring card supports.',
  love: 'A mature, peaceful relationship, or an older partner. An age difference. Also sexual intimacy specifically.',
  work: 'Senior expertise, long experience, a respected position, retirement. Work handled calmly and well.',
  who: 'An older man, a mentor, a father figure, a person of standing. Someone calm and experienced.',
  time: 'Slow and mature. Winter, or the later stage of something.',
  combo: [['+ Heart', 'A mature, peaceful love — or physical intimacy.'],
          ['+ Man', 'An older man specifically.'],
          ['+ Mountain', 'Coldness and distance in a mature situation.']] },

31: { name: 'Sun', card: 'Ace of Diamonds', tone: 'pos',
  kw: { pos: ['success', 'energy', 'victory', 'warmth', 'clarity', 'a great day'],
        neg: ['burning out', 'arrogance', 'too much of a good thing'] },
  scene: 'The sun at full strength, its rays reaching the edge of the card.',
  core: 'The Sun is success and vitality — the single most positive card in the deck. It means things go well: energy, warmth, victory, recognition, and genuine happiness. It also strengthens whatever it stands beside, turning a difficult card easier and a good card excellent. In a yes/no question it is an unambiguous yes.',
  love: 'A happy, warm relationship. Joy, and a very good outcome. If you asked whether it will go well, it will.',
  work: 'Success, recognition, a win, energy for the work. A project that goes well and is seen to go well.',
  who: 'A warm, confident, successful person. Someone whose presence lifts a room.',
  time: 'Daytime, summer, and soon. Quick and bright.',
  combo: [['+ Heart', 'Great happiness in love. One of the best pairs in the deck.'],
          ['+ Fish', 'Financial success — money and it going well together.'],
          ['+ Clouds', 'The sun behind cloud: success delayed or obscured, but still there.']] },

32: { name: 'Moon', card: '8 of Hearts', tone: 'pos',
  kw: { pos: ['emotion', 'recognition', 'reputation', 'intuition', 'romance', 'a month'],
        neg: ['moodiness', 'illusion', 'living in feeling', 'wanting to be seen'] },
  scene: 'A crescent moon in a dark sky. It gives light, but not much, and it changes shape every night.',
  core: 'The Moon is the emotional life and the reputation — two meanings joined by the idea of reflection. Inwardly it is feeling, intuition, dreams, and romance; outwardly it is honour, recognition, fame, and how you are seen. It is also the deck\'s clearest timing card: one moon is one month. It is warmer than the tarot Moon and much less sinister.',
  love: 'Deep romantic feeling, emotional connection, a soulful bond. Also emotional ups and downs.',
  work: 'Recognition, reputation, creative and artistic work, night work. Being honoured for something.',
  who: 'An emotional, intuitive, artistic person. Someone well known, or someone who wants to be.',
  time: 'One month. Or at night.',
  combo: [['+ Heart', 'Deep romantic love — feeling and emotion together.'],
          ['+ Sun', 'Recognition and success. Being seen, and it going well.'],
          ['+ Clouds', 'Emotional confusion, or a reputation under a cloud.']] },

33: { name: 'Key', card: '8 of Diamonds', tone: 'pos',
  kw: { pos: ['certainty', 'yes', 'a solution', 'an opening', 'the answer', 'success'],
        neg: ['—'] },
  scene: 'A key. It is not a symbol of a door; it is the thing that opens it.',
  core: 'The Key is certainty. It means yes, it means the door opens, it means the solution is found. Where the Book closes something, the Key opens it. In a yes/no reading it is the strongest yes in the deck, and next to any blocked card it means the block clears. Its message is that this matter is settled, resolved, or about to be.',
  love: 'A definite yes. The relationship opens up, the answer is clear, the door is not locked.',
  work: 'A solution to the problem, a door opening, a definite outcome. The thing works.',
  who: 'Someone certain and direct, or the person who holds the answer.',
  time: 'Now, and definitely. When the door opens.',
  combo: [['+ Heart', 'Certainty in love — the answer about feelings is yes.'],
          ['+ Mountain', 'The obstacle clears. An excellent pair.'],
          ['+ Book', 'The secret is revealed.']] },

34: { name: 'Fish', card: 'King of Diamonds', tone: 'pos',
  kw: { pos: ['money', 'business', 'abundance', 'flow', 'income', 'independence'],
        neg: ['excess', 'money slipping away', 'too much of something'] },
  scene: 'A fish in deep water with coins settling on the bed below. Both the water and the money are in motion.',
  core: 'The Fish is money and flow. It covers income, business, trade, wealth, and self-employment, and it carries the sense of something moving and plentiful — fish come in shoals. Beyond finance it means abundance of any kind: a lot of whatever card stands beside it. In business questions it is the most directly favourable card in the deck.',
  love: 'A generous partner, a relationship with material comfort, or a bond that flows easily. Sometimes: a relationship where money is a factor.',
  work: 'Income, business, self-employment, sales, investment, cash flow. Financially good.',
  who: 'A businessperson, someone financially independent, a generous person. A merchant.',
  time: 'Flowing and ongoing. When the money comes — payday, month end.',
  combo: [['+ Bear', 'A large sum of money.'],
          ['+ Mice', 'Money draining away — losses, debt, leakage.'],
          ['+ Anchor', 'Stable, reliable income. Financial security.']] },

35: { name: 'Anchor', card: '9 of Spades', tone: 'pos',
  kw: { pos: ['stability', 'persistence', 'security', 'work', 'holding fast', 'a long stay'],
        neg: ['stuck', 'weighed down', 'holding on too long', 'immovable'] },
  scene: 'An anchor on the sea bed, chain taut. It is doing its job, which is to stop things moving.',
  core: 'The Anchor is stability and staying power. It means something holds: a job that lasts, a relationship that endures, a situation that is not going to change. It is also the card of work in the sense of *your livelihood*, and of persistence — hanging on until it works. Its shadow is the same quality seen from another side: being stuck, and holding on to something long after you should have let go.',
  love: 'A relationship that lasts, a partner who stays. Security rather than excitement. Or a bond you are holding on to past its time.',
  work: 'A stable job, long-term employment, a secure position. Work that will still be there next year.',
  who: 'A steady, reliable, immovable person. Someone who does not leave.',
  time: 'Long lasting and permanent. It will still be true later.',
  combo: [['+ Heart', 'Lasting love, a relationship that endures.'],
          ['+ Fish', 'Secure income, a stable financial position.'],
          ['+ Coffin', 'A long-standing situation finally ending.']] },

36: { name: 'Cross', card: '6 of Clubs', tone: 'neg',
  kw: { pos: ['faith', 'meaning', 'a burden nearly carried', 'the end of a trial'],
        neg: ['suffering', 'a burden', 'fate', 'guilt', 'something you must endure'] },
  scene: 'A wooden cross planted in the ground. It is heavy, and it is meant to be carried.',
  core: 'The Cross is burden and fate. It marks the hard part: suffering, obligation, guilt, and a difficulty that has to be gone through rather than around. It also carries genuine spiritual weight — belief, meaning, and destiny. As the last card of the deck it often signals the end of a trial, so it is worth reading what comes after it. The Cross is heavy, but it is finite.',
  love: 'A painful or burdensome relationship. Suffering in love, guilt, or a bond that feels fated and hard.',
  work: 'A heavy workload, an obligation you cannot put down, a difficult period at work.',
  who: 'Someone burdened or suffering. A religious person, or a person who carries others.',
  time: 'A period of trial, ending. The end of a cycle.',
  combo: [['+ Heart', 'Suffering in love. A painful attachment.'],
          ['+ Sun', 'The burden lifts — the hard period ends well.'],
          ['+ Coffin', 'The end of a difficult chapter. Grief, and its conclusion.']] }

});
