/* English card text (The Learner's Deck). */
const ROMAN=['0','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'];

const MAJORS=[
["The Fool","beginnings · faith · innocence · the leap",
 "A youth in a patterned tunic steps toward a cliff edge, face turned up to a white sun. A white rose in one hand, a bundle on a stick over the shoulder, and a small white dog leaping at his heels.",
 "The start of something before you have any evidence it will work. Trust that runs ahead of proof, and the particular freedom of having nothing yet to lose.",
 "Recklessness — or the exact opposite: refusing to move at all because the drop looks too far."],
["The Magician","will · focus · resource · manifestation",
 "One hand raised to the sky, one pointing to the earth, an infinity sign floating above his head. On the table before him lie a wand, a cup, a sword and a pentacle — all four suits.",
 "You already have every tool the situation requires. The work is not acquiring more; it is pointing what you have at one thing.",
 "Talent scattered across too many things, or persuasion turned to manipulation."],
["The High Priestess","intuition · the unrevealed · inner knowing",
 "She sits between a black pillar and a white one, a crescent moon at her feet, a veil of pomegranates drawn behind her, and a scroll only half visible in her lap.",
 "The answer exists but hasn't surfaced. Wait, listen inward, and don't force disclosure — from yourself or anyone else.",
 "Overriding your own gut, or a secret kept well past the point where it helped anyone."],
["The Empress","abundance · nurture · creation · the senses",
 "A crowned woman among ripening wheat, a crown of twelve stars above her, a heart-shaped shield bearing the symbol of Venus at her side.",
 "Something is growing and mostly needs feeding rather than fixing. Fertility in every sense — creative, physical, material comfort, pleasure taken without guilt.",
 "Smothering, creative block, or pouring care into everything except yourself."],
["The Emperor","structure · authority · boundary",
 "A bearded ruler on a stone throne carved with rams' heads, an ankh sceptre in his hand, barren mountains behind him.",
 "Order imposed on chaos: rules, discipline, protection. The card of the person who decides, and of the boundary that makes the rest possible.",
 "Rigidity and domination — or the absence of any structure at all, leaving everything wobbling."],
["The Hierophant","tradition · teaching · institution",
 "A robed figure in a triple crown raises a hand in blessing over two tonsured monks. Crossed keys lie at his feet.",
 "The established way, and someone qualified to teach it. Learning inside a lineage, and the value of doing it how it has always been done.",
 "Dogma that has outlived its use, or a genuine call to break with convention."],
["The Lovers","union · choice · values",
 "A man and a woman stand naked beneath a winged angel in full sun. Behind her, a serpent in a tree; behind him, a tree of flames.",
 "A real meeting between two things, and a choice that reveals what you actually value rather than what you claim to.",
 "Misalignment, a decision dodged, or a partnership where the weight sits on one side."],
["The Chariot","drive · control · victory",
 "An armoured figure stands in a chariot under a canopy of stars, drawn by one black sphinx and one white. There are no reins anywhere in the picture.",
 "Forward motion won by holding two opposing forces on a single course. Willpower over circumstance, at least for now.",
 "Pulled two ways at once, or momentum with nobody steering."],
["Strength","courage · patience · soft power",
 "A woman in white calmly closes a lion's jaws with her bare hands, an infinity sign above her head. She is not straining.",
 "Influence through gentleness and endurance rather than force. Also the quieter version: mastering your own appetite instead of someone else's.",
 "Self-doubt, or force applied where patience would have worked."],
["The Hermit","solitude · search · inner light",
 "A cloaked old man on a snowy peak holds up a lantern with a six-pointed star burning inside it, leaning on a long staff.",
 "Deliberate withdrawal to find your own answer. A season of study, quiet, and deliberately not consulting the crowd.",
 "Isolation that has curdled into avoidance, or refusing help that was genuinely offered."],
["Wheel of Fortune","cycles · turning point · luck",
 "A great wheel lettered T-A-R-O turns in the sky. A sphinx rests above it, a serpent descends one side, a jackal rises the other, and four winged creatures read books in the corners.",
 "Circumstances shift on their own schedule. Ride the turn rather than gripping one spoke and insisting it stay at the top.",
 "A downswing, resistance to a change already underway, or simply bad timing."],
["Justice","fairness · cause and effect · truth",
 "A crowned figure seated between two pillars holds an upright sword in one hand and perfectly level scales in the other.",
 "Things weighed accurately and consequences arriving. A decision that has to be honest rather than kind.",
 "Bias, an unbalanced account, or accountability successfully avoided — for now."],
["The Hanged Man","suspension · reversal · surrender",
 "A man hangs serenely by one ankle from a living T-shaped tree, his free leg crossed behind, a halo of light around his head.",
 "A deliberate pause. The answer comes from inverting your view, not from pushing harder in the direction you were already going.",
 "Stalling dressed up as reflection, or a sacrifice made with nothing coming back."],
["Death","ending · transition · clearance",
 "A skeleton in black armour rides a white horse past a fallen king. Its banner carries a white rose, and the sun rises between two towers on the horizon.",
 "Something concludes for good so that the next thing can exist. Almost never literal, and almost always non-negotiable.",
 "Clinging to what is already over, or an ending being drawn out far longer than it needs to be."],
["Temperance","balance · blending · moderation",
 "A winged figure with one foot on land and one in the water pours liquid between two cups in an arc that shouldn't be possible.",
 "Patient adjustment until the mix comes right. Healing and recovery that will take the time they take.",
 "Excess, impatience, or two elements that simply will not combine."],
["The Devil","bondage · compulsion · shadow",
 "A horned figure squats on a block, an inverted pentagram at his brow. A man and a woman stand chained below him — and the chains are loose enough to lift straight off.",
 "An attachment that is running you: a habit, a craving, a dynamic you tell yourself you can't leave. The looseness of the chains is the whole point.",
 "Recognising the chain for what it is, and making the first move to shake it off."],
["The Tower","sudden collapse · revelation",
 "Lightning strikes the crown from a tall tower. Flames burst from the windows and two figures fall headlong into the dark.",
 "A structure built on something false comes down fast. Painful, clarifying, and not optional once it starts.",
 "A disaster narrowly avoided, or a collapse you are exhaustingly prolonging."],
["The Star","hope · renewal · guidance",
 "A naked woman kneels by a pool, pouring water onto the land with one jug and back into the pool with the other. One great star and seven smaller ones burn overhead.",
 "Calm after the wreckage. Faith restored, and a clear sense of which direction is yours — usually arriving right after The Tower.",
 "Discouragement, faith worn thin, losing sight of the thread you were following."],
["The Moon","uncertainty · dream · distortion",
 "A moon with a face drips dew over a path running between two towers. A dog and a wolf howl at it, and a crayfish crawls out of the pool.",
 "The terrain isn't clear and your read on it may be wrong. Fear, imagination and instinct all talking at once, in the dark.",
 "Confusion lifting, or a deception finally coming to light."],
["The Sun","clarity · vitality · success",
 "A child rides a white horse under an enormous radiant sun, a red banner streaming behind, a wall of sunflowers at their back.",
 "Things are simply good, and visible. Energy, warmth, plain honest joy — the least complicated card in the deck.",
 "Enthusiasm dimmed, success delayed, or optimism being performed rather than felt."],
["Judgement","reckoning · awakening · calling",
 "An angel sounds a trumpet through the clouds and grey figures rise from open coffins with their arms flung open.",
 "A summing-up. You see the whole arc of something at once and answer a call you can't pretend not to have heard.",
 "Harsh self-reproach, or hearing the summons clearly and ignoring it."],
["The World","completion · wholeness · integration",
 "A dancing figure wrapped in a violet sash stands inside a laurel wreath. A bull, a lion, an eagle and an angel occupy the four corners.",
 "The cycle closes properly. Arrival, and the competence that only comes from having gone the whole way round.",
 "So nearly finished — a loose end, or closure someone is withholding."]
];

const MINORS={
wands:{
 el:"Fire", blurb:"Drive, creativity, ambition, the spark before the plan. Wands cards move fast and burn out.",
 pips:[
 ["A hand reaches from a cloud offering a sprouting branch, leaves still falling from it.","A spark: the first surge of wanting to make something. Raw energy, not yet aimed.","A false start, or energy with nowhere to put itself."],
 ["A man on his own battlement holds a globe, looking out past the walls he built.","Planning beyond what you already hold. Choosing the bigger horizon over the comfortable one.","Playing it safe, or plans that never leave the desk."],
 ["A figure on a cliff watches ships sail out across the water.","The first efforts are underway and out of your hands. Expansion, and the wait that follows launching something.","Delays, waiting badly, or a plan pitched too small."],
 ["Four garlanded poles form a gateway before a castle; figures raise bouquets beneath it.","A threshold worth stopping to mark — homecoming, stability, a milestone reached with other people.","The same thing quieter: a celebration deferred or held privately."],
 ["Five youths brandish staves in a scrappy, disorganised mock-fight.","Friction and competition. Everybody talking over everybody; nobody actually being heard.","Conflict swerved, or a long-running argument finally settling."],
 ["A rider crowned with laurel is cheered through a crowd, a wreath on his staff.","Public recognition. The win that other people can see and acknowledge.","Recognition withheld, or a success that rings hollow once you have it."],
 ["A man on high ground fends off six staves coming at him from below.","Holding your position under pressure. Defend what you built — you have the higher ground.","Overwhelmed, or giving up ground you should have kept."],
 ["Eight staves fly through open sky above a river. No people at all.","Sudden speed. Messages, travel, and things landing all at once after a long stillness.","Hold-ups, or energy scattered in eight directions."],
 ["A bandaged man leans on his staff, watching the fence line, braced for the next one.","Worn down and still standing. One more push, and a guardedness that was earned honestly.","Paranoia, or an exhaustion you have been ignoring for too long."],
 ["A figure struggles forward bent double under a bundle of ten staves.","Overload. You took all of it on and it is genuinely too much to carry this way.","Putting something down. Delegating at last, or refusing the next thing."]],
 court:[
 ["A youth in a feathered hat stands in a desert, studying the staff in his hands.","A new enthusiasm, or news that starts something. Permission to be a beginner at it.","Restlessness, big talk, and nothing actually begun."],
 ["A knight in a plumed helm charges on a rearing horse, staff held high.","Bold action and adventure. Going before it is fully planned, on purpose.","Haste and burnout — starting what you have no intention of finishing."],
 ["A crowned woman holds a sunflower, a black cat seated at her feet, facing straight out.","Warm, confident, magnetic. Knows exactly what she wants and makes other people want it too.","Intensity that has turned demanding, or confidence gone brittle."],
 ["A bearded king on a throne carved with salamanders holds a flowering staff.","Vision plus the authority to make others believe in it. A natural leader, impatient with detail.","Impulsiveness at scale, tyranny, or promises outrunning delivery."]]},
cups:{
 el:"Water", blurb:"Emotion, relationship, imagination, the inner life. Cups cards move slowly and go deep.",
 pips:[
 ["A hand offers an overflowing chalice with a dove descending into it, five streams spilling over.","An emotional opening — love offered, a connection beginning, a feeling that hasn't been spoilt yet.","Closed off, or a feeling firmly pushed back down."],
 ["A man and a woman pledge their cups to each other beneath a winged caduceus.","Mutual recognition between two people. Partnership, reconciliation, a truce that both sides mean.","Imbalance, a rift, or one person carrying the whole thing."],
 ["Three women raise their cups in a circle, dancing among the harvest.","Friendship and celebration. Being genuinely glad in company rather than alone.","Gossip, excess, or a group dynamic that has gone sour."],
 ["A figure sits under a tree with arms folded, ignoring a cup offered from a cloud.","Discontent and boredom. Something is being offered and you cannot make yourself want it.","Waking up to the offer. Apathy lifting."],
 ["A cloaked figure grieves over three spilled cups. Two remain standing behind, unnoticed.","Loss, and the way grief makes you look only at what is gone. The two upright cups are the whole message.","Turning around. Acceptance starting, help accepted."],
 ["A child hands another a cup filled with flowers in a walled garden.","Nostalgia and innocence. Kindness from the past coming back around, or someone from it returning.","Stuck in old memory — or finally setting it down."],
 ["Seven cups float in cloud holding a castle, jewels, a wreath, a snake and a shrouded figure.","Too many options, most of them fantasy. Pick one and make it real, or none of them become real.","Clarity arriving, or wishful thinking exposed for what it was."],
 ["A figure walks away from eight stacked cups toward mountains, under an eclipsed moon.","Leaving something that is fine but is not enough. A departure made deliberately, at personal cost.","Going back, or being unable to make yourself leave."],
 ["A satisfied man sits before a curved bar of nine cups, arms folded, pleased with himself.","Contentment. A wish granted and pleasure that was earned — traditionally the wish card.","Smugness, or getting the wish and finding it did not satisfy."],
 ["A couple raise their arms to a rainbow of ten cups while two children dance beside them.","Emotional fulfilment in the whole picture — family, belonging, happiness that holds up over time.","A perfect surface with a real gap underneath it."]],
 court:[
 ["A youth in a blue tunic regards a fish that has appeared in his cup, unbothered.","A tender new feeling, an invitation, or an idea from the imagination worth following.","Moodiness, or feelings held back that needed saying."],
 ["A knight rides slowly, holding his cup out ahead of him like an offering.","Romance and an approach made with grace. Following the heart at walking pace.","An offer with nothing behind it, or idealism that never touches ground."],
 ["A queen gazes into an ornate lidded cup at the water's edge, entirely absorbed.","Deep empathy and emotional intelligence. Able to hold what other people feel without drowning in it.","Overwhelm, absorbing everyone's weather, or care that has become control."],
 ["A king holds cup and sceptre on a throne afloat on a rough sea, robes dry.","Feeling fully felt but not in charge. Steadiness through other people's turbulence.","Suppression, manipulation, or calm that is only on the outside."]]},
swords:{
 el:"Air", blurb:"Mind, truth, communication, conflict. Swords cut both ways and most of them hurt.",
 pips:[
 ["A hand grips an upright sword crowned with laurel and palm, six drops falling.","A hard, clear thought. Truth cutting through, or a decision made and not revisited.","Confusion, or clarity used as a weapon."],
 ["A blindfolded woman holds two crossed swords, seated by moonlit water.","A stalemate held on purpose. Refusing to look directly at a choice you already know about.","The blindfold coming off; the deadlock breaking, one way or the other."],
 ["Three swords pierce a red heart against grey rain.","Plain heartbreak, and usually the words that caused it. The card does not soften anything.","The pain easing. Grief being actively worked through rather than sat in."],
 ["A knight lies in effigy on a tomb, three swords hung above him and one beneath.","Enforced rest. Recovery, retreat, the pause before the next round — not defeat.","Restlessness, burnout, or going back in too early."],
 ["A smirking man gathers up swords while two figures walk away with their backs turned.","Winning at a cost that wasn't worth it. Conflict where no side comes out clean.","Making amends, or accepting a defeat and moving on."],
 ["A ferryman poles a boat carrying a hooded passenger and six swords toward a calmer shore.","A difficult passage away from trouble. Things get quieter from here, but you had to leave to get it.","Baggage carried along; a move that solves nothing because the problem came too."],
 ["A man creeps away from a camp carrying five swords, leaving two stuck in the ground.","Strategy and evasion. Getting away with something — and the two swords you couldn't carry.","Being found out, or deciding to come clean."],
 ["A bound and blindfolded woman stands among eight swords planted in the mud.","Feeling trapped by a situation that has far more give in it than you think. The swords are not a cage.","Seeing the way out. The binding loosens."],
 ["A figure sits up in bed with their face in their hands; nine swords hang on the wall behind.","Anxiety at three in the morning. The dread is real; the scale of it is not.","The worst of it passing, or finally telling somebody."],
 ["A figure lies face down with ten swords in their back as dawn breaks over the water.","Rock bottom, theatrically so. It genuinely cannot get worse than this, and the sun is already coming up.","Recovery. Survival, and refusing to be finished off."]],
 court:[
 ["A youth brandishes a sword on windy high ground, glancing back over their shoulder.","Curiosity and sharp questions. Gathering information, sometimes before knowing why.","Snooping, cynicism, or words used to cut."],
 ["A knight charges headlong through a gale, sword raised, horse at full stretch.","Fast, direct and argumentative. Drives straight at the point and does not slow down for feelings.","Aggression, tactlessness, or charging at entirely the wrong hill."],
 ["A stern queen sits above the clouds, sword upright, one hand extended.","Unsentimental clarity. Honesty delivered kindly but never softened. Has been through something.","Coldness, bitterness, or criticism that has become a personality."],
 ["A king holds his sword slightly tilted, butterflies carved into his throne.","Judgement and intellectual authority. Principle chosen over preference, consistently.","Cold rule, argument treated as sport, or power used to win rather than decide."]]},
pentacles:{
 el:"Earth", blurb:"Work, money, the body, and everything with a physical result. Pentacles are slow and they last.",
 pips:[
 ["A hand offers a golden pentacle above a walled garden with a gate opening to mountains.","A tangible opportunity — an offer, a job, a seed of prosperity that is actually real.","A chance missed, or a plan with no foundation under it."],
 ["A young man dances, juggling two pentacles inside an infinity loop while ships ride high waves.","Balancing demands and keeping it all moving. Adaptable, but only just.","Dropping something. Overcommitted and about to find out."],
 ["A sculptor stands on a bench in a cathedral, conferring with two figures holding plans.","Skilled collaboration. Work recognised and built upon by people who know what they're looking at.","Mismatched effort, or a team pulling in different directions."],
 ["A crowned figure clutches one pentacle to his chest, stands on two, balances one on his head.","Holding on tight. Security, saving, control — bought at the price of being able to move.","Loosening the grip, or losing it whether you wanted to or not."],
 ["Two beggars pass a lit stained-glass window in the snow, one on crutches.","Hardship, and the specific feeling of being outside while others are warm. Help is nearer than it looks.","Recovery beginning, or finally asking for the help."],
 ["A merchant holds level scales in one hand while dropping coins to two kneeling figures.","Give and take. Generosity that is real, and a power difference inside it that is also real.","Strings attached, debt, or giving that only runs one way."],
 ["A man leans on his hoe, surveying a vine heavy with pentacles he has not picked.","Pausing to assess a long investment. Patience, and the honest question of whether to continue.","Impatience, or effort that has been going into the wrong field."],
 ["A craftsman chisels pentacles one at a time at his bench, seven finished, one in hand.","Repetition turning into mastery. The unglamorous middle stretch of getting genuinely good.","Sloppiness, or work that has had all the meaning drained out of it."],
 ["A woman in a walled garden of ripe vines rests a hand on a hooded falcon.","Comfort you made yourself. Independence, and the pleasure of enjoying it on your own terms.","Dependence, or wealth that came with no freedom attached."],
 ["Three generations and two dogs stand beneath an archway; ten pentacles fill the picture.","Durable wealth — legacy, family, the structures that outlast the person who built them.","Family friction over money, or thinking only as far as this month."]],
 court:[
 ["A youth stands in a green field studying a pentacle held carefully in both hands.","A student. A practical new venture taken seriously enough to learn it properly.","Procrastination, or learning that never gets applied to anything."],
 ["An armoured knight sits perfectly still on a heavy black horse, holding a pentacle out.","Methodical and reliable. Slow, unexciting, and it gets finished — the only knight not moving.","Stagnation, stubbornness, or work that has gone dull."],
 ["A queen on a throne carved with fruit and goats cradles a pentacle, a rabbit at her feet.","Practical nurture. Resourceful and grounded; makes the people around her materially safe.","Overwork, smothering, or looking after everyone except herself."],
 ["A king in a robe of vines rests one hand on a pentacle, his castle behind him.","Mastery of the material world. Wealth, stability, and provision you can actually depend on.","Greed, control exercised through money, or stubborn materialism."]]}
};
