/* ============================ astrology, deeper ============================
   Per sign: strengths, challenges, the sign as a Moon sign (how you feel and
   what you need), as a Rising sign (how you come across), and which signs
   tend to get along with it. Mainstream Western astrology, plain language. */
const ZDEEP = {
  ari: { compat: ['leo', 'sag', 'gem', 'aqu'],
    vi: { strengths: ['dám bắt đầu', 'thẳng thắn', 'nhiệt tình'], challenges: ['nóng vội', 'dễ chán', 'ít kiên nhẫn'],
      moon: 'Mặt Trăng Bạch Dương: cảm xúc đến nhanh và bùng nhanh. Bạn cần được tự do phản ứng và cần chuyện gì đó để lao vào. Giận dữ qua mau, nhưng người xung quanh có thể chưa kịp quên.',
      rising: 'Mọc Bạch Dương: người ta thấy bạn nhanh, thẳng, tự tin, hơi thiếu kiên nhẫn. Bạn bước vào phòng là muốn làm ngay việc gì đó. Cơ thể thường gọn, dáng đi dứt khoát.' },
    en: { strengths: ['starts things', 'direct', 'enthusiastic'], challenges: ['impatient', 'bored easily', 'short fuse'],
      moon: 'Moon in Aries: feelings arrive fast and burn fast. You need freedom to react and something to throw yourself into. Anger passes quickly, though others may not forget as fast.',
      rising: 'Aries rising: people see you as quick, direct, confident, a little impatient. You walk into a room ready to do something. Often a lean build and a decisive walk.' } },
  tau: { compat: ['vir', 'cap', 'can', 'pis'],
    vi: { strengths: ['bền bỉ', 'đáng tin', 'biết tận hưởng'], challenges: ['bướng', 'ngại thay đổi', 'giữ của'],
      moon: 'Mặt Trăng Kim Ngưu: bạn cần cảm giác chắc chắn để thấy yên. Ăn ngon, ngủ đủ, tiền có sẵn, người quen bên cạnh. Bạn ít khi khóc, nhưng khi tổn thương thì rất lâu lành.',
      rising: 'Mọc Kim Ngưu: bạn trông điềm tĩnh, ấm, dễ chịu, không vội. Giọng nói thường trầm và dễ nghe. Người ta tin bạn ngay từ ấn tượng đầu.' },
    en: { strengths: ['steady', 'reliable', 'enjoys life'], challenges: ['stubborn', 'resists change', 'possessive'],
      moon: 'Moon in Taurus: you need solid ground to feel calm. Good food, enough sleep, money in the account, familiar people. You rarely cry, but a hurt takes a long time to heal.',
      rising: 'Taurus rising: you come across calm, warm, easy, unhurried. Often a low, pleasant voice. People trust you at first sight.' } },
  gem: { compat: ['lib', 'aqu', 'ari', 'leo'],
    vi: { strengths: ['học nhanh', 'nói chuyện hay', 'thích nghi'], challenges: ['hay đổi ý', 'nông', 'lo lắng vặt'],
      moon: 'Mặt Trăng Song Tử: bạn xử lý cảm xúc bằng cách nói ra hoặc nghĩ về nó. Bạn cần được trò chuyện và được thay đổi không khí. Buồn mà ngồi im là tệ nhất với bạn.',
      rising: 'Mọc Song Tử: bạn trông trẻ, nhanh nhẹn, tò mò, hay cười. Tay và mắt chuyển động nhiều. Người ta thấy bạn dễ bắt chuyện.' },
    en: { strengths: ['learns fast', 'good talker', 'adaptable'], challenges: ['changes mind', 'skims the surface', 'nervous'],
      moon: 'Moon in Gemini: you process feelings by talking or thinking them through. You need conversation and a change of air. Sitting still while sad is the worst thing for you.',
      rising: 'Gemini rising: you look young, quick, curious, often smiling. Hands and eyes move a lot. People find you easy to start talking to.' } },
  can: { compat: ['sco', 'pis', 'tau', 'vir'],
    vi: { strengths: ['quan tâm', 'trực giác', 'trung thành'], challenges: ['hay giận dỗi', 'sống với quá khứ', 'khó nói thẳng'],
      moon: 'Mặt Trăng Cự Giải: Mặt Trăng ở nhà của nó. Cảm xúc của bạn rất mạnh và đổi theo từng ngày. Bạn cần một nơi an toàn để về, và cần được người thân cần đến.',
      rising: 'Mọc Cự Giải: bạn trông mềm, dịu, hơi kín, khuôn mặt tròn và dễ biểu cảm. Người ta thấy an tâm khi ở gần bạn, và hay kể chuyện cho bạn nghe.' },
    en: { strengths: ['caring', 'intuitive', 'loyal'], challenges: ['sulks', 'lives in the past', 'indirect'],
      moon: 'Moon in Cancer: the Moon is at home here. Your feelings are strong and shift day by day. You need a safe place to return to, and to be needed by the people you love.',
      rising: 'Cancer rising: you look soft, gentle, a little guarded, often a round and expressive face. People feel safe near you and tell you their stories.' } },
  leo: { compat: ['ari', 'sag', 'gem', 'lib'],
    vi: { strengths: ['ấm áp', 'rộng rãi', 'tự tin'], challenges: ['cần được khen', 'kiêu', 'kịch tính'],
      moon: 'Mặt Trăng Sư Tử: bạn cần được nhìn thấy và được trân trọng để thấy ổn. Bạn yêu bằng cả trái tim và bị tổn thương khi bị lơ. Vui thì cả nhà vui theo.',
      rising: 'Mọc Sư Tử: bạn bước vào là người ta để ý. Tóc hoặc phong thái nổi bật, nụ cười rộng. Bạn trông tự tin hơn bạn thật sự cảm thấy.' },
    en: { strengths: ['warm', 'generous', 'confident'], challenges: ['needs praise', 'proud', 'dramatic'],
      moon: 'Moon in Leo: you need to be seen and appreciated to feel right. You love wholeheartedly and hurt when ignored. When you are happy the whole house is.',
      rising: 'Leo rising: people notice when you walk in. Striking hair or bearing, a wide smile. You look more confident than you may feel.' } },
  vir: { compat: ['tau', 'cap', 'can', 'sco'],
    vi: { strengths: ['tỉ mỉ', 'giúp ích', 'thực tế'], challenges: ['lo lắng', 'khó tính', 'tự trách'],
      moon: 'Mặt Trăng Xử Nữ: bạn thấy yên khi mọi thứ ngăn nắp và hữu ích. Lo lắng là cách bạn quan tâm. Bạn cần được làm việc có ích và cần một thói quen ổn định.',
      rising: 'Mọc Xử Nữ: bạn trông gọn gàng, kín đáo, thông minh, hơi dè dặt. Người ta thấy bạn đáng tin và hay hỏi ý kiến bạn.' },
    en: { strengths: ['meticulous', 'helpful', 'practical'], challenges: ['worries', 'critical', 'hard on self'],
      moon: 'Moon in Virgo: you feel calm when things are in order and useful. Worry is how you care. You need useful work and a steady routine.',
      rising: 'Virgo rising: you look neat, reserved, intelligent, a little cautious. People find you reliable and ask your opinion.' } },
  lib: { compat: ['gem', 'aqu', 'leo', 'sag'],
    vi: { strengths: ['công bằng', 'duyên dáng', 'biết lắng nghe'], challenges: ['do dự', 'né xung đột', 'lệ thuộc ý người khác'],
      moon: 'Mặt Trăng Thiên Bình: bạn cần hoà thuận để thấy yên. Cãi nhau làm bạn mất ngủ. Bạn thấy rõ mình hơn khi có người bên cạnh, và cần cái đẹp xung quanh.',
      rising: 'Mọc Thiên Bình: bạn trông dễ mến, lịch sự, cân đối, ăn mặc có gu. Người ta thấy bạn dễ gần và hay được chọn làm người hoà giải.' },
    en: { strengths: ['fair', 'charming', 'listens'], challenges: ['indecisive', 'avoids conflict', 'leans on others'],
      moon: 'Moon in Libra: you need harmony to feel calm. Arguments cost you sleep. You see yourself more clearly with someone beside you, and you need beauty around you.',
      rising: 'Libra rising: you look likeable, polite, well-proportioned, well dressed. People find you approachable and pick you to make peace.' } },
  sco: { compat: ['can', 'pis', 'vir', 'cap'],
    vi: { strengths: ['sâu sắc', 'trung thành', 'bền gan'], challenges: ['ghen', 'giữ bí mật', 'khó tha thứ'],
      moon: 'Mặt Trăng Bọ Cạp: cảm xúc của bạn mạnh và kín. Bạn cần sự thật và sự trung thành tuyệt đối để thấy an toàn. Bạn nhớ rất lâu và tha thứ rất chậm.',
      rising: 'Mọc Bọ Cạp: ánh mắt của bạn là thứ người ta nhớ. Bạn trông bí ẩn, mạnh, hơi khó đoán. Người ta hoặc rất tin bạn hoặc hơi e dè.' },
    en: { strengths: ['deep', 'loyal', 'resilient'], challenges: ['jealous', 'secretive', 'slow to forgive'],
      moon: 'Moon in Scorpio: your feelings are intense and private. You need truth and total loyalty to feel safe. You remember for a long time and forgive slowly.',
      rising: 'Scorpio rising: your eyes are what people remember. You look mysterious, strong, hard to read. People either trust you completely or keep a little distance.' } },
  sag: { compat: ['ari', 'leo', 'lib', 'aqu'],
    vi: { strengths: ['lạc quan', 'thật thà', 'ham học'], challenges: ['thiếu tế nhị', 'hứa nhiều', 'sợ ràng buộc'],
      moon: 'Mặt Trăng Nhân Mã: bạn cần tự do và cần niềm tin rằng ngày mai tốt hơn. Buồn thì đi đâu đó, học gì đó. Bị bó buộc là điều làm bạn khổ nhất.',
      rising: 'Mọc Nhân Mã: bạn trông cởi mở, vui, thẳng, hay cười to. Dáng cao hoặc bước đi rộng. Người ta thấy bạn dễ kết bạn.' },
    en: { strengths: ['optimistic', 'honest', 'loves learning'], challenges: ['tactless', 'over-promises', 'fears ties'],
      moon: 'Moon in Sagittarius: you need freedom and faith that tomorrow will be better. When sad you travel or learn something. Being tied down hurts you most.',
      rising: 'Sagittarius rising: you look open, cheerful, direct, a loud laugh. Often tall or with a wide stride. People find you easy to befriend.' } },
  cap: { compat: ['tau', 'vir', 'sco', 'pis'],
    vi: { strengths: ['kỷ luật', 'trách nhiệm', 'kiên trì'], challenges: ['lạnh', 'nghiêm khắc', 'khó nhờ vả'],
      moon: 'Mặt Trăng Ma Kết: bạn giữ cảm xúc rất kỹ và thấy yên khi mọi việc trong tầm kiểm soát. Bạn cần được tôn trọng và cần thấy mình có ích. Học cách nghỉ là bài học của bạn.',
      rising: 'Mọc Ma Kết: bạn trông nghiêm túc, chững chạc, có phần già dặn khi còn trẻ và trẻ ra khi có tuổi. Người ta thấy bạn đáng tin và có thẩm quyền.' },
    en: { strengths: ['disciplined', 'responsible', 'persistent'], challenges: ['cold', 'stern', 'hates asking for help'],
      moon: 'Moon in Capricorn: you keep feelings well guarded and feel calm when things are under control. You need respect and to feel useful. Learning to rest is your lesson.',
      rising: 'Capricorn rising: you look serious, composed, older than your years when young and younger when older. People find you trustworthy and in charge.' } },
  aqu: { compat: ['gem', 'lib', 'ari', 'sag'],
    vi: { strengths: ['độc lập', 'sáng tạo', 'công tâm'], challenges: ['xa cách', 'cứng đầu', 'khó nói cảm xúc'],
      moon: 'Mặt Trăng Bảo Bình: bạn xử lý cảm xúc bằng lý trí và khoảng cách. Bạn cần không gian riêng và bạn bè hơn là gần gũi quá mức. Người ta hay tưởng bạn lạnh; thật ra bạn chỉ cần thời gian.',
      rising: 'Mọc Bảo Bình: bạn trông khác biệt, thân thiện nhưng hơi xa, có gu riêng. Người ta thấy bạn thú vị và khó đoán.' },
    en: { strengths: ['independent', 'inventive', 'fair-minded'], challenges: ['aloof', 'stubborn', 'struggles to voice feelings'],
      moon: 'Moon in Aquarius: you handle feelings with reason and distance. You need your own space and friends more than closeness. People think you are cold; you just need time.',
      rising: 'Aquarius rising: you look different, friendly but a little distant, with a style of your own. People find you interesting and hard to predict.' } },
  pis: { compat: ['can', 'sco', 'tau', 'cap'],
    vi: { strengths: ['thấu cảm', 'sáng tạo', 'bao dung'], challenges: ['trốn tránh', 'mơ hồ', 'dễ bị lợi dụng'],
      moon: 'Mặt Trăng Song Ngư: bạn cảm được cảm xúc của người khác như của mình. Bạn cần thời gian một mình để lọc lại, và cần nghệ thuật, nước, giấc ngủ. Ranh giới là bài học của bạn.',
      rising: 'Mọc Song Ngư: bạn trông mơ màng, dịu, đôi mắt to hoặc ướt, dễ thay đổi theo người đối diện. Người ta thấy bạn dễ thương và hay muốn bảo vệ bạn.' },
    en: { strengths: ['empathetic', 'creative', 'forgiving'], challenges: ['escapes', 'vague', 'easily used'],
      moon: 'Moon in Pisces: you feel other people\'s feelings as your own. You need time alone to filter them out, plus art, water and sleep. Boundaries are your lesson.',
      rising: 'Pisces rising: you look dreamy, gentle, big or liquid eyes, and you shift with whoever is in front of you. People find you lovable and want to protect you.' } }
};
/* Element pairs: same element flows; fire-air and earth-water support each other; the rest takes work. */
function signChemistry(a, b) {
  const ea = ZSIGN[a].el, eb = ZSIGN[b].el;
  if (ea === eb) return 'same';
  if ((ea === 'fire' && eb === 'air') || (ea === 'air' && eb === 'fire') || (ea === 'earth' && eb === 'water') || (ea === 'water' && eb === 'earth')) return 'support';
  return 'work';
}
const CHEM_TEXT = {
  same: { vi: 'cùng nguyên tố, dễ hiểu nhau nhưng cũng dễ giống nhau cả tật xấu', en: 'same element: easy to understand each other, and easy to share the same faults' },
  support: { vi: 'hai nguyên tố nuôi nhau, một bên cho năng lượng, một bên cho nền', en: 'two elements that feed each other, one bringing energy, the other ground' },
  work: { vi: 'hai nguyên tố khác nhịp, hợp được nhưng phải cố ý học cách của nhau', en: 'two elements with different rhythms; it works when both learn the other\'s way on purpose' }
};
