/* ==================== astrological correspondences ==================== */
/* Sourced, not invented. Majors, decans and court spans come from the
   Golden Dawn "Book T" (Mathers & Felkin, 1888) -- the system Waite and
   Smith worked inside. Lenormand carries its historical playing-card
   insets; it is given no zodiac signs, because none exist for it. */

const ZSIGN = {
  ari: {g:'♈', el:'fire', mod:'card', en:'Aries', vi:'Bạch Dương', den:'21 Mar – 19 Apr', dvi:'21/3 – 19/4', de:'Widder', dde:'21. März – 19. April'},
  tau: {g:'♉', el:'earth', mod:'fix', en:'Taurus', vi:'Kim Ngưu', den:'20 Apr – 20 May', dvi:'20/4 – 20/5', de:'Stier', dde:'20. April – 20. Mai'},
  gem: {g:'♊', el:'air', mod:'mut', en:'Gemini', vi:'Song Tử', den:'21 May – 20 Jun', dvi:'21/5 – 20/6', de:'Zwillinge', dde:'21. Mai – 20. Juni'},
  can: {g:'♋', el:'water', mod:'card', en:'Cancer', vi:'Cự Giải', den:'21 Jun – 22 Jul', dvi:'21/6 – 22/7', de:'Krebs', dde:'21. Juni – 22. Juli'},
  leo: {g:'♌', el:'fire', mod:'fix', en:'Leo', vi:'Sư Tử', den:'23 Jul – 22 Aug', dvi:'23/7 – 22/8', de:'Löwe', dde:'23. Juli – 22. August'},
  vir: {g:'♍', el:'earth', mod:'mut', en:'Virgo', vi:'Xử Nữ', den:'23 Aug – 22 Sep', dvi:'23/8 – 22/9', de:'Jungfrau', dde:'23. August – 22. September'},
  lib: {g:'♎', el:'air', mod:'card', en:'Libra', vi:'Thiên Bình', den:'23 Sep – 22 Oct', dvi:'23/9 – 22/10', de:'Waage', dde:'23. September – 22. Oktober'},
  sco: {g:'♏', el:'water', mod:'fix', en:'Scorpio', vi:'Bọ Cạp', den:'23 Oct – 21 Nov', dvi:'23/10 – 21/11', de:'Skorpion', dde:'23. Oktober – 21. November'},
  sag: {g:'♐', el:'fire', mod:'mut', en:'Sagittarius', vi:'Nhân Mã', den:'22 Nov – 21 Dec', dvi:'22/11 – 21/12', de:'Schütze', dde:'22. November – 21. Dezember'},
  cap: {g:'♑', el:'earth', mod:'card', en:'Capricorn', vi:'Ma Kết', den:'22 Dec – 19 Jan', dvi:'22/12 – 19/1', de:'Steinbock', dde:'22. Dezember – 19. Januar'},
  aqu: {g:'♒', el:'air', mod:'fix', en:'Aquarius', vi:'Bảo Bình', den:'20 Jan – 18 Feb', dvi:'20/1 – 18/2', de:'Wassermann', dde:'20. Januar – 18. Februar'},
  pis: {g:'♓', el:'water', mod:'mut', en:'Pisces', vi:'Song Ngư', den:'19 Feb – 20 Mar', dvi:'19/2 – 20/3', de:'Fische', dde:'19. Februar – 20. März'},
};

const ZPLANET = {
  sun: {g:'☉', en:'Sun', vi:'Mặt Trời', de:'Sonne'},
  moo: {g:'☽', en:'Moon', vi:'Mặt Trăng', de:'Mond'},
  mer: {g:'☿', en:'Mercury', vi:'Sao Thuỷ', de:'Merkur'},
  ven: {g:'♀', en:'Venus', vi:'Sao Kim', de:'Venus'},
  mar: {g:'♂', en:'Mars', vi:'Sao Hoả', de:'Mars'},
  jup: {g:'♃', en:'Jupiter', vi:'Sao Mộc', de:'Jupiter'},
  sat: {g:'♄', en:'Saturn', vi:'Sao Thổ', de:'Saturn'},
  ura: {g:'♅', en:'Uranus', vi:'Sao Thiên Vương', de:'Uranus'},
  nep: {g:'♆', en:'Neptune', vi:'Sao Hải Vương', de:'Neptun'},
  plu: {g:'♇', en:'Pluto', vi:'Sao Diêm Vương', de:'Pluto'},
};

const ZELEM = {
  fire: {g:'△', en:'Fire', vi:'Lửa', de:'Feuer'},
  water: {g:'▽', en:'Water', vi:'Nước', de:'Wasser'},
  air: {g:'△̵', en:'Air', vi:'Khí', de:'Luft'},
  earth: {g:'▽̵', en:'Earth', vi:'Đất', de:'Erde'},
};

const ZMODE = {
  card: {en:'Cardinal', vi:'Khởi đầu', de:'Kardinal'},
  fix: {en:'Fixed', vi:'Cố định', de:'Fix'},
  mut: {en:'Mutable', vi:'Biến đổi', de:'Veränderlich'},
};

const ZPIPSUIT = {
  h: {g:'♥', en:'Hearts', vi:'Cơ', col:'red', de:'Herz'},
  d: {g:'♦', en:'Diamonds', vi:'Rô', col:'red', de:'Karo'},
  c: {g:'♣', en:'Clubs', vi:'Chuồn', col:'black', de:'Kreuz'},
  s: {g:'♠', en:'Spades', vi:'Bích', col:'black', de:'Pik'},
};

/* One entry per card id. k = which kind of attribution, so the interface
   can render each honestly instead of flattening them all into "a sign". */
const ASTRO = {
  'major-0': {k:'elem', el:'air', outer:'ura'},
  'major-1': {k:'planet', planet:'mer'},
  'major-2': {k:'planet', planet:'moo'},
  'major-3': {k:'planet', planet:'ven'},
  'major-4': {k:'sign', sign:'ari'},
  'major-5': {k:'sign', sign:'tau'},
  'major-6': {k:'sign', sign:'gem'},
  'major-7': {k:'sign', sign:'can'},
  'major-8': {k:'sign', sign:'leo'},
  'major-9': {k:'sign', sign:'vir'},
  'major-10': {k:'planet', planet:'jup'},
  'major-11': {k:'sign', sign:'lib'},
  'major-12': {k:'elem', el:'water', outer:'nep'},
  'major-13': {k:'sign', sign:'sco'},
  'major-14': {k:'sign', sign:'sag'},
  'major-15': {k:'sign', sign:'cap'},
  'major-16': {k:'planet', planet:'mar'},
  'major-17': {k:'sign', sign:'aqu'},
  'major-18': {k:'sign', sign:'pis'},
  'major-19': {k:'planet', planet:'sun'},
  'major-20': {k:'elem', el:'fire', outer:'plu'},
  'major-21': {k:'planet', planet:'sat', el:'earth'},
  'wands-1': {k:'ace', el:'fire'},
  'wands-2': {k:'decan', planet:'mar', sign:'ari', dec:1, deg:'0°–10°', den:'21–30 Mar', dvi:'21–30/3', ten:'Dominion', tvi:'Thống Lĩnh', dde:'21.–30. März', tde:'Herrschaft'},
  'wands-3': {k:'decan', planet:'sun', sign:'ari', dec:2, deg:'10°–20°', den:'31 Mar – 9 Apr', dvi:'31/3 – 9/4', ten:'Established Strength', tvi:'Sức Mạnh Đã Vững', dde:'31. März – 9. April', tde:'Gefestigte Stärke'},
  'wands-4': {k:'decan', planet:'ven', sign:'ari', dec:3, deg:'20°–30°', den:'10–19 Apr', dvi:'10–19/4', ten:'Perfected Work', tvi:'Công Việc Hoàn Tất', dde:'10.–19. April', tde:'Vollendetes Werk'},
  'wands-5': {k:'decan', planet:'sat', sign:'leo', dec:1, deg:'0°–10°', den:'23 Jul – 1 Aug', dvi:'23/7 – 1/8', ten:'Strife', tvi:'Tranh Chấp', dde:'23. Juli – 1. August', tde:'Streit'},
  'wands-6': {k:'decan', planet:'jup', sign:'leo', dec:2, deg:'10°–20°', den:'2–11 Aug', dvi:'2–11/8', ten:'Victory', tvi:'Chiến Thắng', dde:'2.–11. August', tde:'Sieg'},
  'wands-7': {k:'decan', planet:'mar', sign:'leo', dec:3, deg:'20°–30°', den:'12–22 Aug', dvi:'12–22/8', ten:'Valour', tvi:'Dũng Khí', dde:'12.–22. August', tde:'Tapferkeit'},
  'wands-8': {k:'decan', planet:'mer', sign:'sag', dec:1, deg:'0°–10°', den:'22 Nov – 1 Dec', dvi:'22/11 – 1/12', ten:'Swiftness', tvi:'Sự Mau Lẹ', dde:'22. November – 1. Dezember', tde:'Schnelligkeit'},
  'wands-9': {k:'decan', planet:'moo', sign:'sag', dec:2, deg:'10°–20°', den:'2–11 Dec', dvi:'2–11/12', ten:'Great Strength', tvi:'Sức Mạnh Lớn', dde:'2.–11. Dezember', tde:'Große Stärke'},
  'wands-10': {k:'decan', planet:'sat', sign:'sag', dec:3, deg:'20°–30°', den:'12–21 Dec', dvi:'12–21/12', ten:'Oppression', tvi:'Sự Đè Nặng', dde:'12.–21. Dezember', tde:'Unterdrückung'},
  'wands-c1': {k:'court', sign:'leo', prev:'can', bookt:'Prince of Wands', booktde:'Prinz der Stäbe'},
  'wands-c2': {k:'court', sign:'ari', prev:'pis', bookt:'Queen of Wands', booktde:'Königin der Stäbe'},
  'wands-c3': {k:'court', sign:'sag', prev:'sco', bookt:'Knight of Wands', booktde:'Ritter der Stäbe'},
  'wands-c0': {k:'quad', el:'fire'},
  'cups-1': {k:'ace', el:'water'},
  'cups-2': {k:'decan', planet:'ven', sign:'can', dec:1, deg:'0°–10°', den:'21 Jun – 1 Jul', dvi:'21/6 – 1/7', ten:'Love', tvi:'Tình Yêu', dde:'21. Juni – 1. Juli', tde:'Liebe'},
  'cups-3': {k:'decan', planet:'mer', sign:'can', dec:2, deg:'10°–20°', den:'2–11 Jul', dvi:'2–11/7', ten:'Abundance', tvi:'Sung Túc', dde:'2.–11. Juli', tde:'Fülle'},
  'cups-4': {k:'decan', planet:'moo', sign:'can', dec:3, deg:'20°–30°', den:'12–22 Jul', dvi:'12–22/7', ten:'Blended Pleasure', tvi:'Niềm Vui Pha Tạp', dde:'12.–22. Juli', tde:'Gemischte Freude'},
  'cups-5': {k:'decan', planet:'mar', sign:'sco', dec:1, deg:'0°–10°', den:'23 Oct – 1 Nov', dvi:'23/10 – 1/11', ten:'Loss in Pleasure', tvi:'Mất Mát Trong Niềm Vui', dde:'23. Oktober – 1. November', tde:'Verlust in der Freude'},
  'cups-6': {k:'decan', planet:'sun', sign:'sco', dec:2, deg:'10°–20°', den:'2–11 Nov', dvi:'2–11/11', ten:'Pleasure', tvi:'Niềm Vui', dde:'2.–11. November', tde:'Freude'},
  'cups-7': {k:'decan', planet:'ven', sign:'sco', dec:3, deg:'20°–30°', den:'12–21 Nov', dvi:'12–21/11', ten:'Illusionary Success', tvi:'Thành Công Ảo', dde:'12.–21. November', tde:'Illusorischer Erfolg'},
  'cups-8': {k:'decan', planet:'sat', sign:'pis', dec:1, deg:'0°–10°', den:'19–28 Feb', dvi:'19–28/2', ten:'Abandoned Success', tvi:'Thành Công Bị Bỏ Lại', dde:'19.–28. Februar', tde:'Aufgegebener Erfolg'},
  'cups-9': {k:'decan', planet:'jup', sign:'pis', dec:2, deg:'10°–20°', den:'1–10 Mar', dvi:'1–10/3', ten:'Material Happiness', tvi:'Hạnh Phúc Vật Chất', dde:'1.–10. März', tde:'Materielles Glück'},
  'cups-10': {k:'decan', planet:'mar', sign:'pis', dec:3, deg:'20°–30°', den:'11–20 Mar', dvi:'11–20/3', ten:'Perpetual Success', tvi:'Thành Công Bền Lâu', dde:'11.–20. März', tde:'Beständiger Erfolg'},
  'cups-c1': {k:'court', sign:'sco', prev:'lib', bookt:'Prince of Cups', booktde:'Prinz der Kelche'},
  'cups-c2': {k:'court', sign:'can', prev:'gem', bookt:'Queen of Cups', booktde:'Königin der Kelche'},
  'cups-c3': {k:'court', sign:'pis', prev:'aqu', bookt:'Knight of Cups', booktde:'Ritter der Kelche'},
  'cups-c0': {k:'quad', el:'water'},
  'swords-1': {k:'ace', el:'air'},
  'swords-2': {k:'decan', planet:'moo', sign:'lib', dec:1, deg:'0°–10°', den:'23 Sep – 2 Oct', dvi:'23/9 – 2/10', ten:'Peace Restored', tvi:'Bình Yên Được Nối Lại', dde:'23. September – 2. Oktober', tde:'Wiederhergestellter Frieden'},
  'swords-3': {k:'decan', planet:'sat', sign:'lib', dec:2, deg:'10°–20°', den:'3–12 Oct', dvi:'3–12/10', ten:'Sorrow', tvi:'Nỗi Đau', dde:'3.–12. Oktober', tde:'Kummer'},
  'swords-4': {k:'decan', planet:'jup', sign:'lib', dec:3, deg:'20°–30°', den:'13–22 Oct', dvi:'13–22/10', ten:'Rest from Strife', tvi:'Nghỉ Ngơi Sau Tranh Chấp', dde:'13.–22. Oktober', tde:'Ruhe nach dem Streit'},
  'swords-5': {k:'decan', planet:'ven', sign:'aqu', dec:1, deg:'0°–10°', den:'20–29 Jan', dvi:'20–29/1', ten:'Defeat', tvi:'Thất Bại', dde:'20.–29. Januar', tde:'Niederlage'},
  'swords-6': {k:'decan', planet:'mer', sign:'aqu', dec:2, deg:'10°–20°', den:'30 Jan – 8 Feb', dvi:'30/1 – 8/2', ten:'Earned Success', tvi:'Thành Công Do Nỗ Lực', dde:'30. Januar – 8. Februar', tde:'Erarbeiteter Erfolg'},
  'swords-7': {k:'decan', planet:'moo', sign:'aqu', dec:3, deg:'20°–30°', den:'9–18 Feb', dvi:'9–18/2', ten:'Unstable Effort', tvi:'Nỗ Lực Không Vững', dde:'9.–18. Februar', tde:'Unbeständige Anstrengung'},
  'swords-8': {k:'decan', planet:'jup', sign:'gem', dec:1, deg:'0°–10°', den:'21–31 May', dvi:'21–31/5', ten:'Shortened Force', tvi:'Sức Bị Bó Hẹp', dde:'21.–31. Mai', tde:'Eingeschränkte Kraft'},
  'swords-9': {k:'decan', planet:'mar', sign:'gem', dec:2, deg:'10°–20°', den:'1–10 Jun', dvi:'1–10/6', ten:'Despair and Cruelty', tvi:'Tuyệt Vọng Và Tàn Nhẫn', dde:'1.–10. Juni', tde:'Verzweiflung und Grausamkeit'},
  'swords-10': {k:'decan', planet:'sun', sign:'gem', dec:3, deg:'20°–30°', den:'11–20 Jun', dvi:'11–20/6', ten:'Ruin', tvi:'Sụp Đổ', dde:'11.–20. Juni', tde:'Ruin'},
  'swords-c1': {k:'court', sign:'aqu', prev:'cap', bookt:'Prince of Swords', booktde:'Prinz der Schwerter'},
  'swords-c2': {k:'court', sign:'lib', prev:'vir', bookt:'Queen of Swords', booktde:'Königin der Schwerter'},
  'swords-c3': {k:'court', sign:'gem', prev:'tau', bookt:'Knight of Swords', booktde:'Ritter der Schwerter'},
  'swords-c0': {k:'quad', el:'air'},
  'pentacles-1': {k:'ace', el:'earth'},
  'pentacles-2': {k:'decan', planet:'jup', sign:'cap', dec:1, deg:'0°–10°', den:'22–31 Dec', dvi:'22–31/12', ten:'Harmonious Change', tvi:'Thay Đổi Hài Hoà', dde:'22.–31. Dezember', tde:'Harmonischer Wandel'},
  'pentacles-3': {k:'decan', planet:'mar', sign:'cap', dec:2, deg:'10°–20°', den:'1–10 Jan', dvi:'1–10/1', ten:'Material Works', tvi:'Việc Làm Vật Chất', dde:'1.–10. Januar', tde:'Materielles Wirken'},
  'pentacles-4': {k:'decan', planet:'sun', sign:'cap', dec:3, deg:'20°–30°', den:'11–19 Jan', dvi:'11–19/1', ten:'Earthy Power', tvi:'Quyền Lực Trần Thế', dde:'11.–19. Januar', tde:'Irdische Macht'},
  'pentacles-5': {k:'decan', planet:'mer', sign:'tau', dec:1, deg:'0°–10°', den:'20–29 Apr', dvi:'20–29/4', ten:'Material Trouble', tvi:'Khó Khăn Vật Chất', dde:'20.–29. April', tde:'Materielle Schwierigkeiten'},
  'pentacles-6': {k:'decan', planet:'moo', sign:'tau', dec:2, deg:'10°–20°', den:'30 Apr – 9 May', dvi:'30/4 – 9/5', ten:'Material Success', tvi:'Thành Công Vật Chất', dde:'30. April – 9. Mai', tde:'Materieller Erfolg'},
  'pentacles-7': {k:'decan', planet:'sat', sign:'tau', dec:3, deg:'20°–30°', den:'10–20 May', dvi:'10–20/5', ten:'Success Unfulfilled', tvi:'Thành Công Chưa Trọn', dde:'10.–20. Mai', tde:'Unerfüllter Erfolg'},
  'pentacles-8': {k:'decan', planet:'sun', sign:'vir', dec:1, deg:'0°–10°', den:'23 Aug – 1 Sep', dvi:'23/8 – 1/9', ten:'Prudence', tvi:'Sự Cẩn Trọng', dde:'23. August – 1. September', tde:'Umsicht'},
  'pentacles-9': {k:'decan', planet:'ven', sign:'vir', dec:2, deg:'10°–20°', den:'2–11 Sep', dvi:'2–11/9', ten:'Material Gain', tvi:'Lợi Ích Vật Chất', dde:'2.–11. September', tde:'Materieller Gewinn'},
  'pentacles-10': {k:'decan', planet:'mer', sign:'vir', dec:3, deg:'20°–30°', den:'12–22 Sep', dvi:'12–22/9', ten:'Wealth', tvi:'Sự Giàu Có', dde:'12.–22. September', tde:'Wohlstand'},
  'pentacles-c1': {k:'court', sign:'tau', prev:'ari', bookt:'Prince of Pentacles', booktde:'Prinz der Münzen'},
  'pentacles-c2': {k:'court', sign:'cap', prev:'sag', bookt:'Queen of Pentacles', booktde:'Königin der Münzen'},
  'pentacles-c3': {k:'court', sign:'vir', prev:'leo', bookt:'Knight of Pentacles', booktde:'Ritter der Münzen'},
  'pentacles-c0': {k:'quad', el:'earth'},
};

/* Lenormand: the printed playing-card inset only. No zodiac attribution is
   given because none is attested for the Petit Lenormand. */
const LASTRO = {
  1: {rank:'9', ps:'h'},
  2: {rank:'6', ps:'d'},
  3: {rank:'10', ps:'s'},
  4: {rank:'K', ps:'h'},
  5: {rank:'7', ps:'h'},
  6: {rank:'K', ps:'c'},
  7: {rank:'Q', ps:'c'},
  8: {rank:'9', ps:'d'},
  9: {rank:'Q', ps:'s'},
  10: {rank:'J', ps:'d'},
  11: {rank:'J', ps:'c'},
  12: {rank:'7', ps:'d'},
  13: {rank:'J', ps:'s'},
  14: {rank:'9', ps:'c'},
  15: {rank:'10', ps:'c'},
  16: {rank:'6', ps:'h', sky:'The card pictures stars, and is read as guidance, visibility and a good outcome. It is a picture of the night sky, not an attribution to a constellation or a sign.', skyvi:'Lá này vẽ những ngôi sao, được đọc là sự dẫn đường, sự hiển lộ và kết quả tốt. Đó là hình bầu trời đêm, không phải một chòm sao hay một cung nào được gán cho lá.'},
  17: {rank:'Q', ps:'h'},
  18: {rank:'10', ps:'h'},
  19: {rank:'6', ps:'s'},
  20: {rank:'8', ps:'s'},
  21: {rank:'8', ps:'c'},
  22: {rank:'Q', ps:'d'},
  23: {rank:'7', ps:'c'},
  24: {rank:'J', ps:'h'},
  25: {rank:'A', ps:'c'},
  26: {rank:'10', ps:'d'},
  27: {rank:'7', ps:'s'},
  28: {rank:'A', ps:'h'},
  29: {rank:'A', ps:'s'},
  30: {rank:'K', ps:'s'},
  31: {rank:'A', ps:'d', sky:'The card pictures the Sun, and is read as success, energy and certainty. It shares an image with the Sun of astrology but carries no sign attribution.', skyvi:'Lá này vẽ Mặt Trời, được đọc là thành công, năng lượng và sự chắc chắn. Nó trùng hình ảnh với Mặt Trời trong chiêm tinh nhưng không mang cung nào.'},
  32: {rank:'8', ps:'h', sky:'The card pictures the Moon, and is read as recognition, emotion and a one-month cycle. The month comes from the lunar cycle, which is also why it is the deck’s clearest timing card.', skyvi:'Lá này vẽ Mặt Trăng, được đọc là sự công nhận, cảm xúc và một chu kỳ một tháng. Con số một tháng đến từ chu kỳ mặt trăng — cũng là lý do đây là lá chỉ thời gian rõ nhất của bộ bài.'},
  33: {rank:'8', ps:'d'},
  34: {rank:'K', ps:'d'},
  35: {rank:'9', ps:'s'},
  36: {rank:'6', ps:'c'},
};

