/* ============================ visuals for guides and astrology ============================
   Every guide gets a picture or a small interactive block at the top, and the
   astrology tab gets wheels instead of lists. All drawn from the app's own data. */
const GUIDE_VISUAL = { 'tarot-start': 'steps', 'tarot-reversed': 'reversed', 'tarot-court': 'court', 'tarot-overview': 'journey', 'len-vs-tarot': 'lenvstarot', 'len-pairs': 'pairs',
  'astro-big3': 'big3', 'astro-elements': 'elements', 'astro-moon': 'moonphases', 'astro-retro': 'retro',
  'mani-what': 'steps', 'mani-tools': 'tools', 'mani-script': 'script', 'mani-369': 'tracker369', 'mani-gratitude': 'gratitude', 'mani-limits': 'checklist',
  'fort-numerology': 'numwheel', 'fort-palm': 'hand', 'fort-playing': 'pcmap', 'fort-animals': 'animals', 'fort-tea': 'cup',
  'mani-woop': 'woop', 'mani-vision': 'vision', 'mani-moon': 'moonritual', 'mani-action': 'ifthen', 'mani-letgo': 'steps' };
const EL_COLOR = { fire: '#E07A5F', earth: '#6A994E', air: '#7FB3E6', water: '#5B7DB1' };

function zodiacRingSVG(active, highlight) {
  let s = '<svg viewBox="0 0 240 240" class="zring">';
  s += '<circle cx="120" cy="120" r="100" fill="none" stroke="var(--rule)" stroke-width="1.5"/><circle cx="120" cy="120" r="66" fill="none" stroke="var(--rule-soft)" stroke-dasharray="3 5"/>';
  ZKEYS.forEach((k, i) => {
    const a = i / 12 * Math.PI * 2 - Math.PI / 2, x = 120 + 100 * Math.cos(a), y = 120 + 100 * Math.sin(a), z = ZSIGN[k];
    const on = k === active, hi = highlight && highlight.indexOf(k) > -1;
    s += '<g data-zsign="' + k + '" style="cursor:pointer"><circle cx="' + x.toFixed(1) + '" cy="' + y.toFixed(1) + '" r="' + (on ? 19 : 15) + '" fill="' + (on || hi ? EL_COLOR[z.el] : 'var(--surface)') + '" stroke="' + EL_COLOR[z.el] + '" stroke-width="2"/>'
      + '<text x="' + x.toFixed(1) + '" y="' + (y + 6).toFixed(1) + '" text-anchor="middle" font-size="' + (on ? 18 : 15) + '" fill="' + (on || hi ? '#fff' : 'var(--fg)') + '">' + z.g + '</text></g>';
  });
  return s + '</svg>';
}
function houseWheelSVG(active) {
  let s = '<svg viewBox="0 0 240 240" class="zring">';
  for (let h = 1; h <= 12; h++) {
    const a0 = Math.PI - (h - 1) / 12 * Math.PI * 2, a1 = a0 - Math.PI / 6; // houses run counter-clockwise from the left (the Ascendant)
    const x0 = 120 + 100 * Math.cos(a0), y0 = 120 + 100 * Math.sin(a0), x1 = 120 + 100 * Math.cos(a1), y1 = 120 + 100 * Math.sin(a1);
    const am = (a0 + a1) / 2, tx = 120 + 72 * Math.cos(am), ty = 120 + 72 * Math.sin(am);
    s += '<path d="M120 120 L' + x0.toFixed(1) + ' ' + y0.toFixed(1) + ' A100 100 0 0 0 ' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' Z" fill="' + (h === active ? 'var(--primary)' : (h % 2 ? 'var(--surface-2)' : 'var(--surface)')) + '" stroke="var(--rule)" data-house="' + h + '" style="cursor:pointer"/>'
      + '<text x="' + tx.toFixed(1) + '" y="' + (ty + 5).toFixed(1) + '" text-anchor="middle" font-size="13" font-weight="700" fill="' + (h === active ? 'var(--primary-ink)' : 'var(--fg)') + '" pointer-events="none">' + h + '</text>';
  }
  return s + '<circle cx="120" cy="120" r="34" fill="var(--surface)" stroke="var(--rule)"/><text x="120" y="116" text-anchor="middle" font-size="9" fill="var(--fg-faint)">AC</text><text x="120" y="128" text-anchor="middle" font-size="9" fill="var(--fg-faint)">←</text></svg>';
}
function aspectSVG(deg) {
  const a = -Math.PI / 2, b = a + deg * Math.PI / 180, x0 = 40 + 30 * Math.cos(a), y0 = 40 + 30 * Math.sin(a), x1 = 40 + 30 * Math.cos(b), y1 = 40 + 30 * Math.sin(b);
  return '<svg viewBox="0 0 80 80" class="asp"><circle cx="40" cy="40" r="30" fill="none" stroke="var(--rule)"/><line x1="' + x0.toFixed(1) + '" y1="' + y0.toFixed(1) + '" x2="' + x1.toFixed(1) + '" y2="' + y1.toFixed(1) + '" stroke="var(--primary)" stroke-width="2.5"/><circle cx="' + x0.toFixed(1) + '" cy="' + y0.toFixed(1) + '" r="5" fill="var(--primary)"/><circle cx="' + x1.toFixed(1) + '" cy="' + y1.toFixed(1) + '" r="5" fill="' + (deg ? 'var(--pink)' : 'var(--primary)') + '"/></svg>';
}
function planetOrbitSVG(activeId) {
  const order = ['sun', 'mer', 'ven', 'moo', 'mar', 'jup', 'sat', 'ura', 'nep', 'plu'];
  let s = '<svg viewBox="0 0 320 90" class="orbit">';
  order.forEach((id, i) => { const p = PLANETS.filter((x) => x.id === id)[0], x = 22 + i * 31, on = id === activeId; s += '<circle cx="' + x + '" cy="45" r="' + (on ? 16 : 12) + '" fill="' + (on ? 'var(--primary)' : 'var(--surface-2)') + '" stroke="var(--rule)"/><text x="' + x + '" y="50" text-anchor="middle" font-size="' + (on ? 16 : 13) + '" fill="' + (on ? 'var(--primary-ink)' : 'var(--fg)') + '">' + p.g + '</text><text x="' + x + '" y="78" text-anchor="middle" font-size="7.5" fill="var(--fg-faint)">' + esc(p.name[lang].replace('Sao ', '')) + '</text>'; });
  return s + '</svg>';
}

const TV = (vi, en) => lang === 'vi' ? vi : en;
const toolbar = (key, extra) => '<div class="toolbar">' + (extra || '') + '<button type="button" class="btn sm" data-clear="' + key + '">🗑 ' + esc(T().toolClear) + '</button><span class="faint">' + esc(T().toolSaved) + '</span></div>';
function scriptTemplate() {
  const d = new Date(), ds = pad2(d.getDate()) + '/' + pad2(d.getMonth() + 1);
  return lang === 'vi' ? 'Hôm nay, ' + ds + '\n\nMình vừa ______________________.\nMình thấy __________ và nghe __________.\nCảm giác lúc đó là __________.\n\nCảm ơn vì điều này. ♡' : 'Today, ' + ds + '\n\nI just ______________________.\nI saw __________ and heard __________.\nIt felt __________.\n\nThank you for this. ♡';
}
/* Redraw one guide's visual in place after a change. */
function redrawVisual(el) {
  const box = el.closest('.visual'), id = box && box.getAttribute('data-vid');
  if (!id) { route(); return; }
  box.innerHTML = guideVisualHTML(id); bindGuideVisual(box);
}
function guideVisualHTML(id) {
  const S = T(), v = GUIDE_VISUAL[id];
  if (!v) return '';
  if (v === 'journey') return journeyHTML();
  if (v === 'court') return courtHTML();
  if (v === 'pairs') return pairsHTML();
  if (v === 'numwheel') return '<div class="nwheel">' + [1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => '<a class="nw" href="#/learn/fortune/numbers"><span class="ic">' + NUM_ICON[n] + '</span><b>' + n + '</b><span>' + esc(NUM_KW[lang][n]) + '</span></a>').join('') + '</div>';
  if (v === 'hand') return '<div class="palmwrap"><a href="#/learn/fortune/palm">' + handSVG('heart', 'lines') + '</a></div>' + handShapesHTML();
  if (v === 'cup') return '<div class="teawrap"><a href="#/learn/fortune/tea">' + cupSVG('rim') + '</a></div>';
  if (v === 'animals') return '<div class="awrapper"><a href="#/learn/fortune/animals">' + animalsWheelSVG(-1) + '</a></div>';
  if (v === 'pcmap') return '<div class="pcmap">' + PC_SUITS.map((s) => '<a class="pcs" href="#/learn/fortune/cards"><span class="pip ' + (s[0] === 'h' || s[0] === 'd' ? 'red' : '') + '">' + s[1] + '</span><span>=</span><svg viewBox="-20 -22 40 44"><g stroke="var(--card-ink)" stroke-linejoin="round" stroke-linecap="round" fill="none">' + emblem(s[2], 0, 0, 1) + '</g></svg><b>' + esc(LEX[lang].suitNames[s[2]]) + '</b></a>').join('') + '</div>';
  if (v === 'steps') { const g = GUIDES.filter((x) => x.id === id)[0], lg = store.get('nabu-letgo', {}) || {}; return '<div class="stepsv">' + g.sections.map((s, i) => '<div class="stp"><span class="n">' + (i + 1) + '</span><b>' + esc(L(s.h)) + '</b></div>').join('<span class="arr">→</span>') + '</div>' + (id === 'mani-letgo' ? '<div class="letgo"><b>🍃 ' + esc(TV('Điều mình buông hôm nay', 'What I let go of today')) + '</b><textarea data-save="nabu-letgo" data-k="text" placeholder="' + esc(TV('một người, một chuyện, một kỳ vọng…', 'a person, a matter, an expectation…')) + '">' + esc(lg.text || '') + '</textarea><div class="toolbar"><button type="button" class="btn sm primary" data-release="nabu-letgo:text">🍃 ' + esc(T().toolRelease) + '</button><span class="faint">' + esc(T().releasedTimes(Number(store.get('nabu-letgo-n', 0)) || 0)) + '</span></div></div>' : ''); }
  if (v === 'tools') { const cs = [['#F7F3EA', TV('Trắng', 'White'), TV('mọi ý định, làm sạch', 'any intention, cleansing')], ['#5CB85C', TV('Xanh lá', 'Green'), TV('tiền bạc, phát triển', 'money, growth')], ['#F6A5C0', TV('Hồng', 'Pink'), TV('tình yêu, yêu mình', 'love, self-love')], ['#D9453D', TV('Đỏ', 'Red'), TV('đam mê, dũng khí', 'passion, courage')], ['#F2C744', TV('Vàng', 'Yellow'), TV('thành công, tự tin', 'success, confidence')], ['#8E62C9', TV('Tím', 'Purple'), TV('trực giác, tinh thần', 'intuition, spirit')], ['#4A90D9', TV('Xanh dương', 'Blue'), TV('bình an, chữa lành', 'calm, healing')], ['#F08A3E', TV('Cam', 'Orange'), TV('sáng tạo', 'creativity')], ['#2B2B2B', TV('Đen', 'Black'), TV('bảo vệ, buông bỏ', 'protection, release')]];
    const st = [['🌸', TV('Thạch anh hồng', 'Rose quartz'), TV('tình yêu, dịu dàng', 'love, gentleness')], ['🍋', 'Citrine', TV('sung túc, niềm vui', 'abundance, joy')], ['💎', TV('Thạch anh trắng', 'Clear quartz'), TV('khuếch đại, rõ ràng', 'amplify, clarity')], ['🔮', TV('Thạch anh tím', 'Amethyst'), TV('bình tĩnh, trực giác', 'calm, intuition')], ['🍀', TV('Aventurine xanh', 'Green aventurine'), TV('may mắn, cơ hội', 'luck, chances')], ['🪙', 'Pyrite', TV('tiền bạc, ý chí', 'money, will')], ['🛡️', TV('Tourmaline đen', 'Black tourmaline'), TV('bảo vệ', 'protection')], ['🕊️', 'Selenite', TV('làm sạch đá khác', 'cleanses other stones')], ['🔥', 'Carnelian', TV('năng lượng, can đảm', 'energy, courage')], ['🌙', TV('Đá mặt trăng', 'Moonstone'), TV('khởi đầu mới', 'new beginnings')]];
    return '<h3>🕯️ ' + esc(TV('Nến theo màu', 'Candles by colour')) + '</h3><div class="tgrid">' + cs.map((c) => '<div class="tc"><span class="dot" style="background:' + c[0] + '"></span><b>' + esc(c[1]) + '</b><span>' + esc(c[2]) + '</span></div>').join('') + '</div><h3>💎 ' + esc(TV('Đá theo mục đích', 'Stones by purpose')) + '</h3><div class="tgrid">' + st.map((c) => '<div class="tc"><span class="ic">' + c[0] + '</span><b>' + esc(c[1]) + '</b><span>' + esc(c[2]) + '</span></div>').join('') + '</div>'; }
  if (v === 'reversed') { const c = cardById('major-19'); return '<div class="cmp"><div><span class="face" style="width:110px">' + faceSVG(c) + '</span><b>' + esc(S.upright) + '</b></div><div><span class="face flipped" style="width:110px">' + faceSVG(c) + '</span><b>' + esc(S.reversed) + '</b></div></div>'; }
  if (v === 'lenvstarot') { return '<div class="cmp"><div><span class="face" style="width:110px">' + faceSVG(cardById('major-17')) + '</span><b>Tarot</b><span>' + esc(lang === 'vi' ? 'một cảnh, nhiều tầng' : 'a scene, many layers') + '</span></div><div><span class="face" style="width:110px">' + lenFace(16) + '</span><b>Lenormand</b><span>' + esc(lang === 'vi' ? 'một vật, một từ' : 'one thing, one word') + '</span></div></div>'; }
  if (v === 'big3') { const si = mySign(), k = si > -1 ? ZKEYS[si] : null; const disc = (lbl, g, sub) => '<div class="disc"><span class="g">' + g + '</span><b>' + esc(lbl) + '</b><span>' + esc(sub) + '</span></div>'; return '<div class="big3">' + disc(lang === 'vi' ? 'Mặt Trời' : 'Sun', k ? ZSIGN[k].g : '☉', k ? ZSIGN[k][lang] : (lang === 'vi' ? 'nhập ngày sinh' : 'add your birthday')) + disc(lang === 'vi' ? 'Mặt Trăng' : 'Moon', '☽', lang === 'vi' ? 'cần giờ sinh' : 'needs birth time') + disc(lang === 'vi' ? 'Mọc' : 'Rising', '↑', lang === 'vi' ? 'cần giờ + nơi sinh' : 'needs time + place') + '</div>'; }
  if (v === 'elements') return '<div class="elgrid">' + ['fire', 'earth', 'air', 'water'].map((el) => '<div class="elc" style="border-color:' + EL_COLOR[el] + '"><b style="color:' + EL_COLOR[el] + '">' + ZELEM[el].g + ' ' + esc(ZELEM[el][lang]) + '</b>' + ZKEYS.filter((k) => ZSIGN[k].el === el).map((k) => '<a href="#/learn/sign/' + k + '">' + ZSIGN[k].g + ' ' + esc(ZSIGN[k][lang]) + '</a>').join('') + '</div>').join('') + '</div>';
  if (v === 'moonphases') { const idx = moonPhase(new Date()).idx; return '<div class="phases">' + MOON_ICONS.map((ic, i) => '<div class="ph' + (i === idx ? ' on' : '') + '"><span class="ic">' + ic + '</span><span>' + esc(MOON_NAMES[lang][i]) + '</span></div>').join('') + '</div><p class="faint" style="text-align:center">' + esc(lang === 'vi' ? 'Hôm nay: ' : 'Today: ') + MOON_NAMES[lang][idx] + '</p>'; }
  if (v === 'retro') return '<svg viewBox="0 0 320 120" class="orbit"><circle cx="60" cy="60" r="22" fill="#F6C453"/><text x="60" y="66" text-anchor="middle" font-size="16">☉</text><ellipse cx="60" cy="60" rx="110" ry="40" fill="none" stroke="var(--rule)" stroke-dasharray="4 4"/><path d="M150 40 C 175 30, 190 55, 170 62 C 150 70, 160 90, 185 82" fill="none" stroke="var(--primary)" stroke-width="3" stroke-linecap="round"/><text x="230" y="60" font-size="13" fill="var(--fg)">☿ ' + esc(lang === 'vi' ? 'nhìn từ Trái Đất' : 'seen from Earth') + '</text><text x="230" y="78" font-size="10" fill="var(--fg-faint)">' + esc(lang === 'vi' ? 'có vẻ đi lùi' : 'appears to go backwards') + '</text></svg>';
  if (v === 'woop') { const w = store.get('nabu-woop', {}) || {}; return '<div class="woop edit">' + [['wish', 'W', TV('Mong muốn', 'Wish'), '🌱'], ['outcome', 'O', TV('Kết quả', 'Outcome'), '🌸'], ['obstacle', 'O', TV('Trở ngại', 'Obstacle'), '🪨'], ['plan', 'P', TV('Kế hoạch', 'Plan'), '🗺️']].map((x) => '<div class="wp"><span class="ic">' + x[3] + '</span><b>' + x[1] + '</b><span>' + esc(x[2]) + '</span><textarea data-save="nabu-woop" data-k="' + x[0] + '" placeholder="…">' + esc(w[x[0]] || '') + '</textarea></div>').join('') + '</div>' + toolbar('nabu-woop'); }
  if (v === 'vision') { const b = store.get('nabu-vision', {}) || {}; return '<div class="vboard">' + [['💗', TV('Tình cảm', 'Love')], ['💼', TV('Việc và tiền', 'Work and money')], ['🌿', TV('Sức khỏe', 'Health')], ['🏡', TV('Gia đình, bạn bè', 'Family and friends')], ['📚', TV('Học hỏi', 'Learning')], ['🛌', TV('Nghỉ ngơi', 'Rest')]].map((x, i) => '<div class="vb' + (b['img' + i] ? ' has' : '') + '"><div class="vtap" data-vtile="' + i + '">' + (b['img' + i] ? '<img src="' + esc(b['img' + i]) + '" alt="">' : '<span class="ic">' + x[0] + '</span>') + '<b>' + esc(x[1]) + '</b>' + (b['img' + i] ? '' : '<span class="ph">📷 ' + esc(T().tapPhoto) + '</span>') + '</div><input data-save="nabu-vision" data-k="cap' + i + '" placeholder="' + esc(T().caption) + '" value="' + esc(b['cap' + i] || '') + '">' + (b['img' + i] ? '<button type="button" class="x" data-vclear="' + i + '" aria-label="clear">✕</button>' : '') + '</div>').join('') + '</div><input type="file" accept="image/*" data-vfile hidden>' + toolbar('nabu-vision'); }
  if (v === 'moonritual') { const mo = store.get('nabu-moon', {}) || {}; return '<div class="ritual"><div class="rt"><span class="ic">🌑</span><b>' + esc(TV('Trăng non: gieo', 'New Moon: plant')) + '</b><span>' + esc(TV('viết 3 ý định · đọc to · cất đi', 'write 3 intentions · read aloud · put away')) + '</span></div><span class="arr">→ 14 ' + esc(TV('ngày', 'days')) + ' →</span><div class="rt"><span class="ic">🌕</span><b>' + esc(TV('Trăng tròn: buông', 'Full Moon: release')) + '</b><span>' + esc(TV('đọc lại · ghi bài học · xé tờ buông bỏ', 'reread · note the lesson · tear up the release note')) + '</span></div></div>'
    + '<div class="moonio"><div class="mi"><b>🌑 ' + esc(TV('Ba ý định trăng non', 'Three New Moon intentions')) + '</b>' + [0, 1, 2].map((i) => '<input data-save="nabu-moon" data-k="int' + i + '" placeholder="' + (i + 1) + '. ' + esc(TV('mình đang…', 'I am…')) + '" value="' + esc(mo['int' + i] || '') + '">').join('') + '</div>'
    + '<div class="mi"><b>🌕 ' + esc(TV('Điều mình buông kỳ này', 'What I release this time')) + '</b><textarea data-save="nabu-moon" data-k="rel" placeholder="' + esc(TV('viết ra, rồi xé đi…', 'write it, then tear it up…')) + '">' + esc(mo.rel || '') + '</textarea><button type="button" class="btn sm primary" data-release="nabu-moon:rel">🍃 ' + esc(TV('Xé đi', 'Tear it up')) + '</button></div></div>' + toolbar('nabu-moon'); }
  if (v === 'ifthen') { let rows = store.get('nabu-ifthen', null); if (!Array.isArray(rows) || !rows.length) rows = [['', ''], ['', ''], ['', '']]; const ph = [[TV('Nếu là 7 giờ sáng thứ Hai', 'If it is 7 a.m. on Monday'), TV('thì mình mở hồ sơ xin việc', 'then I open the application')], [TV('Nếu muốn cầm điện thoại sau bữa tối', 'If I reach for the phone after dinner'), TV('thì mình đi giày vào trước', 'then I put my shoes on first')], [TV('Nếu thấy sợ trước khi gọi', 'If I feel scared before the call'), TV('thì mình hít 3 hơi rồi bấm gọi', 'then I take 3 breaths and dial')]]; return '<div class="ifthen">' + rows.map((r, i) => '<div class="it edit"><input data-if="' + i + '" placeholder="' + esc((ph[i] || ph[0])[0]) + '" value="' + esc(r[0] || '') + '"><input data-then="' + i + '" placeholder="' + esc((ph[i] || ph[0])[1]) + '" value="' + esc(r[1] || '') + '"><button type="button" class="x" data-irm="' + i + '" aria-label="remove">✕</button></div>').join('') + '</div>' + toolbar('nabu-ifthen', '<button type="button" class="btn sm" data-iadd="1">+ ' + esc(T().toolAdd) + '</button>'); }
  if (v === 'script') { const sc = store.get('nabu-script', null); const text = sc && typeof sc.text === 'string' ? sc.text : scriptTemplate(); return '<div class="script"><div class="paper"><textarea data-save="nabu-script" data-k="text" rows="10">' + esc(text) + '</textarea></div></div>' + toolbar('nabu-script', '<button type="button" class="btn sm" data-tpl="1">✍️ ' + esc(T().toolTemplate) + '</button>'); }
  if (v === 'tracker369') { const t = store.get('nabu-369', { d: '', a: 0, b: 0, c: 0 }) || { d: '', a: 0, b: 0, c: 0 }, today = isoDate(new Date()); if (t.d !== today) { t.d = today; t.a = t.b = t.c = 0; } return '<div class="t369">' + [['a', 3, TV('Sáng', 'Morning')], ['b', 6, TV('Chiều', 'Afternoon')], ['c', 9, TV('Tối', 'Night')]].map((x) => '<button class="t3" data-t369="' + x[0] + '" data-max="' + x[1] + '"><b>' + x[2] + '</b><span class="cnt">' + t[x[0]] + ' / ' + x[1] + '</span><span class="dots">' + '●'.repeat(t[x[0]]) + '○'.repeat(x[1] - t[x[0]]) + '</span></button>').join('') + '</div><p class="faint" style="text-align:center">' + esc(TV('Mỗi lần viết xong một câu, chạm một lần. Tự về 0 mỗi ngày.', 'Tap once for each line you write. Resets every day.')) + '</p>' + toolbar('nabu-369'); }
  if (v === 'gratitude') { const g = store.get('nabu-gratitude', ['', '', '']) || ['', '', '']; return '<div class="grat"><b>' + esc(TV('Ba điều biết ơn hôm nay', 'Three things I am grateful for today')) + '</b>' + [0, 1, 2].map((i) => '<input data-grat="' + i + '" value="' + esc(g[i] || '') + '" placeholder="' + (i + 1) + '. ' + esc(TV('cụ thể nhé…', 'be specific…')) + '">').join('') + '</div>' + toolbar('nabu-gratitude'); }
  if (v === 'checklist') { const g = GUIDES.filter((x) => x.id === id)[0], ck = store.get('nabu-limits', {}) || {}; return '<div class="chk2">' + g.sections.slice(0, 2).map((s, i) => '<div class="col ' + (i ? 'good' : 'bad') + '"><b>' + (i ? '✓ ' : '✗ ') + esc(L(s.h)) + '</b>' + L(s.p).split(/\.\s+/).filter(Boolean).slice(0, 4).map((line, j) => '<label><input type="checkbox" data-chk="' + i + '-' + j + '"' + (ck[i + '-' + j] ? ' checked' : '') + '> ' + esc(line.replace(/\.$/, '')) + '</label>').join('') + '</div>').join('') + '</div>' + toolbar('nabu-limits'); }
  return '';
}
function bindGuideVisual(root) {
  bindCardLinks(root);
  $$('[data-t369]', root).forEach((b) => b.addEventListener('click', () => { const t = store.get('nabu-369', { d: isoDate(new Date()), a: 0, b: 0, c: 0 }), k = b.getAttribute('data-t369'), mx = Number(b.getAttribute('data-max')); t[k] = (t[k] + 1) % (mx + 1); t.d = isoDate(new Date()); store.set('nabu-369', t); $('.cnt', b).textContent = t[k] + ' / ' + mx; $('.dots', b).textContent = '●'.repeat(t[k]) + '○'.repeat(mx - t[k]); }));
  $$('[data-grat]', root).forEach((inp) => inp.addEventListener('input', () => { store.set('nabu-gratitude', $$('[data-grat]', root).map((x) => x.value)); }));
  // Every tool saves as you type, and can be cleared and redone.
  $$('[data-save]', root).forEach((inp) => inp.addEventListener('input', () => { const k = inp.getAttribute('data-save'), o = store.get(k, {}) || {}; o[inp.getAttribute('data-k')] = inp.value; store.set(k, o); }));
  $$('[data-clear]', root).forEach((b) => b.addEventListener('click', () => { const k = b.getAttribute('data-clear'); store.del(k); if (k === 'nabu-letgo') store.del('nabu-letgo-n'); toast(T().clearedToast); redrawVisual(b); }));
  $$('[data-tpl]', root).forEach((b) => b.addEventListener('click', () => { store.set('nabu-script', { text: scriptTemplate() }); redrawVisual(b); }));
  $$('[data-release]', root).forEach((b) => b.addEventListener('click', () => { const p = b.getAttribute('data-release').split(':'), o = store.get(p[0], {}) || {}; if (!String(o[p[1]] || '').trim()) return; o[p[1]] = ''; store.set(p[0], o); store.set('nabu-letgo-n', (Number(store.get('nabu-letgo-n', 0)) || 0) + 1); toast(T().toolReleased); redrawVisual(b); }));
  $$('[data-chk]', root).forEach((c) => c.addEventListener('change', () => { const o = store.get('nabu-limits', {}) || {}; o[c.getAttribute('data-chk')] = c.checked; store.set('nabu-limits', o); }));
  const rowsOf = () => { let r = store.get('nabu-ifthen', null); if (!Array.isArray(r) || !r.length) r = [['', ''], ['', ''], ['', '']]; return r; };
  $$('[data-if],[data-then]', root).forEach((inp) => inp.addEventListener('input', () => { const r = rowsOf(), i = Number(inp.getAttribute('data-if') != null ? inp.getAttribute('data-if') : inp.getAttribute('data-then')); r[i] = r[i] || ['', '']; r[i][inp.hasAttribute('data-if') ? 0 : 1] = inp.value; store.set('nabu-ifthen', r); }));
  $$('[data-iadd]', root).forEach((b) => b.addEventListener('click', () => { const r = rowsOf(); r.push(['', '']); store.set('nabu-ifthen', r); redrawVisual(b); }));
  $$('[data-irm]', root).forEach((b) => b.addEventListener('click', () => { const r = rowsOf(); r.splice(Number(b.getAttribute('data-irm')), 1); store.set('nabu-ifthen', r.length ? r : [['', '']]); redrawVisual(b); }));
  const vf = $('[data-vfile]', root); let vi = -1;
  $$('[data-vtile]', root).forEach((t) => t.addEventListener('click', () => { vi = Number(t.getAttribute('data-vtile')); if (vf) { vf.value = ''; vf.click(); } }));
  if (vf) vf.addEventListener('change', async () => { const f = vf.files && vf.files[0]; if (!f || vi < 0) return; try { const data = await shrinkImage(f, 520, 0.7); const o = store.get('nabu-vision', {}) || {}; o['img' + vi] = data; store.set('nabu-vision', o); redrawVisual(vf); } catch (e) { toast(T().publishFail); } });
  $$('[data-vclear]', root).forEach((b) => b.addEventListener('click', (e) => { e.stopPropagation(); const o = store.get('nabu-vision', {}) || {}; delete o['img' + b.getAttribute('data-vclear')]; store.set('nabu-vision', o); redrawVisual(b); }));
  $$('[data-len]', root).forEach((b) => b.addEventListener('click', () => { location.hash = '#/learn/len/' + b.getAttribute('data-len'); }));
}
