/* ============================ card insights, Vietnamese ============================
   Viết riêng bằng tiếng Việt, không dịch từ bản tiếng Anh. Câu ngắn, dễ hiểu.
   Fields: [từ khóa tích cực, từ khóa mặt trái, năng lượng lúc này, tình cảm,
   công việc, học tập, tiền bạc, lời khuyên]. Từ khóa cách nhau bằng "|". */
Object.assign(INSIGHT.vi, {
'major-0': ['khởi đầu mới|cởi mở|dũng cảm|dám bước', 'bất cẩn|ngây thơ|không có kế hoạch|trốn trách nhiệm',
  'Bạn đang đứng trước một điều mới. Háo hức nhiều hơn chắc chắn, và như vậy là bình thường. Năng lượng này bảo bạn hãy tin vào bước đầu tiên.',
  'Một người mới hoặc một cảm xúc mới đang tới, hoặc bạn đã sẵn sàng yêu mà không mang nỗi sợ cũ. Cứ vui, nhưng đừng hứa nhiều hơn điều bạn biết.',
  'Một dự án, vai trò hay hướng đi bạn chưa từng thử. Bạn sẽ vừa làm vừa học. Hỏi sớm, hỏi nhiều.',
  'Một môn mới hoặc cách học mới. Lúc này sự tò mò kéo bạn đi; kỷ luật tính sau.',
  'Một nguồn thu mới, hoặc muốn tiêu tiền cho một chuyến phiêu lưu. Để lại một khoản nhỏ phòng thân trước khi nhảy.',
  'Cứ bước, nhưng mang theo hành lý: một kế hoạch, một đường lui, rồi đi.'],
'major-1': ['kỹ năng|tập trung|chủ động|biến ý thành việc', 'khoe mẽ|thao túng|tài năng phân tán|nói nhiều làm ít',
  'Bạn đang có đủ mọi công cụ. Câu hỏi không phải "mình có làm được không" mà là "mình có làm không". Năng lượng của bạn sắc và mạnh.',
  'Lúc này bạn cuốn hút và thuyết phục. Hãy dùng điều đó thật lòng. Nói rõ bạn muốn gì thay vì chơi trò đoán.',
  'Người khác đang thấy khả năng của bạn. Trình bày ý tưởng, dẫn cuộc họp, bắt tay vào việc. Kết quả đến từ làm, không từ tính.',
  'Đầu óc bạn nhanh và tập trung được. Ngồi xuống và dùng nó trước khi cửa sổ này khép lại.',
  'Thời điểm tốt để biến kỹ năng thành tiền. Đặt giá, đưa ra lời đề nghị.',
  'Dồn mọi thứ bạn có vào một mục tiêu trong vài ngày tới và xem nó chuyển động.'],
'major-2': ['trực giác|tĩnh lặng|điều còn ẩn|kiên nhẫn', 'bí mật|thu mình|bỏ qua linh cảm|ngồi yên quá lâu',
  'Có điều gì đó chưa lộ ra. Linh cảm của bạn biết nhiều hơn những gì sự thật đang cho thấy. Đây là lúc lắng nghe, không phải lúc ép.',
  'Cảm xúc đang chảy ngầm, của bạn hoặc của người ấy. Đừng ép ai phải nói ra. Nhìn việc họ làm, đừng chỉ nghe họ nói.',
  'Có thông tin đang bị giữ lại ở đâu đó. Đọc giữa các dòng trước khi quyết định.',
  'Học một mình, yên tĩnh, hợp với bạn lúc này. Bạn hiểu sâu hơn điểm số đang thể hiện.',
  'Khoan ký, khoan chi. Có một chi tiết bạn chưa được nói.',
  'Để câu hỏi đó ở yên một ngày. Câu trả lời tới khi bạn thôi đòi hỏi.'],
'major-3': ['sung túc|nuôi dưỡng|dễ chịu|sáng tạo', 'hưởng thụ quá đà|bao bọc quá mức|bí ý tưởng|quên chăm mình',
  'Mọi thứ quanh bạn đang lớn lên và chủ yếu cần được nuôi, không cần sửa. Bạn được phép thấy dễ chịu. Điều bạn chăm sóc đang chín.',
  'Năng lượng ấm áp, rộng rãi, gần gũi. Mối quan hệ sâu thêm, hoặc sự quan tâm đang chảy về phía bạn. Hãy nhận.',
  'Một dự án ra quả. Việc sáng tạo được ủng hộ. Làm cùng người khác thay vì chống lại họ.',
  'Học vào khi bạn thoải mái và đủ nghỉ. Dọn góc học cho dễ chịu, việc học tự theo sau.',
  'Tiền vào dễ hơn bình thường. Hưởng một chút, để dành một chút, chia sẻ một chút.',
  'Tuần này hãy chăm cơ thể và không gian sống của bạn. Lớn lên đi sau chăm sóc.'],
'major-4': ['cấu trúc|ổn định|dẫn dắt|ranh giới', 'cứng nhắc|kiểm soát|lạnh lùng|không có kỷ luật nào',
  'Đây là năng lượng của trật tự và quyền hạn. Bạn được yêu cầu đặt luật, nắm quyền, hoặc tôn trọng người đang nắm quyền.',
  'Lúc này sự ổn định quan trọng hơn lãng mạn. Một người đáng tin, hoặc bạn cần đặt ranh giới rõ ràng.',
  'Đứng ra dẫn dắt, hoặc làm việc trong hệ thống. Kế hoạch, thứ bậc, kỷ luật thắng sự tuỳ hứng.',
  'Thời khoá biểu và thói quen giúp bạn nhiều hơn cảm hứng. Dựng khung trước.',
  'Ngân sách, kiểm soát, kế hoạch dài hạn. Tiền bạc lúc này đáp lại kỷ luật.',
  'Quyết định rồi giữ vững. Chỉ cần chắc rằng quyết định đó công bằng.'],
'major-5': ['truyền thống|chỉ dẫn|học hỏi|thuộc về', 'giáo điều|làm theo cho xong|phán xét người khác|nổi loạn vô cớ',
  'Những cách làm có sẵn đang nâng đỡ bạn: một người thầy, nếp nhà, một tổ chức. Làm theo cách quen thuộc lúc này cho bạn sự yên tâm.',
  'Cam kết, gia đình chấp thuận, hoặc một mối quan hệ có chung giá trị. Nói với nhau về điều hai người tin.',
  'Làm đúng quy trình. Một người hướng dẫn hay một bằng cấp chính thức giúp bạn. Đừng nhảy cóc.',
  'Học từ thầy giỏi và tài liệu chuẩn. Tuần này không phải lúc sáng tạo lại phương pháp.',
  'Chọn cách an toàn, quen thuộc với tiền. Lời khuyên của người có kinh nghiệm đáng giá.',
  'Hỏi người đã đi qua. Bản đồ của họ tiết kiệm cho bạn nhiều tháng.'],
'major-6': ['kết nối|lựa chọn|giá trị|hoà hợp', 'lệch pha|né tránh quyết định|cám dỗ|tình đơn phương',
  'Một cuộc gặp thật sự giữa hai điều, hoặc một lựa chọn cho thấy bạn thật sự coi trọng gì. Năng lượng này nói về sự hợp nhau, không chỉ là hấp dẫn.',
  'Một mối gắn bó mạnh, một lựa chọn quan trọng về người bạn đời, hoặc một lúc bạn phải quyết mình muốn gì từ tình yêu.',
  'Hợp tác và làm việc nhóm được ủng hộ. Một ngã rẽ giữa hai con đường: chọn con đường hợp với giá trị của bạn.',
  'Học cùng bạn học hoặc nhóm. Nếu phải chọn môn, chọn môn bạn thật sự quan tâm.',
  'Một quyết định tài chính thể hiện ưu tiên của bạn. Đừng chọn chỉ vì con số.',
  'Chọn bằng giá trị của bạn, không bằng nỗi sợ.'],
'major-7': ['ý chí|tiến tới|chiến thắng|có hướng', 'hung hăng|mất kiểm soát|lực phân tán|giẫm lên người khác',
  'Bạn đang chuyển động và đang thắng thế. Những lực kéo ngược đang được ý chí của bạn giữ cùng một hướng. Giữ tay lái.',
  'Theo đuổi điều bạn muốn, nhưng giữ được cảm xúc. Mối quan hệ tiến lên nhờ nỗ lực.',
  'Tham vọng và đà tiến. Vượt qua chướng ngại; bạn có đủ sức. Có thể có chuyến đi.',
  'Tuần này kỷ luật là sức mạnh của bạn. Đặt mục tiêu và lao tới.',
  'Tiền đến nhờ sự quyết tâm. Mục tiêu bạn theo đuổi đã trong tầm tay.',
  'Giữ cả hai dây cương: tự tin và kiểm soát cùng lúc.'],
'major-8': ['sức mạnh bên trong|kiên nhẫn|bao dung|can đảm', 'nghi ngờ bản thân|dùng sức ép|cảm xúc thô|thấy yếu là thấy xấu hổ',
  'Sức mạnh của bạn lúc này rất lặng. Kiên nhẫn và tử tế xử lý được thứ mà sức ép không làm nổi. Sư tử được thuần bằng sự bình tĩnh, không bằng tiếng hét.',
  'Sức mạnh dịu dàng sẽ thắng. Xử lý căng thẳng bằng kiên nhẫn thay vì phản ứng. Ai đó đang cần sự bình tĩnh của bạn.',
  'Đối diện một người hay một tình huống khó bằng sự điềm tĩnh. Sự vững của bạn được để ý.',
  'Hôm nay bền bỉ thắng thông minh. Cứ làm đều, bình tĩnh.',
  'Quản lý tiền đều tay thay vì nước cờ táo bạo. Đừng để nỗi sợ quyết định.',
  'Thở, rồi mới hành động. Phiên bản bình tĩnh của bạn là phiên bản mạnh nhất.'],
'major-9': ['nhìn lại|khôn ngoan|một mình|đi tìm', 'cô lập|cô đơn|thu mình quá lâu|từ chối giúp đỡ',
  'Lúc này cần lùi lại để nghĩ. Câu trả lời bạn cần nằm bên trong, không nằm ở thêm ý kiến. Một mình lúc này là có ích.',
  'Bạn hoặc người ấy cần không gian để nghĩ. Thời gian riêng không phải là từ chối. Gắn kết sâu hơn đến sau khi nhìn lại.',
  'Suy nghĩ kỹ trước bước tiếp theo. Một người đi trước hay kinh nghiệm của chính bạn soi đường. Tránh quyết định trong ồn ào.',
  'Học sâu, tập trung, một mình. Tắt thông báo đi.',
  'Xem lại tài chính một cách lặng lẽ và thành thật. Cần thì hỏi chuyên gia.',
  'Cho mình một buổi tối một mình với câu hỏi. Rồi quay lại với mọi người.'],
'major-10': ['thay đổi|may mắn|vòng quay|bước ngoặt', 'chống lại thay đổi|xui xẻo|thấy mất kiểm soát|lặp lại vòng cũ',
  'Bánh xe đang quay. Hoàn cảnh đang đổi dù bạn có đẩy hay không. Trong không khí có may mắn, và có thay đổi.',
  'Mối quan hệ bước sang giai đoạn mới. Dễ có gặp gỡ tình cờ. Gieo gì gặt nấy.',
  'Chờ đợi sự chuyển động: đổi vai trò, một cơ may, một ngã rẽ bất ngờ. Thích nghi thay vì cưỡng lại.',
  'Kết quả có thể lên xuống. Tận dụng lúc lên và đừng hoảng lúc xuống.',
  'Vận tiền đang đổi. Đừng đánh cược, nhưng hãy sẵn sàng đón cơ hội.',
  'Đi theo vòng quay. Chống lại bánh xe chỉ làm bạn mệt.'],
'major-11': ['công bằng|sự thật|chịu trách nhiệm|rõ ràng', 'bất công|không thật thà|né hậu quả|phán xét khắc nghiệt',
  'Nhân và quả đang hiện rõ. Quyết định lúc này có hậu quả, và chỉ có sự thật thà là hiệu quả.',
  'Thành thật về điều gì là công bằng giữa hai người. Cân bằng trở lại khi mỗi bên nhận phần của mình.',
  'Hợp đồng, pháp lý, đánh giá. Làm đúng quy định và lưu lại giấy tờ.',
  'Nỗ lực công bằng cho kết quả công bằng. Thành thật với mình về việc bạn đã thật sự làm bao nhiêu.',
  'Thanh toán sòng phẳng. Trả điều bạn nợ và thu điều người ta nợ bạn.',
  'Nói thật, nhất là với chính mình.'],
'major-12': ['tạm dừng|buông|góc nhìn mới|thả ra', 'giậm chân|tự làm khổ mình|do dự|tự chọn đứng yên',
  'Mọi thứ đang tạm dừng, và sự dừng này có mục đích. Nhìn từ góc khác, tình hình khác đi. Chờ một cách tự nguyện.',
  'Mối quan hệ đang lơ lửng. Đẩy không giúp gì. Buông kết quả và xem điều gì đổi.',
  'Chậm trễ hoặc dự án bị treo. Dùng thời gian này để nghĩ lại cách làm thay vì ép.',
  'Lùi khỏi bài toán. Lời giải xuất hiện khi bạn thôi nhìn chằm chằm.',
  'Chưa phải lúc động đến tiền. Giữ và xem lại.',
  'Cố ý không làm gì một lúc. Rồi nhìn lại.'],
'major-13': ['kết thúc|chuyển hoá|buông bỏ|đổi mới', 'níu kéo|sợ thay đổi|ứ đọng|kéo dài cái kết',
  'Một điều đang kết thúc để điều khác bắt đầu. Cảm giác nặng, nhưng năng lượng này đang dọn dẹp, không tàn nhẫn.',
  'Một mối quan hệ, hoặc một phiên bản của nó, đang khép lại. Buồn xong rồi, để hình hài mới hiện ra.',
  'Một vai trò, một dự án, một cách làm việc đóng lại. Đừng bám. Điều tiếp theo cần chỗ trống này.',
  'Một cách học cũ hay một mục tiêu cũ đã xong. Đổi cách học.',
  'Một chương tài chính khép lại. Cắt điều không còn hiệu quả và xây lại.',
  'Để nó kết thúc. Bạn không mở được chương mới khi còn giữ trang cuối.'],
'major-14': ['cân bằng|điều độ|kiên nhẫn|chữa lành', 'quá đà|mất cân bằng|nóng vội|ưu tiên chỏi nhau',
  'Pha trộn, đừng ép. Năng lượng của bạn là tìm con đường ở giữa và đi từ từ. Việc chữa lành đang diễn ra.',
  'Hoà hợp lớn lên nhờ kiên nhẫn và nhường nhau. Tránh cực đoan trong cảm xúc hay đòi hỏi.',
  'Làm nhóm ổn định và cân đối việc cẩn thận. Đừng vội. Kết hợp thế mạnh.',
  'Học đều nhịp tốt hơn nhồi. Cân bằng học và nghỉ.',
  'Tiêu vừa, để dành vừa. Không có nước cờ kịch tính.',
  'Mỗi thứ một ít, không thứ nào quá tay.'],
'major-15': ['gắn chặt|ham muốn|tham vọng|thật đến trần trụi', 'nghiện|ám ảnh|mẫu hình độc hại|thấy bị trói',
  'Có thứ đang nắm lấy bạn: một thói quen, một người, một ham muốn. Năng lượng này mạnh và không hẳn xấu, nhưng bạn cần nhìn thấy sợi xích.',
  'Sức hút dữ dội hoặc một mối gắn bó khó rời. Tự hỏi nó nuôi bạn hay rút cạn bạn.',
  'Tham vọng và động lực, hoặc một công việc đang sở hữu bạn. Xem bạn đang đổi gì để lấy tiền.',
  'Xao nhãng và trì hoãn đang mạnh. Gọi tên thói quen đang lấy mất thời gian của bạn.',
  'Coi chừng nợ, tiêu bốc đồng, hay tiền đi kèm điều kiện.',
  'Gọi tên thứ đang giữ bạn. Gọi tên được là xích lỏng ra.'],
'major-16': ['thay đổi đột ngột|sự thật lộ ra|bứt phá|tự do', 'đổ vỡ|sốc|sụp đổ có thể tránh|không chịu học bài học',
  'Thứ được xây trên nền lung lay đang đổ. Là cú sốc, nhưng cái đổ vốn không vững. Sự thật đang phá ra.',
  'Một biến cố bất ngờ hoặc một sự thật lộ ra. Đau, nhưng dọn sạch điều giả.',
  'Thay đổi đột ngột ở chỗ làm: kế hoạch sụp, cấu trúc bị thách thức. Xây lại trên nền chắc hơn.',
  'Kế hoạch tan. Đánh giá lại và dựng lịch từ đầu.',
  'Chi phí bất ngờ hoặc mất mát. Bảo vệ cái cơ bản trước.',
  'Để cái giả rơi. Xây lại bằng cái thật.'],
'major-17': ['hy vọng|chữa lành|cảm hứng|hồi phục', 'nản lòng|mất niềm tin|nghi ngờ mình|lạc quan rỗng',
  'Sau những điều khó, một sự bình yên đã tới. Hy vọng lúc này là thật, không phải gượng. Bạn đang được hồi phục.',
  'Lành lại sau tổn thương. Sự cởi mở quay về. Tình yêu thật thà và bình yên.',
  'Cảm hứng và cảm giác có mục đích. Thời điểm tốt cho kế hoạch sáng tạo và dài hạn.',
  'Động lực trở lại. Bạn thấy rõ vì sao mình học điều này.',
  'Khó khăn tiền bạc dịu đi. Cho đi hào phóng trong chừng mực.',
  'Tin vào niềm hy vọng lặng lẽ đó. Nó đang nói thật.'],
'major-18': ['trực giác|giấc mơ|chưa rõ|tiềm thức', 'ảo ảnh|lo âu|lừa dối|rối bời',
  'Chưa có gì rõ hoàn toàn. Nỗi sợ và trí tưởng tượng tô màu điều bạn thấy. Đi chậm và tin linh cảm, đừng tin lo lắng.',
  'Tín hiệu lẫn lộn và không chắc chắn. Có điều gì bị giấu. Đừng vội nghĩ xấu, nhưng hãy hỏi.',
  'Rối hoặc thông tin không rõ ở chỗ làm. Chờ sự thật rồi mới làm.',
  'Lo âu làm mờ hiểu biết. Ngủ đi, rồi xem lại khi đầu tỉnh.',
  'Chuyện tiền không rõ hoặc rủi ro. Đừng ký thứ bạn không hiểu hết.',
  'Đi chậm qua sương. Sương sẽ tan.'],
'major-19': ['niềm vui|thành công|rõ ràng|sức sống', 'kiêu ngạo|phô bày quá mức|hạnh phúc đến muộn|vui giả',
  'Năng lượng ấm, rõ, tự tin. Mọi thứ đang chạy và điều đó hiện ra. Cứ vui một cách công khai.',
  'Hạnh phúc, ấm áp, một kết nối dễ dàng. Mối quan hệ đang giữa ban ngày.',
  'Thành công, được ghi nhận, một chiến thắng rõ ràng. Công việc của bạn được nhìn thấy.',
  'Sáng rõ và tự tin. Kết quả tốt đang tới.',
  'May mắn và tăng trưởng. Tiền đến cùng niềm vui thay vì vật lộn.',
  'Nói có với điều tốt. Bạn xứng đáng.'],
'major-20': ['thức tỉnh|tiếng gọi|tha thứ|tổng kết', 'tự phán xét|từ chối tiếng gọi|hối tiếc|kẹt trong quá khứ',
  'Một khoảnh khắc nhìn rõ. Bạn được gọi tới một quyết định, một thay đổi, một tầng mới. Quá khứ được xem lại và thả ra.',
  'Mối quan hệ đến bước ngoặt. Tha thứ, quyết định, và đi tiếp.',
  'Một tiếng gọi trong sự nghiệp, một đợt đánh giá, một cơ hội đi lên. Hãy đáp lại.',
  'Kết quả và đánh giá. Học từ quá khứ và bước lên.',
  'Một đợt tổng kết tài chính. Đối diện con số và quyết định.',
  'Đáp lại tiếng gọi. Bạn đã biết nó là gì.'],
'major-21': ['hoàn tất|trọn vẹn|thành tựu|đi xa', 'việc dang dở|chậm trễ|thấy chưa đủ|đi tắt',
  'Một vòng khép lại. Bạn đã thấm bài học. Đây là sự viên mãn, và là cánh cửa sang vòng tiếp theo.',
  'Mối quan hệ đến giai đoạn trọn vẹn, chín chắn. Hoặc một chuyến đi cùng nhau.',
  'Hoàn thành một dự án lớn. Được công nhận, có thể đi xa hoặc làm việc với nước ngoài.',
  'Tốt nghiệp, hoàn thành, làm chủ một môn.',
  'Đạt mục tiêu tài chính. Vững lâu dài.',
  'Làm cho xong hẳn. Rồi ăn mừng trước khi bắt đầu việc mới.'],

'wands-1': ['tia lửa|cảm hứng|năng lượng mới|khao khát', 'khởi đầu hụt|không có hướng|chậm trễ|cháy hết sớm',
  'Một đợt dâng của ham muốn làm ra điều gì đó. Năng lượng thô, chưa nhắm vào đâu. Hãy chĩa nó vào một chỗ.',
  'Sức hút mới, đam mê, một tia lửa. Vui, và chưa phải lời hứa.',
  'Một ý tưởng hoặc lời đề nghị mới có năng lượng thật phía sau. Bắt đầu đi.',
  'Hứng thú với môn mới. Dùng nó trước khi nguội.',
  'Một ý tưởng kiếm tiền mới. Thử nhỏ trước.',
  'Nhóm lửa, rồi xây bếp.'],
'wands-2': ['lên kế hoạch|tầm nhìn|lựa chọn|chân trời rộng', 'chơi an toàn|sợ điều chưa biết|kế hoạch không bao giờ chạy',
  'Bạn đang cầm một thứ trong tay và nhìn ra xa hơn nó. Đến lúc chọn chân trời rộng hơn.',
  'Quyết định bạn muốn gì từ tình yêu, hoặc chọn giữa dễ chịu và một lựa chọn táo bạo hơn.',
  'Lên kế hoạch mở rộng, hợp tác, bước tiếp theo. Nghĩ lớn, rồi cam kết.',
  'Chọn hướng đi hoặc chuyên ngành. Lên kế hoạch cho cả năm, không chỉ tuần này.',
  'Lên kế hoạch đầu tư. Cân bằng an toàn và tăng trưởng.',
  'Quyết định hướng trước. Chi tiết tính sau.'],
'wands-3': ['mở rộng|nhìn xa|tiến triển|chờ đúng cách', 'chậm trễ|nóng vội|nghĩ quá nhỏ|không theo tới cùng',
  'Nỗ lực đầu tiên của bạn đã ra ngoài kia và đang có tác dụng. Giờ bạn chờ và chuẩn bị cho điều quay về.',
  'Điều đã khởi động đang phát triển. Cho nó thời gian. Có thể có chuyện ở xa.',
  'Tăng trưởng, thị trường mới, kết quả từ nỗ lực trước. Giữ mắt ở chân trời.',
  'Nền đã xong; kết quả đang trên đường.',
  'Lợi nhuận từ khoản đầu tư trước. Kiên nhẫn được đền đáp.',
  'Nhìn chân trời, đừng nhìn đồng hồ.'],
'wands-4': ['ăn mừng|mái nhà|ổn định|cộng đồng', 'bất ổn|căng thẳng trong nhà|kế hoạch bị huỷ|thấy không được chào đón',
  'Một cột mốc, một lần về nhà, một lý do để tụ họp. Niềm vui ổn định.',
  'Cam kết, dọn về ở chung, một buổi ăn mừng với người thân.',
  'Cột mốc của nhóm hoặc một nơi làm việc ổn định, ủng hộ nhau. Ăn mừng đi.',
  'Đạt một cột mốc. Nhóm học hoặc môi trường hỗ trợ.',
  'Tài chính ổn định. Mua sắm cho nhà cửa là hợp.',
  'Đánh dấu cột mốc. Rồi nghỉ.'],
'wands-5': ['cạnh tranh|tranh luận|năng lượng|thử sức', 'xung đột|hỗn loạn|cãi vì cãi|né cuộc tranh',
  'Nhiều năng lượng va vào nhau: ý kiến, cái tôi, kế hoạch. Không nguy hiểm, nhưng ồn. Cạnh tranh cho công bằng.',
  'Cãi vặt, ganh đua, hoặc quá nhiều khác biệt cùng lúc. Hãy tranh luận về chuyện thật.',
  'Cạnh tranh, ý kiến trái chiều, khó được lắng nghe. Ở lại trong cuộc chơi.',
  'Môi trường cạnh tranh hoặc tập trung bị chia. Chọn một trận.',
  'Nhiều nhu cầu giành nhau một khoản tiền. Sắp ưu tiên.',
  'Chọn trận đáng đánh và bỏ phần còn lại.'],
'wands-6': ['chiến thắng|được công nhận|tự tin|tiến bộ', 'cái tôi|từ đỉnh rơi xuống|không được nhìn thấy|thắng rỗng',
  'Một chiến thắng đang được để ý. Bạn đang dẫn trước và mọi người thấy. Tận hưởng sự công nhận.',
  'Cảm giác được ngưỡng mộ. Một mối quan hệ bạn tự hào.',
  'Thăng chức, lời khen, thành công trước mọi người. Nhận một cách lịch thiệp.',
  'Kết quả tốt và được công nhận. Sự tự tin có căn cứ.',
  'Một khoản thưởng hoặc thắng lợi tài chính.',
  'Nhận tràng vỗ tay, rồi tiếp tục cưỡi ngựa.'],
'wands-7': ['phòng thủ|bền bỉ|can đảm|giữ vững vị trí', 'bỏ cuộc|kiệt sức|thấy quá tải|phòng thủ thái quá',
  'Bạn đang giữ một vị trí trước áp lực. Mệt, nhưng bạn đang ở thế cao.',
  'Bảo vệ mối quan hệ hoặc nhu cầu của mình. Đứng vững mà không gây chiến.',
  'Cạnh tranh hoặc thách thức vị trí của bạn. Giữ đất bằng kỹ năng.',
  'Áp lực và thử thách. Đi tiếp; bạn mạnh hơn nỗi nghi ngờ.',
  'Bảo vệ điều bạn có trước những đòi hỏi. Biết nói không.',
  'Giữ vững, nhưng nhớ thở trong lúc giữ.'],
'wands-8': ['nhanh|tin tức|chuyển động|đà', 'chậm trễ|hỗn loạn|quyết vội|hiểu lầm',
  'Mọi thứ đang đi nhanh. Tin nhắn, đi lại, tiến triển bất ngờ. Theo kịp và giữ đầu tỉnh.',
  'Diễn biến nhanh, tin nhắn, một kết nối tiến nhanh. Trả lời đi.',
  'Tiến nhanh, tin tức, đi lại. Hành động nhanh với lời đề nghị.',
  'Tiến nhanh. Hạn sắp tới; làm ngay.',
  'Tiền đi nhanh. Cơ hội nhanh, chi tiêu cũng nhanh.',
  'Làm nhanh, nhưng giữ đầu lạnh.'],
'wands-9': ['bền bỉ|kiên trì|cảnh giác|nỗ lực cuối', 'đa nghi|kiệt sức|từ chối giúp đỡ|dựng rào',
  'Bạn mệt nhưng đã gần tới. Giữ điều bạn đã xây và bước bước cuối.',
  'Đề phòng sau tổn thương cũ. Bảo vệ mình, nhưng đừng rào hết mọi người.',
  'Sắp xong một chặng khó. Kiên trì. Đặt ranh giới.',
  'Cú nước rút cuối trước kỳ thi hay hạn nộp. Giữ nhịp.',
  'Bảo vệ khoản tiết kiệm. Cẩn thận với cam kết mới.',
  'Thêm một bước nữa. Rồi nghỉ, nghỉ thật.'],
'wands-10': ['trách nhiệm|gánh nặng|làm việc chăm|quyết tâm', 'quá tải|kiệt sức|gánh cho người khác|không giao việc',
  'Bạn đang mang nhiều, có lẽ quá nhiều. Gánh nặng là thật, sức bạn cũng thật. Có thứ đặt xuống được.',
  'Ôm hết phần cảm xúc trong mối quan hệ. Chia sẻ gánh nặng.',
  'Làm quá sức, quá nhiều việc. Giao bớt hoặc bỏ bớt.',
  'Lịch quá dày. Cắt còn điều quan trọng.',
  'Gánh nặng và nghĩa vụ tài chính. Đơn giản hoá.',
  'Hôm nay đặt xuống một thứ.'],
'wands-c0': ['nhiệt tình|khám phá|tin nhắn|ý tưởng mới', 'thiếu định hướng|nóng vội|non nớt|chậm trễ',
  'Tò mò, háo hức, hơi bồn chồn. Một ý tưởng hay tin nhắn mới đang tới. Khám phá nó.',
  'Một người tán tỉnh, một tin nhắn mới, một người trẻ trong tâm hồn. Vui, chưa nghiêm túc.',
  'Ý tưởng mới, vị trí tập sự, một tin vui về công việc.',
  'Tò mò và hăng hái. Khám phá chủ đề mới.',
  'Ý tưởng mới về tiền. Tìm hiểu trước khi đầu tư.',
  'Theo tia lửa và xem nó dẫn đi đâu.'],
'wands-c1': ['hành động|đam mê|phiêu lưu|cuốn hút', 'liều lĩnh|bốc đồng|kiêu ngạo|đi quá sớm',
  'Táo bạo, nhanh, cuốn hút, thiếu kiên nhẫn. Bạn sẵn sàng lao lên. Ngắm rồi hãy đi.',
  'Một người hoặc một giai đoạn đầy đam mê. Hấp dẫn, và không phải lúc nào cũng đáng tin.',
  'Hành động táo bạo, đi lại, nắm quyền. Coi chừng bốc đồng.',
  'Từng đợt năng lượng. Dồn vào một kế hoạch.',
  'Nước cờ tiền bạc táo bạo. Rủi ro. Xem kỹ chi tiết.',
  'Lao lên, nhưng biết vực ở đâu.'],
'wands-c2': ['ấm áp|tự tin|độc lập|có sức hút', 'ghen|đòi hỏi|kịch tính|cháy sạch',
  'Năng lượng ấm, tự tin, cuốn hút. Bạn đang thu hút sự chú ý. Dùng cho tốt.',
  'Một người bạn đời tự tin, ấm áp, hoặc chính sự tự tin dễ mến của bạn.',
  'Dẫn dắt bằng sự ấm áp. Truyền cảm hứng cho nhóm.',
  'Học tự tin, tự định hướng.',
  'Quản lý tiền tự tin. Độc lập.',
  'Toả sáng, và để người khác cũng được toả sáng.'],
'wands-c3': ['tầm nhìn|dẫn dắt|táo bạo|làm chủ', 'độc đoán|thiếu kiên nhẫn|kỳ vọng quá cao|tàn nhẫn',
  'Năng lượng lãnh đạo nhìn xa và táo bạo. Bạn đang đặt hướng đi. Dẫn bằng cảm hứng, không bằng mệnh lệnh.',
  'Một người bạn đời có sức hút, nhiều động lực, hoặc chính bạn dẫn dắt trong tình yêu.',
  'Dẫn dắt dự án. Tầm nhìn cộng hành động.',
  'Tự nắm lấy lộ trình học của mình.',
  'Tiền theo kiểu khởi nghiệp. Táo bạo mà có tính toán.',
  'Đi đầu, bằng trái tim.'],

'cups-1': ['tình cảm mới|khởi đầu cảm xúc|bao dung|sáng tạo', 'trống rỗng|cảm xúc bị chặn|thiếu yêu bản thân|cảm xúc tràn',
  'Trái tim bạn đang mở ra. Cảm xúc mới, lòng trắc ẩn mới, một khởi đầu sáng tạo hay tâm linh. Hãy nhận.',
  'Một tình yêu mới hoặc cảm xúc được làm mới. Sự cởi mở.',
  'Thoả mãn về cảm xúc trong công việc, khởi đầu sáng tạo, quan hệ tốt.',
  'Niềm vui trong việc học. Một môn sáng tạo đang gọi.',
  'Tiền từ việc bạn yêu thích. Sự hào phóng chảy.',
  'Để chiếc cốc đầy lên.'],
'cups-2': ['gắn kết|hấp dẫn hai chiều|kết nối|cân bằng', 'lệch cân|chia tay|hiểu lầm|một phía',
  'Một kết nối thật giữa hai người hoặc hai phía. Tôn trọng và hấp dẫn từ cả hai bên.',
  'Một mối gắn bó mạnh từ hai phía, hợp tác, một cuộc gặp có ý nghĩa.',
  'Hợp tác kinh doanh tốt hoặc một mối quan hệ làm việc vững.',
  'Bạn học hoặc người hướng dẫn hợp với bạn.',
  'Một hợp tác tài chính công bằng.',
  'Gặp nhau ở giữa; sẽ ổn.'],
'cups-3': ['tình bạn|ăn mừng|cộng đồng|sáng tạo', 'đàm tiếu|quá đà|người thứ ba|cô lập',
  'Năng lượng vui, đông người, ăn mừng. Bạn bè, tụ họp, niềm vui chung.',
  'Ăn mừng với bạn bè. Hoặc có người thứ ba trong bức tranh: kiểm lại.',
  'Làm nhóm, ăn mừng, hợp tác sáng tạo.',
  'Học nhóm hiệu quả. Ăn mừng tiến bộ.',
  'Chi cho đời sống xã hội. Vui trong chừng mực.',
  'Gọi cho bạn bè đi.'],
'cups-4': ['ngẫm nghĩ|thờ ơ|xem lại|chán', 'bỏ lỡ cơ hội|thu mình|vô ơn|tê liệt',
  'Bạn thấy chán, không ấn tượng, không chắc. Có lời đề nghị đang ở đó mà bạn không nhìn thấy. Ngước lên.',
  'Chán hoặc xa cách về cảm xúc. Có điều tốt đang bị bỏ qua.',
  'Không hài lòng, bỏ lỡ cơ hội. Xem lại bạn muốn gì.',
  'Mất động lực. Đổi cách tiếp cận.',
  'Bỏ lỡ cơ hội tiền bạc. Chú ý hơn.',
  'Nhìn điều đang được đưa ra trước khi từ chối.'],
'cups-5': ['đau buồn|hối tiếc|mất mát|chấp nhận', 'không chịu đi tiếp|thương thân|dằn vặt|cô lập',
  'Buồn vì điều đã mất. Nỗi buồn là thật. Nhưng không phải tất cả đã đổ; hai chiếc cốc vẫn đứng.',
  'Thất vọng hoặc mất mát trong tình yêu. Buồn xong, rồi quay lại.',
  'Một bước lùi hay thất vọng. Học và đi tiếp.',
  'Một kết quả kém. Chưa phải hết. Quay về điều còn lại.',
  'Mất tiền. Đánh giá phần còn lại.',
  'Quay lại. Hai cốc vẫn còn đầy.'],
'cups-6': ['hoài niệm|hồn nhiên|tử tế|quá khứ', 'kẹt trong quá khứ|ngây thơ|ký ức tô hồng|níu kéo',
  'Ký ức ngọt, sự tử tế, một điều hồn nhiên quay về. Quá khứ ghé thăm nhẹ nhàng.',
  'Người xưa, sự ngọt ngào thời thơ ấu, hoặc tình cảm giản dị.',
  'Mối quan hệ cũ quay lại. Sự tử tế ở nơi làm. Vai trò quen thuộc.',
  'Ôn lại căn bản. Kiến thức cũ giúp ích.',
  'Một món quà, hoặc tiền từ quá khứ.',
  'Tận hưởng ký ức. Sống ở hiện tại.'],
'cups-7': ['lựa chọn|tưởng tượng|mơ mộng|khả năng', 'ảo tưởng|mơ hão|quá nhiều lựa chọn|trốn thực tế',
  'Nhiều lựa chọn và mộng tưởng. Không phải tất cả đều thật. Chọn bằng mắt sáng.',
  'Mộng tưởng và thực tế trong tình yêu. Lý tưởng hoá ai đó. Nhìn họ cho rõ.',
  'Quá nhiều khả năng. Tập trung vào một con đường thực tế.',
  'Xao nhãng và mơ mộng. Chọn một việc.',
  'Mộng tưởng về tiền. Làm phép tính đi.',
  'Chọn một chiếc cốc, với đôi mắt mở.'],
'cups-8': ['bước đi|tìm điều hơn|buông bỏ|tìm sâu hơn', 'sợ thay đổi|vô định|bỏ chạy|ở lại quá lâu',
  'Bỏ lại một thứ để tìm điều sâu hơn. Vừa là mất, vừa là giải thoát.',
  'Bước khỏi điều không còn làm bạn đủ đầy. Khó và đúng.',
  'Rời một công việc hay vai trò để tìm điều ý nghĩa hơn.',
  'Đổi hướng. Bỏ điều không hợp.',
  'Rời khỏi tình trạng tài chính đang rút cạn bạn.',
  'Đi đi. Điều bạn tìm không ở đây.'],
'cups-9': ['hài lòng|mãn nguyện|ước thành|tận hưởng', 'tự mãn|hưởng thụ quá đà|vui nông|vẫn chưa đủ',
  'Điều ước thành, dễ chịu và tận hưởng. Bạn có điều bạn đã xin. Hưởng đi.',
  'Thoả mãn về cảm xúc, niềm vui trong tình yêu.',
  'Thành tựu và hài lòng trong công việc.',
  'Thành công và hài lòng với kết quả.',
  'Tài chính dễ chịu. Tự thưởng, khôn ngoan.',
  'Tận hưởng. Bạn xin, nó đến.'],
'cups-10': ['hoà thuận|gia đình|hạnh phúc lâu dài|thuộc về', 'gia đình rạn|bất hoà|kỳ vọng phi thực tế|lơ là',
  'Hạnh phúc sâu, chung, bền. Gia đình, mái nhà, sự đủ đầy về cảm xúc.',
  'Một mối quan hệ yêu thương, cam kết. Gia đình hoà thuận.',
  'Công việc đủ đầy và quan hệ tốt với đồng nghiệp.',
  'Gia đình ủng hộ việc học.',
  'An toàn tài chính cho gia đình.',
  'Đây là điều tốt. Giữ nhẹ tay.'],
'cups-c0': ['sáng tạo|trực giác|thông điệp cảm xúc|nhạy cảm', 'non nớt về cảm xúc|thất thường|bí ý tưởng|trốn thực tế',
  'Một thông điệp hay xung động dịu dàng, giàu tưởng tượng. Có điều mới đang khẽ động trong tim bạn.',
  'Một tin nhắn ngọt, một crush, một khởi đầu dịu dàng.',
  'Ý tưởng sáng tạo hoặc một thông điệp cảm xúc ở nơi làm.',
  'Học bằng trực giác. Nghệ thuật và sáng tạo.',
  'Một món quà nhỏ bất ngờ.',
  'Lắng nghe cảm giác nhỏ đó.'],
'cups-c1': ['lãng mạn|duyên dáng|theo trái tim|lý tưởng', 'thất thường|phi thực tế|ghen|lừa dối',
  'Năng lượng lãng mạn, duyên dáng, lý tưởng. Đi theo trái tim. Kiểm xem chân còn chạm đất không.',
  'Một lời tỏ tình lãng mạn hoặc một người theo đuổi duyên dáng. Vui, nhưng coi chừng ảo ảnh.',
  'Dự án sáng tạo và cách tiếp cận khéo léo.',
  'Học có cảm hứng. Nghệ thuật, âm nhạc, văn chương.',
  'Chi tiêu theo cảm xúc. Dừng lại trước khi mua.',
  'Theo trái tim với đôi mắt mở.'],
'cups-c2': ['bao dung|bình tĩnh|trực giác|an toàn cảm xúc', 'bất an|lệ thuộc|hy sinh quá mức|quá tải',
  'Năng lượng bình tĩnh, quan tâm, trực giác. Bạn hiểu người khác và hiểu mình. Chăm mình nữa.',
  'Một người bạn đời biết chăm sóc, yêu thương, hoặc chính sự chín chắn cảm xúc của bạn.',
  'Thấu cảm và trực giác dẫn đường công việc. Hỗ trợ đồng nghiệp.',
  'Học bằng hiểu, không bằng thuộc lòng.',
  'Chọn tiền bằng trực giác. Lo cho sự an toàn.',
  'Chăm người khác, nhưng để lại một phần cho mình.'],
'cups-c3': ['cân bằng cảm xúc|khéo léo|khôn ngoan|bao dung', 'thao túng cảm xúc|thất thường|dễ bùng|lạnh',
  'Làm chủ cảm xúc một cách chín chắn. Cảm xúc mạnh nhưng được giữ bằng sự khôn ngoan.',
  'Một người bạn đời chín chắn, cân bằng về cảm xúc. Bao dung trong tình yêu.',
  'Khéo léo và dẫn dắt bình tĩnh. Đối xử với người khác cẩn thận.',
  'Cách học cân bằng, khôn ngoan.',
  'Quản lý tiền cân bằng, khôn ngoan.',
  'Cảm sâu, làm điềm tĩnh.'],

'swords-1': ['rõ ràng|sự thật|bứt phá|ý tưởng mới', 'rối|lạm dụng sức mạnh|lời cay nghiệt|phán đoán mờ',
  'Một khoảnh khắc đầu óc sáng rõ. Sự thật cắt xuyên qua. Ý tưởng mới, suy nghĩ quyết đoán.',
  'Những cuộc nói chuyện thẳng thắn. Rõ ràng về điều bạn muốn.',
  'Một ý tưởng đột phá. Quyết định rõ ràng.',
  'Suy nghĩ sắc. Một cách hiểu mới.',
  'Tư duy tài chính rõ ràng. Một kế hoạch quyết đoán.',
  'Nói điều thật, một cách tử tế.'],
'swords-2': ['do dự|bế tắc|cân nhắc|đình chiến', 'né tránh|chối bỏ|tê liệt|trốn',
  'Bạn kẹt giữa hai lựa chọn và đang né việc chọn. Tấm bịt mắt là của bạn, bạn tháo được.',
  'Né một quyết định về mối quan hệ. Đối diện đi.',
  'Bế tắc hoặc một quyết định bạn đang tránh. Thu thập sự thật, rồi chọn.',
  'Giằng co giữa các lựa chọn. Chọn một và đi.',
  'Quyết định tài chính đang treo. Quyết đi.',
  'Tháo bịt mắt và chọn.'],
'swords-3': ['tan vỡ|đau buồn|sự thật đau|giải toả', 'ôm nỗi đau|cay đắng|tự làm mình đau|không chịu lành',
  'Một nỗi đau sắc, thường từ sự thật hoặc mất mát. Nó đau, và nó làm rõ. Để nó ra.',
  'Tan vỡ, bị phản bội, một sự thật đau. Cảm nhận nó, rồi lành lại.',
  'Một bước lùi đau hoặc lời phê bình nặng. Học và hồi phục.',
  'Thất vọng. Đau nhưng tạm thời.',
  'Một khoản mất đau. Hồi phục và xây lại.',
  'Để nước mắt ra. Rồi mới lành.'],
'swords-4': ['nghỉ|hồi phục|ngẫm|rút lui', 'kiệt sức|bồn chồn|cô lập|né hành động',
  'Cần nghỉ. Rút lui, hồi phục, suy nghĩ. Không phải lúc chiến đấu.',
  'Một khoảng lặng trong mối quan hệ. Lấy lại năng lượng.',
  'Nghỉ một chút. Hồi phục trước thử thách tiếp theo.',
  'Nghỉ trước khi học tiếp. Đầu bạn cần nó.',
  'Tạm dừng chuyện tiền. Xem lại trong yên lặng.',
  'Nghỉ. Nghỉ thật.'],
'swords-5': ['xung đột|thua|thắng mà trả giá|căng thẳng', 'thù địch|bắt nạt|không ai thắng|bẽ mặt',
  'Một cuộc xung đột không ai thật sự thắng. Tự hỏi trận này có đáng không.',
  'Cãi nhau và lời làm tổn thương. Thắng cuộc cãi có thể mất mối quan hệ.',
  'Xung đột ở nơi làm, một chiến thắng rỗng. Chọn trận mà đánh.',
  'Ganh đua làm đau. Tập trung vào đường của mình.',
  'Tranh chấp tiền bạc. Đừng cãi vì chuyện nhỏ.',
  'Rời khỏi trận không thắng nổi, một cách đàng hoàng.'],
'swords-6': ['chuyển tiếp|đi tiếp|lành|nước lặng hơn', 'kẹt|hành lý chưa xong|chống thay đổi|chuyến đi khó',
  'Rời vùng nước động sang vùng lặng hơn. Một sự chuyển tiếp, lặng lẽ và cần thiết.',
  'Đi tiếp sau khó khăn. Lành lại, có thể có khoảng cách.',
  'Chuyển sang tình huống tốt hơn. Có thể có chuyến đi.',
  'Qua một giai đoạn khó. Tiến bộ.',
  'Tài chính hồi phục dần.',
  'Chèo về phía bình yên. Nó ở đó.'],
'swords-7': ['chiến lược|khôn khéo|tự lập|lách được', 'lừa dối|trộm|tự lừa mình|bị bắt',
  'Chiến lược, lặng lẽ, tự làm. Đôi khi khôn, đôi khi lén. Kiểm lại động cơ của bạn.',
  'Bí mật hoặc lừa dối trong mối quan hệ. Thật thà an toàn hơn.',
  'Chiến lược và độc lập. Hoặc có ai đó không thẳng thắn.',
  'Đường tắt. Cẩn thận kẻo phản tác dụng.',
  'Coi chừng lừa đảo. Khôn khéo với tiền.',
  'Khôn, nhưng đừng lén.'],
'swords-8': ['thấy bị trói|hạn chế|niềm tin tự giới hạn|bất lực', 'tâm lý nạn nhân|tê liệt|tự giam|tự phá',
  'Bạn thấy bị trói, nhưng dây lỏng hơn vẻ ngoài. Nhà tù phần lớn nằm trong đầu.',
  'Thấy kẹt trong mối quan hệ. Bạn có nhiều lựa chọn hơn bạn nghĩ.',
  'Thấy bị bó ở nơi làm. Tìm lối ra bạn chưa nhìn thấy.',
  'Thấy quá tải. Chia việc thành bước nhỏ.',
  'Tiền bị bó. Tìm phương án.',
  'Dây lỏng rồi. Cử động đi.'],
'swords-9': ['lo âu|lo lắng|ác mộng|tội lỗi', 'tuyệt vọng|mất hy vọng|nghĩ tới điều tệ nhất|cô lập',
  'Lo lắng đang làm bạn mất ngủ. Phần lớn nỗi sợ lớn hơn sự thật. Tìm người để nói.',
  'Lo âu về mối quan hệ. Nói chuyện thay vì xoáy trong đầu.',
  'Căng thẳng và lo về công việc. Kiểm lại tình hình thật.',
  'Lo thi. Chuẩn bị, rồi ngủ.',
  'Lo tiền. Lập kế hoạch và chia sẻ gánh nặng.',
  'Bật đèn lên. Quái vật nhỏ lại.'],
'swords-10': ['chạm đáy|kết thúc|phản bội|điều tệ nhất đã qua', 'hồi phục|chống lại cái kết|làm quá|sống sót',
  'Một cái kết đau, đã tới hẳn. Xong rồi. Và vì đã xong, bình minh đang tới.',
  'Một cái kết đau và dứt khoát. Buồn rồi lành; điều tệ nhất đã qua.',
  'Một dự án hay công việc kết thúc tệ. Hồi phục và bắt đầu lại.',
  'Một lần thất bại. Bài học đã học; đi tiếp.',
  'Đáy tài chính. Từ đây đi lên.',
  'Xong rồi. Giờ bạn đứng dậy được.'],
'swords-c0': ['tò mò|cảnh giác|ý tưởng mới|giao tiếp', 'đàm tiếu|lời vội|nghĩ tản mạn|dò xét',
  'Năng lượng tỉnh táo, tò mò, hay nói. Ý tưởng và tin nhắn mới. Coi chừng lời nói.',
  'Tin nhắn tò mò, tranh luận vui. Hoặc đàm tiếu: cẩn thận.',
  'Ý tưởng mới, giao tiếp, cảnh giác.',
  'Đầu óc tò mò. Tìm hiểu và đặt câu hỏi.',
  'Coi chừng lời đồn và quyết định vội.',
  'Hỏi câu hỏi, rồi lắng nghe.'],
'swords-c1': ['tham vọng|hành động|thẳng|nhanh', 'hung hăng|thiếu kiên nhẫn|liều|tàn nhẫn',
  'Năng lượng nhanh, sắc, quyết đoán. Bạn đang lao vào. Chắc rằng bạn chĩa đúng hướng.',
  'Một người thẳng và nhanh, hoặc một quyết định vội. Chậm lại một chút.',
  'Quyết định nhanh và hành động táo bạo. Coi chừng vội.',
  'Đợt học dồn mạnh. Hiệu quả nhưng mệt.',
  'Nước cờ tiền nhanh. Đánh giá rủi ro.',
  'Lao lên, nhưng xem bản đồ trước.'],
'swords-c2': ['độc lập|phán đoán rõ|thật thà|ranh giới', 'lạnh|cay đắng|cô lập|phê bình gắt',
  'Mắt sáng, thật thà, độc lập. Bạn nhìn xuyên qua điều vô nghĩa. Thêm ấm áp vào sự thật.',
  'Độc lập và thật thà. Cần ranh giới.',
  'Phán đoán rõ và giao tiếp thẳng. Dẫn bằng sự chính trực.',
  'Học phân tích, kỷ luật.',
  'Quyết định tiền rõ ràng, không cảm tính.',
  'Nói sự thật với lòng tử tế.'],
'swords-c3': ['quyền hạn|trí tuệ|sự thật|kỷ luật', 'thao túng|độc tài|lạnh|lạm quyền',
  'Quyền hạn của trí tuệ. Luật rõ, phán xét công bằng, sức mạnh của đầu óc. Dùng cho công bằng.',
  'Một người bạn đời lý trí, có nguyên tắc. Rõ ràng trong cam kết.',
  'Dẫn dắt bằng chuyên môn và công bằng.',
  'Làm chủ môn học bằng kỷ luật và logic.',
  'Kế hoạch tài chính lý trí, có cấu trúc.',
  'Cai trị bằng lý lẽ và công bằng.'],

'pentacles-1': ['cơ hội|thịnh vượng|dự án mới|thành hình', 'bỏ lỡ|thiếu thốn|kế hoạch kém|tham',
  'Một cơ hội cụ thể đang được đưa ra. Tiền mới, việc mới, thứ có thật. Nhận lấy.',
  'Một mối quan hệ mới ổn định, có triển vọng. Thật, không chỉ hấp dẫn.',
  'Việc mới, hợp đồng mới, dự án mới. Vững và có triển vọng.',
  'Một cơ hội thực tế mới: học bổng, khoá học, vị trí.',
  'Thu nhập mới hoặc cơ hội tài chính. Nắm lấy.',
  'Nhận đồng xu. Nó là thật.'],
'pentacles-2': ['cân bằng|thích nghi|tung hứng|linh hoạt', 'quá tải|lộn xộn|căng tiền|rơi bóng',
  'Bạn đang tung hứng nhiều thứ và giữ được. Linh hoạt; hiện tại vẫn ổn.',
  'Cân bằng tình yêu với các đòi hỏi khác. Chủ động dành thời gian.',
  'Nhiều dự án. Sắp ưu tiên và giữ linh hoạt.',
  'Cân bằng học và đời. Lên lịch tuần.',
  'Xoay dòng tiền. Lập ngân sách cẩn thận.',
  'Giữ các quả bóng trên không, nhưng không mãi mãi.'],
'pentacles-3': ['làm nhóm|tay nghề|học nghề|chất lượng', 'thiếu phối hợp|chất lượng kém|không được ghi nhận|làm một mình',
  'Tay nghề đang được công nhận và xây thêm. Hợp tác và sự khéo léo được đền đáp.',
  'Cùng nhau xây mối quan hệ, từng bước.',
  'Hợp tác, tay nghề được công nhận, việc chất lượng. Tốt cho dự án nhóm.',
  'Học từ người khác. Kỹ năng lên nhờ luyện.',
  'Tiền từ tay nghề và hợp tác.',
  'Làm cho tốt, cùng người khác.'],
'pentacles-4': ['an toàn|kiểm soát|tiết kiệm|ổn định', 'tham|tích trữ|sợ mất|chiếm hữu',
  'Giữ chặt điều bạn có. An toàn là quan trọng, nhưng nắm chặt quá thì dòng chảy ngừng.',
  'Chiếm hữu hoặc sợ mất ai đó. Nới tay ra.',
  'An toàn công việc và kiểm soát. Đừng chống mọi thay đổi.',
  'Cách học chắc, an toàn. Đừng sợ phương pháp mới.',
  'Tiết kiệm và an toàn. Cân với sự hào phóng.',
  'Giữ điều quan trọng, nới phần còn lại.'],
'pentacles-5': ['khó khăn|lo|bị bỏ ngoài|bền bỉ', 'cô lập|tâm lý thiếu thốn|từ chối giúp đỡ|tuyệt vọng',
  'Một đoạn khó, thấy bị bỏ ngoài trời lạnh. Sự giúp đỡ gần hơn bạn tưởng. Hỏi đi.',
  'Thấy cô đơn hoặc không được nâng đỡ. Tìm đến người khác; đừng chịu trong im lặng.',
  'Bất ổn công việc hoặc căng thẳng tài chính ở chỗ làm. Tìm hỗ trợ.',
  'Vật lộn, thiếu nguồn lực. Nhờ giúp.',
  'Khó khăn tài chính. Tìm sự hỗ trợ; rồi sẽ qua.',
  'Cánh cửa ngay đó. Gõ đi.'],
'pentacles-6': ['hào phóng|cho đi|cân bằng|chia sẻ', 'điều kiện kèm|nợ|bất bình đẳng|lệch quyền lực',
  'Cho và nhận cân bằng. Sự hào phóng chảy, sự công bằng cũng vậy.',
  'Hào phóng và nâng đỡ trong mối quan hệ. Kiểm lại cán cân cho và nhận.',
  'Trả công xứng, được hướng dẫn, được hỗ trợ. Cho và nhận.',
  'Được thầy cô hoặc bạn bè giúp. Chia sẻ điều bạn biết.',
  'Tiền đến qua sự hào phóng, hoặc cơ hội để cho đi.',
  'Cho điều bạn cho được, nhận điều bạn cần.'],
'pentacles-7': ['kiên nhẫn|đánh giá|nhìn dài|bền bỉ', 'nóng vội|chưa có quả|bực bội|đầu tư kém',
  'Bạn đã làm và giờ bạn chờ. Đánh giá sự lớn lên; đừng đào hạt lên xem.',
  'Đánh giá một mối quan hệ. Khoản đầu tư có đang sinh lời không?',
  'Nỗ lực dài hạn. Kết quả chậm nhưng đang tới. Đánh giá.',
  'Tiến chậm. Cứ chăm.',
  'Đầu tư dài hạn. Cần kiên nhẫn.',
  'Để nó lớn từ từ.'],
'pentacles-8': ['tay nghề|chăm chỉ|rèn kỹ năng|tận tâm', 'cầu toàn|đơn điệu|thiếu tham vọng|làm ẩu',
  'Làm việc tập trung, kiên nhẫn. Kỹ năng xây từng lần lặp. Bạn đang giỏi lên.',
  'Vun đắp mối quan hệ bằng sự chăm và đều.',
  'Tận tâm với nghề. Thành thạo qua luyện tập.',
  'Luyện đều, lặp lại. Đây là cách nó ngấm.',
  'Tiền qua tay nghề và làm việc đều.',
  'Làm đủ số lần.'],
'pentacles-9': ['độc lập|tự đủ|sung túc|giá trị bản thân', 'làm quá|lệ thuộc|cô lập|hời hợt',
  'Sự dễ chịu bạn tự tạo ra. Độc lập, và tận hưởng nó. Bạn xứng đáng.',
  'Tự đủ trong tình yêu. Hạnh phúc một mình hay có đôi.',
  'Thành công và độc lập. Hưởng thành quả công việc.',
  'Tự học, tự định hướng. Tin vào khả năng mình.',
  'Độc lập và dễ chịu về tài chính.',
  'Tận hưởng điều bạn đã xây.'],
'pentacles-10': ['di sản|của cải|gia đình|an toàn lâu dài', 'gia đình xung đột|mất tiền|bất ổn|nghĩ ngắn',
  'Của cải bền: gia đình, di sản, những cấu trúc sống lâu hơn bạn. Nghĩ theo thế hệ.',
  'Một mối quan hệ bền, gắn bó gia đình, tương lai chung.',
  'Thành công lâu dài, sự nghiệp ổn định, đóng góp bền.',
  'Học là đầu tư dài hạn. Gia đình ủng hộ.',
  'Của cải, thừa kế, an toàn lâu dài.',
  'Xây cho đường dài.'],
'pentacles-c0': ['tham vọng|học hỏi|khởi đầu thực tế|thành hình', 'trì hoãn|không tiến|mơ mộng|không theo tới cùng',
  'Một khởi đầu thực tế: một khoá học, một kế hoạch, một bước đầu được coi trọng. Học cho đàng hoàng.',
  'Một kết nối mới thực tế, có gốc. Chậm và thật.',
  'Việc mới, đào tạo, hoặc một cơ hội thực tế.',
  'Khoá học mới hoặc thái độ nghiêm túc với việc học.',
  'Một mục tiêu tài chính mới. Bắt đầu để dành.',
  'Bắt đầu, và học cho đàng hoàng.'],
'pentacles-c1': ['đáng tin|nếp|chăm|trách nhiệm', 'chán|ứ đọng|cứng đầu|cầu toàn',
  'Chậm, đáng tin, có phương pháp. Không hào hứng, và làm là xong. Đó là món quà của nó.',
  'Một người bạn đời đáng tin, đều đặn. Tình yêu cháy chậm, bền.',
  'Làm việc có phương pháp. Sự đáng tin thắng.',
  'Nếp học đều. Chậm mà chắc.',
  'Lựa chọn tiền bạc an toàn, thận trọng.',
  'Đi tiếp, đều đặn.'],
'pentacles-c2': ['chăm sóc|thực tế|sung túc|an toàn', 'làm quá sức|bỏ bê mình|bao bọc|vật chất',
  'Chăm sóc thực tế. Bạn làm cho mọi người an toàn về vật chất. Chăm mình nữa.',
  'Một người bạn đời biết chăm lo, thực tế. Nhà cửa và sự dễ chịu.',
  'Quản lý thực tế và lo cho nhóm.',
  'Học có tổ chức, chắc chân.',
  'Quản lý tiền thực tế, hào phóng.',
  'Chăm mình như chăm mọi người.'],
'pentacles-c3': ['của cải|dẫn dắt|an toàn|kỷ luật', 'tham|vật chất|cứng đầu|kiểm soát bằng tiền',
  'Làm chủ thế giới vật chất. Ổn định và chu cấp mà bạn dựa vào được.',
  'Một người chu cấp ổn định, hào phóng. An toàn trong tình yêu.',
  'Thành công trong kinh doanh. Dẫn dắt bằng sự đáng tin.',
  'Làm chủ môn thực hành bằng kỷ luật.',
  'Của cải và làm chủ tài chính.',
  'Xây của cải, và giữ lòng hào phóng.']
});
