/* ============================ card insights, the 22 Majors, rewritten ============================
   Full sentences with a clear subject, each line leading into the next.
   Same field order as insight-en.js / insight-vi.js. */
Object.assign(INSIGHT.vi, {
'major-0': ['khởi đầu mới|cởi mở|dũng cảm|dám bước', 'bất cẩn|ngây thơ|không có kế hoạch|trốn trách nhiệm',
  'Bạn đang đứng trước một điều hoàn toàn mới. Lúc này trong bạn có nhiều háo hức hơn là chắc chắn, và điều đó hoàn toàn bình thường. Lá bài mời bạn tin vào bước chân đầu tiên.',
  'Một người mới hoặc một cảm xúc mới đang đến với bạn, hoặc chính bạn đã sẵn sàng yêu lại mà không mang theo nỗi sợ cũ. Bạn cứ vui với điều đó, nhưng đừng hứa nhiều hơn những gì mình đã biết chắc.',
  'Bạn sắp nhận một dự án, một vai trò hay một hướng đi mà mình chưa từng thử. Bạn sẽ vừa làm vừa học, nên hãy hỏi sớm và hỏi nhiều.',
  'Một môn học mới hoặc một cách học mới đang mở ra. Lúc này sự tò mò sẽ kéo bạn đi; kỷ luật có thể tính sau.',
  'Một nguồn thu mới có thể xuất hiện, hoặc bạn đang muốn tiêu tiền cho một chuyến phiêu lưu. Bạn hãy để lại một khoản nhỏ phòng thân trước khi nhảy.',
  'Bạn cứ bước, nhưng nhớ mang theo hành lý: một kế hoạch nhỏ và một đường lui, rồi hãy đi.'],
'major-1': ['kỹ năng|tập trung|chủ động|biến ý thành việc', 'khoe mẽ|thao túng|tài năng phân tán|nói nhiều làm ít',
  'Bạn đang có trong tay mọi công cụ mình cần. Câu hỏi lúc này không phải là "mình có làm được không", mà là "mình có bắt tay vào làm không". Năng lượng của bạn đang sắc bén và mạnh mẽ.',
  'Lúc này bạn rất cuốn hút và thuyết phục, nên hãy dùng điều đó một cách thật lòng. Bạn nói rõ mình muốn gì sẽ tốt hơn là bắt người kia phải đoán.',
  'Người khác đang nhìn thấy khả năng của bạn. Đây là lúc để bạn trình bày ý tưởng, dẫn dắt cuộc họp và bắt tay vào việc, vì kết quả sẽ đến từ hành động chứ không phải từ tính toán.',
  'Đầu óc bạn đang nhanh nhạy và dễ tập trung. Bạn hãy ngồi xuống và dùng nó ngay, trước khi khoảng thời gian tốt này khép lại.',
  'Đây là thời điểm tốt để biến kỹ năng của bạn thành tiền. Bạn hãy đặt giá và mạnh dạn đưa ra lời đề nghị.',
  'Trong vài ngày tới, bạn hãy dồn mọi thứ mình có vào một mục tiêu duy nhất, và bạn sẽ thấy nó chuyển động.'],
'major-2': ['trực giác|tĩnh lặng|điều còn ẩn|kiên nhẫn', 'bí mật|thu mình|bỏ qua linh cảm|ngồi yên quá lâu',
  'Có một điều gì đó vẫn chưa lộ ra. Linh cảm của bạn đang biết nhiều hơn những gì sự thật cho thấy. Đây là lúc để lắng nghe, chứ chưa phải lúc để thúc ép.',
  'Cảm xúc đang chảy ngầm, có thể là của bạn, có thể là của người ấy. Bạn đừng ép ai phải nói ra, mà hãy nhìn vào việc họ làm hơn là lời họ nói.',
  'Ở đâu đó đang có thông tin bị giữ lại. Bạn nên đọc giữa các dòng trước khi đưa ra quyết định.',
  'Học một mình trong yên tĩnh đang rất hợp với bạn. Bạn hiểu bài sâu hơn những gì điểm số hiện tại thể hiện.',
  'Bạn khoan ký và khoan chi, vì vẫn còn một chi tiết mà người ta chưa nói với bạn.',
  'Bạn hãy để câu hỏi đó yên một ngày. Câu trả lời thường đến đúng lúc bạn thôi đòi hỏi nó.'],
'major-3': ['sung túc|nuôi dưỡng|dễ chịu|sáng tạo', 'hưởng thụ quá đà|bao bọc quá mức|bí ý tưởng|quên chăm mình',
  'Mọi thứ quanh bạn đang lớn lên, và chúng chủ yếu cần được nuôi dưỡng chứ không cần sửa chữa. Bạn được phép thấy dễ chịu, vì điều bạn chăm sóc đang dần chín.',
  'Năng lượng lúc này ấm áp, rộng rãi và gần gũi. Mối quan hệ của bạn đang sâu thêm, hoặc sự quan tâm đang chảy về phía bạn, và bạn chỉ cần mở lòng đón nhận.',
  'Một dự án của bạn đang ra quả, và công việc sáng tạo được ủng hộ. Bạn sẽ tiến xa hơn khi làm cùng người khác thay vì làm một mình.',
  'Bạn học vào nhất khi cơ thể thoải mái và được nghỉ đủ. Bạn hãy dọn góc học cho dễ chịu, việc học sẽ tự theo sau.',
  'Tiền đang vào dễ hơn bình thường. Bạn hãy hưởng một chút, để dành một chút và chia sẻ một chút.',
  'Tuần này bạn hãy chăm sóc cơ thể và không gian sống của mình, vì sự lớn lên luôn đi sau sự chăm sóc.'],
'major-4': ['cấu trúc|ổn định|dẫn dắt|ranh giới', 'cứng nhắc|kiểm soát|lạnh lùng|không có kỷ luật nào',
  'Đây là năng lượng của trật tự và quyền hạn. Bạn đang được yêu cầu đặt ra luật lệ, đứng ra nắm quyền, hoặc tôn trọng người đang nắm quyền.',
  'Lúc này sự ổn định quan trọng hơn sự lãng mạn. Có thể một người đáng tin đang xuất hiện, hoặc chính bạn cần đặt ra những ranh giới rõ ràng.',
  'Bạn hãy đứng ra dẫn dắt, hoặc làm việc thật tốt trong hệ thống. Lúc này kế hoạch, thứ bậc và kỷ luật sẽ thắng sự tùy hứng.',
  'Một thời khóa biểu và một thói quen cố định sẽ giúp bạn nhiều hơn cảm hứng. Bạn hãy dựng cái khung trước đã.',
  'Bạn cần ngân sách, sự kiểm soát và một kế hoạch dài hạn, vì tiền bạc lúc này đáp lại kỷ luật.',
  'Bạn hãy quyết định rồi giữ vững quyết định đó. Chỉ cần chắc rằng nó công bằng với mọi người.'],
'major-5': ['truyền thống|chỉ dẫn|học hỏi|thuộc về', 'giáo điều|làm theo cho xong|phán xét người khác|nổi loạn vô cớ',
  'Những cách làm có sẵn đang nâng đỡ bạn, có thể là một người thầy, một nếp nhà hay một tổ chức. Làm theo cách quen thuộc lúc này sẽ cho bạn sự yên tâm.',
  'Đây có thể là một cam kết, một sự chấp thuận từ gia đình, hoặc một mối quan hệ có chung giá trị. Hai bạn hãy nói với nhau về những điều mình tin.',
  'Bạn hãy làm đúng quy trình, vì một người hướng dẫn hay một bằng cấp chính thức sẽ giúp bạn lúc này. Bạn đừng nhảy cóc.',
  'Bạn nên học từ thầy giỏi và từ tài liệu chuẩn. Tuần này không phải lúc để sáng tạo lại phương pháp.',
  'Bạn hãy chọn cách an toàn và quen thuộc với tiền, vì lời khuyên của người có kinh nghiệm đang rất đáng giá.',
  'Bạn hãy hỏi một người đã đi qua con đường này. Tấm bản đồ của họ có thể tiết kiệm cho bạn nhiều tháng.'],
'major-6': ['kết nối|lựa chọn|giá trị|hòa hợp', 'lệch pha|né tránh quyết định|cám dỗ|tình đơn phương',
  'Đây là một cuộc gặp thật sự giữa hai điều, hoặc một lựa chọn cho thấy bạn thật sự coi trọng gì. Năng lượng này nói về sự hợp nhau, chứ không chỉ về sự hấp dẫn.',
  'Bạn đang có một mối gắn bó mạnh, một lựa chọn quan trọng về người bạn đời, hoặc một khoảnh khắc phải quyết định mình muốn gì từ tình yêu.',
  'Hợp tác và làm việc nhóm đang được ủng hộ. Nếu đứng trước ngã rẽ, bạn hãy chọn con đường hợp với giá trị của mình.',
  'Bạn nên học cùng bạn học hoặc trong một nhóm. Nếu phải chọn môn, bạn hãy chọn môn mình thật sự quan tâm.',
  'Bạn sắp đưa ra một quyết định tài chính thể hiện ưu tiên của mình. Bạn đừng chọn chỉ vì con số.',
  'Bạn hãy chọn bằng giá trị của mình, chứ đừng chọn bằng nỗi sợ.'],
'major-7': ['ý chí|tiến tới|chiến thắng|có hướng', 'hung hăng|mất kiểm soát|lực phân tán|giẫm lên người khác',
  'Bạn đang chuyển động và đang thắng thế. Những lực kéo ngược chiều đang được ý chí của bạn giữ chung một hướng, nên bạn hãy tiếp tục giữ chắc tay lái.',
  'Bạn cứ theo đuổi điều mình muốn, nhưng hãy giữ được cảm xúc của mình. Mối quan hệ này sẽ tiến lên nhờ nỗ lực.',
  'Tham vọng và đà tiến đang ở phía bạn. Bạn hãy vượt qua chướng ngại, vì bạn có đủ sức, và có thể sẽ có một chuyến đi.',
  'Tuần này kỷ luật chính là sức mạnh của bạn. Bạn hãy đặt mục tiêu rồi lao tới.',
  'Tiền đến với bạn nhờ sự quyết tâm. Mục tiêu bạn theo đuổi bấy lâu đã nằm trong tầm tay.',
  'Bạn hãy giữ cả hai dây cương, tức là vừa tự tin vừa kiểm soát, cùng một lúc.'],
'major-8': ['sức mạnh bên trong|kiên nhẫn|bao dung|can đảm', 'nghi ngờ bản thân|dùng sức ép|cảm xúc thô|thấy yếu là thấy xấu hổ',
  'Sức mạnh của bạn lúc này rất lặng lẽ. Sự kiên nhẫn và lòng tử tế sẽ xử lý được những việc mà sức ép không làm nổi, vì con sư tử được thuần bằng sự bình tĩnh chứ không bằng tiếng hét.',
  'Sức mạnh dịu dàng sẽ thắng. Bạn hãy xử lý căng thẳng bằng sự kiên nhẫn thay vì phản ứng, vì có người đang cần sự bình tĩnh của bạn.',
  'Bạn đang đối diện một người khó hoặc một tình huống khó, và sự điềm tĩnh của bạn đang được để ý.',
  'Hôm nay sự bền bỉ sẽ thắng sự thông minh. Bạn cứ làm đều đặn và bình tĩnh.',
  'Bạn nên quản lý tiền một cách đều tay thay vì đi nước cờ táo bạo, và đừng để nỗi sợ quyết định thay mình.',
  'Bạn hãy thở trước rồi mới hành động. Phiên bản bình tĩnh của bạn chính là phiên bản mạnh nhất.'],
'major-9': ['nhìn lại|khôn ngoan|một mình|đi tìm', 'cô lập|cô đơn|thu mình quá lâu|từ chối giúp đỡ',
  'Lúc này bạn cần lùi lại một bước để suy nghĩ. Câu trả lời bạn tìm nằm ở bên trong, chứ không nằm ở thêm một ý kiến nào nữa. Một mình lúc này là điều có ích.',
  'Bạn hoặc người ấy đang cần không gian để suy nghĩ. Thời gian riêng không phải là sự từ chối; sự gắn kết sâu hơn sẽ đến sau khi cả hai đã nhìn lại.',
  'Bạn hãy suy nghĩ kỹ trước bước đi tiếp theo. Một người đi trước hoặc chính kinh nghiệm của bạn sẽ soi đường, nên hãy tránh quyết định trong lúc ồn ào.',
  'Bạn hãy học sâu, tập trung và một mình. Bạn nên tắt thông báo điện thoại đi.',
  'Bạn hãy xem lại tài chính của mình một cách lặng lẽ và thành thật. Nếu cần, bạn hãy hỏi một chuyên gia.',
  'Bạn hãy dành cho mình một buổi tối một mình với câu hỏi đó, rồi quay lại với mọi người.'],
'major-10': ['thay đổi|may mắn|vòng quay|bước ngoặt', 'chống lại thay đổi|xui xẻo|thấy mất kiểm soát|lặp lại vòng cũ',
  'Bánh xe đang quay. Hoàn cảnh của bạn đang thay đổi dù bạn có đẩy hay không, và trong không khí vừa có may mắn vừa có sự chuyển mình.',
  'Mối quan hệ của bạn đang bước sang một giai đoạn mới, và những cuộc gặp gỡ tình cờ rất dễ xảy ra. Bạn gieo gì thì sẽ gặt nấy.',
  'Bạn hãy chờ đợi sự chuyển động: một vai trò mới, một cơ may hay một ngã rẽ bất ngờ. Bạn nên thích nghi thay vì cưỡng lại.',
  'Kết quả của bạn có thể lên xuống. Bạn hãy tận dụng lúc lên và đừng hoảng khi xuống.',
  'Vận tiền của bạn đang đổi. Bạn đừng đánh cược, nhưng hãy sẵn sàng đón lấy cơ hội.',
  'Bạn hãy đi theo vòng quay, vì chống lại bánh xe chỉ khiến bạn mệt.'],
'major-11': ['công bằng|sự thật|chịu trách nhiệm|rõ ràng', 'bất công|không thật thà|né hậu quả|phán xét khắc nghiệt',
  'Nhân và quả đang hiện ra rất rõ. Mỗi quyết định lúc này đều có hậu quả, và chỉ có sự thật thà mới thật sự hiệu quả.',
  'Bạn hãy thành thật về điều gì là công bằng giữa hai người. Sự cân bằng sẽ trở lại khi mỗi bên nhận phần trách nhiệm của mình.',
  'Bạn đang đứng trước chuyện hợp đồng, pháp lý hoặc đánh giá. Bạn hãy làm đúng quy định và lưu lại giấy tờ.',
  'Nỗ lực công bằng sẽ cho kết quả công bằng. Bạn hãy thành thật với chính mình về việc mình đã thật sự học bao nhiêu.',
  'Bạn hãy thanh toán sòng phẳng: trả điều mình nợ và thu điều người ta nợ mình.',
  'Bạn hãy nói thật, nhất là với chính mình.'],
'major-12': ['tạm dừng|buông|góc nhìn mới|thả ra', 'giậm chân|tự làm khổ mình|do dự|tự chọn đứng yên',
  'Mọi thứ đang tạm dừng, và sự dừng lại này có mục đích của nó. Khi nhìn từ một góc khác, tình hình sẽ khác đi. Bạn hãy chờ một cách tự nguyện.',
  'Mối quan hệ của bạn đang lơ lửng, và việc thúc đẩy sẽ không giúp gì. Bạn hãy buông kết quả ra và xem điều gì thay đổi.',
  'Có thể có sự chậm trễ hoặc một dự án bị treo. Bạn hãy dùng thời gian này để nghĩ lại cách làm thay vì ép nó tiến lên.',
  'Bạn hãy lùi ra khỏi bài toán một lúc. Lời giải thường xuất hiện khi bạn thôi nhìn chằm chằm vào nó.',
  'Đây chưa phải lúc để động đến tiền. Bạn hãy giữ nguyên và xem xét lại.',
  'Bạn hãy cố ý không làm gì trong một lúc, rồi nhìn lại mọi thứ.'],
'major-13': ['kết thúc|chuyển hóa|buông bỏ|đổi mới', 'níu kéo|sợ thay đổi|ứ đọng|kéo dài cái kết',
  'Một điều đang kết thúc để một điều khác có thể bắt đầu. Cảm giác có thể nặng nề, nhưng năng lượng này đang dọn dẹp chứ không hề tàn nhẫn.',
  'Một mối quan hệ, hoặc một phiên bản của nó, đang khép lại. Bạn hãy cho phép mình buồn, rồi để hình hài mới của nó hiện ra.',
  'Một vai trò, một dự án hay một cách làm việc đang đóng lại. Bạn đừng bám víu, vì điều tiếp theo cần chính khoảng trống này.',
  'Một cách học cũ hoặc một mục tiêu cũ đã hết vai trò. Bạn hãy đổi cách học của mình.',
  'Một chương tài chính đang khép lại. Bạn hãy cắt bỏ những gì không còn hiệu quả và xây lại từ đầu.',
  'Bạn hãy để nó kết thúc, vì bạn không thể mở chương mới khi vẫn còn giữ trang cuối.'],
'major-14': ['cân bằng|điều độ|kiên nhẫn|chữa lành', 'quá đà|mất cân bằng|nóng vội|ưu tiên chỏi nhau',
  'Bạn hãy pha trộn thay vì ép buộc. Năng lượng lúc này là tìm ra con đường ở giữa và đi từ từ, vì việc chữa lành đang thật sự diễn ra.',
  'Sự hòa hợp sẽ lớn lên nhờ kiên nhẫn và biết nhường nhau. Bạn hãy tránh cực đoan, cả trong cảm xúc lẫn trong đòi hỏi.',
  'Bạn nên làm việc nhóm một cách ổn định và cân đối công việc cẩn thận. Bạn đừng vội, và hãy kết hợp thế mạnh của mọi người.',
  'Học đều nhịp sẽ tốt hơn học nhồi. Bạn hãy cân bằng giữa học và nghỉ.',
  'Bạn hãy tiêu vừa phải và để dành vừa phải. Lúc này không cần nước cờ kịch tính nào.',
  'Bạn hãy có mỗi thứ một ít, và không để thứ nào quá tay.'],
'major-15': ['gắn chặt|ham muốn|tham vọng|thật đến trần trụi', 'nghiện|ám ảnh|mẫu hình độc hại|thấy bị trói',
  'Có một thứ đang nắm lấy bạn, có thể là một thói quen, một người hay một ham muốn. Năng lượng này mạnh và không hẳn là xấu, nhưng bạn cần nhìn thấy sợi xích.',
  'Bạn đang trong một sức hút dữ dội hoặc một mối gắn bó khó rời. Bạn hãy tự hỏi: nó nuôi mình hay rút cạn mình?',
  'Bạn có thể đang đầy tham vọng và động lực, hoặc đang bị một công việc sở hữu. Bạn hãy xem mình đang đổi gì để lấy tiền.',
  'Sự xao nhãng và trì hoãn đang rất mạnh. Bạn hãy gọi tên thói quen đang lấy mất thời gian của mình.',
  'Bạn hãy coi chừng nợ nần, tiêu bốc đồng và những khoản tiền đi kèm điều kiện.',
  'Bạn hãy gọi tên thứ đang giữ mình lại, vì khi gọi được tên nó, sợi xích sẽ lỏng ra.'],
'major-16': ['thay đổi đột ngột|sự thật lộ ra|bứt phá|tự do', 'đổ vỡ|sốc|sụp đổ có thể tránh|không chịu học bài học',
  'Một thứ được xây trên nền lung lay đang đổ xuống. Đó là một cú sốc, nhưng cái đổ ấy vốn không vững, và sự thật đang phá ra ngoài.',
  'Một biến cố bất ngờ hoặc một sự thật đang lộ ra. Nó đau, nhưng nó dọn sạch những điều giả dối.',
  'Ở chỗ làm đang có thay đổi đột ngột: một kế hoạch sụp đổ hoặc một cấu trúc bị thách thức. Bạn hãy xây lại trên nền chắc hơn.',
  'Kế hoạch học của bạn đang tan vỡ. Bạn hãy đánh giá lại và dựng lịch mới từ đầu.',
  'Có thể có một khoản chi bất ngờ hoặc một mất mát. Bạn hãy bảo vệ những thứ cơ bản trước.',
  'Bạn hãy để cái giả rơi xuống, rồi xây lại bằng cái thật.'],
'major-17': ['hy vọng|chữa lành|cảm hứng|hồi phục', 'nản lòng|mất niềm tin|nghi ngờ mình|lạc quan rỗng',
  'Sau những điều khó khăn, một sự bình yên đã đến với bạn. Hy vọng lúc này là thật chứ không phải gượng ép, và bạn đang được hồi phục.',
  'Bạn đang lành lại sau tổn thương, và sự cởi mở đang quay về. Một tình yêu thật thà và bình yên đang ở gần.',
  'Cảm hứng và cảm giác có mục đích đang trở lại với bạn. Đây là thời điểm tốt cho những kế hoạch sáng tạo và dài hạn.',
  'Động lực học của bạn đang trở lại. Bạn thấy rõ vì sao mình học điều này.',
  'Khó khăn tiền bạc đang dịu đi. Bạn có thể cho đi hào phóng trong chừng mực.',
  'Bạn hãy tin vào niềm hy vọng lặng lẽ ấy, vì nó đang nói thật với bạn.'],
'major-18': ['trực giác|giấc mơ|chưa rõ|tiềm thức', 'ảo ảnh|lo âu|lừa dối|rối bời',
  'Chưa có gì rõ ràng hoàn toàn. Nỗi sợ và trí tưởng tượng đang tô màu những gì bạn nhìn thấy, nên bạn hãy đi chậm và tin vào linh cảm thay vì tin vào lo lắng.',
  'Bạn đang nhận những tín hiệu lẫn lộn và thấy không chắc chắn. Có điều gì đó đang bị giấu, nhưng bạn đừng vội nghĩ xấu, mà hãy hỏi thẳng.',
  'Ở chỗ làm đang có sự rối rắm hoặc thông tin không rõ. Bạn hãy chờ sự thật rồi mới hành động.',
  'Lo âu đang làm mờ sự hiểu bài của bạn. Bạn hãy ngủ một giấc, rồi xem lại khi đầu óc đã tỉnh.',
  'Chuyện tiền lúc này chưa rõ ràng hoặc có rủi ro. Bạn đừng ký thứ gì mình chưa hiểu hết.',
  'Bạn hãy đi chậm qua màn sương, vì sương rồi sẽ tan.'],
'major-19': ['niềm vui|thành công|rõ ràng|sức sống', 'kiêu ngạo|phô bày quá mức|hạnh phúc đến muộn|vui giả',
  'Năng lượng của bạn đang ấm áp, rõ ràng và tự tin. Mọi thứ đang vận hành tốt và điều đó hiện ra ngoài, nên bạn cứ vui một cách công khai.',
  'Bạn đang có hạnh phúc, sự ấm áp và một kết nối dễ dàng. Mối quan hệ này đang đứng giữa ban ngày.',
  'Bạn đang thành công, được ghi nhận và có một chiến thắng rõ ràng. Công việc của bạn được nhìn thấy.',
  'Bạn đang sáng rõ và tự tin. Kết quả tốt đang trên đường tới.',
  'May mắn và tăng trưởng đang ở phía bạn. Tiền đến cùng niềm vui thay vì cùng sự vật lộn.',
  'Bạn hãy nói có với điều tốt đẹp này, vì bạn xứng đáng với nó.'],
'major-20': ['thức tỉnh|tiếng gọi|tha thứ|tổng kết', 'tự phán xét|từ chối tiếng gọi|hối tiếc|kẹt trong quá khứ',
  'Đây là một khoảnh khắc nhìn rõ. Bạn đang được gọi tới một quyết định, một thay đổi hay một tầng mới của cuộc đời. Quá khứ được xem lại và được thả ra.',
  'Mối quan hệ của bạn đang đến một bước ngoặt. Bạn hãy tha thứ, quyết định, và đi tiếp.',
  'Bạn đang nghe một tiếng gọi trong sự nghiệp, có thể là một đợt đánh giá hoặc một cơ hội đi lên. Bạn hãy đáp lại nó.',
  'Kết quả và những đợt đánh giá đang đến. Bạn hãy học từ quá khứ và bước lên.',
  'Bạn đang trong một đợt tổng kết tài chính. Bạn hãy đối diện với con số và quyết định.',
  'Bạn hãy đáp lại tiếng gọi, vì bạn đã biết nó là gì rồi.'],
'major-21': ['hoàn tất|trọn vẹn|thành tựu|đi xa', 'việc dang dở|chậm trễ|thấy chưa đủ|đi tắt',
  'Một vòng đang khép lại, và bạn đã thấm bài học của nó. Đây là sự viên mãn, và cũng là cánh cửa mở sang vòng tiếp theo.',
  'Mối quan hệ của bạn đang đến giai đoạn trọn vẹn và chín chắn, hoặc hai bạn sắp có một chuyến đi cùng nhau.',
  'Bạn đang hoàn thành một dự án lớn và được công nhận. Có thể sẽ có chuyến đi xa hoặc công việc với nước ngoài.',
  'Bạn đang tốt nghiệp, hoàn thành, hoặc làm chủ được một môn học.',
  'Bạn đang đạt mục tiêu tài chính của mình, và sự vững vàng này sẽ kéo dài.',
  'Bạn hãy làm cho xong hẳn, rồi ăn mừng trước khi bắt đầu việc mới.']
});
Object.assign(INSIGHT.en, {
'major-0': ['new beginnings|openness|courage|a leap of faith', 'carelessness|naivety|no plan|running from responsibility',
  'You are standing at the edge of something new. Right now there is more excitement in you than certainty, and that is perfectly fine. The card invites you to trust the first step.',
  'Someone new, or a new feeling, is coming toward you, or you yourself are ready to love again without the old fears. Enjoy it, but do not promise more than you know for sure.',
  'You are about to take on a project, a role or a direction you have never tried. You will learn on the job, so ask early and ask often.',
  'A new subject or a new way of studying is opening up. For now, curiosity will carry you; structure can come later.',
  'A new source of income may appear, or you may feel like spending on an adventure. Keep a small cushion aside before you leap.',
  'Take the step, but pack a bag first: one small plan and one way back, and then go.'],
'major-1': ['skill|focus|initiative|making it happen', 'showing off|manipulation|scattered talent|all talk',
  'You already have every tool you need. The question right now is not "can I" but "will I start". Your energy is sharp and strong.',
  'You are attractive and persuasive at the moment, so use that honestly. Saying clearly what you want will work better than making the other person guess.',
  'Other people can see your abilities. This is the time to pitch the idea, lead the meeting and start the work, because results will come from doing rather than from planning.',
  'Your mind is quick and you can concentrate easily. Sit down and use it now, before this good window closes.',
  'This is a good moment to turn your skill into money. Set a price and make the offer.',
  'For the next few days, point everything you have at one goal, and you will watch it move.'],
'major-2': ['intuition|stillness|hidden knowledge|patience', 'secrets|withdrawal|ignoring your gut|passivity',
  'Something has not surfaced yet. Your instincts already know more than the facts are showing. This is a time to listen, not yet a time to push.',
  'Feelings are running under the surface, yours or theirs. Do not force a confession; watch what people do rather than what they say.',
  'Somewhere, information is being held back. Read between the lines before you commit to a decision.',
  'Quiet, solitary study suits you right now. You understand more deeply than your current results show.',
  'Wait before you sign or spend, because there is a detail nobody has told you yet.',
  'Let the question rest for a day. The answer usually arrives the moment you stop demanding it.'],
'major-3': ['abundance|nurture|comfort|creativity', 'overindulgence|smothering|creative block|neglecting yourself',
  'Things around you are growing, and they mostly need feeding rather than fixing. You are allowed to feel comfortable, because what you care for is ripening.',
  'The energy now is warm, generous and close. Your relationship is deepening, or care is flowing toward you, and all you need to do is receive it.',
  'A project of yours is bearing fruit, and creative work is favoured. You will get further working with people than working alone.',
  'You learn best when your body is comfortable and rested. Make your study corner pleasant, and the studying will follow.',
  'Money is coming in more easily than usual. Enjoy some of it, save some of it, and share a little.',
  'This week, look after your body and your surroundings, because growth always follows care.'],
'major-4': ['structure|stability|leadership|boundaries', 'rigidity|control|coldness|no structure at all',
  'This is the energy of order and authority. You are being asked to set the rules, to take charge, or to respect the person who is in charge.',
  'Stability matters more than romance right now. A dependable person may be appearing, or you yourself may need to set clear boundaries.',
  'Take the lead, or work well within the system. Plans, hierarchy and discipline will beat improvisation this time.',
  'A timetable and a fixed routine will do more for you than inspiration. Build the frame first.',
  'You need a budget, control and a long-term plan, because money answers to discipline right now.',
  'Decide, then hold your decision. Just make sure it is fair to everyone.'],
'major-5': ['tradition|guidance|learning|belonging', 'dogma|conformity|judging others|rebellion for its own sake',
  'Established ways are supporting you, whether a teacher, a family custom or an institution. Doing things the familiar way will give you peace of mind right now.',
  'This may be a commitment, a family\'s blessing, or a relationship built on shared values. Talk with each other about what you both believe.',
  'Follow the proper process, because a mentor or a formal qualification will help you now. Do not skip steps.',
  'Learn from a good teacher and from the standard material. This is not the week to reinvent the method.',
  'Choose the safe and familiar path with money, because the advice of an experienced person is worth a lot right now.',
  'Ask someone who has walked this road before. Their map can save you months.'],
'major-6': ['connection|choice|values|harmony', 'misalignment|avoiding a decision|temptation|one-sided love',
  'This is a real meeting between two things, or a choice that reveals what you truly value. The energy is about alignment, not just attraction.',
  'You are in a strong bond, facing an important choice about a partner, or standing at the moment where you must decide what you want from love.',
  'Partnership and teamwork are favoured. If you are at a fork, choose the path that fits your values.',
  'Study with a partner or in a group. If you have to choose a subject, choose the one you actually care about.',
  'You are about to make a financial decision that reflects your priorities. Do not choose on the numbers alone.',
  'Choose with your values, not with your fears.'],
'major-7': ['drive|willpower|victory|direction', 'aggression|losing control|scattered effort|running over people',
  'You are in motion and gaining ground. Forces pulling in opposite directions are being held on one course by your will, so keep both hands on the reins.',
  'Pursue what you want, but stay in control of your feelings. This relationship moves forward through effort.',
  'Ambition and momentum are on your side. Push through the obstacle, because you have what it takes, and travel may be part of it.',
  'This week, discipline is your superpower. Set the target and drive toward it.',
  'Money comes to you through determination. The goal you have been chasing is within reach.',
  'Keep both reins in hand, which means confidence and control at the same time.'],
'major-8': ['inner strength|patience|compassion|courage', 'self-doubt|forcing it|raw emotion|weakness felt as shame',
  'Your strength right now is quiet. Patience and kindness will handle what force cannot, because the lion is tamed by calm, not by shouting.',
  'Gentle strength wins here. Deal with tension patiently instead of reacting, because someone needs your calm.',
  'You are facing a difficult person or situation, and your composure is being noticed.',
  'Today, persistence beats brilliance. Keep at it steadily and calmly.',
  'Manage your money steadily rather than making bold moves, and do not let fear decide for you.',
  'Breathe first, then act. The calm version of you is the strongest one.'],
'major-9': ['reflection|wisdom|solitude|seeking', 'isolation|loneliness|withdrawal too long|refusing help',
  'It is time to step back and think. The answer you need is inside you, not in one more opinion. Solitude is useful right now.',
  'You or your partner need space to think. Time alone is not rejection; a deeper connection comes after both of you have reflected.',
  'Think carefully before your next move. A mentor or your own experience will light the way, so avoid deciding in the middle of noise.',
  'Study deeply, alone and with full attention. Turn off your notifications.',
  'Review your finances quietly and honestly. If you need to, ask an expert.',
  'Give yourself one evening alone with the question, and then come back to people.'],
'major-10': ['change|luck|cycles|turning point', 'resisting change|bad luck|feeling out of control|repeating the cycle',
  'The wheel is turning. Your circumstances are shifting whether you push or not, and there is luck in the air as well as change.',
  'Your relationship is entering a new phase, and chance meetings are likely. What goes around comes around.',
  'Expect movement: a new role, a lucky break, or an unexpected turn. Adapt rather than resist.',
  'Your results may swing. Ride the good streak and do not panic at a dip.',
  'Your fortune is changing. Do not gamble, but be ready to catch an opportunity.',
  'Go with the turn, because fighting the wheel only wears you out.'],
'major-11': ['fairness|truth|accountability|clarity', 'unfairness|dishonesty|avoiding consequences|harsh judgement',
  'Cause and effect are plainly visible. Every decision has consequences right now, and only honesty will truly work.',
  'Be honest about what is fair between the two of you. Balance returns when each side owns its part.',
  'You are dealing with contracts, legal matters or evaluations. Do things by the book and keep your records.',
  'Fair effort brings fair results. Be honest with yourself about how much you have actually studied.',
  'Settle your accounts: pay what you owe and collect what you are owed.',
  'Tell the truth, especially to yourself.'],
'major-12': ['pause|surrender|new perspective|letting go', 'stalling|martyrdom|indecision|stuck by choice',
  'Things are on hold, and the pause has a purpose. Seen from a different angle, the situation looks different. Wait willingly.',
  'Your relationship is in limbo, and pushing will not help. Let go of the outcome and see what changes.',
  'There may be a delay or a project on hold. Use the time to rethink the approach instead of forcing it forward.',
  'Step away from the problem for a while. The solution tends to appear when you stop staring at it.',
  'This is not the time to touch your money. Hold and review.',
  'Do nothing for a moment, on purpose, and then look at everything again.'],
'major-13': ['endings|transformation|release|renewal', 'clinging|fear of change|stagnation|dragging out the end',
  'Something is ending so that something else can begin. It may feel heavy, but this energy is clearing, not cruel.',
  'A relationship, or one version of it, is closing. Let yourself grieve, and then let its new shape appear.',
  'A role, a project or a way of working is coming to an end. Do not cling, because what comes next needs this very space.',
  'An old study method or an old goal has run its course. Change how you learn.',
  'A financial chapter is closing. Cut what no longer works and rebuild from there.',
  'Let it end, because you cannot open a new chapter while you are still holding the last page.'],
'major-14': ['balance|moderation|patience|healing', 'excess|imbalance|impatience|clashing priorities',
  'Blend rather than force. The energy now is about finding the middle path and taking your time, because real healing is happening.',
  'Harmony grows through patience and give-and-take. Avoid extremes, both in feeling and in demand.',
  'Work steadily as a team and balance your tasks with care. Do not rush, and combine everyone\'s strengths.',
  'Steady pacing beats cramming. Balance study with rest.',
  'Spend moderately and save moderately. No dramatic moves are needed right now.',
  'Have a little of everything, and nothing to excess.'],
'major-15': ['attachment|desire|ambition|raw honesty', 'addiction|obsession|toxic patterns|feeling trapped',
  'Something has a grip on you, whether a habit, a person or a craving. This energy is powerful and not necessarily bad, but you need to see the chain.',
  'You are in an intense attraction or a bond that is hard to leave. Ask yourself: does it feed you or drain you?',
  'You may be full of ambition and drive, or you may be owned by a job. Check what you are trading for the money.',
  'Distraction and procrastination are strong right now. Name the habit that is stealing your time.',
  'Watch out for debt, impulse spending, and money that comes with strings attached.',
  'Name the thing that has hold of you, because once it is named, the chain loosens.'],
'major-16': ['sudden change|revelation|breakthrough|freedom', 'disaster|shock|avoidable collapse|refusing the lesson',
  'Something built on shaky ground is coming down. It is a shock, but what falls was never solid, and the truth is breaking through.',
  'A sudden upheaval or a revealed truth is here. It hurts, but it clears away what was false.',
  'There is sudden change at work: a plan collapses or a structure is challenged. Rebuild on firmer ground.',
  'Your study plan is falling apart. Reassess and build a new schedule from scratch.',
  'An unexpected expense or loss may come. Protect the basics first.',
  'Let the false thing fall, and then rebuild with what is true.'],
'major-17': ['hope|healing|inspiration|renewal', 'discouragement|lost faith|self-doubt|empty optimism',
  'After hard times, a calm has come to you. Hope right now is real rather than forced, and you are being restored.',
  'You are healing after hurt, and your openness is returning. An honest, calm kind of love is near.',
  'Inspiration and a sense of purpose are coming back. This is a good time for creative and long-term plans.',
  'Your motivation to study is returning. You can see clearly why you are learning this.',
  'Money troubles are easing. You can give generously, within reason.',
  'Trust the quiet hope, because it is telling you the truth.'],
'major-18': ['intuition|dreams|uncertainty|the unconscious', 'illusion|anxiety|deception|confusion',
  'Nothing is fully clear yet. Fear and imagination are colouring what you see, so move slowly and trust your instincts rather than your worries.',
  'You are getting mixed signals and feeling unsure. Something is hidden, but do not assume the worst; ask directly instead.',
  'There is confusion or unclear information at work. Wait for the facts before you act.',
  'Anxiety is clouding your understanding. Get some sleep, then review with a clear head.',
  'Money matters are unclear or risky at the moment. Do not sign anything you do not fully understand.',
  'Walk slowly through the fog, because the fog will lift.'],
'major-19': ['joy|success|clarity|vitality', 'arrogance|overexposure|delayed happiness|false cheer',
  'Your energy is warm, clear and confident. Things are working and it shows, so enjoy it openly.',
  'You have happiness, warmth and an easy connection. This relationship is standing in full daylight.',
  'You are succeeding, being recognised, and winning clearly. Your work is being seen.',
  'You are clear and confident. Good results are on their way.',
  'Good fortune and growth are with you. Money comes with joy rather than with struggle.',
  'Say yes to this good thing, because you have earned it.'],
'major-20': ['awakening|a calling|forgiveness|reckoning', 'self-judgement|refusing the call|regret|stuck in the past',
  'This is a moment of clear seeing. You are being called to a decision, a change, or a new level of life. The past is being reviewed and released.',
  'Your relationship is reaching a turning point. Forgive, decide, and move on.',
  'You are hearing a calling in your career, perhaps an evaluation or a chance to rise. Answer it.',
  'Results and evaluations are coming. Learn from the past and step up.',
  'You are in a financial reckoning. Face the numbers and decide.',
  'Answer the call, because you already know what it is.'],
'major-21': ['completion|wholeness|achievement|travel', 'unfinished business|delay|feeling incomplete|short-cuts',
  'A cycle is closing, and you have absorbed its lesson. This is fulfilment, and it is also the doorway to the next round.',
  'Your relationship is reaching a whole and mature stage, or the two of you are about to travel together.',
  'You are completing a big project and being recognised. Travel or an international connection may follow.',
  'You are graduating, completing, or mastering a subject.',
  'You are reaching your financial goal, and this security will last.',
  'Finish it properly, and then celebrate before you start the next thing.']
});
