/* ============================ card insights, the 56 Minors, rewritten ============================
   Full sentences, a clear subject in every line, each thought leading into
   the next. Same field order as insight-en.js / insight-vi.js:
   [positive keywords, shadow keywords, energy now, love, work, study, money, advice]. */
Object.assign(INSIGHT.vi, {
'wands-1': ['tia lửa|cảm hứng|năng lượng mới|khao khát', 'khởi đầu hụt|không có hướng|chậm trễ|cháy hết sớm',
  'Trong bạn đang dâng lên một mong muốn làm ra điều gì đó. Năng lượng này còn thô và chưa nhắm vào đâu, nên bạn hãy chọn cho nó một hướng.',
  'Một sức hút mới hoặc một đam mê mới vừa lóe lên. Bạn cứ vui với nó, nhưng hãy nhớ rằng một tia lửa chưa phải là một lời hứa.',
  'Một ý tưởng hoặc một lời đề nghị mới đang đến, và phía sau nó có năng lượng thật. Bạn hãy bắt đầu ngay.',
  'Bạn đang hứng thú với một môn mới. Bạn hãy dùng sự hứng thú ấy trước khi nó nguội đi.',
  'Bạn đang có một ý tưởng kiếm tiền mới. Bạn hãy thử ở quy mô nhỏ trước.',
  'Bạn hãy nhóm lửa trước, rồi mới xây bếp.'],
'wands-2': ['lên kế hoạch|tầm nhìn|lựa chọn|chân trời rộng', 'chơi an toàn|sợ điều chưa biết|kế hoạch không bao giờ chạy',
  'Bạn đang cầm trong tay một thứ và nhìn ra xa hơn nó. Đã đến lúc bạn chọn chân trời rộng hơn thay vì chân trời quen thuộc.',
  'Bạn đang quyết định mình muốn gì từ tình yêu, hoặc đang chọn giữa sự dễ chịu và một lựa chọn táo bạo hơn.',
  'Bạn đang lên kế hoạch mở rộng, hợp tác hoặc bước tiếp theo. Bạn hãy nghĩ lớn, rồi cam kết với một hướng.',
  'Bạn đang chọn hướng đi hoặc chuyên ngành. Bạn hãy lên kế hoạch cho cả năm chứ không chỉ tuần này.',
  'Bạn đang lên kế hoạch đầu tư. Bạn hãy cân bằng giữa an toàn và tăng trưởng.',
  'Bạn hãy quyết định hướng đi trước, còn chi tiết có thể tính sau.'],
'wands-3': ['mở rộng|nhìn xa|tiến triển|chờ đúng cách', 'chậm trễ|nóng vội|nghĩ quá nhỏ|không theo tới cùng',
  'Những nỗ lực đầu tiên của bạn đã ra ngoài kia và đang có tác dụng. Bây giờ bạn chờ, và chuẩn bị cho những gì sẽ quay về.',
  'Điều bạn đã khởi động đang phát triển. Bạn hãy cho nó thời gian, và đừng loại trừ một mối duyên ở xa.',
  'Công việc của bạn đang tăng trưởng và mở ra thị trường mới nhờ những nỗ lực trước đây. Bạn hãy giữ mắt ở chân trời.',
  'Phần nền của bạn đã xong, và kết quả đang trên đường đến.',
  'Khoản đầu tư trước đây của bạn bắt đầu sinh lời. Sự kiên nhẫn đang được đền đáp.',
  'Bạn hãy nhìn vào chân trời thay vì nhìn đồng hồ.'],
'wands-4': ['ăn mừng|mái nhà|ổn định|cộng đồng', 'bất ổn|căng thẳng trong nhà|kế hoạch bị hủy|thấy không được chào đón',
  'Bạn vừa đến một cột mốc, một lần về nhà, hay một lý do để tụ họp. Đây là niềm vui có nền tảng vững.',
  'Có thể là một cam kết, một lần dọn về ở chung, hoặc một buổi ăn mừng với người thân.',
  'Đội nhóm của bạn vừa đạt một cột mốc, hoặc bạn đang ở một nơi làm việc ổn định và ủng hộ nhau. Bạn hãy ăn mừng.',
  'Bạn vừa đạt một cột mốc. Một nhóm học hoặc một môi trường hỗ trợ đang giúp bạn tiến xa.',
  'Tài chính của bạn đang ổn định, và việc mua sắm cho nhà cửa lúc này là hợp lý.',
  'Bạn hãy đánh dấu cột mốc này, rồi cho phép mình nghỉ ngơi.'],
'wands-5': ['cạnh tranh|tranh luận|năng lượng|thử sức', 'xung đột|hỗn loạn|cãi vì cãi|né cuộc tranh',
  'Nhiều luồng năng lượng đang va vào nhau: ý kiến, cái tôi, kế hoạch. Chuyện này không nguy hiểm, chỉ ồn ào, nên bạn hãy cạnh tranh cho công bằng.',
  'Hai bạn đang cãi vặt, ganh đua, hoặc gặp quá nhiều khác biệt cùng lúc. Bạn hãy tranh luận về chuyện thật sự quan trọng.',
  'Bạn đang trong một môi trường cạnh tranh với nhiều ý kiến trái chiều, và khó được lắng nghe. Bạn hãy ở lại trong cuộc chơi.',
  'Môi trường học của bạn đang cạnh tranh, hoặc sự tập trung của bạn đang bị chia nhỏ. Bạn hãy chọn một trận để đánh.',
  'Nhiều nhu cầu đang giành nhau cùng một khoản tiền. Bạn hãy sắp xếp lại thứ tự ưu tiên.',
  'Bạn hãy chọn trận đáng đánh và bỏ qua phần còn lại.'],
'wands-6': ['chiến thắng|được công nhận|tự tin|tiến bộ', 'cái tôi|từ đỉnh rơi xuống|không được nhìn thấy|thắng rỗng',
  'Một chiến thắng của bạn đang được để ý. Bạn đang dẫn trước và mọi người thấy điều đó, nên bạn hãy tận hưởng sự công nhận này.',
  'Bạn đang được ngưỡng mộ, và bạn có một mối quan hệ khiến mình tự hào.',
  'Bạn sắp được thăng chức, được khen, hoặc thành công trước mọi người. Bạn hãy nhận điều đó một cách lịch thiệp.',
  'Bạn đang có kết quả tốt và được công nhận. Sự tự tin của bạn là có căn cứ.',
  'Bạn sắp nhận một khoản thưởng hoặc một thắng lợi tài chính.',
  'Bạn hãy nhận tràng vỗ tay, rồi tiếp tục cưỡi ngựa về phía trước.'],
'wands-7': ['phòng thủ|bền bỉ|can đảm|giữ vững vị trí', 'bỏ cuộc|kiệt sức|thấy quá tải|phòng thủ thái quá',
  'Bạn đang giữ một vị trí trước áp lực từ nhiều phía. Chuyện này mệt, nhưng bạn đang ở thế cao hơn.',
  'Bạn đang bảo vệ mối quan hệ hoặc nhu cầu của chính mình. Bạn hãy đứng vững mà không cần gây chiến.',
  'Vị trí của bạn đang bị cạnh tranh hoặc thách thức. Bạn hãy giữ đất bằng kỹ năng của mình.',
  'Bạn đang chịu áp lực và thử thách. Bạn hãy đi tiếp, vì bạn mạnh hơn nỗi nghi ngờ.',
  'Bạn hãy bảo vệ những gì mình có trước những đòi hỏi từ bên ngoài, và học cách nói không.',
  'Bạn hãy giữ vững, nhưng nhớ thở trong lúc giữ.'],
'wands-8': ['nhanh|tin tức|chuyển động|đà', 'chậm trễ|hỗn loạn|quyết vội|hiểu lầm',
  'Mọi thứ đang đi rất nhanh: tin nhắn, chuyến đi, những tiến triển bất ngờ. Bạn hãy theo kịp và giữ đầu óc tỉnh táo.',
  'Chuyện tình cảm đang diễn biến nhanh với nhiều tin nhắn qua lại. Bạn hãy trả lời đúng lúc.',
  'Công việc tiến nhanh, tin tức đến dồn dập, và có thể có chuyến đi. Bạn hãy hành động nhanh với những lời đề nghị.',
  'Bạn đang tiến nhanh, nhưng hạn nộp cũng đang đến gần. Bạn hãy làm ngay.',
  'Tiền đang đi nhanh, cả cơ hội lẫn chi tiêu. Bạn hãy để mắt đến cả hai.',
  'Bạn hãy làm nhanh, nhưng giữ cho đầu mình lạnh.'],
'wands-9': ['bền bỉ|kiên trì|cảnh giác|nỗ lực cuối', 'đa nghi|kiệt sức|từ chối giúp đỡ|dựng rào',
  'Bạn đang mệt, nhưng bạn đã gần tới đích. Bạn hãy giữ lấy những gì mình đã xây và bước nốt bước cuối.',
  'Bạn đang đề phòng vì tổn thương cũ. Bạn hãy bảo vệ mình, nhưng đừng rào kín với tất cả mọi người.',
  'Bạn sắp xong một chặng khó. Bạn hãy kiên trì thêm một chút và đặt ranh giới rõ ràng.',
  'Đây là cú nước rút cuối trước kỳ thi hay hạn nộp. Bạn hãy giữ đúng nhịp.',
  'Bạn hãy bảo vệ khoản tiết kiệm của mình và cẩn thận với những cam kết mới.',
  'Bạn hãy bước thêm một bước nữa, rồi nghỉ ngơi thật sự.'],
'wands-10': ['trách nhiệm|gánh nặng|làm việc chăm|quyết tâm', 'quá tải|kiệt sức|gánh cho người khác|không giao việc',
  'Bạn đang mang rất nhiều, có lẽ là quá nhiều. Gánh nặng này là thật, nhưng sức của bạn cũng thật, và có một thứ bạn có thể đặt xuống.',
  'Bạn đang ôm hết phần cảm xúc trong mối quan hệ. Bạn hãy chia sẻ gánh nặng ấy.',
  'Bạn đang làm quá sức với quá nhiều nhiệm vụ. Bạn hãy giao bớt hoặc bỏ bớt một việc.',
  'Lịch học của bạn đang quá dày. Bạn hãy cắt bớt, chỉ giữ lại điều quan trọng.',
  'Bạn đang gánh nhiều nghĩa vụ tài chính. Bạn hãy đơn giản hóa chúng.',
  'Hôm nay bạn hãy đặt xuống một thứ.'],
'wands-c0': ['nhiệt tình|khám phá|tin nhắn|ý tưởng mới', 'thiếu định hướng|nóng vội|non nớt|chậm trễ',
  'Bạn đang tò mò, háo hức và hơi bồn chồn. Một ý tưởng hay một tin nhắn mới đang đến, và bạn hãy khám phá nó.',
  'Có một người đang tán tỉnh bạn, một tin nhắn mới, hoặc một người trẻ trong tâm hồn. Chuyện này vui, nhưng chưa nghiêm túc.',
  'Bạn đang có một ý tưởng mới, một vị trí tập sự, hoặc một tin vui về công việc.',
  'Bạn đang tò mò và hăng hái. Bạn hãy khám phá những chủ đề mới.',
  'Bạn đang có một ý tưởng mới về tiền. Bạn hãy tìm hiểu kỹ trước khi đầu tư.',
  'Bạn hãy đi theo tia lửa ấy và xem nó dẫn mình đến đâu.'],
'wands-c1': ['hành động|đam mê|phiêu lưu|cuốn hút', 'liều lĩnh|bốc đồng|kiêu ngạo|đi quá sớm',
  'Bạn đang táo bạo, nhanh, cuốn hút và thiếu kiên nhẫn. Bạn đã sẵn sàng lao lên, nhưng hãy ngắm trước rồi mới đi.',
  'Bạn đang gặp một người đầy đam mê, hoặc chính bạn đang ở một giai đoạn như thế. Chuyện này hấp dẫn, nhưng không phải lúc nào cũng đáng tin.',
  'Bạn đang hành động táo bạo, đi lại nhiều và nắm quyền. Bạn hãy coi chừng sự bốc đồng.',
  'Năng lượng của bạn đến theo từng đợt. Bạn hãy dồn chúng vào một kế hoạch.',
  'Bạn đang định đi một nước cờ tiền bạc táo bạo. Nó có rủi ro, nên bạn hãy xem kỹ chi tiết.',
  'Bạn cứ lao lên, nhưng hãy biết vực nằm ở đâu.'],
'wands-c2': ['ấm áp|tự tin|độc lập|có sức hút', 'ghen|đòi hỏi|kịch tính|cháy sạch',
  'Năng lượng của bạn đang ấm, tự tin và cuốn hút. Bạn đang thu hút sự chú ý, nên bạn hãy dùng điều đó cho việc tốt.',
  'Bạn đang có một người bạn đời tự tin và ấm áp, hoặc chính sự tự tin dễ mến của bạn đang tỏa sáng.',
  'Bạn đang dẫn dắt bằng sự ấm áp và truyền cảm hứng cho cả nhóm.',
  'Bạn đang học một cách tự tin và tự định hướng.',
  'Bạn đang quản lý tiền một cách tự tin và độc lập.',
  'Bạn hãy tỏa sáng, và để người khác cũng được tỏa sáng.'],
'wands-c3': ['tầm nhìn|dẫn dắt|táo bạo|làm chủ', 'độc đoán|thiếu kiên nhẫn|kỳ vọng quá cao|tàn nhẫn',
  'Bạn đang mang năng lượng lãnh đạo nhìn xa và táo bạo, và chính bạn đang đặt hướng đi. Bạn hãy dẫn dắt bằng cảm hứng chứ không bằng mệnh lệnh.',
  'Bạn đang ở bên một người bạn đời có sức hút và nhiều động lực, hoặc chính bạn đang là người dẫn dắt trong tình yêu.',
  'Bạn đang dẫn dắt dự án bằng tầm nhìn cộng với hành động.',
  'Bạn hãy tự nắm lấy lộ trình học của mình.',
  'Bạn đang xử lý tiền theo kiểu khởi nghiệp: táo bạo nhưng có tính toán.',
  'Bạn hãy đi đầu, bằng cả trái tim.'],

'cups-1': ['tình cảm mới|khởi đầu cảm xúc|bao dung|sáng tạo', 'trống rỗng|cảm xúc bị chặn|thiếu yêu bản thân|cảm xúc tràn',
  'Trái tim bạn đang mở ra với một cảm xúc mới, một lòng trắc ẩn mới, hay một khởi đầu sáng tạo. Bạn hãy đón nhận nó.',
  'Một tình yêu mới đang đến, hoặc cảm xúc cũ đang được làm mới. Bạn đang cởi mở hơn bao giờ hết.',
  'Bạn đang thấy thỏa mãn về mặt cảm xúc trong công việc, với một khởi đầu sáng tạo và những mối quan hệ tốt.',
  'Bạn đang tìm thấy niềm vui trong việc học, và một môn sáng tạo đang gọi bạn.',
  'Tiền đang đến từ việc bạn yêu thích, và sự hào phóng đang chảy quanh bạn.',
  'Bạn hãy để chiếc cốc được đầy lên.'],
'cups-2': ['gắn kết|hấp dẫn hai chiều|kết nối|cân bằng', 'lệch cân|chia tay|hiểu lầm|một phía',
  'Bạn đang có một kết nối thật sự với một người hoặc một phía khác. Sự tôn trọng và hấp dẫn đến từ cả hai bên.',
  'Bạn đang ở trong một mối gắn bó mạnh mẽ từ hai phía, hoặc vừa có một cuộc gặp gỡ có ý nghĩa.',
  'Bạn đang có một sự hợp tác kinh doanh tốt hoặc một mối quan hệ làm việc vững chắc.',
  'Bạn đã tìm được một người bạn học hoặc một người hướng dẫn hợp với mình.',
  'Bạn đang trong một sự hợp tác tài chính công bằng.',
  'Bạn hãy gặp người kia ở giữa đường, mọi chuyện sẽ ổn.'],
'cups-3': ['tình bạn|ăn mừng|cộng đồng|sáng tạo', 'đàm tiếu|quá đà|người thứ ba|cô lập',
  'Năng lượng quanh bạn đang vui vẻ và đông người, với bạn bè, tụ họp và niềm vui chung.',
  'Bạn đang ăn mừng cùng bạn bè. Nhưng nếu có người thứ ba trong bức tranh, bạn hãy kiểm tra lại.',
  'Bạn đang làm việc nhóm hiệu quả, ăn mừng thành quả, hoặc bắt đầu một sự hợp tác sáng tạo.',
  'Học nhóm đang rất hiệu quả với bạn. Bạn hãy ăn mừng những tiến bộ nhỏ.',
  'Bạn đang chi cho đời sống xã hội. Bạn hãy vui trong chừng mực.',
  'Bạn hãy gọi cho bạn bè của mình.'],
'cups-4': ['ngẫm nghĩ|thờ ơ|xem lại|chán', 'bỏ lỡ cơ hội|thu mình|vô ơn|tê liệt',
  'Bạn đang thấy chán, không ấn tượng và không chắc chắn. Có một lời đề nghị đang ở ngay đó mà bạn chưa nhìn thấy, nên bạn hãy ngước lên.',
  'Bạn đang chán hoặc xa cách về cảm xúc, và có một điều tốt đang bị bỏ qua.',
  'Bạn đang không hài lòng và có thể đã bỏ lỡ một cơ hội. Bạn hãy xem lại mình thật sự muốn gì.',
  'Bạn đang mất động lực. Bạn hãy đổi cách tiếp cận.',
  'Bạn có thể đã bỏ lỡ một cơ hội tiền bạc. Bạn hãy chú ý hơn.',
  'Bạn hãy nhìn vào điều đang được đưa ra trước khi từ chối nó.'],
'cups-5': ['đau buồn|hối tiếc|mất mát|chấp nhận', 'không chịu đi tiếp|thương thân|dằn vặt|cô lập',
  'Bạn đang buồn vì điều đã mất, và nỗi buồn ấy là thật. Nhưng không phải tất cả đã đổ, vì hai chiếc cốc vẫn đang đứng.',
  'Bạn đang thất vọng hoặc vừa mất mát trong tình yêu. Bạn hãy cho phép mình buồn, rồi quay người lại.',
  'Bạn vừa gặp một bước lùi hoặc một thất vọng. Bạn hãy học từ nó rồi đi tiếp.',
  'Bạn vừa nhận một kết quả kém, nhưng đó chưa phải là hết. Bạn hãy quay về với những gì còn lại.',
  'Bạn vừa mất một khoản tiền. Bạn hãy đánh giá phần còn lại.',
  'Bạn hãy quay lại, vì hai chiếc cốc vẫn còn đầy.'],
'cups-6': ['hoài niệm|hồn nhiên|tử tế|quá khứ', 'kẹt trong quá khứ|ngây thơ|ký ức tô hồng|níu kéo',
  'Những ký ức ngọt ngào, sự tử tế và một điều gì đó hồn nhiên đang quay về. Quá khứ đang ghé thăm bạn một cách nhẹ nhàng.',
  'Một người xưa, một sự ngọt ngào thời thơ ấu, hoặc một tình cảm giản dị đang xuất hiện.',
  'Một mối quan hệ cũ đang quay lại, hoặc bạn đang nhận được sự tử tế ở nơi làm.',
  'Bạn hãy ôn lại phần căn bản, vì kiến thức cũ đang giúp ích cho bạn.',
  'Bạn sắp nhận một món quà, hoặc một khoản tiền từ quá khứ.',
  'Bạn hãy tận hưởng ký ức, nhưng sống ở hiện tại.'],
'cups-7': ['lựa chọn|tưởng tượng|mơ mộng|khả năng', 'ảo tưởng|mơ hão|quá nhiều lựa chọn|trốn thực tế',
  'Bạn đang có nhiều lựa chọn và nhiều mộng tưởng, nhưng không phải tất cả đều thật. Bạn hãy chọn bằng đôi mắt sáng.',
  'Bạn đang lẫn lộn giữa mộng tưởng và thực tế trong tình yêu, có thể đang lý tưởng hóa ai đó. Bạn hãy nhìn họ cho rõ.',
  'Bạn đang có quá nhiều khả năng trước mặt. Bạn hãy tập trung vào một con đường thực tế.',
  'Bạn đang bị xao nhãng và mơ mộng. Bạn hãy chọn một việc và làm.',
  'Bạn đang mộng tưởng về tiền. Bạn hãy ngồi xuống làm phép tính.',
  'Bạn hãy chọn một chiếc cốc, với đôi mắt mở to.'],
'cups-8': ['bước đi|tìm điều hơn|buông bỏ|tìm sâu hơn', 'sợ thay đổi|vô định|bỏ chạy|ở lại quá lâu',
  'Bạn đang bỏ lại một thứ để đi tìm điều sâu hơn. Đó vừa là một mất mát, vừa là một sự giải thoát.',
  'Bạn đang bước ra khỏi điều không còn làm mình đủ đầy. Việc này khó, nhưng đúng.',
  'Bạn đang rời một công việc hay một vai trò để tìm điều ý nghĩa hơn.',
  'Bạn đang đổi hướng học. Bạn hãy bỏ lại những gì không hợp với mình.',
  'Bạn đang rời khỏi một tình trạng tài chính đang rút cạn mình.',
  'Bạn hãy đi đi, vì điều bạn tìm không ở đây.'],
'cups-9': ['hài lòng|mãn nguyện|ước thành|tận hưởng', 'tự mãn|hưởng thụ quá đà|vui nông|vẫn chưa đủ',
  'Điều ước của bạn đang thành sự thật, kèm theo sự dễ chịu và tận hưởng. Bạn đã có điều mình xin, nên bạn hãy hưởng nó.',
  'Bạn đang thấy thỏa mãn về cảm xúc và tìm thấy niềm vui trong tình yêu.',
  'Bạn đang đạt thành tựu và thấy hài lòng với công việc.',
  'Bạn đang thành công và hài lòng với kết quả học tập.',
  'Tài chính của bạn đang dễ chịu. Bạn hãy tự thưởng cho mình một cách khôn ngoan.',
  'Bạn hãy tận hưởng, vì bạn đã xin và nó đã đến.'],
'cups-10': ['hòa thuận|gia đình|hạnh phúc lâu dài|thuộc về', 'gia đình rạn|bất hòa|kỳ vọng phi thực tế|lơ là',
  'Bạn đang có một hạnh phúc sâu, được chia sẻ và bền lâu, với gia đình, mái nhà và sự đủ đầy về cảm xúc.',
  'Bạn đang trong một mối quan hệ yêu thương và cam kết, và gia đình đang hòa thuận.',
  'Công việc của bạn đang đủ đầy, và quan hệ với đồng nghiệp đang tốt đẹp.',
  'Gia đình đang ủng hộ việc học của bạn.',
  'Gia đình bạn đang có sự an toàn về tài chính.',
  'Đây chính là điều tốt đẹp, nên bạn hãy giữ nó thật nhẹ tay.'],
'cups-c0': ['sáng tạo|trực giác|thông điệp cảm xúc|nhạy cảm', 'non nớt về cảm xúc|thất thường|bí ý tưởng|trốn thực tế',
  'Một thông điệp hay một xung động dịu dàng và giàu tưởng tượng đang đến với bạn. Có một điều mới đang khẽ động trong tim bạn.',
  'Bạn đang nhận một tin nhắn ngọt ngào, có một crush mới, hoặc đang ở một khởi đầu dịu dàng.',
  'Bạn đang có một ý tưởng sáng tạo hoặc nhận một thông điệp cảm xúc ở nơi làm.',
  'Bạn đang học bằng trực giác, và nghệ thuật hay sáng tạo đang hợp với bạn.',
  'Bạn sắp nhận một món quà nhỏ bất ngờ.',
  'Bạn hãy lắng nghe cảm giác nhỏ ấy.'],
'cups-c1': ['lãng mạn|duyên dáng|theo trái tim|lý tưởng', 'thất thường|phi thực tế|ghen|lừa dối',
  'Năng lượng của bạn đang lãng mạn, duyên dáng và lý tưởng, và bạn đang đi theo trái tim. Bạn hãy kiểm tra xem chân mình còn chạm đất không.',
  'Bạn đang nhận một lời tỏ tình lãng mạn hoặc gặp một người theo đuổi duyên dáng. Bạn cứ vui, nhưng hãy coi chừng ảo ảnh.',
  'Bạn đang làm những dự án sáng tạo và tiếp cận mọi việc một cách khéo léo.',
  'Bạn đang học với cảm hứng, nhất là nghệ thuật, âm nhạc và văn chương.',
  'Bạn đang chi tiêu theo cảm xúc. Bạn hãy dừng lại một chút trước khi mua.',
  'Bạn hãy đi theo trái tim với đôi mắt mở.'],
'cups-c2': ['bao dung|bình tĩnh|trực giác|an toàn cảm xúc', 'bất an|lệ thuộc|hy sinh quá mức|quá tải',
  'Năng lượng của bạn đang bình tĩnh, quan tâm và giàu trực giác. Bạn hiểu người khác và hiểu chính mình, nhưng bạn hãy nhớ chăm cả bản thân.',
  'Bạn đang có một người bạn đời biết chăm sóc và yêu thương, hoặc chính sự chín chắn về cảm xúc của bạn đang dẫn đường.',
  'Sự thấu cảm và trực giác đang dẫn đường cho công việc của bạn, và bạn đang hỗ trợ đồng nghiệp rất tốt.',
  'Bạn đang học bằng cách hiểu chứ không phải bằng cách thuộc lòng.',
  'Bạn đang chọn cách dùng tiền bằng trực giác và lo cho sự an toàn của mình.',
  'Bạn hãy chăm người khác, nhưng nhớ để lại một phần cho mình.'],
'cups-c3': ['cân bằng cảm xúc|khéo léo|khôn ngoan|bao dung', 'thao túng cảm xúc|thất thường|dễ bùng|lạnh',
  'Bạn đang làm chủ cảm xúc một cách chín chắn. Cảm xúc của bạn mạnh, nhưng chúng được giữ bằng sự khôn ngoan.',
  'Bạn đang ở bên một người bạn đời chín chắn và cân bằng về cảm xúc, và tình yêu của hai bạn có nhiều bao dung.',
  'Bạn đang dẫn dắt một cách khéo léo và bình tĩnh, và đối xử với mọi người rất cẩn thận.',
  'Bạn đang tiếp cận việc học một cách cân bằng và khôn ngoan.',
  'Bạn đang quản lý tiền một cách cân bằng và khôn ngoan.',
  'Bạn hãy cảm nhận thật sâu, nhưng hành động thật điềm tĩnh.'],

'swords-1': ['rõ ràng|sự thật|bứt phá|ý tưởng mới', 'rối|lạm dụng sức mạnh|lời cay nghiệt|phán đoán mờ',
  'Đầu óc bạn đang có một khoảnh khắc sáng rõ, khi sự thật cắt xuyên qua mọi thứ. Bạn đang có ý tưởng mới và suy nghĩ quyết đoán.',
  'Bạn đang có những cuộc nói chuyện thẳng thắn và thấy rõ điều mình muốn.',
  'Bạn vừa có một ý tưởng đột phá và đang đưa ra những quyết định rõ ràng.',
  'Bạn đang suy nghĩ rất sắc và vừa hiểu ra một điều mới.',
  'Bạn đang tư duy rõ ràng về tiền và có một kế hoạch quyết đoán.',
  'Bạn hãy nói điều thật, một cách tử tế.'],
'swords-2': ['do dự|bế tắc|cân nhắc|đình chiến', 'né tránh|chối bỏ|tê liệt|trốn',
  'Bạn đang kẹt giữa hai lựa chọn và đang né tránh việc phải chọn. Tấm bịt mắt ấy là của bạn, và bạn có thể tháo nó ra.',
  'Bạn đang né một quyết định về mối quan hệ. Bạn hãy đối diện với nó.',
  'Bạn đang bế tắc hoặc đang tránh một quyết định. Bạn hãy thu thập sự thật, rồi chọn.',
  'Bạn đang giằng co giữa các lựa chọn. Bạn hãy chọn một và đi.',
  'Một quyết định tài chính của bạn đang bị treo. Bạn hãy quyết định đi.',
  'Bạn hãy tháo bịt mắt ra và chọn.'],
'swords-3': ['tan vỡ|đau buồn|sự thật đau|giải tỏa', 'ôm nỗi đau|cay đắng|tự làm mình đau|không chịu lành',
  'Bạn đang chịu một nỗi đau sắc, thường đến từ một sự thật hoặc một mất mát. Nó đau, nhưng nó cũng làm mọi thứ rõ ràng, nên bạn hãy để nó ra.',
  'Bạn đang tan vỡ, bị phản bội, hoặc đối diện một sự thật đau lòng. Bạn hãy cảm nhận nó, rồi lành lại.',
  'Bạn vừa gặp một bước lùi đau hoặc một lời phê bình nặng nề. Bạn hãy học từ đó và hồi phục.',
  'Bạn đang thất vọng. Chuyện này đau, nhưng chỉ tạm thời.',
  'Bạn vừa mất một khoản tiền đau. Bạn hãy hồi phục và xây lại.',
  'Bạn hãy để nước mắt rơi, rồi mới lành.'],
'swords-4': ['nghỉ|hồi phục|ngẫm|rút lui', 'kiệt sức|bồn chồn|cô lập|né hành động',
  'Bạn cần nghỉ. Đây là lúc để rút lui, hồi phục và suy nghĩ, chứ không phải lúc chiến đấu.',
  'Mối quan hệ của bạn đang trong một khoảng lặng. Bạn hãy lấy lại năng lượng.',
  'Bạn hãy nghỉ một chút và hồi phục trước thử thách tiếp theo.',
  'Bạn hãy nghỉ trước khi học tiếp, vì đầu óc bạn cần điều đó.',
  'Bạn hãy tạm dừng mọi việc liên quan đến tiền và xem lại trong yên lặng.',
  'Bạn hãy nghỉ ngơi, thật sự nghỉ.'],
'swords-5': ['xung đột|thua|thắng mà trả giá|căng thẳng', 'thù địch|bắt nạt|không ai thắng|bẽ mặt',
  'Bạn đang ở trong một cuộc xung đột mà không ai thật sự thắng. Bạn hãy tự hỏi trận này có đáng không.',
  'Hai bạn đang cãi nhau với những lời làm tổn thương. Thắng cuộc cãi có thể khiến bạn mất mối quan hệ.',
  'Bạn đang gặp xung đột ở nơi làm, hoặc vừa có một chiến thắng rỗng. Bạn hãy chọn trận mà đánh.',
  'Sự ganh đua đang làm bạn đau. Bạn hãy tập trung vào con đường của mình.',
  'Bạn đang trong một tranh chấp tiền bạc. Bạn đừng cãi vì chuyện nhỏ.',
  'Bạn hãy rời khỏi trận không thể thắng, một cách đàng hoàng.'],
'swords-6': ['chuyển tiếp|đi tiếp|lành|nước lặng hơn', 'kẹt|hành lý chưa xong|chống thay đổi|chuyến đi khó',
  'Bạn đang rời vùng nước động để sang vùng nước lặng hơn. Đây là một sự chuyển tiếp lặng lẽ và cần thiết.',
  'Bạn đang đi tiếp sau khó khăn và đang lành lại, có thể với một khoảng cách.',
  'Bạn đang chuyển sang một tình huống tốt hơn, và có thể có một chuyến đi.',
  'Bạn đang qua một giai đoạn khó và đang tiến bộ.',
  'Tài chính của bạn đang hồi phục dần.',
  'Bạn hãy chèo về phía bình yên, vì nó ở ngay đó.'],
'swords-7': ['chiến lược|khôn khéo|tự lập|lách được', 'lừa dối|trộm|tự lừa mình|bị bắt',
  'Bạn đang dùng chiến lược, làm việc lặng lẽ và tự làm một mình. Đôi khi việc này là khôn, đôi khi là lén, nên bạn hãy kiểm tra lại động cơ của mình.',
  'Trong mối quan hệ đang có bí mật hoặc sự lừa dối. Thật thà sẽ an toàn hơn.',
  'Bạn đang dùng chiến lược và làm việc độc lập, hoặc có ai đó đang không thẳng thắn với bạn.',
  'Bạn đang đi đường tắt. Bạn hãy cẩn thận kẻo nó phản tác dụng.',
  'Bạn hãy coi chừng lừa đảo và khôn khéo với tiền.',
  'Bạn hãy khôn, nhưng đừng lén.'],
'swords-8': ['thấy bị trói|hạn chế|niềm tin tự giới hạn|bất lực', 'tâm lý nạn nhân|tê liệt|tự giam|tự phá',
  'Bạn đang thấy bị trói, nhưng sợi dây lỏng hơn vẻ ngoài của nó. Nhà tù này phần lớn nằm trong đầu bạn.',
  'Bạn đang thấy kẹt trong mối quan hệ, nhưng bạn có nhiều lựa chọn hơn mình nghĩ.',
  'Bạn đang thấy bị bó buộc ở nơi làm. Bạn hãy tìm lối ra mà mình chưa nhìn thấy.',
  'Bạn đang thấy quá tải. Bạn hãy chia việc thành những bước nhỏ.',
  'Tiền của bạn đang bị bó. Bạn hãy tìm các phương án khác.',
  'Sợi dây đã lỏng rồi, nên bạn hãy cử động đi.'],
'swords-9': ['lo âu|lo lắng|ác mộng|tội lỗi', 'tuyệt vọng|mất hy vọng|nghĩ tới điều tệ nhất|cô lập',
  'Nỗi lo đang làm bạn mất ngủ, nhưng phần lớn nỗi sợ ấy lớn hơn sự thật. Bạn hãy tìm một người để nói chuyện.',
  'Bạn đang lo âu về mối quan hệ. Bạn hãy nói chuyện thay vì xoáy mãi trong đầu.',
  'Bạn đang căng thẳng và lo về công việc. Bạn hãy kiểm tra lại tình hình thật.',
  'Bạn đang lo về kỳ thi. Bạn hãy chuẩn bị, rồi đi ngủ.',
  'Bạn đang lo về tiền. Bạn hãy lập một kế hoạch và chia sẻ gánh nặng.',
  'Bạn hãy bật đèn lên, vì quái vật sẽ nhỏ lại.'],
'swords-10': ['chạm đáy|kết thúc|phản bội|điều tệ nhất đã qua', 'hồi phục|chống lại cái kết|làm quá|sống sót',
  'Một cái kết đau đã đến hẳn, và nó đã xong. Chính vì đã xong, bình minh đang đến.',
  'Bạn đang trải qua một cái kết đau và dứt khoát. Bạn hãy buồn rồi lành lại, vì điều tệ nhất đã qua.',
  'Một dự án hay công việc của bạn vừa kết thúc tệ. Bạn hãy hồi phục và bắt đầu lại.',
  'Bạn vừa thất bại một lần. Bài học đã được học, nên bạn hãy đi tiếp.',
  'Tài chính của bạn đang ở đáy, và từ đây chỉ có đi lên.',
  'Chuyện đã xong rồi, và bây giờ bạn đứng dậy được.'],
'swords-c0': ['tò mò|cảnh giác|ý tưởng mới|giao tiếp', 'đàm tiếu|lời vội|nghĩ tản mạn|dò xét',
  'Năng lượng của bạn đang tỉnh táo, tò mò và hay nói. Ý tưởng và tin nhắn mới đang đến, nhưng bạn hãy coi chừng lời nói của mình.',
  'Bạn đang nhận những tin nhắn tò mò và tranh luận vui. Nhưng nếu có đàm tiếu, bạn hãy cẩn thận.',
  'Bạn đang có ý tưởng mới, giao tiếp nhiều và giữ cảnh giác.',
  'Đầu óc tò mò của bạn đang giúp bạn tìm hiểu và đặt câu hỏi.',
  'Bạn hãy coi chừng lời đồn và những quyết định vội vàng về tiền.',
  'Bạn hãy hỏi câu hỏi, rồi lắng nghe.'],
'swords-c1': ['tham vọng|hành động|thẳng|nhanh', 'hung hăng|thiếu kiên nhẫn|liều|tàn nhẫn',
  'Năng lượng của bạn đang nhanh, sắc và quyết đoán, và bạn đang lao vào. Bạn hãy chắc rằng mình đang chĩa đúng hướng.',
  'Bạn đang gặp một người thẳng và nhanh, hoặc đang đứng trước một quyết định vội. Bạn hãy chậm lại một chút.',
  'Bạn đang quyết định nhanh và hành động táo bạo. Bạn hãy coi chừng sự vội vàng.',
  'Bạn đang trong một đợt học dồn rất mạnh. Cách này hiệu quả nhưng mệt.',
  'Bạn đang đi những nước cờ tiền nhanh. Bạn hãy đánh giá rủi ro.',
  'Bạn cứ lao lên, nhưng hãy xem bản đồ trước.'],
'swords-c2': ['độc lập|phán đoán rõ|thật thà|ranh giới', 'lạnh|cay đắng|cô lập|phê bình gắt',
  'Bạn đang có đôi mắt sáng, sự thật thà và tính độc lập, và bạn nhìn xuyên qua những điều vô nghĩa. Bạn hãy thêm chút ấm áp vào sự thật.',
  'Bạn đang cần sự độc lập, sự thật thà và những ranh giới rõ ràng.',
  'Bạn đang phán đoán rõ và giao tiếp thẳng thắn. Bạn hãy dẫn dắt bằng sự chính trực.',
  'Bạn đang học theo cách phân tích và có kỷ luật.',
  'Bạn đang đưa ra những quyết định tiền bạc rõ ràng và không cảm tính.',
  'Bạn hãy nói sự thật với lòng tử tế.'],
'swords-c3': ['quyền hạn|trí tuệ|sự thật|kỷ luật', 'thao túng|độc tài|lạnh|lạm quyền',
  'Bạn đang mang quyền hạn của trí tuệ: luật rõ ràng, phán xét công bằng và sức mạnh của đầu óc. Bạn hãy dùng nó cho sự công bằng.',
  'Bạn đang ở bên một người bạn đời lý trí và có nguyên tắc, và cam kết của hai bạn rất rõ ràng.',
  'Bạn đang dẫn dắt bằng chuyên môn và sự công bằng.',
  'Bạn đang làm chủ môn học bằng kỷ luật và logic.',
  'Bạn đang lập kế hoạch tài chính một cách lý trí và có cấu trúc.',
  'Bạn hãy cai trị bằng lý lẽ và sự công bằng.'],

'pentacles-1': ['cơ hội|thịnh vượng|dự án mới|thành hình', 'bỏ lỡ|thiếu thốn|kế hoạch kém|tham',
  'Một cơ hội cụ thể đang được đưa đến tay bạn: tiền mới, việc mới, một thứ có thật. Bạn hãy nhận lấy nó.',
  'Bạn đang bước vào một mối quan hệ mới ổn định và có triển vọng. Nó thật, chứ không chỉ hấp dẫn.',
  'Bạn đang nhận một công việc, hợp đồng hoặc dự án mới, vững và có triển vọng.',
  'Bạn đang có một cơ hội thực tế mới: một học bổng, một khóa học hay một vị trí.',
  'Bạn đang có thu nhập mới hoặc một cơ hội tài chính. Bạn hãy nắm lấy nó.',
  'Bạn hãy nhận đồng xu, vì nó là thật.'],
'pentacles-2': ['cân bằng|thích nghi|tung hứng|linh hoạt', 'quá tải|lộn xộn|căng tiền|rơi bóng',
  'Bạn đang tung hứng nhiều việc và vẫn giữ được chúng trên không. Bạn hãy giữ sự linh hoạt, vì hiện tại cách này vẫn ổn.',
  'Bạn đang cân bằng tình yêu với những đòi hỏi khác. Bạn hãy chủ động dành thời gian cho nhau.',
  'Bạn đang làm nhiều dự án cùng lúc. Bạn hãy sắp ưu tiên và giữ sự linh hoạt.',
  'Bạn đang cân bằng giữa học và đời sống. Bạn hãy lên lịch cho cả tuần.',
  'Bạn đang xoay dòng tiền. Bạn hãy lập ngân sách cẩn thận.',
  'Bạn hãy giữ các quả bóng trên không, nhưng đừng giữ mãi mãi.'],
'pentacles-3': ['làm nhóm|tay nghề|học nghề|chất lượng', 'thiếu phối hợp|chất lượng kém|không được ghi nhận|làm một mình',
  'Tay nghề của bạn đang được công nhận và được xây thêm. Sự hợp tác và sự khéo léo đang được đền đáp.',
  'Hai bạn đang cùng nhau xây mối quan hệ, từng bước một.',
  'Bạn đang hợp tác tốt, tay nghề được công nhận, và làm ra công việc chất lượng. Đây là thời điểm tốt cho dự án nhóm.',
  'Bạn đang học từ người khác, và kỹ năng của bạn đang lên nhờ luyện tập.',
  'Tiền đang đến từ tay nghề và sự hợp tác của bạn.',
  'Bạn hãy làm cho thật tốt, cùng với người khác.'],
'pentacles-4': ['an toàn|kiểm soát|tiết kiệm|ổn định', 'tham|tích trữ|sợ mất|chiếm hữu',
  'Bạn đang giữ chặt những gì mình có. Sự an toàn là quan trọng, nhưng nếu nắm quá chặt, dòng chảy sẽ ngừng lại.',
  'Bạn đang chiếm hữu hoặc sợ mất ai đó. Bạn hãy nới tay ra một chút.',
  'Bạn đang giữ sự an toàn và kiểm soát trong công việc. Bạn đừng chống lại mọi thay đổi.',
  'Bạn đang học theo cách chắc chắn và an toàn. Bạn đừng sợ phương pháp mới.',
  'Bạn đang tiết kiệm và giữ an toàn. Bạn hãy cân bằng điều đó với sự hào phóng.',
  'Bạn hãy giữ điều quan trọng, và nới lỏng phần còn lại.'],
'pentacles-5': ['khó khăn|lo|bị bỏ ngoài|bền bỉ', 'cô lập|tâm lý thiếu thốn|từ chối giúp đỡ|tuyệt vọng',
  'Bạn đang ở trong một đoạn khó và thấy mình bị bỏ ngoài trời lạnh. Nhưng sự giúp đỡ gần hơn bạn tưởng, nên bạn hãy hỏi.',
  'Bạn đang thấy cô đơn hoặc không được nâng đỡ. Bạn hãy tìm đến người khác thay vì chịu đựng trong im lặng.',
  'Bạn đang gặp bất ổn trong công việc hoặc căng thẳng tài chính. Bạn hãy tìm sự hỗ trợ.',
  'Bạn đang vật lộn vì thiếu nguồn lực. Bạn hãy nhờ người giúp.',
  'Bạn đang gặp khó khăn tài chính. Bạn hãy tìm sự hỗ trợ, vì chuyện này rồi sẽ qua.',
  'Cánh cửa đang ở ngay đó, nên bạn hãy gõ.'],
'pentacles-6': ['hào phóng|cho đi|cân bằng|chia sẻ', 'điều kiện kèm|nợ|bất bình đẳng|lệch quyền lực',
  'Sự cho và nhận quanh bạn đang cân bằng. Lòng hào phóng đang chảy, và sự công bằng cũng vậy.',
  'Mối quan hệ của bạn đang có sự hào phóng và nâng đỡ. Bạn hãy kiểm tra cán cân giữa cho và nhận.',
  'Bạn đang được trả công xứng đáng, được hướng dẫn và được hỗ trợ. Bạn hãy vừa cho vừa nhận.',
  'Bạn đang được thầy cô hoặc bạn bè giúp đỡ. Bạn hãy chia sẻ lại điều mình biết.',
  'Tiền đang đến qua sự hào phóng, hoặc bạn đang có cơ hội để cho đi.',
  'Bạn hãy cho điều mình cho được, và nhận điều mình cần.'],
'pentacles-7': ['kiên nhẫn|đánh giá|nhìn dài|bền bỉ', 'nóng vội|chưa có quả|bực bội|đầu tư kém',
  'Bạn đã làm việc và bây giờ bạn chờ. Bạn hãy đánh giá sự lớn lên, nhưng đừng đào hạt lên xem.',
  'Bạn đang đánh giá lại mối quan hệ, và tự hỏi khoản đầu tư này có đang sinh lời không.',
  'Bạn đang trong một nỗ lực dài hạn. Kết quả đến chậm nhưng chắc chắn đang đến, nên bạn hãy đánh giá bình tĩnh.',
  'Bạn đang tiến chậm. Bạn cứ tiếp tục chăm sóc việc học của mình.',
  'Bạn đang đầu tư dài hạn, và việc này cần sự kiên nhẫn.',
  'Bạn hãy để nó lớn từ từ.'],
'pentacles-8': ['tay nghề|chăm chỉ|rèn kỹ năng|tận tâm', 'cầu toàn|đơn điệu|thiếu tham vọng|làm ẩu',
  'Bạn đang làm việc tập trung và kiên nhẫn. Kỹ năng được xây từng lần lặp một, và bạn đang giỏi lên.',
  'Bạn đang vun đắp mối quan hệ bằng sự chăm chút và đều đặn.',
  'Bạn đang tận tâm với nghề và trở nên thành thạo nhờ luyện tập.',
  'Bạn đang luyện đều và lặp lại, và đây chính là cách kiến thức ngấm vào.',
  'Tiền đang đến từ tay nghề và công việc đều đặn của bạn.',
  'Bạn hãy làm đủ số lần.'],
'pentacles-9': ['độc lập|tự đủ|sung túc|giá trị bản thân', 'làm quá|lệ thuộc|cô lập|hời hợt',
  'Bạn đang tận hưởng sự dễ chịu mà chính mình tạo ra: độc lập, và thấy vui vì điều đó. Bạn xứng đáng với nó.',
  'Bạn đang tự đủ trong tình yêu, và hạnh phúc dù một mình hay có đôi.',
  'Bạn đang thành công và độc lập. Bạn hãy hưởng thành quả công việc của mình.',
  'Bạn đang tự học và tự định hướng, với niềm tin vào khả năng của mình.',
  'Bạn đang độc lập và dễ chịu về tài chính.',
  'Bạn hãy tận hưởng điều mình đã xây.'],
'pentacles-10': ['di sản|của cải|gia đình|an toàn lâu dài', 'gia đình xung đột|mất tiền|bất ổn|nghĩ ngắn',
  'Bạn đang có của cải bền: gia đình, di sản, và những cấu trúc sẽ sống lâu hơn bạn. Bạn hãy nghĩ theo thế hệ.',
  'Bạn đang trong một mối quan hệ bền, với sự gắn bó gia đình và một tương lai chung.',
  'Bạn đang có thành công lâu dài, một sự nghiệp ổn định và một đóng góp bền vững.',
  'Việc học của bạn là một khoản đầu tư dài hạn, và gia đình đang ủng hộ.',
  'Bạn đang có của cải, thừa kế và sự an toàn lâu dài.',
  'Bạn hãy xây cho đường dài.'],
'pentacles-c0': ['tham vọng|học hỏi|khởi đầu thực tế|thành hình', 'trì hoãn|không tiến|mơ mộng|không theo tới cùng',
  'Bạn đang có một khởi đầu thực tế: một khóa học, một kế hoạch, một bước đầu được coi trọng. Bạn hãy học nó cho đàng hoàng.',
  'Bạn đang có một kết nối mới thực tế và có gốc. Nó chậm nhưng thật.',
  'Bạn đang nhận một công việc mới, một đợt đào tạo, hoặc một cơ hội thực tế.',
  'Bạn đang bắt đầu một khóa học mới với thái độ nghiêm túc.',
  'Bạn đang đặt một mục tiêu tài chính mới. Bạn hãy bắt đầu để dành.',
  'Bạn hãy bắt đầu, và học cho đàng hoàng.'],
'pentacles-c1': ['đáng tin|nếp|chăm|trách nhiệm', 'chán|ứ đọng|cứng đầu|cầu toàn',
  'Bạn đang chậm, đáng tin và có phương pháp. Cách này không hào hứng, nhưng việc gì bạn làm cũng xong, và đó chính là món quà của nó.',
  'Bạn đang ở bên một người bạn đời đáng tin và đều đặn, với một tình yêu cháy chậm mà bền.',
  'Bạn đang làm việc có phương pháp, và sự đáng tin của bạn đang thắng.',
  'Bạn đang giữ nếp học đều, chậm mà chắc.',
  'Bạn đang chọn những lựa chọn tiền bạc an toàn và thận trọng.',
  'Bạn hãy đi tiếp, đều đặn.'],
'pentacles-c2': ['chăm sóc|thực tế|sung túc|an toàn', 'làm quá sức|bỏ bê mình|bao bọc|vật chất',
  'Bạn đang chăm sóc mọi người một cách thực tế và làm cho họ an toàn về vật chất. Bạn hãy nhớ chăm cả chính mình.',
  'Bạn đang có một người bạn đời biết chăm lo và thực tế, với nhà cửa và sự dễ chịu.',
  'Bạn đang quản lý thực tế và lo cho cả nhóm.',
  'Bạn đang học có tổ chức và chắc chân.',
  'Bạn đang quản lý tiền một cách thực tế và hào phóng.',
  'Bạn hãy chăm mình như chăm mọi người.'],
'pentacles-c3': ['của cải|dẫn dắt|an toàn|kỷ luật', 'tham|vật chất|cứng đầu|kiểm soát bằng tiền',
  'Bạn đang làm chủ thế giới vật chất, với sự ổn định và khả năng chu cấp mà người khác dựa vào được.',
  'Bạn đang ở bên một người chu cấp ổn định và hào phóng, và tình yêu của hai bạn có sự an toàn.',
  'Bạn đang thành công trong kinh doanh và dẫn dắt bằng sự đáng tin.',
  'Bạn đang làm chủ một môn thực hành bằng kỷ luật.',
  'Bạn đang có của cải và làm chủ tài chính của mình.',
  'Bạn hãy xây của cải, và giữ lòng hào phóng.']
});
Object.assign(INSIGHT.en, {
'wands-1': ['spark|inspiration|new energy|desire', 'false start|no direction|delay|burnout',
  'A surge of wanting to make something is rising in you. This energy is still raw and not yet aimed, so give it a direction.',
  'A new attraction or a new passion has just sparked. Enjoy it, but remember that a spark is not yet a promise.',
  'A new idea or offer is arriving, and there is real energy behind it. Start now.',
  'You are excited about a new subject. Use that excitement before it cools.',
  'You have a new idea for making money. Test it small first.',
  'Light the fire first, and build the hearth afterwards.'],
'wands-2': ['planning|vision|choice|bold horizons', 'playing it safe|fear of the unknown|plans that never launch',
  'You are holding something in your hands and looking beyond it. It is time to choose the wider horizon over the familiar one.',
  'You are deciding what you want from love, or choosing between comfort and a bolder option.',
  'You are planning an expansion, a partnership, or the next step. Think big, then commit to one direction.',
  'You are choosing a direction or a specialisation. Plan the year, not just the week.',
  'You are planning an investment. Balance safety against growth.',
  'Decide the direction first; the details can come later.'],
'wands-3': ['expansion|foresight|progress|waiting well', 'delay|impatience|thinking too small|no follow-through',
  'Your first efforts are out in the world and already working. Now you wait, and prepare for what comes back.',
  'What you set in motion is developing. Give it time, and do not rule out a connection from far away.',
  'Your work is growing and opening new markets thanks to earlier effort. Keep your eyes on the horizon.',
  'Your groundwork is done, and the results are on their way.',
  'Your earlier investment is starting to return. Patience is paying off.',
  'Watch the horizon, not the clock.'],
'wands-4': ['celebration|home|stability|community', 'instability|tension at home|cancelled plans|feeling unwelcome',
  'You have reached a milestone, a homecoming, or a reason to gather. This is joy with a solid floor under it.',
  'This may be a commitment, moving in together, or a celebration with the people you love.',
  'Your team has hit a milestone, or you are in a stable and supportive workplace. Celebrate it.',
  'You have reached a milestone. A study group or a supportive setting is carrying you forward.',
  'Your finances are stable, and a purchase for the home makes sense right now.',
  'Mark the milestone, and then let yourself rest.'],
'wands-5': ['competition|debate|energy|testing', 'conflict|chaos|arguing for nothing|avoiding the fight',
  'Many energies are clashing around you: opinions, egos, plans. It is not dangerous, only noisy, so compete fairly.',
  'You are bickering, competing, or facing too many differences at once. Argue about what really matters.',
  'You are in a competitive environment with clashing views, and it is hard to be heard. Stay in the game.',
  'Your study environment is competitive, or your focus is split. Pick one battle.',
  'Several needs are competing for the same money. Sort out your priorities.',
  'Pick the fight worth having and let the rest go.'],
'wands-6': ['victory|recognition|confidence|progress', 'ego|fall from grace|no recognition|hollow win',
  'A win of yours is being noticed. You are ahead and people can see it, so enjoy the recognition.',
  'You are being admired, and you are in a relationship you feel proud of.',
  'A promotion, praise, or public success is coming. Accept it graciously.',
  'You are getting good results and recognition. Your confidence is well founded.',
  'A reward or a financial win is on its way.',
  'Take the applause, and then keep riding forward.'],
'wands-7': ['defence|perseverance|courage|standing your ground', 'giving up|exhaustion|feeling overwhelmed|defensiveness',
  'You are holding a position against pressure from several sides. It is tiring, but you have the high ground.',
  'You are defending your relationship or your own needs. Stand firm without going to war.',
  'Your position is being competed for or challenged. Hold your ground with skill.',
  'You are under pressure and being tested. Keep going, because you are stronger than the doubt.',
  'Protect what you have from outside demands, and learn to say no.',
  'Hold the line, but remember to breathe while you do it.'],
'wands-8': ['speed|news|movement|momentum', 'delays|chaos|rushed decisions|miscommunication',
  'Everything is moving fast: messages, travel, sudden progress. Keep up, and keep your head clear.',
  'Things are developing quickly, with messages flying back and forth. Reply while it matters.',
  'Work is moving fast, news is arriving, and travel is possible. Act quickly on offers.',
  'You are making fast progress, and the deadline is approaching just as fast. Do it now.',
  'Money is moving quickly, both opportunities and expenses. Keep an eye on both.',
  'Act fast, but keep your head cool.'],
'wands-9': ['resilience|persistence|caution|last push', 'paranoia|exhaustion|refusing help|defensiveness',
  'You are tired, but you are almost there. Guard what you have built and take the last step.',
  'You are wary because of an old hurt. Protect yourself, but do not wall everyone out.',
  'You are nearly through a hard stretch. Persist a little longer and set clear boundaries.',
  'This is the final push before the exam or the deadline. Keep your routine.',
  'Protect your savings and be cautious with new commitments.',
  'Take one more step, and then rest properly.'],
'wands-10': ['responsibility|burden|hard work|determination', 'overload|burnout|carrying others|no delegation',
  'You are carrying a great deal, perhaps too much. The load is real, but so is your strength, and one thing can be put down.',
  'You are taking on all the emotional work in the relationship. Share the weight.',
  'You are overworked with too many duties. Delegate something or drop it.',
  'Your schedule is overloaded. Cut it down to what matters.',
  'You are carrying heavy financial obligations. Simplify them.',
  'Put one thing down today.'],
'wands-c0': ['enthusiasm|exploration|messages|a fresh idea', 'lack of direction|impatience|immaturity|delays',
  'You are curious, eager, and a little restless. A new idea or message is arriving, so explore it.',
  'Someone is flirting with you, a fresh message is coming, or a young-at-heart person is around. It is fun, but not yet serious.',
  'You have a new idea, a trainee role, or an exciting message about work.',
  'You are curious and eager. Explore new topics.',
  'You have a new idea about money. Research it before you invest.',
  'Follow the spark and see where it leads.'],
'wands-c1': ['action|passion|adventure|charisma', 'recklessness|impulsiveness|arrogance|leaving too soon',
  'You are bold, fast, charming, and impatient. You are ready to charge, but take aim before you go.',
  'You are meeting a passionate person, or living through a passionate phase yourself. It is exciting, though not always reliable.',
  'You are taking bold action, travelling, and taking charge. Watch the impulsiveness.',
  'Your energy comes in bursts. Channel them into a plan.',
  'You are considering a bold financial move. It is risky, so check the details.',
  'Charge ahead, but know where the cliff is.'],
'wands-c2': ['warmth|confidence|independence|magnetism', 'jealousy|demanding|drama|burnout',
  'Your energy is warm, confident, and magnetic. You are attracting attention, so use it well.',
  'You have a confident, warm partner, or your own attractive self-assurance is shining.',
  'You are leading with warmth and inspiring the team.',
  'You are learning confidently and steering your own study.',
  'You are managing money with confidence and independence.',
  'Shine, and let others shine too.'],
'wands-c3': ['vision|leadership|boldness|entrepreneurship', 'tyranny|impatience|high expectations|ruthlessness',
  'You carry big-picture, bold leadership energy, and you are setting the direction. Lead by inspiring rather than by ordering.',
  'You are with a charismatic, driven partner, or you are the one leading in love.',
  'You are leading the venture with vision plus action.',
  'Take charge of your own learning path.',
  'You are handling money like an entrepreneur: bold, but calculated.',
  'Lead from the front, with heart.'],

'cups-1': ['new love|emotional beginning|compassion|creativity', 'emptiness|blocked feelings|self-love missing|emotional overflow',
  'Your heart is opening to a new feeling, a new compassion, or a creative beginning. Receive it.',
  'A new love is arriving, or an old feeling is being renewed. You are more open than ever.',
  'You are finding emotional fulfilment at work, with a creative start and good relationships.',
  'You are finding joy in learning, and a creative subject is calling you.',
  'Money is coming from something you love, and generosity is flowing around you.',
  'Let the cup fill.'],
'cups-2': ['partnership|mutual attraction|connection|balance', 'imbalance|break-up|miscommunication|one-sided',
  'You have a real connection with another person or another side. Respect and attraction are coming from both directions.',
  'You are in a strong mutual bond, or you have just had a meaningful meeting.',
  'You are in a good business partnership or a strong working relationship.',
  'You have found a study partner or a mentor who suits you.',
  'You are in a fair financial partnership.',
  'Meet the other person halfway, and it will work.'],
'cups-3': ['friendship|celebration|community|creativity', 'gossip|overindulgence|a third person|isolation',
  'The energy around you is joyful and social, full of friends, gatherings and shared happiness.',
  'You are celebrating with friends. But if there is a third person in the picture, take a closer look.',
  'You are working well as a team, celebrating results, or starting a creative collaboration.',
  'Group study is working well for you. Celebrate the small wins.',
  'You are spending on your social life. Enjoy it in moderation.',
  'Call your friends.'],
'cups-4': ['contemplation|apathy|re-evaluation|boredom', 'missed opportunity|withdrawal|ingratitude|numbness',
  'You feel flat, unimpressed, and unsure. An offer is right there that you have not seen yet, so look up.',
  'You feel bored or emotionally distant, and something good is being ignored.',
  'You are dissatisfied and may have missed a chance. Re-evaluate what you really want.',
  'You have lost motivation. Change your approach.',
  'You may have missed a financial opportunity. Pay closer attention.',
  'Look at what is being offered before you refuse it.'],
'cups-5': ['grief|regret|loss|acceptance', 'refusing to move on|self-pity|dwelling|isolation',
  'You are grieving what was lost, and the sadness is real. But not everything has spilled, because two cups are still standing.',
  'You are disappointed or have just lost something in love. Let yourself grieve, and then turn around.',
  'You have hit a setback or a disappointment. Learn from it and move on.',
  'You received a poor result, but this is not the end. Turn to what remains.',
  'You have lost some money. Assess what is left.',
  'Turn around, because two cups are still full.'],
'cups-6': ['nostalgia|innocence|kindness|the past', 'stuck in the past|naivety|unrealistic memories|clinging',
  'Sweet memories, kindness, and something innocent are returning. The past is visiting you gently.',
  'An old flame, a childhood sweetness, or a simple affection is showing up.',
  'An old contact is returning, or you are receiving kindness at work.',
  'Revisit the basics, because old knowledge is helping you.',
  'A gift, or money from the past, is coming.',
  'Enjoy the memory, but live in the present.'],
'cups-7': ['choices|imagination|dreams|possibilities', 'illusion|wishful thinking|too many options|escapism',
  'You have many options and many fantasies, but not all of them are real. Choose with clear eyes.',
  'You are mixing fantasy and reality in love, perhaps idealising someone. See them clearly.',
  'You have too many possibilities in front of you. Focus on one realistic path.',
  'You are distracted and daydreaming. Pick one thing and do it.',
  'You are fantasising about money. Sit down and do the maths.',
  'Choose one cup, with your eyes open.'],
'cups-8': ['walking away|seeking more|letting go|a deeper search', 'fear of change|aimlessness|running away|staying too long',
  'You are leaving something behind to find something deeper. It is a loss and a liberation at the same time.',
  'You are walking away from what no longer fulfils you. It is hard, and it is right.',
  'You are leaving a job or a role for something more meaningful.',
  'You are changing direction. Leave behind what does not fit.',
  'You are leaving a financial situation that drains you.',
  'Go, because what you seek is not here.'],
'cups-9': ['satisfaction|contentment|wishes granted|pleasure', 'smugness|overindulgence|shallow happiness|dissatisfaction',
  'Your wish is coming true, with comfort and pleasure alongside it. You have what you asked for, so enjoy it.',
  'You feel emotionally satisfied and are finding joy in love.',
  'You are achieving things and feeling satisfied at work.',
  'You are succeeding and feel satisfied with your results.',
  'Your finances are comfortable. Treat yourself, wisely.',
  'Enjoy it, because you asked and it came.'],
'cups-10': ['harmony|family|lasting happiness|belonging', 'broken family|disharmony|unrealistic expectations|neglect',
  'You have a deep, shared, lasting happiness, with family, home and emotional fulfilment.',
  'You are in a loving, committed relationship, and the family is in harmony.',
  'Your work is fulfilling, and your relationships with colleagues are good.',
  'Your family is supporting your studies.',
  'Your family has financial security.',
  'This is the good thing, so hold it gently.'],
'cups-c0': ['creativity|intuition|a message of feeling|sensitivity', 'emotional immaturity|moodiness|creative block|escapism',
  'A gentle, imaginative message or impulse is reaching you. Something new is stirring quietly in your heart.',
  'You are receiving a sweet message, developing a crush, or standing at a tender beginning.',
  'You have a creative idea or are receiving an emotional message at work.',
  'You are learning intuitively, and art or creativity suits you.',
  'A small, unexpected gift is coming.',
  'Listen to the small feeling.'],
'cups-c1': ['romance|charm|following the heart|idealism', 'moodiness|unrealistic|jealousy|deception',
  'Your energy is romantic, charming and idealistic, and you are following your heart. Check that your feet are still on the ground.',
  'You are receiving a romantic proposal or meeting a charming suitor. Enjoy it, but watch for illusions.',
  'You are working on creative projects and approaching things diplomatically.',
  'You are studying with inspiration, especially art, music and literature.',
  'You are spending emotionally. Pause for a moment before you buy.',
  'Follow your heart with open eyes.'],
'cups-c2': ['compassion|calm|intuition|emotional security', 'insecurity|co-dependence|martyrdom|overwhelmed',
  'Your energy is calm, caring and intuitive. You understand others and yourself, but remember to care for yourself too.',
  'You have a nurturing, loving partner, or your own emotional maturity is leading the way.',
  'Empathy and intuition are guiding your work, and you are supporting your colleagues well.',
  'You are learning through understanding rather than memorising.',
  'You are making intuitive money choices and looking after your security.',
  'Care for others, but keep some care for yourself.'],
'cups-c3': ['emotional balance|diplomacy|wisdom|compassion', 'emotional manipulation|moodiness|volatility|coldness',
  'You are in mature control of your feelings. They are strong, but they are held with wisdom.',
  'You are with a mature, emotionally balanced partner, and there is compassion in your love.',
  'You are leading with diplomacy and calm, and handling people with care.',
  'You are approaching your studies in a balanced, wise way.',
  'You are managing money in a balanced, wise way.',
  'Feel deeply, but act calmly.'],

'swords-1': ['clarity|truth|breakthrough|a new idea', 'confusion|misuse of power|harsh words|clouded judgement',
  'Your mind is having a moment of clarity, when the truth cuts through everything. You have new ideas and decisive thinking.',
  'You are having honest conversations and seeing clearly what you want.',
  'You have had a breakthrough idea and are making clear decisions.',
  'Your thinking is sharp and you have just understood something new.',
  'You are thinking clearly about money and have a decisive plan.',
  'Say the true thing, kindly.'],
'swords-2': ['indecision|stalemate|weighing options|truce', 'avoidance|denial|paralysis|hiding',
  'You are stuck between two options and avoiding the choice. The blindfold is yours, and you can take it off.',
  'You are avoiding a decision about the relationship. Face it.',
  'You are in a stalemate or dodging a decision. Gather the facts, then choose.',
  'You are torn between choices. Pick one and go.',
  'A financial decision is on hold. Decide.',
  'Take off the blindfold and choose.'],
'swords-3': ['heartbreak|grief|painful truth|release', 'holding on to pain|bitterness|self-inflicted hurt|refusing to heal',
  'You are feeling a sharp pain, usually from a truth or a loss. It hurts, but it also clarifies, so let it out.',
  'You are heartbroken, betrayed, or facing a painful truth. Feel it, and then heal.',
  'You have hit a painful setback or harsh criticism. Learn from it and recover.',
  'You are disappointed. It hurts, but it is temporary.',
  'You have taken a painful financial loss. Recover and rebuild.',
  'Let the tears come, and then the healing.'],
'swords-4': ['rest|recovery|contemplation|retreat', 'burnout|restlessness|isolation|avoiding action',
  'You need rest. This is a time to retreat, recover and think, not a time to fight.',
  'Your relationship is in a pause. Recover your energy.',
  'Take a break and recover before the next challenge.',
  'Rest before you study more, because your mind needs it.',
  'Pause all money matters and review them quietly.',
  'Rest. Really rest.'],
'swords-5': ['conflict|defeat|winning at a cost|tension', 'hostility|bullying|no-win situation|humiliation',
  'You are in a conflict where nobody really wins. Ask yourself whether this battle is worth it.',
  'You are arguing with hurtful words. Winning the argument may cost you the relationship.',
  'You are facing conflict at work, or have just had a hollow victory. Choose your battles.',
  'Competitiveness is hurting you. Focus on your own path.',
  'You are in a financial dispute. Do not fight over the small thing.',
  'Walk away from the fight you cannot win, with grace.'],
'swords-6': ['transition|moving on|healing|calmer waters', 'stuck|unfinished baggage|resisting change|rough passage',
  'You are leaving rough water for calmer water. This is a quiet and necessary transition.',
  'You are moving on from difficulty and healing, possibly at a distance.',
  'You are moving to a better situation, and travel is possible.',
  'You are moving past a difficult phase and making progress.',
  'Your finances are recovering gradually.',
  'Row toward the calm, because it is right there.'],
'swords-7': ['strategy|cunning|independence|getting away with it', 'deception|theft|self-deception|getting caught',
  'You are using strategy, working quietly, and doing things alone. Sometimes that is clever and sometimes it is sneaky, so check your motives.',
  'There is secrecy or deception in the relationship. Honesty is safer.',
  'You are being strategic and independent, or someone is not being straight with you.',
  'You are taking shortcuts. Be careful they do not backfire.',
  'Watch out for scams, and be strategic with money.',
  'Be clever, but not sneaky.'],
'swords-8': ['feeling trapped|restriction|self-limiting beliefs|helplessness', 'victim mentality|paralysis|imprisonment|self-sabotage',
  'You feel trapped, but the bonds are looser than they look. The prison is mostly in your mind.',
  'You feel stuck in the relationship, but you have more choice than you think.',
  'You feel restricted at work. Look for the exit you have not seen yet.',
  'You feel overwhelmed. Break the task into small steps.',
  'Your money feels restricted. Look for other options.',
  'The ropes are loose, so move.'],
'swords-9': ['anxiety|worry|nightmares|guilt', 'despair|hopelessness|catastrophising|isolation',
  'Worry is keeping you up at night, but most of the fear is bigger than the facts. Reach out to someone.',
  'You are anxious about the relationship. Talk instead of spiralling.',
  'You are stressed and worried about work. Check the real situation.',
  'You are anxious about the exam. Prepare, then sleep.',
  'You are worried about money. Make a plan and share the burden.',
  'Turn on the light, and the monsters shrink.'],
'swords-10': ['rock bottom|ending|betrayal|the worst is over', 'recovery|resisting the end|dramatising|survival',
  'A painful ending has fully arrived, and it is done. Because it is done, the dawn is coming.',
  'You are going through a painful, final ending. Grieve and then heal, because the worst is over.',
  'A project or job of yours has ended badly. Recover and start fresh.',
  'You have failed once. The lesson is learned, so move on.',
  'Your finances are at a low point, and from here the only way is up.',
  'It is over, and now you can rise.'],
'swords-c0': ['curiosity|vigilance|new ideas|communication', 'gossip|hasty words|scattered thinking|spying',
  'Your energy is alert, curious and talkative. New ideas and messages are arriving, but watch your words.',
  'You are getting curious messages and playful debate. But if there is gossip, be careful.',
  'You have new ideas, plenty of communication, and a watchful eye.',
  'Your curious mind is helping you research and question.',
  'Watch out for rumours and hasty decisions about money.',
  'Ask the question, then listen.'],
'swords-c1': ['ambition|action|directness|speed', 'aggression|impatience|recklessness|ruthlessness',
  'Your energy is fast, sharp and decisive, and you are charging in. Make sure you are pointing the right way.',
  'You are meeting someone direct and fast, or facing a rushed decision. Slow down a little.',
  'You are making rapid decisions and bold moves. Watch out for haste.',
  'You are in an intense study push. It is effective but exhausting.',
  'You are making fast money moves. Assess the risk.',
  'Charge ahead, but check the map first.'],
'swords-c2': ['independence|clear judgement|honesty|boundaries', 'coldness|bitterness|isolation|harsh criticism',
  'You are clear-eyed, honest and independent, and you see through nonsense. Add some warmth to the truth.',
  'You need independence, honesty and clear boundaries right now.',
  'You are judging clearly and communicating directly. Lead with integrity.',
  'You are studying in an analytical, disciplined way.',
  'You are making clear, unsentimental money decisions.',
  'Tell the truth with kindness.'],
'swords-c3': ['authority|intellect|truth|discipline', 'manipulation|tyranny|coldness|abuse of power',
  'You carry the authority of the mind: clear rules, fair judgement and intellectual power. Use it justly.',
  'You are with a logical, principled partner, and your commitment is clear.',
  'You are leading through expertise and fairness.',
  'You are mastering the subject through discipline and logic.',
  'You are planning your finances rationally and with structure.',
  'Rule with reason and fairness.'],

'pentacles-1': ['opportunity|prosperity|new venture|manifestation', 'missed chance|scarcity|poor planning|greed',
  'A concrete opportunity is being handed to you: new money, a new venture, something real. Take it.',
  'You are entering a stable, promising new relationship. It is real, not just exciting.',
  'You are receiving a new job, contract or venture that is solid and promising.',
  'You have a new practical opportunity: a scholarship, a course, or a position.',
  'You have new income or a financial opportunity. Seize it.',
  'Take the coin, because it is real.'],
'pentacles-2': ['balance|adaptability|juggling|flexibility', 'overwhelm|disorganisation|financial stress|dropping the ball',
  'You are juggling several things and keeping them all in the air. Stay flexible, because for now it works.',
  'You are balancing love with other demands. Make time for each other on purpose.',
  'You are running several projects at once. Prioritise and stay adaptable.',
  'You are balancing study with the rest of life. Plan the week.',
  'You are juggling your cash flow. Budget carefully.',
  'Keep the balls in the air, but not forever.'],
'pentacles-3': ['teamwork|skill|learning|quality', 'lack of teamwork|poor quality|no recognition|working alone',
  'Your skill is being recognised and built upon. Collaboration and craftsmanship are paying off.',
  'You are building the relationship together, step by step.',
  'You are collaborating well, your skill is recognised, and your work is good quality. This is a good time for team projects.',
  'You are learning from others, and your skill is improving through practice.',
  'Money is coming from your skill and cooperation.',
  'Do the work well, with others.'],
'pentacles-4': ['security|control|saving|stability', 'greed|hoarding|fear of loss|possessiveness',
  'You are holding tightly to what you have. Security matters, but if you grip too hard the flow stops.',
  'You are being possessive or afraid of losing someone. Loosen your grip a little.',
  'You are holding on to job security and control. Do not resist every change.',
  'You are studying in a steady, safe way. Do not fear new methods.',
  'You are saving and staying secure. Balance that with generosity.',
  'Hold what matters, and loosen the rest.'],
'pentacles-5': ['hardship|worry|feeling left out|resilience', 'isolation|poverty mentality|refusing help|despair',
  'You are in a hard patch and feel left out in the cold. But help is nearer than it seems, so ask for it.',
  'You feel alone or unsupported. Reach out instead of suffering in silence.',
  'You are facing job insecurity or financial strain at work. Seek support.',
  'You are struggling for lack of resources. Ask for help.',
  'You are in financial hardship. Seek assistance, because this will pass.',
  'The door is right there, so knock.'],
'pentacles-6': ['generosity|charity|balance|sharing', 'strings attached|debt|inequality|power imbalance',
  'Giving and receiving are in balance around you. Generosity is flowing, and so is fairness.',
  'There is generosity and support in your relationship. Check the balance of give and take.',
  'You are being paid fairly, mentored and supported. Give and receive.',
  'You are being helped by teachers or peers. Share what you know in return.',
  'Money is coming through generosity, or you have a chance to give.',
  'Give what you can, and receive what you need.'],
'pentacles-7': ['patience|assessment|long-term view|perseverance', 'impatience|lack of reward|frustration|poor investment',
  'You have done the work and now you wait. Assess the growth, but do not dig up the seeds.',
  'You are assessing the relationship and asking whether the investment is paying off.',
  'You are in a long-term effort. Results are slow but coming, so evaluate calmly.',
  'You are progressing slowly. Keep tending your studies.',
  'You are investing for the long term, and that takes patience.',
  'Let it grow at its own pace.'],
'pentacles-8': ['craft|diligence|skill-building|dedication', 'perfectionism|monotony|lack of ambition|cutting corners',
  'You are working with focus and patience. Skill is built one repetition at a time, and you are getting good.',
  'You are tending the relationship with care and consistency.',
  'You are dedicated to your craft and gaining mastery through practice.',
  'You are practising steadily and repeatedly, and that is how it sticks.',
  'Money is coming from your skill and steady work.',
  'Do the repetitions.'],
'pentacles-9': ['independence|self-sufficiency|luxury|self-worth', 'over-work|dependence|isolation|superficiality',
  'You are enjoying a comfort you made yourself: independence, and the pleasure of it. You have earned this.',
  'You are self-sufficient in love, and happy whether alone or together.',
  'You are successful and independent. Enjoy the rewards of your work.',
  'You are directing your own learning with confidence in your abilities.',
  'You are financially independent and comfortable.',
  'Enjoy what you built.'],
'pentacles-10': ['legacy|wealth|family|long-term security', 'family conflict|financial loss|instability|short-term thinking',
  'You have lasting wealth: family, legacy, and structures that will outlast you. Think in generations.',
  'You are in a lasting relationship, with family ties and a shared future.',
  'You have long-term success, a stable career, and a lasting contribution.',
  'Your education is a long-term investment, and your family supports it.',
  'You have wealth, inheritance, and long-term security.',
  'Build for the long run.'],
'pentacles-c0': ['ambition|study|a practical start|manifestation', 'procrastination|lack of progress|daydreaming|no follow-through',
  'You are making a practical new beginning: a course, a plan, a first step taken seriously. Learn it properly.',
  'You are forming a practical, grounded new connection. It is slow, and it is real.',
  'You are receiving a new job, some training, or a practical opportunity.',
  'You are starting a new course with a serious attitude.',
  'You are setting a new financial goal. Start saving.',
  'Start, and learn it properly.'],
'pentacles-c1': ['reliability|routine|hard work|responsibility', 'boredom|stagnation|stubbornness|perfectionism',
  'You are slow, reliable and methodical. It is not exciting, but everything you do gets finished, and that is its gift.',
  'You have a reliable, steady partner, with a slow-burning, dependable love.',
  'You are working methodically, and your reliability is winning.',
  'You are keeping a consistent routine, slow and steady.',
  'You are making conservative, safe money choices.',
  'Keep going, steadily.'],
'pentacles-c2': ['nurturing|practicality|abundance|security', 'overwork|self-neglect|smothering|materialism',
  'You are caring for people in a practical way and making them materially safe. Remember to look after yourself too.',
  'You have a nurturing, practical partner, with home and comfort around you.',
  'You are managing practically and caring for the team.',
  'You are studying in a grounded, well-organised way.',
  'You are managing money practically and generously.',
  'Care for yourself as well as everyone else.'],
'pentacles-c3': ['wealth|leadership|security|discipline', 'greed|materialism|stubbornness|control through money',
  'You have mastery of the material world, with stability and provision that others can depend on.',
  'You are with a stable, generous provider, and there is security in your love.',
  'You are succeeding in business and leading through reliability.',
  'You are mastering a practical subject through discipline.',
  'You have wealth and mastery of your finances.',
  'Build wealth, and stay generous.']
});
