/* ============================ card insights, English ============================
   One entry per card, written for the "pick a card" reading and the card
   pages. Meanings follow the mainstream Rider–Waite–Smith reading tradition.
   Fields: [positive keywords, shadow keywords, energy now, love, work, study,
   money, advice]. Keywords are separated by "|". */
const INSIGHT = { en: {}, vi: {} };

Object.assign(INSIGHT.en, {
'major-0': ['new beginnings|openness|courage|a leap of faith', 'carelessness|naivety|no plan|running from responsibility',
  'You are standing at the edge of something new. There is more excitement than certainty, and that is fine. This energy asks you to trust the first step.',
  'Someone or something fresh is entering, or you are ready to love without the old fears. Enjoy it, but do not promise more than you know yet.',
  'A new project, role or direction you have never tried. You will learn on the job. Ask questions early and often.',
  'A fresh subject or a new way of studying. Curiosity carries you now; structure can come later.',
  'A new source of income or an impulse to spend on an adventure. Keep a small cushion before you leap.',
  'Take the step, but pack the bag: one plan, one safety net, then go.'],
'major-1': ['skill|focus|initiative|making it happen', 'showing off|manipulation|scattered talent|all talk',
  'You have every tool you need right now. The question is not "can I" but "will I". Your energy is sharp and active.',
  'You are attractive and persuasive at the moment. Use that honestly. Say what you want instead of playing games.',
  'Your abilities are visible to others. Pitch the idea, lead the meeting, start the thing. Results come from doing, not planning.',
  'Your mind is quick and concentration is available. Sit down and use it before the window closes.',
  'Good timing for turning a skill into money. Set a price, make the offer.',
  'Point everything you have at one goal for the next few days and watch it move.'],
'major-2': ['intuition|stillness|hidden knowledge|patience', 'secrets|withdrawal|ignoring your gut|passivity',
  'Something is not visible yet. Your instincts know more than the facts show. This is a time to listen, not to push.',
  'Feelings are running under the surface, yours or theirs. Do not force a confession. Watch what people do, not what they say.',
  'Information is being held back somewhere. Read between the lines before you commit to a decision.',
  'Quiet, solo study suits you now. Your understanding is deeper than your test results show yet.',
  'Wait before signing or spending. There is a detail you have not been told.',
  'Sit with the question for a day. The answer arrives when you stop demanding it.'],
'major-3': ['abundance|nurture|comfort|creativity', 'overindulgence|smothering|creative block|neglecting yourself',
  'Things are growing around you and mostly need feeding, not fixing. Pleasure and comfort are allowed. Something you care for is ripening.',
  'Warm, generous, sensual energy. A relationship deepens, or care is flowing toward you. Receive it.',
  'A project bears fruit. Creative work is favoured. Work with people rather than against them.',
  'Learning goes well when you are comfortable and rested. Make the space pleasant and the study follows.',
  'Money is flowing in more easily than usual. Enjoy some of it, save some, and share a little.',
  'Look after your body and your surroundings this week. Growth follows care.'],
'major-4': ['structure|stability|leadership|boundaries', 'rigidity|control|coldness|no structure at all',
  'This is an energy of order and authority. You are being asked to set rules, take charge, or respect someone who does.',
  'Stability matters more than romance right now. Someone dependable, or a need to set clear boundaries.',
  'Take the lead or work within the system. Plans, hierarchy and discipline win over improvisation.',
  'A timetable and a routine will do more for you than inspiration. Build the structure first.',
  'Budget, control, long-term planning. Money responds to discipline now.',
  'Decide, then hold the line. Just make sure the line is fair.'],
'major-5': ['tradition|guidance|learning|belonging', 'dogma|conformity|judging others|rebellion for its own sake',
  'Established ways are supporting you: a teacher, a family custom, an institution. There is comfort in doing it the known way.',
  'Commitment, family approval, or a relationship with clear shared values. Talk about what you both believe.',
  'Follow the proper process. A mentor or a formal qualification helps. Do not skip steps.',
  'Learn from a good teacher and the standard material. This is not the week to reinvent the method.',
  'Traditional, safe choices with money. Advice from someone experienced pays off.',
  'Ask someone who has done it before. Their map saves you months.'],
'major-6': ['connection|choice|values|harmony', 'misalignment|avoiding a decision|temptation|one-sided love',
  'A real meeting of two things, or a choice that shows what you truly value. This energy is about alignment, not just attraction.',
  'A strong bond, a meaningful choice about a partner, or a moment where you must decide what you want from love.',
  'Partnership and teamwork are favoured. A decision between two paths: choose the one that fits your values.',
  'Study with a partner or a group. If choosing between subjects, pick the one you actually care about.',
  'A financial decision that reflects your priorities. Do not choose purely on numbers.',
  'Choose with your values, not your fears.'],
'major-7': ['drive|willpower|victory|direction', 'aggression|losing control|scattered effort|running over people',
  'You are in motion and gaining ground. Opposing forces are being held together by your will. Keep steering.',
  'Pursue what you want, but keep control of your emotions. A relationship moves forward through effort.',
  'Ambition and momentum. Push through the obstacle; you have what it takes. Travel is possible.',
  'Discipline is your superpower this week. Set the target and drive toward it.',
  'Money comes through determination. A goal you have been chasing is within reach.',
  'Keep both hands on the reins: confidence and control together.'],
'major-8': ['inner strength|patience|compassion|courage', 'self-doubt|forcing it|raw emotion|weakness felt as shame',
  'Your power right now is quiet. Patience and kindness handle what force cannot. The lion is tamed by calm, not by shouting.',
  'Gentle strength wins. Deal with tension patiently instead of reacting. Someone needs your calm.',
  'Handle a difficult person or situation with composure. Your steadiness is noticed.',
  'Persistence beats brilliance today. Keep at it calmly.',
  'Steady management of money rather than bold moves. Resist a fear-driven decision.',
  'Breathe, then act. The calm version of you is the strong one.'],
'major-9': ['reflection|wisdom|solitude|seeking', 'isolation|loneliness|withdrawal too long|refusing help',
  'A time to step back and think. The answer you need is inside, not in more opinions. Solitude is useful now.',
  'You or your partner need space to think. Alone time is not rejection. A deeper connection comes after reflection.',
  'Reflect before the next move. A mentor or your own experience lights the way. Avoid noisy decisions.',
  'Deep, focused, solitary study. Turn off the notifications.',
  'Review your finances quietly and honestly. Seek expert advice if you need it.',
  'Give yourself an evening alone with the question. Then come back to people.'],
'major-10': ['change|luck|cycles|turning point', 'resisting change|bad luck|feeling out of control|repeating the cycle',
  'The wheel is turning. Circumstances are shifting whether you push or not. Luck is in the air, and so is change.',
  'A relationship enters a new phase. Chance meetings are likely. What goes around comes around.',
  'Expect movement: a change of role, a lucky break, an unexpected turn. Adapt rather than resist.',
  'Results may swing. Ride the good streak and do not panic at a dip.',
  'Fortune is changing. Do not gamble, but be ready to catch an opportunity.',
  'Go with the turn. Fighting the wheel only wears you out.'],
'major-11': ['fairness|truth|accountability|clarity', 'unfairness|dishonesty|avoiding consequences|harsh judgement',
  'Cause and effect are visible. Decisions have consequences now, and honesty is the only thing that works.',
  'Be honest about what is fair between you. Balance is restored when both sides own their part.',
  'Contracts, legal matters, evaluations. Do things by the book and keep records.',
  'Fair effort brings fair results. Be honest with yourself about how much you have actually done.',
  'Settle accounts. Pay what you owe and collect what you are owed.',
  'Tell the truth, especially to yourself.'],
'major-12': ['pause|surrender|new perspective|letting go', 'stalling|martyrdom|indecision|stuck by choice',
  'Things are on hold, and that pause has a purpose. Seen from a different angle, the situation looks different. Wait willingly.',
  'A relationship is in limbo. Pushing will not help. Let go of the outcome and see what changes.',
  'A delay or a project on hold. Use the time to rethink the approach instead of forcing it.',
  'Step back from a problem. The solution appears when you stop staring at it.',
  'Not the time for money moves. Hold and review.',
  'Do nothing for a moment, on purpose. Then look again.'],
'major-13': ['endings|transformation|release|renewal', 'clinging|fear of change|stagnation|dragging out the end',
  'Something is ending so that something else can begin. It can feel heavy, but the energy is clearing, not cruel.',
  'A relationship, or a version of it, is ending. Grieve, then let the new shape emerge.',
  'A role, a project or a way of working closes. Do not cling. What comes next needs the space.',
  'An old method or an old goal is done. Change how you study.',
  'A financial chapter closes. Cut what no longer works and rebuild.',
  'Let it end. You cannot start the next chapter while holding the last page.'],
'major-14': ['balance|moderation|patience|healing', 'excess|imbalance|impatience|clashing priorities',
  'Blend, do not force. Your energy is about finding the middle path and taking your time. Healing is happening.',
  'Harmony grows through patience and compromise. Avoid extremes in feeling or demand.',
  'Steady teamwork and careful balancing of tasks. Do not rush. Combine skills.',
  'Steady pacing beats cramming. Balance study with rest.',
  'Moderate spending, moderate saving. No dramatic moves.',
  'A little of everything, and nothing to excess.'],
'major-15': ['attachment|desire|ambition|raw honesty', 'addiction|obsession|toxic patterns|feeling trapped',
  'Something has a grip on you: a habit, a person, a want. This energy is powerful and not necessarily bad, but you need to see the chain.',
  'Intense attraction or a bond that is hard to leave. Ask whether it feeds you or drains you.',
  'Ambition and drive, or a job that owns you. Check what you are trading for the money.',
  'Distraction and procrastination are strong. Name the habit that steals your time.',
  'Watch debt, impulse spending, or money that comes with strings.',
  'Name what has you. Naming it loosens the chain.'],
'major-16': ['sudden change|revelation|breakthrough|freedom', 'disaster|shock|avoidable collapse|refusing the lesson',
  'Something built on shaky ground is coming down. It is a shock, but what falls was not solid. Truth is breaking through.',
  'A sudden upheaval or a truth revealed. Painful, but it clears what was false.',
  'Sudden change at work: a plan collapses, a structure is challenged. Rebuild on firmer ground.',
  'A plan falls apart. Reassess and rebuild the schedule from scratch.',
  'Unexpected expense or loss. Protect the basics first.',
  'Let the false thing fall. Rebuild with what is true.'],
'major-17': ['hope|healing|inspiration|renewal', 'discouragement|lost faith|self-doubt|empty optimism',
  'After hard things, a calm has arrived. Hope is real now, not forced. You are being restored.',
  'Healing after hurt. Openness returns. Love that is honest and calm.',
  'Inspiration and a sense of purpose. A good time for creative and long-term plans.',
  'Renewed motivation. You see why you are learning this.',
  'Money troubles ease. Give generously within reason.',
  'Trust the quiet hope. It is telling the truth.'],
'major-18': ['intuition|dreams|uncertainty|the unconscious', 'illusion|anxiety|deception|confusion',
  'Nothing is fully clear. Fears and imagination colour what you see. Move slowly and trust your instincts, not your worries.',
  'Mixed signals and uncertainty. Something is hidden. Do not assume the worst, but do ask.',
  'Confusion or unclear information at work. Wait for facts before you act.',
  'Anxiety clouds understanding. Sleep, then review with a clear head.',
  'Unclear or risky money matters. Do not sign anything you do not fully understand.',
  'Walk slowly through the fog. It lifts.'],
'major-19': ['joy|success|clarity|vitality', 'arrogance|overexposure|delayed happiness|false cheer',
  'Warm, clear, confident energy. Things are working and it shows. Enjoy it openly.',
  'Happiness, warmth, an easy connection. A relationship in full light.',
  'Success, recognition, a clear win. Your work is seen.',
  'Clarity and confidence. Good results are coming.',
  'Good fortune and growth. Money comes with joy rather than struggle.',
  'Say yes to the good thing. You have earned it.'],
'major-20': ['awakening|a calling|forgiveness|reckoning', 'self-judgement|refusing the call|regret|stuck in the past',
  'A moment of clear seeing. You are being called to a decision, a change, a new level. The past is reviewed and released.',
  'A relationship reaches a turning point. Forgive, decide, and move.',
  'A career calling, an evaluation, a chance to rise. Answer it.',
  'Results and evaluations. Learn from the past and step up.',
  'A financial reckoning. Face the numbers and decide.',
  'Answer the call. You already know what it is.'],
'major-21': ['completion|wholeness|achievement|travel', 'unfinished business|delay|feeling incomplete|short-cuts',
  'A cycle completes. You have integrated the lesson. This is fulfilment, and the doorway to the next round.',
  'A relationship reaches a whole, mature stage. Or a journey together.',
  'Completion of a big project. Recognition, and possibly travel or an international link.',
  'Graduation, completion, mastery of a subject.',
  'Financial goal achieved. Long-term security.',
  'Finish it properly. Then celebrate before starting the next thing.'],

'wands-1': ['spark|inspiration|new energy|desire', 'false start|no direction|delay|burnout',
  'A surge of wanting to make something. Raw energy, not yet aimed. Point it somewhere.',
  'New attraction, passion, a spark. Fun, and not yet a promise.',
  'A new idea or offer with real energy behind it. Start.',
  'Enthusiasm for a new subject. Use it before it cools.',
  'A new income idea. Test it small.',
  'Light the fire, then build the hearth.'],
'wands-2': ['planning|vision|choice|bold horizons', 'playing it safe|fear of the unknown|plans that never launch',
  'You hold something and look at what is beyond it. Time to choose the bigger horizon.',
  'Deciding what you want from love, or between comfort and a bolder choice.',
  'Planning expansion, partnerships, the next step. Think big, then commit.',
  'Choosing a direction or a specialisation. Plan the year, not just the week.',
  'Investment planning. Balance safety and growth.',
  'Decide the direction. Detail comes after.'],
'wands-3': ['expansion|foresight|progress|waiting well', 'delay|impatience|thinking too small|no follow-through',
  'Your first efforts are out there and working. Now you wait and prepare for what comes back.',
  'Something set in motion is developing. Give it time. Long-distance possibilities.',
  'Growth, new markets, results from earlier effort. Keep your eye on the horizon.',
  'Groundwork is done; results are on their way.',
  'Returns from earlier investment. Patience pays.',
  'Watch the horizon, not the clock.'],
'wands-4': ['celebration|home|stability|community', 'instability|tension at home|cancelled plans|feeling unwelcome',
  'A milestone, a homecoming, a reason to gather. Stable joy.',
  'Commitment, moving in together, a celebration with loved ones.',
  'A team milestone or a stable, supportive workplace. Celebrate.',
  'A milestone reached. Study group or supportive environment.',
  'Financial stability. A purchase for the home is favoured.',
  'Mark the milestone. Then rest.'],
'wands-5': ['competition|debate|energy|testing', 'conflict|chaos|arguing for nothing|avoiding the fight',
  'Lots of energies clashing: opinions, egos, plans. Not dangerous, but noisy. Compete fairly.',
  'Bickering, rivalry, or too many differences at once. Argue about the real thing.',
  'Competition, differing views, a struggle to be heard. Stay in the game.',
  'Competitive environment or scattered focus. Pick one battle.',
  'Competing demands on money. Prioritise.',
  'Pick the fight worth having and drop the rest.'],
'wands-6': ['victory|recognition|confidence|progress', 'ego|fall from grace|no recognition|hollow win',
  'A win is being noticed. You are ahead and people see it. Enjoy the recognition.',
  'Feeling admired. A relationship you are proud of.',
  'Promotion, praise, success in public. Accept it graciously.',
  'Good results and recognition. Confidence justified.',
  'A financial win or reward.',
  'Take the applause, then keep riding.'],
'wands-7': ['defence|perseverance|courage|standing your ground', 'giving up|exhaustion|feeling overwhelmed|defensiveness',
  'You are holding a position against pressure. It is tiring, but you have the high ground.',
  'Defending a relationship or your own needs. Stand firm without going to war.',
  'Competition or challenges to your position. Hold your ground with skill.',
  'Pressure and challenge. Keep going; you are stronger than the doubt.',
  'Protect what you have from demands. Say no.',
  'Hold the line, but breathe while you do it.'],
'wands-8': ['speed|news|movement|momentum', 'delays|chaos|rushed decisions|miscommunication',
  'Things are moving fast. Messages, travel, sudden progress. Keep up and stay clear.',
  'Quick developments, messages, a fast-moving connection. Reply.',
  'Rapid progress, news, travel. Act quickly on offers.',
  'Fast progress. Deadlines approach; move now.',
  'Money moves quickly. Fast opportunities, fast expenses.',
  'Act fast, but keep your head.'],
'wands-9': ['resilience|persistence|caution|last push', 'paranoia|exhaustion|refusing help|defensiveness',
  'You are tired but nearly there. Guard what you have built and take the last step.',
  'Wary after past hurt. Protect yourself, but do not wall everyone out.',
  'Almost done with a hard stretch. Persist. Set boundaries.',
  'The final push before the exam or deadline. Keep the routine.',
  'Protect your savings. Be cautious with new commitments.',
  'One more step. Then rest, really rest.'],
'wands-10': ['responsibility|burden|hard work|determination', 'overload|burnout|carrying others|no delegation',
  'You are carrying a lot, maybe too much. The load is real, and so is your strength. Something can be put down.',
  'Taking on all the emotional work. Share the weight.',
  'Overwork, too many duties. Delegate or drop something.',
  'Overloaded schedule. Cut to what matters.',
  'Financial burdens and obligations. Simplify.',
  'Put one thing down today.'],
'wands-c0': ['enthusiasm|exploration|messages|a fresh idea', 'lack of direction|impatience|immaturity|delays',
  'Curious, eager, a little restless. A new idea or message is arriving. Explore it.',
  'A flirt, a fresh message, someone young at heart. Fun, not yet serious.',
  'A new idea, a trainee role, an exciting message about work.',
  'Curiosity and eagerness. Explore new topics.',
  'A new idea about money. Research before you invest.',
  'Follow the spark and see where it goes.'],
'wands-c1': ['action|passion|adventure|charisma', 'recklessness|impulsiveness|arrogance|leaving too soon',
  'Bold, fast, charming, impatient. You are ready to charge. Aim before you go.',
  'A passionate, exciting person or phase. Exciting, and not always reliable.',
  'Bold action, travel, taking charge. Watch the impulsiveness.',
  'Bursts of energy. Channel them into a plan.',
  'Bold financial moves. Risky. Check the details.',
  'Charge, but know where the cliff is.'],
'wands-c2': ['warmth|confidence|independence|magnetism', 'jealousy|demanding|drama|burnout',
  'Warm, confident, magnetic energy. You are attracting attention. Use it well.',
  'A confident, warm partner or your own attractive self-assurance.',
  'Leadership with warmth. Inspire the team.',
  'Confident, self-directed learning.',
  'Confident money management. Independence.',
  'Shine, and let others shine too.'],
'wands-c3': ['vision|leadership|boldness|entrepreneurship', 'tyranny|impatience|high expectations|ruthlessness',
  'Big-picture, bold leadership energy. You are setting the direction. Lead by inspiring, not by ordering.',
  'A charismatic, driven partner or your own leadership in love.',
  'Lead the venture. Vision plus action.',
  'Take charge of your learning path.',
  'Entrepreneurial money. Bold, calculated moves.',
  'Lead from the front, with heart.'],

'cups-1': ['new love|emotional beginning|compassion|creativity', 'emptiness|blocked feelings|self-love missing|emotional overflow',
  'Your heart is opening. New feeling, new compassion, a creative or spiritual start. Receive it.',
  'A new love or a renewal of feeling. Openness.',
  'Emotional fulfilment at work, a creative start, good relationships.',
  'Joy in learning. A creative subject calls.',
  'Money from something you love. Generosity flows.',
  'Let the cup fill.'],
'cups-2': ['partnership|mutual attraction|connection|balance', 'imbalance|break-up|miscommunication|one-sided',
  'A real connection between two people or two sides. Mutual respect and attraction.',
  'A strong mutual bond, partnership, a meaningful meeting.',
  'A good business partnership or a strong working relationship.',
  'Study partner or mentor who suits you.',
  'A fair financial partnership.',
  'Meet halfway; it works.'],
'cups-3': ['friendship|celebration|community|creativity', 'gossip|overindulgence|a third person|isolation',
  'Joyful, social, celebratory energy. Friends, gatherings, shared happiness.',
  'Celebration with friends. Or a third person in the picture: check.',
  'Teamwork, celebration, a creative collaboration.',
  'Group study works. Celebrate progress.',
  'Spending on social life. Enjoy in moderation.',
  'Call your friends.'],
'cups-4': ['contemplation|apathy|re-evaluation|boredom', 'missed opportunity|withdrawal|ingratitude|numbness',
  'You feel flat, unimpressed, unsure. An offer is there but you are not seeing it. Look up.',
  'Boredom or emotional distance. Something good is being ignored.',
  'Dissatisfaction, missed chance. Re-evaluate what you want.',
  'Loss of motivation. Change the approach.',
  'Missed financial opportunity. Pay attention.',
  'Look at what is being offered before you refuse it.'],
'cups-5': ['grief|regret|loss|acceptance', 'refusing to move on|self-pity|dwelling|isolation',
  'Sadness over what is lost. It is real. But not everything is spilled; two cups still stand.',
  'Disappointment or loss in love. Grieve, then turn around.',
  'A setback or disappointment. Learn and move on.',
  'A poor result. Not the end. Turn to what remains.',
  'Financial loss. Assess what remains.',
  'Turn around. Two cups are still full.'],
'cups-6': ['nostalgia|innocence|kindness|the past', 'stuck in the past|naivety|unrealistic memories|clinging',
  'Sweet memories, kindness, a return of something innocent. The past visits gently.',
  'An old flame, childhood sweetness, or simple affection.',
  'Old contacts return. Kindness at work. Familiar roles.',
  'Revisit basics. Old knowledge helps.',
  'A gift, or money from the past.',
  'Enjoy the memory. Live in the present.'],
'cups-7': ['choices|imagination|dreams|possibilities', 'illusion|wishful thinking|too many options|escapism',
  'Many options and fantasies. Not all are real. Choose with clear eyes.',
  'Fantasy versus reality in love. Idealising someone. See them clearly.',
  'Too many possibilities. Focus on one realistic path.',
  'Distractions and daydreams. Pick one thing.',
  'Financial fantasies. Do the math.',
  'Choose one cup, with your eyes open.'],
'cups-8': ['walking away|seeking more|letting go|a deeper search', 'fear of change|aimlessness|running away|staying too long',
  'Leaving something behind to find something deeper. It is a loss and a liberation.',
  'Walking away from what no longer fulfils. Hard and right.',
  'Leaving a job or a role for something more meaningful.',
  'Changing direction. Leave what does not fit.',
  'Leaving a financial situation that drains you.',
  'Go. What you seek is not here.'],
'cups-9': ['satisfaction|contentment|wishes granted|pleasure', 'smugness|overindulgence|shallow happiness|dissatisfaction',
  'Wishes fulfilled, comfort and pleasure. You have what you asked for. Enjoy it.',
  'Emotional satisfaction, joy in love.',
  'Achievement and satisfaction at work.',
  'Success and satisfaction with results.',
  'Financial comfort. Treat yourself, wisely.',
  'Enjoy it. You asked, it came.'],
'cups-10': ['harmony|family|lasting happiness|belonging', 'broken family|disharmony|unrealistic expectations|neglect',
  'Deep, shared, lasting happiness. Family, home, emotional fulfilment.',
  'A loving, committed relationship. Family harmony.',
  'Fulfilling work and good relationships with colleagues.',
  'Support from family for your studies.',
  'Financial security for the family.',
  'This is the good thing. Hold it gently.'],
'cups-c0': ['creativity|intuition|a message of feeling|sensitivity', 'emotional immaturity|moodiness|creative block|escapism',
  'A gentle, imaginative message or impulse. Something new is stirring in your heart.',
  'A sweet message, a crush, a tender beginning.',
  'A creative idea or an emotional message at work.',
  'Intuitive learning. Art and creativity.',
  'A small, unexpected gift.',
  'Listen to the small feeling.'],
'cups-c1': ['romance|charm|following the heart|idealism', 'moodiness|unrealistic|jealousy|deception',
  'Romantic, charming, idealistic energy. Following the heart. Check that the feet are on the ground.',
  'A romantic proposal or a charming suitor. Enjoy, but watch for illusions.',
  'Creative projects and diplomatic approaches.',
  'Inspired study. Art, music, literature.',
  'Emotional spending. Pause before buying.',
  'Follow the heart with open eyes.'],
'cups-c2': ['compassion|calm|intuition|emotional security', 'insecurity|co-dependence|martyrdom|overwhelmed',
  'Calm, caring, intuitive energy. You understand others and yourself. Care for yourself too.',
  'A nurturing, loving partner or your own emotional maturity.',
  'Empathy and intuition guide your work. Support colleagues.',
  'Learning through understanding, not memorising.',
  'Intuitive financial choices. Care for security.',
  'Care for others, but keep some for yourself.'],
'cups-c3': ['emotional balance|diplomacy|wisdom|compassion', 'emotional manipulation|moodiness|volatility|coldness',
  'Mature emotional control. Feelings are strong but held with wisdom.',
  'A mature, emotionally balanced partner. Compassion in love.',
  'Diplomacy and calm leadership. Handle people with care.',
  'Balanced, wise approach to learning.',
  'Balanced, wise money management.',
  'Feel deeply, act calmly.'],

'swords-1': ['clarity|truth|breakthrough|a new idea', 'confusion|misuse of power|harsh words|clouded judgement',
  'A moment of mental clarity. The truth cuts through. New ideas, decisive thinking.',
  'Honest conversations. Clarity about what you want.',
  'A breakthrough idea. Clear decisions.',
  'Sharp thinking. A new understanding.',
  'Clear financial thinking. A decisive plan.',
  'Say the true thing, kindly.'],
'swords-2': ['indecision|stalemate|weighing options|truce', 'avoidance|denial|paralysis|hiding',
  'You are stuck between two options and avoiding the choice. The blindfold is yours to remove.',
  'Avoiding a decision about a relationship. Face it.',
  'Stalemate or a decision you are avoiding. Gather facts, then choose.',
  'Torn between choices. Pick one and go.',
  'Financial decision on hold. Decide.',
  'Take off the blindfold and choose.'],
'swords-3': ['heartbreak|grief|painful truth|release', 'holding on to pain|bitterness|self-inflicted hurt|refusing to heal',
  'A sharp pain, usually from truth or loss. It hurts, and it clarifies. Let it out.',
  'Heartbreak, betrayal, a painful truth. Feel it, then heal.',
  'A painful setback or harsh criticism. Learn and recover.',
  'Disappointment. Painful but temporary.',
  'A painful financial loss. Recover and rebuild.',
  'Let the tears come. Then the healing.'],
'swords-4': ['rest|recovery|contemplation|retreat', 'burnout|restlessness|isolation|avoiding action',
  'Rest is required. Retreat, recover, think. Not the time to fight.',
  'A pause in the relationship. Recover your energy.',
  'Take a break. Recover before the next challenge.',
  'Rest before you study more. Your mind needs it.',
  'Pause financial activity. Review quietly.',
  'Rest. Really.'],
'swords-5': ['conflict|defeat|winning at a cost|tension', 'hostility|bullying|no-win situation|humiliation',
  'A conflict where nobody really wins. Ask whether the battle is worth it.',
  'Arguments and hurtful words. Winning the argument may lose the relationship.',
  'Workplace conflict, a hollow victory. Choose your battles.',
  'Competitiveness that hurts. Focus on your own path.',
  'A financial dispute. Do not fight over the small thing.',
  'Walk away from the fight you cannot win with grace.'],
'swords-6': ['transition|moving on|healing|calmer waters', 'stuck|unfinished baggage|resisting change|rough passage',
  'Leaving rough waters for calmer ones. A transition, quiet and necessary.',
  'Moving on from difficulty. Healing, possibly distance.',
  'A transition to a better situation. Travel possible.',
  'Moving past a difficult phase. Progress.',
  'Gradual financial recovery.',
  'Row toward the calm. It is there.'],
'swords-7': ['strategy|cunning|independence|getting away with it', 'deception|theft|self-deception|getting caught',
  'Strategy, stealth, doing it alone. Sometimes clever, sometimes sneaky. Check your motives.',
  'Secrecy or deception in a relationship. Honesty is safer.',
  'Strategy and independence. Or someone is not being straight.',
  'Shortcuts. Be careful they do not backfire.',
  'Watch for scams. Be strategic with money.',
  'Be clever, not sneaky.'],
'swords-8': ['feeling trapped|restriction|self-limiting beliefs|helplessness', 'victim mentality|paralysis|imprisonment|self-sabotage',
  'You feel trapped, but the binds are looser than they look. The prison is mostly in the mind.',
  'Feeling stuck in a relationship. You have more choice than you think.',
  'Feeling restricted at work. Look for the exit you are not seeing.',
  'Feeling overwhelmed. Break the task into small steps.',
  'Financial restriction. Look for options.',
  'The ropes are loose. Move.'],
'swords-9': ['anxiety|worry|nightmares|guilt', 'despair|hopelessness|catastrophising|isolation',
  'Worry is keeping you up. Most of the fears are bigger than the facts. Reach out.',
  'Anxiety about a relationship. Talk instead of spiralling.',
  'Stress and worry about work. Check the real situation.',
  'Exam anxiety. Prepare, then sleep.',
  'Money worries. Make a plan and share the burden.',
  'Turn on the light. The monsters shrink.'],
'swords-10': ['rock bottom|ending|betrayal|the worst is over', 'recovery|resisting the end|dramatising|survival',
  'A painful ending, fully arrived. It is done. And because it is done, the dawn is coming.',
  'A painful, final ending. Grieve and then heal; the worst is over.',
  'A project or job ends badly. Recover and start fresh.',
  'A failed attempt. The lesson is learned; move on.',
  'A financial low point. From here, up.',
  'It is over. Now you can rise.'],
'swords-c0': ['curiosity|vigilance|new ideas|communication', 'gossip|hasty words|scattered thinking|spying',
  'Alert, curious, talkative energy. New ideas and messages. Watch the words.',
  'Curious messages, playful debate. Or gossip: be careful.',
  'New ideas, communication, vigilance.',
  'Curious mind. Research and question.',
  'Watch out for gossip and hasty decisions.',
  'Ask the question, then listen.'],
'swords-c1': ['ambition|action|directness|speed', 'aggression|impatience|recklessness|ruthlessness',
  'Fast, sharp, decisive energy. You are charging in. Make sure you are pointing the right way.',
  'Someone direct and fast, or a rushed decision. Slow down a little.',
  'Rapid decisions and bold action. Watch for haste.',
  'Aggressive study push. Effective but exhausting.',
  'Fast money moves. Assess the risk.',
  'Charge, but check the map first.'],
'swords-c2': ['independence|clear judgement|honesty|boundaries', 'coldness|bitterness|isolation|harsh criticism',
  'Clear-eyed, honest, independent. You see through nonsense. Add warmth to the truth.',
  'Independence and honesty. Boundaries are needed.',
  'Clear judgement and direct communication. Lead with integrity.',
  'Analytical, disciplined learning.',
  'Clear, unsentimental money decisions.',
  'Tell the truth with kindness.'],
'swords-c3': ['authority|intellect|truth|discipline', 'manipulation|tyranny|coldness|abuse of power',
  'Authority of mind. Clear rules, fair judgement, intellectual power. Use it justly.',
  'A logical, principled partner. Clarity in commitment.',
  'Leadership through expertise and fairness.',
  'Master the subject through discipline and logic.',
  'Rational, structured financial planning.',
  'Rule with reason and fairness.'],

'pentacles-1': ['opportunity|prosperity|new venture|manifestation', 'missed chance|scarcity|poor planning|greed',
  'A concrete opportunity is being offered. New money, new venture, something real. Take it.',
  'A stable, promising new relationship. Real, not just exciting.',
  'A new job, contract or venture. Solid and promising.',
  'A new practical opportunity: scholarship, course, position.',
  'New income or a financial opportunity. Seize it.',
  'Take the coin. It is real.'],
'pentacles-2': ['balance|adaptability|juggling|flexibility', 'overwhelm|disorganisation|financial stress|dropping the ball',
  'You are juggling several things and keeping them in the air. Stay flexible; it works for now.',
  'Balancing love with other demands. Make time on purpose.',
  'Multiple projects. Prioritise and stay adaptable.',
  'Balancing study with life. Plan the week.',
  'Cash flow juggling. Budget carefully.',
  'Keep the balls in the air, but not forever.'],
'pentacles-3': ['teamwork|skill|learning|quality', 'lack of teamwork|poor quality|no recognition|working alone',
  'Skill is being recognised and built on. Collaboration and craftsmanship pay off.',
  'Building a relationship together, step by step.',
  'Collaboration, skill recognised, quality work. Good for team projects.',
  'Learning from others. Skill improving through practice.',
  'Money from skill and cooperation.',
  'Do the work well, with others.'],
'pentacles-4': ['security|control|saving|stability', 'greed|hoarding|fear of loss|possessiveness',
  'Holding on tight to what you have. Security matters, but too tight a grip stops the flow.',
  'Possessiveness or fear of losing someone. Loosen the grip.',
  'Job security and control. Do not resist all change.',
  'Steady, secure approach. Do not fear new methods.',
  'Saving and security. Balance with generosity.',
  'Hold what matters, loosen the rest.'],
'pentacles-5': ['hardship|worry|feeling left out|resilience', 'isolation|poverty mentality|refusing help|despair',
  'A hard patch, feeling left out in the cold. Help is nearer than it seems. Ask.',
  'Feeling alone or unsupported. Reach out; do not suffer in silence.',
  'Job insecurity or financial strain at work. Seek support.',
  'Struggling, lacking resources. Ask for help.',
  'Financial hardship. Seek assistance; it passes.',
  'The door is right there. Knock.'],
'pentacles-6': ['generosity|charity|balance|sharing', 'strings attached|debt|inequality|power imbalance',
  'Giving and receiving in balance. Generosity flows, and so does fairness.',
  'Generosity and support in a relationship. Check the balance of give and take.',
  'Fair pay, mentoring, support. Give and receive.',
  'Help from teachers or peers. Share what you know.',
  'Money coming through generosity, or a chance to give.',
  'Give what you can, receive what you need.'],
'pentacles-7': ['patience|assessment|long-term view|perseverance', 'impatience|lack of reward|frustration|poor investment',
  'You have worked and now you wait. Assess the growth; do not dig up the seeds.',
  'Assessing a relationship. Is the investment paying off?',
  'Long-term effort. Results are slow but coming. Evaluate.',
  'Slow progress. Keep tending it.',
  'Long-term investment. Patience is required.',
  'Let it grow.'],
'pentacles-8': ['craft|diligence|skill-building|dedication', 'perfectionism|monotony|lack of ambition|cutting corners',
  'Focused, patient work. Skill is built one repetition at a time. You are getting good.',
  'Working on the relationship with care and consistency.',
  'Dedication to craft. Mastery through practice.',
  'Diligent, repeated practice. This is how it sticks.',
  'Money through skill and steady work.',
  'Do the reps.'],
'pentacles-9': ['independence|self-sufficiency|luxury|self-worth', 'over-work|dependence|isolation|superficiality',
  'Comfort you made yourself. Independence, and enjoying it. You have earned this.',
  'Self-sufficiency in love. Happy alone or together.',
  'Success and independence. Enjoy the rewards of your work.',
  'Self-directed learning. Confidence in your abilities.',
  'Financial independence and comfort.',
  'Enjoy what you built.'],
'pentacles-10': ['legacy|wealth|family|long-term security', 'family conflict|financial loss|instability|short-term thinking',
  'Lasting wealth: family, legacy, structures that outlast you. Think in generations.',
  'A lasting relationship, family ties, a shared future.',
  'Long-term success, stable career, a lasting contribution.',
  'Education as a long-term investment. Family support.',
  'Wealth, inheritance, long-term security.',
  'Build for the long run.'],
'pentacles-c0': ['ambition|study|a practical start|manifestation', 'procrastination|lack of progress|daydreaming|no follow-through',
  'A practical new beginning: a course, a plan, a first step taken seriously. Learn it properly.',
  'A practical, grounded new connection. Slow and real.',
  'A new job, training, or a practical opportunity.',
  'A new course or a serious approach to study.',
  'A new financial goal. Start saving.',
  'Start, and study it properly.'],
'pentacles-c1': ['reliability|routine|hard work|responsibility', 'boredom|stagnation|stubbornness|perfectionism',
  'Slow, reliable, methodical. Not exciting, and it gets finished. That is its gift.',
  'A reliable, steady partner. Slow-burning, dependable love.',
  'Methodical work. Reliability wins.',
  'Consistent routine. Slow and steady.',
  'Conservative, safe money choices.',
  'Keep going, steadily.'],
'pentacles-c2': ['nurturing|practicality|abundance|security', 'overwork|self-neglect|smothering|materialism',
  'Practical care. You make people materially safe. Look after yourself too.',
  'A nurturing, practical partner. Home and comfort.',
  'Practical management and care for the team.',
  'Grounded, well-organised study.',
  'Practical, generous money management.',
  'Care for yourself as well as everyone else.'],
'pentacles-c3': ['wealth|leadership|security|discipline', 'greed|materialism|stubbornness|control through money',
  'Mastery of the material world. Stability and provision you can depend on.',
  'A stable, generous provider. Security in love.',
  'Business success. Leadership through reliability.',
  'Disciplined mastery of a practical subject.',
  'Wealth and financial mastery.',
  'Build wealth, and stay generous.']
});
