/* ============================ card insights, the 56 Minors, rewritten ============================
   Full sentences, a clear subject in every line, each thought leading into
   the next. Same field order as insight-en.js / insight-vi.js:
   [positive keywords, shadow keywords, energy now, love, work, study, money, advice]. */
Object.assign(INSIGHT.vi, {
'wands-1': ['tia lửa mới|cảm hứng|năng lượng dồi dào|khát khao', 'khởi đầu hụt|không có hướng|chậm trễ|cháy hết sớm',
  'Trong bạn đang nhen lên mong muốn làm một điều gì đó. Nguồn năng lượng này còn mới và chưa có hướng, việc của bạn là chọn cho nó một lối đi.',
  'Một sức hút mới hay một rung động vừa chớm nở. Cứ tận hưởng cảm giác ấy, nhưng nhớ rằng tia lửa đầu tiên chưa phải là lời hứa.',
  'Một ý tưởng hay một lời mời mới đang tới, và nó có sức sống thật. Đây là lúc nên bắt tay vào làm.',
  'Bạn đang hứng thú với một môn mới. Tranh thủ học ngay khi niềm hứng khởi còn đang nóng.',
  'Bạn đang nảy ra một cách kiếm tiền mới. Thử trước ở quy mô nhỏ rồi hẵng mở rộng.',
  'Nhóm lửa trước, rồi mới tính chuyện xây bếp.'],
'wands-2': ['lên kế hoạch|tầm nhìn|lựa chọn|chân trời mới', 'chơi an toàn|sợ điều chưa biết|kế hoạch không bao giờ chạy',
  'Bạn đã nắm được một điều trong tay nhưng ánh mắt đang hướng xa hơn. Đã đến lúc chọn chân trời rộng mở thay vì chốn quen thuộc.',
  'Bạn đang tự hỏi mình thật sự muốn gì trong tình yêu, hay đang phân vân giữa sự yên ổn và một lựa chọn táo bạo hơn.',
  'Bạn đang tính chuyện mở rộng, hợp tác hoặc bước tiếp theo. Cứ nghĩ lớn, rồi dứt khoát theo một hướng.',
  'Bạn đang cân nhắc hướng đi hay chuyên ngành. Lên kế hoạch cho cả năm, đừng chỉ nhìn tuần này.',
  'Bạn đang tính đến chuyện đầu tư. Nhớ giữ cân bằng giữa an toàn và sinh lời.',
  'Chọn hướng đi trước, chi tiết để tính sau.'],
'wands-3': ['mở rộng|tầm nhìn xa|tiến triển|biết chờ đợi', 'chậm trễ|nóng vội|nghĩ quá nhỏ|không theo tới cùng',
  'Những nỗ lực đầu tiên của bạn đã được gửi đi và đang bắt đầu có kết quả. Giờ là lúc kiên nhẫn chờ và chuẩn bị đón những gì sắp đến.',
  'Điều bạn vun đắp đang dần lớn lên. Cứ cho nó thêm thời gian, và đừng vội gạt đi một mối duyên ở xa.',
  'Nhờ những gì đã làm trước đó, công việc đang phát triển và mở ra những hướng mới. Hãy luôn nhìn về phía trước.',
  'Nền tảng của bạn đã vững, kết quả đang trên đường tới.',
  'Khoản đầu tư trước đây bắt đầu sinh lời. Sự kiên nhẫn của bạn đang được đền đáp.',
  'Nhìn về phía chân trời, đừng mải nhìn đồng hồ.'],
'wands-4': ['niềm vui|mái ấm|ổn định|sum họp', 'bất ổn|căng thẳng trong nhà|kế hoạch bị hủy|thấy không được chào đón',
  'Bạn vừa chạm tới một cột mốc, được trở về nhà, hay có dịp sum họp. Đây là niềm vui được xây trên nền móng vững chắc.',
  'Có thể là một lời hứa gắn bó, chuyện dọn về chung một nhà, hay một buổi ăn mừng cùng người thân.',
  'Nhóm của bạn vừa đạt một cột mốc, hoặc bạn đang ở một nơi làm việc ổn định, nơi mọi người biết nâng đỡ nhau. Đáng để ăn mừng.',
  'Bạn vừa vượt qua một chặng quan trọng. Nhóm học hay môi trường xung quanh đang giúp bạn tiến xa hơn.',
  'Tài chính đang ổn định, lúc này sắm sửa cho nhà cửa là hợp lý.',
  'Ghi nhận cột mốc này, rồi cho phép mình nghỉ ngơi.'],
'wands-5': ['cạnh tranh|tranh luận|sôi nổi|thử sức', 'xung đột|hỗn loạn|cãi vì cãi|né cuộc tranh',
  'Quanh bạn đang có nhiều ý kiến, cái tôi và kế hoạch va chạm nhau. Không có gì nguy hiểm, chỉ hơi ồn ào, nên cứ cạnh tranh một cách sòng phẳng.',
  'Hai bạn đang hay cãi vặt, ganh đua, hoặc vấp phải quá nhiều khác biệt cùng lúc. Chỉ nên tranh luận về những điều thật sự quan trọng.',
  'Nơi làm việc đang nhiều cạnh tranh và ý kiến trái chiều, khó để được lắng nghe. Đừng vội rút lui khỏi cuộc chơi.',
  'Việc học đang nhiều áp lực cạnh tranh, hoặc bạn đang bị phân tán. Hãy tập trung vào một mục tiêu.',
  'Nhiều khoản chi đang cùng giành một nguồn tiền. Sắp xếp lại xem việc nào cần trước.',
  'Chọn điều đáng để tranh, còn lại thì cho qua.'],
'wands-6': ['chiến thắng|được ghi nhận|tự tin|tiến bộ', 'cái tôi|từ đỉnh rơi xuống|không được nhìn thấy|thắng rỗng',
  'Thành công của bạn đang được mọi người nhìn thấy. Bạn đang dẫn trước, cứ tự hào đón nhận sự ghi nhận này.',
  'Bạn đang được ngưỡng mộ, và có một mối quan hệ khiến bạn thấy tự hào.',
  'Bạn sắp được thăng chức, được khen ngợi hoặc thành công trước mặt nhiều người. Hãy đón nhận một cách khiêm tốn.',
  'Kết quả của bạn đang tốt và được công nhận. Sự tự tin ấy là hoàn toàn xứng đáng.',
  'Một khoản thưởng hay một thắng lợi về tài chính đang đến gần.',
  'Đón nhận tràng pháo tay, rồi tiếp tục tiến lên.'],
'wands-7': ['kiên cường|bền bỉ|can đảm|giữ vững lập trường', 'bỏ cuộc|kiệt sức|thấy quá tải|phòng thủ thái quá',
  'Bạn đang phải đứng vững trước áp lực từ nhiều phía. Mệt thật, nhưng bạn đang ở thế chủ động.',
  'Bạn đang bảo vệ mối quan hệ hay những nhu cầu của chính mình. Cứ vững vàng, không cần phải gây chiến.',
  'Vị trí của bạn đang bị cạnh tranh hoặc thử thách. Hãy giữ chỗ đứng bằng chính năng lực của mình.',
  'Bạn đang chịu nhiều áp lực và thử thách. Cứ đi tiếp, bạn mạnh mẽ hơn những nghi ngờ trong lòng.',
  'Giữ lấy những gì mình có trước các đòi hỏi từ bên ngoài, và tập nói không khi cần.',
  'Đứng vững, nhưng nhớ hít thở.'],
'wands-8': ['nhanh chóng|tin tức|chuyển động|đà tiến', 'chậm trễ|hỗn loạn|quyết vội|hiểu lầm',
  'Mọi thứ đang diễn ra rất nhanh: tin nhắn, chuyến đi, những bước tiến bất ngờ. Hãy theo kịp nhịp và giữ đầu óc tỉnh táo.',
  'Chuyện tình cảm đang tiến triển nhanh, tin nhắn qua lại liên tục. Nhớ hồi đáp đúng lúc.',
  'Công việc đang chạy nhanh, tin tức dồn dập, có thể sắp có chuyến công tác. Có lời đề nghị nào thì nên nắm bắt ngay.',
  'Bạn đang tiến bộ nhanh, nhưng hạn nộp cũng đang tới gần. Bắt tay vào làm luôn thôi.',
  'Tiền đang vào ra nhanh, cả cơ hội lẫn chi tiêu. Để mắt đến cả hai.',
  'Làm nhanh, nhưng giữ cái đầu lạnh.'],
'wands-9': ['bền bỉ|kiên trì|cảnh giác|nỗ lực cuối cùng', 'đa nghi|kiệt sức|từ chối giúp đỡ|dựng rào',
  'Bạn đang mệt, nhưng đích đến đã rất gần. Giữ gìn những gì mình đã gây dựng và bước nốt chặng cuối.',
  'Những tổn thương cũ khiến bạn dè chừng. Tự bảo vệ mình là đúng, nhưng đừng khép cửa với tất cả mọi người.',
  'Bạn sắp đi hết một chặng khó. Kiên trì thêm chút nữa và đặt ranh giới cho rõ ràng.',
  'Đây là giai đoạn nước rút trước kỳ thi hay hạn nộp. Giữ đều nhịp là được.',
  'Giữ chắc khoản tiết kiệm và thận trọng với những cam kết mới.',
  'Bước thêm một bước nữa, rồi nghỉ ngơi cho thật sự.'],
'wands-10': ['trách nhiệm|gánh nặng|chăm chỉ|quyết tâm', 'quá tải|kiệt sức|gánh cho người khác|không giao việc',
  'Bạn đang gánh rất nhiều thứ, có lẽ là quá nhiều. Gánh nặng là thật, sức lực của bạn cũng thật, và có ít nhất một việc bạn có thể buông xuống.',
  'Bạn đang một mình ôm hết phần cảm xúc trong mối quan hệ. Hãy để người kia cùng san sẻ.',
  'Bạn đang làm quá sức với quá nhiều việc. Giao bớt hoặc bỏ bớt một việc đi.',
  'Lịch học của bạn đang quá dày. Cắt bớt, chỉ giữ lại những gì thật sự quan trọng.',
  'Bạn đang gánh nhiều nghĩa vụ tài chính cùng lúc. Thử gom gọn và đơn giản hóa chúng.',
  'Hôm nay, hãy đặt xuống một gánh.'],
'wands-c0': ['nhiệt huyết|khám phá|tin vui|ý tưởng mới', 'thiếu định hướng|nóng vội|non nớt|chậm trễ',
  'Bạn đang tò mò, háo hức và có chút nôn nao. Một ý tưởng hay một tin nhắn mới đang tới, cứ thử khám phá xem sao.',
  'Có người đang tán tỉnh bạn, một tin nhắn mới, hay một người có tâm hồn trẻ trung. Vui đấy, nhưng chưa phải chuyện nghiêm túc.',
  'Một ý tưởng mới, một vị trí thực tập, hoặc một tin vui về công việc đang đến.',
  'Bạn đang tò mò và hăng hái. Thử tìm hiểu thêm những chủ đề mới.',
  'Bạn đang có ý tưởng mới về chuyện tiền bạc. Tìm hiểu kỹ trước khi bỏ vốn.',
  'Đi theo tia lửa ấy, xem nó dẫn mình tới đâu.'],
'wands-c1': ['hành động|đam mê|phiêu lưu|cuốn hút', 'liều lĩnh|bốc đồng|kiêu ngạo|đi quá sớm',
  'Bạn đang táo bạo, nhanh nhẹn, cuốn hút nhưng thiếu kiên nhẫn. Bạn đã sẵn sàng lao đi, chỉ cần nhắm hướng cho kỹ trước.',
  'Bạn đang gặp một người đầy nhiệt huyết, hoặc chính bạn đang ở giai đoạn như vậy. Hấp dẫn thật, nhưng không phải lúc nào cũng đáng tin.',
  'Bạn đang hành động quyết liệt, di chuyển nhiều và nắm thế chủ động. Coi chừng sự bốc đồng.',
  'Năng lượng của bạn lúc lên lúc xuống. Hãy dồn nó vào một kế hoạch cụ thể.',
  'Bạn đang tính một nước đi táo bạo về tiền bạc. Có rủi ro, nên xem kỹ từng chi tiết.',
  'Cứ lao về phía trước, nhưng biết rõ vực thẳm nằm ở đâu.'],
'wands-c2': ['ấm áp|tự tin|độc lập|thu hút', 'ghen|đòi hỏi|kịch tính|cháy sạch',
  'Bạn đang toát ra năng lượng ấm áp, tự tin và cuốn hút. Mọi người đang chú ý đến bạn, hãy dùng điều đó vào việc tốt.',
  'Bạn đang có một người thương tự tin và ấm áp, hoặc chính nét tự tin dễ mến của bạn đang tỏa sáng.',
  'Bạn đang dẫn dắt bằng sự ấm áp và truyền cảm hứng cho cả nhóm.',
  'Bạn đang học với sự tự tin và biết tự định hướng cho mình.',
  'Bạn đang quản lý tiền bạc một cách tự tin và tự chủ.',
  'Hãy tỏa sáng, và để người khác cũng được tỏa sáng.'],
'wands-c3': ['tầm nhìn|dẫn dắt|quyết đoán|làm chủ', 'độc đoán|thiếu kiên nhẫn|kỳ vọng quá cao|tàn nhẫn',
  'Bạn đang mang năng lượng của người lãnh đạo có tầm nhìn, dám nghĩ dám làm, và chính bạn là người vạch đường. Hãy dẫn dắt bằng cảm hứng, đừng bằng mệnh lệnh.',
  'Bạn đang ở bên một người có sức hút và giàu nhiệt huyết, hoặc chính bạn là người dẫn dắt trong chuyện tình cảm.',
  'Bạn đang dẫn dắt dự án bằng cả tầm nhìn lẫn hành động.',
  'Hãy tự làm chủ lộ trình học của mình.',
  'Bạn đang quản lý tiền theo tinh thần khởi nghiệp: táo bạo nhưng có tính toán.',
  'Hãy đi đầu, bằng cả trái tim.'],

'cups-1': ['tình cảm mới|khởi đầu cảm xúc|bao dung|sáng tạo', 'trống rỗng|cảm xúc bị chặn|thiếu yêu bản thân|cảm xúc tràn',
  'Trái tim bạn đang mở ra với một cảm xúc mới, một sự cảm thông mới, hay một khởi đầu đầy sáng tạo. Cứ đón nhận nó.',
  'Một tình yêu mới đang đến, hoặc tình cảm cũ đang được hâm nóng lại. Bạn đang cởi mở hơn bao giờ hết.',
  'Bạn đang thấy vui với công việc, có một khởi đầu sáng tạo và những mối quan hệ tốt đẹp.',
  'Bạn đang tìm thấy niềm vui trong việc học, và một môn nghệ thuật hay sáng tạo đang gọi tên bạn.',
  'Tiền đang đến từ công việc bạn yêu thích, và sự rộng lượng đang lan tỏa quanh bạn.',
  'Hãy để chiếc cốc của mình được rót đầy.'],
'cups-2': ['gắn kết|tình cảm hai chiều|thấu hiểu|cân bằng', 'lệch cân|chia tay|hiểu lầm|một phía',
  'Bạn đang có một sự kết nối thật sự với một người. Sự tôn trọng và rung động đến từ cả hai phía.',
  'Bạn đang có một mối gắn bó sâu sắc từ hai phía, hoặc vừa có một cuộc gặp gỡ đầy ý nghĩa.',
  'Bạn đang có một mối hợp tác tốt hoặc một người đồng nghiệp rất ăn ý.',
  'Bạn đã tìm được một người bạn học hay người hướng dẫn hợp với mình.',
  'Bạn đang hợp tác làm ăn trên tinh thần công bằng, đôi bên cùng có lợi.',
  'Mỗi người nhường một bước, mọi chuyện sẽ ổn.'],
'cups-3': ['tình bạn|niềm vui chung|sum vầy|sáng tạo', 'đàm tiếu|quá đà|người thứ ba|cô lập',
  'Quanh bạn đang rộn ràng tiếng cười, bạn bè tụ họp và niềm vui được sẻ chia.',
  'Bạn đang vui vẻ bên bạn bè. Nhưng nếu có người thứ ba chen vào chuyện tình cảm, hãy để ý kỹ hơn.',
  'Nhóm của bạn đang phối hợp ăn ý, có thành quả đáng ăn mừng hoặc một cuộc hợp tác sáng tạo vừa bắt đầu.',
  'Học cùng bạn bè đang giúp bạn tiến bộ rõ rệt. Đừng quên tự thưởng cho mình sau mỗi bước tiến nhỏ.',
  'Bạn đang chi khá nhiều cho những buổi gặp gỡ, vui chơi. Vui thì cứ vui, nhưng nhớ giữ chừng mực.',
  'Hôm nay, hãy gọi cho một người bạn.'],
'cups-4': ['suy ngẫm|thờ ơ|nhìn lại|chán nản', 'bỏ lỡ cơ hội|thu mình|vô ơn|tê liệt',
  'Bạn đang thấy chán, chẳng có gì làm mình hứng thú và cũng chưa chắc mình muốn gì. Có một cơ hội đang ở ngay trước mặt mà bạn chưa nhận ra, thử ngẩng lên nhìn xem.',
  'Bạn đang thấy nhạt nhẽo hoặc xa cách trong tình cảm, trong khi có một điều tốt đẹp đang bị bỏ qua.',
  'Bạn đang không hài lòng và có thể đã để lỡ một cơ hội. Hãy nghĩ lại xem mình thật sự muốn gì.',
  'Bạn đang mất động lực học. Thử đổi sang một cách học khác.',
  'Có thể bạn đã bỏ lỡ một cơ hội về tiền bạc. Để ý kỹ hơn những gì đang đến.',
  'Nhìn kỹ điều đang được trao cho mình trước khi lắc đầu.'],
'cups-5': ['đau buồn|tiếc nuối|mất mát|chấp nhận', 'không chịu đi tiếp|thương thân|dằn vặt|cô lập',
  'Bạn đang buồn vì điều đã mất, và nỗi buồn ấy là thật. Nhưng chưa phải tất cả đều đổ vỡ, vẫn còn hai chiếc cốc đứng vững sau lưng bạn.',
  'Bạn đang thất vọng hoặc vừa mất mát trong tình yêu. Cứ cho phép mình buồn, rồi hãy quay lại nhìn những gì còn lại.',
  'Bạn vừa gặp một bước lùi hay một nỗi thất vọng. Rút ra bài học rồi đi tiếp.',
  'Bạn vừa nhận một kết quả không như mong đợi, nhưng chưa phải là hết. Hãy dựa vào những gì mình vẫn đang có.',
  'Bạn vừa mất một khoản tiền. Bình tĩnh xem lại những gì mình còn giữ được.',
  'Quay lại nhìn đi, hai chiếc cốc vẫn còn đầy.'],
'cups-6': ['hoài niệm|hồn nhiên|tử tế|kỷ niệm', 'kẹt trong quá khứ|ngây thơ|ký ức tô hồng|níu kéo',
  'Những kỷ niệm ngọt ngào, sự tử tế và một điều gì đó rất hồn nhiên đang quay về. Quá khứ đang nhẹ nhàng ghé thăm bạn.',
  'Một người cũ, một kỷ niệm tuổi thơ, hay một tình cảm giản dị đang xuất hiện.',
  'Một mối quan hệ cũ đang quay lại, hoặc bạn đang nhận được sự tử tế nơi làm việc.',
  'Ôn lại kiến thức nền, vì những gì học từ trước đang giúp ích cho bạn.',
  'Bạn sắp nhận một món quà, hoặc một khoản tiền liên quan đến chuyện cũ.',
  'Nâng niu kỷ niệm, nhưng hãy sống cho hiện tại.'],
'cups-7': ['lựa chọn|tưởng tượng|mơ mộng|nhiều khả năng', 'ảo tưởng|mơ hão|quá nhiều lựa chọn|trốn thực tế',
  'Trước mặt bạn có nhiều lựa chọn và nhiều viễn cảnh đẹp, nhưng không phải cái nào cũng thật. Hãy chọn bằng một cái đầu tỉnh táo.',
  'Bạn đang lẫn lộn giữa mộng tưởng và thực tế trong tình yêu, có thể đang thần tượng hóa ai đó. Hãy nhìn họ cho thật rõ.',
  'Bạn đang có quá nhiều hướng đi trước mặt. Tập trung vào một con đường thực tế.',
  'Bạn đang dễ xao nhãng và hay mơ mộng. Chọn một việc và làm cho xong.',
  'Bạn đang mơ tưởng nhiều về tiền bạc. Ngồi xuống tính toán cho cụ thể.',
  'Chọn lấy một chiếc cốc, và mở to mắt khi chọn.'],
'cups-8': ['ra đi|tìm điều ý nghĩa hơn|buông bỏ|đi sâu vào lòng', 'sợ thay đổi|vô định|bỏ chạy|ở lại quá lâu',
  'Bạn đang bỏ lại một điều quen thuộc để đi tìm thứ ý nghĩa hơn. Đó vừa là mất mát, vừa là sự nhẹ nhõm.',
  'Bạn đang rời khỏi một mối quan hệ không còn khiến mình thấy đủ đầy. Khó thật, nhưng đúng.',
  'Bạn đang rời một công việc hay một vị trí để tìm điều có ý nghĩa hơn.',
  'Bạn đang đổi hướng học. Mạnh dạn bỏ lại những gì không hợp với mình.',
  'Bạn đang thoát ra khỏi một tình trạng tài chính cứ bào mòn mình mãi.',
  'Cứ đi, điều bạn tìm không nằm ở đây.'],
'cups-9': ['hài lòng|mãn nguyện|ước mơ thành thật|tận hưởng', 'tự mãn|hưởng thụ quá đà|vui nông|vẫn chưa đủ',
  'Điều ước của bạn đang thành hiện thực, cùng với sự thoải mái và niềm vui. Bạn đã có điều mình mong, cứ tận hưởng đi.',
  'Bạn đang thấy mãn nguyện và tìm được niềm vui trong tình yêu.',
  'Bạn đang gặt hái thành quả và thấy hài lòng với công việc.',
  'Bạn đang học tốt và hài lòng với kết quả của mình.',
  'Tài chính đang dễ thở. Tự thưởng cho mình, nhưng chi tiêu cho khôn ngoan.',
  'Cứ tận hưởng, điều bạn mong đã đến rồi.'],
'cups-10': ['hòa thuận|gia đình|hạnh phúc lâu dài|được thuộc về', 'gia đình rạn|bất hòa|kỳ vọng phi thực tế|lơ là',
  'Bạn đang có một niềm hạnh phúc sâu sắc, bền lâu và được sẻ chia, bên gia đình, trong mái ấm và sự đủ đầy về tình cảm.',
  'Bạn đang ở trong một mối quan hệ yêu thương, gắn bó, và gia đình đang êm ấm.',
  'Bạn đang thấy đủ đầy trong công việc, và quan hệ với đồng nghiệp rất tốt đẹp.',
  'Gia đình đang ủng hộ việc học của bạn.',
  'Gia đình bạn đang có nền tảng tài chính vững vàng.',
  'Điều tốt đẹp đang ở đây, hãy nâng niu nó thật nhẹ nhàng.'],
'cups-c0': ['sáng tạo|trực giác|lời nhắn tình cảm|nhạy cảm', 'non nớt về cảm xúc|thất thường|bí ý tưởng|trốn thực tế',
  'Một lời nhắn hay một cảm hứng dịu dàng, giàu tưởng tượng đang tìm đến bạn. Có điều gì đó mới đang khẽ lay động trong tim.',
  'Bạn đang nhận được một tin nhắn ngọt ngào, có một người mới để thầm thương, hoặc đang ở một khởi đầu dịu dàng.',
  'Bạn đang có một ý tưởng sáng tạo, hoặc nhận được một lời nhắn chạm đến cảm xúc nơi làm việc.',
  'Bạn đang học tốt bằng trực giác, và các môn nghệ thuật, sáng tạo rất hợp với bạn.',
  'Bạn sắp nhận một món quà nhỏ bất ngờ.',
  'Lắng nghe cảm giác nhỏ bé ấy.'],
'cups-c1': ['lãng mạn|duyên dáng|theo tiếng gọi con tim|lý tưởng', 'thất thường|phi thực tế|ghen|lừa dối',
  'Bạn đang lãng mạn, duyên dáng và sống thiên về lý tưởng, để trái tim dẫn đường. Chỉ cần nhớ giữ đôi chân chạm đất.',
  'Bạn đang nhận một lời tỏ tình lãng mạn hoặc gặp một người theo đuổi rất duyên dáng. Cứ vui, nhưng coi chừng ảo tưởng.',
  'Bạn đang làm những dự án sáng tạo và xử lý mọi việc rất khéo léo.',
  'Bạn đang học đầy cảm hứng, nhất là với nghệ thuật, âm nhạc và văn chương.',
  'Bạn đang chi tiêu theo cảm xúc. Dừng lại một chút trước khi mua.',
  'Đi theo trái tim, nhưng giữ đôi mắt tỉnh táo.'],
'cups-c2': ['bao dung|điềm tĩnh|trực giác|chỗ dựa tinh thần', 'bất an|lệ thuộc|hy sinh quá mức|quá tải',
  'Bạn đang điềm tĩnh, biết quan tâm và rất nhạy bén. Bạn hiểu người khác và hiểu cả chính mình, chỉ cần nhớ chăm sóc bản thân nữa.',
  'Bạn đang có một người thương biết chăm sóc và yêu thương, hoặc chính sự trưởng thành trong cảm xúc của bạn đang dẫn đường.',
  'Sự thấu cảm và trực giác đang giúp bạn làm việc tốt, và bạn là chỗ dựa đáng tin cho đồng nghiệp.',
  'Bạn đang học bằng cách hiểu sâu, chứ không chỉ học thuộc lòng.',
  'Bạn đang dùng tiền theo trực giác và luôn nghĩ đến sự an toàn của mình.',
  'Chăm lo cho người khác, nhưng nhớ chừa một phần cho mình.'],
'cups-c3': ['cảm xúc cân bằng|khéo léo|khôn ngoan|bao dung', 'thao túng cảm xúc|thất thường|dễ bùng|lạnh',
  'Bạn đang làm chủ cảm xúc một cách chín chắn. Cảm xúc của bạn rất mạnh, nhưng được giữ vững bằng sự khôn ngoan.',
  'Bạn đang ở bên một người trưởng thành và vững vàng về cảm xúc, và tình yêu của hai bạn có nhiều bao dung.',
  'Bạn đang dẫn dắt một cách khéo léo, điềm tĩnh và luôn cư xử chu đáo với mọi người.',
  'Bạn đang tiếp cận việc học một cách cân bằng và khôn ngoan.',
  'Bạn đang quản lý tiền bạc một cách cân bằng và sáng suốt.',
  'Cảm nhận thật sâu, nhưng hành động thật điềm tĩnh.'],

'swords-1': ['sáng suốt|sự thật|đột phá|ý tưởng mới', 'rối|lạm dụng sức mạnh|lời cay nghiệt|phán đoán mờ',
  'Đầu óc bạn đang có một khoảnh khắc sáng rõ, khi sự thật hiện ra thẳng thắn và rành mạch. Bạn đang có ý tưởng mới và suy nghĩ rất quyết đoán.',
  'Bạn đang có những cuộc trò chuyện thẳng thắn và thấy rõ điều mình thật sự muốn.',
  'Bạn vừa nảy ra một ý tưởng đột phá và đang đưa ra những quyết định dứt khoát.',
  'Đầu óc bạn đang rất sắc bén, và bạn vừa vỡ lẽ ra một điều mới.',
  'Bạn đang nhìn chuyện tiền bạc rất rõ ràng và có một kế hoạch dứt khoát.',
  'Nói thật, nhưng nói bằng sự tử tế.'],
'swords-2': ['phân vân|bế tắc|cân nhắc|tạm hoãn', 'né tránh|chối bỏ|tê liệt|trốn',
  'Bạn đang kẹt giữa hai lựa chọn và cứ né tránh việc phải quyết định. Chính bạn đang tự bịt mắt mình, và bạn hoàn toàn có thể gỡ nó ra.',
  'Bạn đang lảng tránh một quyết định trong chuyện tình cảm. Đến lúc phải đối diện rồi.',
  'Bạn đang bế tắc hoặc né một quyết định. Tìm hiểu cho rõ sự việc, rồi chọn.',
  'Bạn đang giằng co giữa nhiều lựa chọn. Chọn một hướng và bắt đầu đi.',
  'Một quyết định về tiền bạc đang bị bỏ lửng. Đã đến lúc phải chốt.',
  'Gỡ tấm bịt mắt ra, rồi chọn.'],
'swords-3': ['tổn thương|đau buồn|sự thật khó nghe|giải tỏa', 'ôm nỗi đau|cay đắng|tự làm mình đau|không chịu lành',
  'Bạn đang mang một vết thương lòng, thường đến từ một sự thật khó nghe hay một mất mát. Đau thật, nhưng nó giúp bạn nhìn rõ mọi chuyện, nên đừng cố kìm nén.',
  'Bạn đang tan vỡ, bị phản bội, hoặc phải đối diện một sự thật đau lòng. Cứ cho phép mình buồn, rồi từ từ lành lại.',
  'Bạn vừa vấp một cú ngã đau hoặc nhận một lời chê nặng nề. Rút ra bài học, rồi đứng dậy.',
  'Kết quả chưa như mong đợi khiến bạn thất vọng. Buồn là thật, nhưng chỉ là tạm thời.',
  'Bạn vừa mất một khoản tiền khiến bạn xót xa. Từ từ gượng lại rồi gây dựng lại.',
  'Khóc được thì cứ khóc, nước mắt rơi rồi lòng mới nhẹ.'],
'swords-4': ['nghỉ ngơi|hồi phục|tĩnh tâm|tạm lui', 'kiệt sức|bồn chồn|cô lập|né hành động',
  'Bạn cần được nghỉ. Đây là lúc lùi lại, hồi sức và tĩnh tâm, không phải lúc để chiến đấu.',
  'Mối quan hệ đang ở một khoảng lặng. Hãy để cả hai lấy lại năng lượng.',
  'Nghỉ ngơi một chút để hồi sức trước thử thách tiếp theo.',
  'Nghỉ một lát rồi hẵng học tiếp, đầu óc bạn đang cần điều đó.',
  'Tạm gác mọi chuyện tiền bạc lại và bình tĩnh xem xét.',
  'Nghỉ đi, nghỉ cho thật sự.'],
'swords-5': ['xung đột|thua cuộc|thắng mà mất|căng thẳng', 'thù địch|bắt nạt|không ai thắng|bẽ mặt',
  'Bạn đang ở giữa một cuộc tranh cãi mà chẳng ai thật sự thắng. Thử tự hỏi xem cuộc chiến này có đáng không.',
  'Hai bạn đang cãi nhau với những lời làm tổn thương nhau. Thắng được cuộc cãi vã có khi lại mất đi người mình thương.',
  'Bạn đang va chạm nơi làm việc, hoặc vừa có một chiến thắng chẳng mang lại gì. Chỉ nên tranh những gì đáng tranh.',
  'Sự so bì, ganh đua đang làm bạn mệt mỏi. Tập trung vào con đường của riêng mình.',
  'Bạn đang vướng vào chuyện tranh chấp tiền bạc. Đừng cãi nhau vì những chuyện nhỏ.',
  'Rút lui khỏi cuộc chiến không thể thắng, một cách đàng hoàng.'],
'swords-6': ['chuyển tiếp|bước tiếp|chữa lành|bình yên hơn', 'kẹt|hành lý chưa xong|chống thay đổi|chuyến đi khó',
  'Bạn đang rời khỏi vùng sóng gió để hướng về nơi bình yên hơn. Đây là một cuộc chuyển mình lặng lẽ nhưng cần thiết.',
  'Bạn đang bước tiếp sau những khó khăn và dần lành lại, có thể cần giữ một chút khoảng cách.',
  'Bạn đang chuyển sang một hoàn cảnh tốt hơn, có thể kèm theo một chuyến đi.',
  'Bạn đang dần vượt qua giai đoạn khó và tiến bộ lên từng ngày.',
  'Tài chính của bạn đang hồi phục dần dần.',
  'Cứ chèo về phía bình yên, nó ở ngay phía trước.'],
'swords-7': ['chiến lược|khôn khéo|tự lực|xoay xở', 'lừa dối|trộm|tự lừa mình|bị bắt',
  'Bạn đang tính toán, làm việc lặng lẽ và tự mình xoay xở. Có khi đó là khôn ngoan, có khi lại là lén lút, nên hãy tự hỏi lại động cơ của mình.',
  'Trong chuyện tình cảm đang có điều gì đó bị giấu giếm hoặc không thật lòng. Thành thật mới là cách an toàn nhất.',
  'Bạn đang làm việc độc lập và có tính toán, hoặc có ai đó đang không thẳng thắn với bạn.',
  'Bạn đang đi đường tắt. Cẩn thận kẻo gậy ông đập lưng ông.',
  'Cảnh giác với lừa đảo và khôn khéo khi xử lý tiền bạc.',
  'Khôn ngoan thì được, lén lút thì không.'],
'swords-8': ['cảm giác bị trói buộc|giới hạn|tự giới hạn mình|bất lực', 'tâm lý nạn nhân|tê liệt|tự giam|tự phá',
  'Bạn đang thấy mình bị trói buộc, nhưng sợi dây lỏng hơn bạn tưởng. Phần lớn chiếc lồng này nằm trong suy nghĩ của bạn.',
  'Bạn đang thấy mắc kẹt trong mối quan hệ, nhưng bạn có nhiều lựa chọn hơn mình nghĩ.',
  'Bạn đang thấy bị gò bó nơi làm việc. Thử tìm một lối ra mà mình chưa để ý tới.',
  'Bạn đang thấy quá tải. Chia việc ra thành từng bước nhỏ.',
  'Chuyện tiền bạc đang bó tay bạn. Thử tìm những phương án khác.',
  'Dây đã lỏng rồi, cứ cử động đi.'],
'swords-9': ['lo âu|trăn trở|mất ngủ|áy náy', 'tuyệt vọng|mất hy vọng|nghĩ tới điều tệ nhất|cô lập',
  'Nỗi lo đang khiến bạn trằn trọc, nhưng phần lớn nỗi sợ ấy lớn hơn sự thật. Hãy tìm một người để tâm sự.',
  'Bạn đang bất an về mối quan hệ. Nói chuyện thẳng với nhau thay vì để suy nghĩ xoay vòng trong đầu.',
  'Bạn đang căng thẳng và lo lắng chuyện công việc. Thử nhìn lại xem tình hình thật sự ra sao.',
  'Bạn đang lo về kỳ thi. Chuẩn bị thật kỹ, rồi đi ngủ.',
  'Bạn đang lo lắng chuyện tiền bạc. Lập một kế hoạch và đừng gánh một mình.',
  'Bật đèn lên, con quái vật sẽ bé lại.'],
'swords-10': ['chạm đáy|khép lại|bị phản bội|điều tệ nhất đã qua', 'hồi phục|chống lại cái kết|làm quá|sống sót',
  'Một kết thúc đau đớn đã đến trọn vẹn, và mọi chuyện đã xong. Chính vì đã xong, bình minh đang tới.',
  'Bạn đang trải qua một cái kết đau lòng và dứt khoát. Cứ buồn rồi sẽ lành, điều tệ nhất đã qua rồi.',
  'Một dự án hay một công việc vừa kết thúc không như ý. Hồi sức rồi bắt đầu lại.',
  'Bạn vừa thất bại một lần. Bài học đã rõ, giờ thì đi tiếp.',
  'Tài chính đang chạm đáy, và từ đây chỉ có đi lên.',
  'Mọi chuyện đã qua, giờ bạn có thể đứng dậy.'],
'swords-c0': ['tò mò|tỉnh táo|ý tưởng mới|giao tiếp', 'đàm tiếu|lời vội|nghĩ tản mạn|dò xét',
  'Bạn đang tỉnh táo, tò mò và nói nhiều. Ý tưởng và tin tức mới đang đến, chỉ cần cẩn thận với lời ăn tiếng nói của mình.',
  'Bạn đang có những tin nhắn tò mò và những cuộc đấu khẩu vui vẻ. Nhưng nếu có lời ra tiếng vào, hãy cẩn thận.',
  'Bạn đang có ý tưởng mới, trao đổi nhiều và luôn giữ sự cảnh giác.',
  'Tính tò mò đang giúp bạn tìm tòi và biết đặt câu hỏi.',
  'Cẩn thận với tin đồn và những quyết định vội vàng về tiền bạc.',
  'Đặt câu hỏi, rồi lắng nghe.'],
'swords-c1': ['tham vọng|hành động|thẳng thắn|nhanh nhạy', 'hung hăng|thiếu kiên nhẫn|liều|tàn nhẫn',
  'Bạn đang nhanh nhạy, sắc sảo, quyết đoán và lao thẳng về phía trước. Chỉ cần chắc chắn mình đang đi đúng hướng.',
  'Bạn đang gặp một người thẳng tính và vội vàng, hoặc đứng trước một quyết định gấp gáp. Chậm lại một chút.',
  'Bạn đang quyết định nhanh và hành động táo bạo. Coi chừng sự vội vàng.',
  'Bạn đang trong đợt học dồn rất căng. Hiệu quả thật, nhưng dễ kiệt sức.',
  'Bạn đang có những nước đi tài chính rất nhanh. Cân nhắc kỹ rủi ro.',
  'Cứ lao lên, nhưng xem bản đồ trước đã.'],
'swords-c2': ['độc lập|sáng suốt|thẳng thắn|biết đặt ranh giới', 'lạnh|cay đắng|cô lập|phê bình gắt',
  'Bạn đang nhìn mọi việc rất tỉnh táo, thẳng thắn và độc lập, không dễ bị những điều vô nghĩa đánh lừa. Thêm chút ấm áp khi nói ra sự thật nhé.',
  'Bạn đang cần sự độc lập, sự thẳng thắn và những ranh giới rõ ràng.',
  'Bạn đang phán đoán sáng suốt và trao đổi thẳng thắn. Hãy dẫn dắt bằng sự chính trực.',
  'Bạn đang học theo lối phân tích và rất có kỷ luật.',
  'Bạn đang đưa ra những quyết định tài chính rõ ràng, không để cảm xúc chi phối.',
  'Nói thật, bằng một tấm lòng tử tế.'],
'swords-c3': ['uy quyền|trí tuệ|sự thật|kỷ luật', 'thao túng|độc tài|lạnh|lạm quyền',
  'Bạn đang mang uy quyền của trí tuệ: nguyên tắc rõ ràng, phán xét công minh và một cái đầu vững vàng. Hãy dùng nó để giữ sự công bằng.',
  'Bạn đang ở bên một người lý trí và có nguyên tắc, và những cam kết giữa hai bạn rất rõ ràng.',
  'Bạn đang dẫn dắt bằng chuyên môn vững và sự công tâm.',
  'Bạn đang làm chủ môn học nhờ kỷ luật và tư duy logic.',
  'Bạn đang lên kế hoạch tài chính một cách lý trí và bài bản.',
  'Hãy quyết định bằng lý lẽ và sự công bằng.'],

'pentacles-1': ['cơ hội|thịnh vượng|khởi đầu mới|thành quả thật', 'bỏ lỡ|thiếu thốn|kế hoạch kém|tham',
  'Một cơ hội rất cụ thể đang được trao vào tay bạn: nguồn tiền mới, công việc mới, một điều có thật. Cứ đón lấy nó.',
  'Bạn đang bắt đầu một mối quan hệ mới vững vàng và có tương lai. Không chỉ là rung động, mà là thật lòng.',
  'Bạn đang nhận một công việc, hợp đồng hay dự án mới, vững chắc và nhiều triển vọng.',
  'Một cơ hội thực tế đang mở ra: một suất học bổng, một khóa học hay một vị trí thực tập.',
  'Bạn đang có thêm nguồn thu mới hoặc một cơ hội tài chính. Nắm lấy nó.',
  'Nhận lấy đồng tiền, vì nó là thật.'],
'pentacles-2': ['cân bằng|thích nghi|xoay xở|linh hoạt', 'quá tải|lộn xộn|căng tiền|rơi bóng',
  'Bạn đang xoay xở cùng lúc nhiều việc mà vẫn giữ được mọi thứ trôi chảy. Cứ linh hoạt như vậy, lúc này vẫn ổn.',
  'Bạn đang cố cân bằng giữa tình yêu và những bận rộn khác. Chủ động dành thời gian cho nhau.',
  'Bạn đang làm nhiều dự án cùng lúc. Sắp xếp việc nào cần trước và giữ sự linh hoạt.',
  'Bạn đang cân bằng giữa việc học và cuộc sống. Thử lên lịch cho cả tuần.',
  'Bạn đang xoay vòng dòng tiền. Lập ngân sách thật cẩn thận.',
  'Cứ giữ nhịp như vậy, nhưng đừng gồng mãi.'],
'pentacles-3': ['làm việc nhóm|tay nghề|học hỏi|chất lượng', 'thiếu phối hợp|chất lượng kém|không được ghi nhận|làm một mình',
  'Tay nghề của bạn đang được ghi nhận và ngày càng vững. Sự phối hợp và khéo léo đang mang lại kết quả.',
  'Hai bạn đang cùng nhau vun đắp mối quan hệ, từng bước một.',
  'Bạn đang phối hợp tốt, tay nghề được công nhận và làm ra những sản phẩm chất lượng. Thời điểm rất tốt cho dự án nhóm.',
  'Bạn đang học hỏi từ người khác, và kỹ năng lên dần nhờ chăm chỉ luyện tập.',
  'Tiền đang đến từ tay nghề và sự hợp tác của bạn.',
  'Làm cho thật tốt, cùng với mọi người.'],
'pentacles-4': ['an toàn|kiểm soát|tiết kiệm|ổn định', 'tham|tích trữ|sợ mất|chiếm hữu',
  'Bạn đang giữ khư khư những gì mình có. An toàn là quan trọng, nhưng nắm quá chặt thì mọi thứ sẽ ngừng lưu thông.',
  'Bạn đang có chút chiếm hữu hoặc sợ mất ai đó. Thử nới lỏng tay một chút.',
  'Bạn đang cố giữ mọi thứ an toàn và trong tầm kiểm soát. Đừng chống lại mọi sự thay đổi.',
  'Bạn đang học theo lối quen thuộc và chắc chắn. Đừng ngại thử cách học mới.',
  'Bạn đang tiết kiệm và giữ an toàn. Cân bằng lại một chút với sự rộng rãi.',
  'Giữ lấy điều quan trọng, nới lỏng phần còn lại.'],
'pentacles-5': ['khó khăn|lo âu|lẻ loi|bền bỉ', 'cô lập|tâm lý thiếu thốn|từ chối giúp đỡ|tuyệt vọng',
  'Bạn đang đi qua một giai đoạn chật vật, dễ thấy mình lẻ loi và bị bỏ lại phía sau. Nhưng sự giúp đỡ ở gần hơn bạn nghĩ, chỉ cần bạn mở lời.',
  'Bạn đang thấy cô đơn, như thể chẳng có ai bên cạnh. Thay vì lặng lẽ chịu đựng, thử tìm đến một người mình tin cậy.',
  'Công việc đang bấp bênh và chuyện tiền nong làm bạn căng thẳng. Đây là lúc nên nhờ đến sự hỗ trợ, đừng cố gồng một mình.',
  'Bạn đang xoay xở trong cảnh thiếu thốn, từ tài liệu đến thời gian. Cứ mạnh dạn nhờ thầy cô hay bạn bè giúp một tay.',
  'Tài chính đang eo hẹp. Đừng ngại tìm người hỗ trợ, vì giai đoạn này rồi sẽ qua.',
  'Sự giúp đỡ ở ngay trước mặt, bạn chỉ cần lên tiếng.'],
'pentacles-6': ['rộng lượng|cho đi|công bằng|sẻ chia', 'điều kiện kèm|nợ|bất bình đẳng|lệch quyền lực',
  'Chuyện cho và nhận quanh bạn đang cân bằng. Sự rộng lượng và công bằng đều đang hiện diện.',
  'Mối quan hệ của bạn có sự rộng lượng và nâng đỡ lẫn nhau. Thử nhìn lại xem cho và nhận đã cân bằng chưa.',
  'Bạn đang được trả công xứng đáng, được chỉ dẫn và hỗ trợ. Vừa nhận, vừa biết cho đi.',
  'Bạn đang được thầy cô hay bạn bè giúp đỡ. Chia sẻ lại những gì mình biết cho người khác.',
  'Tiền đang đến nhờ lòng tốt của ai đó, hoặc bạn đang có dịp để giúp người khác.',
  'Cho đi những gì mình có thể, và nhận lấy những gì mình cần.'],
'pentacles-7': ['kiên nhẫn|đánh giá|nhìn đường dài|bền bỉ', 'nóng vội|chưa có quả|bực bội|đầu tư kém',
  'Bạn đã gieo hạt và giờ là lúc chờ đợi. Cứ theo dõi cây lớn lên, nhưng đừng đào hạt lên để xem.',
  'Bạn đang nhìn lại mối quan hệ và tự hỏi những gì mình vun đắp có đang đơm hoa kết trái không.',
  'Bạn đang theo đuổi một mục tiêu dài hạn. Kết quả đến chậm nhưng chắc chắn sẽ đến, cứ bình tĩnh đánh giá.',
  'Bạn đang tiến bộ chậm. Cứ kiên trì chăm chút cho việc học.',
  'Bạn đang đầu tư cho đường dài, và việc này cần sự kiên nhẫn.',
  'Cứ để nó lớn lên từ từ.'],
'pentacles-8': ['tay nghề|chăm chỉ|rèn luyện|tận tâm', 'cầu toàn|đơn điệu|thiếu tham vọng|làm ẩu',
  'Bạn đang làm việc tập trung và kiên nhẫn. Kỹ năng được rèn qua từng lần làm lại, và bạn đang giỏi lên mỗi ngày.',
  'Bạn đang vun đắp mối quan hệ bằng sự chăm chút và đều đặn.',
  'Bạn đang tận tâm với nghề và ngày càng thành thạo nhờ luyện tập.',
  'Bạn đang luyện tập đều đặn, và đó chính là cách để kiến thức thấm vào.',
  'Tiền đang đến từ tay nghề và sự chăm chỉ đều đặn của bạn.',
  'Cứ làm đi làm lại cho đến khi thành thạo.'],
'pentacles-9': ['độc lập|tự chủ|sung túc|biết giá trị bản thân', 'làm quá|lệ thuộc|cô lập|hời hợt',
  'Bạn đang tận hưởng sự thoải mái do chính mình tạo ra, tự chủ và vui vì điều đó. Bạn hoàn toàn xứng đáng.',
  'Bạn đang thấy đủ đầy trong tình yêu, hạnh phúc dù đang một mình hay có đôi.',
  'Bạn đang thành công và tự chủ. Cứ tận hưởng thành quả từ công sức của mình.',
  'Bạn đang tự học, tự định hướng và tin vào khả năng của mình.',
  'Bạn đang tự chủ và thoải mái về tài chính.',
  'Tận hưởng những gì mình đã gây dựng.'],
'pentacles-10': ['di sản|của cải|gia đình|an ổn lâu dài', 'gia đình xung đột|mất tiền|bất ổn|nghĩ ngắn',
  'Bạn đang có những giá trị bền vững: gia đình, di sản và những nền móng còn lại lâu dài. Hãy nghĩ cho cả những thế hệ sau.',
  'Bạn đang có một mối quan hệ bền chặt, gắn với gia đình và một tương lai chung.',
  'Bạn đang có thành công lâu dài, sự nghiệp ổn định và những đóng góp bền vững.',
  'Việc học là khoản đầu tư dài hạn của bạn, và gia đình đang ủng hộ.',
  'Bạn đang có của cải, tài sản thừa kế và sự an ổn lâu dài.',
  'Hãy xây cho đường dài.'],
'pentacles-c0': ['chí hướng|ham học|khởi đầu thực tế|thành hình', 'trì hoãn|không tiến|mơ mộng|không theo tới cùng',
  'Bạn đang có một khởi đầu thực tế: một khóa học, một kế hoạch, một bước đi nghiêm túc. Học cho đến nơi đến chốn nhé.',
  'Bạn đang có một mối kết nối mới thực tế và có gốc rễ. Chậm thôi nhưng thật lòng.',
  'Bạn đang nhận một công việc mới, một khóa đào tạo hoặc một cơ hội rất thực tế.',
  'Bạn đang bắt đầu một khóa học mới với thái độ nghiêm túc.',
  'Bạn đang đặt ra một mục tiêu tài chính mới. Bắt đầu để dành từ bây giờ.',
  'Bắt đầu thôi, và học cho đến nơi đến chốn.'],
'pentacles-c1': ['đáng tin|nề nếp|chăm chỉ|trách nhiệm', 'chán|ứ đọng|cứng đầu|cầu toàn',
  'Bạn đang chậm rãi, đáng tin cậy và làm việc có phương pháp. Không mấy hào hứng, nhưng việc gì bạn làm cũng đến nơi đến chốn, và đó chính là điểm mạnh.',
  'Bạn đang ở bên một người đáng tin và chung thủy, với một tình yêu chậm rãi mà bền lâu.',
  'Bạn đang làm việc bài bản, và chính sự đáng tin cậy đang giúp bạn thành công.',
  'Bạn đang giữ nếp học đều đặn, chậm mà chắc.',
  'Bạn đang chọn những cách dùng tiền an toàn và thận trọng.',
  'Cứ đi tiếp, đều đặn như vậy.'],
'pentacles-c2': ['chăm lo|thực tế|sung túc|an toàn', 'làm quá sức|bỏ bê mình|bao bọc|vật chất',
  'Bạn đang chăm lo cho mọi người một cách thực tế và giúp họ thấy yên tâm. Nhớ chăm lo cho cả chính mình nữa.',
  'Bạn đang có một người thương biết chăm lo và thực tế, cùng một mái ấm dễ chịu.',
  'Bạn đang quản lý mọi việc rất thực tế và luôn lo cho cả nhóm.',
  'Bạn đang học có tổ chức và rất vững vàng.',
  'Bạn đang quản lý tiền bạc thực tế mà vẫn rộng rãi.',
  'Chăm lo cho mình như cách bạn chăm lo cho mọi người.'],
'pentacles-c3': ['sung túc|dẫn dắt|vững vàng|kỷ luật', 'tham|vật chất|cứng đầu|kiểm soát bằng tiền',
  'Bạn đang làm chủ đời sống vật chất, với sự ổn định và khả năng lo toan mà người khác có thể dựa vào.',
  'Bạn đang ở bên một người vững vàng, biết lo toan và rộng lượng, và tình yêu của hai bạn rất yên ổn.',
  'Bạn đang thành công trong kinh doanh và dẫn dắt bằng uy tín của mình.',
  'Bạn đang làm chủ một môn thực hành nhờ tính kỷ luật.',
  'Bạn đang có của cải và làm chủ được tài chính của mình.',
  'Gây dựng của cải, nhưng giữ lấy tấm lòng rộng lượng.']
});
Object.assign(INSIGHT.en, {
'wands-1': ['spark|inspiration|new energy|desire', 'false start|no direction|delay|burnout',
  'Something in you wants to make, start and build. The energy is still raw and unaimed, so give it a direction.',
  'A new attraction or a new passion has just sparked. Enjoy it, but remember that a spark is not yet a promise.',
  'A new idea or offer is arriving, and there is real energy behind it. Start now.',
  'A new subject has caught your interest. Make the most of it before the excitement cools.',
  'A new way to earn is taking shape. Try it on a small scale first.',
  'Light the fire first, and build the hearth afterwards.'],
'wands-2': ['planning|vision|choice|bold horizons', 'playing it safe|fear of the unknown|plans that never launch',
  'Something is already in your hands, and your eyes are on what lies beyond it. It is time to choose the wider horizon over the familiar one.',
  'What do you really want from love? Right now you may be weighing comfort against something bolder.',
  'You are planning an expansion, a partnership, or the next step. Think big, then commit to one direction.',
  'A direction or a specialisation is waiting to be chosen. Plan for the year, not just the week.',
  'An investment is on your mind. Weigh safety against growth.',
  'Decide the direction first; the details can come later.'],
'wands-3': ['expansion|foresight|progress|waiting well', 'delay|impatience|thinking too small|no follow-through',
  'Your first efforts are out in the world and already working. Now comes the waiting, and getting ready for what comes back.',
  'What you set in motion is developing. Give it time, and do not rule out a connection from far away.',
  'Your work is growing and opening new markets thanks to earlier effort. Keep your eyes on the horizon.',
  'Your groundwork is done, and the results are on their way.',
  'Your earlier investment is starting to return. Patience is paying off.',
  'Watch the horizon, not the clock.'],
'wands-4': ['celebration|home|stability|community', 'instability|tension at home|cancelled plans|feeling unwelcome',
  'A milestone, a homecoming, a reason to gather: this is joy with a solid floor beneath it.',
  'This may be a commitment, moving in together, or a celebration with the people you love.',
  'Your team has hit a milestone, or you are in a stable and supportive workplace. Celebrate it.',
  'You have reached a milestone. A study group or a supportive setting is carrying you forward.',
  'Your finances are stable, and a purchase for the home makes sense right now.',
  'Mark the milestone, and then let yourself rest.'],
'wands-5': ['competition|debate|energy|testing', 'conflict|chaos|arguing for nothing|avoiding the fight',
  'Many energies are clashing around you: opinions, egos, plans. It is not dangerous, only noisy, so compete fairly.',
  'Bickering, rivalry, or too many differences at once. Save the arguments for what really matters.',
  'The workplace is competitive and full of clashing views, and it is hard to be heard. Stay in the game.',
  'Your study environment is competitive, or your focus is split. Pick one battle.',
  'Several needs are competing for the same money. Sort out your priorities.',
  'Pick the fight worth having and let the rest go.'],
'wands-6': ['victory|recognition|confidence|progress', 'ego|fall from grace|no recognition|hollow win',
  'A win of yours is being noticed. You are ahead and people can see it, so enjoy the recognition.',
  'Someone admires you, and the relationship is one you feel proud of.',
  'A promotion, praise, or public success is coming. Accept it graciously.',
  'Good results are coming, and so is recognition. Your confidence is well earned.',
  'A reward or a financial win is on its way.',
  'Take the applause, then keep moving forward.'],
'wands-7': ['defence|perseverance|courage|standing your ground', 'giving up|exhaustion|feeling overwhelmed|defensiveness',
  'Pressure is coming from several sides, and you are holding your ground. It is tiring, but the high ground is yours.',
  'Your relationship, or your own needs, need defending. Stand firm without going to war.',
  'Your position is being competed for or challenged. Hold your ground with skill.',
  'The pressure is on and you are being tested. Keep going: you are stronger than the doubt.',
  'Protect what you have from outside demands, and learn to say no.',
  'Hold the line, but remember to breathe while you do it.'],
'wands-8': ['speed|news|movement|momentum', 'delays|chaos|rushed decisions|miscommunication',
  'Everything is moving fast: messages, travel, sudden progress. Keep up, and keep your head clear.',
  'Things are developing quickly, with messages flying back and forth. Reply while it matters.',
  'Work is moving fast, news is arriving, and travel is possible. Act quickly on offers.',
  'Progress is fast, and so is the approaching deadline. Start now.',
  'Money is moving quickly, both opportunities and expenses. Keep an eye on both.',
  'Act fast, but keep your head cool.'],
'wands-9': ['resilience|persistence|caution|last push', 'paranoia|exhaustion|refusing help|defensiveness',
  'Tired as you are, you are almost there. Guard what you have built and take the last step.',
  'An old hurt has made you wary. Protect yourself, but do not wall everyone out.',
  'The hard stretch is nearly behind you. Hold on a little longer and set clear boundaries.',
  'This is the final push before the exam or the deadline. Keep your routine.',
  'Protect your savings and be cautious with new commitments.',
  'Take one more step, and then rest properly.'],
'wands-10': ['responsibility|burden|hard work|determination', 'overload|burnout|carrying others|no delegation',
  'You are carrying a great deal, perhaps too much. The load is real, but so is your strength, and one thing can be put down.',
  'All the emotional work in the relationship seems to be falling on you. Share the weight.',
  'Too many duties, too little time. Hand something over, or let it go.',
  'Your schedule is overloaded. Cut it down to what matters.',
  'Your financial obligations are heavy. Find ways to simplify them.',
  'Put one thing down today.'],
'wands-c0': ['enthusiasm|exploration|messages|a fresh idea', 'lack of direction|impatience|immaturity|delays',
  'Curious, eager and a little restless: a new idea or message is on its way, so explore it.',
  'Someone is flirting, a sweet message arrives, or a playful, young-at-heart person appears. It is fun, but not serious yet.',
  'A new idea, a trainee role, or exciting news about work.',
  'Curiosity is your best tool right now. Explore new topics.',
  'A new money idea is forming. Research it before you invest.',
  'Follow the spark and see where it leads.'],
'wands-c1': ['action|passion|adventure|charisma', 'recklessness|impulsiveness|arrogance|leaving too soon',
  'Bold, fast, charming and impatient, you are ready to charge. Take aim before you go.',
  'You are meeting a passionate person, or living through a passionate phase yourself. It is exciting, though not always reliable.',
  'Bold moves, travel, taking charge: all good, as long as you watch the impulsiveness.',
  'Your energy comes in bursts. Channel them into a plan.',
  'A bold financial move is tempting. It is risky, so check the details.',
  'Charge ahead, but know where the cliff is.'],
'wands-c2': ['warmth|confidence|independence|magnetism', 'jealousy|demanding|drama|burnout',
  'Your energy is warm, confident, and magnetic. You are attracting attention, so use it well.',
  'A warm, confident partner, or your own easy self-assurance, is shining through.',
  'You are leading with warmth and inspiring the team.',
  'You are learning with confidence and setting your own course.',
  'You are managing money with confidence and independence.',
  'Shine, and let others shine too.'],
'wands-c3': ['vision|leadership|boldness|entrepreneurship', 'tyranny|impatience|high expectations|ruthlessness',
  'Big-picture, bold leadership energy is with you, and the direction is yours to set. Lead by inspiring, not by ordering.',
  'You are with a charismatic, driven partner, or you are the one leading in love.',
  'You are leading the project with both vision and action.',
  'Take charge of your own learning path.',
  'You handle money like an entrepreneur: bold, but calculated.',
  'Lead from the front, with heart.'],

'cups-1': ['new love|emotional beginning|compassion|creativity', 'emptiness|blocked feelings|self-love missing|emotional overflow',
  'Your heart is opening to a new feeling, a new compassion, or a creative beginning. Receive it.',
  'A new love is arriving, or an old feeling is being renewed. You are more open than ever.',
  'Work feels emotionally rewarding right now, with a creative start and good people around you.',
  'Learning has become a joy, and a creative subject is calling you.',
  'Money is coming from something you love, and generosity is flowing around you.',
  'Let the cup fill.'],
'cups-2': ['partnership|mutual attraction|connection|balance', 'imbalance|break-up|miscommunication|one-sided',
  'A real connection is forming between you and someone else. Respect and attraction are flowing both ways.',
  'A strong, mutual bond, or a meeting that truly means something.',
  'A good business partnership, or a working relationship built on trust.',
  'A study partner or mentor who suits you has come along.',
  'A financial partnership that is fair to both sides.',
  'Meet the other person halfway, and it will work.'],
'cups-3': ['friendship|celebration|community|creativity', 'gossip|overindulgence|a third person|isolation',
  'The energy around you is joyful and social, full of friends, gatherings and shared happiness.',
  'Friends and good times are around you. But if a third person is in the picture, take a closer look.',
  'The team is working well together, celebrating results, or starting a creative collaboration.',
  'Group study is working well for you. Celebrate the small wins.',
  'Your social life is costing a fair bit. Enjoy it, in moderation.',
  'Call a friend today.'],
'cups-4': ['contemplation|apathy|re-evaluation|boredom', 'missed opportunity|withdrawal|ingratitude|numbness',
  'Flat, unimpressed and unsure of what you want: that is how it feels. Yet an offer is right in front of you, unnoticed, so look up.',
  'Boredom or emotional distance has crept in, and something good is being overlooked.',
  'Dissatisfaction may have made you miss a chance. Take another look at what you really want.',
  'Motivation has slipped. Try a different approach.',
  'You may have missed a financial opportunity. Pay closer attention.',
  'Look at what is being offered before you refuse it.'],
'cups-5': ['grief|regret|loss|acceptance', 'refusing to move on|self-pity|dwelling|isolation',
  'The loss is real, and so is the sadness. But not everything has spilled: two cups are still standing.',
  'Disappointment or loss in love. Let yourself grieve, and then turn around.',
  'A setback or a disappointment. Learn from it and move on.',
  'A poor result, but not the end. Turn to what remains.',
  'Some money has been lost. Take stock of what is left.',
  'Turn around, because two cups are still full.'],
'cups-6': ['nostalgia|innocence|kindness|the past', 'stuck in the past|naivety|unrealistic memories|clinging',
  'Sweet memories, kindness, and something innocent are returning. The past is visiting you gently.',
  'An old flame, a childhood sweetness, or a simple affection is showing up.',
  'An old contact returns, or kindness finds you at work.',
  'Go back to the basics: what you learned before is helping you now.',
  'A gift, or money from the past, is coming.',
  'Enjoy the memory, but live in the present.'],
'cups-7': ['choices|imagination|dreams|possibilities', 'illusion|wishful thinking|too many options|escapism',
  'So many options, so many daydreams, and not all of them real. Choose with clear eyes.',
  'Fantasy and reality are blurring in love, and you may be idealising someone. See them as they are.',
  'Too many possibilities, not enough focus. Pick one realistic path.',
  'Distraction and daydreaming are getting in the way. Pick one thing and do it.',
  'Dreaming about money will not change it. Sit down and do the maths.',
  'Choose one cup, with your eyes open.'],
'cups-8': ['walking away|seeking more|letting go|a deeper search', 'fear of change|aimlessness|running away|staying too long',
  'Something is being left behind so you can find something deeper. It is a loss and a liberation at once.',
  'Walking away from what no longer fulfils you is hard, and it is right.',
  'A job or role is being left behind for something more meaningful.',
  'A change of direction. Leave behind what does not fit.',
  'You are getting out of a financial situation that has been draining you.',
  'Go, because what you seek is not here.'],
'cups-9': ['satisfaction|contentment|wishes granted|pleasure', 'smugness|overindulgence|shallow happiness|dissatisfaction',
  'Your wish is coming true, with comfort and pleasure alongside it. You have what you asked for, so enjoy it.',
  'Love feels satisfying and full of joy right now.',
  'Achievement and real satisfaction at work.',
  'Success, and results you are happy with.',
  'Your finances are comfortable. Treat yourself, wisely.',
  'Enjoy it, because you asked and it came.'],
'cups-10': ['harmony|family|lasting happiness|belonging', 'broken family|disharmony|unrealistic expectations|neglect',
  'A deep, shared and lasting happiness: family, home and hearts that feel full.',
  'A loving, committed relationship, and a family in harmony.',
  'Fulfilling work, and good relationships with colleagues.',
  'Your family is supporting your studies.',
  'Your family has financial security.',
  'This is the good thing, so hold it gently.'],
'cups-c0': ['creativity|intuition|a message of feeling|sensitivity', 'emotional immaturity|moodiness|creative block|escapism',
  'A gentle, imaginative message or impulse is reaching you. Something new is stirring quietly in your heart.',
  'A sweet message, a new crush, or a tender beginning.',
  'A creative idea, or a message at work that touches your heart.',
  'Intuition is a good guide for your learning, and art or creative work suits you.',
  'A small, unexpected gift is coming.',
  'Listen to the small feeling.'],
'cups-c1': ['romance|charm|following the heart|idealism', 'moodiness|unrealistic|jealousy|deception',
  'Romantic, charming and idealistic, you are following your heart. Just check your feet are still on the ground.',
  'A romantic proposal or a charming suitor. Enjoy it, but watch for illusions.',
  'Creative projects, handled with tact and grace.',
  'Inspiration is carrying your studies, especially art, music and literature.',
  'Spending is being driven by feelings. Pause for a moment before you buy.',
  'Follow your heart with open eyes.'],
'cups-c2': ['compassion|calm|intuition|emotional security', 'insecurity|co-dependence|martyrdom|overwhelmed',
  'Calm, caring and intuitive, you understand others and yourself. Remember to care for yourself too.',
  'You have a nurturing, loving partner, or your own emotional maturity is leading the way.',
  'Empathy and intuition are guiding your work, and colleagues can lean on you.',
  'Understanding, not memorising, is how you learn best right now.',
  'Your money choices are intuitive and keep your security in mind.',
  'Care for others, but keep some care for yourself.'],
'cups-c3': ['emotional balance|diplomacy|wisdom|compassion', 'emotional manipulation|moodiness|volatility|coldness',
  'Your feelings are strong, but they are held with maturity and wisdom.',
  'A mature, emotionally balanced partner, and a love with plenty of compassion.',
  'Leadership with diplomacy and calm, handling people with care.',
  'A balanced, sensible approach to your studies.',
  'Money managed in a balanced, sensible way.',
  'Feel deeply, but act calmly.'],

'swords-1': ['clarity|truth|breakthrough|a new idea', 'confusion|misuse of power|harsh words|clouded judgement',
  'A moment of clarity: the truth cuts through everything. New ideas are coming, and your thinking is decisive.',
  'Honest conversations, and a clear view of what you want.',
  'A breakthrough idea, and decisions made with a clear head.',
  'Your thinking is sharp and you have just understood something new.',
  'A clear head about money, and a decisive plan.',
  'Say the true thing, kindly.'],
'swords-2': ['indecision|stalemate|weighing options|truce', 'avoidance|denial|paralysis|hiding',
  'Stuck between two options, you are putting off the choice. The blindfold is yours, and you can take it off.',
  'A decision about the relationship is being avoided. It is time to face it.',
  'Stalemate, or a decision being dodged. Gather the facts, then choose.',
  'Torn between choices? Pick one and go.',
  'A financial decision is on hold. Make it.',
  'Take off the blindfold and choose.'],
'swords-3': ['heartbreak|grief|painful truth|release', 'holding on to pain|bitterness|self-inflicted hurt|refusing to heal',
  'A sharp pain, usually from a hard truth or a loss. It hurts, but it also brings clarity, so do not hold it in.',
  'Heartbreak, betrayal, or a painful truth. Feel it, and then let it heal.',
  'A painful setback or harsh criticism. Learn from it, then pick yourself up.',
  'Disappointment hurts, but it will pass.',
  'A financial loss that stings. Recover, and rebuild.',
  'Let the tears come, and then the healing.'],
'swords-4': ['rest|recovery|contemplation|retreat', 'burnout|restlessness|isolation|avoiding action',
  'You need rest. This is a time to retreat, recover and think, not a time to fight.',
  'The relationship is in a quiet pause. Use it to recover your energy.',
  'Take a break and recover before the next challenge.',
  'Rest before you study more, because your mind needs it.',
  'Pause all money matters and review them quietly.',
  'Rest. Really rest.'],
'swords-5': ['conflict|defeat|winning at a cost|tension', 'hostility|bullying|no-win situation|humiliation',
  'A conflict where nobody really wins. Ask yourself whether this battle is worth it.',
  'Hurtful words are flying. Winning the argument may cost you the relationship.',
  'Conflict at work, or a victory that feels hollow. Choose your battles.',
  'Competitiveness is hurting you. Focus on your own path.',
  'A dispute over money. Do not fight over the small things.',
  'Walk away from the fight you cannot win, with grace.'],
'swords-6': ['transition|moving on|healing|calmer waters', 'stuck|unfinished baggage|resisting change|rough passage',
  'Rough water is giving way to calmer water. This is a quiet, necessary transition.',
  'Moving on from difficulty and healing, perhaps with some distance.',
  'A move to a better situation, and possibly some travel.',
  'The difficult phase is passing, and progress is showing.',
  'Your finances are recovering gradually.',
  'Row toward the calm, because it is right there.'],
'swords-7': ['strategy|cunning|independence|getting away with it', 'deception|theft|self-deception|getting caught',
  'Strategy, quiet work, going it alone. Sometimes that is clever and sometimes it is sneaky, so check your motives.',
  'There is secrecy or deception in the relationship. Honesty is safer.',
  'Working strategically and independently, or dealing with someone who is not being straight with you.',
  'Shortcuts are tempting. Be careful they do not backfire.',
  'Watch out for scams, and be strategic with money.',
  'Be clever, but not sneaky.'],
'swords-8': ['feeling trapped|restriction|self-limiting beliefs|helplessness', 'victim mentality|paralysis|imprisonment|self-sabotage',
  'You feel trapped, but the bonds are looser than they look. The prison is mostly in your mind.',
  'The relationship feels like a trap, but you have more choice than you think.',
  'Work feels restrictive. Look for the way out you have not spotted yet.',
  'Overwhelmed? Break the task into small steps.',
  'Your money feels restricted. Look for other options.',
  'The ropes are loose, so move.'],
'swords-9': ['anxiety|worry|nightmares|guilt', 'despair|hopelessness|catastrophising|isolation',
  'Worry is keeping you up at night, but most of the fear is bigger than the facts. Reach out to someone.',
  'Anxiety about the relationship is growing. Talk it through instead of spiralling.',
  'Work stress and worry are piling up. Check what is really going on.',
  'Exam nerves. Prepare well, then get some sleep.',
  'Money worries. Make a plan, and do not carry it alone.',
  'Turn on the light, and the monsters shrink.'],
'swords-10': ['rock bottom|ending|betrayal|the worst is over', 'recovery|resisting the end|dramatising|survival',
  'A painful ending has fully arrived, and it is done. Because it is done, the dawn is coming.',
  'A painful, final ending. Grieve, then heal: the worst is over.',
  'A project or job has ended badly. Recover and start fresh.',
  'One failure, one lesson learned. Now move on.',
  'Your finances are at a low point, and from here the only way is up.',
  'It is over, and now you can rise.'],
'swords-c0': ['curiosity|vigilance|new ideas|communication', 'gossip|hasty words|scattered thinking|spying',
  'Alert, curious and talkative: new ideas and messages are arriving. Just watch your words.',
  'Curious messages and playful debate. But if gossip starts, be careful.',
  'New ideas, lots of communication, and a watchful eye.',
  'A curious mind is helping you dig in and ask good questions.',
  'Watch out for rumours and hasty decisions about money.',
  'Ask the question, then listen.'],
'swords-c1': ['ambition|action|directness|speed', 'aggression|impatience|recklessness|ruthlessness',
  'Fast, sharp and decisive, you are charging in. Make sure you are heading the right way.',
  'Someone direct and fast, or a rushed decision. Slow down a little.',
  'Rapid decisions and bold moves. Watch out for haste.',
  'An intense study push: effective, but exhausting.',
  'Fast money moves. Weigh the risk first.',
  'Charge ahead, but check the map first.'],
'swords-c2': ['independence|clear judgement|honesty|boundaries', 'coldness|bitterness|isolation|harsh criticism',
  'Clear-eyed, honest and independent, you see straight through nonsense. Add some warmth to the truth.',
  'Independence, honesty and clear boundaries are what you need right now.',
  'Clear judgement and direct communication. Lead with integrity.',
  'An analytical, disciplined way of studying suits you now.',
  'Clear, unsentimental decisions about money.',
  'Tell the truth with kindness.'],
'swords-c3': ['authority|intellect|truth|discipline', 'manipulation|tyranny|coldness|abuse of power',
  'The authority of a clear mind is with you: fair rules, fair judgement, sharp thinking. Use it justly.',
  'A logical, principled partner, and a commitment that is clear.',
  'Leadership built on expertise and fairness.',
  'Discipline and logic are how you are mastering this subject.',
  'Rational, well-structured financial planning.',
  'Decide with reason and fairness.'],

'pentacles-1': ['opportunity|prosperity|new venture|manifestation', 'missed chance|scarcity|poor planning|greed',
  'A concrete opportunity is being handed to you: new money, a new venture, something real. Take it.',
  'A stable, promising new relationship is beginning. It is real, not just exciting.',
  'A new job, contract or venture is coming your way, solid and full of promise.',
  'A practical new opportunity has opened: a scholarship, a course, or a position.',
  'New income or a financial opportunity is here. Seize it.',
  'Take the coin, because it is real.'],
'pentacles-2': ['balance|adaptability|juggling|flexibility', 'overwhelm|disorganisation|financial stress|dropping the ball',
  'Several things are in the air at once, and you are keeping them all up. Stay flexible: for now, it works.',
  'Love is competing with other demands. Make time for each other on purpose.',
  'Several projects are running at once. Prioritise, and stay adaptable.',
  'Study and the rest of life both want your time. Plan the week.',
  'Cash flow is a juggling act right now. Budget carefully.',
  'Keep the balls in the air, but not forever.'],
'pentacles-3': ['teamwork|skill|learning|quality', 'lack of teamwork|poor quality|no recognition|working alone',
  'Your skill is being recognised and built upon. Collaboration and craftsmanship are paying off.',
  'The two of you are building the relationship together, step by step.',
  'Good collaboration, recognised skill and quality work. A good time for team projects.',
  'Learning from others and practising is steadily improving your skill.',
  'Money is coming from your skill and cooperation.',
  'Do the work well, with others.'],
'pentacles-4': ['security|control|saving|stability', 'greed|hoarding|fear of loss|possessiveness',
  'What you have is being held very tightly. Security matters, but grip too hard and the flow stops.',
  'Possessiveness, or a fear of losing someone, is showing. Loosen your grip a little.',
  'Job security and control feel important. Just do not resist every change.',
  'A steady, safe way of studying suits you. Do not be afraid of new methods.',
  'Saving and staying secure is wise. Balance it with a little generosity.',
  'Hold what matters, and loosen the rest.'],
'pentacles-5': ['hardship|worry|feeling left out|resilience', 'isolation|poverty mentality|refusing help|despair',
  'A hard patch has left you feeling out in the cold. But help is nearer than it seems, so ask for it.',
  'Loneliness, or a lack of support, is weighing on you. Reach out instead of suffering in silence.',
  'Job insecurity or money strain is making work stressful. Look for support.',
  'A lack of resources is making study a struggle. Ask for help.',
  'Money is tight. Look for help, because this will pass.',
  'Help is right there. All you have to do is ask.'],
'pentacles-6': ['generosity|charity|balance|sharing', 'strings attached|debt|inequality|power imbalance',
  'Giving and receiving are in balance around you. Generosity is flowing, and so is fairness.',
  'The relationship has generosity and support in it. Check that giving and taking are in balance.',
  'Fair pay, good mentoring, real support. Give back as well as receive.',
  'Teachers or friends are helping you. Share what you know in return.',
  'Money is coming through generosity, or you have a chance to give.',
  'Give what you can, and receive what you need.'],
'pentacles-7': ['patience|assessment|long-term view|perseverance', 'impatience|lack of reward|frustration|poor investment',
  'The work is done, and now comes the waiting. Check how things are growing, but do not dig up the seeds.',
  'It may be time to ask whether what you are putting into the relationship is growing into something.',
  'A long-term effort. Results are slow but coming, so judge them calmly.',
  'Progress is slow. Keep tending your studies.',
  'Long-term investments need patience.',
  'Let it grow at its own pace.'],
'pentacles-8': ['craft|diligence|skill-building|dedication', 'perfectionism|monotony|lack of ambition|cutting corners',
  'Focus and patience are your tools right now. Skill is built one repetition at a time, and you are getting good.',
  'Care and consistency are what is making the relationship grow.',
  'Dedication to your craft is turning practice into mastery.',
  'Steady, repeated practice is exactly how it sticks.',
  'Money is coming from your skill and steady work.',
  'Do the repetitions.'],
'pentacles-9': ['independence|self-sufficiency|luxury|self-worth', 'over-work|dependence|isolation|superficiality',
  'A comfort you created yourself: independence, and the pleasure it brings. You have earned this.',
  'Self-sufficient in love, you are happy whether alone or with someone.',
  'Success and independence. Enjoy the rewards of your work.',
  'You are steering your own learning, confident in what you can do.',
  'Financially independent and comfortable.',
  'Enjoy what you built.'],
'pentacles-10': ['legacy|wealth|family|long-term security', 'family conflict|financial loss|instability|short-term thinking',
  'Lasting wealth: family, legacy, and foundations that will outlast you. Think in generations.',
  'A lasting relationship, with family ties and a shared future.',
  'Long-term success, a stable career, and a contribution that lasts.',
  'Your education is a long-term investment, and your family supports it.',
  'Wealth, inheritance and long-term security.',
  'Build for the long run.'],
'pentacles-c0': ['ambition|study|a practical start|manifestation', 'procrastination|lack of progress|daydreaming|no follow-through',
  'A practical new beginning: a course, a plan, a first step taken seriously. Learn it properly.',
  'A practical, grounded new connection. Slow, and real.',
  'A new job, some training, or a practical opportunity is coming.',
  'A new course, started with a serious attitude.',
  'A new financial goal. Start saving now.',
  'Start, and learn it properly.'],
'pentacles-c1': ['reliability|routine|hard work|responsibility', 'boredom|stagnation|stubbornness|perfectionism',
  'Slow, reliable and methodical: not exciting, but everything gets finished, and that is its gift.',
  'A reliable, steady partner, and a slow-burning love you can depend on.',
  'Methodical work, and a reliability that is paying off.',
  'A consistent routine, slow and steady.',
  'Conservative, safe choices with money.',
  'Keep going, steadily.'],
'pentacles-c2': ['nurturing|practicality|abundance|security', 'overwork|self-neglect|smothering|materialism',
  'Caring for people in practical ways, you help them feel safe. Remember to look after yourself too.',
  'A nurturing, practical partner, and a home full of comfort.',
  'Practical management, and real care for the team.',
  'A grounded, well-organised way of studying.',
  'Money managed practically, and generously.',
  'Care for yourself as well as everyone else.'],
'pentacles-c3': ['wealth|leadership|security|discipline', 'greed|materialism|stubbornness|control through money',
  'Mastery of the material world, with a stability and security others can rely on.',
  'A stable, generous partner, and a love that feels secure.',
  'Success in business, and leadership built on reliability.',
  'Discipline is how you are mastering a practical subject.',
  'Wealth, and full command of your finances.',
  'Build wealth, and stay generous.']
});
