/* ============================ card insights, Vietnamese ============================
   Viết riêng bằng tiếng Việt, không dịch từ bản tiếng Anh. Câu ngắn, dễ hiểu.
   Fields: [từ khóa tích cực, từ khóa mặt trái, năng lượng lúc này, tình cảm,
   công việc, học tập, tiền bạc, lời khuyên]. Từ khóa cách nhau bằng "|". */
Object.assign(INSIGHT.vi, {
'major-0': ['khởi đầu mới|cởi mở|dũng cảm|dám bước', 'bất cẩn|ngây thơ|không có kế hoạch|trốn trách nhiệm',
  'Một cánh cửa mới vừa mở ra trước mặt bạn. Lúc này cảm giác hồi hộp lấn át sự chắc chắn, và điều đó hoàn toàn tự nhiên. Lá bài khuyến khích bạn đặt niềm tin vào bước chân đầu tiên.',
  'Trong chuyện tình cảm, bạn có thể sắp gặp một người mới, đón một rung động mới, hoặc bạn đã đủ nhẹ lòng để yêu mà không còn kéo theo nỗi sợ ngày trước. Bạn hãy tận hưởng giai đoạn này, nhưng chỉ nên hứa những điều bạn thật sự biết rõ.',
  'Công việc đang mở ra một dự án, một vị trí hay một con đường mà bạn chưa có kinh nghiệm. Bạn sẽ học ngay trong lúc làm. Bạn nên đặt câu hỏi từ sớm và đừng ngại hỏi thật nhiều.',
  'Việc học đưa bạn đến một môn mới hoặc một phương pháp mới. Ở giai đoạn này, sự tò mò là động cơ chính, còn tính kỷ luật có thể được bổ sung sau.',
  'Về tiền bạc, bạn có thể đón một nguồn thu mới, hoặc bạn đang muốn chi cho một cuộc phiêu lưu. Trước khi lao đi, bạn nên giữ lại một khoản dự phòng nho nhỏ.',
  'Bạn hãy lên đường, nhưng đừng đi tay không. Bạn nên chuẩn bị một kế hoạch và một phương án rút lui, rồi mới cất bước.'],
'major-1': ['kỹ năng|tập trung|chủ động|biến ý thành việc', 'khoe mẽ|thao túng|tài năng phân tán|nói nhiều làm ít',
  'Mọi dụng cụ cần thiết đã nằm trong tay bạn. Điều đáng hỏi lúc này không còn là bạn có đủ khả năng hay không, mà là bạn có bắt tay vào làm hay không. Năng lượng của bạn đang sắc bén và dồi dào.',
  'Sức hút và khả năng thuyết phục của bạn đang ở mức cao. Bạn nên dùng lợi thế này một cách chân thành. Thay vì để đối phương phải đoán, bạn hãy nói thẳng điều mình mong muốn.',
  'Năng lực của bạn đang lọt vào mắt những người xung quanh. Đây là lúc bạn nên đưa ra ý tưởng, đứng ra điều hành cuộc họp và trực tiếp bắt tay vào việc. Thành quả sinh ra từ hành động chứ không phải từ những phép tính trong đầu.',
  'Trí óc của bạn đang nhạy bén và dễ tập trung. Bạn nên tận dụng ngay giai đoạn thuận lợi này bằng cách ngồi vào bàn học trước khi nó qua đi.',
  'Đây là lúc thuận lợi để bạn chuyển kỹ năng của mình thành thu nhập. Bạn hãy định giá công sức và chủ động gửi lời chào hàng.',
  'Trong vài ngày tới, bạn hãy tập trung toàn bộ nguồn lực vào một mục tiêu duy nhất và quan sát nó bắt đầu chuyển mình.'],
'major-2': ['trực giác|tĩnh lặng|điều còn ẩn|kiên nhẫn', 'bí mật|thu mình|bỏ qua linh cảm|ngồi yên quá lâu',
  'Vẫn còn một phần của câu chuyện chưa được hé lộ. Trực giác của bạn nắm bắt được nhiều hơn những gì các dữ kiện bề ngoài đang bày ra. Giai đoạn này đòi hỏi bạn lắng nghe chứ không phải thúc ép.',
  'Có những cảm xúc đang âm thầm vận động, có thể ở phía bạn hoặc ở phía đối phương. Bạn không nên buộc ai phải bày tỏ. Hành động của họ sẽ cho bạn biết nhiều hơn lời nói.',
  'Ở nơi làm việc, một phần thông tin đang được ai đó giữ kín. Trước khi ra quyết định, bạn nên đọc kỹ những ẩn ý phía sau từng câu chữ.',
  'Lúc này bạn hợp với việc tự học trong không gian yên tĩnh. Mức độ hiểu bài của bạn thật ra sâu hơn những gì điểm số phản ánh.',
  'Bạn nên hoãn việc ký kết và tạm dừng chi tiêu. Còn một chi tiết quan trọng mà người ta chưa nói cho bạn biết.',
  'Bạn hãy gác câu hỏi đó lại trọn một ngày. Câu trả lời thường xuất hiện đúng lúc bạn ngừng thúc giục nó.'],
'major-3': ['sung túc|nuôi dưỡng|dễ chịu|sáng tạo', 'hưởng thụ quá đà|bao bọc quá mức|bí ý tưởng|quên chăm mình',
  'Những gì quanh bạn đang sinh sôi, và chúng cần được vun bón hơn là chỉnh sửa. Bạn hoàn toàn có quyền cảm thấy thư thái. Thứ mà bạn đã dày công chăm sóc đang bước vào mùa chín.',
  'Tình cảm lúc này mang một bầu không khí ấm áp, hào phóng và thân mật. Mối quan hệ của bạn đang đậm sâu hơn, hoặc sự quan tâm của ai đó đang hướng về bạn. Bạn hãy cho phép mình đón nhận.',
  'Một dự án của bạn bắt đầu cho thành quả. Những công việc mang tính sáng tạo đang được hậu thuẫn. Bạn nên hợp sức với đồng nghiệp thay vì đối đầu với họ.',
  'Bạn tiếp thu tốt nhất khi cơ thể được nghỉ ngơi đầy đủ và tinh thần thư giãn. Khi góc học tập được sắp xếp dễ chịu, việc học sẽ tự nhiên trôi chảy.',
  'Dòng tiền đang đổ về thuận lợi hơn thường lệ. Bạn nên chia nó thành ba phần, một phần để tận hưởng, một phần để dành và một phần để san sẻ.',
  'Trong tuần này, bạn nên dành thời gian cho cơ thể và cho tổ ấm của mình. Mọi sự phát triển đều bắt đầu từ việc được chăm sóc tử tế.'],
'major-4': ['cấu trúc|ổn định|dẫn dắt|ranh giới', 'cứng nhắc|kiểm soát|lạnh lùng|không có kỷ luật nào',
  'Lá bài mang tinh thần của kỷ cương và uy quyền. Hoàn cảnh đòi hỏi bạn đặt ra luật lệ, đứng vào vị trí điều hành, hoặc tôn trọng người đang giữ vai trò đó.',
  'Trong tình cảm, sự vững chắc đang được ưu tiên hơn những phút giây bay bổng. Một người đáng tin cậy có thể đang ở bên bạn, hoặc bạn cần vạch ra những giới hạn rõ ràng.',
  'Bạn nên nhận vai trò dẫn dắt hoặc vận hành theo đúng cơ cấu sẵn có. Lúc này kế hoạch, thứ bậc và kỷ luật mang lại kết quả tốt hơn sự ngẫu hứng.',
  'Một thời khoá biểu cố định và những thói quen đều đặn hỗ trợ bạn nhiều hơn là chờ cảm hứng. Bạn hãy xây khung học tập trước rồi lấp nội dung vào sau.',
  'Tiền bạc lúc này cần một ngân sách rõ ràng, sự kiểm soát chặt chẽ và một kế hoạch dài hơi. Sự kỷ luật của bạn sẽ được đền đáp.',
  'Bạn hãy đưa ra quyết định và kiên định với nó. Điều duy nhất cần bảo đảm là quyết định ấy công bằng với mọi người.'],
'major-5': ['truyền thống|chỉ dẫn|học hỏi|thuộc về', 'giáo điều|làm theo cho xong|phán xét người khác|nổi loạn vô cớ',
  'Bạn đang được nâng đỡ bởi những nền nếp đã có từ trước, có thể là một người thầy, truyền thống gia đình hay một tổ chức. Đi theo lối quen thuộc lúc này đem lại cho bạn cảm giác an tâm.',
  'Tình cảm hướng về sự cam kết, sự đồng thuận của gia đình, hoặc một mối quan hệ được xây trên những giá trị chung. Hai bạn nên trò chuyện với nhau về những điều mỗi người tin tưởng.',
  'Trong công việc, bạn nên tuân thủ đúng quy trình. Một người cố vấn hoặc một chứng chỉ chính thức sẽ mở đường cho bạn. Bạn không nên bỏ qua các bước trung gian.',
  'Bạn nên tìm đến những người thầy giỏi và các tài liệu đã được kiểm chứng. Tuần này chưa phải lúc để bạn thử phát minh ra một phương pháp học mới.',
  'Với tiền bạc, bạn nên ưu tiên những cách làm an toàn và đã quen thuộc. Kinh nghiệm của những người đi trước lúc này rất có giá trị.',
  'Bạn hãy tìm đến người từng đi qua chặng đường này. Tấm bản đồ của họ có thể giúp bạn rút ngắn hành trình đến nhiều tháng.'],
'major-6': ['kết nối|lựa chọn|giá trị|hoà hợp', 'lệch pha|né tránh quyết định|cám dỗ|tình đơn phương',
  'Lá bài nói đến sự gặp gỡ đích thực giữa hai phía, hoặc một lựa chọn phơi bày điều bạn thật lòng trân trọng. Năng lượng ở đây thiên về sự tương hợp chứ không dừng ở sức hút bề ngoài.',
  'Tình cảm đang xoay quanh một sợi dây gắn kết bền chặt, một quyết định lớn về người đồng hành, hoặc một thời điểm bạn buộc phải xác định mình mong đợi gì ở tình yêu.',
  'Công việc hiện tại thuận lợi cho sự hợp tác và tinh thần đồng đội. Bạn cũng đang đứng giữa hai lối rẽ, và lối nên đi là lối phù hợp với giá trị sống của bạn.',
  'Việc học chung với bạn bè hoặc trong một nhóm sẽ có lợi cho bạn. Nếu đứng trước việc chọn môn, bạn hãy nghiêng về môn mà bạn thật lòng hứng thú.',
  'Cách bạn quyết định về tiền lúc này phản ánh thứ tự ưu tiên trong lòng bạn. Bạn không nên để mỗi con số quyết định thay mình.',
  'Bạn hãy để những giá trị của mình dẫn dắt lựa chọn, thay vì để nỗi sợ làm điều đó.'],
'major-7': ['ý chí|tiến tới|chiến thắng|có hướng', 'hung hăng|mất kiểm soát|lực phân tán|giẫm lên người khác',
  'Bạn đang tiến về phía trước với lợi thế trong tay. Các lực kéo trái chiều vẫn được ý chí của bạn gom về một hướng. Bạn hãy nắm chắc dây cương.',
  'Bạn có thể theo đuổi điều mình mong muốn trong tình yêu, miễn là cảm xúc vẫn nằm trong tầm kiểm soát. Mối quan hệ này tiến triển nhờ sự cố gắng của cả hai.',
  'Công việc đang được tiếp sức bởi tham vọng và đà tiến mạnh. Bạn đủ sức vượt qua trở ngại trước mắt. Một chuyến công tác hoặc di chuyển cũng có thể xuất hiện.',
  'Trong tuần này, sức mạnh lớn nhất của bạn nằm ở tính kỷ luật. Bạn hãy xác định mục tiêu và dốc sức tiến tới.',
  'Sự quyết tâm sẽ mang tiền về cho bạn. Mục tiêu tài chính mà bạn theo đuổi đã ở rất gần.',
  'Bạn cần cầm chắc cả hai dây cương, một bên là sự tự tin và bên kia là sự kiểm soát.'],
'major-8': ['sức mạnh bên trong|kiên nhẫn|bao dung|can đảm', 'nghi ngờ bản thân|dùng sức ép|cảm xúc thô|thấy yếu là thấy xấu hổ',
  'Sức mạnh của bạn hiện lên một cách âm thầm. Lòng kiên nhẫn và sự tử tế giải quyết được những điều mà áp lực không thể. Con sư tử chịu thuần phục trước sự điềm tĩnh chứ không phải trước tiếng quát.',
  'Trong tình cảm, sự mềm mỏng sẽ giành phần thắng. Khi căng thẳng nổi lên, bạn nên đáp lại bằng kiên nhẫn thay vì phản ứng tức thì. Có người đang rất cần sự điềm tĩnh của bạn.',
  'Bạn hãy giữ thái độ bình thản khi đối mặt với một đồng nghiệp khó tính hay một tình huống nan giải. Sự vững vàng ấy không qua mắt được mọi người.',
  'Hôm nay sự bền bỉ mang lại kết quả tốt hơn sự nhanh trí. Bạn hãy duy trì nhịp học đều đặn và giữ tâm thế thư thái.',
  'Bạn nên giữ cách quản lý tiền ổn định thay vì mạo hiểm với một nước đi lớn. Đừng để nỗi lo sợ cầm lái các quyết định tài chính.',
  'Bạn hãy hít một hơi sâu trước khi hành động. Khi bình tĩnh, bạn đang ở trạng thái mạnh mẽ nhất của chính mình.'],
'major-9': ['nhìn lại|khôn ngoan|một mình|đi tìm', 'cô lập|cô đơn|thu mình quá lâu|từ chối giúp đỡ',
  'Đây là thời điểm bạn nên lùi một bước để suy ngẫm. Lời đáp bạn tìm nằm ở bên trong bạn chứ không ở thêm những ý kiến bên ngoài. Khoảng thời gian một mình lúc này thật sự hữu ích.',
  'Một trong hai người đang cần khoảng lặng riêng để suy nghĩ. Việc tạm rút lui không đồng nghĩa với sự chối bỏ. Sau khi nhìn lại, hai bạn có thể gắn bó sâu sắc hơn.',
  'Bạn nên cân nhắc kỹ trước khi đi bước tiếp theo trong công việc. Ánh sáng dẫn đường có thể đến từ một người đi trước hoặc từ chính trải nghiệm của bạn. Bạn hãy tránh ra quyết định giữa lúc ồn ào.',
  'Việc học lúc này cần chiều sâu, sự tập trung và không gian riêng. Bạn hãy tắt hết các thông báo trên điện thoại.',
  'Bạn nên lặng lẽ rà soát lại tình hình tài chính một cách trung thực. Nếu thấy cần, bạn hãy tham khảo ý kiến chuyên gia.',
  'Bạn hãy dành một buổi tối riêng tư để ở cùng câu hỏi của mình. Sau đó bạn có thể trở lại với mọi người.'],
'major-10': ['thay đổi|may mắn|vòng quay|bước ngoặt', 'chống lại thay đổi|xui xẻo|thấy mất kiểm soát|lặp lại vòng cũ',
  'Vòng quay đã khởi động. Dù bạn có tác động hay không, hoàn cảnh vẫn đang chuyển dịch. Không khí lúc này vừa có vận may vừa có biến động.',
  'Chuyện tình cảm đang chuyển sang một chương mới. Những cuộc gặp gỡ tình cờ rất dễ xảy ra. Điều bạn nhận về sẽ tương xứng với điều bạn đã gieo.',
  'Công việc sắp có sự dịch chuyển, có thể là một vai trò khác, một cơ hội bất ngờ hay một lối rẽ không ai đoán trước. Bạn nên uyển chuyển thích nghi thay vì chống lại dòng chảy.',
  'Điểm số của bạn có thể dao động thất thường. Bạn hãy tận dụng những lúc thăng hoa và giữ bình tĩnh khi kết quả đi xuống.',
  'Vận may về tài chính đang chuyển hướng. Bạn không nên đánh cược, nhưng hãy chuẩn bị sẵn sàng để nắm bắt cơ hội khi nó đến.',
  'Bạn hãy thuận theo vòng quay của bánh xe. Việc chống lại nó chỉ khiến bạn hao sức.'],
'major-11': ['công bằng|sự thật|chịu trách nhiệm|rõ ràng', 'bất công|không thật thà|né hậu quả|phán xét khắc nghiệt',
  'Mối liên hệ giữa nguyên nhân và kết quả đang phơi bày rõ ràng. Mỗi lựa chọn của bạn lúc này đều kéo theo hệ quả, và chỉ có sự trung thực mới thật sự có tác dụng.',
  'Hai bạn nên thẳng thắn với nhau về thế nào là công bằng trong mối quan hệ này. Thế cân bằng sẽ được khôi phục khi mỗi người nhận đúng phần thuộc về mình.',
  'Công việc lúc này gắn với hợp đồng, thủ tục pháp lý hoặc một kỳ đánh giá. Bạn nên tuân thủ đúng quy định và giữ lại mọi giấy tờ liên quan.',
  'Kết quả học tập sẽ phản ánh trung thực mức độ cố gắng của bạn. Bạn hãy thành thật với bản thân về lượng công sức mình thật sự đã bỏ ra.',
  'Về tiền bạc, bạn nên giải quyết mọi khoản cho rõ ràng. Bạn hãy hoàn trả những gì mình còn nợ và thu về những gì người khác còn nợ bạn.',
  'Bạn hãy giữ sự trung thực, và trước hết là trung thực với chính bản thân mình.'],
'major-12': ['tạm dừng|buông bỏ|góc nhìn mới|thả ra', 'giậm chân|tự làm khổ mình|do dự|tự chọn đứng yên',
  'Mọi việc đang chững lại, và khoảng dừng này không hề vô nghĩa. Khi bạn đổi góc nhìn, tình hình sẽ hiện ra theo cách khác. Bạn hãy chủ động chọn sự chờ đợi.',
  'Chuyện tình cảm đang ở trạng thái treo lửng. Cố thúc đẩy lúc này sẽ không mang lại gì. Bạn hãy thả lỏng kỳ vọng về kết quả và quan sát điều gì sẽ chuyển biến.',
  'Công việc có thể bị trì hoãn hoặc một dự án bị tạm gác. Thay vì cố ép tiến độ, bạn nên tận dụng quãng nghỉ này để xem xét lại cách làm.',
  'Bạn hãy tạm rời khỏi bài toán đang giải. Đáp án thường hiện ra khi bạn không còn dán mắt vào nó nữa.',
  'Thời điểm này chưa thích hợp để bạn xê dịch tiền bạc. Bạn hãy giữ nguyên hiện trạng và rà soát lại.',
  'Bạn hãy chủ động dành ra một quãng thời gian để không làm gì cả. Sau khoảng lặng ấy, bạn hãy quan sát lại toàn cảnh.'],
'major-13': ['kết thúc|chuyển hoá|buông bỏ|đổi mới', 'níu kéo|sợ thay đổi|ứ đọng|kéo dài cái kết',
  'Một chương đang khép lại để nhường chỗ cho chương kế tiếp. Cảm giác có thể nặng nề, nhưng năng lượng này đang dọn dẹp chứ không hề tàn nhẫn.',
  'Một mối quan hệ, hoặc một dạng thức cũ của nó, đang đi đến hồi kết. Bạn hãy cho phép mình buồn trọn vẹn, rồi để một hình hài mới có cơ hội thành hình.',
  'Trong công việc, một vị trí, một dự án hay một lối làm việc đang chấm dứt. Bạn không nên níu giữ. Những điều sắp tới cần đúng khoảng trống này để bước vào.',
  'Một phương pháp học hay một mục tiêu ngày trước đã hết vai trò. Bạn hãy chuyển sang cách tiếp cận mới.',
  'Một giai đoạn tài chính đang kết thúc. Bạn hãy loại bỏ những gì không còn sinh lợi và bắt tay dựng lại từ nền mới.',
  'Bạn hãy cho phép mọi thứ kết thúc. Chừng nào còn giữ chặt trang cuối, bạn chưa thể lật sang chương mới.'],
'major-14': ['cân bằng|điều độ|kiên nhẫn|chữa lành', 'quá đà|mất cân bằng|nóng vội|ưu tiên chỏi nhau',
  'Bạn hãy hoà trộn thay vì gò ép. Năng lượng lúc này hướng bạn đến con đường trung dung và nhịp đi chậm rãi. Quá trình chữa lành đang âm thầm diễn ra.',
  'Sự hoà hợp trong tình yêu được nuôi lớn bằng lòng kiên nhẫn và sự nhường nhịn. Bạn nên tránh mọi thái cực, dù trong cảm xúc hay trong yêu cầu dành cho đối phương.',
  'Công việc nhóm lúc này cần sự ổn định và một cách phân bổ việc cân đối. Bạn không nên hấp tấp. Bạn hãy kết nối những thế mạnh khác nhau lại với nhau.',
  'Việc học với nhịp độ ổn định mang lại hiệu quả cao hơn việc nhồi nhét. Bạn hãy giữ sự cân đối giữa thời gian học và thời gian nghỉ.',
  'Bạn nên chi tiêu có chừng mực và tiết kiệm cũng có chừng mực. Đây không phải lúc cho những nước đi táo bạo về tiền bạc.',
  'Bạn hãy dành cho mỗi việc một phần vừa phải, và không để việc nào vượt quá giới hạn.'],
'major-15': ['gắn chặt|ham muốn|tham vọng|thật đến trần trụi', 'nghiện ngập|ám ảnh|mẫu hình độc hại|thấy bị trói',
  'Một điều gì đó đang giữ chặt lấy bạn, có thể là một thói quen, một con người hay một khao khát. Năng lượng này rất mạnh và không nhất thiết là tiêu cực, nhưng bạn cần nhận ra sợi dây đang trói mình.',
  'Tình cảm lúc này mang một sức hút mãnh liệt hoặc một sự ràng buộc khó dứt. Bạn hãy tự hỏi mối quan hệ này đang nuôi dưỡng bạn hay đang vắt kiệt bạn.',
  'Công việc đang được thúc đẩy bởi tham vọng, hoặc ngược lại, nó đang chiếm hữu bạn. Bạn nên xem xét mình đang đánh đổi điều gì để lấy thu nhập.',
  'Sự phân tâm và thói trì hoãn đang lấn át việc học. Bạn hãy chỉ đích danh thói quen nào đang ăn mòn thời gian của mình.',
  'Bạn cần cảnh giác với nợ nần, những khoản chi bốc đồng, và những đồng tiền đi kèm ràng buộc.',
  'Bạn hãy đặt tên cho điều đang trói buộc mình. Ngay khi được gọi đúng tên, sợi xích ấy bắt đầu nới lỏng.'],
'major-16': ['thay đổi đột ngột|sự thật lộ ra|bứt phá|tự do', 'đổ vỡ|cú sốc|sụp đổ có thể tránh|không chịu học bài học',
  'Những gì dựng trên nền móng chông chênh đang sụp xuống. Cú sốc là có thật, nhưng thứ sụp đổ vốn dĩ đã không bền. Sự thật đang phá vỡ lớp vỏ để lộ ra.',
  'Tình cảm có thể gặp một biến cố đột ngột hoặc một sự thật bị phơi bày. Nỗi đau là thật, nhưng nó quét sạch những điều giả dối.',
  'Nơi làm việc đang trải qua biến động bất ngờ, khi kế hoạch đổ vỡ và cơ cấu bị đặt dấu hỏi. Bạn hãy dựng lại mọi thứ trên một nền tảng vững vàng hơn.',
  'Kế hoạch học tập của bạn đang vỡ vụn. Bạn hãy nhìn nhận lại tình hình và lập thời gian biểu mới từ đầu.',
  'Bạn có thể gặp một khoản chi ngoài dự tính hoặc một tổn thất. Bạn hãy ưu tiên bảo vệ những nhu cầu thiết yếu trước.',
  'Bạn hãy để những gì giả tạo rơi rụng. Bạn hãy xây dựng lại bằng những gì chân thật.'],
'major-17': ['hy vọng|chữa lành|cảm hứng|hồi phục', 'nản lòng|mất niềm tin|nghi ngờ mình|lạc quan rỗng',
  'Sau chuỗi ngày khó khăn, sự bình yên đã tìm đến bạn. Niềm hy vọng lúc này là thật lòng chứ không phải gượng ép. Bạn đang trong quá trình hồi phục.',
  'Vết thương tình cảm của bạn đang lành. Sự cởi mở đang tìm đường quay lại. Tình yêu lúc này chân thành và êm đềm.',
  'Bạn đang tìm lại cảm hứng và ý nghĩa trong công việc. Đây là thời điểm thuận lợi cho những dự định sáng tạo và có tầm nhìn xa.',
  'Động lực học tập đang trở lại với bạn. Bạn nhìn thấy rõ lý do mình theo đuổi môn học này.',
  'Áp lực tài chính đang vơi bớt. Bạn có thể rộng lòng cho đi, nhưng vẫn nên giữ trong giới hạn hợp lý.',
  'Bạn hãy đặt lòng tin vào niềm hy vọng âm thầm ấy. Nó đang nói với bạn sự thật.'],
'major-18': ['trực giác|giấc mơ|chưa rõ|tiềm thức', 'ảo ảnh|lo âu|lừa dối|rối bời',
  'Bức tranh hiện tại vẫn còn mờ nhoè. Nỗi sợ và trí tưởng tượng đang nhuộm màu lên những gì bạn nhìn thấy. Bạn hãy đi từng bước chậm, tin vào linh cảm chứ không tin vào nỗi lo.',
  'Tình cảm đang phát đi những tín hiệu mâu thuẫn và thiếu chắc chắn. Có điều gì đó đang bị che giấu. Bạn không nên vội suy diễn theo hướng xấu, nhưng hãy mạnh dạn hỏi.',
  'Nơi làm việc đang rối ren hoặc thiếu thông tin minh bạch. Bạn hãy đợi sự thật sáng tỏ rồi mới hành động.',
  'Nỗi lo âu đang che mờ khả năng hiểu bài của bạn. Bạn hãy ngủ một giấc và xem lại khi đầu óc đã minh mẫn.',
  'Tình hình tài chính đang thiếu minh bạch hoặc tiềm ẩn rủi ro. Bạn không nên ký vào bất cứ giấy tờ nào mà mình chưa hiểu trọn vẹn.',
  'Bạn hãy chậm rãi băng qua màn sương này. Sương rồi sẽ tan.'],
'major-19': ['niềm vui|thành công|rõ ràng|sức sống', 'kiêu ngạo|phô bày quá mức|hạnh phúc đến muộn|vui giả',
  'Năng lượng của bạn đang ấm áp, sáng rõ và đầy tự tin. Mọi việc đều trôi chảy và ai cũng có thể nhìn thấy điều đó. Bạn hãy thoải mái bày tỏ niềm vui của mình.',
  'Tình cảm đang tràn đầy hạnh phúc, sự ấm áp và một kết nối nhẹ nhàng. Mối quan hệ của bạn đang đứng dưới ánh nắng ban ngày.',
  'Công việc mang về thành công, sự ghi nhận và một chiến thắng không thể phủ nhận. Những nỗ lực của bạn đang được mọi người thấy rõ.',
  'Đầu óc bạn đang sáng suốt và bạn tự tin vào bản thân. Kết quả học tập tốt đang trên đường đến.',
  'Tài chính đang gặp may mắn và tăng trưởng. Tiền tìm đến bạn cùng với niềm vui thay vì qua sự vật lộn.',
  'Bạn hãy đồng ý đón nhận những điều tốt đẹp. Bạn xứng đáng với chúng.'],
'major-20': ['thức tỉnh|tiếng gọi|tha thứ|tổng kết', 'tự phán xét|từ chối tiếng gọi|hối tiếc|kẹt trong quá khứ',
  'Đây là khoảnh khắc mọi thứ trở nên sáng tỏ. Bạn được mời gọi bước vào một quyết định, một sự thay đổi hay một tầng nhận thức mới. Quá khứ được nhìn lại rồi được buông xuống.',
  'Tình cảm của bạn đang đứng trước một khúc ngoặt. Bạn hãy tha thứ, đưa ra quyết định và tiếp tục hành trình.',
  'Sự nghiệp đang vang lên một tiếng gọi, có thể là một kỳ đánh giá hay một cơ hội thăng tiến. Bạn hãy trả lời tiếng gọi đó.',
  'Việc học đang đi đến lúc nhận kết quả và được đánh giá. Bạn hãy rút kinh nghiệm từ quá khứ và bước lên nấc cao hơn.',
  'Tiền bạc đang bước vào một kỳ tổng kết. Bạn hãy nhìn thẳng vào các con số và đưa ra quyết định.',
  'Bạn hãy hồi đáp tiếng gọi ấy. Trong thâm tâm, bạn đã biết nó là gì.'],
'major-21': ['hoàn tất|trọn vẹn|thành tựu|đi xa', 'việc dang dở|chậm trễ|thấy chưa đủ|đi tắt',
  'Một chu kỳ vừa hoàn tất. Bài học đã thấm vào bạn. Đây là sự trọn vẹn, đồng thời là cánh cửa dẫn sang chu kỳ kế tiếp.',
  'Tình cảm đang bước vào độ chín và trọn vẹn. Lá bài cũng có thể báo trước một chuyến đi mà hai bạn cùng thực hiện.',
  'Bạn sắp hoàn tất một dự án quan trọng. Thành quả này mang lại sự công nhận, và có thể mở ra cơ hội đi xa hoặc làm việc với đối tác nước ngoài.',
  'Việc học đang tiến đến lúc tốt nghiệp, hoàn thành chương trình hoặc nắm vững trọn vẹn một môn.',
  'Bạn đang chạm tới mục tiêu tài chính của mình. Sự ổn định này có thể kéo dài bền vững.',
  'Bạn hãy hoàn thành mọi việc một cách trọn vẹn. Sau đó bạn nên ăn mừng trước khi khởi đầu điều mới.'],

'wands-1': ['tia lửa|cảm hứng|năng lượng mới|khao khát', 'khởi đầu hụt|không có hướng|chậm trễ|cháy hết sớm',
  'Trong bạn đang trào lên khao khát tạo ra một điều gì đó. Nguồn năng lượng này còn thô ráp và chưa có đích đến. Bạn hãy hướng nó vào một mục tiêu cụ thể.',
  'Tình cảm đang bừng lên một sức hút mới, một niềm đam mê, một tia lửa vừa loé. Cảm giác này rất vui, nhưng nó chưa phải là một lời cam kết.',
  'Một ý tưởng hoặc một lời mời hợp tác mới đang có sức sống thật sự đứng sau. Bạn hãy khởi động ngay.',
  'Bạn đang hào hứng với một môn học mới. Bạn nên tận dụng ngọn lửa ấy trước khi nó nguội đi.',
  'Một cách kiếm tiền mới đang nhen nhóm trong đầu bạn. Bạn hãy thử nghiệm ở quy mô nhỏ trước khi mở rộng.',
  'Bạn hãy châm lửa trước, rồi mới dựng bếp quanh ngọn lửa ấy.'],
'wands-2': ['lên kế hoạch|tầm nhìn|lựa chọn|chân trời rộng', 'chơi an toàn|sợ điều chưa biết|kế hoạch không bao giờ chạy',
  'Bạn đang nắm giữ một thành quả, nhưng tầm mắt đã hướng xa hơn nó. Đã đến lúc bạn chọn cho mình một chân trời rộng lớn hơn.',
  'Tình cảm đòi hỏi bạn xác định rõ mình mong đợi gì ở tình yêu, hoặc chọn giữa sự an toàn dễ chịu và một hướng đi mạo hiểm hơn.',
  'Công việc đang ở giai đoạn hoạch định cho việc mở rộng, hợp tác và bước đi kế tiếp. Bạn hãy dám nghĩ lớn, rồi dấn thân cam kết.',
  'Bạn đang đứng trước việc chọn hướng đi hoặc chuyên ngành. Bạn nên lập kế hoạch cho cả một năm thay vì chỉ cho tuần trước mắt.',
  'Tiền bạc lúc này cần một kế hoạch đầu tư rõ ràng. Bạn hãy cân đối giữa sự an toàn và khả năng sinh lời.',
  'Bạn hãy chốt hướng đi trước. Những chi tiết nhỏ có thể được giải quyết sau.'],
'wands-3': ['mở rộng|nhìn xa|tiến triển|chờ đúng cách', 'chậm trễ|nóng vội|nghĩ quá nhỏ|không theo tới cùng',
  'Những cố gắng ban đầu của bạn đã được gửi đi và đang phát huy tác dụng. Lúc này bạn chỉ cần chờ đợi và chuẩn bị đón nhận thành quả quay về.',
  'Điều bạn đã khởi xướng trong tình cảm đang lớn dần. Bạn hãy cho nó thêm thời gian. Một mối liên hệ ở phương xa cũng có thể xuất hiện.',
  'Công việc đang tăng trưởng, mở ra thị trường mới và gặt hái thành quả từ nỗ lực trước đó. Bạn hãy tiếp tục hướng tầm nhìn về phía chân trời.',
  'Phần nền tảng đã hoàn tất, và kết quả học tập đang trên đường đến với bạn.',
  'Khoản đầu tư trước đây bắt đầu sinh lời. Sự kiên nhẫn của bạn đang được đền bù xứng đáng.',
  'Bạn hãy hướng mắt về phía chân trời thay vì dõi theo kim đồng hồ.'],
'wands-4': ['ăn mừng|mái nhà|ổn định|cộng đồng', 'bất ổn|căng thẳng trong nhà|kế hoạch bị huỷ|thấy không được chào đón',
  'Bạn đang chạm tới một cột mốc, một dịp trở về mái nhà hay một lý do để mọi người sum họp. Niềm vui lúc này vững chãi và bền lâu.',
  'Tình cảm đang hướng tới một lời cam kết, việc dọn về chung một mái nhà, hoặc một buổi tiệc mừng bên những người thân yêu.',
  'Tập thể của bạn vừa đạt được một cột mốc, hoặc bạn đang ở trong một môi trường làm việc ổn định và tương trợ. Bạn hãy dành thời gian ăn mừng.',
  'Việc học của bạn vừa chạm tới một dấu mốc đáng nhớ. Nhóm bạn học hoặc môi trường xung quanh đang là chỗ dựa tốt cho bạn.',
  'Tình hình tài chính đang vững vàng. Lúc này bạn có thể chi tiêu cho nhà cửa một cách hợp lý.',
  'Bạn hãy ghi nhận cột mốc vừa đạt được. Sau đó bạn hãy cho phép mình nghỉ ngơi.'],
'wands-5': ['cạnh tranh|tranh luận|năng lượng|thử sức', 'xung đột|hỗn loạn|cãi vì cãi|né cuộc tranh',
  'Nhiều luồng năng lượng đang xung đột, từ ý kiến, cái tôi cho đến kế hoạch của mỗi người. Tình hình không nguy hiểm nhưng khá ồn ào. Bạn hãy ganh đua một cách sòng phẳng.',
  'Tình cảm đang vướng vào những cuộc cãi vã nhỏ, sự ganh đua, hoặc quá nhiều khác biệt nổi lên cùng lúc. Hai bạn nên tập trung tranh luận về vấn đề cốt lõi.',
  'Nơi làm việc đang đầy cạnh tranh và ý kiến trái ngược, khiến bạn khó được lắng nghe. Bạn hãy kiên trì bám trụ trong cuộc chơi.',
  'Môi trường học tập đang rất cạnh tranh, hoặc sự chú ý của bạn đang bị phân tán. Bạn hãy chọn ra một mặt trận duy nhất để dồn sức.',
  'Cùng một khoản tiền đang bị nhiều nhu cầu tranh giành. Bạn hãy xếp thứ tự ưu tiên cho chúng.',
  'Bạn hãy chọn cuộc chiến thật sự xứng đáng và buông những cuộc chiến còn lại.'],
'wands-6': ['chiến thắng|được công nhận|tự tin|tiến bộ', 'cái tôi|từ đỉnh rơi xuống|không được nhìn thấy|thắng rỗng',
  'Thắng lợi của bạn đang thu hút sự chú ý. Bạn đang ở vị trí dẫn đầu và mọi người đều nhận ra. Bạn hãy tận hưởng sự ghi nhận này.',
  'Bạn đang cảm nhận được sự ngưỡng mộ từ người khác. Mối quan hệ này khiến bạn tự hào.',
  'Công việc có thể mang đến sự thăng tiến, lời khen ngợi hoặc một thành công được công khai. Bạn hãy đón nhận với thái độ khiêm nhường và lịch thiệp.',
  'Bạn đạt kết quả học tập tốt và được thầy cô, bạn bè công nhận. Sự tự tin của bạn có cơ sở vững chắc.',
  'Một khoản tiền thưởng hoặc một thắng lợi về tài chính có thể sắp đến với bạn.',
  'Bạn hãy đón nhận tràng pháo tay, rồi tiếp tục thúc ngựa tiến lên.'],
'wands-7': ['phòng thủ|bền bỉ|can đảm|giữ vững vị trí', 'bỏ cuộc|kiệt sức|thấy quá tải|phòng thủ thái quá',
  'Bạn đang bảo vệ vị trí của mình trước sức ép từ nhiều phía. Dù thấm mệt, bạn vẫn đang đứng ở thế thượng phong.',
  'Tình cảm đòi hỏi bạn đứng lên bảo vệ mối quan hệ hoặc nhu cầu của bản thân. Bạn hãy giữ vững lập trường mà không biến nó thành một cuộc chiến.',
  'Vị trí của bạn ở nơi làm việc đang bị cạnh tranh hoặc thử thách. Bạn hãy giữ chỗ đứng bằng chính năng lực của mình.',
  'Việc học đang chất chồng áp lực và thử thách. Bạn hãy bước tiếp, vì bạn mạnh mẽ hơn nỗi hoài nghi trong lòng.',
  'Bạn nên giữ gìn những gì mình đang có trước các yêu cầu từ bên ngoài. Bạn cần học cách từ chối.',
  'Bạn hãy kiên định giữ vững vị trí, nhưng đừng quên thở đều trong lúc đó.'],
'wands-8': ['nhanh chóng|tin tức|chuyển động|đà tiến', 'chậm trễ|hỗn loạn|quyết vội|hiểu lầm',
  'Nhịp sống đang tăng tốc với những tin nhắn, chuyến đi và bước tiến bất ngờ. Bạn hãy bắt kịp dòng chảy nhưng vẫn giữ đầu óc tỉnh táo.',
  'Tình cảm đang tiến triển chóng vánh, với những tin nhắn và một mối liên hệ phát triển rất nhanh. Bạn hãy hồi âm ngay.',
  'Công việc đang tăng tốc, kèm theo tin tức mới và những chuyến đi. Bạn nên phản hồi nhanh với lời đề nghị đang có.',
  'Việc học đang tiến nhanh. Thời hạn đã cận kề, vì vậy bạn hãy bắt tay vào làm ngay lập tức.',
  'Dòng tiền đang luân chuyển rất nhanh. Cơ hội đến nhanh, và các khoản chi cũng trôi đi nhanh không kém.',
  'Bạn hãy hành động nhanh chóng, nhưng giữ cho cái đầu luôn lạnh.'],
'wands-9': ['bền bỉ|kiên trì|cảnh giác|nỗ lực cuối', 'đa nghi|kiệt sức|từ chối giúp đỡ|dựng rào',
  'Bạn đã thấm mệt, nhưng đích đến đã ở rất gần. Bạn hãy bảo vệ những gì mình đã gây dựng và đi nốt chặng cuối.',
  'Những tổn thương cũ khiến bạn dè chừng trong tình cảm. Bạn có quyền tự bảo vệ, nhưng không nên dựng rào chắn với tất cả mọi người.',
  'Một giai đoạn công việc đầy khó khăn sắp khép lại. Bạn hãy bền chí và đặt ra những giới hạn rõ ràng.',
  'Bạn đang trong chặng nước rút cuối cùng trước kỳ thi hoặc hạn nộp bài. Bạn hãy duy trì nhịp độ ổn định.',
  'Bạn nên giữ chặt khoản tiết kiệm của mình. Bạn hãy thận trọng trước bất kỳ cam kết tài chính mới nào.',
  'Bạn hãy cố thêm một bước nữa. Sau đó bạn hãy nghỉ ngơi, một cách thật sự.'],
'wands-10': ['trách nhiệm|gánh nặng|làm việc chăm|quyết tâm', 'quá tải|kiệt sức|gánh cho người khác|không giao việc',
  'Bạn đang gánh trên vai rất nhiều thứ, có lẽ là quá sức. Gánh nặng là thật, nhưng sức bền của bạn cũng thật. Trong số đó có những thứ bạn có thể đặt xuống.',
  'Bạn đang một mình ôm trọn phần cảm xúc của mối quan hệ. Bạn hãy san sẻ gánh nặng ấy với đối phương.',
  'Bạn đang làm việc quá sức với khối lượng công việc quá lớn. Bạn hãy uỷ thác bớt hoặc mạnh dạn cắt bỏ một phần.',
  'Thời khoá biểu của bạn đang quá tải. Bạn hãy tinh giản nó xuống chỉ còn những gì thật sự quan trọng.',
  'Bạn đang chịu nhiều gánh nặng và nghĩa vụ về tiền bạc. Bạn hãy đơn giản hoá bức tranh tài chính của mình.',
  'Ngay hôm nay, bạn hãy chọn một gánh nặng và đặt nó xuống.'],
'wands-c0': ['nhiệt tình|khám phá|tin nhắn|ý tưởng mới', 'thiếu định hướng|nóng vội|non nớt|chậm trễ',
  'Bạn đang tò mò, hào hứng và có phần bồn chồn. Một ý tưởng hoặc một tin nhắn mới đang trên đường đến. Bạn hãy khám phá nó.',
  'Tình cảm có thể xuất hiện một người đang tán tỉnh bạn, một tin nhắn mới, hoặc một tâm hồn trẻ trung. Chuyện này mang lại niềm vui, nhưng chưa đi vào chiều sâu nghiêm túc.',
  'Công việc có thể mang đến một ý tưởng mới, một vị trí tập sự, hoặc một tin tức đáng mừng.',
  'Bạn đang tràn đầy sự tò mò và nhiệt huyết trong việc học. Bạn hãy mạnh dạn khám phá những chủ đề mới.',
  'Một ý tưởng tài chính mới đang thu hút bạn. Bạn hãy nghiên cứu kỹ trước khi bỏ tiền vào.',
  'Bạn hãy đi theo tia lửa vừa loé và xem nó sẽ dẫn mình đến đâu.'],
'wands-c1': ['hành động|đam mê|phiêu lưu|cuốn hút', 'liều lĩnh|bốc đồng|kiêu ngạo|đi quá sớm',
  'Bạn đang ở trạng thái táo bạo, nhanh nhẹn, cuốn hút nhưng thiếu kiên nhẫn. Bạn đã sẵn sàng xông lên. Bạn hãy ngắm đích thật kỹ rồi mới xuất phát.',
  'Tình cảm đang gắn với một người hoặc một giai đoạn rực lửa đam mê. Sức hấp dẫn là rõ ràng, nhưng độ tin cậy thì không phải lúc nào cũng có.',
  'Công việc đang kêu gọi những hành động táo bạo, những chuyến đi và việc nắm giữ quyền chủ động. Bạn hãy dè chừng tính bốc đồng.',
  'Năng lượng học tập của bạn đến theo từng đợt ngắn. Bạn hãy gom chúng lại vào một kế hoạch thống nhất.',
  'Bạn đang cân nhắc một nước đi tài chính mạo hiểm. Rủi ro là có thật. Bạn hãy rà soát từng chi tiết trước khi quyết định.',
  'Bạn có thể xông lên phía trước, nhưng cần biết rõ vực thẳm nằm ở đâu.'],
'wands-c2': ['ấm áp|tự tin|độc lập|có sức hút', 'ghen tuông|đòi hỏi|kịch tính|cháy sạch',
  'Bạn đang toả ra một nguồn năng lượng ấm áp, tự tin và lôi cuốn. Sự chú ý của mọi người đang đổ về phía bạn. Bạn hãy dùng lợi thế này cho những điều tốt đẹp.',
  'Tình cảm nói về một người đồng hành vừa tự tin vừa ấm áp, hoặc chính là nét tự tin đáng mến của bạn.',
  'Bạn hãy dẫn dắt mọi người bằng sự ấm áp. Bạn có thể trở thành nguồn cảm hứng cho cả nhóm.',
  'Bạn học tốt nhất khi tự tin vào bản thân và tự vạch ra hướng đi cho mình.',
  'Bạn đang quản lý tiền bạc với sự tự tin và tinh thần tự chủ.',
  'Bạn hãy toả sáng theo cách của mình, đồng thời chừa chỗ để người khác cũng được toả sáng.'],
'wands-c3': ['tầm nhìn|dẫn dắt|táo bạo|làm chủ', 'độc đoán|thiếu kiên nhẫn|kỳ vọng quá cao|tàn nhẫn',
  'Bạn đang mang năng lượng của một người lãnh đạo có tầm nhìn và dám nghĩ dám làm. Bạn là người vạch ra hướng đi. Bạn hãy dẫn dắt bằng cảm hứng thay vì bằng mệnh lệnh.',
  'Tình cảm nói về một người đồng hành lôi cuốn và giàu động lực, hoặc chính bạn đang giữ vai trò dẫn dắt trong chuyện yêu đương.',
  'Bạn hãy đứng ra cầm trịch dự án. Thành công đến từ sự kết hợp giữa tầm nhìn và hành động.',
  'Bạn hãy tự mình làm chủ lộ trình học tập thay vì để người khác vạch ra cho bạn.',
  'Bạn đang tiếp cận tiền bạc với tinh thần của một người khởi nghiệp. Bạn hãy táo bạo nhưng luôn có tính toán.',
  'Bạn hãy tiên phong dẫn đường, và hãy làm điều đó bằng cả trái tim.'],

'cups-1': ['tình cảm mới|khởi đầu cảm xúc|bao dung|sáng tạo', 'trống rỗng|cảm xúc bị chặn|thiếu yêu bản thân|cảm xúc tràn',
  'Trái tim bạn đang dần hé mở. Những cảm xúc mới, lòng trắc ẩn mới, hoặc một khởi đầu về sáng tạo hay tâm linh đang tìm đến. Bạn hãy dang tay đón nhận.',
  'Tình cảm đang đón một tình yêu mới, hoặc một mối quan hệ cũ được thổi vào luồng cảm xúc tươi mới. Trái tim bạn đang cởi mở.',
  'Công việc mang lại cho bạn sự thoả mãn về mặt tinh thần, một khởi đầu sáng tạo và những mối quan hệ tốt đẹp với đồng nghiệp.',
  'Việc học đang trở thành niềm vui với bạn. Một môn học thiên về sáng tạo đang vẫy gọi.',
  'Thu nhập đang đến từ chính công việc bạn yêu thích. Sự hào phóng đang tuôn chảy quanh bạn.',
  'Bạn hãy cho phép chiếc cốc của mình được rót đầy.'],
'cups-2': ['gắn kết|hấp dẫn hai chiều|kết nối|cân bằng', 'lệch cân|chia tay|hiểu lầm|một phía',
  'Giữa hai con người hoặc hai phía đang hình thành một sự gắn kết chân thật. Sự tôn trọng và sức hút đến từ cả hai chiều.',
  'Tình cảm cho thấy một sự gắn bó song phương bền chặt, một sự hợp tác, hoặc một cuộc gặp gỡ đầy ý nghĩa.',
  'Công việc đang có một mối hợp tác kinh doanh thuận lợi hoặc một quan hệ đồng nghiệp bền chắc.',
  'Bạn đang tìm được một người bạn cùng học hoặc một người hướng dẫn thật sự hợp ý với mình.',
  'Tiền bạc đang gắn với một mối hợp tác được xây trên sự công bằng cho cả hai bên.',
  'Hai bạn hãy tìm đến điểm gặp nhau ở giữa, rồi mọi chuyện sẽ ổn thoả.'],
'cups-3': ['tình bạn|ăn mừng|cộng đồng|sáng tạo', 'đàm tiếu|quá đà|người thứ ba|cô lập',
  'Không khí quanh bạn đang rộn ràng, đông vui và tràn ngập tinh thần ăn mừng. Bạn bè, những buổi tụ họp và niềm vui chung đang bao quanh bạn.',
  'Tình cảm có thể đưa bạn đến một buổi vui cùng bạn bè. Tuy nhiên, lá bài cũng có thể cảnh báo sự xuất hiện của người thứ ba, nên bạn hãy xem xét lại.',
  'Công việc đang thuận lợi cho tinh thần đồng đội, những dịp ăn mừng và sự hợp tác sáng tạo.',
  'Việc học theo nhóm đang mang lại hiệu quả rõ rệt. Bạn hãy dành thời gian ghi nhận và ăn mừng những tiến bộ đạt được.',
  'Tiền của bạn đang chảy vào các hoạt động giao lưu bạn bè. Bạn hãy vui, nhưng giữ trong giới hạn cho phép.',
  'Bạn hãy nhấc máy và gọi cho những người bạn của mình.'],
'cups-4': ['ngẫm nghĩ|thờ ơ|xem lại|chán nản', 'bỏ lỡ cơ hội|thu mình|vô ơn|tê liệt',
  'Bạn đang chán chường, thờ ơ và thiếu chắc chắn. Một lời đề nghị đang ở ngay trước mặt nhưng bạn chưa nhìn ra. Bạn hãy ngẩng đầu lên.',
  'Tình cảm đang rơi vào trạng thái nhàm chán hoặc xa cách. Có một điều tốt đẹp đang bị bạn bỏ lỡ.',
  'Bạn đang bất mãn với công việc và có nguy cơ để tuột mất cơ hội. Bạn hãy nhìn lại xem mình thật sự muốn gì.',
  'Động lực học tập của bạn đang cạn dần. Bạn hãy thử một cách tiếp cận khác.',
  'Bạn đang bỏ qua những cơ hội tài chính ngay trước mắt. Bạn hãy để tâm nhiều hơn.',
  'Trước khi lắc đầu từ chối, bạn hãy nhìn kỹ điều đang được trao cho mình.'],
'cups-5': ['đau buồn|hối tiếc|mất mát|chấp nhận', 'không chịu đi tiếp|thương thân|dằn vặt|cô lập',
  'Bạn đang tiếc nuối về những gì đã mất, và nỗi buồn ấy hoàn toàn có thật. Tuy nhiên không phải mọi thứ đều đổ vỡ, vì vẫn còn hai chiếc cốc đứng vững phía sau.',
  'Tình cảm đang trải qua sự thất vọng hoặc một mất mát. Bạn hãy cho mình thời gian buồn, rồi quay trở lại với cuộc sống.',
  'Công việc đang gặp một bước lùi hoặc một nỗi thất vọng. Bạn hãy rút ra bài học và tiếp tục tiến bước.',
  'Bạn vừa nhận một kết quả không như ý. Đây chưa phải là dấu chấm hết. Bạn hãy tập trung vào những gì vẫn còn trong tay.',
  'Bạn vừa chịu một khoản thất thoát về tiền bạc. Bạn hãy đánh giá lại phần tài sản còn lại của mình.',
  'Bạn hãy quay đầu nhìn lại. Hai chiếc cốc phía sau vẫn còn nguyên.'],
'cups-6': ['hoài niệm|hồn nhiên|tử tế|quá khứ', 'kẹt trong quá khứ|ngây thơ|ký ức tô hồng|níu kéo',
  'Những ký ức êm đềm, lòng tốt và một nét hồn nhiên ngày xưa đang trở về với bạn. Quá khứ ghé thăm một cách dịu dàng.',
  'Tình cảm có thể gắn với một người cũ, sự ngọt ngào của thuở ấu thơ, hoặc một tình yêu mộc mạc giản đơn.',
  'Một mối quan hệ công việc từ trước có thể quay trở lại. Nơi làm việc đang có sự tử tế, và bạn được trở về với một vai trò quen thuộc.',
  'Bạn nên ôn lại những kiến thức nền tảng. Những gì đã học trước đây sẽ trở nên hữu ích.',
  'Bạn có thể nhận được một món quà, hoặc một khoản tiền có nguồn gốc từ quá khứ.',
  'Bạn hãy trân trọng những kỷ niệm, nhưng đôi chân vẫn đặt ở hiện tại.'],
'cups-7': ['lựa chọn|tưởng tượng|mơ mộng|khả năng', 'ảo tưởng|mơ hão|quá nhiều lựa chọn|trốn thực tế',
  'Trước mắt bạn là vô số lựa chọn và ảo mộng. Không phải tất cả đều có thật. Bạn hãy chọn với đôi mắt tỉnh táo.',
  'Trong tình cảm, ranh giới giữa mộng tưởng và thực tế đang nhoà đi. Bạn có thể đang tô vẽ ai đó quá mức. Bạn hãy nhìn họ đúng như con người thật của họ.',
  'Công việc đang mở ra quá nhiều khả năng cùng lúc. Bạn hãy dồn sức vào một con đường thực tế nhất.',
  'Bạn đang bị phân tâm và chìm trong mơ mộng thay vì học. Bạn hãy chọn lấy một việc và làm cho xong.',
  'Bạn đang xây những giấc mơ về tiền bạc. Bạn hãy ngồi xuống và tính toán cụ thể.',
  'Bạn hãy chọn lấy một chiếc cốc, và hãy chọn với đôi mắt mở to.'],
'cups-8': ['bước đi|tìm điều hơn|buông bỏ|tìm sâu hơn', 'sợ thay đổi|vô định|bỏ chạy|ở lại quá lâu',
  'Bạn đang rời bỏ một điều để đi tìm điều sâu sắc hơn. Cảm giác lúc này vừa là mất mát vừa là sự giải phóng.',
  'Bạn đang rời khỏi một mối quan hệ không còn khiến mình trọn vẹn. Quyết định này khó khăn, nhưng nó đúng đắn.',
  'Bạn đang từ bỏ một công việc hay một vị trí để tìm kiếm điều có ý nghĩa hơn với mình.',
  'Việc học của bạn cần một hướng đi khác. Bạn hãy bỏ lại những gì không còn phù hợp.',
  'Bạn nên bước ra khỏi một tình trạng tài chính đang bào mòn sức lực của mình.',
  'Bạn hãy cất bước ra đi. Điều bạn tìm kiếm không nằm ở nơi này.'],
'cups-9': ['hài lòng|mãn nguyện|ước thành|tận hưởng', 'tự mãn|hưởng thụ quá đà|vui nông|vẫn chưa đủ',
  'Điều ước của bạn đã thành hiện thực, kéo theo sự thoải mái và niềm vui tận hưởng. Bạn đã có được thứ mình từng cầu mong. Bạn hãy thưởng thức nó.',
  'Tình cảm mang đến cho bạn sự mãn nguyện về cảm xúc và niềm vui trong tình yêu.',
  'Công việc đang mang về cho bạn thành tựu và sự hài lòng.',
  'Bạn đang gặt hái thành công và cảm thấy hài lòng với kết quả học tập.',
  'Tình hình tài chính đang thoải mái. Bạn có thể tự thưởng cho mình, miễn là một cách khôn ngoan.',
  'Bạn hãy tận hưởng thành quả. Bạn đã cầu xin, và nó đã tìm đến.'],
'cups-10': ['hoà thuận|gia đình|hạnh phúc lâu dài|thuộc về', 'gia đình rạn|bất hoà|kỳ vọng phi thực tế|lơ là',
  'Bạn đang ở trong một niềm hạnh phúc sâu lắng, được sẻ chia và bền lâu. Gia đình, mái ấm và sự đủ đầy về cảm xúc đang vây quanh bạn.',
  'Tình cảm cho thấy một mối quan hệ đầy yêu thương và cam kết. Gia đình bạn đang sống trong hoà thuận.',
  'Công việc đang mang lại cho bạn cảm giác trọn vẹn, cùng những mối quan hệ tốt đẹp với đồng nghiệp.',
  'Gia đình đang đứng phía sau ủng hộ con đường học tập của bạn.',
  'Bạn đang xây được sự an toàn về tài chính cho cả gia đình.',
  'Đây là một điều tốt đẹp. Bạn hãy nâng niu nó bằng bàn tay nhẹ nhàng.'],
'cups-c0': ['sáng tạo|trực giác|thông điệp cảm xúc|nhạy cảm', 'non nớt về cảm xúc|thất thường|bí ý tưởng|trốn thực tế',
  'Một thông điệp hoặc một rung động nhẹ nhàng, giàu trí tưởng tượng đang đến với bạn. Có điều gì mới mẻ vừa khẽ lay động trong trái tim bạn.',
  'Tình cảm có thể mang đến một tin nhắn ngọt ngào, một người bạn đang thầm thích, hoặc một khởi đầu êm dịu.',
  'Công việc đang xuất hiện một ý tưởng sáng tạo, hoặc một thông điệp chạm đến cảm xúc từ đồng nghiệp.',
  'Bạn tiếp thu tốt nhất khi học theo trực giác. Nghệ thuật và các môn sáng tạo đang hợp với bạn.',
  'Một món quà nhỏ ngoài dự tính có thể đang đến với bạn.',
  'Bạn hãy lắng nghe cảm giác mong manh vừa loé lên trong lòng.'],
'cups-c1': ['lãng mạn|duyên dáng|theo trái tim|lý tưởng', 'thất thường|phi thực tế|ghen tuông|lừa dối',
  'Bạn đang toát ra vẻ lãng mạn, duyên dáng và đầy lý tưởng. Trái tim đang dẫn lối cho bạn. Bạn hãy kiểm tra xem đôi chân mình còn chạm đất hay không.',
  'Tình cảm có thể đưa đến một lời tỏ tình lãng mạn hoặc một người theo đuổi đầy duyên dáng. Chuyện này thật vui, nhưng bạn nên cảnh giác với ảo ảnh.',
  'Công việc đang thuận lợi cho những dự án sáng tạo và một cách tiếp cận tinh tế.',
  'Bạn đang học với nhiều cảm hứng. Nghệ thuật, âm nhạc và văn chương là những lĩnh vực đặc biệt hợp với bạn lúc này.',
  'Cảm xúc đang chi phối cách bạn tiêu tiền. Bạn hãy dừng lại một nhịp trước khi quyết định mua.',
  'Bạn hãy đi theo tiếng gọi của trái tim, nhưng đừng nhắm mắt.'],
'cups-c2': ['bao dung|bình tĩnh|trực giác|an toàn cảm xúc', 'bất an|lệ thuộc|hy sinh quá mức|quá tải',
  'Bạn đang mang một nguồn năng lượng điềm tĩnh, ân cần và giàu trực giác. Bạn thấu hiểu người khác cũng như thấu hiểu chính mình. Bạn đừng quên tự chăm sóc bản thân.',
  'Tình cảm nói về một người đồng hành biết yêu thương và chăm sóc, hoặc chính sự trưởng thành về cảm xúc của bạn.',
  'Sự đồng cảm và trực giác đang soi đường cho bạn trong công việc. Bạn hãy trở thành chỗ dựa cho đồng nghiệp.',
  'Bạn nên học bằng cách thấu hiểu bản chất vấn đề thay vì học thuộc lòng.',
  'Bạn hãy để trực giác dẫn dắt các quyết định tài chính. Bạn cũng nên chăm lo cho sự an toàn về tiền bạc.',
  'Bạn hãy chăm lo cho mọi người, nhưng nhớ dành lại một phần cho chính mình.'],
'cups-c3': ['cân bằng cảm xúc|khéo léo|khôn ngoan|bao dung', 'thao túng cảm xúc|thất thường|dễ bùng|lạnh lùng',
  'Bạn đang làm chủ cảm xúc với sự trưởng thành. Cảm xúc của bạn mãnh liệt nhưng được điều tiết bằng sự khôn ngoan.',
  'Tình cảm nói về một người đồng hành chín chắn và cân bằng về cảm xúc. Lòng bao dung đang hiện diện trong tình yêu của bạn.',
  'Bạn đang dẫn dắt công việc bằng sự khéo léo và điềm tĩnh. Bạn hãy cư xử với mọi người một cách chu đáo.',
  'Bạn đang có một cách học vừa cân bằng vừa khôn ngoan.',
  'Bạn đang quản lý tiền bạc với sự cân bằng và khôn ngoan.',
  'Bạn hãy cảm nhận thật sâu, nhưng hành động thật điềm tĩnh.'],

'swords-1': ['rõ ràng|sự thật|bứt phá|ý tưởng mới', 'rối trí|lạm dụng sức mạnh|lời cay nghiệt|phán đoán mờ',
  'Một khoảnh khắc đầu óc sáng rõ. Sự thật cắt xuyên qua. Ý tưởng mới, suy nghĩ quyết đoán.',
  'Những cuộc nói chuyện thẳng thắn. Rõ ràng về điều bạn muốn.',
  'Một ý tưởng đột phá. Quyết định rõ ràng.',
  'Suy nghĩ sắc. Một cách hiểu mới.',
  'Tư duy tài chính rõ ràng. Một kế hoạch quyết đoán.',
  'Nói điều thật, một cách tử tế.'],
'swords-2': ['do dự|bế tắc|cân nhắc|đình chiến', 'né tránh|chối bỏ|tê liệt|trốn tránh',
  'Bạn đang mắc kẹt giữa hai khả năng và tìm cách trì hoãn việc chọn. Tấm vải che mắt do chính bạn buộc lên, nên bạn hoàn toàn có thể tự tháo nó xuống.',
  'Bạn đang tránh một quyết định trong chuyện tình cảm. Bạn hãy đối diện với nó.',
  'Công việc đang bế tắc, hoặc có một quyết định mà bạn né tránh. Bạn nên thu thập đủ thông tin xác thực trước khi chọn.',
  'Bạn đang giằng co giữa nhiều hướng học. Bạn hãy chọn lấy một hướng và bắt đầu đi.',
  'Một quyết định tài chính của bạn vẫn đang bỏ ngỏ. Đã đến lúc bạn chốt lại.',
  'Bạn hãy gỡ tấm che mắt xuống và đưa ra lựa chọn.'],
'swords-3': ['tan vỡ|đau buồn|sự thật đau|giải toả', 'ôm nỗi đau|cay đắng|tự làm mình đau|không chịu lành',
  'Bạn đang mang một nỗi đau buốt, thường đến từ một sự thật hoặc một mất mát. Nỗi đau đó làm bạn tổn thương nhưng cũng làm mọi thứ sáng rõ. Bạn nên để nó được thoát ra.',
  'Chuyện tình cảm có thể mang đến đổ vỡ, sự phản bội hoặc một sự thật khó nghe. Bạn hãy cho mình cảm nhận trọn vẹn, sau đó vết thương sẽ lành.',
  'Trong công việc, bạn có thể gặp một bước lùi đau hoặc nhận lời phê bình nặng nề. Bạn hãy rút ra bài học và cho mình thời gian hồi phục.',
  'Việc học mang lại cho bạn một nỗi thất vọng. Cảm giác này khó chịu nhưng chỉ kéo dài trong chốc lát.',
  'Bạn có thể chịu một khoản thiệt hại xót xa. Bạn hãy hồi phục rồi gây dựng lại từ đầu.',
  'Bạn hãy để nước mắt được rơi. Vết thương chỉ lành sau khi bạn khóc xong.'],
'swords-4': ['nghỉ ngơi|hồi phục|suy ngẫm|rút lui', 'kiệt sức|bồn chồn|cô lập|né hành động',
  'Cơ thể và tâm trí bạn đang cần được nghỉ ngơi. Bạn nên lùi lại, dưỡng sức và suy ngẫm. Đây không phải thời điểm dành cho một trận chiến.',
  'Mối quan hệ của bạn đang đi qua một khoảng lặng. Bạn hãy dùng nó để nạp lại năng lượng.',
  'Bạn nên cho mình một quãng nghỉ ngắn. Sức lực hồi lại sẽ giúp bạn đón thử thách kế tiếp.',
  'Bạn hãy dừng lại một chút trước khi học tiếp. Trí óc của bạn đang cần khoảng trống đó.',
  'Bạn nên tạm hoãn các động thái về tiền bạc. Trong yên tĩnh, bạn sẽ nhìn lại rõ hơn.',
  'Bạn hãy nghỉ ngơi, và hãy nghỉ một cách trọn vẹn.'],
'swords-5': ['xung đột|thua thiệt|thắng mà trả giá|căng thẳng', 'thù địch|bắt nạt|không ai thắng|bẽ mặt',
  'Bạn đang ở giữa một cuộc xung đột mà không bên nào thật sự chiến thắng. Bạn hãy tự hỏi trận này có đáng để mình bước vào hay không.',
  'Những trận cãi vã và lời nói sắc nhọn đang xuất hiện. Thắng được cuộc tranh luận đôi khi khiến bạn mất luôn mối quan hệ.',
  'Nơi làm việc có mâu thuẫn, và phần thắng nếu có cũng rỗng ruột. Bạn nên chọn lọc trận nào đáng để mình tham gia.',
  'Sự ganh đua trong học tập đang làm bạn tổn thương. Bạn hãy dồn chú ý vào con đường riêng của mình.',
  'Một tranh chấp tiền bạc có thể nảy sinh. Bạn không nên tranh cãi vì những khoản không đáng.',
  'Bạn hãy rút khỏi cuộc chiến không thể thắng, và hãy rút lui trong tư thế đàng hoàng.'],
'swords-6': ['chuyển tiếp|đi tiếp|lành lại|nước lặng hơn', 'mắc kẹt|hành lý chưa xong|chống thay đổi|chuyến đi khó',
  'Bạn đang rời khỏi vùng nước xáo động để sang một mặt nước êm hơn. Đây là một cuộc chuyển tiếp âm thầm nhưng cần thiết.',
  'Bạn bước tiếp sau một chặng khó khăn trong tình cảm. Vết thương đang lành, và giữa hai người có thể xuất hiện một khoảng cách.',
  'Công việc của bạn đang dịch chuyển sang một hoàn cảnh dễ thở hơn. Một chuyến đi cũng có thể xuất hiện.',
  'Bạn đã đi qua một giai đoạn học tập vất vả. Kết quả của bạn đang tiến lên.',
  'Tình hình tài chính của bạn đang hồi phục từng chút một.',
  'Bạn hãy chèo thuyền về phía bờ bình yên. Nơi đó thật sự đang chờ bạn.'],
'swords-7': ['chiến lược|khôn khéo|tự lập|lách được', 'lừa dối|trộm cắp|tự lừa mình|bị bắt',
  'Bạn đang hành động một mình, lặng lẽ và có tính toán. Cách này có lúc là khôn ngoan, có lúc lại thành lén lút. Bạn nên soi lại động cơ của chính mình.',
  'Trong tình cảm có thể tồn tại điều giấu giếm hoặc sự dối lừa. Sự thành thật vẫn là con đường an toàn hơn cho bạn.',
  'Bạn làm việc theo chiến lược riêng và khá độc lập. Cũng có khả năng một người quanh bạn đang thiếu thẳng thắn.',
  'Bạn đang bị hấp dẫn bởi những lối đi tắt. Bạn nên cẩn thận vì chúng dễ gây tác dụng ngược.',
  'Bạn hãy đề phòng những trò lừa đảo. Đồng tiền của bạn cần được xoay xở một cách khôn khéo.',
  'Bạn hãy giữ sự khôn ngoan, nhưng đừng để nó trượt thành lén lút.'],
'swords-8': ['thấy bị trói|hạn chế|niềm tin tự giới hạn|bất lực', 'tâm lý nạn nhân|tê liệt|tự giam|tự phá',
  'Bạn có cảm giác mình đang bị trói buộc, nhưng sợi dây lỏng hơn vẻ bề ngoài rất nhiều. Nhà tù này phần lớn được dựng lên trong tâm trí bạn.',
  'Bạn cảm thấy bị giam trong mối quan hệ hiện tại. Thực ra bạn còn nhiều lựa chọn hơn những gì bạn hình dung.',
  'Bạn thấy mình bị bó buộc ở chỗ làm. Bạn hãy tìm những lối ra mà mắt bạn chưa kịp nhận ra.',
  'Khối lượng bài vở đang khiến bạn quá tải. Bạn hãy chia nó thành từng bước nhỏ.',
  'Dòng tiền của bạn đang bị siết lại. Bạn nên tìm thêm phương án xoay xở.',
  'Sợi dây quanh bạn đã nới ra. Bạn hãy cử động.'],
'swords-9': ['lo âu|lo lắng|ác mộng|tội lỗi', 'tuyệt vọng|mất hy vọng|nghĩ tới điều tệ nhất|cô lập',
  'Nỗi lo đang cướp đi giấc ngủ của bạn. Phần lớn những nỗi sợ đó lớn hơn sự thật rất nhiều. Bạn nên tìm một người để trò chuyện.',
  'Bạn đang lo lắng về mối quan hệ của mình. Bạn hãy nói ra thành lời thay vì để suy nghĩ xoáy tròn trong đầu.',
  'Công việc đang khiến bạn căng thẳng và bất an. Bạn nên đối chiếu lại với tình hình thực tế.',
  'Kỳ thi đang làm bạn lo lắng. Bạn hãy ôn tập cho kỹ, sau đó cho mình đi ngủ.',
  'Chuyện tiền bạc đang đè nặng tâm trí bạn. Bạn hãy lập một kế hoạch và san sẻ gánh nặng với người khác.',
  'Bạn hãy bật đèn lên. Con quái vật trong bóng tối sẽ thu nhỏ lại.'],
'swords-10': ['chạm đáy|kết thúc|phản bội|điều tệ nhất đã qua', 'hồi phục|chống lại cái kết|làm quá|sống sót',
  'Một cái kết đau đớn đã diễn ra trọn vẹn. Mọi chuyện khép lại tại đây. Chính vì đã khép lại, bình minh mới có chỗ để ló rạng.',
  'Chuyện tình cảm khép lại một cách đau đớn và dứt khoát. Bạn sẽ buồn rồi sẽ lành, bởi điều tệ nhất đã nằm lại phía sau.',
  'Một dự án hoặc một công việc của bạn kết thúc không đẹp. Bạn hãy hồi phục rồi bắt đầu lại từ đầu.',
  'Bạn vấp phải một lần thất bại trong học tập. Bài học đã nằm trong tay bạn, nên bạn hãy đi tiếp.',
  'Tài chính của bạn đang chạm đáy. Từ điểm này, đường đi duy nhất là hướng lên.',
  'Chuyện đã kết thúc. Bây giờ bạn có thể đứng dậy.'],
'swords-c0': ['tò mò|cảnh giác|ý tưởng mới|giao tiếp', 'đàm tiếu|lời vội|nghĩ tản mạn|dò xét',
  'Năng lượng của bạn đang tỉnh táo, ham tìm hiểu và thích trò chuyện. Những ý tưởng và tin tức mới sẽ đến với bạn. Bạn nên giữ chừng mực trong lời nói.',
  'Tình cảm mang màu sắc của những tin nhắn tò mò và các cuộc tranh luận vui vẻ. Chuyện đàm tiếu cũng có thể xen vào, nên bạn hãy cẩn trọng.',
  'Công việc của bạn cần ý tưởng mới, sự giao tiếp linh hoạt và một tinh thần cảnh giác.',
  'Trí tò mò của bạn đang được đánh thức. Bạn hãy tìm hiểu sâu và đặt nhiều câu hỏi.',
  'Bạn nên đề phòng những lời đồn thổi và các quyết định tiền bạc quá vội vàng.',
  'Bạn hãy đặt câu hỏi, sau đó dành thời gian lắng nghe.'],
'swords-c1': ['tham vọng|hành động|thẳng thắn|nhanh chóng', 'hung hăng|thiếu kiên nhẫn|liều lĩnh|tàn nhẫn',
  'Năng lượng của bạn đang nhanh, sắc bén và đầy quyết đoán. Bạn lao về phía trước với tốc độ cao. Bạn hãy chắc chắn mũi kiếm của mình đang chĩa đúng hướng.',
  'Bạn có thể gặp một người thẳng thắn và nhanh nhạy, hoặc chính bạn đưa ra một quyết định vội vàng. Bạn nên giảm tốc một chút.',
  'Công việc đòi hỏi bạn quyết nhanh và hành động táo bạo. Bạn hãy đề phòng sự hấp tấp.',
  'Bạn đang bước vào một đợt học dồn với cường độ cao. Cách này cho kết quả tốt nhưng lấy đi nhiều sức.',
  'Một nước cờ tài chính nhanh đang mở ra trước bạn. Bạn nên cân nhắc kỹ mức rủi ro.',
  'Bạn hãy tiến lên hết tốc lực, nhưng bạn nên nhìn bản đồ trước khi xuất phát.'],
'swords-c2': ['độc lập|phán đoán rõ|thật thà|ranh giới', 'lạnh lùng|cay đắng|cô lập|phê bình gắt',
  'Bạn đang sáng suốt, thành thật và tự chủ. Ánh nhìn của bạn xuyên qua mọi thứ giả tạo. Bạn nên thêm chút ấm áp vào những sự thật mình nói ra.',
  'Bạn giữ sự độc lập và thành thật trong tình cảm. Bạn cần những ranh giới rõ ràng.',
  'Bạn phán đoán sáng rõ và trao đổi thẳng thắn trong công việc. Bạn hãy dẫn dắt bằng sự chính trực.',
  'Bạn học theo lối phân tích và duy trì kỷ luật đều đặn.',
  'Các quyết định tiền bạc của bạn cần sự rõ ràng và tránh xa cảm tính.',
  'Bạn hãy nói ra sự thật bằng một giọng điệu tử tế.'],
'swords-c3': ['quyền hạn|trí tuệ|sự thật|kỷ luật', 'thao túng|độc tài|lạnh lùng|lạm quyền',
  'Đây là uy quyền đến từ trí tuệ. Lá bài nói về luật lệ minh bạch, phán xét công tâm và sức mạnh của lý trí. Bạn hãy dùng những điều đó để phục vụ lẽ công bằng.',
  'Bạn gắn bó với một người bạn đời sống bằng lý trí và giữ nguyên tắc. Cam kết giữa hai người được nói ra rõ ràng.',
  'Bạn dẫn dắt công việc bằng năng lực chuyên môn và cách hành xử công bằng.',
  'Bạn làm chủ môn học của mình nhờ kỷ luật và tư duy logic.',
  'Kế hoạch tài chính của bạn được xây bằng lý trí và có cấu trúc rõ ràng.',
  'Bạn hãy điều hành mọi việc bằng lý lẽ và sự công bằng.'],

'pentacles-1': ['cơ hội|thịnh vượng|dự án mới|thành hình', 'bỏ lỡ|thiếu thốn|kế hoạch kém|tham lam',
  'Một cơ hội cụ thể đang được đưa ra. Tiền mới, việc mới, thứ có thật. Nhận lấy.',
  'Một mối quan hệ mới ổn định, có triển vọng. Thật, không chỉ hấp dẫn.',
  'Việc mới, hợp đồng mới, dự án mới. Vững và có triển vọng.',
  'Một cơ hội thực tế mới: học bổng, khoá học, vị trí.',
  'Thu nhập mới hoặc cơ hội tài chính. Nắm lấy.',
  'Nhận đồng xu. Nó là thật.'],
'pentacles-2': ['cân bằng|thích nghi|tung hứng|linh hoạt', 'quá tải|lộn xộn|căng tiền|rơi bóng',
  'Bạn đang cùng lúc giữ nhiều việc trên tay và vẫn xoay xở được. Sự linh hoạt của bạn đang phát huy tác dụng, và hiện tại mọi thứ vẫn trong tầm kiểm soát.',
  'Bạn cần cân bằng chuyện tình cảm với những đòi hỏi khác trong đời sống. Bạn hãy chủ động sắp xếp thời gian cho người mình thương.',
  'Bạn đang gánh nhiều dự án cùng lúc. Bạn nên sắp xếp thứ tự ưu tiên và giữ cho mình sự linh hoạt.',
  'Bạn cần cân bằng giữa việc học và đời sống riêng. Một thời khoá biểu theo tuần sẽ giúp bạn.',
  'Bạn đang phải xoay dòng tiền qua lại. Bạn hãy lập ngân sách một cách cẩn thận.',
  'Bạn có thể giữ những quả bóng trên không thêm một thời gian, nhưng bạn không nên duy trì mãi.'],
'pentacles-3': ['làm nhóm|tay nghề|học nghề|chất lượng', 'thiếu phối hợp|chất lượng kém|không được ghi nhận|làm một mình',
  'Tay nghề của bạn đang được ghi nhận và tiếp tục được bồi đắp. Sự hợp tác cùng đôi tay khéo léo của bạn nhận lại phần thưởng xứng đáng.',
  'Hai người đang cùng nhau vun đắp mối quan hệ theo từng bước một.',
  'Công việc mang đến sự hợp tác, sự công nhận dành cho tay nghề và những sản phẩm chất lượng. Đây là thời điểm thuận lợi cho các dự án nhóm.',
  'Bạn học được nhiều điều từ những người xung quanh. Kỹ năng của bạn đi lên nhờ luyện tập.',
  'Tiền bạc đến với bạn qua tay nghề và qua những mối hợp tác.',
  'Bạn hãy làm thật tốt phần việc của mình, và hãy làm cùng người khác.'],
'pentacles-4': ['an toàn|kiểm soát|tiết kiệm|ổn định', 'tham lam|tích trữ|sợ mất|chiếm hữu',
  'Bạn đang siết chặt những gì mình đang có. Cảm giác an toàn rất quan trọng, nhưng khi bàn tay nắm quá chặt, dòng chảy sẽ dừng lại.',
  'Bạn có thể đang chiếm hữu hoặc sợ mất một người. Bạn hãy nới lỏng bàn tay của mình.',
  'Bạn coi trọng sự ổn định và quyền kiểm soát trong công việc. Bạn không nên chống lại mọi thay đổi.',
  'Bạn đang học theo lối chắc chắn và an toàn. Bạn đừng ngại thử những phương pháp mới.',
  'Bạn đang tiết kiệm và ưu tiên sự an toàn. Bạn nên cân bằng điều đó với lòng hào phóng.',
  'Bạn hãy giữ lại những gì thật sự quan trọng và buông nhẹ phần còn lại.'],
'pentacles-5': ['khó khăn|lo lắng|bị bỏ ngoài|bền bỉ', 'cô lập|tâm lý thiếu thốn|từ chối giúp đỡ|tuyệt vọng',
  'Bạn đang đi qua một đoạn đường khó và cảm thấy mình bị bỏ lại giữa trời lạnh. Sự giúp đỡ ở gần hơn bạn tưởng rất nhiều. Bạn hãy lên tiếng nhờ.',
  'Bạn thấy mình cô đơn hoặc thiếu người nâng đỡ trong tình cảm. Bạn hãy tìm đến người khác thay vì chịu đựng trong im lặng.',
  'Công việc của bạn đang bấp bênh, hoặc nơi làm có sức ép về tài chính. Bạn nên tìm nguồn hỗ trợ.',
  'Bạn đang vật lộn với việc học trong điều kiện thiếu thốn. Bạn hãy nhờ người khác giúp một tay.',
  'Bạn gặp khó khăn về tiền bạc. Bạn hãy tìm sự hỗ trợ, và giai đoạn này rồi sẽ qua.',
  'Cánh cửa đang ở ngay trước mặt bạn. Bạn hãy gõ vào nó.'],
'pentacles-6': ['hào phóng|cho đi|cân bằng|chia sẻ', 'điều kiện kèm|nợ nần|bất bình đẳng|lệch quyền lực',
  'Việc cho đi và nhận lại đang ở thế cân bằng quanh bạn. Lòng hào phóng lưu thông, và sự công bằng cũng vậy.',
  'Mối quan hệ của bạn đầy sự rộng lượng và nâng đỡ. Bạn nên xem lại cán cân giữa phần cho đi và phần nhận về.',
  'Bạn nhận được thù lao xứng đáng, sự hướng dẫn và sự hỗ trợ trong công việc. Dòng cho và nhận đang chảy đều.',
  'Thầy cô hoặc bạn bè đang giúp đỡ bạn trong việc học. Bạn hãy chia sẻ lại những gì mình biết.',
  'Tiền bạc đến với bạn nhờ lòng hào phóng, hoặc bạn gặp một dịp để cho đi.',
  'Bạn hãy cho đi trong khả năng của mình, và hãy nhận về những gì mình cần.'],
'pentacles-7': ['kiên nhẫn|đánh giá|nhìn dài|bền bỉ', 'nóng vội|chưa có quả|bực bội|đầu tư kém',
  'Bạn đã bỏ công gieo trồng và bây giờ bạn đang chờ. Bạn hãy quan sát sự lớn lên của cây, và đừng đào hạt giống lên để kiểm tra.',
  'Đây là lúc bạn nhìn lại một mối quan hệ. Bạn hãy tự hỏi những gì mình đầu tư vào đó có đang sinh hoa trái hay không.',
  'Công việc của bạn thuộc dạng đường dài. Kết quả đến chậm nhưng vẫn đang trên đường tới. Bạn nên dừng lại để đánh giá.',
  'Việc học của bạn tiến từng bước chậm. Bạn hãy giữ vững sự chuyên cần.',
  'Các khoản đầu tư của bạn cần thời gian dài. Bạn sẽ cần đến sự kiên nhẫn.',
  'Bạn hãy để mọi thứ lớn lên theo nhịp riêng của nó.'],
'pentacles-8': ['tay nghề|chăm chỉ|rèn kỹ năng|tận tâm', 'cầu toàn|đơn điệu|thiếu tham vọng|làm ẩu',
  'Bạn đang làm việc một cách tập trung và kiên nhẫn. Kỹ năng của bạn được bồi đắp qua từng lần lặp lại. Bạn đang giỏi lên từng ngày.',
  'Bạn vun đắp mối quan hệ bằng sự chăm chút và đều đặn.',
  'Bạn dành sự tận tâm cho nghề của mình. Sự thành thạo đến với bạn qua luyện tập.',
  'Bạn luyện tập đều đặn và lặp lại nhiều lần. Kiến thức ngấm vào bạn theo đúng cách đó.',
  'Tiền bạc đến với bạn nhờ tay nghề và nhịp làm việc đều đặn.',
  'Bạn hãy làm đủ số lần mà công việc đó đòi hỏi.'],
'pentacles-9': ['độc lập|tự đủ|sung túc|giá trị bản thân', 'làm quá|lệ thuộc|cô lập|hời hợt',
  'Sự thoải mái quanh bạn do chính bạn tạo ra. Bạn đang tự chủ và tận hưởng điều đó. Bạn hoàn toàn xứng đáng.',
  'Bạn đủ đầy trong chuyện tình cảm. Bạn hạnh phúc khi ở một mình cũng như khi có đôi.',
  'Bạn đạt được thành công và sự độc lập. Bạn đang hưởng thành quả từ công việc của mình.',
  'Bạn tự học và tự định hướng con đường của mình. Bạn hãy tin vào năng lực của bản thân.',
  'Bạn đang độc lập và thong thả về mặt tài chính.',
  'Bạn hãy tận hưởng những gì mình đã gây dựng.'],
'pentacles-10': ['di sản|của cải|gia đình|an toàn lâu dài', 'gia đình xung đột|mất tiền|bất ổn|nghĩ ngắn',
  'Lá bài nói về của cải bền vững, gồm gia đình, di sản và những nền móng tồn tại lâu hơn đời bạn. Bạn hãy suy nghĩ theo đơn vị thế hệ.',
  'Bạn có một mối quan hệ bền chặt, gắn với gia đình và hướng tới một tương lai chung.',
  'Bạn xây được thành công lâu dài, một sự nghiệp ổn định và những đóng góp có sức bền.',
  'Việc học là khoản đầu tư dài hạn của bạn. Gia đình đang đứng phía sau ủng hộ.',
  'Bạn hướng tới của cải tích luỹ, phần thừa kế và sự an toàn lâu dài.',
  'Bạn hãy xây dựng mọi thứ cho một chặng đường dài.'],
'pentacles-c0': ['tham vọng|học hỏi|khởi đầu thực tế|thành hình', 'trì hoãn|không tiến|mơ mộng|không theo tới cùng',
  'Bạn đang có một khởi đầu rất thực tế, có thể là một khoá học, một bản kế hoạch hoặc một bước đi đầu tiên được bạn coi trọng. Bạn hãy học hành cho tử tế.',
  'Một kết nối mới đang hình thành, thực tế và có nền tảng. Nó tiến chậm nhưng chân thật.',
  'Bạn có thể nhận một công việc mới, một khoá đào tạo hoặc một cơ hội mang tính thực tế.',
  'Bạn bắt đầu một khoá học mới, hoặc bạn đang nghiêm túc hơn với việc học của mình.',
  'Bạn đặt ra một mục tiêu tài chính mới. Bạn hãy bắt đầu tích luỹ.',
  'Bạn hãy bắt tay vào làm, và hãy học hành cho tử tế.'],
'pentacles-c1': ['đáng tin|nền nếp|chăm chỉ|trách nhiệm', 'chán nản|ứ đọng|cứng đầu|cầu toàn',
  'Bạn đang đi chậm, đáng tin cậy và có phương pháp. Cách làm này không gây hào hứng, nhưng việc giao cho bạn luôn được hoàn thành. Đó chính là món quà mà lá bài mang lại.',
  'Bạn gắn bó với một người bạn đời đáng tin và đều đặn. Tình yêu giữa hai người cháy chậm nhưng giữ được lâu.',
  'Bạn làm việc theo một phương pháp rõ ràng. Sự đáng tin cậy của bạn sẽ giành phần thắng.',
  'Bạn duy trì một nếp học đều đặn. Bạn tiến chậm nhưng rất chắc.',
  'Bạn chọn những phương án tiền bạc an toàn và thận trọng.',
  'Bạn hãy đi tiếp với một nhịp đều đặn.'],
'pentacles-c2': ['chăm sóc|thực tế|sung túc|an toàn', 'làm quá sức|bỏ bê mình|bao bọc|vật chất',
  'Bạn đang chăm sóc người khác bằng những việc rất cụ thể. Bạn mang lại cho mọi người sự an toàn về vật chất. Bạn cũng nên chăm sóc chính mình.',
  'Bạn có một người bạn đời biết chăm lo và sống thực tế. Tổ ấm và sự dễ chịu là điều hai người cùng hướng tới.',
  'Bạn quản lý công việc một cách thực tế và chăm lo cho cả nhóm.',
  'Bạn học một cách có tổ chức và đứng vững trên nền tảng của mình.',
  'Bạn quản lý tiền bạc theo lối thực tế và vẫn giữ được sự hào phóng.',
  'Bạn hãy chăm sóc bản thân với sự tận tình mà bạn dành cho mọi người.'],
'pentacles-c3': ['của cải|dẫn dắt|an toàn|kỷ luật', 'tham lam|vật chất|cứng đầu|kiểm soát bằng tiền',
  'Làm chủ thế giới vật chất. Ổn định và chu cấp mà bạn dựa vào được.',
  'Một người chu cấp ổn định, hào phóng. An toàn trong tình yêu.',
  'Thành công trong kinh doanh. Dẫn dắt bằng sự đáng tin.',
  'Làm chủ môn thực hành bằng kỷ luật.',
  'Của cải và làm chủ tài chính.',
  'Xây của cải, và giữ lòng hào phóng.']
});
