/* ============================ guides ============================
   Short pieces for the Học tab, written to be read on a phone: full
   sentences, one idea at a time, each paragraph leading into the next.
   `tags` are INTERESTS ids so the home screen can suggest guides. */
const GUIDES = [

/* ------------------------------------------------------------ tarot ---- */
{ id: 'tarot-overview', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Tổng quan bộ bài và cách học', en: 'The deck at a glance and how to learn it' },
  intro: { vi: 'Một bộ tarot có 78 lá và chia làm hai phần. Hai mươi hai lá Ẩn Chính kể lại hành trình lớn của một đời người, còn năm mươi sáu lá Ẩn Phụ nói về những chuyện diễn ra mỗi ngày. Bài này cho bạn cái khung chung, để về sau mỗi lá bạn học đều có một chỗ đứng rõ ràng.', en: 'A tarot deck has 78 cards in two parts. The twenty-two Major Arcana tell the great journey of a life, while the fifty-six Minor Arcana speak about the things that happen every day. This lesson gives you the frame, so that every card you learn later has a clear place in it.' },
  sections: [
    { h: { vi: '22 lá Ẩn Chính', en: 'The 22 Major Arcana' }, p: { vi: 'Các lá Ẩn Chính được đánh số từ 0, Gã Khờ, đến 21, Thế Giới. Mỗi lá là một bài học lớn: một khởi đầu, một lựa chọn, một mất mát, một niềm hy vọng hay một lần hoàn tất. Khi một lá Ẩn Chính xuất hiện trong trải bài, chuyện bạn đang hỏi thường quan trọng hơn bạn tưởng, và cũng ít nằm trong tay bạn hơn.', en: 'The Majors are numbered from 0, The Fool, to 21, The World. Each one is a big lesson: a beginning, a choice, a loss, a hope, or a completion. When a Major appears in a spread, the matter you are asking about is usually more important than it looks, and less in your hands than you would like.' } },
    { h: { vi: '56 lá Ẩn Phụ', en: 'The 56 Minor Arcana' }, p: { vi: 'Các lá Ẩn Phụ chia thành bốn chất, mỗi chất có mười bốn lá: từ Át đến Mười, rồi bốn lá hoàng gia là Tiểu Đồng, Kỵ Sĩ, Nữ Hoàng và Đức Vua. Gậy thuộc lửa, nói về hành động, đam mê và công việc. Cốc thuộc nước, nói về cảm xúc, tình yêu và các mối quan hệ. Kiếm thuộc khí, nói về suy nghĩ, lời nói và xung đột. Tiền thuộc đất, nói về tiền bạc, sức khỏe và những việc cụ thể. Ẩn Phụ kể chuyện hằng ngày, tức là những thứ bạn có thể thay đổi được.', en: 'The Minors come in four suits of fourteen cards: Ace to Ten, then the four court cards, Page, Knight, Queen and King. Wands belong to fire and speak of action, passion and work. Cups belong to water and speak of feelings, love and relationships. Swords belong to air and speak of thought, words and conflict. Pentacles belong to earth and speak of money, health and practical matters. The Minors tell the story of everyday life, which means the things you can actually change.' } },
    { h: { vi: 'Hành trình của Gã Khờ: chặng một (0–7)', en: 'The Fool\'s Journey, part one (0–7)' }, p: { vi: 'Bạn có thể xem 22 lá Ẩn Chính như một câu chuyện liền mạch. Gã Khờ (0) là chính bạn lúc mới lên đường, tay trắng nhưng tin đời. Trên đường đi, cậu gặp những người dạy cậu cách sống trong thế giới bên ngoài. Nhà Ảo Thuật (1) cho cậu thấy mình đã có đủ công cụ. Nữ Tư Tế (2) dạy cậu lắng nghe trực giác. Hoàng Hậu (3) là tình thương và sự nuôi dưỡng, còn Hoàng Đế (4) là kỷ luật và trật tự. Giáo Hoàng (5) đại diện cho truyền thống và người thầy. Đến Người Yêu (6), cậu đứng trước lựa chọn đầu tiên của trái tim, và với Cỗ Xe (7), cậu lần đầu tự cầm cương và giành chiến thắng.', en: 'You can read the 22 Majors as one continuous story. The Fool (0) is you at the start of the road, empty-handed but trusting life. Along the way he meets the people who teach him how to live in the outer world. The Magician (1) shows him that he already has every tool he needs. The High Priestess (2) teaches him to listen inward. The Empress (3) is love and nurture, and The Emperor (4) is discipline and order. The Hierophant (5) stands for tradition and the teacher. With The Lovers (6) he faces the heart\'s first real choice, and with The Chariot (7) he takes the reins for the first time and wins.' } },
    { h: { vi: 'Chặng hai (8–14): quay vào bên trong', en: 'Part two (8–14): turning inward' }, p: { vi: 'Sau khi thắng, cậu học được rằng sức mạnh thật sự không ồn ào. Sức Mạnh (8) là sự dịu dàng đủ để thuần một con sư tử. Ẩn Sĩ (9) là lúc cậu rút về một mình để hiểu chính mình. Bánh Xe (10) nhắc cậu rằng đời có lúc lên lúc xuống, và không phải điều gì cũng do mình quyết. Công Lý (11) buộc cậu chịu trách nhiệm cho những việc đã làm. Người Treo Ngược (12) dạy cậu biết dừng lại và nhìn theo một cách khác. Tử Thần (13) là một kết thúc cần thiết để bắt đầu lại, và Tiết Độ (14) là sự cân bằng cậu tìm thấy sau tất cả.', en: 'Having won, he learns that real strength makes no noise. Strength (8) is the gentleness that can tame a lion. The Hermit (9) is his retreat into solitude to understand himself. The Wheel (10) reminds him that life rises and falls, and that not everything is his to decide. Justice (11) makes him answer for what he has done. The Hanged Man (12) teaches him to stop and look at things another way. Death (13) is the ending that makes a new start possible, and Temperance (14) is the balance he finds after all of it.' } },
    { h: { vi: 'Chặng ba (15–21): bóng tối và ánh sáng', en: 'Part three (15–21): darkness and light' }, p: { vi: 'Chặng cuối là phần khó nhất, nhưng cũng đẹp nhất. Ác Quỷ (15) là những thứ đang trói cậu: thói quen, ham muốn và nỗi sợ. Tòa Tháp (16) là cú sập của tất cả những gì được xây trên nền giả. Sau cơn bão, Ngôi Sao (17) mang hy vọng trở lại. Mặt Trăng (18) là đoạn đường mờ sương mà cậu phải đi bằng linh cảm. Rồi Mặt Trời (19) mang đến niềm vui trong sáng khi bóng tối đã ở lại phía sau. Phán Xét (20) là tiếng gọi thức tỉnh, khi cậu nhìn lại cả hành trình. Và Thế Giới (21) là lúc cậu về đến nơi, trọn vẹn, sẵn sàng lên đường lần nữa với con số 0.', en: 'The last stretch is the hardest, and also the most beautiful. The Devil (15) is everything that binds him: habits, cravings and fears. The Tower (16) is the collapse of all that was built on false ground. After the storm, The Star (17) brings hope back. The Moon (18) is the foggy road he must walk by instinct. Then The Sun (19) brings clear joy once the darkness is behind him. Judgement (20) is the wake-up call, when he looks back over the whole road. And The World (21) is his arrival, whole and ready to set out once more as 0.' } },
    { h: { vi: 'Cách học trong khóa này', en: 'How to learn in this course' }, p: { vi: 'Hãy học Ẩn Chính trước, theo đúng thứ tự của câu chuyện ở trên. Mỗi ngày bạn mở một lá, đọc trang của lá đó, rồi tự kể lại vì sao lá này lại đứng sau lá trước. Sau hai mươi hai ngày, bạn chuyển sang Ẩn Phụ và học theo từng chất, từ Át đến Đức Vua. Mỗi sáng, bạn rút một lá và viết một câu về điều bạn nghĩ nó muốn nói, rồi mới đọc trang của nó. Phần Trải bài nên để sau cùng, khi các lá đã trở thành những gương mặt quen.', en: 'Learn the Majors first, in the order of the story above. Each day, open one card, read its page, then retell in your own words why this card follows the one before. After twenty-two days, move on to the Minors and take them one suit at a time, from Ace to King. Each morning, draw a card and write one line about what you think it is saying, and only then read its page. Leave the Spreads section for last, once the cards have become familiar faces.' } }
  ] },
{ id: 'tarot-start', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Bắt đầu học tarot', en: 'Getting started with tarot' },
  intro: { vi: 'Bạn không cần thuộc hết 78 lá trước khi rút lá đầu tiên. Thứ bạn thật sự cần là một bộ bài, một câu hỏi rõ ràng và một thói quen nhỏ mỗi ngày. Bốn bước dưới đây là đủ để bắt đầu.', en: 'You do not need to memorise all 78 cards before your first draw. What you really need is one deck, one clear question and a small daily habit. The four steps below are enough to begin.' },
  sections: [
    { h: { vi: 'Chỉ dùng một bộ bài', en: 'Use one deck only' }, p: { vi: 'Hãy bắt đầu với bộ Rider–Waite–Smith hoặc một bộ được vẽ theo nó. Hầu hết sách và video đều dựa trên hình ảnh của bộ này, và cả 78 lá đều có tranh, nên bức tranh sẽ dạy bạn trước cả khi bạn thuộc nghĩa.', en: 'Start with the Rider–Waite–Smith deck or one drawn after it. Most books and videos assume its pictures, and all 78 cards are illustrated, so the pictures teach you before you have learned the meanings.' } },
    { h: { vi: 'Học cấu trúc trước, nghĩa sau', en: 'Structure first, meanings later' }, p: { vi: 'Hãy nắm bộ khung trước: 22 lá Ẩn Chính là những bài học lớn, còn 56 lá Ẩn Phụ là chuyện hằng ngày, chia thành bốn chất. Gậy là lửa và hành động, Cốc là nước và cảm xúc, Kiếm là khí và suy nghĩ, Tiền là đất và vật chất. Khi đã biết khung này, bạn có thể đoán được nghĩa của một lá mình chưa từng học.', en: 'Get the skeleton first: the 22 Majors are the big lessons, and the 56 Minors are daily life, divided into four suits. Wands are fire and action, Cups are water and feeling, Swords are air and thought, Pentacles are earth and the material world. Once you know this frame, you can make a fair guess at a card you have never studied.' } },
    { h: { vi: 'Mỗi ngày một lá', en: 'One card a day' }, p: { vi: 'Sáng nào bạn cũng rút một lá. Bạn viết ra điều mình nhìn thấy và điều mình nghĩ nó muốn nói, rồi mới tra nghĩa. Khoảng cách giữa điều bạn đoán và điều sách viết chính là nơi bạn học được nhiều nhất. Đến tối, bạn nhìn lại xem lá bài ấy khớp với ngày của mình đến đâu.', en: 'Every morning, pull one card. Write down what you see and what you think it is saying, and only then look up the meaning. The gap between your guess and the book is where most of the learning happens. In the evening, look back and see how well the card matched your day.' } },
    { h: { vi: 'Câu hỏi quyết định câu trả lời', en: 'The question shapes the answer' }, p: { vi: 'Một câu hỏi tốt cho một câu trả lời tốt. "Mình cần biết gì về chuyện này?" luôn hay hơn "Có nên hay không?", và "Mình nên làm gì để…?" hay hơn "Khi nào?". Một lá bài trả lời tốt câu hỏi cái gì, trả lời dở câu hỏi có hay không, và gần như không trả lời được câu hỏi khi nào.', en: 'A good question earns a good answer. "What do I need to know about this?" always works better than "Should I or not?", and "What should I do to…?" works better than "When?". A single card answers what very well, answers yes-or-no poorly, and can hardly answer when at all.' } }
  ] },
{ id: 'tarot-reversed', cat: 'tarot', badge: 'conv', tags: ['tarot'],
  title: { vi: 'Lá ngược: có nên đọc không?', en: 'Reversed cards: should you read them?' },
  intro: { vi: 'Không có luật nào bắt buộc bạn phải đọc lá ngược. Nhiều người đọc, nhiều người không, và cả hai cách đều cho ra những trải bài tốt. Điều quan trọng là bạn chọn một cách và giữ nó.', en: 'There is no rule that forces you to read reversed cards. Many readers do, many do not, and both ways produce good readings. What matters is that you choose one way and keep to it.' },
  sections: [
    { h: { vi: 'Cách một: không đọc ngược', en: 'Way one: no reversals' }, p: { vi: 'Theo cách này, mỗi lá bài có sẵn một mặt sáng và một mặt tối. Bạn nhìn vào câu hỏi và các lá xung quanh để biết lá này đang nói về mặt nào. Có một mẹo nhỏ rất hiệu quả: hãy thêm chữ "quá" vào trước từ khóa tích cực, bạn sẽ có ngay từ khóa tiêu cực. Tự tin quá thì thành kiêu ngạo, chủ động quá thì thành áp đặt.', en: 'In this way, every card already has a bright side and a shadow side. You look at the question and at the neighbouring cards to tell which side is speaking. There is a small trick that works very well: put the word "too" in front of a positive keyword and you get the negative one. Too confident becomes arrogant, too active becomes pushy.' } },
    { h: { vi: 'Cách hai: đọc ngược', en: 'Way two: with reversals' }, p: { vi: 'Nếu bạn đọc lá ngược, hãy hiểu nó là năng lượng của lá đang bị chặn lại, bị trì hoãn, hoặc quay vào bên trong. Ngược không có nghĩa là xấu. Mười Kiếm ngược, chẳng hạn, thường có nghĩa là điều tệ nhất đã qua rồi.', en: 'If you do read reversals, think of them as the card\'s energy being blocked, delayed, or turned inward. Reversed does not mean bad. The Ten of Swords reversed, for example, usually means that the worst is already over.' } },
    { h: { vi: 'Chọn một cách và giữ nó', en: 'Pick one way and keep it' }, p: { vi: 'Bạn nên quyết định trước khi xào bài. Nếu đổi cách giữa chừng chỉ vì không thích câu trả lời, thì bạn đang tự lừa mình, và trải bài sẽ không còn nói được điều gì đáng tin.', en: 'Decide before you shuffle. If you switch halfway simply because you dislike the answer, you are fooling yourself, and the spread can no longer tell you anything you can trust.' } }
  ] },
{ id: 'tarot-court', cat: 'tarot', badge: 'conv', tags: ['tarot', 'love'],
  title: { vi: 'Lá hoàng gia: là người hay là tính cách?', en: 'Court cards: a person or a trait?' },
  intro: { vi: 'Mười sáu lá hoàng gia, gồm Tiểu Đồng, Kỵ Sĩ, Nữ Hoàng và Đức Vua của bốn chất, là phần khó nhất với người mới. Lý do là chúng có thể mang ba nghĩa cùng lúc: một người cụ thể, một phần trong con người bạn, hoặc một cách hành xử.', en: 'The sixteen court cards, the Page, Knight, Queen and King of each suit, are the hardest part for beginners. The reason is that they can carry three meanings at once: a specific person, a part of yourself, or a way of behaving.' },
  sections: [
    { h: { vi: 'Bốn cấp bậc', en: 'Four ranks' }, p: { vi: 'Tiểu Đồng là người trẻ, là một tin nhắn, hoặc là bước đầu học một điều mới. Kỵ Sĩ là hành động và di chuyển, đôi khi hơi quá đà. Nữ Hoàng là người đã làm chủ chất đó từ bên trong. Đức Vua là người thể hiện chất đó ra bên ngoài và có quyền quyết định.', en: 'The Page is a young person, a message, or the first step of learning something new. The Knight is action and movement, sometimes a little too much of it. The Queen has mastered the suit from within. The King expresses the suit outwardly and holds the authority to decide.' } },
    { h: { vi: 'Khi bạn hỏi về một người', en: 'When you ask about a person' }, p: { vi: 'Lá hoàng gia mô tả tính cách chứ không cố định tuổi hay giới tính. Nữ Hoàng Kiếm hoàn toàn có thể là một người đàn ông sắc sảo. Vì vậy, hãy nhìn vào chất trước: Gậy nóng và nhiệt, Cốc giàu tình cảm, Kiếm thiên về lý trí, còn Tiền thì thực tế.', en: 'A court card describes character rather than a fixed age or gender. The Queen of Swords can perfectly well be a sharp-minded man. So look at the suit first: Wands are hot and eager, Cups are emotional, Swords are rational, and Pentacles are practical.' } }
  ] },

/* -------------------------------------------------------- lenormand ---- */
{ id: 'len-vs-tarot', cat: 'lenormand', badge: 'doc', tags: ['lenormand'],
  title: { vi: 'Lenormand khác tarot ở đâu', en: 'How Lenormand differs from tarot' },
  intro: { vi: 'Lenormand là một bộ bài 36 lá, và mỗi lá là một vật cụ thể: Kỵ Mã, Cỏ Ba Lá, Con Thuyền, Ngôi Nhà. Điểm khác lớn nhất so với tarot là bạn không đọc từng lá một, mà đọc những lá đứng cạnh nhau như đọc một câu văn.', en: 'Lenormand is a deck of 36 cards, and each card is a concrete thing: the Rider, the Clover, the Ship, the House. The biggest difference from tarot is that you do not read one card at a time; you read the cards standing next to each other, the way you would read a sentence.' },
  sections: [
    { h: { vi: 'Mỗi lá là một danh từ', en: 'Each card is a noun' }, p: { vi: 'Tarot cho bạn một khung cảnh với nhiều tầng nghĩa, còn Lenormand chỉ cho bạn một từ. Lá Thư nghĩa là một lá thư, và Chìa Khóa nghĩa là mở ra, là điều chắc chắn. Nghĩa thật sự chỉ xuất hiện khi bạn ghép các từ lại với nhau. Chẳng hạn, Kỵ Mã đứng cạnh Lá Thư nghĩa là một tin nhắn đang trên đường đến.', en: 'Tarot gives you a scene with many layers of meaning, while Lenormand gives you a single word. The Letter means a letter, and the Key means opening, or certainty. The real meaning only appears when you join the words together. The Rider next to the Letter, for instance, means a message that is on its way.' } },
    { h: { vi: 'Không có lá ngược', en: 'There are no reversals' }, p: { vi: 'Lenormand không đọc lá ngược. Thay vào đó, mỗi lá mang sẵn một sắc thái: tích cực, trung tính hoặc tiêu cực. Lá đứng bên cạnh sẽ làm dịu đi hoặc làm nặng thêm sắc thái ấy.', en: 'Lenormand does not use reversals. Instead, every card carries a built-in tone: positive, neutral or negative. The card beside it softens or sharpens that tone.' } },
    { h: { vi: 'Bộ bài đến từ đâu', en: 'Where the deck comes from' }, p: { vi: 'Bộ bài này bắt nguồn từ một trò chơi bàn cờ ở Đức vào năm 1799 và chỉ mang tên bà Lenormand sau khi bà qua đời. Trên mỗi lá đều in kèm một lá bài Tây từ bộ 36 lá, và đó là tương ứng thật sự duy nhất của Lenormand. Lenormand không có tương ứng với cung hoàng đạo; những bảng cung mà bạn thấy trên mạng là do từng tác giả tự đặt ra.', en: 'The deck began as a German board game in 1799 and only took Mlle Lenormand\'s name after her death. Every card carries a playing card from the 36-card pack, and that is Lenormand\'s only real correspondence. Lenormand has no zodiac correspondences; the sign tables you see online are each author\'s own invention.' } }
  ] },
{ id: 'len-pairs', cat: 'lenormand', badge: 'doc', tags: ['lenormand'],
  title: { vi: 'Đọc hai lá và ba lá', en: 'Reading two and three cards' },
  intro: { vi: 'Đây là bài tập cơ bản nhất của Lenormand, và cũng là kỹ năng bạn sẽ dùng mãi về sau. Hai lá ghép lại thành một ý, còn ba lá ghép lại thành một câu chuyện nhỏ.', en: 'This is the most basic Lenormand exercise, and also the skill you will keep using for the rest of your practice. Two cards together make one idea, and three cards together make a small story.' },
  sections: [
    { h: { vi: 'Hai lá', en: 'Two cards' }, p: { vi: 'Lá đầu tiên là chủ đề, còn lá thứ hai bổ nghĩa cho nó. Ngôi Nhà đứng trước Trái Tim nói về một gia đình ấm áp. Nhưng nếu Trái Tim đứng trước Ngôi Nhà, thì đó lại là tình cảm đang hướng về gia đình, một mong muốn ổn định. Bạn thấy đấy, chỉ cần đổi thứ tự là nghĩa đã khác đi.', en: 'The first card is the subject, and the second card describes it. The House before the Heart speaks of a warm family home. But if the Heart comes before the House, it becomes love turned toward home, a wish to settle down. As you can see, swapping the order changes the meaning.' } },
    { h: { vi: 'Ba lá', en: 'Three cards' }, p: { vi: 'Với ba lá, bạn có hai cách đọc. Cách thứ nhất là xem lá giữa làm trọng tâm, còn hai lá hai bên bổ nghĩa cho nó. Cách thứ hai là đọc từ trái sang phải như quá khứ, hiện tại và tương lai. Hãy chọn một cách trước khi rút bài.', en: 'With three cards you have two ways to read. The first treats the middle card as the focus, with the two outer cards describing it. The second reads from left to right as past, present and future. Choose your way before you draw.' } },
    { h: { vi: 'Luyện mỗi ngày', en: 'Daily practice' }, p: { vi: 'Mỗi sáng, bạn rút ba lá và viết một câu duy nhất. Đến tối, bạn kiểm tra lại xem câu đó đúng đến đâu. Sau khoảng một tháng, bạn sẽ đọc được các cặp lá mà không cần tra nghĩa nữa.', en: 'Each morning, draw three cards and write a single sentence. In the evening, check how well that sentence held up. After about a month, you will be reading pairs without looking anything up.' } }
  ] },

/* ------------------------------------------------------------ astro ---- */
{ id: 'astro-big3', cat: 'astro', badge: 'doc', tags: ['astro'],
  title: { vi: 'Cung Mặt Trời, Mặt Trăng và cung Mọc', en: 'Sun, Moon and Rising' },
  intro: { vi: 'Khi bạn nói "mình là Sư Tử", bạn đang nói về cung Mặt Trời của mình. Nhưng cung Mặt Trời chỉ là một phần của bản đồ sao. Có hai phần nữa cũng quan trọng không kém, đó là cung Mặt Trăng và cung Mọc.', en: 'When you say "I am a Leo", you are talking about your Sun sign. But the Sun sign is only one part of the birth chart. Two other parts matter just as much: the Moon sign and the Rising sign.' },
  sections: [
    { h: { vi: 'Mặt Trời: bạn là ai', en: 'The Sun: who you are' }, p: { vi: 'Cung Mặt Trời được tính từ ngày sinh của bạn. Nó nói về cái tôi, về hướng sống và về con người mà bạn muốn trở thành. Ứng dụng này tính cung Mặt Trời cho bạn ngay khi bạn nhập ngày sinh.', en: 'Your Sun sign comes from your date of birth. It speaks of your core self, your direction in life, and the person you want to become. This app works out your Sun sign as soon as you enter your birthday.' } },
    { h: { vi: 'Mặt Trăng: bạn cảm thấy thế nào', en: 'The Moon: how you feel' }, p: { vi: 'Để biết cung Mặt Trăng, bạn cần giờ sinh gần đúng. Mặt Trăng nói về cảm xúc, thói quen và những gì bạn cần để thấy an toàn. Nhiều người nhận ra mình trong cung Mặt Trăng còn rõ hơn cả cung Mặt Trời.', en: 'To know your Moon sign, you need a roughly correct birth time. The Moon speaks of your feelings, your habits, and what you need in order to feel safe. Many people recognise themselves in their Moon sign even more clearly than in their Sun sign.' } },
    { h: { vi: 'Cung Mọc: người khác thấy bạn ra sao', en: 'Rising: how others see you' }, p: { vi: 'Cung Mọc đòi hỏi giờ sinh và nơi sinh chính xác, vì nó đổi sau mỗi hai giờ. Đây là ấn tượng đầu tiên bạn để lại, là phong cách và vẻ ngoài của bạn. Nếu muốn có một bản đồ sao đầy đủ, bạn cần cả ba thứ: ngày sinh, giờ sinh và nơi sinh.', en: 'The Rising sign needs your exact birth time and place, because it changes every two hours. It is the first impression you leave, your style, your appearance. If you want a full birth chart, you need all three: the date, the time and the place of birth.' } }
  ] },
{ id: 'astro-elements', cat: 'astro', badge: 'doc', tags: ['astro', 'tarot'],
  title: { vi: 'Bốn nguyên tố và ba tính chất', en: 'Four elements and three modes' },
  intro: { vi: 'Mười hai cung hoàng đạo được chia theo hai cách. Nguyên tố cho biết một cung được "làm bằng gì", còn tính chất cho biết cung ấy "chuyển động ra sao". Khi nắm được hai cách chia này, bạn sẽ hiểu bất kỳ cung nào nhanh hơn rất nhiều.', en: 'The twelve signs are divided in two ways. The element tells you what a sign is "made of", and the mode tells you how that sign "moves". Once you know these two divisions, you will understand any sign much faster.' },
  sections: [
    { h: { vi: 'Bốn nguyên tố', en: 'The four elements' }, p: { vi: 'Lửa gồm Bạch Dương, Sư Tử và Nhân Mã: hành động, nhiệt huyết và tự tin. Đất gồm Kim Ngưu, Xử Nữ và Ma Kết: thực tế, bền bỉ và gắn với vật chất. Khí gồm Song Tử, Thiên Bình và Bảo Bình: suy nghĩ, giao tiếp và ý tưởng. Nước gồm Cự Giải, Bọ Cạp và Song Ngư: cảm xúc, trực giác và ký ức. Trong tarot, bốn nguyên tố này tương ứng với bốn chất: Gậy là lửa, Tiền là đất, Kiếm là khí và Cốc là nước.', en: 'Fire holds Aries, Leo and Sagittarius: action, heat and confidence. Earth holds Taurus, Virgo and Capricorn: practical, steady and tied to the material world. Air holds Gemini, Libra and Aquarius: thought, communication and ideas. Water holds Cancer, Scorpio and Pisces: feeling, intuition and memory. In tarot, the four elements match the four suits: Wands are fire, Pentacles are earth, Swords are air and Cups are water.' } },
    { h: { vi: 'Ba tính chất', en: 'The three modes' }, p: { vi: 'Các cung khởi đầu là Bạch Dương, Cự Giải, Thiên Bình và Ma Kết. Mỗi cung mở ra một mùa mới, nên chúng giỏi bắt đầu mọi việc. Các cung cố định là Kim Ngưu, Sư Tử, Bọ Cạp và Bảo Bình. Chúng giữ và duy trì, đôi khi hơi bướng. Các cung biến đổi là Song Tử, Xử Nữ, Nhân Mã và Song Ngư. Chúng thích nghi, linh hoạt và biết cách kết thúc.', en: 'The cardinal signs are Aries, Cancer, Libra and Capricorn. Each one opens a new season, so they are good at starting things. The fixed signs are Taurus, Leo, Scorpio and Aquarius. They hold and maintain, and can be a little stubborn. The mutable signs are Gemini, Virgo, Sagittarius and Pisces. They adapt, stay flexible, and know how to bring things to a close.' } }
  ] },
{ id: 'astro-moon', cat: 'astro', badge: 'conv', tags: ['astro', 'manifest'],
  title: { vi: 'Chu kỳ trăng và cách dùng nó', en: 'The Moon cycle and how to use it' },
  intro: { vi: 'Mặt Trăng đi hết một vòng trong khoảng 29 ngày rưỡi, từ trăng non đến trăng tròn rồi trở lại trăng non. Nhiều người dùng vòng quay này như một nhịp sống: có lúc để gieo, có lúc để nhìn lại, và có lúc để buông. Đây là một thói quen đẹp chứ không phải một quy luật, nên bạn hãy thử và giữ lại những gì hợp với mình.', en: 'The Moon completes one cycle in about twenty-nine and a half days, from new to full and back to new again. Many people use this turning as a rhythm for life: there is a time to plant, a time to look back, and a time to let go. It is a lovely habit rather than a law, so try it and keep whatever suits you.' },
  sections: [
    { h: { vi: 'Trăng non: gieo hạt', en: 'New Moon: planting' }, p: { vi: 'Vào đêm trăng non, bầu trời tối nhất và vòng quay mới bắt đầu. Đây là lúc thích hợp để bạn viết ra điều mình muốn bắt đầu trong tháng này. Hãy viết ngắn và cụ thể, chẳng hạn "mình sẽ tập thể dục ba buổi mỗi tuần" thay vì "mình sẽ khỏe hơn". Một ý định rõ ràng sẽ dễ theo đuổi hơn rất nhiều.', en: 'On the night of the new Moon the sky is at its darkest and a new cycle begins. This is a good moment to write down what you want to start this month. Keep it short and specific, for example "I will exercise three times a week" rather than "I will get healthier". A clear intention is far easier to follow through.' } },
    { h: { vi: 'Trăng tròn: nhìn lại', en: 'Full Moon: looking back' }, p: { vi: 'Khoảng hai tuần sau, trăng tròn là lúc sáng nhất trong tháng. Những gì bạn gieo từ đầu chu kỳ bây giờ đã lộ rõ, nên đây là thời điểm để nhìn lại: điều gì đang tiến triển, điều gì cần buông. Nhiều người thích rút bài vào đêm trăng tròn, vì cảm xúc lúc này thường rõ ràng và dễ gọi tên hơn.', en: 'About two weeks later, the full Moon is the brightest point of the month. Whatever you planted at the start of the cycle has now come to light, so this is the time to look back: what is moving forward, and what needs to be released. Many people like to draw cards on a full-Moon night, because feelings tend to be clearer and easier to name.' } },
    { h: { vi: 'Trăng khuyết: dọn dẹp và nghỉ', en: 'Waning Moon: clearing and rest' }, p: { vi: 'Từ trăng tròn cho đến trăng non tiếp theo, ánh trăng nhỏ dần. Đây là quãng để bạn dọn dẹp, kết thúc những việc dang dở và cho mình nghỉ ngơi. Bạn không nên bắt đầu việc lớn trong giai đoạn này; hãy để dành sức cho vòng quay mới.', en: 'From the full Moon to the next new Moon, the light shrinks night by night. This is the stretch for clearing up, finishing what is unfinished, and giving yourself some rest. It is not the time to start anything big; save your energy for the next cycle.' } },
    { h: { vi: 'Cách dùng cho gọn', en: 'A simple way to use it' }, p: { vi: 'Bạn chỉ cần nhớ ba mốc: trăng non để đặt ý định, trăng tròn để nhìn lại, và trăng khuyết để buông. Ứng dụng luôn hiển thị pha trăng của hôm nay trên trang chủ, nên bạn không cần tự tính.', en: 'You only need to remember three points: the new Moon to set an intention, the full Moon to look back, and the waning Moon to let go. The app always shows today\'s Moon phase on the home screen, so you never have to work it out yourself.' } }
  ] },
{ id: 'astro-retro', cat: 'astro', badge: 'doc', tags: ['astro', 'work'],
  title: { vi: 'Sao Thủy nghịch hành là gì', en: 'What Mercury retrograde means' },
  intro: { vi: 'Ba hoặc bốn lần mỗi năm, Sao Thủy nhìn từ Trái Đất có vẻ như đang đi lùi trong khoảng ba tuần. Thật ra hành tinh không hề lùi; đó chỉ là hiệu ứng góc nhìn khi hai hành tinh vượt qua nhau trên quỹ đạo.', en: 'Three or four times a year, Mercury appears from Earth to move backwards for about three weeks. The planet is not really reversing; it is a trick of perspective as the two planets pass each other in their orbits.' },
  sections: [
    { h: { vi: 'Vì sao người ta hay đổ lỗi cho nó', en: 'Why it gets the blame' }, p: { vi: 'Trong chiêm tinh, Sao Thủy gắn với giao tiếp, đi lại, hợp đồng và máy móc. Vì vậy, mỗi khi Sao Thủy nghịch hành, người ta thường đổ lỗi cho nó về những tin nhắn bị hiểu lầm, những chuyến đi trễ giờ hay chiếc điện thoại bỗng dưng hỏng.', en: 'In astrology, Mercury is linked to communication, travel, contracts and machines. So whenever Mercury goes retrograde, people tend to blame it for misread messages, late journeys and the phone that suddenly stops working.' } },
    { h: { vi: 'Cách dùng cho có ích', en: 'A useful way to treat it' }, p: { vi: 'Bạn có thể xem giai đoạn này như một lời nhắc nhở nhẹ nhàng: đọc lại tin nhắn trước khi gửi, sao lưu dữ liệu, kiểm tra kỹ hợp đồng, và liên lạc lại với những người cũ nếu cần. Nhưng đừng hoãn cả cuộc đời chỉ vì một hành tinh; những việc quan trọng vẫn có thể làm được, chỉ cần cẩn thận hơn một chút.', en: 'You can treat this period as a gentle reminder: re-read a message before sending it, back up your data, check contracts carefully, and reconnect with old contacts if you need to. But do not put your whole life on hold because of one planet; important things can still be done, just with a little more care.' } }
  ] },

/* --------------------------------------------------------- manifest ---- */
{ id: 'mani-what', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Manifestation là gì', en: 'What manifestation is' },
  intro: { vi: 'Manifestation là việc bạn nói rõ điều mình muốn, tin rằng điều đó có thể xảy ra, và hành động như thể nó đang trên đường đến. Phần "hành động" là phần người ta hay quên nhất, nhưng lại là phần quan trọng nhất.', en: 'Manifestation means naming clearly what you want, believing that it is possible, and acting as if it is already on its way. The "acting" part is the one people forget most often, and it is also the part that matters most.' },
  sections: [
    { h: { vi: 'Nó làm được gì cho bạn', en: 'What it can do for you' }, p: { vi: 'Khi bạn gọi tên mục tiêu một cách rõ ràng, bộ não sẽ bắt đầu để ý những cơ hội liên quan mà trước đây bạn bỏ qua. Bạn sẽ dám mở lời, dám nộp đơn và dám hẹn gặp. Đó chính là cách "vũ trụ đáp lại" theo nghĩa thực tế nhất.', en: 'When you name a goal clearly, your mind starts noticing the related chances you used to walk past. You dare to speak up, to apply, to ask for the meeting. That is what "the universe answering" looks like in the most practical sense.' } },
    { h: { vi: 'Nó không làm được gì', en: 'What it cannot do' }, p: { vi: 'Manifestation không thay đổi được người khác, và cũng không thay thế được việc học, việc làm hay việc đi khám bệnh. Nếu có ai nói rằng bạn ốm hay nghèo là vì "rung động thấp", thì họ đang đổ lỗi cho bạn chứ không phải đang dạy bạn.', en: 'Manifestation cannot change other people, and it does not replace studying, working, or seeing a doctor. If someone tells you that you are sick or poor because of "low vibration", they are blaming you, not teaching you.' } },
    { h: { vi: 'Bắt đầu như thế nào', en: 'How to begin' }, p: { vi: 'Hãy viết một câu ở thì hiện tại, chẳng hạn: "Mình đang làm công việc mình thích, với mức lương đủ để sống thoải mái." Mỗi sáng bạn đọc lại câu ấy, rồi trong ngày làm một việc nhỏ hướng về nó. Chỉ cần vậy là bạn đã bắt đầu đúng cách.', en: 'Write one sentence in the present tense, for example: "I am doing work I enjoy, and it pays me enough to live comfortably." Read it every morning, then do one small thing during the day that moves toward it. That alone is a proper start.' } }
  ] },
{ id: 'mani-script', cat: 'manifest', badge: 'conv', tags: ['manifest', 'love', 'work'],
  title: { vi: 'Viết kịch bản (scripting)', en: 'Scripting' },
  intro: { vi: 'Scripting là cách bạn viết một trang nhật ký như thể điều mình mong muốn đã xảy ra rồi. Bạn càng viết cụ thể, càng tả rõ mình thấy gì, nghe gì và cảm thấy gì, thì bài tập càng có tác dụng.', en: 'Scripting means writing a diary page as if the thing you want has already happened. The more specific you are about what you see, hear and feel, the better the exercise works.' },
  sections: [
    { h: { vi: 'Viết như thế nào', en: 'How to write it' }, p: { vi: 'Bạn dùng thì hiện tại hoặc quá khứ gần, ví dụ: "Hôm nay mình vừa ký hợp đồng mới. Sếp bắt tay mình và nói rằng…". Bạn kết bài bằng một lời cảm ơn. Hãy viết liền trong mười phút và đừng dừng lại để sửa.', en: 'Use the present or the recent past tense, for example: "Today I signed the new contract. My manager shook my hand and said…". End the page with a word of thanks. Write for ten minutes without stopping to edit.' } },
    { h: { vi: 'Viết khi nào', en: 'When to write' }, p: { vi: 'Nhiều người thích viết vào đêm trăng non hoặc tối hôm trước một ngày quan trọng. Thật ra, bất cứ lúc nào bạn có được mười phút yên tĩnh đều là thời điểm tốt.', en: 'Many people like to write on a new-Moon night or the evening before an important day. In truth, any ten quiet minutes will do.' } },
    { h: { vi: 'Khi viết về người khác', en: 'When writing about other people' }, p: { vi: 'Hãy viết về cảm giác mà bạn muốn có trong tình yêu, thay vì viết rằng một người cụ thể phải yêu bạn. Mỗi người đều có ý chí riêng của họ. Một câu như "mình được yêu một cách nhẹ nhàng và rõ ràng" sẽ mở ra nhiều cánh cửa hơn là một cái tên.', en: 'Write about the feeling you want to have in love, rather than writing that a specific person must love you. Everyone has a will of their own. A line like "I am loved gently and clearly" opens more doors than a single name ever will.' } }
  ] },
{ id: 'mani-369', cat: 'manifest', badge: 'own', tags: ['manifest'],
  title: { vi: 'Phương pháp 369', en: 'The 369 method' },
  intro: { vi: 'Với phương pháp này, bạn viết câu khẳng định của mình ba lần vào buổi sáng, sáu lần vào buổi chiều và chín lần vào buổi tối. Nó lan truyền từ TikTok và thường được gắn với tên Tesla, dù ông chưa bao giờ dạy điều này.', en: 'With this method, you write your affirmation three times in the morning, six times in the afternoon and nine times at night. It spread from TikTok and is often linked to Tesla, although he never taught anything of the kind.' },
  sections: [
    { h: { vi: 'Vì sao nó có tác dụng với một số người', en: 'Why it works for some people' }, p: { vi: 'Tác dụng không đến từ con số, mà đến từ việc bạn nhắc mình về một mục tiêu đến mười tám lần mỗi ngày. Sự lặp lại đều đặn biến mục tiêu ấy thành ưu tiên thật sự trong đầu bạn.', en: 'The effect does not come from the numbers; it comes from reminding yourself of one goal eighteen times a day. That steady repetition turns the goal into a real priority in your mind.' } },
    { h: { vi: 'Cách làm gọn nhất', en: 'The leanest version' }, p: { vi: 'Bạn chọn một câu ngắn, dưới mười lăm chữ, và giữ nó trong hai mươi mốt ngày. Nếu lỡ quên một ngày, bạn cứ tiếp tục chứ đừng bắt đầu lại từ đầu. Ứng dụng có sẵn bảng đếm để bạn chạm mỗi lần viết xong.', en: 'Choose one short sentence, under fifteen words, and keep it for twenty-one days. If you miss a day, simply carry on rather than starting over. The app has a counter you can tap each time you finish a line.' } }
  ] },
{ id: 'mani-gratitude', cat: 'manifest', badge: 'conv', tags: ['manifest'],
  title: { vi: 'Biết ơn và câu khẳng định', en: 'Gratitude and affirmations' },
  intro: { vi: 'Đây là hai thói quen đơn giản nhất, và cũng là hai thói quen được tâm lý học ủng hộ nhiều nhất. Mỗi tối, bạn ghi ba điều mình biết ơn. Mỗi sáng, bạn nói một câu khẳng định.', en: 'These are the two simplest habits, and also the two with the strongest backing from psychology. Each night, you write down three things you are grateful for. Each morning, you say one affirmation.' },
  sections: [
    { h: { vi: 'Biết ơn cho cụ thể', en: 'Be specific about gratitude' }, p: { vi: 'Lòng biết ơn chỉ có tác dụng khi nó cụ thể. Thay vì viết "biết ơn gia đình", bạn hãy viết "biết ơn vì mẹ gọi hỏi mình ăn cơm chưa lúc bảy giờ tối". Ba điều như thế mỗi tối, ghi vào sổ, là đủ để thay đổi cách bạn nhìn một ngày.', en: 'Gratitude only works when it is specific. Instead of writing "grateful for my family", write "grateful that mum called at seven to ask if I had eaten". Three lines like that each night, in a notebook, are enough to change how you see a day.' } },
    { h: { vi: 'Câu khẳng định phải tin được', en: 'An affirmation you can believe' }, p: { vi: 'Câu khẳng định chỉ có ích khi bạn tin được nó. Nếu bạn nói "mình là triệu phú" trong lúc tài khoản trống, bạn sẽ chỉ thấy giả tạo. Nhưng câu "mình đang học cách quản lý tiền tốt hơn mỗi tuần" thì tin được, và chính niềm tin ấy sẽ kéo bạn đi.', en: 'An affirmation only helps when you can believe it. If you say "I am a millionaire" while your account is empty, it will only feel fake. But "I am learning to handle money better every week" is believable, and that belief is what moves you forward.' } }
  ] },
{ id: 'mani-limits', cat: 'manifest', badge: 'own', tags: ['manifest'],
  title: { vi: 'Giới hạn và sự thật thà', en: 'Limits and honesty' },
  intro: { vi: 'Nabu không hứa rằng manifestation làm được mọi thứ. Theo cách Nabu nhìn, đây là một công cụ giúp bạn biết rõ mình muốn gì và can đảm hơn để đi lấy nó. Bảng dưới đây giúp bạn tự kiểm tra xem mình đang dùng nó đúng hay sai.', en: 'Nabu does not promise that manifestation can do everything. The way Nabu sees it, it is a tool that helps you know what you want and be braver about going for it. The checklist below helps you see whether you are using it well or badly.' },
  sections: [
    { h: { vi: 'Dấu hiệu bạn đang dùng sai', en: 'Signs you are using it badly' }, p: { vi: 'Bạn chờ đợi thay vì hành động. Bạn tự trách mình mỗi khi chuyện xấu xảy ra. Bạn tiêu tiền vào những khóa học hứa hẹn một "bí mật". Bạn tránh đi bác sĩ hoặc tránh những cuộc nói chuyện thẳng thắn vì sợ "hút năng lượng xấu".', en: 'You wait instead of acting. You blame yourself whenever something bad happens. You spend money on courses that promise a "secret". You avoid the doctor, or avoid honest conversations, for fear of "attracting bad energy".' } },
    { h: { vi: 'Dấu hiệu bạn đang dùng đúng', en: 'Signs you are using it well' }, p: { vi: 'Bạn thấy rõ hơn mình muốn gì. Bạn dám mở lời hơn trước. Bạn bớt sợ hãi. Và bạn vẫn làm việc, vẫn đi khám, vẫn tiết kiệm như bình thường. Manifestation là thứ được thêm vào cuộc sống của bạn, chứ không thay thế nó.', en: 'You are clearer about what you want. You speak up more than before. You are less afraid. And you still work, still see the doctor, still save money as usual. Manifestation is something added to your life, not something that replaces it.' } }
  ] },

/* ---------------------------------------------------------- fortune ---- */
{ id: 'fort-numerology', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Thần số học: số đường đời', en: 'Numerology: your life path number' },
  intro: { vi: 'Số đường đời được tính từ ngày sinh của bạn. Bạn cộng các chữ số của ngày, tháng và năm cho đến khi còn một chữ số, nhưng giữ nguyên các số 11, 22 và 33. Ứng dụng sẽ tính sẵn cho bạn ở mục Tôi.', en: 'Your life path number comes from your date of birth. You add the digits of the day, the month and the year until a single digit remains, keeping 11, 22 and 33 as they are. The app works it out for you under Me.' },
  sections: [
    { h: { vi: 'Cách tính', en: 'How to count' }, p: { vi: 'Giả sử bạn sinh ngày 12 tháng 3 năm 1995. Ngày là 1 cộng 2 bằng 3. Tháng là 3. Năm là 1 cộng 9 cộng 9 cộng 5 bằng 24, rút gọn thành 2 cộng 4 bằng 6. Cộng ba kết quả lại, ta được 3 cộng 3 cộng 6 bằng 12, rút gọn thành 3. Vậy số đường đời của bạn là 3. Riêng tháng 11 và các ngày 11, 22 thì giữ nguyên, không rút gọn.', en: 'Suppose you were born on 12 March 1995. The day is 1 plus 2, which gives 3. The month is 3. The year is 1 plus 9 plus 9 plus 5, which gives 24, reduced to 2 plus 4, which gives 6. Add the three results and you get 3 plus 3 plus 6, which is 12, reduced to 3. So your life path is 3. Month 11 and days 11 and 22 stay as they are and are not reduced.' } },
    { h: { vi: 'Đọc con số thế nào', en: 'How to read the number' }, p: { vi: 'Hãy xem con số như một chủ đề xuyên suốt cuộc đời bạn, chứ không phải một bản án. Số 1 học cách tự lập, số 2 học cách hợp tác, số 7 học cách tin người. Các số bậc thầy 11, 22 và 33 mang bài học của số rút gọn tương ứng là 2, 4 và 6, nhưng với áp lực lớn hơn.', en: 'Treat the number as a theme running through your life, not as a verdict. A 1 learns independence, a 2 learns cooperation, a 7 learns to trust people. The master numbers 11, 22 and 33 carry the lessons of their reduced digits, 2, 4 and 6, but with greater pressure.' } },
    { h: { vi: 'Nên hiểu nó ra sao', en: 'How to hold it' }, p: { vi: 'Thần số học hiện đại ra đời vào đầu thế kỷ hai mươi, dựa trên ý tưởng gán số cho chữ cái có từ thời Pythagoras. Chưa có nghiên cứu nào chứng minh rằng nó dự đoán được đời người, nên bạn hãy dùng nó như một tấm gương để suy nghĩ về chính mình.', en: 'Modern numerology arose in the early twentieth century, built on the Pythagorean idea of giving numbers to letters. No study has shown that it predicts a life, so use it as a mirror for thinking about yourself.' } }
  ] },
{ id: 'fort-palm', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Xem chỉ tay cơ bản', en: 'Palm reading basics' },
  intro: { vi: 'Trên lòng bàn tay có ba đường chính: đường tim, đường trí và đường sinh mệnh. Theo cách xem phổ biến, tay thuận cho biết "hiện tại" của bạn, còn tay kia cho biết những gì bạn mang theo từ khi sinh ra.', en: 'The palm has three main lines: the heart line, the head line and the life line. In the common way of reading, your dominant hand shows your "present", while the other hand shows what you were born with.' },
  sections: [
    { h: { vi: 'Đường tim', en: 'The heart line' }, p: { vi: 'Đường tim nằm trên cùng và chạy ngang dưới các ngón tay. Nếu nó cong và dài, bạn là người cởi mở và dễ thể hiện cảm xúc. Nếu nó thẳng và ngắn, bạn kín đáo và thực tế hơn trong tình yêu. Đường tim kết thúc dưới ngón trỏ cho thấy một người yêu bằng lý tưởng và dễ hài lòng, còn kết thúc dưới ngón giữa thì cho thấy một người yêu bằng lý trí và hay đặt mình lên trước.', en: 'The heart line sits at the top and runs across under the fingers. If it is curved and long, you are open and show your feelings easily. If it is straight and short, you are more private and practical in love. A heart line that ends under the index finger points to someone idealistic and content in love, while one that ends under the middle finger points to someone who loves with the head and puts themselves first.' } },
    { h: { vi: 'Đường trí', en: 'The head line' }, p: { vi: 'Đường trí nằm ở giữa lòng bàn tay. Đường dài thuộc về người nghĩ nhiều và thích phân tích; đường ngắn thuộc về người quyết định nhanh và thực tế. Nếu đường cong xuống, bạn giàu trí tưởng tượng; nếu nó thẳng, bạn thiên về logic. Khi đường trí tách rời đường sinh mệnh ngay từ đầu, đó là dấu hiệu của một người độc lập từ sớm.', en: 'The head line runs through the middle of the palm. A long line belongs to someone who thinks a lot and likes to analyse; a short line belongs to someone who decides fast and stays practical. If the line curves downward, you are imaginative; if it runs straight, you lean toward logic. When the head line is separate from the life line right from the start, it points to someone who became independent early.' } },
    { h: { vi: 'Đường sinh mệnh', en: 'The life line' }, p: { vi: 'Đường sinh mệnh vòng quanh gốc ngón cái. Nó không nói bạn sống bao lâu, mà nói về sức sống và những thay đổi lớn. Một chỗ đứt đoạn hay rẽ nhánh thường đánh dấu một lần đổi đời.', en: 'The life line curves around the base of the thumb. It does not say how long you will live; it speaks of vitality and of big changes. A break or a fork usually marks a turning point in life.' } },
    { h: { vi: 'Nên hiểu nó ra sao', en: 'How to hold it' }, p: { vi: 'Xem chỉ tay đã có ở Ấn Độ, Trung Quốc và châu Âu từ hàng nghìn năm, và mỗi nơi có cách xem riêng. Cách được mô tả ở đây là cách phổ biến ở phương Tây. Chưa có bằng chứng khoa học cho nó, vì vậy bạn hãy xem đây như một cuộc trò chuyện thú vị về tính cách.', en: 'Palm reading has existed in India, China and Europe for thousands of years, and each place has its own rules. The version described here is the common Western one. There is no scientific evidence for it, so treat it as an enjoyable conversation about character.' } }
  ] },
{ id: 'fort-playing', cat: 'fortune', badge: 'conv', tags: ['fortune', 'tarot'],
  title: { vi: 'Bói bài Tây 52 lá', en: 'Reading with playing cards' },
  intro: { vi: 'Bộ bài Tây thực chất là một bộ tarot đã bỏ đi các lá Ẩn Chính và các lá Kỵ Sĩ. Vì vậy, nếu bạn đã biết tarot, bạn có thể đọc bài Tây gần như ngay lập tức.', en: 'A playing-card deck is really a tarot deck with the Majors and the Knights removed. So if you already know tarot, you can read playing cards almost right away.' },
  sections: [
    { h: { vi: 'Bốn chất', en: 'The four suits' }, p: { vi: 'Cơ tương ứng với Cốc và nói về tình cảm, gia đình. Rô tương ứng với Tiền và nói về tiền bạc, công việc. Chuồn tương ứng với Gậy và nói về hành động, kế hoạch, bạn bè. Bích tương ứng với Kiếm và nói về khó khăn, suy nghĩ và tin xấu.', en: 'Hearts match Cups and speak of love and family. Diamonds match Pentacles and speak of money and work. Clubs match Wands and speak of action, plans and friends. Spades match Swords and speak of trouble, thought and bad news.' } },
    { h: { vi: 'Số và hình', en: 'Numbers and faces' }, p: { vi: 'Át là khởi đầu của chất đó, còn Mười là kết thúc trọn vẹn. J là một người trẻ hoặc một tin tức, Q là một người phụ nữ hoặc người chăm sóc, và K là một người đàn ông hoặc người có quyền. Các lá số có nghĩa gần giống lá Ẩn Phụ cùng số trong tarot.', en: 'The Ace is the beginning of the suit, and the Ten is its full completion. The Jack is a young person or a piece of news, the Queen a woman or a carer, and the King a man or someone in authority. The number cards mean roughly what the same-numbered Minors mean in tarot.' } },
    { h: { vi: 'Lenormand dùng bài Tây ra sao', en: 'How Lenormand uses playing cards' }, p: { vi: 'Mỗi lá Lenormand đều in kèm một lá bài Tây từ bộ 36 lá, từ Sáu đến Át. Đó là tương ứng thật sự duy nhất của Lenormand, và nó đã có trên bài từ năm 1799.', en: 'Every Lenormand card carries a playing card from the 36-card pack, from Six to Ace. That is Lenormand\'s only real correspondence, and it has been printed on the cards since 1799.' } }
  ] },
{ id: 'fort-animals', cat: 'fortune', badge: 'doc', tags: ['fortune', 'astro'],
  title: { vi: '12 con giáp', en: 'The 12 zodiac animals' },
  intro: { vi: 'Mỗi năm âm lịch mang tên một con giáp, và vòng con giáp lặp lại sau mười hai năm. Ứng dụng tính con giáp của bạn theo năm sinh ở mục Tôi, còn vòng con giáp đầy đủ nằm trong phần Bói toán.', en: 'Each lunar year carries the name of an animal, and the cycle repeats every twelve years. The app works out your animal from your birth year under Me, and the full wheel lives in the Fortune telling section.' },
  sections: [
    { h: { vi: 'Lưu ý về Tết', en: 'A note about Tết' }, p: { vi: 'Năm con giáp bắt đầu từ Tết chứ không phải từ ngày 1 tháng 1. Vì vậy, nếu bạn sinh vào tháng 1 hoặc đầu tháng 2, bạn có thể thuộc con giáp của năm trước. Ứng dụng tính theo năm dương, nên bạn hãy kiểm tra lại nếu sinh trước Tết.', en: 'The animal year begins at Lunar New Year, not on 1 January. So if you were born in January or early February, you may belong to the previous year\'s animal. The app counts by the calendar year, so double-check if you were born before Tết.' } },
    { h: { vi: 'Tam hợp và tứ hành xung', en: 'Trios and clashes' }, p: { vi: 'Theo truyền thống, mười hai con giáp chia thành bốn nhóm tam hợp, là những bộ ba dễ hợp nhau, và ba nhóm tứ hành xung, là những bộ bốn dễ va chạm. Đây là chuyện tính cách chung và "hợp tuổi" trong văn hóa, chứ không phải khoa học. Bạn đừng để chuyện "khắc tuổi" quyết định hôn nhân thay cho hai người trong cuộc.', en: 'By tradition, the twelve animals form four trios that get on easily, and three groups of four that tend to clash. This is about general character and cultural "compatibility", not science. Do not let a "clashing year" decide a marriage instead of the two people involved.' } },
    { h: { vi: 'Tử vi thì khác', en: 'Tử vi is something else' }, p: { vi: 'Tử vi đẩu số cần giờ sinh và lập một lá số gồm mười hai cung với hơn một trăm sao. Đó là một hệ thống riêng và sâu hơn con giáp rất nhiều. Nabu xem tử vi trong buổi hẹn riêng, chứ không tính trong ứng dụng này.', en: 'Tử vi, Vietnamese astrology, needs the hour of birth and builds a chart of twelve palaces with more than a hundred stars. It is a separate and much deeper system than the animals. Nabu reads tử vi in a private session, not inside this app.' } }
  ] },
{ id: 'fort-tea', cat: 'fortune', badge: 'conv', tags: ['fortune'],
  title: { vi: 'Bài trà', en: 'Tealeaf fortune telling' },
  intro: { vi: 'Bạn uống một tách trà lá cho đến gần cạn, xoay tách ba vòng, úp lên đĩa, rồi nhìn những hình mà lá trà để lại trong lòng tách. Cách xem này đến từ châu Âu thế kỷ mười bảy, khi trà mới được đưa sang từ Trung Quốc.', en: 'You drink a cup of loose-leaf tea almost to the bottom, swirl it three times, turn it over onto the saucer, then look at the shapes the leaves have left inside. The practice comes from seventeenth-century Europe, when tea had just arrived from China.' },
  sections: [
    { h: { vi: 'Chuẩn bị', en: 'Getting ready' }, p: { vi: 'Bạn dùng trà lá rời, không dùng túi lọc, và chọn một chiếc tách sáng màu có lòng tròn. Trong lúc uống, bạn nghĩ về câu hỏi của mình. Khi còn một ngụm cuối, bạn xoay tách ba vòng bằng tay trái, úp nhanh lên đĩa, đợi vài giây rồi lật lại.', en: 'Use loose leaves rather than a tea bag, and pick a light-coloured cup with a round bowl. While you drink, think about your question. When one sip remains, swirl the cup three times with your left hand, turn it quickly onto the saucer, wait a few seconds, then turn it back.' } },
    { h: { vi: 'Đọc theo vị trí', en: 'Reading by position' }, p: { vi: 'Hình nằm gần miệng tách nói về chuyện sắp tới. Hình ở giữa tách nói về vài tuần sau. Hình dưới đáy nói về chuyện xa hơn, hoặc về gốc rễ của vấn đề. Hình gần quai liên quan trực tiếp đến bạn, còn hình đối diện quai nói về người khác và những chuyện bên ngoài.', en: 'Shapes near the rim speak of what is coming soon. Shapes in the middle speak of a few weeks ahead. Shapes at the bottom speak of things further away, or of the root of the matter. Shapes near the handle concern you directly, while shapes opposite the handle speak of other people and outside events.' } },
    { h: { vi: 'Vài hình thường gặp', en: 'Some common shapes' }, p: { vi: 'Con chim là tin tức. Trái tim là tình cảm. Chiếc nhẫn là cam kết hay hôn nhân. Chìa khóa là một cánh cửa đang mở. Đường thẳng là một chuyến đi. Cái cây là thành công đến dần. Đám mây là sự rối rắm, chưa rõ ràng. Một chữ cái là tên của ai đó, và một con số là số ngày hoặc số tháng.', en: 'A bird is news. A heart is love. A ring is commitment or marriage. A key is a door opening. A straight line is a journey. A tree is success arriving gradually. A cloud is confusion, something not yet clear. A letter is someone\'s name, and a number is a count of days or months.' } },
    { h: { vi: 'Đọc với tinh thần nào', en: 'The right spirit' }, p: { vi: 'Bài trà là một cách kể chuyện qua hình ảnh, giống như nhìn mây trên trời. Nó gợi ý chứ không phán xét. Hình mà bạn nhìn thấy đầu tiên thường là hình quan trọng nhất.', en: 'Tealeaf fortune telling is a way of telling a story through pictures, much like watching clouds. It suggests; it does not judge. The shape you notice first is usually the one that matters most.' } }
  ] },
{ id: 'fort-oracle', cat: 'fortune', badge: 'conv', tags: ['fortune', 'tarot'],
  title: { vi: 'Bài oracle và bài "Pick a Card"', en: 'Oracle decks and "Pick a Card"' },
  intro: { vi: 'Oracle là loại bài tự do: số lá, hình vẽ và ý nghĩa đều do tác giả đặt ra, không có cấu trúc chung như tarot. Nabu dùng oracle như một lời nhắn thêm, luôn chỉ rút một lá và xào riêng.', en: 'An oracle deck is a free-form deck: the number of cards, the pictures and the meanings are all the author\'s own, with no shared structure like tarot. Nabu uses oracle as an extra message, always drawing one card from a separate shuffle.' },
  sections: [
    { h: { vi: 'Pick a Card là gì', en: 'What a Pick a Card post is' }, p: { vi: 'Pick a Card là một thông điệp dành cho nhiều người cùng lúc. Người xem chọn một trong vài nhóm, thường được đánh dấu bằng số, hình hoặc chữ cái, rồi Nabu rút bài cho từng nhóm. Vì đây là bài chung chứ không phải bài riêng cho bạn, phần nào không khớp thì bạn cứ bỏ qua.', en: 'A Pick a Card post is one message for many people at once. Viewers choose one of a few piles, usually marked with numbers, pictures or letters, and Nabu draws for each pile. Because it is a collective reading rather than your personal one, feel free to skip whatever does not fit.' } },
    { h: { vi: 'Dấu hiệu tên và cung', en: 'Initials and signs' }, p: { vi: 'Việc đọc chữ cái đầu của tên từ lá bài không có nguồn gốc lịch sử; đó là hệ thống riêng của mỗi người đọc bài. Trong ứng dụng này, những bài có ghi "dành cho bạn nếu…" chỉ là gợi ý để bạn dễ nhận ra mình, chứ không phải một lời tiên đoán chắc chắn.', en: 'Reading the initials of a name from the cards has no historical basis; it is each reader\'s own system. In this app, posts marked "for you if…" are only hints to help you recognise yourself, not a firm prediction.' } }
  ] }
];
