/* Lenormand card text — German.

   Stage 2 of the German translation. Lenormand is a German deck to begin with,
   so the names here are the originals rather than anything translated back out
   of English: Der Reiter, Der Klee, Das Schiff. Playing-card equivalents use
   the German suits — Herz, Karo, Pik, Kreuz.

   Meanings follow the mainstream Petit Lenormand tradition, as the English and
   Vietnamese halves do. This is a different system from tarot with a different
   grammar, and the two are deliberately kept apart. */

LEN.de = {};

Object.assign(LEN.de, {

1: { name: 'Der Reiter', card: 'Herz 9', tone: 'pos', person: true,
  kw: { pos: ['Nachricht', 'Ankunft', 'Bewegung', 'Besuch', 'eine Annäherung', 'Sport'],
        neg: ['Ruhelosigkeit', 'eine Nachricht, die beunruhigt', 'jemand, der nicht bleibt'] },
  scene: 'Ein Reiter zu Pferd, quer über die Karte in Bewegung. Er kommt auf etwas zu, und er bringt etwas mit — die Botschaft ist nicht seine eigene.',
  core: 'Der Reiter ist die Karte der eintreffenden Nachricht und der Dinge, die von außen kommen. Etwas ist zu dir unterwegs: eine Nachricht, ein Mensch, eine Gelegenheit, eine Information. Es geht schnell — der Reiter ist eine der flinksten Karten im Deck. Für sich allein ist er schlicht eine gute Nachricht; die Karte daneben sagt dir, worum es dabei geht.',
  love: 'Eine Nachricht von jemandem, eine erste Annäherung, oder ein junger Mann, der ins Bild kommt. Kontakt kommt — aber der Reiter bringt Nachricht, keine Bindung.',
  work: 'Ein Angebot, eine Einladung zum Gespräch, eine Lieferung, ein Kurier, alles rund um Verkauf oder Sport. Bewegung in einer Lage, die stillstand.',
  who: 'Ein junger Mann, ein Sportler, ein Bote, ein Fahrer — jemand Aktives, Schnelles, der durchzieht statt zu bleiben.',
  time: 'Sehr schnell. Ein bis drei Tage, manchmal noch am selben Tag.',
  combo: [['+ Herz', 'Eine Liebesnachricht, ein Geständnis, eine Erklärung, die ankommt.'],
          ['+ Brief', 'Ausdrücklich Schriftliches — eine E-Mail, eine Nachricht, ein förmliches Schreiben.'],
          ['+ Sarg', 'Eine schlechte Nachricht, oder eine Nachricht, die etwas beendet.']] },

2: { name: 'Der Klee', card: 'Karo 6', tone: 'pos',
  kw: { pos: ['kleines Glück', 'ein Glücksfall', 'eine kurze Chance', 'Erleichterung', 'Leichtigkeit'],
        neg: ['es hält nicht', 'Glücksspiel', 'ein Zufall, den du nicht wiederholen kannst'] },
  scene: 'Ein Klee, dicht über dem Boden gewachsen. Er ist klein, und man übersieht ihn leicht, wenn man nicht nach unten schaut.',
  core: 'Der Klee ist Glück — aber kleines, schnelles Glück. Ein Fenster geht auf und bleibt nicht lange offen. Diese Karte sagt Ja, aber Ja zu etwas Bescheidenem und Vorübergehendem, nicht zu etwas, das dein Leben ändert. Ihr großer Wert in einer Legung ist, dass sie alles neben sich leichter macht: Selbst eine schwere Karte wird neben dem Klee erträglicher.',
  love: 'Ein schöner Moment, ein Flirt, ein bisschen Glück in einer Beziehung. Nicht die Karte einer dauerhaften Bindung — nimm sie so, wie sie ist.',
  work: 'Eine kleine Gelegenheit, ein bescheidener Gewinn, ein Problem, das sich unerwartet von selbst löst. Nimm es jetzt; es wartet nicht.',
  who: 'Jemand Unbeschwertes, Glückliches, nicht Ernsthaftes. Angenehm dabeizuhaben, aber niemand, auf dem man baut.',
  time: 'Sehr kurz. Stunden bis wenige Tage. Wenn du auf den Moment wartest: Der Moment ist jetzt.',
  combo: [['+ Fische', 'Ein kleiner Geldsegen — Geld, das unerwartet ankommt.'],
          ['+ Wolken', 'Glück, das durcheinandergerät oder verpasst wird. Die Chance war da, und du hast sie nicht gesehen.'],
          ['+ Ring', 'Eine glückliche Zusage, oder eine Abmachung, die nicht lange hält.']] },

3: { name: 'Das Schiff', card: 'Pik 10', tone: 'neu',
  kw: { pos: ['Reise', 'Ferne', 'Handel', 'eine Fahrt', 'Auslandsangelegenheiten', 'Fortschritt'],
        neg: ['Sehnsucht', 'jemand weit weg', 'Weggehen', 'innere Distanz'] },
  scene: 'Ein Schiff unter vollen Segeln auf offenem Wasser, fort von dort, wo es losfuhr.',
  core: 'Das Schiff ist Ferne und Aufbruch. Es steht für wirkliche Reisen, für das Ausland, für Einfuhr und Handel, und ebenso für die gefühlte Fassung davon: dass jemand oder etwas weit weg ist, und für die Sehnsucht, die dazugehört. Das Schiff ist immer in Bewegung, es sagt also, dass die Lage sich bewegt — aber langsam, und fort von dort, wo sie jetzt ist.',
  love: 'Eine Fernbeziehung, jemand, der weit weg wohnt, oder ein Mensch, der innerlich woanders ist. Es kann auch heißen, dass eine Beziehung auf einer Reise beginnt.',
  work: 'Import und Export, internationale Arbeit, Reisen für den Beruf, oder eine Laufbahn, die dich woandershin bringt. Fortschritt, der Zeit braucht.',
  who: 'Jemand aus dem Ausland, ein Reisender, jemand, der im Ausland lebt, ein Händler. Oder der Mensch in deinem Leben, der ständig fortgeht.',
  time: 'Langsam. Wochen bis Monate — oder "wenn die Reise stattfindet".',
  combo: [['+ Herz', 'Liebe über die Ferne, oder eine Romanze, die auf einer Reise beginnt.'],
          ['+ Haus', 'Umzug, Ortswechsel, oder ein Zuhause im Ausland.'],
          ['+ Sarg', 'Eine Reise, die endet, oder ein Aufbruch, der etwas endgültig abschließt.']] },

4: { name: 'Das Haus', card: 'Herz König', tone: 'neu',
  kw: { pos: ['Zuhause', 'Familie', 'Sicherheit', 'Halt', 'Eigentum', 'Tradition'],
        neg: ['im Vertrauten feststecken', 'Druck aus der Familie', 'zu konservativ'] },
  scene: 'Ein festes Haus mit geschlossener Tür und erleuchteten Fenstern. Es geht nirgendwohin.',
  core: 'Das Haus ist deine Basis — die Wohnung, die Familie, und das Gefühl von Sicherheit, das aus beidem kommt. Es ist eine der stabilsten Karten im Deck, und es erdet alles, was daneben liegt. Wo das Schiff hinausfährt, bleibt das Haus. Es deutet oft darauf hin, dass eine Sache häuslich und privat ist statt öffentlich.',
  love: 'Eine Beziehung mit häuslichem, gesetztem Zug — zusammenziehen, die Familie kennenlernen, etwas bauen, in dem man wohnen kann. Eher sicher als aufregend.',
  work: 'Arbeit von zu Hause, ein Familienbetrieb, Immobilien und Eigentum, oder eine Stelle, die Sicherheit bietet statt Aufstieg.',
  who: 'Ein Familienmitglied, eine Vaterfigur, ein Vermieter, jemand Traditionelles und Verlässliches.',
  time: 'Beständig und ohne Eile. Etwa vier Wochen, oder "wenn du zu Hause bist".',
  combo: [['+ Ring', 'Heirat, Zusammenziehen, ein Vertrag über eine Wohnung.'],
          ['+ Mäuse', 'Das Zuhause wird untergraben — Verlust von Eigentum, Stress daheim, oder eine Familie, die dich auslaugt.'],
          ['+ Fische', 'Familiengeld, Einkünfte aus Eigentum, finanzielle Sicherheit.']] },

5: { name: 'Der Baum', card: 'Herz 7', tone: 'neu',
  kw: { pos: ['Gesundheit', 'Wachstum', 'Wurzeln', 'Tiefe', 'Lebenskraft', 'Verbundenheit'],
        neg: ['Langsamkeit', 'Krankheit', 'Stillstand', 'etwas Langjähriges'] },
  scene: 'Ein einzelner Baum mit schwerer Krone und dickem Stamm. Seine Wurzeln sind der Teil, den du nicht siehst.',
  core: 'Der Baum steht für Gesundheit, Wurzeln und langsames, beständiges Wachstum. Seine Themen brauchen Zeit: der Körper, familiäre Linien, eine tiefe Bindung oder ein länger bestehendes Thema. In einer Legung weist er auf etwas tief Verwurzeltes hin, das sich nicht über Nacht löst.',
  love: 'Eine tiefe, langsam wachsende Bindung, manchmal eine karmische oder familienähnliche Verbindung. Kein Feuerwerk — Wurzeln.',
  work: 'Eine Laufbahn, die langsam und stetig wächst, Arbeit im Gesundheitswesen, oder etwas, das du in zehn Jahren noch tust.',
  who: 'Ein Arzt oder Heiler, ein Verwandter, jemand Geduldiges und tief Verwurzeltes.',
  time: 'Sehr langsam. Monate bis Jahre. Der Baum ist die Karte, die "noch nicht" sagt.',
  combo: [['+ Sarg', 'Dieses Paar wird traditionell mit einer gesundheitlich schwächeren Phase oder deren Ende verbunden; es ersetzt keine medizinische Beratung.'],
          ['+ Sonne', 'Ein Symbol für gute Vitalität und einen günstigen Erholungsverlauf.'],
          ['+ Berg', 'Eine Blockade, die schon lange da ist; langsame Heilung, chronische Verzögerung.']] },

6: { name: 'Die Wolken', card: 'Kreuz König', tone: 'neg',
  kw: { pos: ['es geht vorbei', 'Aufklaren', 'ein vorübergehender Nebel'],
        neg: ['Verwirrung', 'Zweifel', 'fehlende Klarheit', 'Ärger', 'etwas Verdecktes'] },
  scene: 'Zwei Wolkenbänke — eine dunkel, eine hell. Überliefert zeigt die dunkle Seite, wo der Ärger sitzt.',
  core: 'Die Wolken sind Verwirrung, Zweifel und Dinge, die du nicht klar siehst. Das ist keine Katastrophe — es ist Nebel. Etwas an der Lage ist unklar, entweder weil Informationen fehlen oder weil jemand durcheinander ist. Klassisch hat die Karte eine Richtung: Wohin die dunkle Seite zeigt, dort sitzt der Ärger, und wohin die helle zeigt, dort klart es auf.',
  love: 'Widersprüchliche Signale, eine unklare Beziehung, jemand, der selbst nicht weiß, was er will. Das ist die Karte für alles, was keinen Namen hat.',
  work: 'Eine verwirrende Lage bei der Arbeit, unklare Anweisungen, eine Entscheidung ohne genug Informationen.',
  who: 'Jemand Unklares, Launisches oder Ausweichendes — nicht unbedingt unehrlich, nur unmöglich zu lesen.',
  time: 'Ungewiss, und genau das ist der Punkt. Ein bis drei Tage, bis der Nebel sich hebt.',
  combo: [['+ Herz', 'Verwirrte Gefühle, eine unklare Romanze, gemischte Signale in der Liebe.'],
          ['+ Schlüssel', 'Die Verwirrung löst sich — Klarheit kommt, der Nebel hebt sich.'],
          ['+ Fuchs', 'Die Verwirrung ist Absicht. Jemand trübt das Wasser mit Vorsatz.']] },

7: { name: 'Die Schlange', card: 'Kreuz Dame', tone: 'neg', person: true,
  kw: { pos: ['Weisheit', 'Sinnlichkeit', 'ein nötiger Umweg', 'Wandlung'],
        neg: ['Verrat', 'eine Rivalin', 'Verwicklung', 'eine Lüge', 'ein gewundener Weg'] },
  scene: 'Eine Schlange, in einem langen S gewunden. Sie geht nie geradeaus, und sie ist schön.',
  core: 'Die Schlange ist Verwicklung — und zwar Verwicklung mit einem Menschen dahinter. Überliefert ist es eine andere Frau, eine Rivalin, oder jemand, der gegen deine Interessen handelt. Weiter gefasst ist es alles, was nicht geradeaus geht: ein Umweg, eine Verstrickung, eine Lüge, ein komplizierter Weg zu dem, was du willst. Die Schlange ist nicht dumm; sie ist die Karte der Klugheit im eigenen Interesse.',
  love: 'Eine dritte Person, eine Rivalin, eine Affäre, oder eine Beziehung mit einer ernsten Verwicklung darin. Verlangen, das echt ist, aber nicht einfach.',
  work: 'Machtspiele im Büro, jemand, der gegen dich arbeitet, ein Geschäft mit einer versteckten Bedingung, ein umständliches Verfahren.',
  who: 'Eine Frau, die Dinge verkompliziert — eine Rivalin, eine Ex, jemand, der manipuliert. Oder schlicht ein kluger, sinnlicher, schwieriger Mensch.',
  time: 'Verzögert und gewunden. Es geht nicht geradeaus, rechne also mit mehr Zeit, als du denkst.',
  combo: [['+ Herz', 'Eine Rivalin in der Liebe, oder eine Verführung. Jemand anderes ist im Bild.'],
          ['+ Ring', 'Eine komplizierte Bindung, eine Affäre in einer Ehe, ein Vertrag mit einer Falle darin.'],
          ['+ Dame', 'Ganz wörtlich: Eine andere Frau ist beteiligt.']] },

8: { name: 'Der Sarg', card: 'Karo 9', tone: 'neg',
  kw: { pos: ['ein sauberes Ende', 'Wandlung', 'Abschluss', 'Loslassen'],
        neg: ['Verlust', 'Krankheit', 'Trauer', 'das Ende von etwas', 'Stillstand'] },
  scene: 'Ein geschlossener Sarg. Was darin liegt, ist zu Ende, und der Deckel ist zu.',
  core: 'Der Sarg ist ein Ende. Er ist die Karte für Dinge, die vorbei sind: eine Beziehung, eine Stelle, ein Lebensabschnitt, manchmal eine Zeit der Krankheit. In einer heutigen Legung ist er selten wörtlich der Tod — aber er ist wirklich endgültig. Lies ihn ehrlich statt beschönigend, und lies, was daneben liegt: Der Sarg beschreibt, was endet, und die Nachbarkarte, wofür er Platz macht.',
  love: 'Eine Beziehung endet, Gefühle sind gestorben, oder eine Zeit der Trauer. Wenn du gefragt hast, ob es vorbei ist, sagt diese Karte: ja.',
  work: 'Eine Stelle endet, ein Vorhaben wird gestrichen, ein Betrieb schließt. Auch Ausbrennen — Kraft, die aufgebraucht ist.',
  who: 'Jemand in Trauer, jemand Zurückgezogenes, oder ein Mensch, der innerlich zugemacht hat.',
  time: 'Ein abschließender Zeitraum, etwa acht Wochen — oder "wenn es endet", was schon geschehen sein kann.',
  combo: [['+ Herz', 'Das Ende einer Beziehung, oder Liebeskummer.'],
          ['+ Storch', 'Ein Ende, das zur Wende zum Besseren wird — das klassische Wandlungspaar.'],
          ['+ Baum', 'Eine Gesundheitssache, oder ein langjähriger Zustand, der zu Ende geht.']] },

9: { name: 'Der Blumenstrauß', card: 'Pik Dame', tone: 'pos',
  kw: { pos: ['ein Geschenk', 'eine Einladung', 'Charme', 'Schönheit', 'Wertschätzung', 'ein schönes Angebot'],
        neg: ['Schmeichelei', 'Charme an der Oberfläche', 'eine Geste ohne etwas dahinter'] },
  scene: 'Ein Strauß, gebunden und bereit, jemandem gereicht zu werden. Sein ganzer Zweck ist, verschenkt zu werden.',
  core: 'Der Blumenstrauß ist ein freundliches Angebot — ein Geschenk, eine Einladung, ein Kompliment, eine Freundlichkeit, die ankommt. Er ist eine der liebenswürdigsten Karten im Deck und macht alles, was er berührt, angenehmer. Seine einzige Mahnung: Ein Strauß ist eine Oberfläche. Er ist schön, er ist wirklich nett, und er beweist von sich aus keine Tiefe. Jemand ist reizend zu dir. Ob er es ernst meint, sagt die nächste Karte.',
  love: 'Umworben werden. Komplimente, Geschenke, eine Einladung, jemand, der sich Mühe gibt, dich zu bezaubern. Ein sehr gutes Zeichen, wenn du nach jemandem fragst, den du magst.',
  work: 'Anerkennung, eine Prämie, eine gut aufgenommene Präsentation, eine Einladung. Kreative und gestalterische Arbeit.',
  who: 'Ein charmanter, höflicher, anziehender Mensch. Jemand, der es angenehm macht.',
  time: 'Bald und auf angenehme Weise — etwa neun Tage.',
  combo: [['+ Herz', 'Eine romantische Geste — Blumen, ein Geschenk, ein Bekenntnis von Zuneigung.'],
          ['+ Fuchs', 'Schmeichelei mit Absicht. Der Charme ist Taktik.'],
          ['+ Ring', 'Ein Antrag, ein Verlobungsgeschenk, ein schönes Angebot mit Verbindlichkeit dahinter.']] },

10: { name: 'Die Sense', card: 'Karo Bube', tone: 'neg',
  kw: { pos: ['ein entschiedener Schnitt', 'Ernte', 'sauberes Entfernen', 'Operation'],
        neg: ['plötzlicher Verlust', 'Gefahr', 'ein abruptes Ende', 'etwas bricht ab'] },
  scene: 'Eine Sense mit erhobenem Blatt. Sie arbeitet nur auf eine Art: schnell, und alles auf einmal.',
  core: 'Die Sense ist der plötzliche Schnitt. Wo der Sarg ein Ende ist, das sich setzt, ist die Sense ein Ende, das in einem Augenblick geschieht, ohne Vorwarnung und meist ohne Aussprache. Sie ist auch Entscheidung — die Karte des endgültigen Abschneidens. Ihr bestimmender Zug ist Tempo: Was sie berührt, geschieht abrupt. Überliefert zeigt die Richtung des Blattes, was geschnitten wird.',
  love: 'Eine plötzliche Trennung, abgeschnitten werden, oder eine Entscheidung ohne Vorwarnung. Auch die Karte dafür, selbst endlich Schluss zu machen.',
  work: 'Kündigung, ein gekündigter Vertrag, ein gestopptes Vorhaben. Auch Operationen und jede Arbeit mit Klingen oder Genauigkeit.',
  who: 'Jemand Entschiedenes und Schroffes. Ein Chirurg, ein Zahnarzt, oder ein Mensch, der Dinge ohne Gespräch beendet.',
  time: 'Sofort. Jetzt, oder ganz ohne Vorwarnung.',
  combo: [['+ Herz', 'Eine plötzliche Trennung, oder der Entschluss, eine Beziehung zu beenden.'],
          ['+ Baum', 'Eine Operation, oder ein plötzliches gesundheitliches Ereignis.'],
          ['+ Ring', 'Ein gekündigter Vertrag, eine beendete Ehe, eine gebrochene Abmachung.']] },

11: { name: 'Die Rute', card: 'Kreuz Bube', tone: 'neg',
  kw: { pos: ['Disziplin', 'körperliche Kraft', 'Wiederholung, die aufbaut', 'Sexualität'],
        neg: ['Streit', 'Konflikt', 'Wiederholung', 'derselbe Streit wieder', 'Übergriffe'] },
  scene: 'Zwei gekreuzte Ruten. Hier geschieht nichts ein einziges Mal — die Rute ist immer eine wiederholte Bewegung.',
  core: 'Die Rute ist Konflikt und Wiederholung. Das Schlüsselwort ist *wieder*: derselbe Streit, dasselbe Muster, derselbe Kreis. Sie umfasst Auseinandersetzungen, Kritik und das Zermürbende an einem Streit, der immer wieder von vorn beginnt. Ihre andere Seite ist körperlich: Sport, Bewegung, hartes Training, und Sexualität. Beide Lesarten haben denselben Motor — etwas, das immer und immer wieder getan wird.',
  love: 'Wiederkehrende Auseinandersetzungen, eine Beziehung, die immer denselben Streit führt. In anderer Tonart: starke körperliche Anziehung.',
  work: 'Konflikt mit einem Kollegen, Kritik, eintönige Arbeit, körperliche Arbeit. Ein Streit, der immer wieder aufbricht.',
  who: 'Jemand Streitlustiges, Körperliches oder Hitziges. Ein Sportler, ein Trainer, oder ein Mensch, mit dem du immer wieder aneinandergerätst.',
  time: 'In die Länge gezogen und wiederkehrend. Es passiert mehr als einmal, bevor es vorbei ist.',
  combo: [['+ Herz', 'Eine stürmische Beziehung — Leidenschaft und Streit am selben Ort.'],
          ['+ Wolken', 'Ein Streit, der zu nichts führt, weil niemand klar ist.'],
          ['+ Sarg', 'Der Streit endet — oder die Beziehung endet wegen des Streits.']] },

12: { name: 'Die Vögel', card: 'Karo 7', tone: 'neu',
  kw: { pos: ['Gespräch', 'ein Paar', 'ein Anruf', 'Verhandlung', 'Lebhaftigkeit'],
        neg: ['Gerede', 'Unruhe', 'Geschnatter', 'Nervosität', 'reden statt tun'] },
  scene: 'Zwei kleine Vögel, die beide gleichzeitig reden. Es sind immer zwei, und sie sind immer laut.',
  core: 'Die Vögel sind das Reden. Anrufe, Gespräche, Verhandlungen, Klatsch, und das nervöse Geplapper im eigenen Kopf. Weil es zwei Vögel sind, bedeutet die Karte auch ein Paar — zwei Menschen, ein Duo, oder zwei von irgendetwas. Sie ist kurz und geschäftig statt tief, und sie trägt ein Grundrauschen von Unruhe.',
  love: 'Ein Gespräch mit jemandem, ein Anruf, oder ein Paar. Auch Nervosität wegen einer Beziehung, und andere Leute, die darüber reden.',
  work: 'Besprechungen, Anrufe, Verhandlungen, Arbeit mit Medien und Kommunikation. Oder Büroklatsch.',
  who: 'Ein gesprächiger, geselliger, nervöser Mensch. Zwei Personen. Geschwister. Jemand aus Vertrieb oder Medien.',
  time: 'Schnell, aber aufgeregt. Zwölf Stunden bis zwölf Tage.',
  combo: [['+ Herz', 'Ein Gespräch über Gefühle, oder ein Paar.'],
          ['+ Wolken', 'Gerede und Verwirrung — Leute reden, ohne es zu wissen.'],
          ['+ Ring', 'Über eine Bindung verhandeln, oder zwei Menschen einigen sich.']] },

13: { name: 'Das Kind', card: 'Pik Bube', tone: 'pos', person: true,
  kw: { pos: ['ein Neuanfang', 'Unschuld', 'ein Kind', 'etwas Kleines', 'frische Kraft'],
        neg: ['Unreife', 'Naivität', 'Unerfahrenheit', 'zu neu, um darauf zu bauen'] },
  scene: 'Ein kleines Kind, das für sich allein steht. Alles an ihm ist früh.',
  core: 'Das Kind ist Anfang und Kleinheit. Es meint ein wirkliches Kind, und es meint alles, was ganz am Anfang steht: eine neue Beziehung, eine neue Stelle, ein neuer Einfall. Was es berührt, wird jünger und kleiner — ein kleiner Betrag, ein kleines Problem, ein frühes Stadium. Seine ehrliche Kante ist die Unerfahrenheit: Das Kind ist aufrichtig, aber es weiß noch nicht, was es tut.',
  love: 'Eine neue Beziehung kann beginnen, oder eine bestehende befindet sich noch am Anfang. Die Gefühle sind ehrlich, aber noch nicht ausgereift. Traditionell kann diese Karte auch mit Kindern, Schwangerschaft oder einem Neubeginn verbunden werden.',
  work: 'Eine neue Stelle, ein Auszubildender, ein kleines Vorhaben, ein frischer Start. Arbeit mit Kindern oder in der Bildung.',
  who: 'Ein Kind, ein junger Mensch, jemand Naives oder Neues. Jemand Kindliches im guten Sinn, und im schwierigen.',
  time: 'Der allererste Anfang von etwas. Kurz und früh.',
  combo: [['+ Herz', 'Neue Liebe, eine junge Romanze, unschuldige Gefühle.'],
          ['+ Storch', 'Dieses Paar wird häufig mit Schwangerschaft, Geburt oder einem neuen Anfang in der Familie verbunden.'],
          ['+ Schlange', 'Naivität, die ausgenutzt wird.']] },

14: { name: 'Der Fuchs', card: 'Kreuz 9', tone: 'neg', person: true,
  kw: { pos: ['Klugheit', 'Strategie', 'Selbstschutz', 'der Brotberuf'],
        neg: ['Täuschung', 'ein Trick', 'Eigennutz', 'ein falscher Freund', 'ein Fehler'] },
  scene: 'Ein Fuchs, der beobachtet. Er jagt noch nicht — er rechnet.',
  core: 'Der Fuchs ist List und Eigennutz. Jemand handelt zum eigenen Vorteil, und er stellt sich klug dabei an. Das reicht von harmloser Strategie bis zu offener Täuschung, und die Nachbarkarte sagt dir, was davon. In den meisten Überlieferungen ist der Fuchs auch die Karte *der Arbeit* — dessen, was du für Geld tust, des Alltagstrotts. Und er warnt vor einem Irrtum: Etwas an der Lage ist nicht das, als was es dargestellt wird.',
  love: 'Jemand mit einer Absicht, ein Mensch, der nicht offen mit dir ist, oder eine Beziehung, in der eine Seite ein Spiel spielt.',
  work: 'Deine Arbeit selbst, ein schwieriger Kollege, Machtspiele, oder ein Fehler in der Arbeit. Lies genau, bevor du unterschreibst.',
  who: 'Ein kluger, auf sich bedachter Mensch. Ein Kollege, ein Rivale, ein Betrüger — oder schlicht ein Stratege.',
  time: 'Trau dem Zeitplan nicht. Später als versprochen, oder nicht dann, wenn es hieß.',
  combo: [['+ Herz', 'Unaufrichtige Zuneigung, oder Liebe mit einem Hintergedanken.'],
          ['+ Blumenstrauß', 'Schmeichelei als Werkzeug.'],
          ['+ Schlüssel', 'Der Trick fliegt auf — die Wahrheit darüber kommt heraus.']] },

15: { name: 'Der Bär', card: 'Kreuz 10', tone: 'neu', person: true,
  kw: { pos: ['Stärke', 'Macht', 'Schutz', 'Autorität', 'Geld', 'ein Versorger'],
        neg: ['Beherrschung', 'Eifersucht', 'jemand, der kontrolliert', 'Gewicht', 'Übermaß'] },
  scene: 'Ein großer Bär. Allein seine Anwesenheit verändert den Raum — nichts an ihm ist zurückhaltend.',
  core: 'Der Bär ist Macht. Er umfasst Stärke, Schutz, und die Person in der Lage, die das Sagen hat: ein Chef, eine Mutterfigur, jemand, der über die Mittel verfügt. Er ist auch die Karte für größere Geldbeträge und für körperliche Wucht. Der Bär beschützt, was seins ist, und das ist seine Tugend und sein Problem — der Schatten des Bären ist Besitzanspruch und Kontrolle.',
  love: 'Ein beschützender, starker Mensch an deiner Seite — oder ein besitzergreifender, eifersüchtiger. Jemand Älteres oder Mächtigeres in der Beziehung.',
  work: 'Dein Chef, eine Person mit Autorität, eine große Summe, Finanzen und Führung. Stärke, auf die du dich verlassen kannst.',
  who: 'Ein Chef, eine Mutter, ein älterer oder größerer Mensch, jemand in einer Machtstellung. Mächtig, beschützend, schwer zu widersprechen.',
  time: 'Lang und schwer. Eher Monate als Wochen.',
  combo: [['+ Fische', 'Erhebliches Geld — eine große Summe, Vermögen, eine Anlage.'],
          ['+ Herz', 'Beschützende Liebe, oder eine eifersüchtige und kontrollierende.'],
          ['+ Schlange', 'Ein Machtkampf, oder eine eifersüchtige Rivalin.']] },

16: { name: 'Die Sterne', card: 'Herz 6', tone: 'pos',
  kw: { pos: ['Hoffnung', 'Klarheit', 'Führung', 'ein klarer Weg', 'Eingebung', 'viele'],
        neg: ['zerstreut', 'ein Traum ohne Plan', 'zu weit verteilt', 'Nacht'] },
  scene: 'Ein Nachthimmel voller Sterne, einer heller als die anderen. Man kann sich nach ihnen richten.',
  core: 'Die Sterne sind Klarheit, Hoffnung und Richtung. Das ist die Karte, die sagt: Der Weg ist sichtbar. Du siehst, wohin du gehst, und die Lage steht unter guten Sternen. Sie trägt einen geistigen, ahnenden Zug und sie vervielfacht — viele Sterne heißen viele von dem, was daneben liegt. Ihre Schwäche ist, dass Sterne weit weg sind: Die Sterne zeigen die Richtung wunderbar und gehen den Weg nicht.',
  love: 'Eine hoffnungsvolle Beziehung unter guten Zeichen. Jemand, den du idealisierst. Klarheit darüber, was du wirklich willst.',
  work: 'Ein klarer Plan, eine gute Richtung, kreative und technische Arbeit, alles Digitale. Viele kleine Gelegenheiten.',
  who: 'Ein inspirierender, geistig geprägter oder visionärer Mensch. Jemand, zu dem du aufschaust.',
  time: 'Nachts, oder deutlich ausgeschildert. Etwa sechzehn Tage.',
  combo: [['+ Herz', 'Eine hoffnungsvolle, schöne Liebe. Klarheit über deine Gefühle.'],
          ['+ Wolken', 'Die Richtung ist verloren — Hoffnung verdeckt, ein Plan im Nebel.'],
          ['+ Schlüssel', 'Gewissheit und Klarheit zusammen: Die Antwort ist ja, und sie ist klar.']] },

17: { name: 'Der Storch', card: 'Herz Dame', tone: 'pos',
  kw: { pos: ['Veränderung', 'Verbesserung', 'Umzug', 'ein neuer Abschnitt', 'Geburt', 'Rückkehr'],
        neg: ['Ruhelosigkeit', 'Veränderung um ihrer selbst willen', 'Unbeständigkeit'] },
  scene: 'Ein Storch auf langen Beinen, mitten im Zug. Er geht, und dann kommt er wieder.',
  core: 'Der Storch ist Veränderung — und anders als die meisten Veränderungskarten ist es eine Veränderung zum Besseren. Er umfasst Umzüge, Stellenwechsel, eine Verschiebung in einer Beziehung, und die wirkliche Geburt. Störche ziehen fort und kehren zurück, also trägt die Karte auch Rückkehr: etwas kommt wieder, oder etwas wechselt im Kreis. Wo der Sarg beendet und die Sense schneidet, wandelt der Storch — die Sache hört nicht auf, sie wird etwas anderes.',
  love: 'Eine Beziehung ändert ihre Form — sie wird offiziell, ihr zieht zusammen, oder sie geht in einen neuen Abschnitt. Verbesserung.',
  work: 'Ein Stellenwechsel, eine Beförderung, ein Wechsel in eine andere Abteilung oder Stadt. Eine willkommene Veränderung der Umstände.',
  who: 'Jemand im Übergang, eine Mutter, eine Hebamme. Ein Mensch, der sich vor Kurzem stark verändert hat.',
  time: 'Ein Wechsel der Jahreszeit — etwa siebzehn Tage, oder das Frühjahr.',
  combo: [['+ Haus', 'Ein Umzug. Ganz wörtlich.'],
          ['+ Kind', 'Dieses Paar wird häufig mit Schwangerschaft, Geburt oder einem neuen Anfang in der Familie verbunden.'],
          ['+ Sarg', 'Eine Veränderung, die etwas beendet, oder ein Ende, das zur Veränderung wird.']] },

18: { name: 'Der Hund', card: 'Herz 10', tone: 'pos', person: true,
  kw: { pos: ['ein Freund', 'Treue', 'Vertrauen', 'Verlässlichkeit', 'Vertrautheit', 'Rückhalt'],
        neg: ['Abhängigkeit', 'blinde Treue', 'aus Gewohnheit bleiben', 'nur ein Freund'] },
  scene: 'Ein Hund, der sitzt und wartet. Er war die ganze Zeit da.',
  core: 'Der Hund ist Treue und Freundschaft. Er ist eine der wärmsten Karten im Deck und zeigt auf jemanden Verlässlichen — einen Freund, einen Menschen, der bleibt, jemanden, der sich bewährt hat. Wörtlich gelesen heißt er oft einfach *ein Freund*, und in einer Liebeslegung ist das eine wichtige Information: Der Hund ist zugewandt und beständig, aber er ist nicht die Karte der Romantik. Er ist die Karte des Menschen, der auch morgen noch da ist.',
  love: 'Ein treuer Mensch an deiner Seite, oder jemand, der dich als Freund liebt. Wenn du nach einem Schwarm fragst, sei ehrlich: Der Hund kann treue Zuneigung heißen, und er kann die Freundschaftsecke heißen.',
  work: 'Ein vertrauenswürdiger Kollege, eine verlässliche Zusammenarbeit, ein langjähriger Kunde. Rückhalt, auf den du zählen kannst.',
  who: 'Ein Freund, ein treuer Partner, ein Unterstützer. Jemand Vertrautes und Sicheres.',
  time: 'Beständig und verlässlich. Es geschieht dann, wann es immer geschieht.',
  combo: [['+ Herz', 'Eine liebevolle Freundschaft, oder ein Freund, der mehr wird.'],
          ['+ Schlange', 'Ein falscher Freund — Verrat durch jemanden, dem du vertraut hast.'],
          ['+ Ring', 'Eine treue Bindung; eine Freundschaft, die zur Partnerschaft wird.']] },

19: { name: 'Der Turm', card: 'Pik 6', tone: 'neu',
  kw: { pos: ['Autorität', 'Struktur', 'eine Institution', 'Überblick', 'Grenzen'],
        neg: ['Abgeschiedenheit', 'Einsamkeit', 'Kälte', 'Bürokratie', 'ausgeschlossen sein'] },
  scene: 'Ein hoher steinerner Turm, der allein steht. Von oben sieht man weit, und niemand steht mit dir dort.',
  core: 'Der Turm ist die Institution und die einsame Höhe. Er umfasst Behörden und große Häuser — Ämter, Konzerne, Krankenhäuser, Gerichte — und die förmliche, unpersönliche Art, wie sie arbeiten. Auf der persönlichen Seite ist er Abgeschiedenheit: für sich stehen, eine Grenze halten, allein sein aus Wahl oder aus Umständen. Er trägt Autorität, Dauer, und eine gewisse Kälte.',
  love: 'Innere Distanz, jemand, der eine Mauer hält, oder eine Beziehung, die eher förmlich als warm ist. Auch: allein sein, und damit oft ganz zufrieden.',
  work: 'Eine große Organisation, ein förmliches Verfahren, Behörden oder Rechtssachen, eine leitende Stellung. Langfristig und bürokratisch.',
  who: 'Eine Autoritätsperson, ein Amtsträger, ein Einzelgänger. Jemand Zurückhaltendes, das mit sich auskommt.',
  time: 'Lang und behördlich. Langsam, weil ein System beteiligt ist.',
  combo: [['+ Herz', 'Liebe auf Abstand gehalten, oder ein einsames Herz.'],
          ['+ Ring', 'Ein amtlicher Vertrag — die standesamtliche Ehe, eine Vereinbarung zwischen Firmen.'],
          ['+ Park', 'Das Private trifft das Öffentliche — mit etwas an die Öffentlichkeit gehen, oder eine Behörde in den Nachrichten.']] },

20: { name: 'Der Park', card: 'Pik 8', tone: 'neu',
  kw: { pos: ['die Öffentlichkeit', 'eine Zusammenkunft', 'Gemeinschaft', 'Kontakte knüpfen', 'ein Treffen', 'Geselligkeit'],
        neg: ['Bloßstellung', 'keine Privatsphäre', 'oberflächlicher Kontakt', 'eine Menge'] },
  scene: 'Ein öffentlicher Park mit einem Weg hindurch. Hier darf jeder gehen.',
  core: 'Der Park ist der öffentliche Raum. Hier wirst du gesehen: gesellige Anlässe, Feste, Kontakte, das Internet, der Ruf, und alles, was vor anderen Menschen geschieht. Für sich ist er weder gut noch schlecht — er sagt nur, dass diese Sache nicht privat ist. Welche Karte neben dem Park steht, wird öffentlich bekannt oder findet unter Leuten statt.',
  love: 'Jemanden in Gesellschaft kennenlernen, eine Beziehung, die öffentlich ist, oder eine, die im gemeinsamen Freundeskreis stattfindet. Kennenlernen im Netz.',
  work: 'Kontakte knüpfen, eine Veranstaltung, Arbeit mit Publikum, Werbung, dein beruflicher Ruf. Ein Treffen mit mehreren Menschen.',
  who: 'Ein geselliger Mensch, die Öffentlichkeit selbst, eine Menge, ein Freundeskreis.',
  time: 'Wenn Menschen zusammenkommen. Im Sommer, oder bei der Veranstaltung.',
  combo: [['+ Herz', 'Eine öffentliche Romanze, oder jemanden bei einem geselligen Anlass kennenlernen.'],
          ['+ Vögel', 'Es wird geredet. Klatsch in einer Gruppe.'],
          ['+ Fische', 'Geschäfte unter Leuten — Handel, ein Markt, Einkünfte aus der Öffentlichkeit.']] },

21: { name: 'Der Berg', card: 'Kreuz 8', tone: 'neg',
  kw: { pos: ['Ausdauer', 'eine Herausforderung, die sich zu besteigen lohnt', 'Dauerhaftigkeit'],
        neg: ['eine Blockade', 'Verzögerung', 'ein Hindernis', 'Ferne', 'jemand Kaltes'] },
  scene: 'Eine Bergkette, Schnee auf den Gipfeln. Sie wird sich für dich nicht bewegen.',
  core: 'Der Berg ist das Hindernis. Etwas Großes steht im Weg, und es rückt nicht leicht zur Seite — eine Verzögerung, eine Blockade, eine harte Schranke zwischen dir und dem, was du willst. Er ist auch Ferne und Kälte: ein Mensch, den man nicht erreicht, eine Lage, die eingefroren ist. Der Berg sagt nicht nie. Er sagt: nicht auf diesem Weg, und nicht bald.',
  love: 'Eine blockierte Beziehung, ein ernstes Hindernis zwischen zwei Menschen, oder jemand innerlich Kaltes, den du nicht erreichst. Lange Verzögerungen.',
  work: 'Ein stockendes Vorhaben, eine blockierte Beförderung, behördliche Verzögerung, ein ernstes berufliches Hindernis.',
  who: 'Ein kalter, ferner oder blockierender Mensch. Ein Gegner, oder schlicht jemand Unbewegliches.',
  time: 'Blockiert. Unbestimmte Verzögerung — plan nicht damit.',
  combo: [['+ Herz', 'Eine blockierte Beziehung, oder ein Herz, das kalt geworden ist.'],
          ['+ Schlüssel', 'Das Hindernis wird überwunden — die Blockade löst sich. Ein sehr gutes Paar.'],
          ['+ Klee', 'Ein glücklicher Durchbruch am Hindernis vorbei, wenn auch ein kleiner.']] },

22: { name: 'Die Wege', card: 'Karo Dame', tone: 'neu',
  kw: { pos: ['Wahl', 'Möglichkeiten', 'Freiheit', 'Alternativen', 'eine Entscheidung'],
        neg: ['Unentschlossenheit', 'gespalten', 'zu viele Möglichkeiten', 'kein klarer Weg'] },
  scene: 'Ein Weg, der sich teilt, mit einem Wegweiser. Beide Richtungen sind echt.',
  core: 'Die Wege sind die Wahl. Es gibt mehr als eine Möglichkeit, und was herauskommt, hängt davon ab, welche du nimmst. Die Karte ist wirklich neutral: Sie sagt nicht, welcher Weg besser ist, nur dass die Entscheidung deine ist. Sie bedeutet auch Vielheit — zwei von etwas, Alternativen, und manchmal einen Menschen, der sich alles offenhält.',
  love: 'Eine Wahl zwischen zwei Menschen, oder eine Entscheidung darüber, ob es weitergeht. Auch jemand, der sich noch nicht entschieden hat — was für sich schon eine Antwort ist.',
  work: 'Eine Wahl zwischen Angeboten, eine berufliche Entscheidung, eine Gabelung in einem Vorhaben. Mehrere Möglichkeiten offen.',
  who: 'Jemand Unentschlossenes, jemand mit Auswahl, ein Mensch, der sich nicht festgelegt hat.',
  time: 'Es hängt an deiner Entscheidung. Der Zeitpunkt liegt bei dir.',
  combo: [['+ Herz', 'Eine Wahl in der Liebe, oder jemand, der sich zwischen zwei Menschen entscheidet.'],
          ['+ Sarg', 'Die Entscheidung lautet: beenden.'],
          ['+ Wolken', 'Eine Wahl in der Verwirrung — du siehst die Möglichkeiten nicht klar.']] },

23: { name: 'Die Mäuse', card: 'Kreuz 7', tone: 'neg',
  kw: { pos: ['es hört auf, sobald du es siehst', 'ein kleines Problem, früh bemerkt'],
        neg: ['Verlust', 'Auszehrung', 'Stress', 'Diebstahl', 'etwas wird weggefressen'] },
  scene: 'Mäuse, die an etwas arbeiten. Kein einzelner Biss zählt; die Summe zählt.',
  core: 'Die Mäuse sind der allmähliche Verlust. Etwas wird weggefressen — Geld, Kraft, Gesundheit, Vertrauen, Zeit. Der Schaden ist nicht dramatisch, und genau deshalb ist er gefährlich: Er geschieht nach und nach und fällt leicht erst auf, wenn schon viel weg ist. Die Mäuse bedeuten auch Stress und Sorge, und Diebstahl. Welche Karte neben ihnen liegt, wird kleiner.',
  love: 'Vertrauen oder Zuneigung sickern langsam weg. Eine Beziehung, die zermürbt wird statt zerbricht. Stress, der eine Bindung angreift.',
  work: 'Geld, das versickert, kleine laufende Verluste, Stress, Ausbrennen, oder etwas, das genommen wird. Prüf die Einzelheiten.',
  who: 'Jemand, der dich auslaugt. Ein sorgenvoller Mensch, oder ein kleiner Dieb.',
  time: 'Laufend und allmählich. Es geschieht genau jetzt, langsam.',
  combo: [['+ Fische', 'Geld geht verloren — Mittel versickern, Schulden, Diebstahl.'],
          ['+ Herz', 'Liebe, die sich abnutzt, oder Kummer und Stress.'],
          ['+ Baum', 'Dieses Paar wird häufig als länger anhaltender Stress gelesen, der Kraft oder Wohlbefinden beeinträchtigt.']] },

24: { name: 'Das Herz', card: 'Herz Bube', tone: 'pos',
  kw: { pos: ['Liebe', 'Zuneigung', 'Romantik', 'Wärme', 'Aufrichtigkeit', 'das Herz'],
        neg: ['Rührseligkeit', 'Liebe ohne Handeln', 'vom Gefühl regiert werden'] },
  scene: 'Ein einzelnes rotes Herz, unverwechselbar. Sonst ist nichts auf der Karte.',
  core: 'Das Herz ist die Liebe — das Gefühl selbst, in seiner klarsten Form. Es umfasst Romantik, Zuneigung, Wärme, Güte und echtes Empfinden. Es ist eine der eindeutigsten Karten im Deck: Wo das Herz auftaucht, ist wirkliches Gefühl da. Was es dir nicht sagt, ist, was jemand mit diesem Gefühl *tun* wird — das Herz ist Gefühl, nicht Bindung. Für die Bindung schau auf den Ring.',
  love: 'Liebe, schlicht. Echte Zuneigung, Romantik und Aufrichtigkeit. Wenn du nach jemandem fragst, den du magst, ist das die Karte, die du willst.',
  work: 'Arbeit, die du liebst, eine Arbeit mit echter Sorgfalt, gute Beziehungen zu Kollegen. Soziale und pflegende Berufe.',
  who: 'Ein warmer, liebevoller, großzügiger Mensch. Der geliebte Mensch.',
  time: 'Bald und warm. Im Sommer, oder wenn das Gefühl stimmt.',
  combo: [['+ Ring', 'Liebe und Bindung zusammen — das stärkste Beziehungspaar im Deck.'],
          ['+ Wolken', 'Verwirrte Gefühle, unklare Liebe, gemischte Signale.'],
          ['+ Berg', 'Blockierte Liebe — echtes Gefühl, das nicht durchkommt.']] },

25: { name: 'Der Ring', card: 'Kreuz Ass', tone: 'pos',
  kw: { pos: ['Bindung', 'ein Vertrag', 'Ehe', 'eine Partnerschaft', 'ein Versprechen', 'ein Kreislauf'],
        neg: ['eine Bindung, aus der du nicht herauskommst', 'ein sich wiederholender Kreis', 'Pflicht ohne Liebe'] },
  scene: 'Ein goldener Ring — ein geschlossener Kreis. Er hat kein Ende, und genau darum geht es.',
  core: 'Der Ring ist die Bindung und die Abmachung, die sie hält: Ehe, Vertrag, Partnerschaft, ein gegebenes Versprechen. Weil ein Ring ein geschlossener Kreis ist, bedeutet er auch Kreisläufe — etwas kommt wieder herum, ein Muster wiederholt sich, eine laufende Vereinbarung. Er sagt: Eine Bindung besteht. Ob diese Bindung liebevoll ist, ist eine andere Frage, und das Herz ist die Karte, die sie beantwortet.',
  love: 'Bindung, eine ernste Beziehung, Verlobung, Ehe. Oder eine Beziehung, die immer wieder von vorn beginnt.',
  work: 'Ein Vertrag, eine geschäftliche Partnerschaft, eine bindende Vereinbarung, eine laufende Abmachung. Lies die Bedingungen.',
  who: 'Ein Partner, ein Ehepartner, ein Geschäftspartner. Jemand, der dir durch eine Abmachung verbunden ist.',
  time: 'Ein voller Kreis — etwa ein Jahr, oder wenn der Vertrag wieder ansteht.',
  combo: [['+ Herz', 'Eine verbindliche, liebevolle Beziehung. Verlobung oder Ehe.'],
          ['+ Sense', 'Ein gebrochener Vertrag, eine gelöste Verlobung, eine durchtrennte Bindung.'],
          ['+ Schlange', 'Eine komplizierte Bindung — eine Falle im Vertrag, oder eine Affäre in einer Ehe.']] },

26: { name: 'Das Buch', card: 'Karo 10', tone: 'neu',
  kw: { pos: ['Wissen', 'Studium', 'Lernen', 'Fachkenntnis', 'Forschung'],
        neg: ['ein Geheimnis', 'etwas Verborgenes', 'Information, die du noch nicht hast'] },
  scene: 'Ein geschlossenes Buch mit Schließe. Alles, was es weiß, liegt innen.',
  core: 'Das Buch hat zwei Gesichter, und es ist dasselbe Gesicht: Wissen, und zurückgehaltenes Wissen. Geschlossen ist es ein Geheimnis — etwas, das man dir nicht gesagt hat, eine Information, die bewusst zurückgehalten wird, eine verborgene Seite der Lage. Geöffnet ist es Studium, Ausbildung, Fachkenntnis und Forschung. In einer Legung heißt es sehr oft einfach: Du hast das Bild noch nicht ganz.',
  love: 'Ein Geheimnis in der Beziehung, oder etwas, das man dir nicht gesagt hat. Auch ein Mensch, der sich nicht leicht öffnet.',
  work: 'Studium, Ausbildung, Abschlüsse, Forschung, oder besonderes Fachwissen. Auch vertrauliche Dinge bei der Arbeit.',
  who: 'Ein zurückhaltender, gebildeter, verschwiegener Mensch. Ein Lehrer, ein Studierender, ein Forscher.',
  time: 'Unbekannt — der Zeitpunkt ist noch nicht offen. Frag noch einmal, wenn du mehr weißt.',
  combo: [['+ Herz', 'Eine heimliche Liebe, oder verborgene Gefühle.'],
          ['+ Schlüssel', 'Das Geheimnis kommt heraus. Verborgenes Wissen wird offenbar.'],
          ['+ Fuchs', 'Etwas wird dir absichtlich verheimlicht.']] },

27: { name: 'Der Brief', card: 'Pik 7', tone: 'neu',
  kw: { pos: ['eine Nachricht', 'ein Dokument', 'schriftliche Nachricht', 'Kommunikation', 'ein Beleg'],
        neg: ['schlechte Nachricht schriftlich', 'Papierkram', 'etwas, das nur auf dem Papier steht'] },
  scene: 'Ein versiegelter Brief. Jemand hat das mit Absicht aufgeschrieben.',
  core: 'Der Brief ist die schriftliche Mitteilung: eine Nachricht, eine SMS, eine E-Mail, ein Dokument, eine Urkunde, Papierkram. Wo der Reiter die Nachricht bringt, ist der Brief die Nachricht selbst, in einer Form, die du behalten kannst. Er ist neutral — die Karte daneben sagt, ob die Nachricht willkommen ist. Seine leise Bedeutung: Es wird *festgehalten*. Etwas wird schriftlich gefasst statt bloß gesagt.',
  love: 'Eine Nachricht von jemandem, eine SMS, ein Brief. Worte auf einem Bildschirm statt eines Gesprächs von Angesicht zu Angesicht.',
  work: 'Ein Vertrag, ein Bericht, eine Bewerbung, ein Angebotsschreiben, Unterlagen. Alles Amtliche auf Papier.',
  who: 'Ein Schreibender, ein Sachbearbeiter, oder schlicht der Mensch, der schreibt statt anzurufen.',
  time: 'Wenn die Nachricht ankommt — ein paar Tage.',
  combo: [['+ Herz', 'Ein Liebesbrief, eine Nachricht über Gefühle, ein schriftliches Geständnis.'],
          ['+ Sarg', 'Schlechte Nachricht schriftlich — eine Kündigung, ein förmliches Ende.'],
          ['+ Ring', 'Ein Vertrag, ein amtliches Dokument, Papiere für die Ehe.']] },

28: { name: 'Der Herr', card: 'Herz Ass', tone: 'neu', person: true,
  kw: { pos: ['der Mann, um den es geht', 'der männliche Fragende', 'ein Partner', 'er'],
        neg: ['—'] },
  scene: 'Ein Mann, der steht und nach vorn schaut. Er ist das Thema, kein Sinnbild.',
  core: 'Der Herr ist ein Mensch, keine Eigenschaft. Ist der Fragende ein Mann, ist diese Karte er; geht die Frage um einen Mann, ist diese Karte dieser Mann. Er ist der Ankerpunkt der Legung — die Karten neben ihm beschreiben ihn, die Richtung, in die er schaut, zeigt, wem er zugewandt ist, und was hinter ihm liegt, ist seine Vergangenheit. Deute den Herrn nicht als Bedeutung. Finde ihn, und lies, was ihn umgibt.',
  love: 'Er — der Mann, nach dem du fragst, oder dein Partner. Die Karten neben ihm sind seine Gemütslage.',
  work: 'Ein Kollege, Chef oder Kunde. Der Mann in der beruflichen Lage.',
  who: 'Ein Mann, meist erwachsen. In einer gleichgeschlechtlichen Legung derjenige Partner, den die Legende dieser Karte zu Beginn zuweist.',
  time: 'Wann immer er handelt. Sein Zeitpunkt, nicht deiner.',
  combo: [['Herr + Herz', 'Er ist verliebt, oder er empfindet Zuneigung.'],
          ['Herr + Wolken', 'Er ist verwirrt, oder er verbirgt seine Gemütslage.'],
          ['Herr + Dame', 'Die beiden zusammen — der Abstand zeigt, wie nah sie einander wirklich sind.']] },

29: { name: 'Die Dame', card: 'Pik Ass', tone: 'neu', person: true,
  kw: { pos: ['die Frau, um die es geht', 'die weibliche Fragende', 'eine Partnerin', 'sie'],
        neg: ['—'] },
  scene: 'Eine Frau, die steht und nach vorn schaut. Sie ist das Thema, kein Sinnbild.',
  core: 'Die Dame ist ein Mensch, keine Eigenschaft. Ist die Fragende eine Frau, ist diese Karte sie; geht die Frage um eine Frau, ist diese Karte diese Frau. Sie verankert die Legung genauso wie der Herr — lies die Karten um sie herum als ihre Umstände, ihre Gefühle, und das, wem sie zugewandt ist. Der Abstand zwischen Herr und Dame auf dem Tisch ist ganz für sich schon eine Auskunft.',
  love: 'Sie — die Frau, nach der du fragst, oder deine Partnerin. Die Karten neben ihr beschreiben ihre Lage.',
  work: 'Eine Kollegin, Chefin oder Kundin. Die Frau in der beruflichen Lage.',
  who: 'Eine Frau, meist erwachsen. In einer gleichgeschlechtlichen Legung diejenige Partnerin, die die Legende dieser Karte zu Beginn zuweist.',
  time: 'Wann immer sie handelt. Ihr Zeitpunkt, nicht deiner.',
  combo: [['Dame + Herz', 'Sie ist verliebt, oder sie empfindet Zuneigung.'],
          ['Dame + Schlange', 'Eine Rivalin ist ihr nah, oder sie selbst ist die Verwicklung.'],
          ['Dame + Berg', 'Sie ist blockiert, fern, oder nicht zu erreichen.']] },

30: { name: 'Die Lilie', card: 'Pik König', tone: 'neu', person: true,
  kw: { pos: ['Reife', 'Frieden', 'Weisheit', 'Erfahrung', 'Harmonie', 'ein älterer Mann'],
        neg: ['Kälte', 'ein Altersunterschied', 'Sexualität', 'etwas, dessen Zeit vorbei ist'] },
  scene: 'Eine weiße Lilie, ganz geöffnet. Es ist keine junge Blume.',
  core: 'Die Lilie ist Reife — Frieden, Weisheit, und die Ruhe dessen, der schon eine Weile gelebt hat. Sie zeigt auf ältere Menschen, auf lange bestehende Verhältnisse, und auf Dinge, die mit Würde behandelt werden. Überliefert trägt sie zwei weitere Lesarten, die schlecht zusammenpassen und doch beide dazugehören: Sie ist eine Karte der Tugend und Reinheit, und sie ist die Karte der Sexualität in diesem Deck. Lies sie als Reife in dem Sinn, den die Nachbarkarte stützt.',
  love: 'Eine reife, friedliche Beziehung, oder ein älterer Partner. Ein Altersunterschied. Auch ausdrücklich körperliche Nähe.',
  work: 'Erfahrung auf hohem Niveau, lange Praxis, eine geachtete Stellung, der Ruhestand. Arbeit, die ruhig und gut erledigt wird.',
  who: 'Ein älterer Mann, ein Mentor, eine Vaterfigur, ein Mensch von Ansehen. Jemand Ruhiges und Erfahrenes.',
  time: 'Langsam und reif. Im Winter, oder im späteren Abschnitt von etwas.',
  combo: [['+ Herz', 'Eine reife, friedliche Liebe — oder körperliche Nähe.'],
          ['+ Herr', 'Ausdrücklich ein älterer Mann.'],
          ['+ Berg', 'Kälte und Ferne in einer reifen Lage.']] },

31: { name: 'Die Sonne', card: 'Karo Ass', tone: 'pos',
  kw: { pos: ['Erfolg', 'Kraft', 'Sieg', 'Wärme', 'Klarheit', 'ein großer Tag'],
        neg: ['ausbrennen', 'Überheblichkeit', 'zu viel des Guten'] },
  scene: 'Die Sonne in voller Stärke, ihre Strahlen reichen bis an den Rand der Karte.',
  core: 'Die Sonne ist Erfolg und Lebenskraft — die mit Abstand positivste Karte im Deck. Sie heißt: Es geht gut. Kraft, Wärme, Sieg, Anerkennung und echtes Glück. Sie stärkt außerdem alles, was neben ihr steht, macht eine schwere Karte leichter und eine gute ausgezeichnet. Bei einer Ja-Nein-Frage ist sie ein eindeutiges Ja.',
  love: 'Eine glückliche, warme Beziehung. Freude, und ein sehr gutes Ende. Wenn du gefragt hast, ob es gut geht: Es geht gut.',
  work: 'Erfolg, Anerkennung, ein Gewinn, Kraft für die Arbeit. Ein Vorhaben, das gut läuft und bei dem man es auch sieht.',
  who: 'Ein warmer, selbstsicherer, erfolgreicher Mensch. Jemand, dessen Anwesenheit einen Raum hebt.',
  time: 'Am Tag, im Sommer, und bald. Schnell und hell.',
  combo: [['+ Herz', 'Großes Glück in der Liebe. Eines der besten Paare im Deck.'],
          ['+ Fische', 'Finanzieller Erfolg — Geld, und es läuft gut.'],
          ['+ Wolken', 'Die Sonne hinter Wolken: Erfolg verzögert oder verdeckt, aber vorhanden.']] },

32: { name: 'Der Mond', card: 'Herz 8', tone: 'pos',
  kw: { pos: ['Gefühl', 'Anerkennung', 'Ruf', 'Ahnung', 'Romantik', 'ein Monat'],
        neg: ['Launenhaftigkeit', 'Täuschung', 'im Gefühl leben', 'gesehen werden wollen'] },
  scene: 'Eine Mondsichel an einem dunklen Himmel. Sie gibt Licht, aber wenig, und sie ändert jede Nacht ihre Gestalt.',
  core: 'Der Mond ist das Gefühlsleben und der Ruf — zwei Bedeutungen, die der Gedanke der Spiegelung verbindet. Nach innen ist er Gefühl, Ahnung, Traum und Romantik; nach außen Ehre, Anerkennung, Bekanntheit, und wie man dich sieht. Er ist außerdem die klarste Zeitkarte des Decks: ein Mond ist ein Monat. Er ist wärmer als der Mond im Tarot und weit weniger unheimlich.',
  love: 'Tiefes romantisches Gefühl, eine seelische Verbindung, eine innige Bindung. Auch das Auf und Ab der Gefühle.',
  work: 'Anerkennung, Ruf, kreative und künstlerische Arbeit, Nachtarbeit. Für etwas geehrt werden.',
  who: 'Ein gefühlvoller, ahnungsreicher, künstlerischer Mensch. Jemand Bekanntes, oder jemand, der es sein möchte.',
  time: 'Ein Monat. Oder nachts.',
  combo: [['+ Herz', 'Tiefe romantische Liebe — Gefühl und Empfindung zusammen.'],
          ['+ Sonne', 'Anerkennung und Erfolg. Gesehen werden, und es läuft gut.'],
          ['+ Wolken', 'Gefühlsverwirrung, oder ein Ruf, der Schaden nimmt.']] },

33: { name: 'Der Schlüssel', card: 'Karo 8', tone: 'pos',
  kw: { pos: ['Gewissheit', 'ja', 'eine Lösung', 'eine Öffnung', 'die Antwort', 'Erfolg'],
        neg: ['—'] },
  scene: 'Ein Schlüssel. Er ist kein Sinnbild für eine Tür; er ist das, was sie öffnet.',
  core: 'Der Schlüssel ist Gewissheit. Er heißt ja, er heißt: Die Tür geht auf, er heißt: Die Lösung ist gefunden. Wo das Buch etwas schließt, öffnet der Schlüssel es. In einer Ja-Nein-Legung ist er das stärkste Ja im Deck, und neben jeder blockierten Karte heißt er, dass die Blockade sich löst. Seine Botschaft ist, dass diese Sache geklärt ist, gelöst, oder kurz davor.',
  love: 'Ein klares Ja. Die Beziehung öffnet sich, die Antwort ist eindeutig, die Tür ist nicht verschlossen.',
  work: 'Eine Lösung für das Problem, eine Tür, die aufgeht, ein eindeutiges Ergebnis. Die Sache funktioniert.',
  who: 'Jemand Sicheres und Direktes, oder der Mensch, der die Antwort hat.',
  time: 'Jetzt, und mit Sicherheit. Wenn die Tür aufgeht.',
  combo: [['+ Herz', 'Gewissheit in der Liebe — die Antwort auf die Gefühlsfrage ist ja.'],
          ['+ Berg', 'Das Hindernis löst sich. Ein ausgezeichnetes Paar.'],
          ['+ Buch', 'Das Geheimnis wird offenbar.']] },

34: { name: 'Die Fische', card: 'Karo König', tone: 'pos',
  kw: { pos: ['Geld', 'Geschäft', 'Fülle', 'Fluss', 'Einkommen', 'Unabhängigkeit'],
        neg: ['Übermaß', 'Geld, das entgleitet', 'zu viel von etwas'] },
  scene: 'Ein Fisch in tiefem Wasser, darunter setzen sich Münzen auf dem Grund ab. Sowohl das Wasser als auch das Geld sind in Bewegung.',
  core: 'Die Fische sind Geld und Fluss. Sie umfassen Einkommen, Geschäft, Handel, Vermögen und Selbstständigkeit, und sie tragen den Sinn von etwas Bewegtem und Reichlichem — Fische kommen im Schwarm. Über das Finanzielle hinaus bedeuten sie Fülle jeder Art: viel von dem, was neben ihnen liegt. Bei geschäftlichen Fragen sind sie die unmittelbar günstigste Karte im Deck.',
  love: 'Ein großzügiger Mensch an deiner Seite, eine Beziehung mit materieller Behaglichkeit, oder eine Bindung, die leicht fließt. Manchmal auch: eine Beziehung, in der Geld eine Rolle spielt.',
  work: 'Einkommen, Geschäft, Selbstständigkeit, Verkauf, Anlage, Liquidität. Finanziell gut.',
  who: 'Ein Geschäftsmensch, jemand finanziell Unabhängiges, ein großzügiger Mensch. Ein Händler.',
  time: 'Fließend und fortlaufend. Wenn das Geld kommt — Zahltag, Monatsende.',
  combo: [['+ Bär', 'Eine große Geldsumme.'],
          ['+ Mäuse', 'Geld versickert — Verluste, Schulden, Schwund.'],
          ['+ Anker', 'Stabiles, verlässliches Einkommen. Finanzielle Sicherheit.']] },

35: { name: 'Der Anker', card: 'Pik 9', tone: 'pos',
  kw: { pos: ['Halt', 'Beharrlichkeit', 'Sicherheit', 'Arbeit', 'festhalten', 'ein langer Aufenthalt'],
        neg: ['festsitzen', 'beschwert sein', 'zu lange festhalten', 'unbeweglich'] },
  scene: 'Ein Anker auf dem Meeresgrund, die Kette straff. Er tut seine Arbeit, und die besteht darin, Bewegung zu stoppen.',
  core: 'Der Anker ist Halt und Ausdauer. Er heißt, dass etwas hält: eine Stelle, die bleibt, eine Beziehung, die trägt, eine Lage, die sich nicht ändern wird. Er ist auch die Karte der Arbeit im Sinne des *Broterwerbs*, und der Beharrlichkeit — dranbleiben, bis es klappt. Sein Schatten ist dieselbe Eigenschaft von der anderen Seite: festsitzen, und an etwas festhalten, lange nachdem du hättest loslassen sollen.',
  love: 'Eine Beziehung, die bleibt, ein Mensch, der bleibt. Sicherheit statt Aufregung. Oder eine Bindung, an der du über ihre Zeit hinaus festhältst.',
  work: 'Eine sichere Stelle, ein langes Arbeitsverhältnis, eine feste Position. Arbeit, die es nächstes Jahr noch gibt.',
  who: 'Ein beständiger, verlässlicher, unbeweglicher Mensch. Jemand, der nicht geht.',
  time: 'Lange anhaltend und dauerhaft. Es wird auch später noch gelten.',
  combo: [['+ Herz', 'Dauerhafte Liebe, eine Beziehung, die trägt.'],
          ['+ Fische', 'Sicheres Einkommen, eine stabile finanzielle Lage.'],
          ['+ Sarg', 'Eine langjährige Lage geht endlich zu Ende.']] },

36: { name: 'Das Kreuz', card: 'Kreuz 6', tone: 'neg',
  kw: { pos: ['Glaube', 'Sinn', 'eine Last, fast getragen', 'das Ende einer Prüfung'],
        neg: ['Leid', 'eine Last', 'Schicksal', 'Schuld', 'etwas, das du durchstehen musst'] },
  scene: 'Ein hölzernes Kreuz, in den Boden gesetzt. Es ist schwer, und es ist zum Tragen gedacht.',
  core: 'Das Kreuz ist Last und Schicksal. Es bezeichnet den schweren Teil: Leid, Verpflichtung, Schuld, und eine Schwierigkeit, durch die man hindurch muss statt außen herum. Es trägt auch echtes geistiges Gewicht — Glaube, Sinn, Bestimmung. Als letzte Karte des Decks zeigt es oft das Ende einer Prüfung an, es lohnt sich also zu lesen, was danach kommt. Das Kreuz ist schwer, aber es ist endlich.',
  love: 'Eine schmerzhafte oder belastende Beziehung. Leid in der Liebe, Schuld, oder eine Bindung, die sich schicksalhaft und schwer anfühlt.',
  work: 'Eine schwere Arbeitslast, eine Pflicht, die du nicht ablegen kannst, eine harte Zeit im Beruf.',
  who: 'Jemand Belastetes oder Leidendes. Ein gläubiger Mensch, oder ein Mensch, der andere trägt.',
  time: 'Eine Zeit der Prüfung, die endet. Das Ende eines Kreislaufs.',
  combo: [['+ Herz', 'Leid in der Liebe. Eine schmerzhafte Bindung.'],
          ['+ Sonne', 'Die Last hebt sich — die schwere Zeit endet gut.'],
          ['+ Sarg', 'Das Ende eines schweren Kapitels. Trauer, und ihr Abschluss.']] }

});
