/* ==================== Lenormand card text — Vietnamese ==================== */
/* Nghĩa các lá theo dòng Petit Lenormand phổ thông. Đây là một hệ thống khác
   tarot, có ngữ pháp riêng, và được để tách hẳn khỏi phần tarot của trang này:
   không có nội dung nào ở đây lấy từ bài giảng tarot của Thu Anh, và khi luận
   thì không nên trộn hai hệ vào nhau. */

Object.assign(LEN.vi, {

1: { name: 'Kỵ Mã', card: '9 Cơ', tone: 'neu', person: true,
  kw: { pos: ['tin tức', 'sự đến gần', 'chuyển động', 'khách ghé thăm', 'người chủ động', 'thể thao'],
        neg: ['bồn chồn', 'tin làm xáo trộn', 'người đến rồi đi, không ở lại'] },
  scene: 'Trên lá bài, một người cưỡi ngựa phóng ngang qua khung hình. Người đó đang hướng tới một đích nào đó, và trong tay người đó là một thứ thuộc về người khác.',
  core: 'Kỵ Mã đại diện cho tin tức và cho những gì đang từ bên ngoài tiến vào tình huống của bạn. Lá này cho biết có một điều đang trên đường đến với bạn, có thể là một tin nhắn, một con người, một cơ hội hoặc một thông tin. Tốc độ của nó rất cao, và Kỵ Mã thuộc nhóm những lá nhanh nhất trong bộ bài. Khi đứng một mình, nó mang một tin trung tính và nghiêng về hướng tốt. Lá nằm bên cạnh mới cho bạn biết tin đó nói về chuyện gì.',
  love: 'Bạn có thể nhận một tin nhắn, chứng kiến một bước chủ động đầu tiên, hoặc thấy một chàng trai trẻ bước vào câu chuyện. Liên lạc chắc chắn sẽ xảy ra. Tuy nhiên Kỵ Mã chỉ mang tin tức đến, lá này không mang theo sự cam kết.',
  work: 'Lá này chỉ một lời mời, một cuộc phỏng vấn, một đơn hàng hoặc một người giao hàng, và nó bao gồm mọi việc gắn với bán hàng hay thể thao. Nó cũng báo rằng một tình huống vốn đứng yên bắt đầu chuyển động.',
  who: 'Người được chỉ tới là một chàng trai trẻ, một vận động viên, một người đưa tin hoặc một người giao hàng. Người này năng động và nhanh nhẹn, đi ngang qua đời bạn chứ không ở lại.',
  time: 'Lá này chỉ thời gian rất nhanh. Sự việc thường diễn ra trong một đến ba ngày, đôi khi ngay trong ngày.',
  combo: [['+ Trái Tim', 'Một lời tỏ tình đang đến với bạn, dưới dạng một tin nhắn về tình cảm hoặc một lời thổ lộ.'],
          ['+ Lá Thư', 'Tin tức đến với bạn bằng chữ viết cụ thể, ví dụ một email, một tin nhắn hoặc một văn bản chính thức.'],
          ['+ Quan Tài', 'Một tin xấu đang đến, hoặc một tin báo rằng điều gì đó đã khép lại.']] },

2: { name: 'Cỏ Ba Lá', card: '6 Rô', tone: 'pos',
  kw: { pos: ['may mắn nhỏ', 'một cơ hội chớp nhoáng', 'sự nhẹ nhõm', 'một khe cửa hé ra'],
        neg: ['không kéo dài', 'cờ bạc, ăn may', 'điều không lặp lại được'] },
  scene: 'Một nhánh cỏ ba lá mọc sát mặt đất. Nhánh cỏ này rất nhỏ, và bạn sẽ bỏ sót nó nếu bạn không cúi xuống nhìn.',
  core: 'Cỏ Ba Lá mang ý nghĩa may mắn, nhưng đó là thứ may mắn nhỏ và đến nhanh. Một cánh cửa hé ra trong chốc lát, và cánh cửa đó không mở lâu. Lá này trả lời "có", song điều nó hứa chỉ khiêm tốn và tạm thời, và nó không làm thay đổi cả cuộc đời bạn. Trong một trải bài, giá trị lớn nhất của Cỏ Ba Lá là làm nhẹ lá nằm bên cạnh, vì một lá nặng đứng cạnh nó cũng trở nên dễ thở hơn.',
  love: 'Bạn gặp một khoảnh khắc dễ chịu, một lời tán tỉnh nhẹ nhàng, hoặc một chút may mắn trong quan hệ. Đây không phải lá của một mối quan hệ bền lâu, vì vậy bạn nên tận hưởng nó đúng như bản chất của nó.',
  work: 'Bạn nhận được một cơ hội nhỏ, một thắng lợi vừa phải, hoặc một vấn đề tự tháo gỡ. Bạn nên nắm lấy nó ngay, vì cơ hội này không chờ bạn.',
  who: 'Người được chỉ tới sống vô tư, gặp nhiều may mắn và không đặt nặng sự nghiêm túc. Bạn thấy vui khi ở cạnh người này, nhưng bạn khó xây dựng điều gì lâu dài cùng họ.',
  time: 'Lá này chỉ một khoảng thời gian rất ngắn, từ vài giờ đến vài ngày. Nếu bạn đang chờ đúng thời điểm, thời điểm đó chính là lúc này.',
  combo: [['+ Con Cá', 'Một khoản tiền nhỏ đến với bạn một cách bất ngờ.'],
          ['+ Mây', 'Bạn bỏ lỡ may mắn vì bạn không nhìn thấy nó. Cơ hội đã đến, nhưng bạn không nhận ra.'],
          ['+ Chiếc Nhẫn', 'Một cam kết đến cùng với may mắn, hoặc một thỏa thuận chỉ kéo dài trong ngắn hạn.']] },

3: { name: 'Con Thuyền', card: '10 Bích', tone: 'pos',
  kw: { pos: ['đi xa', 'du lịch', 'thương mại', 'chuyện nước ngoài', 'sự tiến triển'],
        neg: ['nhớ nhung', 'người ở xa', 'sự rời đi', 'khoảng cách cảm xúc'] },
  scene: 'Một con thuyền căng buồm giữa mặt nước rộng. Con thuyền đang rời xa nơi nó xuất phát.',
  core: 'Con Thuyền nói về khoảng cách và sự rời đi. Lá này bao gồm việc đi lại theo nghĩa đen, chuyện nước ngoài, hoạt động xuất nhập khẩu, và cả phiên bản cảm xúc của những điều đó: một người hoặc một việc đang ở rất xa, kèm theo nỗi nhớ. Vì con thuyền luôn chuyển động, lá này báo rằng tình hình vẫn đang đi tới. Tuy nhiên nó đi chậm, và nó đi ra xa khỏi chỗ đứng hiện tại của bạn.',
  love: 'Bạn có thể đang yêu xa, gắn bó với một người sống ở nơi khác, hoặc ở cạnh một người mà tâm trí đang đặt ở nơi nào đó khác. Lá này cũng chỉ một mối quan hệ bắt đầu trong một chuyến đi.',
  work: 'Lá này gắn với xuất nhập khẩu, công việc quốc tế, các chuyến công tác, hoặc một hướng nghề nghiệp đưa bạn tới nơi khác. Tiến triển vẫn có, nhưng bạn cần thời gian để tới đích.',
  who: 'Người được chỉ tới là người nước ngoài, người hay đi lại, người sống ở xa, hoặc một thương nhân. Đó cũng có thể là người luôn chuẩn bị rời đi trong đời bạn.',
  time: 'Lá này chỉ nhịp thời gian chậm, kéo dài từ vài tuần đến vài tháng. Thời điểm cũng có thể trùng với lúc chuyến đi diễn ra.',
  combo: [['+ Trái Tim', 'Bạn đang yêu xa, hoặc bạn bắt đầu một mối tình trong lúc đi xa.'],
          ['+ Ngôi Nhà', 'Bạn chuyển nhà, đổi chỗ ở, hoặc bạn có một mái nhà ở nước ngoài.'],
          ['+ Quan Tài', 'Một chuyến đi kết thúc, hoặc một lần rời đi khép lại điều gì đó vĩnh viễn.']] },

4: { name: 'Ngôi Nhà', card: 'K Cơ', tone: 'pos',
  kw: { pos: ['mái ấm', 'gia đình', 'sự an toàn', 'ổn định', 'nhà cửa', 'truyền thống'],
        neg: ['mắc kẹt trong cái quen thuộc', 'áp lực gia đình', 'quá bảo thủ'] },
  scene: 'Một ngôi nhà vững chãi với cửa đóng và đèn sáng trong khung cửa sổ. Ngôi nhà này đứng yên tại chỗ.',
  core: 'Ngôi Nhà là nền móng của bạn, bao gồm căn nhà có thật, gia đình, và cảm giác an toàn sinh ra từ cả hai. Đây là một trong những lá ổn định nhất bộ bài, và nó neo lại bất cứ lá nào đứng cạnh. Con Thuyền đi ra xa, còn Ngôi Nhà ở lại. Lá này thường chỉ một chuyện thuộc về gia đình và đời sống riêng tư, không phải chuyện ngoài xã hội.',
  love: 'Lá này chỉ một mối quan hệ mang chất "về nhà": hai người sống chung, ra mắt gia đình, và cùng xây một chỗ để ở trong đó. Nó thiên về sự an toàn hơn là sự hồi hộp.',
  work: 'Lá này chỉ việc làm tại nhà, kinh doanh gia đình, bất động sản, hoặc một công việc bạn chọn vì sự yên ổn thay vì vì tham vọng.',
  who: 'Người được chỉ tới là một thành viên trong gia đình, một hình bóng người cha, một chủ nhà, hoặc một người truyền thống và đáng tin.',
  time: 'Lá này chỉ một nhịp ổn định và không vội, khoảng bốn tuần. Thời điểm cũng có thể là lúc bạn đang ở nhà.',
  combo: [['+ Chiếc Nhẫn', 'Hai người kết hôn, dọn về sống chung, hoặc ký một hợp đồng nhà đất.'],
          ['+ Đàn Chuột', 'Mái ấm đang bị bào mòn dần. Bạn mất mát tài sản, chịu căng thẳng trong nhà, hoặc gia đình đang rút cạn sức lực của bạn.'],
          ['+ Con Cá', 'Cặp này nói về tiền của gia đình, thu nhập từ nhà đất, và sự an toàn tài chính.']] },

5: { name: 'Cái Cây', card: '7 Cơ', tone: 'neu',
  kw: { pos: ['sức khỏe', 'sự lớn lên', 'gốc rễ', 'chiều sâu', 'sinh lực', 'sự gắn kết'],
        neg: ['chậm chạp', 'bệnh tật', 'trì trệ', 'chuyện đã kéo dài từ lâu'] },
  scene: 'Một cái cây đứng một mình, tán dày và thân lớn. Phần rễ mới là phần bạn không nhìn thấy.',
  core: 'Cái Cây là lá của sức khỏe, đồng thời là lá của sự lớn lên sâu và chậm. Mọi thứ thuộc về Cái Cây đều cần thời gian, vì lá này không làm gì nhanh. Nó nói về những gì có gốc rễ: bệnh mãn tính, mối dây sâu đậm, huyết thống, và chính cơ thể bạn. Trong trải bài, Cái Cây khẳng định rằng chuyện này là thật và có chiều sâu, đồng thời báo trước rằng chuyện này sẽ không xong sớm.',
  love: 'Lá này chỉ một mối dây sâu và lớn lên chậm, đôi khi mang màu duyên nợ hoặc thân thuộc như người trong nhà. Đây không phải pháo hoa, đây là rễ.',
  work: 'Bạn đi một con đường nghề nghiệp chậm mà chắc, làm công việc y tế và chăm sóc, hoặc gắn bó với một việc mà mười năm nữa bạn vẫn còn làm.',
  who: 'Người được chỉ tới là bác sĩ hoặc người chữa lành, một người họ hàng, hoặc một người kiên nhẫn và có gốc rễ sâu.',
  time: 'Lá này chỉ nhịp thời gian rất chậm, kéo dài từ vài tháng đến vài năm. Cái Cây là lá nói rằng chưa phải bây giờ.',
  combo: [['+ Quan Tài', 'Đây là cặp cảnh báo sức khỏe kinh điển. Nó chỉ bệnh tật, hoặc một tình trạng đang đi đến hồi kết.'],
          ['+ Mặt Trời', 'Bạn có sức khỏe tốt, sinh lực dồi dào và khả năng hồi phục.'],
          ['+ Ngọn Núi', 'Một tắc nghẽn đã tồn tại từ rất lâu. Quá trình chữa lành diễn ra chậm, và sự trì hoãn kéo dài.']] },

6: { name: 'Mây', card: 'K Chuồn', tone: 'neg',
  kw: { pos: ['rồi sẽ qua', 'trời đang hửng', 'một màn sương tạm thời'],
        neg: ['mơ hồ', 'hoang mang', 'thiếu rõ ràng', 'rắc rối', 'điều bị che khuất'] },
  scene: 'Lá bài có hai mảng mây, một mảng tối và một mảng sáng. Theo truyền thống, phía tối chỉ ra chỗ rắc rối đang nằm.',
  core: 'Mây nói về sự mơ hồ, sự nghi ngờ, và những gì bạn chưa nhìn rõ. Đây không phải một thảm họa, đây là sương mù. Có một phần trong tình huống còn chưa rõ, hoặc vì bạn thiếu thông tin, hoặc vì có người đang rối. Theo lối luận cổ điển, lá này có hướng: phía tối chỉ vào đâu thì đó là phần rắc rối, còn phía sáng chỉ vào đâu thì đó là phần sẽ sáng ra.',
  love: 'Bạn nhận những tín hiệu lẫn lộn, đứng trong một mối quan hệ không rõ ràng, hoặc gặp một người không hiểu nổi lòng mình. Đây chính là lá chỉ sự mập mờ trong bộ Lenormand.',
  work: 'Lá này chỉ một tình huống rối ở chỗ làm, những chỉ đạo không rõ ràng, hoặc một quyết định được đưa ra khi thông tin còn thiếu.',
  who: 'Người được chỉ tới khó đoán, thất thường và hay né tránh. Người này không hẳn nói dối, nhưng bạn không đọc được họ.',
  time: 'Lá này không xác định thời điểm, và chính điều đó là thông điệp của nó. Sương thường tan trong khoảng một đến ba ngày.',
  combo: [['+ Trái Tim', 'Cảm xúc đang rối. Bạn ở trong một mối tình không rõ ràng và nhận những tín hiệu lẫn lộn.'],
          ['+ Chìa Khóa', 'Sự mơ hồ được hóa giải. Mọi thứ sáng tỏ và sương tan.'],
          ['+ Con Cáo', 'Sự mơ hồ này mang tính cố ý. Có người đang chủ động làm đục nước.']] },

7: { name: 'Con Rắn', card: 'Q Chuồn', tone: 'neg', person: true,
  kw: { pos: ['sự khôn ngoan', 'quyến rũ', 'một đường vòng cần thiết', 'lột xác'],
        neg: ['phản bội', 'người thứ ba', 'rắc rối', 'lời nói dối', 'đường đi quanh co'] },
  scene: 'Một con rắn cuộn mình thành chữ S dài. Con rắn không bao giờ đi thẳng, và nó rất đẹp.',
  core: 'Con Rắn chỉ sự rắc rối, và cụ thể là loại rắc rối có một con người đứng sau. Theo truyền thống, đó là một người phụ nữ khác, một tình địch, hoặc một người đang hành động ngược lại lợi ích của bạn. Ở nghĩa rộng hơn, lá này gom mọi thứ không đi thẳng: một đường vòng, một sự vướng víu, một lời nói dối, hoặc một lối đi loanh quanh tới điều bạn muốn. Con Rắn không hề thiếu khôn ngoan, vì đây là lá của trí khôn được dùng cho mục đích riêng.',
  love: 'Lá này chỉ người thứ ba, một tình địch, một mối quan hệ ngoài luồng, hoặc một quan hệ chứa rắc rối nghiêm trọng bên trong. Ham muốn ở đây có thật, nhưng tình huống không hề đơn giản.',
  work: 'Bạn gặp chính trị công sở, đồng nghiệp chơi xấu, một thỏa thuận có điều kiện giấu kín, hoặc một quy trình rối rắm.',
  who: 'Người được chỉ tới là một phụ nữ làm mọi thứ phức tạp lên, có thể là tình địch, người cũ, hoặc người thao túng. Đó cũng có thể chỉ là một người thông minh, quyến rũ và khó đối phó.',
  time: 'Lá này chỉ nhịp chậm và quanh co. Sự việc sẽ không đi theo đường thẳng, vì vậy bạn nên cộng thêm thời gian.',
  combo: [['+ Trái Tim', 'Bạn gặp một tình địch trong chuyện tình cảm, hoặc một sức quyến rũ đang tác động. Có người khác đang hiện diện trong bức tranh.'],
          ['+ Chiếc Nhẫn', 'Đây là một cam kết phức tạp, một chuyện ngoại tình trong hôn nhân, hoặc một hợp đồng có cài bẫy.'],
          ['+ Người Phụ Nữ', 'Bạn nên hiểu cặp này theo nghĩa đen: có một người phụ nữ khác dính vào chuyện này.']] },

8: { name: 'Quan Tài', card: '9 Rô', tone: 'neg',
  kw: { pos: ['một kết thúc dứt khoát', 'sự chuyển hóa', 'khép lại', 'buông bỏ'],
        neg: ['mất mát', 'bệnh tật', 'đau buồn', 'sự kết thúc', 'đình trệ'] },
  scene: 'Một cỗ quan tài nằm đó với nắp đã đóng. Điều nằm bên trong đã kết thúc, và nắp đã hạ xuống.',
  core: 'Quan Tài đánh dấu một kết thúc. Đây là lá của những gì đã qua: một mối quan hệ, một công việc, một chặng đời, và đôi khi một đợt bệnh. Trong cách luận hiện đại, lá này hiếm khi chỉ cái chết theo nghĩa đen, nhưng nó thật sự dứt điểm. Bạn nên luận nó một cách trung thực thay vì làm nhẹ đi, và bạn nên đọc lá bên cạnh, vì Quan Tài mô tả điều đã kết thúc còn lá kế bên mô tả chỗ trống mà nó để lại.',
  love: 'Một mối quan hệ kết thúc, tình cảm đã chết, hoặc một giai đoạn đau buồn bắt đầu. Nếu bạn hỏi chuyện này đã hết hay chưa, lá này trả lời rằng nó đã hết.',
  work: 'Một công việc chấm dứt, một dự án bị hủy, hoặc một cơ sở đóng cửa. Lá này cũng chỉ tình trạng kiệt sức, khi năng lượng của bạn đã cạn.',
  who: 'Người được chỉ tới đang để tang, đang thu mình lại, hoặc đã đóng cửa cảm xúc của họ.',
  time: 'Lá này chỉ một giai đoạn đang khép lại, khoảng tám tuần. Thời điểm cũng có thể là lúc sự việc kết thúc, và điều đó có thể đã xảy ra rồi.',
  combo: [['+ Trái Tim', 'Một mối quan hệ kết thúc, hoặc một trái tim tan vỡ.'],
          ['+ Con Cò', 'Một kết thúc trở thành một thay đổi tốt hơn. Đây là cặp chuyển hóa kinh điển.'],
          ['+ Cái Cây', 'Cặp này nói về sức khỏe, hoặc về một tình trạng kéo dài đang đi đến hồi kết.']] },

9: { name: 'Bó Hoa', card: 'Q Bích', tone: 'pos',
  kw: { pos: ['món quà', 'lời mời', 'sự duyên dáng', 'vẻ đẹp', 'sự trân trọng', 'một lời đề nghị dễ chịu'],
        neg: ['lời nịnh', 'duyên bề mặt', 'một cử chỉ không có gì phía sau'] },
  scene: 'Một bó hoa đã được gói sẵn và đang chờ người nhận. Nó tồn tại vì một lý do duy nhất, đó là để được đem tặng.',
  core: 'Bó Hoa là một lời đề nghị dễ chịu, có thể là một món quà, một lời mời, một lời khen, hoặc một sự tử tế đang đến. Đây là một trong những lá thân thiện nhất bộ bài, và nó làm ngọt lại bất cứ thứ gì nó chạm vào. Bạn chỉ cần lưu ý một điểm: bó hoa nằm ở bề mặt. Nó đẹp và thật sự dễ chịu, nhưng tự nó không chứng minh được chiều sâu. Có người đang đối xử rất đẹp với bạn, còn câu hỏi họ có thật lòng hay không thuộc về lá kế bên.',
  love: 'Bạn đang được theo đuổi. Bạn nhận lời khen, quà, lời mời, và có một người đang cố gắng làm bạn vui. Đây là dấu hiệu rất tốt trong một trải bài mập mờ.',
  work: 'Bạn được ghi nhận, được thưởng, có một bài thuyết trình được đón nhận, hoặc nhận một lời mời tham dự. Lá này cũng chỉ công việc sáng tạo và thẩm mỹ.',
  who: 'Người được chỉ tới duyên dáng, lịch thiệp và ưa nhìn. Người này khiến mọi chuyện trở nên dễ chịu.',
  time: 'Lá này chỉ một thời điểm sớm và êm đẹp, khoảng chín ngày.',
  combo: [['+ Trái Tim', 'Bạn nhận một cử chỉ lãng mạn, có thể là hoa, quà, hoặc một lời bày tỏ tình cảm.'],
          ['+ Con Cáo', 'Đây là lời nịnh có mục đích. Sự duyên dáng ở đây đóng vai trò một chiến thuật.'],
          ['+ Chiếc Nhẫn', 'Bạn nhận một lời cầu hôn, một món quà đính hôn, hoặc một đề nghị đẹp có cam kết đứng phía sau.']] },

10: { name: 'Lưỡi Hái', card: 'J Rô', tone: 'neg',
  kw: { pos: ['một nhát cắt dứt khoát', 'mùa gặt', 'loại bỏ gọn ghẽ', 'phẫu thuật'],
        neg: ['mất mát đột ngột', 'nguy hiểm', 'kết thúc bất ngờ', 'sự đứt gãy'] },
  scene: 'Một lưỡi hái được giơ cao. Nó chỉ hoạt động theo một cách duy nhất, đó là cắt thật nhanh trong một lần.',
  core: 'Lưỡi Hái là nhát cắt bất ngờ. Nếu Quan Tài là cái kết lắng dần xuống, Lưỡi Hái là cái kết xảy ra trong một khoảnh khắc, không báo trước và thường không kèm theo thảo luận. Đây cũng là lá của quyết định, cụ thể là quyết định cắt đứt một thứ. Đặc tính then chốt của nó là tốc độ, vì bất cứ điều gì nó chạm vào đều xảy ra đột ngột. Theo truyền thống, lưỡi dao chỉ về hướng nào thì thứ nằm ở hướng đó đang bị cắt.',
  love: 'Bạn chia tay đột ngột, bị cắt liên lạc, hoặc chứng kiến một quyết định đưa ra không báo trước. Đây cũng là lá của lần chính bạn dứt khoát chấm dứt.',
  work: 'Bạn bị cho nghỉ, hợp đồng bị hủy, hoặc dự án bị dừng. Lá này còn chỉ phẫu thuật và mọi công việc dùng dao kéo hoặc đòi hỏi độ chính xác.',
  who: 'Người được chỉ tới hành động dứt khoát và đột ngột. Đó là bác sĩ phẫu thuật, nha sĩ, hoặc một người kết thúc mọi thứ mà không cần nói chuyện.',
  time: 'Lá này chỉ thời điểm ngay lập tức. Sự việc xảy ra bây giờ, hoặc xảy ra hoàn toàn không báo trước.',
  combo: [['+ Trái Tim', 'Hai người chia tay đột ngột, hoặc một bên quyết định chấm dứt mối quan hệ.'],
          ['+ Cái Cây', 'Cặp này chỉ một ca phẫu thuật, hoặc một biến cố sức khỏe xảy đến bất ngờ.'],
          ['+ Chiếc Nhẫn', 'Một hợp đồng bị hủy, một cuộc hôn nhân chấm dứt, hoặc một lời hứa bị bẻ gãy.']] },

11: { name: 'Ngọn Roi', card: 'J Chuồn', tone: 'neg',
  kw: { pos: ['kỷ luật', 'năng lượng thể chất', 'sự lặp lại có tích lũy', 'chuyện chăn gối'],
        neg: ['cãi vã', 'xung đột', 'lặp đi lặp lại', 'lại đúng cuộc cãi đó', 'bạo hành'] },
  scene: 'Hai cây roi bắt chéo nhau. Ở đây không có gì xảy ra một lần duy nhất, vì Ngọn Roi luôn là một động tác lặp lại.',
  core: 'Ngọn Roi nói về xung đột và sự lặp lại. Từ khóa cốt lõi của nó là "lại nữa": vẫn cuộc cãi đó, vẫn cái vòng đó, vẫn cách phản ứng đó. Lá này bao gồm cãi cọ, chỉ trích, và cả sự mệt mỏi của một cuộc tranh cãi liên tục mở lại. Mặt còn lại của nó thuộc về thể chất, gồm thể thao, tập luyện, lao động nặng và tình dục. Cả hai cách luận đều chạy trên cùng một động cơ, đó là một việc được làm đi làm lại.',
  love: 'Hai người cãi nhau lặp đi lặp lại, và mối quan hệ xoay quanh mãi một chuyện. Ở một tông khác, lá này chỉ sức hút thể xác mạnh.',
  work: 'Bạn gặp mâu thuẫn với đồng nghiệp, bị chỉ trích, làm công việc lặp lại, hoặc làm lao động chân tay. Một tranh chấp cũ liên tục mở lại.',
  who: 'Người được chỉ tới hay tranh cãi, thiên về thể chất, hoặc nóng tính. Đó là vận động viên, huấn luyện viên, hoặc người bạn liên tục va chạm.',
  time: 'Lá này chỉ một nhịp kéo dài và lặp lại. Sự việc sẽ xảy ra nhiều hơn một lần trước khi kết thúc.',
  combo: [['+ Trái Tim', 'Đây là một mối quan hệ giông bão, nơi đam mê và cãi vã cùng tồn tại.'],
          ['+ Mây', 'Một cuộc cãi không đi tới đâu, vì không ai nói rõ được điều gì.'],
          ['+ Quan Tài', 'Cuộc cãi vã chấm dứt, hoặc mối quan hệ chấm dứt vì cãi vã.']] },

12: { name: 'Đôi Chim', card: '7 Rô', tone: 'neu',
  kw: { pos: ['trò chuyện', 'một cặp', 'cuộc gọi', 'thương lượng', 'sự rộn ràng'],
        neg: ['đàm tiếu', 'lo âu', 'nói nhiều', 'căng thẳng thần kinh', 'nói thay vì làm'] },
  scene: 'Hai con chim nhỏ cùng hót một lúc. Trên lá luôn có hai con, và tiếng của chúng luôn ồn.',
  core: 'Đôi Chim là lời nói. Lá này gồm điện thoại, trò chuyện, thương lượng, tin đồn, và cả tiếng ồn lo lắng trong đầu bạn. Vì trên lá có hai con chim, nó còn mang nghĩa một cặp: hai người, một đôi, hoặc hai của bất cứ thứ gì. Nội dung của nó ngắn và bận rộn hơn là sâu, và luôn có một tiếng vo ve lo âu ở phía nền.',
  love: 'Bạn có một cuộc nói chuyện với người kia, một cuộc gọi, hoặc bạn đang ở trong một cặp đôi. Lá này cũng chỉ sự lo lắng về mối quan hệ và việc người khác đang bàn tán về nó.',
  work: 'Lá này chỉ họp hành, gọi điện, đàm phán, truyền thông và các công việc giao tiếp. Nó cũng chỉ chuyện ngồi lê đôi mách ở công ty.',
  who: 'Người được chỉ tới nói nhiều, hòa đồng và hay lo. Lá này cũng chỉ hai người, anh chị em, hoặc người làm bán hàng và truyền thông.',
  time: 'Lá này chỉ một nhịp nhanh nhưng rối, kéo dài từ mười hai giờ đến mười hai ngày.',
  combo: [['+ Trái Tim', 'Hai người có một cuộc nói chuyện về tình cảm, hoặc họ tạo thành một cặp đôi.'],
          ['+ Mây', 'Tin đồn và sự rối rắm cùng xuất hiện. Người ta bàn tán trong khi không ai nắm rõ sự thật.'],
          ['+ Chiếc Nhẫn', 'Hai bên thương lượng về một cam kết, hoặc họ đang thống nhất các điều kiện.']] },

13: { name: 'Đứa Trẻ', card: 'J Bích', tone: 'pos', person: true,
  kw: { pos: ['khởi đầu mới', 'ngây thơ', 'một đứa trẻ', 'một thứ nhỏ bé', 'năng lượng mới'],
        neg: ['non nớt', 'ngây ngô', 'thiếu kinh nghiệm', 'mới quá nên chưa tin được'] },
  scene: 'Một đứa trẻ nhỏ đứng một mình. Mọi thứ ở đứa trẻ này đều còn rất sớm.',
  core: 'Đứa Trẻ nói về khởi đầu và sự nhỏ bé. Lá này chỉ một đứa trẻ có thật, và chỉ bất cứ điều gì đang ở vạch xuất phát: một mối quan hệ mới, một công việc mới, hoặc một ý tưởng mới. Bất cứ thứ gì nó chạm vào đều trở nên trẻ hơn và nhỏ hơn, ví dụ một khoản tiền nhỏ, một vấn đề nhỏ, hoặc một giai đoạn còn sớm. Điểm cần nói thật là sự thiếu kinh nghiệm: Đứa Trẻ rất chân thành, nhưng nó chưa biết mình đang làm gì.',
  love: 'Bạn bước vào một mối quan hệ mới, hoặc một mối quan hệ vẫn còn ở giai đoạn đầu. Tình cảm ở đây trong sáng và chân thật, nhưng nó chưa chín. Lá này cũng có nghĩa đen là một đứa con hoặc một lần mang thai.',
  work: 'Lá này chỉ một công việc mới, một người mới vào nghề, một dự án nhỏ, hoặc một lần bắt đầu lại. Nó cũng chỉ việc làm với trẻ em và trong ngành giáo dục.',
  who: 'Người được chỉ tới là một đứa trẻ, một người trẻ, hoặc một người còn ngây thơ và mới mẻ. Chất trẻ con ở đây vừa đáng yêu vừa có thể gây khó chịu.',
  time: 'Lá này chỉ đoạn khởi đầu của một sự việc. Khoảng thời gian ngắn và đến sớm.',
  combo: [['+ Trái Tim', 'Bạn có một tình yêu mới, một mối tình non trẻ và một tình cảm trong sáng.'],
          ['+ Con Cò', 'Cặp này chỉ việc mang thai, sinh nở, hoặc một khởi đầu làm thay đổi tất cả.'],
          ['+ Con Rắn', 'Có người đang lợi dụng sự ngây thơ.']] },

14: { name: 'Con Cáo', card: '9 Chuồn', tone: 'neg', person: true,
  kw: { pos: ['sự khôn khéo', 'chiến lược', 'tự bảo vệ', 'công việc kiếm sống'],
        neg: ['lừa dối', 'một cái bẫy', 'vụ lợi', 'bạn giả', 'một sai sót'] },
  scene: 'Một con cáo đang quan sát. Nó chưa bắt đầu săn, nó đang tính toán.',
  core: 'Con Cáo nói về sự tinh ranh và tính vụ lợi. Có người đang hành động vì lợi ích của chính họ, và họ làm điều đó một cách khôn khéo. Mức độ trải từ chiến thuật vô hại tới lừa dối trắng trợn, và lá bên cạnh cho biết mức nào đang đúng. Trong hầu hết các dòng, Con Cáo còn là lá của công việc kiếm sống, tức là cái nghề bạn làm để có tiền. Lá này cũng cảnh báo sai sót, vì có điều gì đó không đúng như nó đang được trình bày.',
  love: 'Lá này chỉ một người có toan tính, một người không thẳng thắn với bạn, hoặc một mối quan hệ mà một bên đang chơi trò chơi riêng.',
  work: 'Lá này chỉ chính công việc của bạn, một đồng nghiệp khó chịu, chính trị công sở, hoặc một lỗi sai trong công việc. Bạn nên đọc kỹ trước khi ký.',
  who: 'Người được chỉ tới khôn ngoan và vụ lợi. Đó là đồng nghiệp, đối thủ, kẻ lừa đảo, hoặc đơn giản là một người giỏi tính toán.',
  time: 'Bạn không nên tin vào lịch hẹn đã có. Sự việc đến muộn hơn lời hứa, hoặc diễn ra khác với những gì người ta nói.',
  combo: [['+ Trái Tim', 'Tình cảm ở đây không thật lòng, hoặc một người yêu vì một mục đích khác.'],
          ['+ Bó Hoa', 'Có người dùng lời ngọt như một công cụ.'],
          ['+ Chìa Khóa', 'Mánh khóe bị lật tẩy, và sự thật về nó lộ ra.']] },

15: { name: 'Con Gấu', card: '10 Chuồn', tone: 'pos', person: true,
  kw: { pos: ['sức mạnh', 'quyền lực', 'sự che chở', 'thẩm quyền', 'tiền lớn', 'người chống lưng'],
        neg: ['áp đảo', 'ghen tuông', 'kiểm soát', 'sức nặng', 'quá đà'] },
  scene: 'Một con gấu lớn xuất hiện. Chỉ riêng sự có mặt của nó đã làm đổi cả căn phòng, và không có gì ở nó là tinh tế.',
  core: 'Con Gấu là quyền lực. Lá này bao gồm sức mạnh, sự bảo vệ, và người nắm thẩm quyền trong tình huống, có thể là một người sếp, một hình bóng người mẹ, hoặc một người giữ nguồn lực. Nó cũng là lá của những khoản tiền lớn và của khối lượng vật chất. Con Gấu bảo vệ những gì thuộc về nó, và đó vừa là đức tính vừa là vấn đề của nó, vì mặt tối của Con Gấu là sự chiếm hữu và kiểm soát.',
  love: 'Bạn có một người bạn đời mạnh mẽ và che chở, hoặc một người chiếm hữu và ghen tuông. Người này thường lớn tuổi hơn hoặc có vị thế cao hơn trong quan hệ.',
  work: 'Lá này chỉ sếp của bạn, người có quyền, một khoản tiền lớn, và các việc tài chính và quản lý. Nó cũng chỉ một chỗ dựa đáng tin.',
  who: 'Người được chỉ tới là sếp, người mẹ, người lớn tuổi hoặc to lớn hơn, hoặc người có thẩm quyền. Người này mạnh mẽ, che chở và khó cãi lại.',
  time: 'Lá này chỉ một nhịp dài và nặng. Bạn nên tính bằng tháng thay vì bằng tuần.',
  combo: [['+ Con Cá', 'Cặp này chỉ tiền lớn: một khoản đáng kể, sự giàu có, hoặc một khoản đầu tư.'],
          ['+ Trái Tim', 'Đây là một tình yêu có che chở, hoặc một tình yêu ghen tuông và kiểm soát.'],
          ['+ Con Rắn', 'Hai bên tranh giành quyền lực, hoặc một tình địch đầy ghen tuông xuất hiện.']] },

16: { name: 'Những Vì Sao', card: '6 Cơ', tone: 'pos',
  kw: { pos: ['hy vọng', 'sự sáng tỏ', 'định hướng', 'con đường rõ ràng', 'cảm hứng', 'số nhiều'],
        neg: ['tản mát', 'giấc mơ không có kế hoạch', 'ôm quá nhiều thứ', 'ban đêm'] },
  scene: 'Một bầu trời đêm đầy sao, trong đó một ngôi sáng hơn cả. Bạn có thể dựa vào chúng để định hướng.',
  core: 'Những Vì Sao nói về sự sáng tỏ, hy vọng và phương hướng. Lá này cho biết con đường đang nhìn thấy được: bạn biết mình đi đâu, và tình hình đang được chiếu mệnh tốt. Nó mang màu tâm linh và trực giác, đồng thời nó nhân lên, vì nhiều ngôi sao nghĩa là nhiều cái của lá đứng cạnh. Điểm yếu của nó nằm ở chỗ các ngôi sao ở rất xa: Những Vì Sao chỉ hướng rất đẹp, nhưng nó không đi thay bạn.',
  love: 'Bạn có một mối quan hệ nhiều hy vọng và được ưu ái. Lá này cũng chỉ một người được bạn lý tưởng hóa, và sự sáng tỏ về điều bạn thật sự muốn.',
  work: 'Bạn có một kế hoạch rõ ràng và một hướng đi tốt. Lá này gắn với công việc sáng tạo, công nghệ và mọi chuyện trên mạng, kèm theo nhiều cơ hội nhỏ.',
  who: 'Người được chỉ tới truyền cảm hứng, thiên về tâm linh và có tầm nhìn. Đó là một người bạn ngưỡng mộ.',
  time: 'Lá này chỉ ban đêm, hoặc một thời điểm có chỉ dẫn rõ ràng. Khoảng thời gian là mười sáu ngày.',
  combo: [['+ Trái Tim', 'Đây là một tình yêu đẹp và nhiều hy vọng. Bạn cũng nhìn rõ cảm xúc của chính mình.'],
          ['+ Mây', 'Bạn mất phương hướng. Hy vọng bị che khuất và kế hoạch mờ đi.'],
          ['+ Chìa Khóa', 'Sự chắc chắn và sự sáng tỏ đến cùng lúc. Câu trả lời là có, và câu trả lời đó rõ ràng.']] },

17: { name: 'Con Cò', card: 'Q Cơ', tone: 'pos',
  kw: { pos: ['thay đổi', 'cải thiện', 'chuyển chỗ', 'một giai đoạn mới', 'sinh nở', 'sự quay lại'],
        neg: ['không yên', 'thay đổi chỉ vì muốn đổi', 'thiếu ổn định'] },
  scene: 'Một con cò chân dài đang trên đường di cư. Nó bay đi, rồi nó quay về.',
  core: 'Con Cò nói về sự thay đổi, và khác với phần lớn các lá thay đổi, đây là thay đổi theo hướng tốt hơn. Lá này bao gồm việc chuyển nhà, đổi việc, một bước ngoặt trong quan hệ, và cả sinh nở theo nghĩa đen. Vì cò di cư, lá này còn mang nghĩa quay lại: một điều gì đó trở về, hoặc một chu kỳ lặp lại. Quan Tài kết thúc, Lưỡi Hái cắt đứt, còn Con Cò chuyển hóa, nghĩa là sự việc không dừng lại mà trở thành một thứ khác.',
  love: 'Mối quan hệ của bạn đổi hình thức, có thể trở thành chính thức, chuyển sang sống chung, hoặc bước sang một giai đoạn mới. Lá này báo một sự cải thiện.',
  work: 'Bạn đổi việc, được thăng chức, chuyển bộ phận hoặc chuyển thành phố. Đây là một thay đổi hoàn cảnh đáng mừng.',
  who: 'Người được chỉ tới đang trong giai đoạn chuyển tiếp. Đó là một người mẹ, một bà đỡ, hoặc một người vừa thay đổi rất nhiều.',
  time: 'Lá này chỉ một mùa chuyển, khoảng mười bảy ngày. Thời điểm cũng có thể rơi vào mùa xuân.',
  combo: [['+ Ngôi Nhà', 'Bạn chuyển nhà. Bạn nên hiểu cặp này theo nghĩa đen.'],
          ['+ Đứa Trẻ', 'Cặp kinh điển này chỉ việc mang thai hoặc sinh con.'],
          ['+ Quan Tài', 'Một thay đổi khép lại điều gì đó, hoặc một kết thúc biến thành sự đổi thay.']] },

18: { name: 'Con Chó', card: '10 Cơ', tone: 'pos', person: true,
  kw: { pos: ['bạn bè', 'trung thành', 'tin cậy', 'thủy chung', 'sự thân quen', 'chỗ dựa'],
        neg: ['phụ thuộc', 'trung thành mù quáng', 'ở lại vì quen', 'chỉ là bạn thôi'] },
  scene: 'Một con chó ngồi đợi tại chỗ. Nó đã có mặt ở đó ngay từ đầu.',
  core: 'Con Chó nói về lòng trung thành và tình bạn. Đây là một trong những lá ấm áp nhất bộ bài, và nó chỉ tới một người đáng tin: một người bạn, một người ở lại, một người đã chứng minh được mình. Đọc theo nghĩa đen, lá này thường chỉ đơn giản là một người bạn, và trong trải bài tình cảm, thông tin đó rất quan trọng. Con Chó thân thiết và bền, nhưng nó không phải lá của tình yêu đôi lứa. Nó là lá của người sẽ vẫn còn ở đó.',
  love: 'Bạn có một người bạn đời chung thủy, hoặc một người yêu quý bạn như một người bạn. Trong một trải bài mập mờ, bạn nên nói thật: Con Chó có thể là sự tận tụy, và cũng có thể là một tình bạn không vượt qua ranh giới.',
  work: 'Bạn có một đồng nghiệp đáng tin, một quan hệ làm việc bền, hoặc một khách hàng lâu năm. Đây là chỗ dựa bạn có thể trông cậy.',
  who: 'Người được chỉ tới là một người bạn, một người yêu chung thủy, hoặc một người ủng hộ bạn. Người này thân quen và an toàn.',
  time: 'Lá này chỉ một nhịp đều đặn và đáng tin. Sự việc sẽ xảy ra vào lúc nó vẫn thường xảy ra.',
  combo: [['+ Trái Tim', 'Đây là một tình bạn đầy thương mến, hoặc một người bạn trở thành nhiều hơn một người bạn.'],
          ['+ Con Rắn', 'Bạn gặp một người bạn giả, và bạn bị phản bội bởi chính người mình tin.'],
          ['+ Chiếc Nhẫn', 'Đây là một cam kết trung thành, trong đó một tình bạn trở thành sự gắn bó lâu dài.']] },

19: { name: 'Tòa Tháp', card: '6 Bích', tone: 'neu',
  kw: { pos: ['thẩm quyền', 'cấu trúc', 'tổ chức', 'tầm nhìn xa', 'ranh giới'],
        neg: ['cô lập', 'cô đơn', 'lạnh lùng', 'thủ tục hành chính', 'bị gạt ra ngoài'] },
  scene: 'Một tòa tháp đá cao đứng một mình. Từ trên đó bạn nhìn được rất xa, và trên đó không có ai khác.',
  core: 'Tòa Tháp là tổ chức và độ cao đơn độc. Nó bao gồm các cơ quan chính thức — nhà nước, tập đoàn, bệnh viện, tòa án — và cách vận hành khô khan, quy củ của chúng. Ở khía cạnh cá nhân, nó là sự cô lập: đứng tách ra, giữ một ranh giới, ở một mình vì chọn hoặc vì hoàn cảnh. Nó mang theo quyền lực, sự bền lâu, và một sự lạnh nhất định.',
  love: 'Khoảng cách cảm xúc, một người luôn dựng tường, hoặc một quan hệ nghi thức hơn là ấm áp. Cũng là sự độc thân, và thường là độc thân mà thấy ổn.',
  work: 'Một tổ chức lớn, thủ tục chính thức, chuyện pháp lý hoặc nhà nước, một vị trí cấp cao. Dài hạn và nhiều giấy tờ.',
  who: 'Người có chức quyền, một cán bộ, một người sống khép. Dè dặt và tự đủ.',
  time: 'Dài và mang tính thể chế. Chậm vì có một bộ máy dính vào.',
  combo: [['+ Trái Tim', 'Tình yêu bị giữ ở khoảng cách, hoặc một trái tim cô đơn.'],
          ['+ Chiếc Nhẫn', 'Một hợp đồng chính thức — đăng ký kết hôn, một thỏa thuận công ty.'],
          ['+ Khu Vườn', 'Riêng tư gặp công khai — công khai một chuyện, hoặc một tổ chức lên báo.']] },

20: { name: 'Khu Vườn', card: '8 Bích', tone: 'neu',
  kw: { pos: ['công chúng', 'một buổi tụ họp', 'cộng đồng', 'kết nối', 'gặp gỡ', 'đời sống xã hội'],
        neg: ['bị phơi bày', 'không còn riêng tư', 'quan hệ hời hợt', 'đám đông'] },
  scene: 'Một khu vườn công cộng có lối đi chạy xuyên qua. Ai cũng có thể bước vào đây.',
  core: 'Khu Vườn là không gian công cộng. Đây là nơi bạn được nhìn thấy: tiệc tùng, tụ họp, kết nối, mạng internet, danh tiếng, và mọi chuyện diễn ra trước mặt người khác. Tự nó không tốt cũng không xấu — nó chỉ nói rằng chuyện này không còn riêng tư. Lá nào đứng cạnh Khu Vườn thì lá đó trở thành chuyện ai cũng biết, hoặc diễn ra giữa đám đông.',
  love: 'Gặp nhau trong một dịp xã giao, một mối quan hệ công khai, hoặc một mối diễn ra trong nhóm bạn chung. Hẹn hò qua mạng.',
  work: 'Networking, một sự kiện, công việc tiếp xúc công chúng, marketing, danh tiếng nghề nghiệp. Một cuộc họp nhiều người.',
  who: 'Người hòa đồng, chính công chúng, một đám đông, một nhóm bạn.',
  time: 'Khi mọi người tụ họp. Mùa hè, hoặc tại sự kiện.',
  combo: [['+ Trái Tim', 'Một mối tình công khai, hoặc gặp được người ấy tại một sự kiện.'],
          ['+ Đôi Chim', 'Người ta đang bàn tán. Tin đồn trong một nhóm.'],
          ['+ Con Cá', 'Kinh doanh giữa đám đông — buôn bán, chợ, thu nhập từ công chúng.']] },

21: { name: 'Ngọn Núi', card: '8 Chuồn', tone: 'neg',
  kw: { pos: ['sức bền', 'một thử thách đáng leo', 'sự bền vững'],
        neg: ['tắc nghẽn', 'trì hoãn', 'chướng ngại', 'khoảng cách', 'một người lạnh lùng'] },
  scene: 'Một dãy núi, tuyết phủ trên đỉnh. Nó sẽ không dịch đi vì bạn.',
  core: 'Ngọn Núi là chướng ngại. Có một thứ rất lớn đang chắn đường và nó sẽ không dễ dịch chuyển — một sự trì hoãn, một tắc nghẽn, một rào chắn cứng giữa bạn và điều bạn muốn. Nó cũng là khoảng cách và sự lạnh lẽo: một người không với tới được, một tình huống đang đóng băng. Ngọn Núi không nói "không bao giờ". Nó nói "không phải đường này, và không phải sớm".',
  love: 'Một mối quan hệ bị chặn, một trở ngại nghiêm trọng giữa hai người, hoặc một người lạnh lùng và không thể với tới. Trì hoãn kéo dài.',
  work: 'Dự án đứng, thăng chức bị chặn, thủ tục kéo dài, một trở ngại nghề nghiệp nghiêm túc.',
  who: 'Người lạnh, xa cách, hoặc cản trở. Một đối thủ, hoặc đơn giản là một người không lay chuyển.',
  time: 'Bị chặn. Trì hoãn không xác định — đừng lên kế hoạch dựa vào nó.',
  combo: [['+ Trái Tim', 'Một mối quan hệ bị chặn, hoặc một trái tim đã nguội.'],
          ['+ Chìa Khóa', 'Chướng ngại được vượt qua — thông tắc. Một cặp rất tốt.'],
          ['+ Cỏ Ba Lá', 'Một cú may vượt qua chướng ngại, dù chỉ là một cú nhỏ.']] },

22: { name: 'Ngã Rẽ', card: 'Q Rô', tone: 'neu',
  kw: { pos: ['lựa chọn', 'các phương án', 'sự tự do', 'một quyết định'],
        neg: ['do dự', 'phân vân', 'quá nhiều lựa chọn', 'không có đường nào rõ'] },
  scene: 'Một con đường tách làm hai, có biển chỉ đường. Cả hai hướng đều có thật.',
  core: 'Ngã Rẽ là sự lựa chọn. Có nhiều hơn một phương án, và kết quả tùy vào việc bạn chọn đường nào. Lá này trung tính thật sự: nó không nói đường nào tốt hơn, chỉ nói rằng quyết định thuộc về bạn. Nó cũng mang nghĩa số nhiều — hai của một thứ gì đó, các phương án thay thế, và đôi khi là một người đang cố giữ cho mình nhiều đường lui.',
  love: 'Một lựa chọn giữa hai người, hoặc một quyết định về việc có tiếp tục hay không. Cũng là một người vẫn chưa chọn — và bản thân điều đó đã là một câu trả lời.',
  work: 'Chọn giữa các lời mời, một quyết định nghề nghiệp, một ngã ba trong dự án. Nhiều hướng đang mở.',
  who: 'Người còn do dự, người đang có nhiều lựa chọn, một người chưa cam kết.',
  time: 'Tùy quyết định của bạn. Thời điểm nằm trong tay bạn.',
  combo: [['+ Trái Tim', 'Một lựa chọn trong tình cảm, hoặc ai đó đang phân vân giữa hai người.'],
          ['+ Quan Tài', 'Quyết định là dừng lại.'],
          ['+ Mây', 'Một lựa chọn đưa ra trong mơ hồ — bạn không nhìn rõ các phương án.']] },

23: { name: 'Đàn Chuột', card: '7 Chuồn', tone: 'neg',
  kw: { pos: ['nhìn ra là dừng được', 'một vấn đề nhỏ, bắt được sớm'],
        neg: ['hao hụt', 'bào mòn', 'căng thẳng', 'mất trộm', 'bị gặm dần'] },
  scene: 'Lũ chuột đang gặm một thứ gì đó. Không nhát nào đáng kể; chỉ có sự tích lũy mới đáng kể.',
  core: 'Đàn Chuột là sự mất mát dần dần. Có thứ gì đó đang bị gặm mòn — tiền, sức lực, sức khỏe, lòng tin, thời gian. Thiệt hại không kịch tính, và chính vì thế nó nguy hiểm: nó xảy ra từng chút một và rất dễ không nhận ra cho tới khi mất đi rất nhiều. Đàn Chuột cũng có nghĩa là căng thẳng và lo âu, và là trộm cắp. Lá nào đứng cạnh chúng thì lá đó đang bị hao đi.',
  love: 'Lòng tin hoặc tình cảm đang cạn dần. Một mối quan hệ bị bào mòn chứ không bị bẻ gãy. Stress đang ăn mòn sự gắn bó.',
  work: 'Tiền rò rỉ, những mất mát nhỏ kéo dài, căng thẳng, kiệt sức, hoặc có thứ đang bị lấy đi. Hãy kiểm tra lại chi tiết.',
  who: 'Người rút cạn năng lượng của bạn. Một người hay lo, hoặc một kẻ ăn cắp vặt.',
  time: 'Đang diễn ra và từ từ. Ngay lúc này, chậm rãi.',
  combo: [['+ Con Cá', 'Tiền đang mất — thất thoát, nợ nần, mất trộm.'],
          ['+ Trái Tim', 'Tình cảm mòn dần, hoặc đau lòng và căng thẳng.'],
          ['+ Cái Cây', 'Sức khỏe bị bào mòn vì stress.']] },

24: { name: 'Trái Tim', card: 'J Cơ', tone: 'pos',
  kw: { pos: ['tình yêu', 'sự trìu mến', 'lãng mạn', 'ấm áp', 'chân thành', 'trái tim'],
        neg: ['ủy mị', 'yêu mà không hành động', 'bị cảm xúc dẫn dắt'] },
  scene: 'Một trái tim đỏ duy nhất, không thể nhầm lẫn. Trên lá không còn gì khác.',
  core: 'Trái Tim là tình yêu — chính cảm xúc ấy, ở dạng rõ nhất của nó. Nó bao gồm lãng mạn, thương mến, ấm áp, tử tế và tình cảm thật lòng. Đây là một trong những lá ít mơ hồ nhất bộ bài: nơi nào Trái Tim xuất hiện, nơi đó có tình cảm thật. Điều nó không nói cho bạn biết là người ta sẽ *làm gì* với tình cảm đó — Trái Tim là cảm xúc, không phải cam kết. Muốn biết về cam kết thì phải nhìn Chiếc Nhẫn.',
  love: 'Tình yêu, đơn giản vậy. Tình cảm thật, sự lãng mạn và chân thành. Trong trải bài mập mờ thì đây là lá bạn muốn thấy.',
  work: 'Công việc bạn yêu, một việc được làm bằng sự tận tâm, quan hệ tốt với đồng nghiệp. Công việc thiện nguyện và chăm sóc.',
  who: 'Một người ấm áp, thương yêu, rộng lượng. Người được yêu.',
  time: 'Sớm và ấm. Mùa hè, hoặc khi cảm xúc đã đúng.',
  combo: [['+ Chiếc Nhẫn', 'Tình yêu và cam kết cùng lúc — cặp quan hệ mạnh nhất bộ bài.'],
          ['+ Mây', 'Cảm xúc rối, tình yêu không rõ ràng, tín hiệu lẫn lộn.'],
          ['+ Ngọn Núi', 'Tình yêu bị chặn — tình cảm có thật nhưng không đi qua được.']] },

25: { name: 'Chiếc Nhẫn', card: 'A Chuồn', tone: 'pos',
  kw: { pos: ['cam kết', 'hợp đồng', 'hôn nhân', 'sự gắn bó', 'một lời hứa', 'một chu kỳ'],
        neg: ['một ràng buộc khó thoát', 'vòng lặp', 'nghĩa vụ không có tình yêu'] },
  scene: 'Một chiếc nhẫn vàng — một vòng tròn khép kín. Nó không có điểm kết, và đó chính là ý.',
  core: 'Chiếc Nhẫn là sự cam kết và cái thỏa thuận giữ lấy cam kết đó: hôn nhân, hợp đồng, sự gắn bó, một lời hứa đã trao. Vì nhẫn là một vòng tròn khép kín, nó cũng có nghĩa là chu kỳ — một điều gì đó quay lại, một khuôn mẫu lặp lại, một sự dàn xếp đang tiếp diễn. Nó nói rằng có một ràng buộc tồn tại. Còn ràng buộc đó có tình yêu hay không lại là câu hỏi khác, và Trái Tim mới là lá trả lời.',
  love: 'Cam kết, một mối quan hệ nghiêm túc, đính hôn, kết hôn. Hoặc một mối quan hệ cứ quay vòng lại mãi.',
  work: 'Một hợp đồng, một quan hệ đối tác, một thỏa thuận ràng buộc, một sự sắp xếp đang chạy. Hãy đọc kỹ điều khoản.',
  who: 'Bạn đời, vợ hoặc chồng, đối tác kinh doanh. Người bị ràng buộc với bạn bằng một thỏa thuận.',
  time: 'Một chu kỳ trọn vẹn — khoảng một năm, hoặc khi hợp đồng tới hạn.',
  combo: [['+ Trái Tim', 'Một mối quan hệ vừa cam kết vừa có tình yêu. Đính hôn hoặc kết hôn.'],
          ['+ Lưỡi Hái', 'Hợp đồng bị hủy, đính hôn tan, một cam kết bị cắt.'],
          ['+ Con Rắn', 'Một cam kết phức tạp — cái bẫy trong hợp đồng, hoặc ngoại tình trong hôn nhân.']] },

26: { name: 'Cuốn Sách', card: '10 Rô', tone: 'neu',
  kw: { pos: ['kiến thức', 'học hành', 'chuyên môn', 'nghiên cứu'],
        neg: ['một bí mật', 'điều bị giấu', 'thông tin bạn chưa có'] },
  scene: 'Một cuốn sách đóng, có khóa. Mọi thứ nó biết đều nằm ở bên trong.',
  core: 'Cuốn Sách có hai mặt mà thực ra là một: kiến thức, và kiến thức bị giữ lại. Đóng lại, nó là một bí mật — điều bạn chưa được kể, thông tin bị cố ý giấu, một khía cạnh khuất của tình huống. Mở ra, nó là học hành, giáo dục, chuyên môn và nghiên cứu. Trong trải bài, rất thường nó chỉ đơn giản nói: bạn chưa có đủ bức tranh.',
  love: 'Một bí mật trong mối quan hệ, hoặc điều bạn chưa được kể. Cũng là một người không dễ mở lòng.',
  work: 'Học hành, đào tạo, bằng cấp, nghiên cứu, hoặc chuyên môn sâu. Cũng là thông tin mật ở nơi làm việc.',
  who: 'Người kín đáo, có học, hay giữ bí mật. Một giáo viên, một sinh viên, một nhà nghiên cứu.',
  time: 'Chưa biết — thời điểm chưa được hé lộ. Hãy hỏi lại khi biết thêm.',
  combo: [['+ Trái Tim', 'Một tình yêu thầm kín, hoặc tình cảm giấu trong lòng.'],
          ['+ Chìa Khóa', 'Bí mật lộ ra. Điều bị giấu được hé mở.'],
          ['+ Con Cáo', 'Có điều gì đó đang bị cố ý giấu khỏi bạn.']] },

27: { name: 'Lá Thư', card: '7 Bích', tone: 'neu',
  kw: { pos: ['một tin nhắn', 'một văn bản', 'tin bằng chữ', 'liên lạc', 'một bản ghi'],
        neg: ['tin xấu bằng văn bản', 'giấy tờ', 'chỉ nói trên giấy'] },
  scene: 'Một lá thư đã dán kín. Có người đã cố ý viết điều này ra.',
  core: 'Lá Thư là liên lạc bằng chữ viết: một tin nhắn, một email, một văn bản, một chứng chỉ, giấy tờ. Nếu Kỵ Mã mang tin đến, thì Lá Thư chính là cái tin đó, ở dạng bạn giữ lại được. Nó trung tính — lá bên cạnh sẽ cho biết tin này có đáng mừng không. Ẩn ý lặng lẽ của nó là điều này *được ghi lại*: có thứ đang được viết ra chứ không chỉ nói miệng.',
  love: 'Một tin nhắn từ người ấy, một dòng chữ, một lá thư. Chữ trên màn hình chứ không phải một cuộc nói chuyện trực tiếp.',
  work: 'Một hợp đồng, một báo cáo, một hồ sơ ứng tuyển, thư mời làm việc, giấy tờ. Mọi thứ chính thức trên văn bản.',
  who: 'Một người viết lách, một người làm hành chính, hoặc đơn giản là người thích nhắn hơn gọi.',
  time: 'Khi tin nhắn đến — vài ngày.',
  combo: [['+ Trái Tim', 'Một lá thư tình, một tin nhắn về tình cảm, một lời tỏ bằng chữ.'],
          ['+ Quan Tài', 'Tin xấu bằng văn bản — thư nghỉ việc, một kết thúc chính thức.'],
          ['+ Chiếc Nhẫn', 'Một hợp đồng, một giấy tờ chính thức, thủ tục kết hôn.']] },

28: { name: 'Người Đàn Ông', card: 'A Cơ', tone: 'neu', person: true,
  kw: { pos: ['người đàn ông được hỏi', 'người hỏi bài là nam', 'bạn đời', 'anh ấy'] },
  scene: 'Một người đàn ông đứng nhìn thẳng. Anh ta là chủ thể, không phải một biểu tượng.',
  core: 'Người Đàn Ông là một con người, không phải một tính chất. Nếu người hỏi là nam thì lá này chính là họ; nếu câu hỏi về một người đàn ông thì lá này là người đàn ông đó. Anh ta là điểm neo của trải bài — các lá gần anh ta mô tả anh ta, hướng anh ta quay về cho biết anh ta đang hướng tới điều gì, và những gì ở phía sau là quá khứ của anh ta. Đừng luận Người Đàn Ông như một ý nghĩa. Hãy tìm anh ta, rồi đọc những gì vây quanh.',
  love: 'Anh ấy — người đàn ông bạn đang hỏi, hoặc bạn đời nam của bạn. Các lá cạnh anh ta chính là tâm trạng của anh ta.',
  work: 'Một đồng nghiệp, sếp hoặc khách hàng nam. Người đàn ông trong tình huống công việc.',
  who: 'Một người đàn ông, thường là đã trưởng thành. Trong trải bài đồng giới, là người mà người luận đã gán cho lá này từ đầu.',
  time: 'Khi nào anh ta hành động. Nhịp của anh ta, không phải của bạn.',
  combo: [['Đàn Ông + Trái Tim', 'Anh ấy đang yêu, hoặc đang có tình cảm.'],
          ['Đàn Ông + Mây', 'Anh ấy đang rối, hoặc đang giấu tâm trạng của mình.'],
          ['Đàn Ông + Phụ Nữ', 'Hai người họ ở cùng nhau — khoảng cách giữa hai lá cho biết họ thật sự gần nhau đến đâu.']] },

29: { name: 'Người Phụ Nữ', card: 'A Bích', tone: 'neu', person: true,
  kw: { pos: ['người phụ nữ được hỏi', 'người hỏi bài là nữ', 'bạn đời', 'cô ấy'] },
  scene: 'Một người phụ nữ đứng nhìn thẳng. Cô ấy là chủ thể, không phải một biểu tượng.',
  core: 'Người Phụ Nữ là một con người, không phải một tính chất. Nếu người hỏi là nữ thì lá này chính là họ; nếu câu hỏi về một người phụ nữ thì lá này là người phụ nữ đó. Cô ấy neo trải bài đúng theo cách Người Đàn Ông neo — hãy đọc các lá quanh cô ấy như hoàn cảnh, cảm xúc và những gì cô ấy đang đối diện. Khoảng cách giữa lá Đàn Ông và lá Phụ Nữ trên bàn tự nó đã là một thông tin.',
  love: 'Cô ấy — người phụ nữ bạn đang hỏi, hoặc bạn đời nữ của bạn. Các lá cạnh cô ấy mô tả vị thế của cô ấy.',
  work: 'Một đồng nghiệp, sếp hoặc khách hàng nữ. Người phụ nữ trong tình huống công việc.',
  who: 'Một người phụ nữ, thường là đã trưởng thành. Trong trải bài đồng giới, là người mà người luận đã gán cho lá này từ đầu.',
  time: 'Khi nào cô ấy hành động. Nhịp của cô ấy, không phải của bạn.',
  combo: [['Phụ Nữ + Trái Tim', 'Cô ấy đang yêu, hoặc đang có tình cảm.'],
          ['Phụ Nữ + Con Rắn', 'Có tình địch ở gần cô ấy, hoặc chính cô ấy là rắc rối.'],
          ['Phụ Nữ + Ngọn Núi', 'Cô ấy đang bị chặn, xa cách, hoặc không với tới được.']] },

30: { name: 'Hoa Loa Kèn', card: 'K Bích', tone: 'pos', person: true,
  kw: { pos: ['sự chín chắn', 'bình an', 'khôn ngoan', 'từng trải', 'hài hòa', 'một người đàn ông lớn tuổi'],
        neg: ['lạnh nhạt', 'chênh lệch tuổi tác', 'chuyện chăn gối', 'đã qua mùa'] },
  scene: 'Một bông loa kèn trắng nở hết. Đây không phải một bông hoa còn non.',
  core: 'Hoa Loa Kèn là sự chín chắn — bình an, khôn ngoan, và sự điềm tĩnh có được từ việc đã sống đủ lâu. Nó chỉ tới người lớn tuổi, những tình huống đã ổn định từ lâu, và những chuyện được xử lý một cách đàng hoàng. Theo truyền thống nó còn mang hai nghĩa nghe có vẻ chỏi nhau nhưng đều thuộc về nó: đây là lá của sự thanh sạch và đức hạnh, và đây cũng là lá của tình dục trong bộ bài. Hãy luận theo nghĩa nào mà lá bên cạnh chống đỡ.',
  love: 'Một mối quan hệ chín chắn và bình yên, hoặc một người bạn đời lớn tuổi hơn. Chênh lệch tuổi. Cũng có nghĩa cụ thể là sự thân mật thể xác.',
  work: 'Chuyên môn lâu năm, kinh nghiệm dày, một vị trí được nể trọng, hưu trí. Công việc được xử lý điềm tĩnh và tử tế.',
  who: 'Một người đàn ông lớn tuổi, một người thầy, một hình bóng người cha, một người có vị thế. Điềm đạm và từng trải.',
  time: 'Chậm và chín. Mùa đông, hoặc giai đoạn về sau của một việc.',
  combo: [['+ Trái Tim', 'Một tình yêu chín chắn và bình an — hoặc sự thân mật thể xác.'],
          ['+ Người Đàn Ông', 'Cụ thể là một người đàn ông lớn tuổi.'],
          ['+ Ngọn Núi', 'Sự lạnh nhạt và xa cách trong một tình huống đã chín.']] },

31: { name: 'Mặt Trời', card: 'A Rô', tone: 'pos',
  kw: { pos: ['thành công', 'năng lượng', 'chiến thắng', 'ấm áp', 'sáng tỏ', 'một ngày đẹp'],
        neg: ['cháy sạch', 'kiêu ngạo', 'tốt quá hóa thừa'] },
  scene: 'Mặt trời ở độ sáng mạnh nhất, tia nắng chạm tới rìa lá bài.',
  core: 'Mặt Trời là thành công và sinh lực — lá tích cực nhất bộ bài. Nó nghĩa là mọi chuyện suôn sẻ: năng lượng, hơi ấm, chiến thắng, sự công nhận, và niềm vui thật. Nó còn làm mạnh lên bất cứ lá nào đứng cạnh, biến một lá khó thành dễ thở hơn và một lá tốt thành xuất sắc. Với câu hỏi có/không thì đây là một chữ "có" không thể rõ hơn.',
  love: 'Một mối quan hệ vui và ấm. Niềm vui, và một kết quả rất tốt. Nếu bạn hỏi liệu có suôn sẻ không, thì có.',
  work: 'Thành công, được ghi nhận, một chiến thắng, năng lượng cho công việc. Một dự án chạy tốt và được nhìn thấy là chạy tốt.',
  who: 'Một người ấm áp, tự tin, thành đạt. Người có mặt là căn phòng sáng lên.',
  time: 'Ban ngày, mùa hè, và sớm. Nhanh và rực.',
  combo: [['+ Trái Tim', 'Hạnh phúc lớn trong tình cảm. Một trong những cặp đẹp nhất bộ bài.'],
          ['+ Con Cá', 'Thành công tài chính — tiền và sự suôn sẻ cùng lúc.'],
          ['+ Mây', 'Mặt trời sau mây: thành công bị trì hoãn hoặc bị che, nhưng vẫn còn đó.']] },

32: { name: 'Mặt Trăng', card: '8 Cơ', tone: 'pos',
  kw: { pos: ['cảm xúc', 'được công nhận', 'danh tiếng', 'trực giác', 'lãng mạn', 'một tháng'],
        neg: ['thất thường', 'ảo tưởng', 'sống bằng cảm xúc', 'thèm được chú ý'] },
  scene: 'Một vầng trăng khuyết trên trời tối. Nó có phát sáng, nhưng không nhiều, và mỗi đêm lại đổi hình.',
  core: 'Mặt Trăng là đời sống cảm xúc và danh tiếng — hai nghĩa nối với nhau bởi ý niệm phản chiếu. Hướng vào trong, nó là cảm xúc, trực giác, giấc mơ và sự lãng mạn; hướng ra ngoài, nó là danh dự, sự công nhận, tiếng tăm, và cách bạn được nhìn nhận. Nó cũng là lá chỉ thời điểm rõ nhất bộ bài: một vầng trăng là một tháng. Nó ấm hơn và ít u ám hơn nhiều so với lá Mặt Trăng trong tarot.',
  love: 'Cảm xúc lãng mạn sâu, sự kết nối tâm hồn, một mối dây nhiều tình. Cũng là những lên xuống thất thường của cảm xúc.',
  work: 'Được công nhận, danh tiếng, công việc sáng tạo và nghệ thuật, làm ca đêm. Được vinh danh vì một điều gì đó.',
  who: 'Người giàu cảm xúc, nhiều trực giác, chất nghệ. Một người nổi tiếng, hoặc một người muốn được biết đến.',
  time: 'Một tháng. Hoặc vào ban đêm.',
  combo: [['+ Trái Tim', 'Tình yêu lãng mạn sâu đậm — cảm xúc và tình cảm cùng lúc.'],
          ['+ Mặt Trời', 'Được công nhận và thành công. Được nhìn thấy, và mọi thứ suôn sẻ.'],
          ['+ Mây', 'Rối loạn cảm xúc, hoặc danh tiếng bị phủ bóng.']] },

33: { name: 'Chìa Khóa', card: '8 Rô', tone: 'pos',
  kw: { pos: ['sự chắc chắn', 'khẳng định', 'lời giải', 'mở ra', 'câu trả lời', 'thành công'] },
  scene: 'Một chiếc chìa khóa. Nó không phải biểu tượng của cánh cửa; nó là thứ mở cánh cửa ra.',
  core: 'Chìa Khóa là sự chắc chắn. Nó nghĩa là có, nghĩa là cửa mở, nghĩa là đã tìm ra lời giải. Cuốn Sách đóng lại thứ gì thì Chìa Khóa mở thứ đó ra. Trong câu hỏi có/không, đây là chữ "có" mạnh nhất bộ bài, và đứng cạnh bất cứ lá tắc nghẽn nào thì nó nghĩa là chỗ tắc được thông. Thông điệp của nó là: chuyện này đã ngã ngũ, đã được giải, hoặc sắp được giải.',
  love: 'Một chữ "có" dứt khoát. Mối quan hệ mở ra, câu trả lời rõ ràng, cánh cửa không hề khóa.',
  work: 'Lời giải cho vấn đề, một cánh cửa mở ra, một kết quả dứt khoát. Thứ đó chạy được.',
  who: 'Một người chắc chắn và thẳng thắn, hoặc chính là người đang giữ câu trả lời.',
  time: 'Bây giờ, và chắc chắn. Khi cánh cửa mở ra.',
  combo: [['+ Trái Tim', 'Chắc chắn trong tình cảm — câu trả lời về tình cảm là có.'],
          ['+ Ngọn Núi', 'Chướng ngại được thông. Một cặp rất tốt.'],
          ['+ Cuốn Sách', 'Bí mật được hé lộ.']] },

34: { name: 'Con Cá', card: 'K Rô', tone: 'pos',
  kw: { pos: ['tiền bạc', 'kinh doanh', 'dồi dào', 'dòng chảy', 'thu nhập', 'tự chủ'],
        neg: ['quá đà', 'tiền trôi đi', 'quá nhiều thứ gì đó'] },
  scene: 'Một con cá trong làn nước sâu, những đồng tiền đang lắng xuống đáy. Cả nước lẫn tiền đều đang chuyển động.',
  core: 'Con Cá là tiền bạc và dòng chảy. Nó bao gồm thu nhập, kinh doanh, buôn bán, của cải và làm chủ, và mang cảm giác của một thứ đang chảy và đang nhiều — cá thì đi thành đàn. Ngoài tài chính, nó có nghĩa là sự dồi dào nói chung: rất nhiều cái của lá đứng cạnh. Trong câu hỏi làm ăn, đây là lá thuận lợi trực tiếp nhất bộ bài.',
  love: 'Một người bạn đời rộng rãi, một mối quan hệ đủ đầy về vật chất, hoặc một mối dây trôi chảy dễ dàng. Đôi khi là: một quan hệ mà tiền bạc là một yếu tố.',
  work: 'Thu nhập, kinh doanh, làm tự do, bán hàng, đầu tư, dòng tiền. Thuận về mặt tài chính.',
  who: 'Một người làm kinh doanh, một người tự chủ tài chính, một người hào phóng. Một thương nhân.',
  time: 'Chảy và liên tục. Khi tiền về — ngày lương, cuối tháng.',
  combo: [['+ Con Gấu', 'Một khoản tiền lớn.'],
          ['+ Đàn Chuột', 'Tiền đang trôi đi — thua lỗ, nợ, rò rỉ.'],
          ['+ Mỏ Neo', 'Thu nhập ổn định và đáng tin. An toàn tài chính.']] },

35: { name: 'Mỏ Neo', card: '9 Bích', tone: 'pos',
  kw: { pos: ['ổn định', 'kiên trì', 'an toàn', 'công việc', 'bám trụ', 'ở lại lâu'],
        neg: ['mắc kẹt', 'bị níu lại', 'giữ quá lâu', 'không lay chuyển'] },
  scene: 'Một mỏ neo nằm dưới đáy biển, dây xích căng. Nó đang làm đúng việc của nó, là giữ cho mọi thứ đứng yên.',
  core: 'Mỏ Neo là sự ổn định và sức bền. Nó nghĩa là có thứ gì đó trụ được: một công việc lâu dài, một mối quan hệ bền, một tình huống sẽ không đổi. Nó cũng là lá của công việc theo nghĩa *nghề nghiệp nuôi sống bạn*, và của sự kiên trì — bám tới khi nào được thì thôi. Mặt tối của nó chính là phẩm chất ấy nhìn từ phía khác: sự mắc kẹt, và việc giữ chặt một thứ rất lâu sau khi lẽ ra nên buông.',
  love: 'Một mối quan hệ kéo dài, một người ở lại. An toàn hơn là hồi hộp. Hoặc một mối dây bạn đang giữ quá hạn của nó.',
  work: 'Một công việc ổn định, sự gắn bó lâu dài, một vị trí vững. Việc mà sang năm vẫn còn đó.',
  who: 'Một người vững vàng, đáng tin, không lay chuyển. Người không bỏ đi.',
  time: 'Lâu dài và bền. Sau này nó vẫn còn đúng.',
  combo: [['+ Trái Tim', 'Tình yêu bền lâu, một mối quan hệ trụ được.'],
          ['+ Con Cá', 'Thu nhập vững, một vị thế tài chính ổn định.'],
          ['+ Quan Tài', 'Một tình huống kéo dài từ lâu cuối cùng cũng kết thúc.']] },

36: { name: 'Cây Thánh Giá', card: '6 Chuồn', tone: 'neg',
  kw: { pos: ['đức tin', 'ý nghĩa', 'gánh nặng sắp qua', 'kết thúc một thử thách'],
        neg: ['khổ sở', 'gánh nặng', 'số phận', 'mặc cảm tội lỗi', 'điều phải chịu đựng'] },
  scene: 'Một cây thánh giá gỗ cắm xuống đất. Nó nặng, và nó sinh ra để được vác.',
  core: 'Cây Thánh Giá là gánh nặng và số phận. Nó đánh dấu phần khó: sự khổ, nghĩa vụ, mặc cảm, và một khó khăn phải đi xuyên qua chứ không đi vòng được. Nó cũng mang sức nặng tâm linh thật sự — niềm tin, ý nghĩa, và định mệnh. Là lá cuối cùng của bộ bài, nó thường báo hiệu một thử thách đang kết thúc, nên rất đáng đọc kỹ lá đến sau nó. Cây Thánh Giá nặng, nhưng nó có hồi kết.',
  love: 'Một mối quan hệ đau đớn hoặc nặng gánh. Khổ vì yêu, mặc cảm, hoặc một mối dây có màu duyên nợ và nhọc nhằn.',
  work: 'Khối lượng công việc quá nặng, một nghĩa vụ không đặt xuống được, một giai đoạn khó ở chỗ làm.',
  who: 'Một người đang gánh nặng hoặc đang khổ. Một người mộ đạo, hoặc một người vác thay cho người khác.',
  time: 'Một giai đoạn thử thách đang khép lại. Kết thúc một chu kỳ.',
  combo: [['+ Trái Tim', 'Khổ vì tình. Một sự gắn bó đau đớn.'],
          ['+ Mặt Trời', 'Gánh nặng được cất — giai đoạn khó kết thúc tốt đẹp.'],
          ['+ Quan Tài', 'Kết thúc một chương nặng nề. Nỗi đau, và hồi kết của nó.']] }

});
