/* ==================== Lenormand card text — Vietnamese ==================== */
/* Nghĩa các lá theo dòng Petit Lenormand phổ thông. Đây là một hệ thống khác
   tarot, có ngữ pháp riêng, và được để tách hẳn khỏi phần tarot của trang này:
   không có nội dung nào ở đây lấy từ bài giảng tarot của Thu Anh, và khi luận
   thì không nên trộn hai hệ vào nhau. */

Object.assign(LEN.vi, {

1: { name: 'Kỵ Mã', card: '9 Cơ', tone: 'neu', person: true,
  kw: { pos: ['tin tức', 'sự đến gần', 'chuyển động', 'khách ghé thăm', 'người chủ động', 'thể thao'],
        neg: ['bồn chồn', 'tin làm xáo trộn', 'người đến rồi đi, không ở lại'] },
  scene: 'Hình vẽ cho thấy một kỵ sĩ thúc ngựa băng qua mặt lá. Anh ta có một nơi cần tới, và món đồ anh ta cầm theo vốn không thuộc về anh ta.',
  core: 'Ý nghĩa trung tâm của lá này là tin tức, cùng với mọi thứ từ bên ngoài đang tiến vào hoàn cảnh của bạn. Một tin nhắn, một con người, một cơ hội hoặc một mẩu thông tin đang trên đường tới chỗ bạn. Tốc độ là điểm nổi bật của nó, vì trong cả bộ bài rất ít lá chạy nhanh hơn Kỵ Mã. Khi đứng riêng, lá này báo một tin trung tính và hơi nghiêng về phía tốt. Nội dung cụ thể của tin đó nằm ở lá bên cạnh.',
  love: 'Một tin nhắn tới tay bạn, một người chủ động bước tới trước, hoặc một chàng trai trẻ xuất hiện trong câu chuyện của bạn. Việc liên lạc chắc chắn sẽ diễn ra. Bạn nên nhớ rằng lá này chỉ đưa tin, và nó không hứa hẹn bất kỳ sự cam kết nào.',
  work: 'Một lời mời, một buổi phỏng vấn, một đơn hàng hoặc một người giao hàng đều nằm trong phạm vi của lá này, cùng với mọi nghề gắn với bán hàng và thể thao. Ngoài ra, nó báo rằng một việc lâu nay đứng im đã bắt đầu chuyển động.',
  who: 'Hãy hình dung một người giao hàng, một người đưa tin, một vận động viên hoặc một chàng trai còn rất trẻ. Đời bạn chỉ được người này đi ngang qua, vì sức trẻ và sự nhanh nhẹn không cho phép họ dừng lại lâu.',
  time: 'Nhịp thời gian ở đây rất gấp. Sự việc thường xảy ra trong vòng một đến ba ngày, và đôi khi nó xảy ra ngay trong hôm đó.',
  combo: [['+ Trái Tim', 'Có người sắp ngỏ lời với bạn, bằng một tin nhắn tình cảm hoặc một lần thổ lộ trực tiếp.'],
          ['+ Lá Thư', 'Một giấy tờ chính thức, một tin nhắn hay một email sẽ là hình thức mà tin tức mượn để tới với bạn.'],
          ['+ Quan Tài', 'Bạn sắp nhận một tin không vui, hoặc một thông báo cho biết một việc đã chấm dứt.']] },

2: { name: 'Cỏ Ba Lá', card: '6 Rô', tone: 'pos',
  kw: { pos: ['may mắn nhỏ', 'một cơ hội chớp nhoáng', 'sự nhẹ nhõm', 'một khe cửa hé ra'],
        neg: ['không kéo dài', 'cờ bạc, ăn may', 'điều không lặp lại được'] },
  scene: 'Sát mặt đất có một nhánh cỏ ba lá đang mọc. Kích thước của nó quá nhỏ, cho nên bạn chỉ thấy nó khi bạn chịu cúi người xuống.',
  core: 'May mắn là thông điệp của lá này, song đó là loại may mắn nhỏ và trôi qua nhanh. Một khe cửa hé mở trong chốc lát rồi khép lại. Câu trả lời ở đây là "có", nhưng lời hứa của nó chỉ khiêm tốn và tạm thời, và nó không xoay chuyển cả cuộc đời bạn. Công dụng đáng quý nhất của Cỏ Ba Lá nằm ở chỗ nó làm dịu lá đứng kề bên, bởi vì một lá nặng nề đặt cạnh nó cũng bớt ngột ngạt.',
  love: 'Một khoảnh khắc dễ chịu, một câu tán tỉnh nhẹ nhàng hoặc một chút may mắn nhỏ trong tình cảm sẽ đến với bạn. Lá này không nói về một mối quan hệ bền lâu, cho nên bạn hãy đón nhận nó đúng với bản chất của nó.',
  work: 'Một cơ hội nhỏ, một thắng lợi vừa tầm hoặc một rắc rối tự nó được gỡ sẽ xuất hiện. Bạn hãy hành động ngay lập tức, bởi vì cơ hội này không đứng đợi bạn.',
  who: 'Nhân vật ở đây sống vô tư, thường gặp may và không đặt nặng sự nghiêm túc. Bạn cảm thấy thoải mái khi ở bên người này, tuy nhiên bạn khó cùng họ dựng nên một điều gì lâu dài.',
  time: 'Vài giờ cho tới vài ngày là tất cả những gì lá này cho bạn. Thời điểm thích hợp mà bạn vẫn chờ đợi chính là hiện tại.',
  combo: [['+ Con Cá', 'Bạn bất ngờ nhận được một món tiền nhỏ.'],
          ['+ Mây', 'Cơ hội có ghé qua, chỉ tiếc là mắt bạn không bắt được nó. Phần may mắn đó vì vậy đã trôi mất.'],
          ['+ Chiếc Nhẫn', 'May mắn đi kèm một lời cam kết, hoặc một thỏa thuận chỉ có giá trị trong thời gian ngắn.']] },

3: { name: 'Con Thuyền', card: '10 Bích', tone: 'pos',
  kw: { pos: ['đi xa', 'du lịch', 'thương mại', 'chuyện nước ngoài', 'sự tiến triển'],
        neg: ['nhớ nhung', 'người ở xa', 'sự rời đi', 'khoảng cách cảm xúc'] },
  scene: 'Giữa vùng nước rộng, một con thuyền đang no gió. Bến xuất phát của nó mỗi lúc một lùi xa.',
  core: 'Khoảng cách và sự rời đi là hai ý chính của lá này. Nó bao gồm chuyện đi lại theo nghĩa đen, chuyện nước ngoài và hoạt động xuất nhập khẩu, đồng thời bao gồm phiên bản cảm xúc của những điều đó, tức là một người hay một việc đang ở rất xa và bạn mang theo nỗi nhớ. Vì con thuyền không bao giờ đứng yên, lá này cho biết tình hình vẫn tiến về phía trước. Tuy nhiên nó tiến chậm, và hướng đi của nó là rời xa vị trí hiện tại của bạn.',
  love: 'Có thể bạn đang yêu xa, đang gắn bó với một người sống ở vùng đất khác, hoặc đang ở bên một người mà tâm trí họ đặt tại nơi nào đó khác. Một mối quan hệ nảy sinh trong lúc đi xa cũng thuộc về lá này.',
  work: 'Một hướng nghề nghiệp đưa bạn sang vùng đất khác, các chuyến công tác, công việc mang tính quốc tế và hoạt động xuất nhập khẩu đều nằm trong lá này. Đích đến vẫn nằm phía trước, chỉ là bạn cần thêm thời gian mới chạm tới.',
  who: 'Nhân vật ở đây là một người nước ngoài, một người thường xuyên di chuyển, một người sống ở xa hoặc một nhà buôn. Đó cũng có thể là người lúc nào cũng trong tư thế sắp rời khỏi đời bạn.',
  time: 'Từ vài tuần cho tới vài tháng là quãng mà bạn cần chuẩn bị tinh thần, vì nhịp ở đây rất chậm. Mốc thời gian đôi khi trùng luôn với chuyến đi.',
  combo: [['+ Trái Tim', 'Chuyện tình của bạn cách trở về địa lý, hoặc nó bắt đầu ngay trong một chuyến đi.'],
          ['+ Ngôi Nhà', 'Bạn dọn sang một nơi ở mới, đổi chỗ cư trú, hoặc có nhà tại nước ngoài.'],
          ['+ Quan Tài', 'Chuyến đi khép lại tại đây, hoặc lần ra đi này đóng sập một điều gì đó mãi mãi.']] },

4: { name: 'Ngôi Nhà', card: 'K Cơ', tone: 'pos',
  kw: { pos: ['mái ấm', 'gia đình', 'sự an toàn', 'ổn định', 'nhà cửa', 'truyền thống'],
        neg: ['mắc kẹt trong cái quen thuộc', 'áp lực gia đình', 'quá bảo thủ'] },
  scene: 'Một nếp nhà chắc chắn hiện ra, cửa đã khép và ánh đèn hắt qua ô cửa sổ. Ngôi nhà không hề dịch chuyển khỏi chỗ của nó.',
  core: 'Nền móng của bạn là điều lá này nói tới, gồm căn nhà có thật, những người thân trong gia đình, và cảm giác an toàn sinh ra từ cả hai. Ít lá nào trong bộ bài vững như nó, và nó giữ chân bất cứ lá nào nằm kề bên. Con Thuyền hướng ra xa, còn Ngôi Nhà chọn ở lại. Phần lớn trường hợp, lá này nói về chuyện gia đình và đời sống riêng tư, chứ không nói về chuyện ngoài xã hội.',
  love: 'Mối quan hệ ở đây mang cảm giác "về nhà", với việc hai người dọn về ở chung, ra mắt gia đình và cùng dựng nên một chỗ trú cho cả hai. Sự an toàn được đặt cao hơn cảm giác hồi hộp.',
  work: 'Công việc tại nhà, việc kinh doanh của gia đình, lĩnh vực bất động sản, hoặc một chỗ làm bạn chọn vì sự yên ổn chứ không vì tham vọng, tất cả đều thuộc lá này.',
  who: 'Nhân vật ở đây là một người trong nhà, một hình bóng người cha, một người chủ nhà, hoặc một người sống theo nếp cũ và đáng tin cậy.',
  time: 'Bốn tuần là con số gắn với lá này, và nhịp của nó vững vàng, không hối hả. Mốc đó đôi khi rơi vào lúc bạn có mặt ở nhà.',
  combo: [['+ Chiếc Nhẫn', 'Cặp này chỉ một đám cưới, một lần dọn về chung sống, hoặc một hợp đồng mua bán nhà đất.'],
          ['+ Đàn Chuột', 'Tổ ấm đang hao mòn từng ngày. Tài sản của bạn thất thoát, không khí trong nhà căng thẳng, hoặc chính gia đình đang hút cạn sức lực của bạn.'],
          ['+ Con Cá', 'Tiền bạc của gia đình, nguồn thu từ nhà đất và sự vững vàng về tài chính là nội dung của cặp này.']] },

5: { name: 'Cái Cây', card: '7 Cơ', tone: 'neu',
  kw: { pos: ['sức khỏe', 'sự lớn lên', 'gốc rễ', 'chiều sâu', 'sinh lực', 'sự gắn kết'],
        neg: ['chậm chạp', 'bệnh tật', 'trì trệ', 'chuyện đã kéo dài từ lâu'] },
  scene: 'Một thân cây lớn đứng lẻ loi, tán lá rậm rạp. Bộ rễ của nó nằm khuất và bạn không nhìn thấy được.',
  core: 'Sức khỏe là địa hạt của lá này, cùng với sự trưởng thành diễn ra sâu và chậm. Bất cứ điều gì thuộc về Cái Cây đều đòi hỏi thời gian, vì nó không làm việc gì một cách vội vã. Nó nói tới những thứ có gốc rễ, ví dụ bệnh mãn tính, mối dây gắn bó sâu đậm, huyết thống và chính cơ thể bạn. Khi xuất hiện trong trải bài, lá này xác nhận rằng chuyện đang hỏi là thật và có chiều sâu, đồng thời báo trước rằng chuyện đó chưa thể xong trong thời gian ngắn.',
  love: 'Mối dây ở đây sâu và lớn lên từ từ, đôi khi mang màu duyên nợ hoặc gần gũi như người ruột thịt. Đây không phải thứ tình cảm bùng lên rồi tắt, đây là thứ tình cảm bám rễ.',
  work: 'Con đường nghề nghiệp của bạn chậm mà chắc. Lá này gắn với ngành y tế và các công việc chăm sóc, cũng như với một nghề mà mười năm sau bạn vẫn còn theo.',
  who: 'Hãy nghĩ tới một người bà con trong họ, một thầy thuốc hoặc người làm nghề chữa lành, hoặc một người sống chậm rãi với gốc rễ rất chắc.',
  time: 'Nhịp thời gian ở đây rất chậm, kéo dài từ vài tháng cho tới vài năm. Thông điệp của Cái Cây là thời điểm này chưa phải lúc.',
  combo: [['+ Quan Tài', 'Bệnh tật, hoặc một tình trạng đang đi tới hồi kết, là điều cặp này muốn nói. Đây là lời cảnh báo sức khỏe quen thuộc nhất.'],
          ['+ Mặt Trời', 'Cơ thể bạn khỏe mạnh, năng lượng đầy, và vết thương nào cũng lành nhanh.'],
          ['+ Ngọn Núi', 'Chỗ tắc này đã nằm đó từ rất lâu. Việc chữa lành nhích từng chút một, và sự trì hoãn còn kéo dài.']] },

6: { name: 'Mây', card: 'K Chuồn', tone: 'neg',
  kw: { pos: ['rồi sẽ qua', 'trời đang hửng', 'một màn sương tạm thời'],
        neg: ['mơ hồ', 'hoang mang', 'thiếu rõ ràng', 'rắc rối', 'điều bị che khuất'] },
  scene: 'Trên mặt lá có hai khối mây, một khối sẫm màu và một khối sáng. Lối đọc truyền thống cho rằng khối sẫm chỉ ra nơi rắc rối đang ẩn.',
  core: 'Sự mơ hồ, nỗi nghi ngờ và những gì bạn chưa nhìn rõ là nội dung của lá này. Đây không phải một thảm họa, đây là một màn sương. Một phần của tình huống còn tối, hoặc vì bạn thiếu thông tin, hoặc vì có người đang rối trí. Theo lối luận cổ điển, lá này có hướng: phần sẫm quay về lá nào thì lá đó là chỗ rắc rối, còn phần sáng quay về lá nào thì lá đó là chỗ sẽ sáng ra.',
  love: 'Những tín hiệu bạn nhận được lẫn lộn với nhau, mối quan hệ thiếu rõ ràng, hoặc đối phương không hiểu nổi lòng mình. Trong bộ Lenormand, đây chính là lá của sự mập mờ.',
  work: 'Một quyết định được chốt trong lúc dữ liệu chưa đủ, những chỉ đạo nói nửa vời, hoặc một mớ bòng bong tại chỗ làm, tất cả đều là hình ảnh của lá này.',
  who: 'Bạn không tài nào đọc được người này, dù họ chưa chắc đã nói dối bạn. Tính khí của họ thay đổi liên tục và họ có thói quen lảng tránh.',
  time: 'Thời điểm ở đây không được xác định, và bản thân sự không xác định đó chính là thông điệp. Màn sương thường tan sau khoảng một đến ba ngày.',
  combo: [['+ Trái Tim', 'Tình cảm đang trong trạng thái rối. Mối tình của bạn thiếu rõ ràng và những tín hiệu bạn nhận được lẫn lộn với nhau.'],
          ['+ Chìa Khóa', 'Điều mơ hồ được tháo gỡ. Màn sương tan đi và mọi thứ trở nên sáng rõ.'],
          ['+ Con Cáo', 'Sự mù mờ ở đây có chủ đích. Một người nào đó đang cố tình khuấy cho nước đục lên.']] },

7: { name: 'Con Rắn', card: 'Q Chuồn', tone: 'neg', person: true,
  kw: { pos: ['sự khôn ngoan', 'quyến rũ', 'một đường vòng cần thiết', 'lột xác'],
        neg: ['phản bội', 'người thứ ba', 'rắc rối', 'lời nói dối', 'đường đi quanh co'] },
  scene: 'Con rắn uốn thân thành một đường chữ S dài. Nó không bao giờ bò theo đường thẳng, và vẻ ngoài của nó rất đẹp.',
  core: 'Rắc rối là nội dung của lá này, và cụ thể hơn, đó là loại rắc rối có một con người đứng phía sau. Truyền thống gọi đó là một người phụ nữ khác, một tình địch, hoặc một người đang hành động ngược với lợi ích của bạn. Ở phạm vi rộng hơn, lá này thu về mọi thứ không đi theo đường thẳng, gồm một đường vòng, một sự vướng víu, một lời nói dối, hoặc một lối đi loanh quanh dẫn tới điều bạn muốn. Trí khôn ở đây rất dồi dào, chỉ có điều nó được đem ra phục vụ mục đích riêng của người sở hữu.',
  love: 'Người thứ ba, một tình địch, một mối quan hệ ngoài luồng, hoặc một mối quan hệ chứa rắc rối nghiêm trọng bên trong đều nằm ở lá này. Ham muốn giữa hai bên là có thật, tuy nhiên tình huống không hề đơn giản.',
  work: 'Nơi làm việc của bạn xuất hiện chuyện bè phái, đồng nghiệp chơi xấu, một thỏa thuận giấu điều kiện, hoặc một quy trình vòng vo.',
  who: 'Một người phụ nữ đang làm mọi việc rối thêm, có thể là người yêu cũ, tình địch, hoặc một người quen thao túng. Đôi khi đó chỉ đơn giản là một người sắc sảo, có sức hút và rất khó đối phó.',
  time: 'Nhịp ở đây chậm và ngoằn ngoèo. Sự việc không đi theo đường thẳng, cho nên bạn hãy trừ hao thêm thời gian.',
  combo: [['+ Trái Tim', 'Một tình địch xuất hiện trong chuyện tình cảm, hoặc một sức hút đang chi phối cuộc chơi. Bức tranh này có thêm một người nữa.'],
          ['+ Chiếc Nhẫn', 'Bên trong hợp đồng có bẫy, bên trong hôn nhân có người thứ ba, hoặc nói chung là một cam kết đầy nút thắt.'],
          ['+ Người Phụ Nữ', 'Cặp này cần được đọc thẳng theo nghĩa đen, vì có một người phụ nữ khác đang dính vào câu chuyện.']] },

8: { name: 'Quan Tài', card: '9 Rô', tone: 'neg',
  kw: { pos: ['một kết thúc dứt khoát', 'sự chuyển hóa', 'khép lại', 'buông bỏ'],
        neg: ['mất mát', 'bệnh tật', 'đau buồn', 'sự kết thúc', 'đình trệ'] },
  scene: 'Nắp đã đậy và cỗ quan tài nằm bất động. Những gì được cất bên dưới đều đã đi tới điểm cuối.',
  core: 'Một dấu chấm hết được đặt xuống. Lá này thuộc về những gì đã qua, gồm một mối quan hệ, một công việc, một chặng đời, và đôi khi một đợt bệnh. Cách luận hiện đại hiếm khi đọc nó thành cái chết theo nghĩa đen, nhưng tính dứt điểm của nó là thật. Bạn nên luận nó một cách trung thực thay vì làm nhẹ đi, và bạn nên nhìn sang lá kế bên, bởi vì Quan Tài mô tả thứ đã chấm dứt còn lá bên cạnh mô tả khoảng trống mà nó bỏ lại.',
  love: 'Câu hỏi chuyện này còn hay hết đã có đáp án, và đáp án là đã hết. Một mối quan hệ đóng lại, tình cảm không còn sự sống, hoặc một chặng đau buồn vừa mở ra.',
  work: 'Cửa hàng đóng lại, dự án bị gạch tên, hoặc chỗ làm của bạn không còn nữa. Bên cạnh đó, lá này nói về lúc bạn kiệt sức và trong người không còn chút năng lượng nào.',
  who: 'Nhân vật ở đây đang chịu tang, đang co mình lại, hoặc đã khóa chặt cảm xúc của bản thân.',
  time: 'Tám tuần là con số gắn với lá này, và nó đo một chặng đang đóng lại. Mốc đó cũng có thể chính là lúc sự việc chấm dứt, và rất có thể lúc ấy đã trôi qua.',
  combo: [['+ Trái Tim', 'Cặp này báo một mối quan hệ chấm dứt, hoặc một trái tim vỡ.'],
          ['+ Con Cò', 'Cái kết ở đây biến thành một thay đổi theo hướng tốt hơn. Đây là cặp chuyển hóa quen thuộc nhất.'],
          ['+ Cái Cây', 'Sức khỏe là chủ đề của cặp này, hoặc một tình trạng dai dẳng đang tới hồi kết.']] },

9: { name: 'Bó Hoa', card: 'Q Bích', tone: 'pos',
  kw: { pos: ['món quà', 'lời mời', 'sự duyên dáng', 'vẻ đẹp', 'sự trân trọng', 'một lời đề nghị dễ chịu'],
        neg: ['lời nịnh', 'duyên bề mặt', 'một cử chỉ không có gì phía sau'] },
  scene: 'Bó hoa đã gói xong và đang đợi tới tay ai đó. Lý do tồn tại duy nhất của nó là để được trao đi.',
  core: 'Một lời đề nghị dễ chịu đang tới, dưới dạng món quà, lời mời, lời khen hoặc một cử chỉ tử tế. Trong cả bộ bài, ít lá nào thân thiện bằng lá này, và nó làm ngọt lại mọi thứ mà nó chạm vào. Bạn chỉ cần nhớ một điều: bó hoa nằm ở lớp bề mặt. Nó đẹp và thật sự dễ chịu, song bản thân nó chưa chứng minh được chiều sâu. Có người đang đối xử rất đẹp với bạn, còn câu hỏi về sự thật lòng của họ thuộc về lá bên cạnh.',
  love: 'Có người đang theo đuổi bạn. Lời khen, quà tặng và lời mời lần lượt đến, và một người nào đó đang nỗ lực làm bạn vui. Trong một trải bài còn mập mờ, đây là dấu hiệu rất đáng mừng.',
  work: 'Công sức của bạn được ghi nhận, bạn được thưởng, một bài thuyết trình được đón nhận, hoặc một lời mời tham dự đến với bạn. Lá này còn gắn với công việc sáng tạo và những nghề gắn với cái đẹp.',
  who: 'Nhân vật ở đây duyên dáng, lịch thiệp và có ngoại hình dễ mến. Người này làm cho mọi việc trở nên nhẹ nhàng hơn.',
  time: 'Thời điểm ở đây đến sớm và êm đẹp, vào khoảng chín ngày.',
  combo: [['+ Trái Tim', 'Ai đó gửi tới bạn một cử chỉ lãng mạn, dưới hình thức bó hoa, món quà hoặc lời bày tỏ.'],
          ['+ Con Cáo', 'Lời khen ở đây được nói ra vì một mục đích. Sự duyên dáng chỉ đóng vai một nước cờ.'],
          ['+ Chiếc Nhẫn', 'Đằng sau đề nghị đẹp đẽ này có một sự cam kết thật sự. Đó là lời cầu hôn, hoặc món quà trong ngày đính hôn.']] },

10: { name: 'Lưỡi Hái', card: 'J Rô', tone: 'neg',
  kw: { pos: ['một nhát cắt dứt khoát', 'mùa gặt', 'loại bỏ gọn ghẽ', 'phẫu thuật'],
        neg: ['mất mát đột ngột', 'nguy hiểm', 'kết thúc bất ngờ', 'sự đứt gãy'] },
  scene: 'Lưỡi hái đang được nâng lên cao. Nó chỉ biết làm đúng một việc, đó là cắt gọn trong một nhát thật nhanh.',
  core: 'Một nhát cắt bất ngờ là hình ảnh cốt lõi ở đây. Nếu Quan Tài là cái kết lắng dần xuống, thì lá này là cái kết gói trong một khoảnh khắc, không hề báo trước và thường không có thảo luận đi kèm. Đây cũng là lá của quyết định, cụ thể là quyết định cắt bỏ một thứ. Tốc độ là đặc tính then chốt, bởi vì mọi thứ nó chạm tới đều diễn ra đột ngột. Theo lối đọc truyền thống, lưỡi dao hướng về phía nào thì thứ nằm phía đó chính là thứ đang bị cắt.',
  love: 'Một cuộc chia tay xảy ra đột ngột, liên lạc bị cắt đứt, hoặc một quyết định được đưa ra mà không hề báo trước. Lá này cũng nói về lần chính bạn dứt khoát chấm dứt mọi chuyện.',
  work: 'Dự án ngừng giữa chừng, hợp đồng bị hủy, hoặc bạn mất chỗ làm. Ngoài ra, mọi nghề cầm dao kéo hay đòi hỏi tay nghề chính xác, kể cả phẫu thuật, đều thuộc lá này.',
  who: 'Hãy nghĩ tới một nha sĩ, một bác sĩ mổ, hoặc một người khép lại mọi chuyện mà không cần một lời giải thích. Cách hành xử của họ vừa dứt khoát vừa bất ngờ.',
  time: 'Thời điểm ở đây là tức khắc. Sự việc diễn ra ngay lúc này, hoặc diễn ra hoàn toàn không có dấu hiệu báo trước.',
  combo: [['+ Trái Tim', 'Cuộc chia tay đến bất ngờ, hoặc một trong hai người quyết định khép lại mối quan hệ.'],
          ['+ Cái Cây', 'Một ca mổ, hoặc một biến cố sức khỏe ập tới không báo trước, là nội dung của cặp này.'],
          ['+ Chiếc Nhẫn', 'Lời hứa bị bẻ đôi, cuộc hôn nhân đi tới điểm cuối, hoặc bản hợp đồng bị xé ngang.']] },

11: { name: 'Ngọn Roi', card: 'J Chuồn', tone: 'neg',
  kw: { pos: ['kỷ luật', 'năng lượng thể chất', 'sự lặp lại có tích lũy', 'chuyện chăn gối'],
        neg: ['cãi vã', 'xung đột', 'lặp đi lặp lại', 'lại đúng cuộc cãi đó', 'bạo hành'] },
  scene: 'Hai cây roi đặt chéo lên nhau. Không việc gì ở đây chỉ xảy ra đúng một lần, bởi vì roi luôn là động tác được vung lại nhiều lượt.',
  core: 'Từ khóa của lá này là "lại nữa", tức là vẫn cuộc cãi đó, vẫn cái vòng đó, vẫn cách phản ứng đó. Nó đứng cho xung đột và cho sự lặp lại, bao gồm cãi cọ, lời chỉ trích và nỗi mệt của một tranh cãi mở lại hết lần này tới lần khác. Mặt kia của lá thuộc về thân thể, gồm thể thao, tập luyện, lao động nặng và đời sống tình dục. Dù bạn đọc theo mặt nào, động cơ bên dưới vẫn là một, đó là một việc được làm đi làm lại.',
  love: 'Hai người tranh cãi hết lần này tới lần khác, và mối quan hệ quay mãi quanh một chủ đề. Ở sắc thái khác, lá này nói về một sức hút thể xác mạnh mẽ.',
  work: 'Một tranh chấp cũ được khơi lại nhiều lần. Lá này còn nói tới lao động chân tay, những đầu việc lặp lại, các lời chỉ trích, và mâu thuẫn với đồng nghiệp.',
  who: 'Hãy nghĩ tới một huấn luyện viên, một vận động viên, hoặc chính người mà bạn va chạm hết lần này tới lần khác. Người này nóng nảy, thích tranh luận, và thiên về hoạt động thể chất.',
  time: 'Nhịp ở đây kéo dài và quay vòng. Sự việc còn xảy ra thêm vài lần nữa trước khi nó thật sự khép lại.',
  combo: [['+ Trái Tim', 'Mối quan hệ ở đây đầy sóng gió, với đam mê và cãi vã song hành cùng nhau.'],
          ['+ Mây', 'Cuộc cãi vã này không dẫn tới đâu, bởi vì không bên nào nói rõ được điều mình muốn.'],
          ['+ Quan Tài', 'Tranh cãi đi tới hồi kết, hoặc quan hệ tan vỡ vì tranh cãi.']] },

12: { name: 'Đôi Chim', card: '7 Rô', tone: 'neu',
  kw: { pos: ['trò chuyện', 'một cặp', 'cuộc gọi', 'thương lượng', 'sự rộn ràng'],
        neg: ['đàm tiếu', 'lo âu', 'nói nhiều', 'căng thẳng thần kinh', 'nói thay vì làm'] },
  scene: 'Trên lá bao giờ cũng có đúng hai con chim nhỏ, và chúng hót cùng một lúc. Tiếng của chúng lúc nào cũng inh ỏi.',
  core: 'Mọi thứ liên quan tới lời nói đều nằm trong lá này: một cuộc điện thoại, một buổi trò chuyện, một cuộc thương lượng, một tin đồn, và cả tiếng ồn lo lắng chạy trong đầu bạn. Hình ảnh hai con chim cho nó thêm nghĩa một cặp, tức là một đôi, hai con người, hoặc hai đơn vị của bất cứ thứ gì. Chiều sâu không phải thế mạnh ở đây, thay vào đó là sự ngắn gọn và bận rộn, kèm một tiếng vo ve lo âu ở phía nền.',
  love: 'Một cuộc trò chuyện với đối phương, một cuộc gọi, hoặc chính việc bạn đang ở trong một cặp đôi đều thuộc về lá này. Nó cũng nói tới nỗi lo lắng về mối quan hệ và những lời bàn tán của người ngoài về nó.',
  work: 'Họp hành, điện thoại, đàm phán, truyền thông và mọi nghề sống bằng giao tiếp đều nằm trong lá này. Chuyện bàn tán sau lưng ở công ty cũng thuộc về nó.',
  who: 'Hãy nghĩ tới một người bán hàng, một người làm truyền thông, hoặc anh chị em ruột, và lá này cũng chỉ được hai người. Tính cách đi kèm là nói nhiều, dễ gần, hay lo.',
  time: 'Nhịp ở đây nhanh nhưng lộn xộn, trải từ mười hai giờ cho tới mười hai ngày.',
  combo: [['+ Trái Tim', 'Chuyện tình cảm được hai người đem ra nói với nhau, hoặc họ chính thức thành một đôi.'],
          ['+ Mây', 'Tin đồn đi kèm sự rối rắm. Mọi người bàn tán sôi nổi trong lúc không ai nắm được sự thật.'],
          ['+ Chiếc Nhẫn', 'Các điều khoản đang được hai bên chốt dần, hoặc một cam kết đang nằm trên bàn thương lượng.']] },

13: { name: 'Đứa Trẻ', card: 'J Bích', tone: 'pos', person: true,
  kw: { pos: ['khởi đầu mới', 'ngây thơ', 'một đứa trẻ', 'một thứ nhỏ bé', 'năng lượng mới'],
        neg: ['non nớt', 'ngây ngô', 'thiếu kinh nghiệm', 'mới quá nên chưa tin được'] },
  scene: 'Một em bé đứng lẻ loi trên mặt lá. Ở em bé này, mọi thứ đều mới ở giai đoạn đầu tiên.',
  core: 'Khởi đầu và sự nhỏ bé là hai ý chính. Lá này có thể là một đứa trẻ bằng xương bằng thịt, và cũng có thể là bất cứ điều gì còn đứng ở vạch xuất phát, ví dụ một mối quan hệ mới, một công việc mới hoặc một ý tưởng mới. Mọi thứ nó chạm vào đều nhỏ lại và trẻ lại, cụ thể là một khoản tiền nhỏ, một vấn đề nhỏ, hoặc một giai đoạn còn rất sớm. Điều cần nói thẳng là sự thiếu kinh nghiệm, bởi vì Đứa Trẻ rất chân thành nhưng chưa biết mình đang làm gì.',
  love: 'Một mối quan hệ mới mở ra, hoặc mối quan hệ hiện tại vẫn còn ở những bước đầu. Tình cảm ở đây trong trẻo và thành thật, song nó chưa đủ chín. Theo nghĩa đen, lá này còn chỉ một đứa con hoặc một lần mang thai.',
  work: 'Một công việc mới, một người vừa vào nghề, một dự án quy mô nhỏ, hoặc một lần làm lại từ đầu đều thuộc về lá này. Nó cũng gắn với công việc chăm sóc trẻ em và với ngành giáo dục.',
  who: 'Chất trẻ con của người này có lúc làm bạn thấy dễ thương, có lúc lại làm bạn thấy phiền. Đó là một em bé, một người còn ít tuổi, hoặc một người vẫn giữ nguyên sự ngây thơ và non nớt.',
  time: 'Thời điểm ở đây nằm ở đoạn mở đầu của sự việc. Quãng thời gian này ngắn và tới sớm.',
  combo: [['+ Trái Tim', 'Cặp này báo một tình yêu vừa chớm, một mối tình còn non và một tấm lòng trong trẻo.'],
          ['+ Con Cò', 'Mang thai, sinh nở, hoặc một khởi đầu làm đảo lộn mọi thứ là nội dung của cặp này.'],
          ['+ Con Rắn', 'Sự ngây thơ đang bị một người nào đó lợi dụng.']] },

14: { name: 'Con Cáo', card: '9 Chuồn', tone: 'neg', person: true,
  kw: { pos: ['sự khôn khéo', 'chiến lược', 'tự bảo vệ', 'công việc kiếm sống'],
        neg: ['lừa dối', 'một cái bẫy', 'vụ lợi', 'bạn giả', 'một sai sót'] },
  scene: 'Con cáo đứng yên và dõi theo. Cuộc săn chưa mở màn, vì nó còn đang cân nhắc từng bước.',
  core: 'Sự tinh ranh và tính vụ lợi là nội dung của lá này. Một người nào đó đang xoay xở cho lợi ích của chính họ, và họ làm việc đó rất khéo. Thang độ trải rộng từ một chiến thuật vô hại cho tới một trò lừa trắng trợn, và lá nằm kề bên sẽ nói cho bạn biết mức nào đang đúng. Hầu hết các trường phái còn dùng Con Cáo cho công việc kiếm sống, tức là cái nghề đem tiền về cho bạn. Ngoài ra, lá này cảnh báo sai sót, bởi vì có thứ gì đó không đúng như cách nó đang được trình bày.',
  love: 'Trong mối quan hệ này có một bên đang chơi ván bài của riêng họ. Đó là người giấu bạn suy nghĩ thật, hoặc người bước vào với đầy toan tính.',
  work: 'Chính nghề nghiệp của bạn, một đồng nghiệp khó chịu, chuyện phe cánh nơi công sở, hoặc một lỗi trong công việc đều nằm ở đây. Bạn hãy đọc thật kỹ mọi giấy tờ trước khi đặt bút ký.',
  who: 'Hãy nghĩ tới một kẻ lừa đảo, một đối thủ, một đồng nghiệp, hoặc một người rất giỏi tính toán. Điểm chung của họ là sự khôn ngoan đi cùng lợi ích riêng.',
  time: 'Lịch hẹn được đưa ra không đáng để bạn tin. Sự việc sẽ tới trễ hơn lời hứa, hoặc sẽ diễn ra khác với những gì người ta nói với bạn.',
  combo: [['+ Trái Tim', 'Tình cảm ở đây thiếu chân thành, hoặc có người đang yêu vì một mục đích nằm ngoài tình yêu.'],
          ['+ Bó Hoa', 'Lời ngọt ngào ở đây là một công cụ.'],
          ['+ Chìa Khóa', 'Trò mánh bị vạch trần, và sự thật đằng sau nó hiện ra.']] },

15: { name: 'Con Gấu', card: '10 Chuồn', tone: 'pos', person: true,
  kw: { pos: ['sức mạnh', 'quyền lực', 'sự che chở', 'thẩm quyền', 'tiền lớn', 'người chống lưng'],
        neg: ['áp đảo', 'ghen tuông', 'kiểm soát', 'sức nặng', 'quá đà'] },
  scene: 'Một con gấu to lớn bước vào khung hình. Sự có mặt của nó đủ để đổi không khí cả căn phòng, và ở nó không có chỗ nào gọi là tinh tế.',
  core: 'Quyền lực là nội dung của lá này. Nó bao gồm sức mạnh, sự che chở, và người đang nắm thẩm quyền trong tình huống, có thể là một người sếp, một hình bóng người mẹ, hoặc người giữ nguồn lực. Nó cũng đại diện cho những khoản tiền lớn và cho khối lượng vật chất. Con Gấu giữ gìn những gì thuộc về nó, và đó vừa là ưu điểm vừa là vấn đề của nó, bởi vì mặt tối của lá này là sự chiếm hữu và sự kiểm soát.',
  love: 'Trong mối quan hệ này có một bên ở vị thế cao hơn, thường là người nhiều tuổi hơn. Người đó có thể là chỗ dựa mạnh mẽ cho bạn, và cũng có thể là người ghen tuông và muốn sở hữu bạn.',
  work: 'Chuyện quản lý, chuyện tài chính, một khoản tiền lớn, người nắm quyền và cả sếp của bạn đều được lá này bao trùm. Nó cũng báo hiệu một chỗ dựa đáng tin.',
  who: 'Bạn rất khó cãi lại người này, vì họ vừa mạnh vừa quen bảo bọc kẻ khác. Đó là một người có thẩm quyền, một người sếp, một người mẹ, hoặc một người hơn bạn về tuổi tác lẫn tầm vóc.',
  time: 'Nhịp ở đây dài và nặng nề. Đơn vị bạn nên dùng là tháng chứ không phải tuần.',
  combo: [['+ Con Cá', 'Tiền lớn là nội dung của cặp này, gồm một khoản đáng kể, sự giàu có, hoặc một vụ đầu tư.'],
          ['+ Trái Tim', 'Tình yêu ở đây mang tính chở che, hoặc mang tính ghen tuông và kiểm soát.'],
          ['+ Con Rắn', 'Một cuộc giành giật quyền lực nổ ra, hoặc một tình địch đầy ghen tuông bước vào.']] },

16: { name: 'Những Vì Sao', card: '6 Cơ', tone: 'pos',
  kw: { pos: ['hy vọng', 'sự sáng tỏ', 'định hướng', 'con đường rõ ràng', 'cảm hứng', 'số nhiều'],
        neg: ['tản mát', 'giấc mơ không có kế hoạch', 'ôm quá nhiều thứ', 'ban đêm'] },
  scene: 'Bầu trời đêm dày đặc những vì sao, và một ngôi trong số đó sáng vượt lên. Bạn có thể lấy chúng làm mốc để tìm đường.',
  core: 'Sự sáng tỏ, niềm hy vọng và phương hướng là nội dung của lá này. Con đường trước mặt đã hiện ra rõ, bạn biết mình đi về đâu, và hoàn cảnh đang được chiếu mệnh thuận lợi. Lá này mang màu tâm linh và trực giác, đồng thời nó có sức nhân lên, bởi vì nhiều ngôi sao nghĩa là nhiều hơn nữa cái mà lá bên cạnh nói tới. Điểm yếu của nó nằm ở chỗ các ngôi sao treo rất xa: nó chỉ đường rất đẹp, nhưng nó không bước thay bạn.',
  love: 'Mối quan hệ của bạn tràn hy vọng và đang được ưu ái. Lá này cũng nói tới một người mà bạn lý tưởng hóa, cùng với việc bạn nhìn rõ điều mình thật sự mong muốn.',
  work: 'Mọi hoạt động trên mạng, lĩnh vực công nghệ và các nghề sáng tạo đều nằm ở lá này, cùng với khá nhiều cơ hội nhỏ. Đường hướng bạn chọn tốt và kế hoạch của bạn mạch lạc.',
  who: 'Đây là người mà bạn dành sự ngưỡng mộ. Họ có tầm nhìn xa, thiên về đời sống tâm linh, và biết cách truyền cảm hứng cho người khác.',
  time: 'Thời điểm ở đây rơi vào ban đêm, hoặc vào lúc bạn đã có chỉ dẫn rõ ràng. Quãng thời gian tương ứng là mười sáu ngày.',
  combo: [['+ Trái Tim', 'Tình yêu ở đây đẹp và đầy hy vọng. Bạn cũng thấy rõ cảm xúc bên trong mình.'],
          ['+ Mây', 'Phương hướng của bạn biến mất. Hy vọng bị che lấp và kế hoạch trở nên mờ mịt.'],
          ['+ Chìa Khóa', 'Đáp án là có, và nó hiện lên không chút mập mờ. Sự sáng tỏ đi kèm ngay với sự chắc chắn.']] },

17: { name: 'Con Cò', card: 'Q Cơ', tone: 'pos',
  kw: { pos: ['thay đổi', 'cải thiện', 'chuyển chỗ', 'một giai đoạn mới', 'sinh nở', 'sự quay lại'],
        neg: ['không yên', 'thay đổi chỉ vì muốn đổi', 'thiếu ổn định'] },
  scene: 'Một con cò chân dài đang trên hành trình di cư. Nó rời đi, và sau đó nó trở lại.',
  core: 'Sự thay đổi là nội dung của lá này, và khác với đa số các lá thay đổi khác, đây là thay đổi đi lên. Chuyển nhà, đổi việc, một bước ngoặt trong quan hệ, và cả chuyện sinh nở theo nghĩa đen đều nằm ở đây. Vì loài cò di cư theo mùa, lá này còn mang nghĩa quay trở lại, tức là một điều gì đó tìm về hoặc một chu kỳ lặp lại. Quan Tài khép lại, Lưỡi Hái cắt phăng, còn Con Cò chuyển hóa, nghĩa là sự việc không dừng lại mà hóa thành một thứ khác.',
  love: 'Một sự cải thiện đang tới. Mối quan hệ của bạn sẽ đổi dạng, có thể là hai người dọn về chung một nhà, có thể là quan hệ được đưa lên mức chính thức, hoặc bước vào một chặng mới.',
  work: 'Bạn chuyển sang công việc khác, được đề bạt, đổi bộ phận hoặc dời tới thành phố khác. Sự đổi thay hoàn cảnh này là một tin vui.',
  who: 'Hãy nghĩ tới một bà đỡ, một người mẹ, hoặc một người vừa lột xác rất nhiều. Điểm chung là họ đang đứng giữa một giai đoạn chuyển tiếp.',
  time: 'Thời điểm ở đây là lúc giao mùa, vào khoảng mười bảy ngày. Nó cũng có thể rơi vào mùa xuân.',
  combo: [['+ Ngôi Nhà', 'Một lần chuyển nhà đang tới. Bạn hãy hiểu theo nghĩa đen.'],
          ['+ Đứa Trẻ', 'Đây là cặp quen thuộc báo tin mang thai hoặc sinh con.'],
          ['+ Quan Tài', 'Sự đổi thay này đặt dấu chấm cho một điều gì đó, hoặc một cái kết đang hóa thành bước ngoặt.']] },

18: { name: 'Con Chó', card: '10 Cơ', tone: 'pos', person: true,
  kw: { pos: ['bạn bè', 'trung thành', 'tin cậy', 'thủy chung', 'sự thân quen', 'chỗ dựa'],
        neg: ['phụ thuộc', 'trung thành mù quáng', 'ở lại vì quen', 'chỉ là bạn thôi'] },
  scene: 'Con chó ngồi yên một chỗ và chờ. Nó đã ở đó ngay từ lúc câu chuyện bắt đầu.',
  core: 'Lòng trung thành và tình bạn là nội dung của lá này. Trong cả bộ bài, ít lá nào ấm áp bằng nó, và nó chỉ tới một người đáng tin, tức là một người bạn, một người ở lại, một người đã chứng minh được bản thân. Đọc theo nghĩa đen, lá này thường chỉ đơn giản là một người bạn, và trong một trải bài tình cảm, chi tiết đó rất quan trọng. Con Chó gần gũi và bền bỉ, nhưng nó không phải lá của tình yêu đôi lứa. Nó là lá của người vẫn sẽ còn ở đó.',
  love: 'Bên cạnh bạn là một người chung thủy, hoặc một người thương bạn theo cách của một người bạn. Với trải bài còn mập mờ, bạn cần nói thẳng điều này: lá bài vừa có thể là lòng tận tụy, vừa có thể là một tình bạn dừng lại trước ranh giới.',
  work: 'Bạn đang có một điểm tựa vững trong công việc. Đó là một khách hàng gắn bó nhiều năm, một quan hệ hợp tác bền, hoặc một đồng nghiệp đáng tin.',
  who: 'Ở gần người này bạn thấy quen thuộc và yên tâm. Đó là một người bạn, một người yêu chung thủy, hoặc một người luôn đứng về phía bạn.',
  time: 'Nhịp ở đây đều đặn và đáng tin cậy. Sự việc sẽ diễn ra đúng vào lúc mà xưa nay nó vẫn diễn ra.',
  combo: [['+ Trái Tim', 'Tình bạn ở đây chan chứa thương mến, hoặc một người bạn đang bước qua ranh giới của tình bạn.'],
          ['+ Con Rắn', 'Một người bạn giả xuất hiện, và sự phản bội đến từ chính người bạn đặt niềm tin.'],
          ['+ Chiếc Nhẫn', 'Cam kết ở đây dựa trên lòng trung thành, và một tình bạn chuyển thành sự gắn bó lâu dài.']] },

19: { name: 'Tòa Tháp', card: '6 Bích', tone: 'neu',
  kw: { pos: ['thẩm quyền', 'cấu trúc', 'tổ chức', 'tầm nhìn xa', 'ranh giới'],
        neg: ['cô lập', 'cô đơn', 'lạnh lùng', 'thủ tục hành chính', 'bị gạt ra ngoài'] },
  scene: 'Một ngọn tháp đá vươn cao và không có gì vây quanh. Từ trên đỉnh, tầm mắt của bạn trải rất rộng, chỉ có điều bên cạnh bạn không có một ai.',
  core: 'Hai chủ đề của lá này là bộ máy tổ chức và độ cao đơn độc. Nó bao gồm các cơ quan chính thức như nhà nước, tập đoàn, bệnh viện và tòa án, cùng lối vận hành khô khan và nhiều nguyên tắc của chúng. Ở tầng cá nhân, lá này là sự cô lập: bạn đứng tách khỏi đám đông, bạn giữ một ranh giới, và bạn ở một mình vì tự chọn hoặc vì hoàn cảnh đưa đẩy. Đi kèm với nó là quyền lực, sự bền lâu và một mức độ lạnh lùng nhất định.',
  love: 'Khoảng cách cảm xúc, một người luôn dựng lên bức tường ngăn, hoặc một mối quan hệ nặng về nghi thức hơn là hơi ấm, tất cả đều thuộc lá này. Nó cũng nói tới tình trạng độc thân, và phần lớn là độc thân một cách thoải mái.',
  work: 'Giấy tờ chất chồng và tiến độ ì ạch. Bạn đang đối diện một tổ chức lớn, các thủ tục chính thức, chuyện pháp lý hoặc cơ quan nhà nước, hoặc bạn đang ngồi ở một ghế cấp cao.',
  who: 'Nhân vật ở đây nắm chức quyền, làm trong bộ máy công quyền, hoặc sống khép kín. Người này dè dặt và tự lo được cho mình.',
  time: 'Nhịp ở đây dài và mang dấu ấn của guồng máy. Sự việc bị chậm lại vì một bộ máy đã tham gia vào.',
  combo: [['+ Trái Tim', 'Một khoảng cách đang được duy trì trong tình yêu, hoặc có một trái tim đang lẻ bóng.'],
          ['+ Chiếc Nhẫn', 'Một thỏa thuận giữa các công ty, hoặc thủ tục đăng ký kết hôn, chính là bản hợp đồng chính thức ở đây.'],
          ['+ Khu Vườn', 'Việc riêng bước ra chỗ đông người. Bạn công bố một chuyện, hoặc một tổ chức được nhắc tới trên báo chí.']] },

20: { name: 'Khu Vườn', card: '8 Bích', tone: 'neu',
  kw: { pos: ['công chúng', 'một buổi tụ họp', 'cộng đồng', 'kết nối', 'gặp gỡ', 'đời sống xã hội'],
        neg: ['bị phơi bày', 'không còn riêng tư', 'quan hệ hời hợt', 'đám đông'] },
  scene: 'Một công viên mở với con đường dạo chạy xuyên qua giữa. Cửa vào không khóa với bất kỳ ai.',
  core: 'Không gian công cộng chính là lá này. Đây là nơi bạn bị nhìn thấy, gồm tiệc tùng, các buổi tụ họp, việc kết nối, mạng internet, danh tiếng, và mọi chuyện diễn ra trước mắt người khác. Bản thân nó không tốt cũng không xấu, nó chỉ cho biết rằng chuyện này đã hết riêng tư. Lá nào nằm kề Khu Vườn thì nội dung của lá đó trở thành chuyện ai cũng biết, hoặc diễn ra giữa đám đông.',
  love: 'Cuộc gặp đầu tiên diễn ra tại một dịp xã giao, trong một nhóm bạn mà cả hai cùng chơi, hoặc trên một ứng dụng hẹn hò. Mối quan hệ sau đó được dựng lên một cách công khai.',
  work: 'Uy tín nghề nghiệp, mảng marketing, các công việc tiếp xúc công chúng, một sự kiện và hoạt động kết nối đều nằm trong lá này. Một buổi họp đông người cũng vậy.',
  who: 'Nhân vật ở đây dễ hòa đồng với mọi người. Ngoài ra, lá này còn chỉ bản thân công chúng, một đám đông, hoặc một nhóm bạn bè.',
  time: 'Thời điểm ở đây là lúc mọi người tụ về một chỗ. Nó có thể rơi vào mùa hè, hoặc vào đúng lúc sự kiện diễn ra.',
  combo: [['+ Trái Tim', 'Mối tình ở đây được công khai, hoặc bạn gặp đối phương ngay tại một sự kiện.'],
          ['+ Đôi Chim', 'Câu chuyện đang bị đem ra bàn tán. Tin đồn chạy khắp một nhóm.'],
          ['+ Con Cá', 'Việc làm ăn của bạn diễn ra giữa đám đông. Cặp này nói về buôn bán, về chợ, và về nguồn thu tới từ công chúng.']] },

21: { name: 'Ngọn Núi', card: '8 Chuồn', tone: 'neg',
  kw: { pos: ['sức bền', 'một thử thách đáng leo', 'sự bền vững'],
        neg: ['tắc nghẽn', 'trì hoãn', 'chướng ngại', 'khoảng cách', 'một người lạnh lùng'] },
  scene: 'Một dãy núi hiện ra với lớp tuyết trắng trên đỉnh. Khối đá đó không hề nhúc nhích vì bạn.',
  core: 'Chướng ngại là nội dung của lá này. Một khối rất lớn đang chắn ngang lối đi, và bạn khó lòng đẩy nó sang bên. Đó là một sự trì hoãn, một chỗ tắc, hoặc một rào chắn cứng nằm giữa bạn và điều bạn mong muốn. Lá này còn nói về khoảng cách và cái lạnh, cụ thể là một người mà bạn không với tới, hoặc một tình huống đang đóng băng. Ngọn Núi không tuyên bố "không bao giờ". Nó chỉ cho biết rằng con đường này không đi được, và trong thời gian gần bạn cũng chưa đi được.',
  love: 'Giữa hai người có một vật cản nghiêm trọng, và mối quan hệ vì thế không nhúc nhích. Lá này còn nói tới một người lạnh lùng nằm ngoài tầm với của bạn, cùng một sự trì hoãn không biết khi nào dứt.',
  work: 'Một trở ngại nghề nghiệp đáng kể đang chờ bạn. Thủ tục kéo dài lê thê, cơ hội thăng tiến bị khóa, và dự án của bạn đứng nguyên tại chỗ.',
  who: 'Đây là một đối thủ, hoặc chỉ đơn giản là một người mà không ai lay chuyển nổi. Họ giữ khoảng cách, tỏ ra lạnh nhạt, và đang chắn đường bạn.',
  time: 'Thời gian ở đây đang bị chặn lại. Sự trì hoãn không có hạn định, cho nên bạn đừng dựng kế hoạch dựa trên nó.',
  combo: [['+ Trái Tim', 'Có một trái tim đã tắt lửa, hoặc một mối quan hệ đang bị khóa chặt.'],
          ['+ Chìa Khóa', 'Bạn vượt qua được vật cản, và chỗ nghẽn được mở ra. Đây là một cặp rất đáng mừng.'],
          ['+ Cỏ Ba Lá', 'Một chút may mắn đủ để đưa bạn qua vật cản, dù phần may đó không lớn.']] },

22: { name: 'Ngã Rẽ', card: 'Q Rô', tone: 'neu',
  kw: { pos: ['lựa chọn', 'các phương án', 'sự tự do', 'một quyết định'],
        neg: ['do dự', 'phân vân', 'quá nhiều lựa chọn', 'không có đường nào rõ'] },
  scene: 'Con đường chia thành hai nhánh, kèm một tấm biển chỉ hướng. Cả hai nhánh đều có thật.',
  core: 'Sự lựa chọn là nội dung của lá này. Trước mặt bạn có hơn một phương án, và kết quả sẽ tùy theo nhánh đường bạn bước vào. Đây là một lá trung tính đúng nghĩa, vì nó không phán xét nhánh nào hay hơn, nó chỉ xác nhận rằng quyền quyết định nằm trong tay bạn. Nó cũng mang nghĩa số nhiều, gồm hai của một thứ, các phương án thay thế, và đôi khi một người đang cố chừa lại cho mình nhiều lối lui.',
  love: 'Trước mặt bạn là hai con người, hoặc là câu hỏi nên đi tiếp hay dừng lại. Lá này cũng nói tới một người tới giờ vẫn chưa chịu chọn, và chính sự im lặng đó đã trả lời thay họ.',
  work: 'Nhiều hướng đi đang mở ra cùng lúc. Bạn phải chọn trong số các lời mời, chốt một quyết định nghề nghiệp, hoặc xử lý một ngã ba trong dự án.',
  who: 'Nhân vật ở đây vẫn còn do dự, đang nắm trong tay nhiều lựa chọn, hoặc chưa cam kết bất cứ điều gì.',
  time: 'Quyết định của bạn sẽ định ra thời điểm. Nhịp của sự việc hiện nằm trong tay bạn.',
  combo: [['+ Trái Tim', 'Chuyện tình cảm đang đặt ra cho bạn một lựa chọn, hoặc có ai đó chưa quyết được nên chọn ai trong hai người.'],
          ['+ Quan Tài', 'Lựa chọn đúng ở đây là dừng lại.'],
          ['+ Mây', 'Bạn phải chọn trong lúc mọi thứ còn mơ hồ, bởi vì các phương án chưa hiện rõ trước mắt bạn.']] },

23: { name: 'Đàn Chuột', card: '7 Chuồn', tone: 'neg',
  kw: { pos: ['nhìn ra là dừng được', 'một vấn đề nhỏ, bắt được sớm'],
        neg: ['hao hụt', 'bào mòn', 'căng thẳng', 'mất trộm', 'bị gặm dần'] },
  scene: 'Bầy chuột đang gặm nhấm một vật gì đó. Từng nhát gặm riêng lẻ đều không đáng kể, chỉ tổng số của chúng mới đáng kể.',
  core: 'Sự mất mát diễn ra từ từ là nội dung của lá này. Một thứ gì đó đang bị gặm mòn, có thể là tiền bạc, sức lực, sức khỏe, lòng tin, hoặc thời gian. Thiệt hại không hề ồn ào, và đó chính là chỗ nguy hiểm, bởi vì nó diễn ra từng chút một và bạn rất dễ bỏ qua cho tới khi phần mất đã lớn. Lá này còn mang nghĩa căng thẳng, lo âu và trộm cắp. Lá nào nằm cạnh đàn chuột thì lá đó đang bị hao hụt.',
  love: 'Niềm tin hoặc tình cảm đang vơi đi từng ngày. Mối quan hệ của bạn không bị bẻ gãy, nó bị mài mòn, và sự căng thẳng đang gặm dần vào chỗ gắn bó.',
  work: 'Bạn hãy soát lại từng chi tiết một. Có thứ đang bị lấy đi, các khoản thất thoát nhỏ nối nhau kéo dài, tiền bạc rỉ ra từng chút, và sự căng thẳng cùng tình trạng kiệt sức đã xuất hiện.',
  who: 'Ở bên người này, năng lượng của bạn vơi đi từng ngày. Đó là một người sống trong lo lắng triền miên, hoặc một kẻ quen tay lấy vặt.',
  time: 'Thời gian ở đây là một quá trình đang chảy chậm. Sự việc diễn ra ngay lúc này, nhưng nó tiến từng bước nhỏ.',
  combo: [['+ Con Cá', 'Nợ nần, thất thoát và những vụ mất cắp đang lấy dần tiền của bạn.'],
          ['+ Trái Tim', 'Nỗi đau lòng và sự căng thẳng đè lên bạn, hoặc tình cảm mỗi ngày một mỏng.'],
          ['+ Cái Cây', 'Căng thẳng đang bào mòn sức khỏe của bạn.']] },

24: { name: 'Trái Tim', card: 'J Cơ', tone: 'pos',
  kw: { pos: ['tình yêu', 'sự trìu mến', 'lãng mạn', 'ấm áp', 'chân thành', 'trái tim'],
        neg: ['ủy mị', 'yêu mà không hành động', 'bị cảm xúc dẫn dắt'] },
  scene: 'Chỉ có một trái tim màu đỏ, hiện lên rõ ràng và không thể lẫn với thứ gì. Phần còn lại của lá bài để trống.',
  core: 'Tình yêu là nội dung của lá này, tức là chính cảm xúc đó ở dạng rõ ràng nhất. Nó bao gồm sự lãng mạn, lòng thương mến, hơi ấm, sự tử tế và tình cảm thật lòng. Trong cả bộ bài, ít lá nào ít mơ hồ như nó, bởi vì Trái Tim có mặt ở đâu thì ở đó có tình cảm thật. Điều lá này không nói ra là người ta sẽ làm gì với tình cảm đó, vì nó chỉ mô tả cảm xúc chứ không mô tả sự cam kết. Câu hỏi về cam kết thuộc về lá Chiếc Nhẫn.',
  love: 'Khi trải bài còn nhiều điều chưa rõ, đây chính là lá bạn mong lật trúng. Nó là tình yêu ở dạng giản dị nhất, với sự lãng mạn, lòng chân thành và tình cảm thật.',
  work: 'Đồng nghiệp quý mến bạn, và bạn đặt cả tấm lòng vào một nghề mà bạn yêu. Các nghề chăm sóc cùng hoạt động thiện nguyện cũng nằm trong lá này.',
  who: 'Nhân vật ở đây ấm áp, giàu tình thương và rộng lượng. Đó cũng có thể là người đang được người khác yêu.',
  time: 'Thời điểm ở đây đến sớm và mang hơi ấm. Nó có thể rơi vào mùa hè, hoặc vào lúc cảm xúc đã chín đúng.',
  combo: [['+ Chiếc Nhẫn', 'Tình yêu và sự cam kết cùng có mặt. Trong cả bộ bài, đây là cặp về quan hệ mạnh nhất.'],
          ['+ Mây', 'Các tín hiệu chồng lên nhau, tình yêu chưa hiện hình, và bên trong bạn là một mớ cảm xúc rối.'],
          ['+ Ngọn Núi', 'Tình cảm ở đây có thật, chỉ tiếc là nó không băng qua nổi vật cản đang chắn ngang.']] },

25: { name: 'Chiếc Nhẫn', card: 'A Chuồn', tone: 'pos',
  kw: { pos: ['cam kết', 'hợp đồng', 'hôn nhân', 'sự gắn bó', 'một lời hứa', 'một chu kỳ'],
        neg: ['một ràng buộc khó thoát', 'vòng lặp', 'nghĩa vụ không có tình yêu'] },
  scene: 'Chiếc nhẫn vàng khép lại thành một vòng tròn trọn vẹn. Đường viền của nó không có điểm dừng, và chính chi tiết đó làm nên ý nghĩa của lá.',
  core: 'Sự cam kết và lời thỏa thuận giữ lấy cam kết đó là nội dung của lá này, gồm hôn nhân, hợp đồng, sự gắn bó và một lời hứa đã được trao. Vì hình dáng của nó là một vòng tròn khép kín, lá này còn mang nghĩa chu kỳ, tức là một điều gì đó quay trở lại, một khuôn mẫu tự lặp, hoặc một sự dàn xếp vẫn đang chạy. Nó xác nhận rằng có một ràng buộc đang tồn tại. Việc ràng buộc đó có tình yêu bên trong hay không lại là câu hỏi dành cho lá Trái Tim.',
  love: 'Sự cam kết, một mối quan hệ nghiêm túc, một lễ đính hôn hoặc một đám cưới đều nằm ở lá này. Nó cũng nói tới một mối quan hệ liên tục lặp lại theo vòng.',
  work: 'Bạn hãy đọc từng điều khoản một cách cẩn thận. Lá này báo một hợp đồng, một mối làm ăn chung, một thỏa thuận có ràng buộc, hoặc một cơ chế đang chạy.',
  who: 'Nhân vật ở đây là bạn đời, người vợ hoặc người chồng, hoặc một đối tác kinh doanh. Giữa bạn và người này có một thỏa thuận ràng buộc hai bên.',
  time: 'Khoảng thời gian ở đây là một chu kỳ đầy đủ, vào chừng một năm. Thời điểm cũng có thể rơi vào lúc hợp đồng đến hạn.',
  combo: [['+ Trái Tim', 'Mối quan hệ ở đây có đủ cả cam kết lẫn tình yêu. Cặp này báo một lễ đính hôn hoặc một đám cưới.'],
          ['+ Lưỡi Hái', 'Cam kết bị cắt đứt giữa chừng, lễ đính hôn không thành, hoặc bản hợp đồng bị hủy.'],
          ['+ Con Rắn', 'Bên trong bản cam kết này có nút thắt, dưới dạng một điều khoản gài bẫy hoặc một người thứ ba trong hôn nhân.']] },

26: { name: 'Cuốn Sách', card: '10 Rô', tone: 'neu',
  kw: { pos: ['kiến thức', 'học hành', 'chuyên môn', 'nghiên cứu'],
        neg: ['một bí mật', 'điều bị giấu', 'thông tin bạn chưa có'] },
  scene: 'Cuốn sách gập lại, và trên nó có một chiếc khóa. Mọi hiểu biết của nó nằm khuất bên trong.',
  core: 'Lá này có hai mặt vốn cùng một gốc, đó là kiến thức và kiến thức bị giữ lại. Ở trạng thái đóng, nó là một bí mật, tức là điều chưa ai kể cho bạn, thông tin bị cố ý che, hoặc một khía cạnh còn khuất của tình huống. Ở trạng thái mở, nó là việc học hành, giáo dục, chuyên môn và nghiên cứu. Rất thường xuyên, thông điệp của nó trong trải bài chỉ gọn một câu: bức tranh trong tay bạn còn thiếu.',
  love: 'Mối quan hệ đang chứa một bí mật, hoặc có chuyện chưa ai nói cho bạn nghe. Lá này cũng nói tới một người rất khó mở lòng.',
  work: 'Việc học, các khóa đào tạo, bằng cấp, công tác nghiên cứu và chuyên môn sâu đều nằm ở lá này. Thông tin thuộc diện bảo mật tại nơi làm việc cũng thuộc về nó.',
  who: 'Nhân vật ở đây kín tiếng, có học thức, và quen giữ điều riêng cho mình. Đó là một giáo viên, một sinh viên, hoặc một nhà nghiên cứu.',
  time: 'Thời điểm chưa được tiết lộ, bởi vì nó vẫn đang bị giữ kín. Bạn hãy hỏi lại sau khi có thêm thông tin.',
  combo: [['+ Trái Tim', 'Có một tình cảm đang được giữ kín trong lòng, hoặc một mối tình chưa ai biết tới.'],
          ['+ Chìa Khóa', 'Bí mật bị đưa ra ánh sáng. Thứ vốn bị che nay đã hé ra.'],
          ['+ Con Cáo', 'Một người nào đó đang chủ động che giấu điều gì đó với bạn.']] },

27: { name: 'Lá Thư', card: '7 Bích', tone: 'neu',
  kw: { pos: ['một tin nhắn', 'một văn bản', 'tin bằng chữ', 'liên lạc', 'một bản ghi'],
        neg: ['tin xấu bằng văn bản', 'giấy tờ', 'chỉ nói trên giấy'] },
  scene: 'Phong thư đã được dán lại cẩn thận. Một người nào đó đã chủ ý chép nội dung này lên giấy.',
  core: 'Liên lạc bằng chữ viết là nội dung của lá này, gồm một tin nhắn, một email, một văn bản, một chứng chỉ, hoặc giấy tờ nói chung. Kỵ Mã mang tin tới, còn lá này chính là cái tin đó ở dạng bạn có thể giữ lại. Sắc thái của nó trung tính, và lá nằm kề bên sẽ cho biết tin này vui hay buồn. Ẩn ý lặng lẽ của nó là mọi thứ đã được ghi lại, nghĩa là có điều được viết thành chữ chứ không chỉ nói bằng miệng.',
  love: 'Đối phương gửi cho bạn một tin nhắn, một dòng chữ, hoặc một bức thư. Việc liên lạc đi qua con chữ trên màn hình chứ không qua một cuộc gặp mặt.',
  work: 'Một hợp đồng, một bản báo cáo, một hồ sơ ứng tuyển, một thư mời nhận việc, hoặc giấy tờ nói chung đều thuộc lá này. Mọi thứ mang tính chính thức trên văn bản đều nằm trong phạm vi của nó.',
  who: 'Nhân vật ở đây sống bằng nghề viết hoặc làm công việc hành chính. Đó cũng có thể là một người chuộng nhắn tin hơn là gọi điện.',
  time: 'Thời điểm ở đây là lúc tin nhắn tới tay bạn, thường chỉ sau vài ngày.',
  combo: [['+ Trái Tim', 'Một bức thư tình, một tin nhắn bày tỏ, hoặc một lời tỏ tình viết thành chữ sẽ đến với bạn.'],
          ['+ Quan Tài', 'Tin buồn đến với bạn dưới dạng văn bản, có thể là một lá đơn nghỉ việc hoặc một thông báo chấm dứt chính thức.'],
          ['+ Chiếc Nhẫn', 'Một hợp đồng, một giấy tờ chính thức, hoặc thủ tục đăng ký kết hôn là nội dung của cặp này.']] },

28: { name: 'Người Đàn Ông', card: 'A Cơ', tone: 'neu', person: true,
  kw: { pos: ['người đàn ông được hỏi', 'người hỏi bài là nam', 'bạn đời', 'anh ấy'] },
  scene: 'Trên lá là một người đàn ông, tư thế đứng, mắt hướng về phía trước. Vai của ông không phải vai biểu tượng, mà là vai một con người cụ thể.',
  core: 'Đây là một con người chứ không phải một tính chất. Khi người hỏi bài là nam, lá này chính là họ; khi câu hỏi xoay quanh một người đàn ông, lá này là người đàn ông đó. Anh ta đóng vai cột mốc của trải bài: những lá nằm gần anh ta mô tả anh ta, hướng mặt anh ta cho biết anh ta đang nhắm tới điều gì, và những lá phía sau lưng kể lại chuyện đã qua của anh ta. Bạn đừng luận lá này như một ý nghĩa. Bạn hãy định vị anh ta trước, sau đó đọc mọi thứ vây quanh anh ta.',
  love: 'Đây chính là người đàn ông trong câu hỏi của bạn, hoặc người bạn đời nam của bạn. Tâm trạng của anh ta được bộc lộ qua những lá nằm sát bên.',
  work: 'Một đồng nghiệp nam, một người sếp nam, hoặc một khách hàng nam đều nằm ở lá này. Đây là người đàn ông có mặt trong hoàn cảnh công việc của bạn.',
  who: 'Đây là một người đàn ông, và phần lớn trường hợp là người đã trưởng thành. Với một trải bài đồng giới, lá này thuộc về ai là do người luận quy ước ngay từ lúc mở đầu.',
  time: 'Nhịp của bạn không quyết định được gì ở đây, vì mọi việc chạy theo nhịp của anh ta. Anh ta ra tay lúc nào thì đó là thời điểm.',
  combo: [['Đàn Ông + Trái Tim', 'Người đàn ông này đã rung động trước một ai đó, hoặc anh ta đang yêu.'],
          ['Đàn Ông + Mây', 'Tâm trạng thật của người đàn ông này bị giấu đi, hoặc anh ta đang rối.'],
          ['Đàn Ông + Phụ Nữ', 'Hai người này đang ở bên nhau. Độ xa gần của hai lá trên bàn cho biết họ thân thiết tới mức nào.']] },

29: { name: 'Người Phụ Nữ', card: 'A Bích', tone: 'neu', person: true,
  kw: { pos: ['người phụ nữ được hỏi', 'người hỏi bài là nữ', 'bạn đời', 'cô ấy'] },
  scene: 'Trên lá là một người phụ nữ, lưng thẳng, mắt nhìn về phía trước. Cô đứng đó với tư cách một con người cụ thể, không phải một biểu tượng.',
  core: 'Đây là một con người chứ không phải một tính chất. Khi người hỏi bài là nữ, lá này chính là họ; khi câu hỏi xoay quanh một người phụ nữ, lá này là người phụ nữ đó. Cô làm cột mốc cho trải bài giống hệt cách Người Đàn Ông làm cột mốc, vì vậy bạn hãy đọc các lá quanh cô như hoàn cảnh, cảm xúc và những điều cô đang phải đương đầu. Riêng khoảng cách giữa lá Đàn Ông và lá Phụ Nữ trên mặt bàn đã là một thông tin đáng giá.',
  love: 'Đây chính là người phụ nữ trong câu hỏi của bạn, hoặc người bạn đời nữ của bạn. Vị thế của cô được các lá nằm sát bên nói rõ.',
  work: 'Một đồng nghiệp nữ, một người sếp nữ, hoặc một khách hàng nữ đều nằm ở lá này. Đây là người phụ nữ có mặt trong hoàn cảnh công việc của bạn.',
  who: 'Đây là một người phụ nữ, và phần lớn trường hợp là người đã trưởng thành. Với một trải bài đồng giới, lá này thuộc về ai là do người luận quy ước ngay từ lúc mở đầu.',
  time: 'Thời điểm được quyết định bởi lúc cô ra tay. Sự việc đi theo nhịp của cô, không đi theo nhịp của bạn.',
  combo: [['Phụ Nữ + Trái Tim', 'Người phụ nữ này đã rung động trước một ai đó, hoặc cô đang yêu.'],
          ['Phụ Nữ + Con Rắn', 'Ngay bên cạnh cô có bóng dáng một tình địch, hoặc rắc rối bắt nguồn từ chính cô.'],
          ['Phụ Nữ + Ngọn Núi', 'Người phụ nữ này đang bị cản trở, đang giữ khoảng cách, hoặc cô nằm ngoài tầm với của bạn.']] },

30: { name: 'Hoa Loa Kèn', card: 'K Bích', tone: 'pos', person: true,
  kw: { pos: ['sự chín chắn', 'bình an', 'khôn ngoan', 'từng trải', 'hài hòa', 'một người đàn ông lớn tuổi'],
        neg: ['lạnh nhạt', 'chênh lệch tuổi tác', 'chuyện chăn gối', 'đã qua mùa'] },
  scene: 'Bông loa kèn trắng đã bung hết cánh. Đóa hoa này không còn ở tuổi non nữa.',
  core: 'Điều lá này mang tới là sự chín chắn, tức là sự bình an, sự khôn ngoan và nét điềm tĩnh mà chỉ thời gian sống mới đem lại. Nó gắn với người lớn tuổi, với các tình huống đã yên vị từ lâu, và với những việc được xử lý đàng hoàng. Có hai nghĩa truyền thống nghe như chọi nhau nhưng cùng đúng cho lá này: nó vừa đứng cho sự thanh sạch và đức hạnh, vừa là lá của tình dục trong bộ bài. Nghĩa nào được lá bên cạnh chống đỡ thì bạn chọn nghĩa đó.',
  love: 'Bạn đời của bạn nhiều tuổi hơn, hoặc mối quan hệ giữa hai người đã chín và rất yên ả. Khoảng cách tuổi tác nằm ở đây, và nghĩa cụ thể về sự thân mật thể xác cũng vậy.',
  work: 'Chuyên môn tích lũy qua nhiều năm, kinh nghiệm dày, một vị trí được nể trọng, hoặc quãng nghỉ hưu đều thuộc lá này. Cách giải quyết ở đây điềm tĩnh và tử tế.',
  who: 'Hãy nghĩ tới một người thầy, một hình bóng người cha, một người có vị thế, hoặc một người đàn ông đã có tuổi. Nét chung của họ là sự điềm đạm cùng vốn sống dày.',
  time: 'Mùa đông, hoặc chặng cuối của một sự việc, là nơi mốc thời gian rơi vào. Nhịp đi kèm chậm rãi và đã tới độ chín.',
  combo: [['+ Trái Tim', 'Hai người có một tình yêu đã chín và rất yên, hoặc giữa họ là sự thân mật về thể xác.'],
          ['+ Người Đàn Ông', 'Nhân vật được nói tới là một người đàn ông đã có tuổi.'],
          ['+ Ngọn Núi', 'Một tình huống vốn đã chín nay xuất hiện sự lạnh nhạt và xa cách.']] },

31: { name: 'Mặt Trời', card: 'A Rô', tone: 'pos',
  kw: { pos: ['thành công', 'năng lượng', 'chiến thắng', 'ấm áp', 'sáng tỏ', 'một ngày đẹp'],
        neg: ['cháy sạch', 'kiêu ngạo', 'tốt quá hóa thừa'] },
  scene: 'Vầng dương tỏa sáng ở mức mạnh nhất, và những tia nắng của nó vươn ra tới sát mép lá bài.',
  core: 'Thành công và sinh lực là nội dung của lá này, và trong cả bộ bài không có lá nào tích cực hơn nó. Nó cho biết mọi việc đang trôi chảy, kèm theo năng lượng, hơi ấm, chiến thắng, sự công nhận và niềm vui có thật. Lá này còn khuếch đại bất cứ lá nào nằm cạnh, khiến một lá khó trở nên dễ thở hơn và một lá tốt trở nên xuất sắc. Trước một câu hỏi có hoặc không, khó tìm được chữ "có" nào rõ hơn thế.',
  love: 'Mối quan hệ của bạn vui vẻ và ấm áp, đi cùng niềm hạnh phúc và một kết quả rất đẹp. Khi bạn hỏi mọi chuyện có suôn sẻ hay không, lá này trả lời rằng có.',
  work: 'Năng lượng dành cho công việc của bạn rất dồi dào, và đi kèm là chiến thắng, sự ghi nhận cùng thành công. Dự án chạy trơn tru, và điều đó cũng lọt vào mắt những người xung quanh.',
  who: 'Nhân vật ở đây ấm áp, tự tin và thành đạt. Chỉ cần người này bước vào, căn phòng đã sáng hẳn lên.',
  time: 'Mùa hè, ban ngày và một mốc tới sớm là nơi thời điểm rơi vào. Sự việc diễn ra vừa nhanh vừa rực rỡ.',
  combo: [['+ Trái Tim', 'Hạnh phúc lớn đang ở trong chuyện tình cảm của bạn. Cả bộ bài hiếm có cặp nào đẹp bằng cặp này.'],
          ['+ Con Cá', 'Thành công về tài chính đang tới, bởi vì tiền bạc và sự thuận lợi cùng xuất hiện một lúc.'],
          ['+ Mây', 'Nắng đang nấp sau một đám mây. Thành công bị hoãn lại hoặc bị che đi, song nó chưa hề mất.']] },

32: { name: 'Mặt Trăng', card: '8 Cơ', tone: 'pos',
  kw: { pos: ['cảm xúc', 'được công nhận', 'danh tiếng', 'trực giác', 'lãng mạn', 'một tháng'],
        neg: ['thất thường', 'ảo tưởng', 'sống bằng cảm xúc', 'thèm được chú ý'] },
  scene: 'Trên nền trời tối, một vầng trăng khuyết đang treo. Nó có tỏa sáng, song thứ ánh sáng đó không mạnh, và mỗi đêm nó lại mang một hình dạng khác.',
  core: 'Đời sống cảm xúc và danh tiếng là hai nội dung của lá này, và chúng nối với nhau qua ý niệm phản chiếu. Quay vào bên trong, lá này là cảm xúc, trực giác, giấc mơ và sự lãng mạn. Quay ra bên ngoài, nó là danh dự, sự công nhận, tiếng tăm và cách người khác nhìn bạn. Đây cũng là lá xác định thời điểm rõ nhất bộ bài, vì một vầng trăng ứng với một tháng. So với lá Mặt Trăng bên tarot, lá này ấm hơn và ít u ám hơn nhiều.',
  love: 'Giữa hai người có một mối dây đậm tình cảm, một sự đồng điệu về tâm hồn, và những rung động lãng mạn rất sâu. Kèm theo đó là các đợt lên xuống thất thường của tâm trạng.',
  work: 'Ca đêm, nghề nghệ thuật, công việc sáng tạo, tiếng tăm và sự công nhận đều nằm trong lá này. Nó còn báo rằng bạn được vinh danh vì một điều gì đó.',
  who: 'Đây là một người có tên tuổi, hoặc một người đang khao khát được người khác biết tới. Họ sống nhiều bằng cảm xúc, trực giác nhạy, và mang chất nghệ sĩ.',
  time: 'Khoảng thời gian ở đây vào chừng một tháng. Thời điểm cũng có thể nằm trong ban đêm.',
  combo: [['+ Trái Tim', 'Tình yêu ở đây lãng mạn và sâu đậm, với cảm xúc và tình cảm cùng có mặt một lúc.'],
          ['+ Mặt Trời', 'Mọi việc chạy trơn tru, và ánh mắt của người khác đang đổ về phía bạn. Thành công và sự công nhận cùng có mặt.'],
          ['+ Mây', 'Cảm xúc của bạn rối loạn, hoặc tiếng tăm của bạn bị một bóng mờ phủ lên.']] },

33: { name: 'Chìa Khóa', card: '8 Rô', tone: 'pos',
  kw: { pos: ['sự chắc chắn', 'khẳng định', 'lời giải', 'mở ra', 'câu trả lời', 'thành công'] },
  scene: 'Mặt lá chỉ đặt duy nhất một chiếc chìa khóa. Nó không đại diện cho cánh cửa, nó là vật làm cho cánh cửa mở ra.',
  core: 'Sự chắc chắn là nội dung của lá này. Nó có nghĩa là có, là cánh cửa đã mở, và là lời giải đã nằm trong tay. Cuốn Sách khóa thứ gì lại thì lá này mở đúng thứ đó ra. Với một câu hỏi có hoặc không, đây là chữ "có" mạnh nhất bộ bài, và khi nằm cạnh bất kỳ lá tắc nghẽn nào, nó báo rằng chỗ nghẽn đã được khai thông. Thông điệp của nó là chuyện này đã ngã ngũ, đã được giải quyết, hoặc sắp được giải quyết.',
  love: 'Cánh cửa ở đây chưa bao giờ bị khóa. Mối quan hệ mở ra, mọi thứ hiện rõ, và điều lá này nói với bạn là một chữ "có" dứt khoát.',
  work: 'Phương án bạn đưa ra vận hành tốt. Lời giải cho vấn đề đã có, một cánh cửa vừa mở, và kết quả tới tay bạn rất rõ ràng.',
  who: 'Nhân vật ở đây quả quyết và thẳng thắn. Đó cũng có thể chính là người đang nắm câu trả lời.',
  time: 'Thời điểm ở đây là ngay lúc này, và nó chắc chắn. Sự việc diễn ra vào đúng lúc cánh cửa bật mở.',
  combo: [['+ Trái Tim', 'Chuyện tình cảm của bạn đã có sự chắc chắn, và câu trả lời cho nó là có.'],
          ['+ Ngọn Núi', 'Vật cản được dọn đi. Đây là một cặp rất thuận lợi.'],
          ['+ Cuốn Sách', 'Điều bí mật nay đã lộ ra.']] },

34: { name: 'Con Cá', card: 'K Rô', tone: 'pos',
  kw: { pos: ['tiền bạc', 'kinh doanh', 'dồi dào', 'dòng chảy', 'thu nhập', 'tự chủ'],
        neg: ['quá đà', 'tiền trôi đi', 'quá nhiều thứ gì đó'] },
  scene: 'Dưới làn nước sâu có một con cá đang bơi, và những đồng tiền từ từ chìm xuống đáy. Nước cũng động, tiền cũng động.',
  core: 'Tiền bạc và dòng chảy là nội dung của lá này. Nó bao gồm thu nhập, việc kinh doanh, chuyện buôn bán, của cải và quyền tự làm chủ, và nó mang cảm giác của một thứ vừa chảy vừa nhiều, bởi vì cá luôn đi theo đàn. Bên cạnh mặt tài chính, nó còn nghĩa là sự dồi dào nói chung, tức là rất nhiều thứ mà lá bên cạnh nói tới. Trước một câu hỏi về làm ăn, cả bộ bài không có lá nào thuận lợi trực tiếp hơn nó.',
  love: 'Giữa hai người, mọi thứ trôi chảy nhẹ nhàng, đời sống vật chất đủ đầy, và bạn đời của bạn rất rộng rãi. Có lúc lá này còn cho biết tiền bạc là một yếu tố trong mối quan hệ.',
  work: 'Dòng tiền của bạn đang chảy thuận. Lá này bao trùm việc bán hàng, đầu tư, kinh doanh, làm việc tự do và mọi nguồn thu nhập.',
  who: 'Nhân vật ở đây làm kinh doanh, tự lo được về tài chính, và rộng rãi với người khác. Đó là một nhà buôn.',
  time: 'Nhịp ở đây chảy đều và không đứt. Thời điểm rơi vào lúc tiền về, có thể là ngày nhận lương hoặc dịp cuối tháng.',
  combo: [['+ Con Gấu', 'Một món tiền lớn xuất hiện.'],
          ['+ Đàn Chuột', 'Những chỗ rò, các món nợ và các khoản lỗ đang cuốn tiền của bạn đi.'],
          ['+ Mỏ Neo', 'Nguồn thu của bạn đều đặn và đáng tin. Nền tài chính của bạn ở trạng thái an toàn.']] },

35: { name: 'Mỏ Neo', card: '9 Bích', tone: 'pos',
  kw: { pos: ['ổn định', 'kiên trì', 'an toàn', 'công việc', 'bám trụ', 'ở lại lâu'],
        neg: ['mắc kẹt', 'bị níu lại', 'giữ quá lâu', 'không lay chuyển'] },
  scene: 'Dưới đáy biển, dây xích căng ra và giữ chặt chiếc mỏ neo. Công việc của nó là ghìm mọi thứ lại một chỗ, và nó đang làm rất tròn vai.',
  core: 'Sự ổn định và sức bền là nội dung của lá này. Nó cho biết có một thứ đang trụ vững, có thể là một công việc lâu dài, một mối quan hệ bền, hoặc một tình huống sẽ không đổi. Nó cũng là lá của công việc theo nghĩa nghề nghiệp nuôi sống bạn, và của sự kiên trì, tức là bám trụ cho tới khi có kết quả. Mặt tối của nó chính là phẩm chất đó khi nhìn từ phía ngược lại, gồm sự mắc kẹt và việc níu giữ một thứ rất lâu sau thời điểm lẽ ra nên buông tay.',
  love: 'Mối quan hệ của bạn kéo dài, và người bên cạnh là người ở lại. An toàn ở đây nhiều hơn hồi hộp. Lá này cũng có thể là một mối dây bạn đang giữ quá hạn của nó.',
  work: 'Công việc của bạn ổn định, sự gắn bó của bạn lâu dài, và vị trí của bạn vững vàng. Sang năm sau, chỗ làm này vẫn còn nguyên đó.',
  who: 'Nhân vật ở đây vững vàng, đáng tin cậy và không dễ lung lay. Người này sẽ không bỏ đi.',
  time: 'Nhịp ở đây dài hơi và bền bỉ. Những gì lá này nói vẫn giữ nguyên giá trị về sau.',
  combo: [['+ Trái Tim', 'Tình yêu ở đây bền lâu, và mối quan hệ này đủ sức trụ lại.'],
          ['+ Con Cá', 'Nguồn thu của bạn vững, và vị thế tài chính của bạn ổn định.'],
          ['+ Quan Tài', 'Một tình huống dai dẳng từ lâu rốt cuộc đã khép lại.']] },

36: { name: 'Cây Thánh Giá', card: '6 Chuồn', tone: 'neg',
  kw: { pos: ['đức tin', 'ý nghĩa', 'gánh nặng sắp qua', 'kết thúc một thử thách'],
        neg: ['khổ sở', 'gánh nặng', 'số phận', 'mặc cảm tội lỗi', 'điều phải chịu đựng'] },
  scene: 'Cây thánh giá gỗ được cắm xuống nền đất. Sức nặng của nó rất lớn, và nó có mặt ở đó để có người vác nó lên vai.',
  core: 'Gánh nặng và số phận là nội dung của lá này. Nó đánh dấu phần khó nhọc, gồm nỗi khổ, nghĩa vụ, mặc cảm, và một khó khăn mà bạn buộc phải đi xuyên qua chứ không thể đi vòng. Nó cũng mang sức nặng tâm linh có thật, gồm niềm tin, ý nghĩa và định mệnh. Vì đây là lá cuối cùng của bộ bài, nó thường báo rằng một thử thách sắp khép lại, cho nên bạn rất nên đọc kỹ lá xuất hiện ngay sau nó. Lá này nặng, nhưng nó có hồi kết.',
  love: 'Nỗi khổ vì yêu, cảm giác mặc cảm, hoặc một mối dây vừa duyên nợ vừa nhọc nhằn, đó là những gì lá này nói. Mối quan hệ của bạn nặng gánh, và nó làm bạn đau.',
  work: 'Có một nghĩa vụ mà bạn không thể đặt xuống. Chỗ làm của bạn đang ở giai đoạn khó, và lượng việc đổ lên vai bạn quá nhiều.',
  who: 'Hãy nghĩ tới một người sùng đạo, hoặc một người mang giúp phần nặng của kẻ khác. Trên vai họ là một gánh nặng, và trong lòng họ là nỗi khổ.',
  time: 'Thời điểm ở đây là lúc một giai đoạn thử thách đang khép lại. Một chu kỳ đã đi tới gần cuối.',
  combo: [['+ Trái Tim', 'Tình cảm khiến bạn chịu khổ. Sự gắn bó này rất đau đớn.'],
          ['+ Mặt Trời', 'Gánh nặng được đặt xuống, và chặng đường khó khăn khép lại một cách tốt đẹp.'],
          ['+ Quan Tài', 'Nỗi đau và điểm dừng của nỗi đau là nội dung cặp này. Một chương đầy nặng nề vừa đóng lại.']] }

});
