/* ==================== quiz bank: the tarot course ====================
   Five questions to a lesson. The first option written is always the correct
   one; the screen shuffles them, so the order here is only for reading.

   The two marked hard: true in each set ask for something the lesson does not
   state outright - the Golden Dawn attributions the app carries in its own
   decan table, or a piece of the deck's history that anyone going further into
   tarot will meet early. Every one of them can be checked inside the app. */

QUIZ.tarot = {
  1: [
    { q: { vi: 'Một bộ tarot đầy đủ có bao nhiêu lá?', en: 'How many cards are in a full tarot deck?' },
      a: [{ vi: '78', en: '78' }, { vi: '52', en: '52' }, { vi: '36', en: '36' }, { vi: '22', en: '22' }],
      why: { vi: '78 lá: 22 lá Ẩn Chính và 56 lá Ẩn Phụ.', en: '78 cards: 22 Majors and 56 Minors.' } },
    { q: { vi: 'Bộ Ẩn Chính gồm bao nhiêu lá?', en: 'How many cards make up the Major Arcana?' },
      a: [{ vi: '22', en: '22' }, { vi: '16', en: '16' }, { vi: '40', en: '40' }, { vi: '56', en: '56' }],
      why: { vi: 'Ẩn Chính chạy từ số 0 tới số 21, tức 22 lá.', en: 'The Majors run from 0 to 21, which is 22 cards.' } },
    { q: { vi: 'Lá Gã Khờ mang số mấy?', en: 'What number does the Fool carry?' },
      a: [{ vi: '0', en: '0' }, { vi: '1', en: '1' }, { vi: '21', en: '21' }, { vi: '22', en: '22' }],
      why: { vi: 'Gã Khờ mang số 0, vì hành trình chưa bắt đầu.', en: 'The Fool is 0: the journey has not begun yet.' } },
    { hard: true,
      q: { vi: 'Ẩn Phụ có 56 lá. Ngoài 40 lá số, phần còn lại là gì?', en: 'The Minors number 56. Beyond the 40 pip cards, what makes up the rest?' },
      a: [{ vi: '16 lá hoàng gia', en: '16 court cards' }, { vi: '16 lá Ẩn Chính', en: '16 more Majors' }, { vi: '14 lá hoàng gia', en: '14 court cards' }, { vi: '12 lá hoàng gia', en: '12 court cards' }],
      why: { vi: '40 lá số (Át tới Mười của bốn chất) cộng 16 lá hoàng gia (bốn thứ bậc nhân bốn chất) là 56.', en: '40 pips (Ace to Ten in four suits) plus 16 court cards (four ranks in four suits) makes 56.' } },
    { hard: true,
      q: { vi: 'Trong thứ tự Rider–Waite, lá số 8 và lá số 11 lần lượt là gì?', en: 'In the Rider–Waite ordering, which cards are numbered 8 and 11?' },
      a: [{ vi: 'Sức Mạnh là 8, Công Lý là 11', en: 'Strength is 8, Justice is 11' }, { vi: 'Công Lý là 8, Sức Mạnh là 11', en: 'Justice is 8, Strength is 11' }, { vi: 'Ẩn Sĩ là 8, Bánh Xe là 11', en: 'The Hermit is 8, the Wheel is 11' }, { vi: 'Cỗ Xe là 8, Người Treo Ngược là 11', en: 'The Chariot is 8, the Hanged Man is 11' }],
      why: { vi: 'Waite đã đổi chỗ hai lá này so với bộ Marseille để Sức Mạnh khớp với Sư Tử và Công Lý khớp với Thiên Bình. App này dùng thứ tự của Waite.', en: 'Waite swapped these two from the Marseille order so that Strength lines up with Leo and Justice with Libra. This app follows Waite.' } }
  ],
  2: [
    { q: { vi: 'Lá số 3 trong Ẩn Chính là lá nào?', en: 'Which card is number 3 in the Majors?' },
      a: [{ vi: 'Nữ Hoàng', en: 'The Empress' }, { vi: 'Nữ Tư Tế', en: 'The High Priestess' }, { vi: 'Hoàng Đế', en: 'The Emperor' }, { vi: 'Giáo Hoàng', en: 'The Hierophant' }],
      why: { vi: 'Nữ Hoàng là số 3, đứng giữa Nữ Tư Tế (2) và Hoàng Đế (4).', en: 'The Empress is 3, between the High Priestess (2) and the Emperor (4).' } },
    { q: { vi: 'Lá Người Yêu mang số mấy?', en: 'What number is the Lovers?' },
      a: [{ vi: '6', en: '6' }, { vi: '2', en: '2' }, { vi: '7', en: '7' }, { vi: '5', en: '5' }],
      why: { vi: 'Người Yêu là số 6, ngay trước Cỗ Xe.', en: 'The Lovers is 6, just before the Chariot.' } },
    { q: { vi: 'Nữ Tư Tế nói về điều gì rõ nhất?', en: 'What does the High Priestess speak of most clearly?' },
      a: [{ vi: 'Trực giác và điều chưa nói ra', en: 'Intuition and what is not yet said' }, { vi: 'Quyền lực và luật lệ', en: 'Power and rules' }, { vi: 'Tiền bạc và công việc', en: 'Money and work' }, { vi: 'Chuyến đi xa', en: 'A long journey' }],
      why: { vi: 'Nữ Tư Tế giữ điều chưa được nói ra: bà biết nhưng chưa trả lời.', en: 'The High Priestess holds what has not been spoken: she knows, but does not answer yet.' } },
    { hard: true,
      q: { vi: 'Pháp Sư ứng với hành tinh nào?', en: 'Which planet belongs to the Magician?' },
      a: [{ vi: 'Sao Thuỷ', en: 'Mercury' }, { vi: 'Mặt Trăng', en: 'The Moon' }, { vi: 'Sao Kim', en: 'Venus' }, { vi: 'Mặt Trời', en: 'The Sun' }],
      why: { vi: 'Pháp Sư ứng với Sao Thuỷ: lời nói, tay nghề và sự khéo léo. Bạn xem lại ở mục Chiêm tinh của lá bài.', en: 'The Magician takes Mercury: speech, craft and dexterity. The card\'s astrology panel says so.' } },
    { hard: true,
      q: { vi: 'Cỗ Xe ứng với cung hoàng đạo nào?', en: 'Which zodiac sign belongs to the Chariot?' },
      a: [{ vi: 'Cự Giải', en: 'Cancer' }, { vi: 'Bạch Dương', en: 'Aries' }, { vi: 'Sư Tử', en: 'Leo' }, { vi: 'Nhân Mã', en: 'Sagittarius' }],
      why: { vi: 'Cỗ Xe ứng với Cự Giải: lớp vỏ cứng bên ngoài che một bên trong mềm, và đó chính là chiếc xe.', en: 'The Chariot is Cancer: a hard shell around something soft, which is exactly what a chariot is.' } }
  ],
  3: [
    { q: { vi: 'Ẩn Sĩ mang số mấy?', en: 'What number is the Hermit?' },
      a: [{ vi: '9', en: '9' }, { vi: '8', en: '8' }, { vi: '10', en: '10' }, { vi: '12', en: '12' }],
      why: { vi: 'Ẩn Sĩ là số 9, ngay trước Bánh Xe Số Phận.', en: 'The Hermit is 9, just before the Wheel of Fortune.' } },
    { q: { vi: 'Lá số 13 là lá nào?', en: 'Which card is number 13?' },
      a: [{ vi: 'Cái Chết', en: 'Death' }, { vi: 'Tiết Độ', en: 'Temperance' }, { vi: 'Người Treo Ngược', en: 'The Hanged Man' }, { vi: 'Ác Quỷ', en: 'The Devil' }],
      why: { vi: 'Cái Chết là số 13, và trong tarot nó nói về một kết thúc dứt khoát chứ không phải cái chết thật.', en: 'Death is 13, and in tarot it speaks of a decisive ending rather than a literal death.' } },
    { q: { vi: 'Người Treo Ngược dạy điều gì?', en: 'What does the Hanged Man teach?' },
      a: [{ vi: 'Dừng lại và nhìn mọi việc theo chiều khác', en: 'Stopping, and seeing things the other way up' }, { vi: 'Hành động thật nhanh', en: 'Acting quickly' }, { vi: 'Tích luỹ tiền bạc', en: 'Building up money' }, { vi: 'Tranh luận cho tới khi thắng', en: 'Arguing until you win' }],
      why: { vi: 'Người Treo Ngược tự nguyện treo mình: cái giá của một góc nhìn mới là phải chịu đứng yên.', en: 'The Hanged Man hangs willingly: the price of a new view is holding still for it.' } },
    { hard: true,
      q: { vi: 'Bánh Xe Số Phận ứng với hành tinh nào?', en: 'Which planet belongs to the Wheel of Fortune?' },
      a: [{ vi: 'Sao Mộc', en: 'Jupiter' }, { vi: 'Sao Thổ', en: 'Saturn' }, { vi: 'Sao Hoả', en: 'Mars' }, { vi: 'Sao Kim', en: 'Venus' }],
      why: { vi: 'Bánh Xe ứng với Sao Mộc: hành tinh của sự mở rộng và của vận may đến từ bên ngoài.', en: 'The Wheel takes Jupiter: the planet of expansion and of luck arriving from outside.' } },
    { hard: true,
      q: { vi: 'Tiết Độ ứng với cung hoàng đạo nào?', en: 'Which zodiac sign belongs to Temperance?' },
      a: [{ vi: 'Nhân Mã', en: 'Sagittarius' }, { vi: 'Bảo Bình', en: 'Aquarius' }, { vi: 'Xử Nữ', en: 'Virgo' }, { vi: 'Thiên Bình', en: 'Libra' }],
      why: { vi: 'Tiết Độ ứng với Nhân Mã: mũi tên nhắm xa, pha trộn hai thứ để tới được đích.', en: 'Temperance is Sagittarius: an arrow aimed far off, blending two things to carry it there.' } }
  ],
  4: [
    { q: { vi: 'Lá số 16 là lá nào?', en: 'Which card is number 16?' },
      a: [{ vi: 'Tòa Tháp', en: 'The Tower' }, { vi: 'Ác Quỷ', en: 'The Devil' }, { vi: 'Ngôi Sao', en: 'The Star' }, { vi: 'Mặt Trăng', en: 'The Moon' }],
      why: { vi: 'Tòa Tháp là số 16, ngay sau Ác Quỷ và ngay trước Ngôi Sao.', en: 'The Tower is 16, straight after the Devil and straight before the Star.' } },
    { q: { vi: 'Lá cuối cùng của Ẩn Chính là lá nào?', en: 'Which card closes the Major Arcana?' },
      a: [{ vi: 'Thế Giới', en: 'The World' }, { vi: 'Phán Xét', en: 'Judgement' }, { vi: 'Mặt Trời', en: 'The Sun' }, { vi: 'Gã Khờ', en: 'The Fool' }],
      why: { vi: 'Thế Giới là số 21, lá cuối cùng: vòng đi đã trọn.', en: 'The World is 21, the last card: the round is complete.' } },
    { q: { vi: 'Ngôi Sao đến ngay sau lá nào, và vì sao điều đó quan trọng?', en: 'Which card comes immediately before the Star, and why does that matter?' },
      a: [{ vi: 'Tòa Tháp — hy vọng đến ngay sau khi mọi thứ sụp đổ', en: 'The Tower — hope arrives right after everything falls' }, { vi: 'Mặt Trăng — ánh sáng đến sau sương mù', en: 'The Moon — light arrives after the fog' }, { vi: 'Mặt Trời — niềm vui nối tiếp niềm vui', en: 'The Sun — one joy follows another' }, { vi: 'Phán Xét — tỉnh thức rồi mới hy vọng', en: 'Judgement — waking first, then hope' }],
      why: { vi: 'Ngôi Sao (17) đứng ngay sau Tòa Tháp (16). Thứ tự ấy là cả bài học: hy vọng đến sau đổ vỡ, chứ không phải trước.', en: 'The Star (17) follows the Tower (16). That order is the lesson: hope comes after the wreck, not before it.' } },
    { hard: true,
      q: { vi: 'Tòa Tháp ứng với hành tinh nào?', en: 'Which planet belongs to the Tower?' },
      a: [{ vi: 'Sao Hoả', en: 'Mars' }, { vi: 'Sao Thiên Vương', en: 'Uranus' }, { vi: 'Sao Thổ', en: 'Saturn' }, { vi: 'Sao Diêm Vương', en: 'Pluto' }],
      why: { vi: 'Tòa Tháp ứng với Sao Hoả: cú đánh thẳng, nhanh và không báo trước.', en: 'The Tower takes Mars: the blow that lands straight, fast and unannounced.' } },
    { hard: true,
      q: { vi: 'Thế Giới ứng với hành tinh nào?', en: 'Which planet belongs to the World?' },
      a: [{ vi: 'Sao Thổ', en: 'Saturn' }, { vi: 'Sao Mộc', en: 'Jupiter' }, { vi: 'Mặt Trời', en: 'The Sun' }, { vi: 'Sao Hải Vương', en: 'Neptune' }],
      why: { vi: 'Thế Giới ứng với Sao Thổ: hành tinh của giới hạn, của thời gian và của việc hoàn tất.', en: 'The World takes Saturn: the planet of limits, of time, and of finishing.' } }
  ],
  5: [
    { q: { vi: 'Chất Gậy ứng với nguyên tố nào?', en: 'Which element belongs to Wands?' },
      a: [{ vi: 'Lửa', en: 'Fire' }, { vi: 'Nước', en: 'Water' }, { vi: 'Khí', en: 'Air' }, { vi: 'Đất', en: 'Earth' }],
      why: { vi: 'Gậy là lửa: hành động, đam mê và ý chí.', en: 'Wands are fire: action, passion and will.' } },
    { q: { vi: 'Chất Cốc ứng với nguyên tố nào?', en: 'Which element belongs to Cups?' },
      a: [{ vi: 'Nước', en: 'Water' }, { vi: 'Lửa', en: 'Fire' }, { vi: 'Đất', en: 'Earth' }, { vi: 'Khí', en: 'Air' }],
      why: { vi: 'Cốc là nước: cảm xúc, tình cảm và các mối quan hệ.', en: 'Cups are water: feeling, love and relationships.' } },
    { q: { vi: 'Trong mỗi chất, dãy lá số chạy từ đâu tới đâu?', en: 'Within each suit, where does the run of pip cards begin and end?' },
      a: [{ vi: 'Từ Át tới Mười', en: 'From the Ace to the Ten' }, { vi: 'Từ Hai tới Vua', en: 'From the Two to the King' }, { vi: 'Từ Át tới Vua', en: 'From the Ace to the King' }, { vi: 'Từ Một tới Hai Mươi Mốt', en: 'From One to Twenty-one' }],
      why: { vi: 'Át là hạt giống của chất, Mười là chất ấy ở mức đầy nhất. Bốn lá hoàng gia đứng riêng.', en: 'The Ace is the seed of the suit and the Ten is the suit at its fullest. The four court cards stand apart.' } },
    { hard: true,
      q: { vi: 'Lá Hai Gậy ứng với decan nào?', en: 'Which decan does the Two of Wands take?' },
      a: [{ vi: 'Sao Hoả trong Bạch Dương', en: 'Mars in Aries' }, { vi: 'Sao Kim trong Kim Ngưu', en: 'Venus in Taurus' }, { vi: 'Mặt Trời trong Sư Tử', en: 'The Sun in Leo' }, { vi: 'Sao Thuỷ trong Song Tử', en: 'Mercury in Gemini' }],
      why: { vi: 'Hai Gậy là Sao Hoả trong Bạch Dương, decan đầu tiên của vòng hoàng đạo, và tên cổ của nó là “Thống Lĩnh”. Bạn xem lại ở mục Chiêm tinh của lá bài.', en: 'The Two of Wands is Mars in Aries, the first decan of the zodiac, and its old title is “Dominion”. The card\'s astrology panel says so.' } },
    { hard: true,
      q: { vi: 'Bốn lá Át không được gán một decan. Vậy chúng được gán gì?', en: 'The four Aces are not given a decan. What are they given instead?' },
      a: [{ vi: 'Chính nguyên tố của chất đó', en: 'The element of their suit itself' }, { vi: 'Ba decan đầu của chất', en: 'The first three decans of the suit' }, { vi: 'Một hành tinh riêng', en: 'A planet of their own' }, { vi: 'Một lá Ẩn Chính tương ứng', en: 'A matching Major' }],
      why: { vi: 'Ba mươi sáu lá số từ Hai tới Mười phủ kín 36 decan. Bốn lá Át đứng ngoài hệ đó và mang chính nguyên tố của chất: lửa, nước, khí, đất.', en: 'The thirty-six pips from Two to Ten cover all thirty-six decans. The four Aces sit outside that scheme and carry the raw element of the suit: fire, water, air, earth.' } }
  ],
  6: [
    { q: { vi: 'Chất Kiếm ứng với nguyên tố nào?', en: 'Which element belongs to Swords?' },
      a: [{ vi: 'Khí', en: 'Air' }, { vi: 'Lửa', en: 'Fire' }, { vi: 'Đất', en: 'Earth' }, { vi: 'Nước', en: 'Water' }],
      why: { vi: 'Kiếm là khí: suy nghĩ, lời nói và xung đột.', en: 'Swords are air: thought, words and conflict.' } },
    { q: { vi: 'Chất Tiền ứng với nguyên tố nào?', en: 'Which element belongs to Pentacles?' },
      a: [{ vi: 'Đất', en: 'Earth' }, { vi: 'Khí', en: 'Air' }, { vi: 'Nước', en: 'Water' }, { vi: 'Lửa', en: 'Fire' }],
      why: { vi: 'Tiền là đất: tiền bạc, sức khỏe và những việc cụ thể.', en: 'Pentacles are earth: money, health and practical work.' } },
    { q: { vi: 'Vì sao Kiếm được xem là chất khó đọc nhất?', en: 'Why are Swords held to be the hardest suit to read?' },
      a: [{ vi: 'Vì phần lớn các lá nói về khó khăn trong suy nghĩ và lời nói', en: 'Because most of them speak of trouble in thought and speech' }, { vi: 'Vì chúng có nhiều lá hơn các chất khác', en: 'Because there are more of them than in other suits' }, { vi: 'Vì chúng không có lá hoàng gia', en: 'Because they have no court cards' }, { vi: 'Vì chúng không bao giờ nói về con người', en: 'Because they never speak of people' }],
      why: { vi: 'Mỗi chất có mười lá số như nhau. Kiếm khó vì nội dung của chúng: lo âu, tranh cãi và những quyết định phải trả giá.', en: 'Every suit has the same ten pips. Swords are hard because of what they carry: worry, argument and decisions that cost something.' } },
    { hard: true,
      q: { vi: 'Lá Mười Kiếm ứng với decan nào?', en: 'Which decan does the Ten of Swords take?' },
      a: [{ vi: 'Mặt Trời trong Song Tử', en: 'The Sun in Gemini' }, { vi: 'Sao Thổ trong Song Ngư', en: 'Saturn in Pisces' }, { vi: 'Sao Hoả trong Bọ Cạp', en: 'Mars in Scorpio' }, { vi: 'Sao Thuỷ trong Xử Nữ', en: 'Mercury in Virgo' }],
      why: { vi: 'Mười Kiếm là Mặt Trời trong Song Tử, decan cuối của Song Tử, tên cổ là “Sụp Đổ”.', en: 'The Ten of Swords is the Sun in Gemini, the last decan of Gemini, and its old title is “Ruin”.' } },
    { hard: true,
      q: { vi: 'Mười lá số của chất Kiếm trải trên ba cung nào?', en: 'The ten pips of Swords run across which three signs?' },
      a: [{ vi: 'Thiên Bình, Bảo Bình, Song Tử', en: 'Libra, Aquarius, Gemini' }, { vi: 'Bạch Dương, Sư Tử, Nhân Mã', en: 'Aries, Leo, Sagittarius' }, { vi: 'Cự Giải, Bọ Cạp, Song Ngư', en: 'Cancer, Scorpio, Pisces' }, { vi: 'Kim Ngưu, Xử Nữ, Ma Kết', en: 'Taurus, Virgo, Capricorn' }],
      why: { vi: 'Kiếm là khí, nên chúng trải trên ba cung khí: Thiên Bình, Bảo Bình và Song Tử. Mỗi cung nhận ba lá.', en: 'Swords are air, so they run across the three air signs: Libra, Aquarius and Gemini, three cards to each.' } }
  ],
  7: [
    { q: { vi: 'Bộ hoàng gia gồm bao nhiêu lá?', en: 'How many court cards are there?' },
      a: [{ vi: '16', en: '16' }, { vi: '12', en: '12' }, { vi: '4', en: '4' }, { vi: '22', en: '22' }],
      why: { vi: 'Bốn thứ bậc nhân bốn chất là 16 lá.', en: 'Four ranks in four suits makes 16.' } },
    { q: { vi: 'Bốn thứ bậc hoàng gia là gì?', en: 'What are the four court ranks?' },
      a: [{ vi: 'Tiểu Đồng, Hiệp Sĩ, Hoàng Hậu, Vua', en: 'Page, Knight, Queen, King' }, { vi: 'Át, Hoàng Hậu, Vua, Joker', en: 'Ace, Queen, King, Joker' }, { vi: 'Tiểu Đồng, Hoàng Tử, Công Chúa, Vua', en: 'Page, Prince, Princess, King' }, { vi: 'Hiệp Sĩ, Vua, Hoàng Hậu, Ẩn Sĩ', en: 'Knight, King, Queen, Hermit' }],
      why: { vi: 'Tiểu Đồng, Hiệp Sĩ, Hoàng Hậu và Vua, lặp lại trong cả bốn chất.', en: 'Page, Knight, Queen and King, repeated in all four suits.' } },
    { q: { vi: 'Một lá Vua thường chỉ điều gì trong một trải bài?', en: 'What does a King usually point to in a reading?' },
      a: [{ vi: 'Một người trưởng thành đang nắm quyền quyết định', en: 'A grown person who holds the decision' }, { vi: 'Một tin nhắn sắp đến', en: 'A message on its way' }, { vi: 'Một khoản tiền', en: 'A sum of money' }, { vi: 'Một khoảng thời gian dài', en: 'A long stretch of time' }],
      why: { vi: 'Vua là thứ bậc của quyền và của quyết định đã chín. Tin nhắn thường là Tiểu Đồng.', en: 'The King is the rank of authority and settled decision. A message is usually the Page.' } },
    { hard: true,
      q: { vi: 'Trong hệ Golden Dawn, mỗi lá hoàng gia được gán một khoảng hoàng đạo như thế nào?', en: 'In the Golden Dawn scheme, what stretch of the zodiac does a court card cover?' },
      a: [{ vi: 'Mười độ cuối của một cung và hai mươi độ đầu của cung kế tiếp', en: 'The last ten degrees of one sign and the first twenty of the next' }, { vi: 'Trọn một cung', en: 'One whole sign' }, { vi: 'Trọn hai cung liền nhau', en: 'Two whole signs in a row' }, { vi: 'Một decan duy nhất', en: 'A single decan' }],
      why: { vi: 'Mỗi lá hoàng gia bắc cầu qua hai cung: decan cuối của cung trước và hai decan đầu của cung sau. Vì thế lá bài mang tính chất của cả hai.', en: 'Each court card bridges two signs: the last decan of one and the first two of the next. That is why it carries something of both.' } },
    { hard: true,
      q: { vi: 'Thứ bậc nào trong bộ hoàng gia không được gán một khoảng hoàng đạo?', en: 'Which court rank is given no stretch of the zodiac at all?' },
      a: [{ vi: 'Tiểu Đồng', en: 'The Page' }, { vi: 'Hiệp Sĩ', en: 'The Knight' }, { vi: 'Hoàng Hậu', en: 'The Queen' }, { vi: 'Vua', en: 'The King' }],
      why: { vi: 'Ba thứ bậc kia phủ kín vòng hoàng đạo. Tiểu Đồng đứng ngoài: trong hệ này Tiểu Đồng được gán một phần tư của địa cầu chứ không phải một khoảng hoàng đạo.', en: 'The other three ranks cover the zodiac between them. The Page stands outside it: in this scheme the Page is given a quarter of the earth rather than a stretch of the sky.' } }
  ],
  8: [
    { q: { vi: 'Trải ba lá thường được đọc theo thứ tự nào?', en: 'How is a three-card spread usually read?' },
      a: [{ vi: 'Quá khứ – hiện tại – tương lai', en: 'Past – present – future' }, { vi: 'Tốt – xấu – trung tính', en: 'Good – bad – neutral' }, { vi: 'Tiền – tình – sức khỏe', en: 'Money – love – health' }, { vi: 'Sáng – trưa – tối', en: 'Morning – noon – night' }],
      why: { vi: 'Ba lá theo dòng thời gian là cách trải đầu tiên nên học, và cũng là cách dễ kiểm chứng nhất.', en: 'Three cards along a timeline is the first spread to learn and the easiest to check against life.' } },
    { q: { vi: 'Việc quan trọng nhất cần làm trước khi trải bài là gì?', en: 'What matters most before laying any cards?' },
      a: [{ vi: 'Đặt một câu hỏi rõ ràng', en: 'Settling on a clear question' }, { vi: 'Xáo bài thật lâu', en: 'Shuffling for a long time' }, { vi: 'Chọn đúng khăn trải', en: 'Choosing the right cloth' }, { vi: 'Rút thật nhiều lá', en: 'Drawing as many cards as possible' }],
      why: { vi: 'Một câu hỏi mơ hồ chỉ cho ra một câu trả lời mơ hồ. Câu hỏi là phần khó nhất của việc trải bài.', en: 'A vague question can only produce a vague answer. The question is the hardest part of any reading.' } },
    { q: { vi: 'Khi một trải bài cho ra câu trả lời bạn không muốn nghe, cách làm đúng là gì?', en: 'When a spread gives an answer you did not want, what is the right thing to do?' },
      a: [{ vi: 'Ghi lại và đối chiếu về sau', en: 'Write it down and check it against what happens' }, { vi: 'Rút lại cho tới khi ra kết quả khác', en: 'Draw again until it changes' }, { vi: 'Bỏ lá không thích ra ngoài', en: 'Take the unwanted card out' }, { vi: 'Đổi sang bộ bài khác', en: 'Switch to a different deck' }],
      why: { vi: 'Rút lại cùng một câu hỏi cho tới khi vừa ý là cách nhanh nhất để mất khả năng đọc bài. Ghi lại rồi đối chiếu mới là cách học.', en: 'Redrawing the same question until it pleases you is the fastest way to lose the ability to read at all. Recording and checking is how the skill is built.' } },
    { hard: true,
      q: { vi: 'Trải bài Celtic Cross gồm bao nhiêu vị trí?', en: 'How many positions make up the Celtic Cross?' },
      a: [{ vi: '10', en: '10' }, { vi: '7', en: '7' }, { vi: '12', en: '12' }, { vi: '5', en: '5' }],
      why: { vi: 'Celtic Cross có 10 vị trí: sáu lá làm thành hình thập giá và bốn lá xếp thành cột bên phải.', en: 'The Celtic Cross has 10: six making the cross itself and four in a staff up the right-hand side.' } },
    { hard: true,
      q: { vi: 'Trong lối trải bài cổ điển, “significator” là gì?', en: 'In the older spreads, what is a significator?' },
      a: [{ vi: 'Lá được chọn trước để đại diện cho người hỏi', en: 'A card chosen in advance to stand for the querent' }, { vi: 'Lá cuối cùng rút ra', en: 'The last card drawn' }, { vi: 'Lá rơi ra khi xáo bài', en: 'A card that falls out while shuffling' }, { vi: 'Lá Ẩn Chính đầu tiên xuất hiện', en: 'The first Major to appear' }],
      why: { vi: 'Significator được chọn có chủ ý, thường là một lá hoàng gia hợp với tuổi và tính cách người hỏi, rồi đặt làm trung tâm cho phần còn lại đọc quanh nó.', en: 'The significator is chosen deliberately, usually a court card matching the querent, and laid first so the rest of the spread is read around it.' } }
  ]
};
