/* ============================ spreads ============================ */
/* How many cards to draw for which kind of question, where each card goes, and
   what each position means.
   `lay` is a list of [col, row] grid slots -- and optionally a third entry 'r'
   for a card laid crosswise. The renderer turns that into a diagram, so a
   layout is described once and drawn identically in both languages.
   `kinds` drives the question-type filter. `sys` keeps the two systems apart. */

const SPREADS = { en: [], vi: [] };

/* ---- shared geometry, so both languages draw the same picture ---- */
const LAY = {
  one:    [[0, 0]],
  two:    [[0, 0], [1, 0]],
  three:  [[0, 0], [1, 0], [2, 0]],
  four:   [[0, 0], [1, 0], [2, 0], [3, 0]],
  five:   [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]],
  choice: [[1, 0], [0, 1], [0, 2], [2, 1], [2, 2]],
  rel7:   [[0, 0], [0, 1], [0, 2], [2, 0], [2, 1], [2, 2], [1, 1]],
  celtic: [[1, 1], [1, 1, 'r'], [1, 2], [0, 1], [1, 0], [2, 1], [3, 3], [3, 2], [3, 1], [3, 0]],
  box9:   [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2]],
  gt:     (function () {
    const a = [];
    for (let r = 0; r < 4; r++) for (let c = 0; c < 8; c++) a.push([c, r]);
    for (let c = 2; c < 6; c++) a.push([c, 4]);
    return a;
  }())
};

/* ============================ English ============================ */

SPREADS.en = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'Daily practice, and any question small enough to answer in a sentence. Also the right size when you have already read a spread and just need one more piece of information.',
  ask: '"What do I most need to know about ___ today?" Keep it open. A single card answers a *what*, badly answers a *should I*, and cannot answer a *when*.',
  pos: [['The answer', 'The whole reading. Read the image first and what you notice about it, then the keywords, then the upright or reversed meaning. Do not reach for a second card to soften the first one.']],
  read: 'One card is not a lesser reading — it is a more disciplined one. If the card seems to say nothing, the usual cause is that the question was too vague to be answered.',
  note: 'Never re-draw because you did not like the answer. If you genuinely need more, draw a clarifier and say out loud that that is what you are doing.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — situation, action, outcome',
  when: 'The everyday workhorse. Any question where you want to know what is going on, what to do about it, and where it leads. This is the spread to reach for when you are unsure which spread to use.',
  ask: '"Where does ___ stand, what should I do, and where does that lead?" One subject, three angles.',
  pos: [['1 · Situation', 'What is actually happening now — not what you fear or hope. If a Major lands here, the matter is bigger than the question you asked.'],
        ['2 · Action', 'What is yours to do. This position is advice, so read it as an instruction rather than a prediction.'],
        ['3 · Outcome', 'Where the current path leads *if the advice in position 2 is followed*. It is a projection, not a fixed fate.']],
  read: 'Read left to right as a sentence. Then check the balance across all three: heavy Majors mean the situation is not fully in your hands; all Minors of one suit means the whole matter lives in that one area of life.',
  note: 'Position 3 answers "if nothing changes." That is what makes position 2 worth acting on.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Yes / No — five cards',
  when: 'A genuine closed question with two possible answers. Use it sparingly: most questions worth asking are not yes/no questions, and forcing them into this shape wastes the reading.',
  ask: 'The question must be answerable with yes or no, and must be about one thing. "Will he text me this week?" works. "Will he text me and does he love me?" does not.',
  pos: [['1–5 · The tally', 'Deal five cards face up in a row. Count upright against reversed: three or more upright is yes, three or more reversed is no. Five to nothing in either direction is emphatic.'],
        ['The Majors', 'Any Major Arcana in the row carries double weight in the count — the matter is not entirely in human hands.'],
        ['The middle card', 'Card 3 is the heart of the answer. Even when the tally says yes, this card tells you what kind of yes it is.'],
        ['The suits', 'A row dominated by one suit tells you which area actually decides the outcome — Cups for feeling, Swords for what is said, Pentacles for practical reality, Wands for whether anyone acts.']],
  read: 'Give the tally first, then immediately explain it using card 3 and the suit balance. A bare yes or no is not a reading; it is a coin toss with pictures.',
  note: 'If you do not read reversals, this method does not work. Use the three-card spread instead and answer the question from the meaning.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Timing — four periods',
  when: '"When will it happen?" Tarot is poor at naming dates and good at describing sequence, so this spread asks *what happens in each period* rather than *which date*.',
  ask: 'Decide the unit before you shuffle and say it out loud: four weeks, or four months, or four quarters. Changing the unit after you see the cards is how readings become meaningless.',
  pos: [['1 · First period', 'What this stretch of time holds. If the thing you asked about appears here, it is close.'],
        ['2 · Second period', 'The next stretch. Watch for movement cards — Wands, Knights, the Chariot, the Wheel — which show things actually shifting.'],
        ['3 · Third period', 'The stretch after that. A run of stillness here (Fours, the Hanged Man, Seven of Pentacles) means the wait is longer than hoped.'],
        ['4 · Fourth period', 'The end of the window you asked about. If nothing has arrived by here, the honest answer is "not within this window" — say so.']],
  read: 'Find the card that answers the question and read the position it landed in. That is the timing. If no card answers it, the honest reading is that the event is not in this window, and the client is better served by hearing that than by a comforting guess.',
  note: 'Never promise a date. Give the period, give the conditions, and say plainly that timing is the least reliable thing tarot does.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Two roads — a decision',
  when: 'A real either/or: two jobs, stay or leave, tell them or say nothing. It compares two futures instead of predicting one.',
  ask: 'Name both options out loud before you shuffle, and assign one to the left branch and one to the right. Do not decide which is which after seeing the cards.',
  pos: [['1 · You now', 'Where you stand, and what you are actually deciding between — which is often not what you said it was.'],
        ['2 · Road A, first step', 'What immediately follows if you take the first option.'],
        ['3 · Road A, where it leads', 'Where that road arrives. Read it together with card 2 as one movement.'],
        ['4 · Road B, first step', 'What immediately follows if you take the second option.'],
        ['5 · Road B, where it leads', 'Where that road arrives.']],
  read: 'Compare the two branches as pairs, not as four separate cards. The cleaner reading is usually not "which branch is nicer" but "which branch is honest about its cost" — a road with a hard first step and a good end often beats an easy start.',
  note: 'The cards do not choose. They describe two futures; the decision stays with the person who asked.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Two sides — the relationship',
  when: 'Any two-person question where you need both sides separately: a couple, a situationship, a falling-out, even a working relationship. Its strength is that it refuses to blend the two people together.',
  ask: 'Name who is on the left and who is on the right before shuffling. The left column is usually the person asking.',
  pos: [['1 · You: feeling', 'What you actually feel, underneath what you say you feel.'],
        ['2 · You: thinking', 'What you tell yourself about this. Often at odds with card 1, and that gap is the reading.'],
        ['3 · You: doing', 'How you are actually behaving — what the other person sees.'],
        ['4 · Them: feeling', 'What they feel. Read it plainly; do not soften it because the person asking is in the room.'],
        ['5 · Them: thinking', 'How they are framing this to themselves.'],
        ['6 · Them: doing', 'What they are actually doing, which is the only part you have evidence for.'],
        ['7 · Between you', 'The relationship itself as a third thing — the shared ground, or what stands in it.']],
  read: 'Read down each column first, then across. The most useful comparison is card 3 against card 6: what each side is *doing*. Feelings can be misread; behaviour is what actually happens.',
  note: 'If cards 4–6 are all courts or all Cups, you are reading their temperament rather than their intent — consider a clarifier for what they intend to do.' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross — ten cards',
  when: 'A large, tangled situation that a three-card spread cannot hold. Do not use it as a default — ten cards on a simple question produce noise, not depth.',
  ask: 'One situation, broadly framed: "Show me what is happening with ___." The Celtic Cross answers a landscape, not a question.',
  pos: [['1 · The heart', 'The core of the matter as it stands.'],
        ['2 · Crossing', 'Laid across card 1. What complicates it — sometimes an obstacle, sometimes help you did not ask for.'],
        ['3 · Beneath', 'The root. What is underneath this and probably older than it.'],
        ['4 · Behind', 'What is passing out of the situation — recent past, still exerting a pull.'],
        ['5 · Above', 'What is in the open: the goal, the ideal, or what everyone can see.'],
        ['6 · Before', 'What is coming next, in the near term.'],
        ['7 · Yourself', 'How you are showing up in this — your stance, not your feelings.'],
        ['8 · Environment', 'Other people, and the conditions around you that you do not control.'],
        ['9 · Hopes and fears', 'Traditionally both at once, because they are usually the same card seen from two sides.'],
        ['10 · Outcome', 'Where this is heading, given everything above. Read it last, and read it against card 1.']],
  read: 'Read the cross (1–6) as the situation and the staff (7–10) as your relationship to it. If cards 1 and 10 tell the same story, the matter is settled. If they contradict each other, card 9 usually explains why.',
  note: 'Do not attempt this until three cards feel easy. Ten positions you half-remember are worse than three you know.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Clarifiers — one or two extra',
  when: 'A single position in a finished spread is genuinely unreadable, or a card has several branching meanings and you need to know which branch applies. This is a technique, not a spread.',
  ask: 'Point at the specific card and ask a specific question about it: "What does the Seven of Swords mean *here*?" Never "tell me something better."',
  pos: [['1 · Clarifier', 'Read this as an adjective attached to the original card, not as a new answer. It modifies; it does not replace.'],
        ['2 · Second clarifier', 'Only if the first genuinely did not land. Two is the limit.']],
  read: 'Say out loud, before drawing, what would count as an answer. That single habit is what separates clarifying from fishing.',
  note: 'Drawing until you like the answer is the most common way readers lose their own trust in the deck. Two clarifiers, then stop.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'A card of the day, or one very narrow question. Lenormand cards are nouns, so a single card gives you a subject with no sentence around it.',
  ask: 'Ask for a thing, not a feeling: "What is the day about?" A single Lenormand card names a topic and stops there.',
  pos: [['The subject', 'The noun. Take it literally first — Ship means travel or distance before it means anything symbolic.']],
  read: 'One card is the weakest Lenormand reading, because the whole system works by combination. If you can draw two instead, draw two.',
  note: 'Do not read Lenormand cards the way you read tarot. There is no reversal and no inner journey — the card is an object in your life.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Two cards — the pair',
  when: 'The fundamental unit of Lenormand, and the technique every larger spread is built from. Use it for one specific question with one specific answer.',
  ask: 'One narrow question. The pair gives you a noun and a modifier, so the answer arrives as a short phrase, not an essay.',
  pos: [['1 · The subject', 'The noun. This is what the answer is about.'],
        ['2 · The modifier', 'This describes card 1. Heart + Mountain is blocked love; Mountain + Heart is an obstacle to do with the heart — the order changes the meaning.']],
  read: 'Say the pair out loud as two words joined: "letter + coffin" becomes "bad news in writing." If you cannot say it in one short phrase, you are overthinking it.',
  note: 'This is the single most important habit in Lenormand: read pairs, always, before you read individual cards.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — the line',
  when: 'The everyday Lenormand reading. It answers a question with a full sentence and stays small enough to read cleanly.',
  ask: 'One clear question about one matter. Three cards is enough for a situation and its direction.',
  pos: [['1 · Subject', 'What the matter is. Often the person or thing you asked about.'],
        ['2 · Centre', 'The heart of the answer. In a three-card line the middle card carries the most weight, and it is also modified by both neighbours.'],
        ['3 · Direction', 'Where it is going, or what it results in.']],
  read: 'Read it three ways: as one sentence left to right; as the pair 1+2; and as the pair 2+3. Where all three readings agree, you have your answer. Where they disagree, card 2 decides.',
  note: 'Timing lives in the cards, not the positions — Rider is days, Ship is months, Anchor is lasting. A three-card line can answer "when" if a timing card lands in it.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Five cards — the line',
  when: 'A fuller answer to one question: background, the matter itself, and where it goes. The best all-purpose Lenormand spread once pairs feel natural.',
  ask: 'One question, asked more broadly than in a three-card line. Five cards can hold a cause and an outcome as well as the subject.',
  pos: [['1 · Background', 'What lies behind this — the past, or the setting the matter sits in.'],
        ['2 · What is developing', 'Read as a pair with card 1 and with card 3.'],
        ['3 · The centre', 'The core of the answer. Everything else in the line describes this card.'],
        ['4 · What is coming', 'Read as a pair with card 3 and with card 5.'],
        ['5 · Outcome', 'Where it lands.']],
  read: 'Read the centre first, then the pairs either side of it, then the two ends against each other. Cards 1 and 5 as a pair often give the shortest summary of the whole reading.',
  note: 'Where the Man or the Woman lands in the line matters: near the start they are the cause, near the end they are the result, and the direction they face shows what they are turned towards.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Yes / No — three cards',
  when: 'A closed question. Lenormand answers yes/no more comfortably than tarot does, because the cards carry a settled positive or negative tone.',
  ask: 'One closed question about one thing. Decide before drawing what a yes would actually look like in real life.',
  pos: [['1–3 · The tone', 'Count the positive against the negative cards. Two or three positive is yes; two or three negative is no. Neutral cards take their tone from the cards beside them.'],
        ['The strong yes', 'Key, Sun and Clover override the tally. Key especially is close to a definitive yes wherever it lands.'],
        ['The strong no', 'Coffin, Mountain, Scythe, Mice and Cross override it the other way. Mountain in particular means "not by this route."']],
  read: 'Give the answer, then read the three cards as a line to explain *why* — a Lenormand yes/no should always come with its reason attached.',
  note: 'Only nine negative cards and eight positive ones are agreed on by every source; the tone list in the Lenormand tab shows which, and which cards are argued over. Count the agreed ones and treat the rest as neutral. For a yes/no that explains itself, use the French Cross below.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Nine cards — the box',
  when: 'A full picture of one situation, without the commitment of a Grand Tableau. The standard "serious question" spread in Lenormand.',
  ask: 'One situation, asked broadly. Deal three rows of three, left to right, top to bottom.',
  pos: [['Centre (5)', 'The heart of the matter. Read this card first — everything else in the box modifies it.'],
        ['Top row (1–3)', 'What is above the situation: the past, or what is known and in the open.'],
        ['Middle row (4–6)', 'The present. The most important line in the box.'],
        ['Bottom row (7–9)', 'What is underneath or ahead: the outcome, or what is hidden.'],
        ['Columns', 'Left column is the past or the cause; centre column is the matter itself; right column is the future or the result.'],
        ['Diagonals', 'Both diagonals cross the centre card and describe hidden influences on it.'],
        ['Corners (1, 3, 7, 9)', 'Read the four corners together as a summary of the whole box.']],
  read: 'Work in this order: centre card, then the middle row, then the other rows, then the columns, then the diagonals, then the corners. Each pass should sharpen the same answer rather than produce a new one.',
  note: 'If a pass contradicts everything before it, you have started interpreting instead of reading. Go back to the centre card.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau — all 36',
  when: 'A whole-life reading, or a situation with many moving parts. The full Lenormand method, and the one that takes longest to learn.',
  ask: 'You do not ask a narrow question here. You lay the whole deck out and let it describe the landscape — then answer specific questions from within it.',
  pos: [['The layout', 'All 36 cards: four rows of eight, then a final row of four centred beneath. Deal left to right, top to bottom.'],
        ['Find the significator', 'Locate the Man or the Woman — whichever represents the person you are reading for. The reading is organised around where they landed.'],
        ['Near cards', 'The cards immediately touching the significator, including diagonals, are the most important in the whole spread. Read them first.'],
        ['Direction', 'What lies in front of the significator is ahead of them; what lies behind is past. Above is what is on their mind, below is what is grounding or weighing on them.'],
        ['Houses', 'Each of the 36 positions also carries the meaning of the card that "belongs" to it — position 24 is the House of the Heart, so whatever lands there speaks about love.'],
        ['Knighting', 'The cards a chess knight\'s move away from the significator carry hidden influences. Advanced; leave it until the rest is solid.'],
        ['Mirroring', 'Cards facing each other across a row, and cards directly above and below, comment on one another.']],
  read: 'Read in layers: significator and its neighbours, then its row, then the houses of whatever you were asked about, then the corners of the tableau. Answer one question at a time from the same layout rather than trying to read all 36 cards in order.',
  note: 'Do not start here. Work through pairs, three-card lines and the nine-card box first — the Grand Tableau is those same techniques applied thirty-six times.' }

];

/* ============================ Vietnamese ============================ */

SPREADS.vi = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Dùng cho bài tập mỗi sáng, hoặc cho một câu hỏi nhỏ, trả lời được trong một câu. Cũng dùng khi bạn đã luận xong một trải bài lớn mà còn thiếu một ý.',
  ask: 'Hỏi kiểu "Hôm nay mình cần biết gì về chuyện ___?". Một lá trả lời tốt câu hỏi "chuyện gì", trả lời kém câu hỏi "có nên không", và gần như không trả lời được câu hỏi "khi nào".',
  pos: [['Câu trả lời', 'Cả trải bài nằm ở lá này. Nhìn hình trước và để ý xem điều gì đập vào mắt bạn, rồi mới đọc từ khoá, sau cùng mới đọc nghĩa xuôi hay ngược.']],
  read: 'Đọc theo ba bước: hình ảnh, từ khoá, nghĩa. Nếu thấy lá bài "không nói gì", thường là do câu hỏi còn mơ hồ. Hãy hỏi lại cho rõ, đừng rút lá khác.',
  note: 'Không rút lại chỉ vì không thích câu trả lời. Nếu thật sự cần thêm, rút một lá làm rõ, và tự nhắc mình rằng đó là lá làm rõ chứ không phải lá thay thế.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá — tình huống, hành động, kết quả',
  when: 'Trải bài dùng hằng ngày. Hợp với mọi chuyện bạn muốn biết ba điều: đang thế nào, nên làm gì, và sẽ đi tới đâu. Không biết chọn trải bài nào thì chọn cái này.',
  ask: 'Hỏi kiểu "Chuyện ___ đang thế nào, mình nên làm gì, rồi sẽ ra sao?". Một chuyện, ba góc nhìn.',
  pos: [['1 · Tình huống', 'Chuyện đang thật sự diễn ra, không phải điều bạn sợ hay mong. Nếu lá Ẩn Chính rơi vào đây, chuyện lớn hơn câu hỏi bạn đặt.'],
        ['2 · Việc nên làm', 'Phần thuộc về bạn. Đọc lá này như một lời khuyên để làm theo, không phải một lời tiên đoán.'],
        ['3 · Kết quả', 'Nếu bạn làm theo lá 2 thì chuyện sẽ đi tới đây. Đây là hướng đi, không phải số phận đã định.']],
  read: 'Bước 1: đọc ba lá từ trái sang phải như một câu chuyện ngắn. Bước 2: nhìn cả ba lá cùng lúc. Nhiều lá Ẩn Chính: chuyện không hoàn toàn nằm trong tay bạn. Ba lá cùng một chất: chuyện nằm trọn trong lĩnh vực của chất đó (Cốc là tình cảm, Tiền là tiền bạc, Gậy là hành động, Kiếm là suy nghĩ).',
  note: 'Lá 3 là kết quả "nếu bạn làm theo lá 2". Vì vậy lá 2 mới là lá đáng làm theo nhất.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Có / Không — năm lá',
  when: 'Chỉ dùng khi câu hỏi thật sự chỉ có hai đáp án. Đừng lạm dụng: phần lớn câu hỏi hay không phải câu hỏi có/không.',
  ask: 'Câu hỏi phải trả lời được bằng có hoặc không, và chỉ hỏi một chuyện. "Tuần này anh ấy có nhắn tin không?" là được. "Anh ấy có nhắn không, và có yêu mình không?" là hai câu hỏi.',
  pos: [['1–5 · Đếm', 'Lật năm lá thành một hàng. Đếm lá xuôi và lá ngược: từ ba lá xuôi trở lên là có, từ ba lá ngược trở lên là không. Năm lá cùng chiều là câu trả lời rất rõ.'],
        ['Lá Ẩn Chính', 'Lá Ẩn Chính trong hàng tính gấp đôi. Nó cũng cho biết chuyện này có phần không nằm trong tay con người.'],
        ['Lá giữa', 'Lá 3 là trọng tâm. Kể cả khi đếm ra là "có", lá 3 cho biết đó là kiểu "có" như thế nào: có ngay, có nhưng chậm, hay có kèm điều kiện.'],
        ['Chất bài', 'Hàng nghiêng về chất nào thì lĩnh vực đó quyết định: Cốc là cảm xúc, Kiếm là lời nói, Tiền là thực tế, Gậy là có ai chịu hành động hay không.']],
  read: 'Bước 1: nói kết quả đếm (có hay không). Bước 2: giải thích ngay bằng lá 3 và chất bài chiếm đa số. Một chữ "có" hay "không" mà không giải thích thì chỉ như tung đồng xu.',
  note: 'Cách này cần lá ngược. Nếu bạn không đọc lá ngược, hãy dùng trải bài ba lá và trả lời câu hỏi bằng ý nghĩa của bài.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Thời điểm — bốn giai đoạn',
  when: 'Khi câu hỏi là "bao giờ". Tarot gọi tên ngày tháng rất kém nhưng mô tả trình tự rất tốt, nên trải bài này hỏi "mỗi giai đoạn có gì" thay vì "ngày nào".',
  ask: 'Chốt đơn vị thời gian trước khi xào bài, và nói ra thành lời: bốn tuần, bốn tháng, hay bốn quý. Thấy bài rồi mới đổi đơn vị là trải bài mất ý nghĩa.',
  pos: [['1 · Giai đoạn một', 'Khoảng thời gian đầu có gì. Nếu điều bạn hỏi xuất hiện ngay ở đây, nó đang rất gần.'],
        ['2 · Giai đoạn hai', 'Khoảng tiếp theo. Để ý các lá chuyển động: Gậy, Kỵ Sĩ, Cỗ Xe, Bánh Xe. Chúng cho thấy chuyện đang dịch chuyển.'],
        ['3 · Giai đoạn ba', 'Khoảng sau đó. Nếu toàn lá đứng yên (các lá Bốn, Người Treo Ngược, Bảy Tiền), bạn phải chờ lâu hơn mong đợi.'],
        ['4 · Giai đoạn bốn', 'Cuối khung thời gian. Nếu tới đây vẫn chưa thấy điều bạn hỏi, câu trả lời thật là "chưa xảy ra trong khung này". Hãy nói thẳng như vậy.']],
  read: 'Tìm lá trả lời đúng câu hỏi của bạn, rồi xem nó nằm ở giai đoạn nào: đó là thời điểm. Nếu không lá nào trả lời, sự việc chưa nằm trong khung này. Nói thật điều đó tốt hơn đoán một ngày cho vui lòng.',
  note: 'Không bao giờ hứa một ngày cụ thể. Chỉ đưa giai đoạn và điều kiện, và nói rõ rằng thời điểm là phần tarot đoán kém nhất.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Hai con đường — một quyết định',
  when: 'Khi bạn thật sự phải chọn một trong hai: hai công việc, ở lại hay rời đi, nói ra hay im lặng. Trải bài này so sánh hai tương lai, không đoán một tương lai.',
  ask: 'Gọi tên hai phương án trước khi xào bài, và quy định trước: nhánh trái là phương án nào, nhánh phải là phương án nào. Không được thấy bài rồi mới gán.',
  pos: [['1 · Bạn lúc này', 'Bạn đang đứng ở đâu, và thật ra bạn đang chọn giữa điều gì. Nhiều khi không giống điều bạn nói ra.'],
        ['2 · Đường A, bước đầu', 'Chuyện xảy ra ngay sau khi bạn chọn phương án thứ nhất.'],
        ['3 · Đường A, về sau', 'Con đường đó dẫn tới đâu. Đọc chung với lá 2 như một mạch.'],
        ['4 · Đường B, bước đầu', 'Chuyện xảy ra ngay sau khi bạn chọn phương án thứ hai.'],
        ['5 · Đường B, về sau', 'Con đường đó dẫn tới đâu.']],
  read: 'So sánh theo từng nhánh (lá 2+3 với lá 4+5), đừng so bốn lá rời rạc. Câu hỏi hay không phải "nhánh nào dễ chịu hơn" mà là "nhánh nào nói thật về cái giá phải trả". Một con đường khó lúc đầu nhưng kết thúc đẹp thường tốt hơn con đường êm lúc đầu.',
  note: 'Bài không chọn thay bạn. Bài chỉ mô tả hai tương lai; quyết định vẫn là của bạn.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Hai phía — mối quan hệ',
  when: 'Cho mọi chuyện giữa hai người mà bạn cần nhìn riêng từng phía: một cặp đôi, một mối mập mờ, một lần giận nhau, cả quan hệ đồng nghiệp. Trải bài này không cho phép trộn hai người làm một.',
  ask: 'Quy định trước ai ở cột trái, ai ở cột phải, rồi mới xào bài. Cột trái thường là người hỏi.',
  pos: [['1 · Bạn: cảm thấy', 'Điều bạn thật sự cảm thấy, bên dưới điều bạn nói ra.'],
        ['2 · Bạn: nghĩ', 'Điều bạn tự nói với mình về chuyện này. Thường lệch với lá 1, và chỗ lệch đó chính là điều đáng đọc.'],
        ['3 · Bạn: làm', 'Bạn đang cư xử thế nào trên thực tế, tức là phần người kia nhìn thấy.'],
        ['4 · Họ: cảm thấy', 'Họ cảm thấy gì. Đọc thẳng, đừng làm nhẹ đi chỉ vì người hỏi đang ngồi trước mặt.'],
        ['5 · Họ: nghĩ', 'Họ đang tự lý giải chuyện này ra sao.'],
        ['6 · Họ: làm', 'Họ đang thật sự làm gì. Đây là phần duy nhất có bằng chứng.'],
        ['7 · Giữa hai người', 'Chính mối quan hệ, như một thứ thứ ba: phần chung của hai người, hoặc thứ đang chắn giữa.']],
  read: 'Bước 1: đọc từng cột từ trên xuống (bạn, rồi họ). Bước 2: đọc ngang, so từng cặp. Cặp đáng so nhất là lá 3 và lá 6: mỗi bên đang làm gì. Cảm xúc dễ đọc sai, hành động mới là thứ thật.',
  note: 'Nếu ba lá 4, 5, 6 toàn lá Hoàng gia hoặc toàn Cốc, bạn mới thấy tính cách của họ chứ chưa thấy ý định. Rút thêm một lá làm rõ: "họ định làm gì?".' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross — mười lá',
  when: 'Cho một chuyện lớn và rối mà ba lá không chứa nổi. Đừng dùng làm mặc định: mười lá cho một câu hỏi nhỏ chỉ thêm nhiễu, không thêm sâu.',
  ask: 'Đặt câu hỏi rộng về một tình huống: "Cho mình thấy chuyện ___ đang diễn ra thế nào". Celtic Cross vẽ một bức tranh, không trả lời một câu ngắn.',
  pos: [['1 · Trọng tâm', 'Cốt lõi của chuyện, như nó đang là.'],
        ['2 · Lá cắt ngang', 'Đặt nằm ngang trên lá 1. Điều làm chuyện rối thêm: có khi là trở ngại, có khi là sự giúp đỡ bạn không ngờ.'],
        ['3 · Bên dưới', 'Gốc rễ. Điều nằm dưới chuyện này, và thường có từ trước.'],
        ['4 · Phía sau', 'Điều đang lùi dần: quá khứ gần, vẫn còn níu bạn.'],
        ['5 · Bên trên', 'Điều ở ngoài sáng: mục tiêu, mong muốn, hoặc điều ai cũng thấy.'],
        ['6 · Phía trước', 'Điều sắp tới, trong thời gian gần.'],
        ['7 · Chính bạn', 'Bạn đang xuất hiện thế nào trong chuyện này: tư thế của bạn, không phải cảm xúc.'],
        ['8 · Xung quanh', 'Người khác, và hoàn cảnh quanh bạn mà bạn không kiểm soát được.'],
        ['9 · Hy vọng và nỗi sợ', 'Cả hai cùng lúc, vì thường điều ta mong và điều ta sợ là một.'],
        ['10 · Kết quả', 'Chuyện đang đi tới đâu, xét tất cả những lá trên. Đọc sau cùng, và so với lá 1.']],
  read: 'Bước 1: đọc sáu lá chữ thập (1 đến 6) như tình huống. Bước 2: đọc bốn lá cột dọc (7 đến 10) như cách bạn đứng trong tình huống đó. Bước 3: so lá 1 với lá 10. Cùng một câu chuyện: chuyện đã rõ. Mâu thuẫn: nhìn lá 9, nó thường giải thích vì sao.',
  note: 'Chỉ dùng khi ba lá đã thành thạo. Mười vị trí nhớ lơ mơ tệ hơn ba vị trí nắm chắc.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Lá làm rõ — rút thêm một hoặc hai',
  when: 'Khi một vị trí trong trải bài đã xong mà bạn thật sự không hiểu, hoặc một lá có nhiều nghĩa và bạn cần biết nghĩa nào đang đúng. Đây là một kỹ thuật, không phải một trải bài riêng.',
  ask: 'Chỉ đúng vào lá đó và hỏi cụ thể: "Bảy Kiếm ở vị trí này nghĩa là gì?". Đừng hỏi "cho mình một câu trả lời đẹp hơn".',
  pos: [['1 · Lá làm rõ', 'Đọc lá này như một tính từ gắn thêm vào lá gốc, không phải một câu trả lời mới. Nó bổ nghĩa, không thay thế.'],
        ['2 · Lá làm rõ thứ hai', 'Chỉ rút khi lá đầu vẫn chưa giúp gì. Hai là giới hạn.']],
  read: 'Trước khi rút, nói ra thành lời: "thế nào thì mình coi là đã rõ". Thói quen nhỏ này giúp bạn phân biệt "làm rõ" với "rút bừa cho tới khi vừa ý".',
  note: 'Rút mãi cho tới khi thích câu trả lời là cách nhanh nhất để mất niềm tin vào bộ bài của mình. Tối đa hai lá làm rõ, rồi dừng.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Lá của ngày, hoặc một câu hỏi rất hẹp. Lá Lenormand là một danh từ, nên một lá chỉ cho bạn chủ đề, chưa có câu chuyện.',
  ask: 'Hỏi về một chuyện cụ thể, không hỏi về cảm giác: "Hôm nay xoay quanh chuyện gì?". Một lá Lenormand gọi tên chủ đề rồi dừng.',
  pos: [['Chủ đề', 'Một danh từ. Hiểu theo nghĩa đen trước: Con Thuyền là đi xa hay khoảng cách, rồi mới nghĩ tới nghĩa bóng.']],
  read: 'Một lá là cách đọc Lenormand yếu nhất, vì hệ thống này sống bằng sự kết hợp giữa các lá. Nếu rút được hai lá, hãy rút hai.',
  note: 'Đừng đọc Lenormand như tarot. Không có lá ngược, không có hành trình nội tâm. Mỗi lá là một vật, một chuyện trong đời bạn.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Hai lá — cặp bài',
  when: 'Đơn vị cơ bản của Lenormand, và là kỹ thuật mà mọi trải bài lớn hơn đều xây từ đó. Dùng cho một câu hỏi cụ thể cần một câu trả lời cụ thể.',
  ask: 'Một câu hỏi hẹp. Cặp bài cho bạn một danh từ và một từ bổ nghĩa, nên câu trả lời là một cụm ngắn, không phải một bài dài.',
  pos: [['1 · Chủ đề', 'Danh từ. Câu trả lời nói về thứ này.'],
        ['2 · Bổ nghĩa', 'Lá này mô tả lá 1. Trái Tim + Ngọn Núi là tình yêu bị chặn; Ngọn Núi + Trái Tim là một trở ngại liên quan tới tình cảm. Đổi thứ tự là đổi nghĩa.']],
  read: 'Nói to cặp bài thành một cụm: "Lá Thư + Quan Tài" thành "tin buồn bằng văn bản". Nếu không nói được trong một cụm ngắn, bạn đang nghĩ quá nhiều.',
  note: 'Thói quen quan trọng nhất trong Lenormand: luôn đọc theo cặp trước, rồi mới đọc từng lá.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá — hàng ngang',
  when: 'Cách đọc Lenormand dùng hằng ngày. Trả lời một câu hỏi bằng một câu hoàn chỉnh mà vẫn đủ gọn.',
  ask: 'Một câu hỏi rõ về một chuyện. Ba lá đủ cho tình huống và hướng đi của nó.',
  pos: [['1 · Chủ đề', 'Chuyện là gì. Thường là người hoặc việc bạn đang hỏi.'],
        ['2 · Lá giữa', 'Trọng tâm của câu trả lời. Trong hàng ba lá, lá giữa nặng nhất và được cả hai lá bên cạnh bổ nghĩa.'],
        ['3 · Hướng đi', 'Chuyện đi tới đâu, hoặc dẫn tới kết quả gì.']],
  read: 'Đọc ba lần: lần một, cả hàng như một câu từ trái sang phải; lần hai, cặp 1+2; lần ba, cặp 2+3. Ba cách đọc cùng nói một ý thì đó là câu trả lời. Chúng khác nhau thì lá 2 quyết định.',
  note: 'Thời gian nằm ở lá bài, không nằm ở vị trí: Kỵ Mã là vài ngày, Con Thuyền là vài tháng, Mỏ Neo là lâu dài. Hàng ba lá vẫn trả lời được "khi nào" nếu có lá chỉ thời gian.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Năm lá — hàng ngang',
  when: 'Câu trả lời đầy đủ hơn cho một câu hỏi: bối cảnh, chính sự việc, và kết quả. Trải bài đa dụng tốt nhất của Lenormand, khi bạn đã đọc cặp thành thạo.',
  ask: 'Một câu hỏi, đặt rộng hơn hàng ba lá một chút. Năm lá chứa được cả nguyên nhân lẫn kết quả.',
  pos: [['1 · Bối cảnh', 'Điều nằm phía sau: quá khứ, hoặc hoàn cảnh của chuyện.'],
        ['2 · Đang hình thành', 'Đọc thành cặp với lá 1 và với lá 3.'],
        ['3 · Trung tâm', 'Cốt lõi của câu trả lời. Các lá còn lại đều mô tả lá này.'],
        ['4 · Sắp tới', 'Đọc thành cặp với lá 3 và với lá 5.'],
        ['5 · Kết quả', 'Chuyện dừng lại ở đâu.']],
  read: 'Bước 1: đọc lá giữa. Bước 2: đọc hai cặp hai bên (2+3 và 3+4). Bước 3: so hai đầu hàng (lá 1 và lá 5): cặp này thường là bản tóm tắt ngắn nhất của cả trải bài.',
  note: 'Để ý lá Quý Ông hoặc Quý Bà rơi vào đâu: gần đầu hàng thì người đó là nguyên nhân, gần cuối hàng thì là kết quả, và hướng họ quay mặt cho biết họ đang hướng về điều gì.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Có / Không — ba lá',
  when: 'Cho câu hỏi đóng. Lenormand trả lời có/không dễ hơn tarot, vì mỗi lá đã mang sẵn sắc thái tốt hoặc xấu.',
  ask: 'Một câu hỏi đóng về một chuyện. Trước khi rút, hình dung xem "có" trên thực tế sẽ trông thế nào.',
  pos: [['1–3 · Sắc thái', 'Đếm lá tốt và lá xấu. Hai hoặc ba lá tốt là có; hai hoặc ba lá xấu là không. Lá trung tính lấy sắc thái từ lá bên cạnh.'],
        ['"Có" mạnh', 'Chìa Khoá, Mặt Trời, Cỏ Ba Lá mạnh hơn phép đếm. Riêng Chìa Khoá gần như là "có" chắc chắn, dù rơi ở đâu.'],
        ['"Không" mạnh', 'Quan Tài, Ngọn Núi, Lưỡi Hái, Đàn Chuột, Thánh Giá mạnh hơn phép đếm theo chiều ngược lại. Riêng Ngọn Núi nghĩa là "không phải bằng đường này".']],
  read: 'Bước 1: nói câu trả lời. Bước 2: đọc ba lá như một hàng để giải thích vì sao. Trong Lenormand, có hay không luôn đi kèm lý do.',
  note: 'Chỉ chín lá xấu và tám lá tốt là mọi sách đều đồng ý; bảng sắc thái trong tab Lenormand cho biết đó là những lá nào. Đếm những lá đã thống nhất, coi phần còn lại là trung tính.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Chín lá — ô vuông',
  when: 'Bức tranh đầy đủ về một chuyện mà không cần trải cả Grand Tableau. Đây là trải bài "câu hỏi nghiêm túc" tiêu chuẩn của Lenormand.',
  ask: 'Một chuyện, hỏi rộng. Rải ba hàng, mỗi hàng ba lá, từ trái sang phải, từ trên xuống dưới.',
  pos: [['Lá giữa (5)', 'Trọng tâm. Đọc lá này trước; mọi lá khác đều bổ nghĩa cho nó.'],
        ['Hàng trên (1–3)', 'Điều bao trùm: quá khứ, hoặc những gì đã biết.'],
        ['Hàng giữa (4–6)', 'Hiện tại. Hàng quan trọng nhất.'],
        ['Hàng dưới (7–9)', 'Điều bên dưới hoặc phía trước: kết quả, hoặc những gì còn ẩn.'],
        ['Các cột', 'Cột trái là quá khứ hoặc nguyên nhân; cột giữa là chính sự việc; cột phải là tương lai hoặc kết quả.'],
        ['Hai đường chéo', 'Đều đi qua lá giữa; mô tả những ảnh hưởng ngầm.'],
        ['Bốn góc (1, 3, 7, 9)', 'Đọc chung như bản tóm tắt của cả ô.']],
  read: 'Đọc theo thứ tự: lá giữa, hàng giữa, hai hàng còn lại, ba cột, hai đường chéo, bốn góc. Mỗi lượt đọc phải làm rõ thêm cùng một câu trả lời, không tạo ra câu trả lời mới.',
  note: 'Nếu một lượt đọc mâu thuẫn với tất cả lượt trước, bạn đang suy diễn chứ không còn đọc bài. Quay lại lá giữa.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau — cả 36 lá',
  when: 'Trải bài tổng quan cả cuộc sống, hoặc một chuyện có rất nhiều phần. Đây là phương pháp Lenormand đầy đủ nhất, và cũng lâu học nhất.',
  ask: 'Không hỏi một câu hẹp. Trải cả bộ bài để nó mô tả toàn cảnh, rồi trả lời từng câu hỏi cụ thể từ bức tranh đó.',
  pos: [['Cách bày', 'Cả 36 lá: bốn hàng tám lá, và một hàng cuối bốn lá đặt giữa bên dưới. Rải từ trái sang phải, từ trên xuống dưới.'],
        ['Tìm lá đại diện', 'Tìm lá Quý Ông hoặc Quý Bà, tuỳ người bạn đang xem. Cả trải bài xoay quanh vị trí của lá này.'],
        ['Các lá kề', 'Những lá chạm vào lá đại diện, kể cả theo đường chéo, là quan trọng nhất. Đọc chúng trước.'],
        ['Trước và sau', 'Lá phía trước lá đại diện là điều sắp tới; phía sau là quá khứ. Bên trên là điều đang bận tâm; bên dưới là điều đang nâng đỡ hoặc đè nặng.'],
        ['Các "ngôi nhà"', 'Mỗi vị trí trong 36 ô còn mang nghĩa của lá bài số đó. Ô 24 là nhà của Trái Tim, nên lá nào rơi vào đó cũng nói về tình cảm.'],
        ['Bước mã', 'Những lá cách lá đại diện đúng một bước đi của quân mã (cờ vua) mang ảnh hưởng ngầm. Kỹ thuật nâng cao, để dành sau.'],
        ['Soi chiếu', 'Các lá đối xứng nhau trong một hàng, và các lá nằm ngay trên và dưới nhau, bổ nghĩa cho nhau.']],
  read: 'Đọc theo lớp: lá đại diện và các lá kề, rồi hàng của nó, rồi ngôi nhà của chủ đề bạn hỏi, rồi bốn góc bảng. Trả lời từng câu hỏi từ cùng một bức tranh, đừng cố đọc lần lượt 36 lá.',
  note: 'Đừng bắt đầu từ đây. Học cặp bài, hàng ba lá và ô chín lá trước; Grand Tableau chỉ là những kỹ thuật đó lặp lại 36 lần.' }

];
