/* ============================ spreads ============================ */
/* How many cards to draw for which kind of question, where each card goes, and
   what each position means.
   `lay` is a list of [col, row] grid slots -- and optionally a third entry 'r'
   for a card laid crosswise. The renderer turns that into a diagram, so a
   layout is described once and drawn identically in both languages.
   `kinds` drives the question-type filter. `sys` keeps the two systems apart. */

const SPREADS = { en: [], vi: [] };

/* ---- shared geometry, so both languages draw the same picture ---- */
const LAY = {
  one:    [[0, 0]],
  two:    [[0, 0], [1, 0]],
  three:  [[0, 0], [1, 0], [2, 0]],
  four:   [[0, 0], [1, 0], [2, 0], [3, 0]],
  five:   [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]],
  choice: [[1, 0], [0, 1], [0, 2], [2, 1], [2, 2]],
  rel7:   [[0, 0], [0, 1], [0, 2], [2, 0], [2, 1], [2, 2], [1, 1]],
  celtic: [[1, 1], [1, 1, 'r'], [1, 2], [0, 1], [1, 0], [2, 1], [3, 3], [3, 2], [3, 1], [3, 0]],
  box9:   [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2]],
  gt:     (function () {
    const a = [];
    for (let r = 0; r < 4; r++) for (let c = 0; c < 8; c++) a.push([c, r]);
    for (let c = 2; c < 6; c++) a.push([c, 4]);
    return a;
  }())
};

/* ============================ English ============================ */

SPREADS.en = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'Daily practice, and any question small enough to answer in a sentence. Also the right size when you have already read a spread and just need one more piece of information.',
  ask: '"What do I most need to know about ___ today?" Keep it open. A single card answers a *what*, badly answers a *should I*, and cannot answer a *when*.',
  pos: [['The answer', 'The whole reading. Read the image first and what you notice about it, then the keywords, then the upright or reversed meaning. Do not reach for a second card to soften the first one.']],
  read: 'One card is not a lesser reading — it is a more disciplined one. If the card seems to say nothing, the usual cause is that the question was too vague to be answered.',
  note: 'Never re-draw because you did not like the answer. If you genuinely need more, draw a clarifier and say out loud that that is what you are doing.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — situation, action, outcome',
  when: 'The everyday workhorse. Any question where you want to know what is going on, what to do about it, and where it leads. This is the spread to reach for when you are unsure which spread to use.',
  ask: '"Where does ___ stand, what should I do, and where does that lead?" One subject, three angles.',
  pos: [['1 · Situation', 'What is actually happening now — not what you fear or hope. If a Major lands here, the matter is bigger than the question you asked.'],
        ['2 · Action', 'What is yours to do. This position is advice, so read it as an instruction rather than a prediction.'],
        ['3 · Outcome', 'Where the current path leads *if the advice in position 2 is followed*. It is a projection, not a fixed fate.']],
  read: 'Read left to right as a sentence. Then check the balance across all three: heavy Majors mean the situation is not fully in your hands; all Minors of one suit means the whole matter lives in that one area of life.',
  note: 'Position 3 answers "if nothing changes." That is what makes position 2 worth acting on.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Yes / No — five cards',
  when: 'A genuine closed question with two possible answers. Use it sparingly: most questions worth asking are not yes/no questions, and forcing them into this shape wastes the reading.',
  ask: 'The question must be answerable with yes or no, and must be about one thing. "Will he text me this week?" works. "Will he text me and does he love me?" does not.',
  pos: [['1–5 · The tally', 'Deal five cards face up in a row. Count upright against reversed: three or more upright is yes, three or more reversed is no. Five to nothing in either direction is emphatic.'],
        ['The Majors', 'Any Major Arcana in the row carries double weight in the count — the matter is not entirely in human hands.'],
        ['The middle card', 'Card 3 is the heart of the answer. Even when the tally says yes, this card tells you what kind of yes it is.'],
        ['The suits', 'A row dominated by one suit tells you which area actually decides the outcome — Cups for feeling, Swords for what is said, Pentacles for practical reality, Wands for whether anyone acts.']],
  read: 'Give the tally first, then immediately explain it using card 3 and the suit balance. A bare yes or no is not a reading; it is a coin toss with pictures.',
  note: 'If you do not read reversals, this method does not work. Use the three-card spread instead and answer the question from the meaning.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Timing — four periods',
  when: '"When will it happen?" Tarot is poor at naming dates and good at describing sequence, so this spread asks *what happens in each period* rather than *which date*.',
  ask: 'Decide the unit before you shuffle and say it out loud: four weeks, or four months, or four quarters. Changing the unit after you see the cards is how readings become meaningless.',
  pos: [['1 · First period', 'What this stretch of time holds. If the thing you asked about appears here, it is close.'],
        ['2 · Second period', 'The next stretch. Watch for movement cards — Wands, Knights, the Chariot, the Wheel — which show things actually shifting.'],
        ['3 · Third period', 'The stretch after that. A run of stillness here (Fours, the Hanged Man, Seven of Pentacles) means the wait is longer than hoped.'],
        ['4 · Fourth period', 'The end of the window you asked about. If nothing has arrived by here, the honest answer is "not within this window" — say so.']],
  read: 'Find the card that answers the question and read the position it landed in. That is the timing. If no card answers it, the honest reading is that the event is not in this window, and the client is better served by hearing that than by a comforting guess.',
  note: 'Never promise a date. Give the period, give the conditions, and say plainly that timing is the least reliable thing tarot does.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Two roads — a decision',
  when: 'A real either/or: two jobs, stay or leave, tell them or say nothing. It compares two futures instead of predicting one.',
  ask: 'Name both options out loud before you shuffle, and assign one to the left branch and one to the right. Do not decide which is which after seeing the cards.',
  pos: [['1 · You now', 'Where you stand, and what you are actually deciding between — which is often not what you said it was.'],
        ['2 · Road A, first step', 'What immediately follows if you take the first option.'],
        ['3 · Road A, where it leads', 'Where that road arrives. Read it together with card 2 as one movement.'],
        ['4 · Road B, first step', 'What immediately follows if you take the second option.'],
        ['5 · Road B, where it leads', 'Where that road arrives.']],
  read: 'Compare the two branches as pairs, not as four separate cards. The cleaner reading is usually not "which branch is nicer" but "which branch is honest about its cost" — a road with a hard first step and a good end often beats an easy start.',
  note: 'The cards do not choose. They describe two futures; the decision stays with the person who asked.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Two sides — the relationship',
  when: 'Any two-person question where you need both sides separately: a couple, a situationship, a falling-out, even a working relationship. Its strength is that it refuses to blend the two people together.',
  ask: 'Name who is on the left and who is on the right before shuffling. The left column is usually the person asking.',
  pos: [['1 · You: feeling', 'What you actually feel, underneath what you say you feel.'],
        ['2 · You: thinking', 'What you tell yourself about this. Often at odds with card 1, and that gap is the reading.'],
        ['3 · You: doing', 'How you are actually behaving — what the other person sees.'],
        ['4 · Them: feeling', 'What they feel. Read it plainly; do not soften it because the person asking is in the room.'],
        ['5 · Them: thinking', 'How they are framing this to themselves.'],
        ['6 · Them: doing', 'What they are actually doing, which is the only part you have evidence for.'],
        ['7 · Between you', 'The relationship itself as a third thing — the shared ground, or what stands in it.']],
  read: 'Read down each column first, then across. The most useful comparison is card 3 against card 6: what each side is *doing*. Feelings can be misread; behaviour is what actually happens.',
  note: 'If cards 4–6 are all courts or all Cups, you are reading their temperament rather than their intent — consider a clarifier for what they intend to do.' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross — ten cards',
  when: 'A large, tangled situation that a three-card spread cannot hold. Do not use it as a default — ten cards on a simple question produce noise, not depth.',
  ask: 'One situation, broadly framed: "Show me what is happening with ___." The Celtic Cross answers a landscape, not a question.',
  pos: [['1 · The heart', 'The core of the matter as it stands.'],
        ['2 · Crossing', 'Laid across card 1. What complicates it — sometimes an obstacle, sometimes help you did not ask for.'],
        ['3 · Beneath', 'The root. What is underneath this and probably older than it.'],
        ['4 · Behind', 'What is passing out of the situation — recent past, still exerting a pull.'],
        ['5 · Above', 'What is in the open: the goal, the ideal, or what everyone can see.'],
        ['6 · Before', 'What is coming next, in the near term.'],
        ['7 · Yourself', 'How you are showing up in this — your stance, not your feelings.'],
        ['8 · Environment', 'Other people, and the conditions around you that you do not control.'],
        ['9 · Hopes and fears', 'Traditionally both at once, because they are usually the same card seen from two sides.'],
        ['10 · Outcome', 'Where this is heading, given everything above. Read it last, and read it against card 1.']],
  read: 'Read the cross (1–6) as the situation and the staff (7–10) as your relationship to it. If cards 1 and 10 tell the same story, the matter is settled. If they contradict each other, card 9 usually explains why.',
  note: 'Do not attempt this until three cards feel easy. Ten positions you half-remember are worse than three you know.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Clarifiers — one or two extra',
  when: 'A single position in a finished spread is genuinely unreadable, or a card has several branching meanings and you need to know which branch applies. This is a technique, not a spread.',
  ask: 'Point at the specific card and ask a specific question about it: "What does the Seven of Swords mean *here*?" Never "tell me something better."',
  pos: [['1 · Clarifier', 'Read this as an adjective attached to the original card, not as a new answer. It modifies; it does not replace.'],
        ['2 · Second clarifier', 'Only if the first genuinely did not land. Two is the limit.']],
  read: 'Say out loud, before drawing, what would count as an answer. That single habit is what separates clarifying from fishing.',
  note: 'Drawing until you like the answer is the most common way readers lose their own trust in the deck. Two clarifiers, then stop.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'A card of the day, or one very narrow question. Lenormand cards are nouns, so a single card gives you a subject with no sentence around it.',
  ask: 'Ask for a thing, not a feeling: "What is the day about?" A single Lenormand card names a topic and stops there.',
  pos: [['The subject', 'The noun. Take it literally first — Ship means travel or distance before it means anything symbolic.']],
  read: 'One card is the weakest Lenormand reading, because the whole system works by combination. If you can draw two instead, draw two.',
  note: 'Do not read Lenormand cards the way you read tarot. There is no reversal and no inner journey — the card is an object in your life.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Two cards — the pair',
  when: 'The fundamental unit of Lenormand, and the technique every larger spread is built from. Use it for one specific question with one specific answer.',
  ask: 'One narrow question. The pair gives you a noun and a modifier, so the answer arrives as a short phrase, not an essay.',
  pos: [['1 · The subject', 'The noun. This is what the answer is about.'],
        ['2 · The modifier', 'This describes card 1. Heart + Mountain is blocked love; Mountain + Heart is an obstacle to do with the heart — the order changes the meaning.']],
  read: 'Say the pair out loud as two words joined: "letter + coffin" becomes "bad news in writing." If you cannot say it in one short phrase, you are overthinking it.',
  note: 'This is the single most important habit in Lenormand: read pairs, always, before you read individual cards.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — the line',
  when: 'The everyday Lenormand reading. It answers a question with a full sentence and stays small enough to read cleanly.',
  ask: 'One clear question about one matter. Three cards is enough for a situation and its direction.',
  pos: [['1 · Subject', 'What the matter is. Often the person or thing you asked about.'],
        ['2 · Centre', 'The heart of the answer. In a three-card line the middle card carries the most weight, and it is also modified by both neighbours.'],
        ['3 · Direction', 'Where it is going, or what it results in.']],
  read: 'Read it three ways: as one sentence left to right; as the pair 1+2; and as the pair 2+3. Where all three readings agree, you have your answer. Where they disagree, card 2 decides.',
  note: 'Timing lives in the cards, not the positions — Rider is days, Ship is months, Anchor is lasting. A three-card line can answer "when" if a timing card lands in it.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Five cards — the line',
  when: 'A fuller answer to one question: background, the matter itself, and where it goes. The best all-purpose Lenormand spread once pairs feel natural.',
  ask: 'One question, asked more broadly than in a three-card line. Five cards can hold a cause and an outcome as well as the subject.',
  pos: [['1 · Background', 'What lies behind this — the past, or the setting the matter sits in.'],
        ['2 · What is developing', 'Read as a pair with card 1 and with card 3.'],
        ['3 · The centre', 'The core of the answer. Everything else in the line describes this card.'],
        ['4 · What is coming', 'Read as a pair with card 3 and with card 5.'],
        ['5 · Outcome', 'Where it lands.']],
  read: 'Read the centre first, then the pairs either side of it, then the two ends against each other. Cards 1 and 5 as a pair often give the shortest summary of the whole reading.',
  note: 'Where the Man or the Woman lands in the line matters: near the start they are the cause, near the end they are the result, and the direction they face shows what they are turned towards.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Yes / No — three cards',
  when: 'A closed question. Lenormand answers yes/no more comfortably than tarot does, because the cards carry a settled positive or negative tone.',
  ask: 'One closed question about one thing. Decide before drawing what a yes would actually look like in real life.',
  pos: [['1–3 · The tone', 'Count the positive against the negative cards. Two or three positive is yes; two or three negative is no. Neutral cards take their tone from the cards beside them.'],
        ['The strong yes', 'Key, Sun and Clover override the tally. Key especially is close to a definitive yes wherever it lands.'],
        ['The strong no', 'Coffin, Mountain, Scythe, Mice and Cross override it the other way. Mountain in particular means "not by this route."']],
  read: 'Give the answer, then read the three cards as a line to explain *why* — a Lenormand yes/no should always come with its reason attached.',
  note: 'Only nine negative cards and eight positive ones are agreed on by every source; the tone list in the Lenormand tab shows which, and which cards are argued over. Count the agreed ones and treat the rest as neutral. For a yes/no that explains itself, use the French Cross below.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Nine cards — the box',
  when: 'A full picture of one situation, without the commitment of a Grand Tableau. The standard "serious question" spread in Lenormand.',
  ask: 'One situation, asked broadly. Deal three rows of three, left to right, top to bottom.',
  pos: [['Centre (5)', 'The heart of the matter. Read this card first — everything else in the box modifies it.'],
        ['Top row (1–3)', 'What is above the situation: the past, or what is known and in the open.'],
        ['Middle row (4–6)', 'The present. The most important line in the box.'],
        ['Bottom row (7–9)', 'What is underneath or ahead: the outcome, or what is hidden.'],
        ['Columns', 'Left column is the past or the cause; centre column is the matter itself; right column is the future or the result.'],
        ['Diagonals', 'Both diagonals cross the centre card and describe hidden influences on it.'],
        ['Corners (1, 3, 7, 9)', 'Read the four corners together as a summary of the whole box.']],
  read: 'Work in this order: centre card, then the middle row, then the other rows, then the columns, then the diagonals, then the corners. Each pass should sharpen the same answer rather than produce a new one.',
  note: 'If a pass contradicts everything before it, you have started interpreting instead of reading. Go back to the centre card.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau — all 36',
  when: 'A whole-life reading, or a situation with many moving parts. The full Lenormand method, and the one that takes longest to learn.',
  ask: 'You do not ask a narrow question here. You lay the whole deck out and let it describe the landscape — then answer specific questions from within it.',
  pos: [['The layout', 'All 36 cards: four rows of eight, then a final row of four centred beneath. Deal left to right, top to bottom.'],
        ['Find the significator', 'Locate the Man or the Woman — whichever represents the person you are reading for. The reading is organised around where they landed.'],
        ['Near cards', 'The cards immediately touching the significator, including diagonals, are the most important in the whole spread. Read them first.'],
        ['Direction', 'What lies in front of the significator is ahead of them; what lies behind is past. Above is what is on their mind, below is what is grounding or weighing on them.'],
        ['Houses', 'Each of the 36 positions also carries the meaning of the card that "belongs" to it — position 24 is the House of the Heart, so whatever lands there speaks about love.'],
        ['Knighting', 'The cards a chess knight\'s move away from the significator carry hidden influences. Advanced; leave it until the rest is solid.'],
        ['Mirroring', 'Cards facing each other across a row, and cards directly above and below, comment on one another.']],
  read: 'Read in layers: significator and its neighbours, then its row, then the houses of whatever you were asked about, then the corners of the tableau. Answer one question at a time from the same layout rather than trying to read all 36 cards in order.',
  note: 'Do not start here. Work through pairs, three-card lines and the nine-card box first — the Grand Tableau is those same techniques applied thirty-six times.' }

];

/* ============================ Vietnamese ============================ */

SPREADS.vi = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Bạn dùng trải bài này cho bài tập mỗi sáng, hoặc cho một câu hỏi nhỏ có thể trả lời gọn trong một câu. Bạn cũng có thể dùng nó khi một trải bài lớn đã luận xong nhưng vẫn còn thiếu một ý.',
  ask: 'Bạn hãy đặt câu hỏi theo dạng "Hôm nay mình cần biết gì về chuyện ___?". Một lá trả lời tốt cho câu hỏi "chuyện gì", trả lời kém cho câu hỏi "có nên hay không", và gần như không trả lời được câu hỏi "khi nào".',
  pos: [['Câu trả lời', 'Toàn bộ trải bài nằm gọn trong lá này. Bạn hãy nhìn bức tranh trước và ghi nhận chi tiết nào đập vào mắt mình, sau đó bạn mới đọc từ khoá, và cuối cùng bạn mới xét nghĩa xuôi hay nghĩa ngược.']],
  read: 'Bạn đọc theo ba bước lần lượt là hình ảnh, từ khoá và nghĩa. Nếu lá bài có vẻ "không nói gì", nguyên nhân thường nằm ở câu hỏi còn mơ hồ. Bạn hãy đặt lại câu hỏi cho rõ thay vì rút thêm một lá khác.',
  note: 'Bạn không nên rút lại chỉ vì bạn không thích câu trả lời. Nếu bạn thật sự cần thêm thông tin, bạn rút một lá làm rõ, và bạn tự nhắc mình rằng đó là lá bổ sung chứ không phải lá thay thế.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá: tình huống, hành động và kết quả',
  when: 'Đây là trải bài bạn dùng hằng ngày. Nó hợp với mọi chuyện mà bạn muốn biết ba điều: tình hình đang ra sao, bạn nên làm gì, và mọi việc sẽ đi tới đâu. Khi bạn phân vân không biết chọn trải bài nào, bạn hãy chọn trải bài này.',
  ask: 'Bạn hãy hỏi theo dạng "Chuyện ___ đang thế nào, mình nên làm gì, và rồi sẽ ra sao?". Trải bài này lấy một sự việc và soi nó từ ba góc nhìn.',
  pos: [['1 · Tình huống', 'Vị trí này cho biết điều đang thật sự diễn ra, chứ không phải điều bạn sợ hoặc điều bạn mong. Nếu một lá Ẩn Chính rơi vào đây, sự việc lớn hơn câu hỏi bạn vừa đặt.'],
        ['2 · Việc nên làm', 'Vị trí này chỉ ra phần việc thuộc về bạn. Bạn hãy đọc lá này như một lời khuyên để làm theo, chứ không phải như một lời tiên đoán.'],
        ['3 · Kết quả', 'Nếu bạn làm theo lá 2, sự việc sẽ đi tới điểm này. Đây là một hướng đi, chứ không phải một số phận đã định sẵn.']],
  read: 'Ở bước một, bạn đọc ba lá từ trái sang phải như một câu chuyện ngắn. Ở bước hai, bạn nhìn cả ba lá cùng lúc. Khi nhiều lá Ẩn Chính xuất hiện, sự việc không hoàn toàn nằm trong tay bạn. Khi cả ba lá cùng một chất, sự việc nằm trọn trong lĩnh vực của chất đó, với Cốc là tình cảm, Tiền là tiền bạc, Gậy là hành động và Kiếm là suy nghĩ.',
  note: 'Lá 3 mô tả kết quả trong trường hợp bạn làm theo lá 2. Vì vậy lá 2 mới là lá đáng để bạn làm theo nhất.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Có hoặc không: trải bài năm lá',
  when: 'Bạn chỉ nên dùng trải bài này khi câu hỏi thật sự chỉ có hai đáp án. Bạn không nên lạm dụng nó, vì phần lớn câu hỏi hay đều không phải câu hỏi có hoặc không.',
  ask: 'Câu hỏi của bạn phải trả lời được bằng có hoặc không, và nó chỉ được hỏi về một chuyện duy nhất. Câu "Tuần này người đó có nhắn tin cho mình không?" là hợp lệ. Câu "Người đó có nhắn tin không, và người đó có yêu mình không?" thật ra là hai câu hỏi.',
  pos: [['1–5 · Đếm', 'Bạn lật năm lá thành một hàng ngang. Sau đó bạn đếm số lá xuôi và số lá ngược: từ ba lá xuôi trở lên là có, còn từ ba lá ngược trở lên là không. Khi cả năm lá cùng một chiều, câu trả lời rất rõ ràng.'],
        ['Lá Ẩn Chính', 'Một lá Ẩn Chính nằm trong hàng được tính gấp đôi. Lá đó cũng cho biết sự việc có một phần không nằm trong tay con người.'],
        ['Lá giữa', 'Lá 3 giữ vai trò trọng tâm. Ngay cả khi phép đếm cho ra "có", lá 3 vẫn cho biết đó là một chữ "có" như thế nào: có ngay lập tức, có nhưng chậm, hoặc có kèm điều kiện.'],
        ['Chất bài', 'Hàng bài nghiêng về chất nào thì lĩnh vực đó nắm quyền quyết định: Cốc ứng với cảm xúc, Kiếm ứng với lời nói, Tiền ứng với thực tế, và Gậy ứng với việc có ai chịu hành động hay không.']],
  read: 'Ở bước một, bạn nói ra kết quả của phép đếm, tức là có hoặc không. Ở bước hai, bạn giải thích ngay bằng lá 3 và bằng chất bài chiếm đa số. Một chữ "có" hoặc "không" mà thiếu lời giải thích chỉ ngang với việc tung một đồng xu.',
  note: 'Cách đọc này đòi hỏi bạn phải dùng lá ngược. Nếu bạn không đọc lá ngược, bạn hãy chuyển sang trải bài ba lá và trả lời câu hỏi bằng ý nghĩa của các lá.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Thời điểm: bốn giai đoạn',
  when: 'Bạn dùng trải bài này khi câu hỏi của bạn là "bao giờ". Tarot gọi tên ngày tháng rất kém nhưng mô tả trình tự rất tốt, vì vậy trải bài này hỏi mỗi giai đoạn có gì thay vì hỏi ngày nào.',
  ask: 'Bạn hãy chốt đơn vị thời gian trước khi xào bài và nói nó ra thành lời: bốn tuần, bốn tháng, hoặc bốn quý. Nếu bạn nhìn thấy bài rồi mới đổi đơn vị, trải bài mất hết ý nghĩa.',
  pos: [['1 · Giai đoạn một', 'Vị trí này cho biết khoảng thời gian đầu tiên có gì. Nếu điều bạn hỏi xuất hiện ngay tại đây, nó đang ở rất gần.'],
        ['2 · Giai đoạn hai', 'Vị trí này là khoảng thời gian kế tiếp. Bạn hãy để ý các lá mang tính chuyển động như Gậy, Kỵ Sĩ, Cỗ Xe và Bánh Xe, vì chúng cho thấy sự việc đang dịch chuyển.'],
        ['3 · Giai đoạn ba', 'Vị trí này là khoảng thời gian sau đó. Nếu ở đây toàn các lá đứng yên như các lá Bốn, Người Treo Ngược và Bảy Tiền, bạn sẽ phải chờ lâu hơn mong đợi.'],
        ['4 · Giai đoạn bốn', 'Vị trí này nằm ở cuối khung thời gian. Nếu tới đây bạn vẫn chưa thấy điều mình hỏi, câu trả lời thật sự là sự việc chưa xảy ra trong khung này. Bạn hãy nói thẳng điều đó.']],
  read: 'Bạn hãy tìm lá trả lời đúng câu hỏi của mình, rồi xem lá đó nằm ở giai đoạn nào, vì giai đoạn đó chính là thời điểm. Nếu không lá nào trả lời, sự việc chưa nằm trong khung thời gian này. Nói thật điều đó vẫn tốt hơn đoán một ngày cho vừa lòng người nghe.',
  note: 'Bạn không bao giờ nên hứa một ngày cụ thể. Bạn chỉ đưa ra giai đoạn cùng các điều kiện, và bạn nói rõ rằng thời điểm là phần tarot đoán kém nhất.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Hai con đường cho một quyết định',
  when: 'Bạn dùng trải bài này khi bạn thật sự phải chọn một trong hai phương án: hai công việc, ở lại hay rời đi, nói ra hay giữ im lặng. Trải bài này so sánh hai tương lai chứ không dự đoán một tương lai.',
  ask: 'Bạn hãy gọi tên hai phương án trước khi xào bài, và quy định trước nhánh trái ứng với phương án nào, nhánh phải ứng với phương án nào. Bạn không được nhìn thấy bài rồi mới gán tên.',
  pos: [['1 · Bạn lúc này', 'Vị trí này cho biết bạn đang đứng ở đâu và bạn thật sự đang chọn giữa những gì. Nhiều khi điều này khác với những gì bạn nói ra.'],
        ['2 · Đường A, bước đầu', 'Vị trí này mô tả việc xảy ra ngay sau khi bạn chọn phương án thứ nhất.'],
        ['3 · Đường A, về sau', 'Vị trí này cho biết con đường thứ nhất dẫn tới đâu. Bạn hãy đọc nó chung với lá 2 như một mạch liền.'],
        ['4 · Đường B, bước đầu', 'Vị trí này mô tả việc xảy ra ngay sau khi bạn chọn phương án thứ hai.'],
        ['5 · Đường B, về sau', 'Con đường đó dẫn tới đâu.']],
  read: 'Bạn so sánh theo từng nhánh, tức là lá 2 cộng lá 3 đặt cạnh lá 4 cộng lá 5, thay vì so bốn lá rời rạc. Câu hỏi đáng đặt không phải nhánh nào dễ chịu hơn, mà là nhánh nào nói thật về cái giá phải trả. Một con đường khó lúc đầu nhưng kết thúc đẹp thường tốt hơn một con đường êm ái lúc đầu.',
  note: 'Bộ bài không chọn thay bạn. Bộ bài chỉ mô tả hai tương lai, còn quyết định vẫn thuộc về bạn.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Hai phía của một mối quan hệ',
  when: 'Bạn dùng trải bài này cho mọi chuyện giữa hai người mà bạn cần nhìn riêng từng phía: một cặp đôi, một mối quan hệ mập mờ, một lần giận nhau, hoặc cả quan hệ đồng nghiệp. Trải bài này không cho phép bạn trộn hai người thành một.',
  ask: 'Bạn hãy quy định trước ai đứng ở cột trái và ai đứng ở cột phải, sau đó bạn mới xào bài. Cột trái thường dành cho người hỏi.',
  pos: [['1 · Bạn: cảm thấy', 'Vị trí này cho biết điều bạn thật sự cảm thấy, nằm bên dưới những gì bạn nói ra.'],
        ['2 · Bạn: nghĩ', 'Vị trí này cho biết bạn đang tự nói với mình điều gì về chuyện này. Nó thường lệch với lá 1, và chính chỗ lệch đó là phần đáng đọc.'],
        ['3 · Bạn: làm', 'Vị trí này cho biết bạn đang cư xử thế nào trên thực tế, tức là phần mà người kia nhìn thấy.'],
        ['4 · Họ: cảm thấy', 'Vị trí này cho biết người kia đang cảm thấy gì. Bạn hãy đọc thẳng, không làm nhẹ đi chỉ vì người hỏi đang ngồi trước mặt.'],
        ['5 · Họ: nghĩ', 'Vị trí này cho biết người kia đang tự lý giải chuyện này theo cách nào.'],
        ['6 · Họ: làm', 'Vị trí này cho biết người kia đang thật sự làm gì. Đây là phần duy nhất có bằng chứng.'],
        ['7 · Giữa hai người', 'Vị trí này mô tả chính mối quan hệ như một thực thể thứ ba: phần chung của hai người, hoặc thứ đang chắn giữa hai người.']],
  read: 'Ở bước một, bạn đọc từng cột theo chiều từ trên xuống, đọc cột của bạn trước rồi tới cột của người kia. Ở bước hai, bạn đọc ngang và so từng cặp. Cặp đáng so nhất là lá 3 với lá 6, vì chúng cho biết mỗi bên đang làm gì. Cảm xúc rất dễ bị đọc sai, còn hành động mới là phần thật.',
  note: 'Nếu ba lá ở vị trí 4, 5 và 6 đều là lá hoàng gia hoặc đều thuộc chất Cốc, bạn mới thấy tính cách của người kia chứ chưa thấy ý định. Bạn hãy rút thêm một lá làm rõ với câu hỏi "họ định làm gì?".' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross: trải bài mười lá',
  when: 'Bạn dùng trải bài này cho một chuyện lớn và rối mà ba lá không chứa nổi. Bạn không nên lấy nó làm lựa chọn mặc định, vì mười lá dành cho một câu hỏi nhỏ chỉ thêm nhiễu chứ không thêm chiều sâu.',
  ask: 'Bạn hãy đặt một câu hỏi rộng về một tình huống, ví dụ "Cho mình thấy chuyện ___ đang diễn ra thế nào". Celtic Cross vẽ ra một bức tranh chứ không trả lời một câu ngắn.',
  pos: [['1 · Trọng tâm', 'Vị trí này là cốt lõi của sự việc, đúng như nó đang diễn ra.'],
        ['2 · Lá cắt ngang', 'Bạn đặt lá này nằm ngang trên lá 1. Nó cho biết điều làm sự việc rối thêm, đôi khi là một trở ngại, đôi khi lại là một sự giúp đỡ bạn không ngờ tới.'],
        ['3 · Bên dưới', 'Vị trí này là gốc rễ. Nó cho biết điều nằm bên dưới sự việc, và điều đó thường đã có từ trước.'],
        ['4 · Phía sau', 'Vị trí này cho biết điều đang lùi dần, tức là quá khứ gần vẫn còn níu giữ bạn.'],
        ['5 · Bên trên', 'Vị trí này cho biết điều đang ở ngoài sáng: mục tiêu, mong muốn, hoặc điều mà ai cũng nhìn thấy.'],
        ['6 · Phía trước', 'Vị trí này cho biết điều sắp tới trong thời gian gần.'],
        ['7 · Chính bạn', 'Vị trí này cho biết bạn đang xuất hiện thế nào trong câu chuyện, tức là tư thế của bạn chứ không phải cảm xúc của bạn.'],
        ['8 · Xung quanh', 'Vị trí này cho biết người khác và hoàn cảnh quanh bạn, tức là phần bạn không kiểm soát được.'],
        ['9 · Hy vọng và nỗi sợ', 'Vị trí này giữ cả hy vọng lẫn nỗi sợ cùng lúc, vì điều ta mong và điều ta sợ thường là một.'],
        ['10 · Kết quả', 'Vị trí này cho biết sự việc đang đi tới đâu khi xét tất cả các lá phía trên. Bạn đọc nó sau cùng và so nó với lá 1.']],
  read: 'Ở bước một, bạn đọc sáu lá thuộc hình chữ thập, tức lá 1 đến lá 6, như phần tình huống. Ở bước hai, bạn đọc bốn lá thuộc cột dọc, tức lá 7 đến lá 10, như cách bạn đứng trong tình huống đó. Ở bước ba, bạn so lá 1 với lá 10. Nếu hai lá kể cùng một câu chuyện, sự việc đã rõ. Nếu chúng mâu thuẫn, bạn hãy nhìn lá 9, vì lá này thường giải thích nguyên nhân.',
  note: 'Bạn chỉ nên dùng trải bài này khi bạn đã thành thạo ba lá. Mười vị trí nhớ lơ mơ còn tệ hơn ba vị trí nắm chắc.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Lá làm rõ: rút thêm một hoặc hai lá',
  when: 'Bạn dùng kỹ thuật này khi một vị trí trong trải bài đã xong mà bạn thật sự không hiểu, hoặc khi một lá có nhiều nghĩa và bạn cần biết nghĩa nào đang đúng. Đây là một kỹ thuật chứ không phải một trải bài riêng.',
  ask: 'Bạn hãy chỉ đúng vào lá đó và hỏi thật cụ thể, ví dụ "Bảy Kiếm ở vị trí này nghĩa là gì?". Bạn không nên hỏi xin một câu trả lời đẹp hơn.',
  pos: [['1 · Lá làm rõ', 'Bạn đọc lá này như một tính từ gắn thêm vào lá gốc, chứ không phải như một câu trả lời mới. Nó bổ nghĩa cho lá gốc và không thay thế lá gốc.'],
        ['2 · Lá làm rõ thứ hai', 'Bạn chỉ rút lá này khi lá làm rõ đầu tiên vẫn chưa giúp được gì. Hai lá là giới hạn.']],
  read: 'Trước khi rút, bạn hãy nói ra thành lời tiêu chuẩn của mình: thế nào thì bạn coi là đã rõ. Thói quen nhỏ này giúp bạn phân biệt việc làm rõ với việc rút bừa cho tới khi vừa ý.',
  note: 'Việc rút mãi cho tới khi bạn thích câu trả lời là cách nhanh nhất để bạn mất niềm tin vào bộ bài của mình. Bạn dừng lại ở tối đa hai lá làm rõ.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Bạn dùng trải bài này cho lá của ngày, hoặc cho một câu hỏi rất hẹp. Mỗi lá Lenormand là một danh từ, nên một lá chỉ cho bạn chủ đề chứ chưa dựng nên câu chuyện.',
  ask: 'Bạn hãy hỏi về một chuyện cụ thể thay vì hỏi về cảm giác, ví dụ "Hôm nay xoay quanh chuyện gì?". Một lá Lenormand gọi tên chủ đề rồi dừng lại.',
  pos: [['Chủ đề', 'Vị trí này cho bạn một danh từ. Bạn hiểu theo nghĩa đen trước, ví dụ Con Thuyền là chuyến đi xa hoặc khoảng cách, rồi sau đó bạn mới nghĩ tới nghĩa bóng.']],
  read: 'Một lá là cách đọc yếu nhất của Lenormand, vì hệ thống này sống nhờ sự kết hợp giữa các lá. Nếu bạn rút được hai lá, bạn hãy rút hai lá.',
  note: 'Bạn không nên đọc Lenormand theo lối tarot. Hệ này không có lá ngược và không có hành trình nội tâm. Mỗi lá là một vật, tức là một chuyện có thật trong đời bạn.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Hai lá: một cặp bài',
  when: 'Cặp bài là đơn vị cơ bản của Lenormand, và mọi trải bài lớn hơn đều được xây từ kỹ thuật này. Bạn dùng nó cho một câu hỏi cụ thể cần một câu trả lời cụ thể.',
  ask: 'Bạn hãy đặt một câu hỏi hẹp. Cặp bài trao cho bạn một danh từ và một từ bổ nghĩa, nên câu trả lời sẽ là một cụm ngắn chứ không phải một bài dài.',
  pos: [['1 · Chủ đề', 'Vị trí này là danh từ. Câu trả lời của bạn nói về chính thứ đó.'],
        ['2 · Bổ nghĩa', 'Lá ở vị trí này mô tả lá 1. Trái Tim cộng Ngọn Núi cho ra tình yêu bị chặn, còn Ngọn Núi cộng Trái Tim cho ra một trở ngại liên quan tới tình cảm. Khi bạn đổi thứ tự, nghĩa cũng đổi theo.']],
  read: 'Bạn hãy nói to cặp bài thành một cụm duy nhất, ví dụ "Lá Thư cộng Quan Tài" trở thành "tin buồn bằng văn bản". Nếu bạn không gói được nó trong một cụm ngắn, bạn đang nghĩ quá nhiều.',
  note: 'Đây là thói quen quan trọng nhất trong Lenormand: bạn luôn đọc theo cặp trước, sau đó bạn mới đọc từng lá.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá xếp thành hàng ngang',
  when: 'Đây là cách đọc Lenormand bạn dùng hằng ngày. Nó trả lời một câu hỏi bằng một câu hoàn chỉnh mà vẫn giữ được sự gọn gàng.',
  ask: 'Bạn hãy đặt một câu hỏi rõ ràng về một sự việc. Ba lá đủ để mô tả tình huống và hướng đi của tình huống đó.',
  pos: [['1 · Chủ đề', 'Vị trí này cho biết sự việc là gì. Nó thường là người hoặc việc mà bạn đang hỏi.'],
        ['2 · Lá giữa', 'Vị trí này là trọng tâm của câu trả lời. Trong một hàng ba lá, lá giữa mang sức nặng lớn nhất và được cả hai lá bên cạnh bổ nghĩa.'],
        ['3 · Hướng đi', 'Vị trí này cho biết sự việc đi tới đâu, hoặc nó dẫn tới kết quả nào.']],
  read: 'Bạn đọc ba lượt. Lượt một, bạn đọc cả hàng như một câu từ trái sang phải. Lượt hai, bạn đọc cặp gồm lá 1 và lá 2. Lượt ba, bạn đọc cặp gồm lá 2 và lá 3. Nếu ba lượt đọc cùng nói một ý, đó chính là câu trả lời. Nếu chúng khác nhau, lá 2 giữ quyền quyết định.',
  note: 'Thời gian nằm ở bản thân lá bài chứ không nằm ở vị trí: Kỵ Mã tính bằng ngày, Con Thuyền tính bằng tháng, còn Mỏ Neo mang nghĩa lâu dài. Một hàng ba lá vẫn trả lời được câu hỏi khi nào nếu trong hàng có lá chỉ thời gian.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Năm lá xếp thành hàng ngang',
  when: 'Trải bài này cho một câu trả lời đầy đủ hơn, gồm bối cảnh, chính sự việc, và kết quả. Đây là trải bài đa dụng tốt nhất của Lenormand, dành cho lúc bạn đã đọc cặp bài thành thạo.',
  ask: 'Bạn hãy đặt một câu hỏi rộng hơn câu hỏi dành cho hàng ba lá một chút. Năm lá chứa được cả nguyên nhân lẫn kết quả.',
  pos: [['1 · Bối cảnh', 'Vị trí này cho biết điều nằm phía sau, tức là quá khứ hoặc hoàn cảnh của sự việc.'],
        ['2 · Đang hình thành', 'Bạn đọc lá này thành cặp với lá 1, rồi bạn đọc nó thành cặp với lá 3.'],
        ['3 · Trung tâm', 'Vị trí này là cốt lõi của câu trả lời. Mọi lá còn lại đều mô tả lá nằm ở đây.'],
        ['4 · Sắp tới', 'Bạn đọc lá này thành cặp với lá 3, rồi bạn đọc nó thành cặp với lá 5.'],
        ['5 · Kết quả', 'Vị trí này cho biết sự việc dừng lại ở đâu.']],
  read: 'Ở bước một, bạn đọc lá giữa. Ở bước hai, bạn đọc hai cặp nằm hai bên, gồm cặp 2 với 3 và cặp 3 với 4. Ở bước ba, bạn so hai đầu hàng, tức lá 1 với lá 5, vì cặp này thường là bản tóm tắt ngắn nhất của cả trải bài.',
  note: 'Bạn hãy để ý lá Quý Ông hoặc lá Quý Bà rơi vào đâu. Nếu lá đó nằm gần đầu hàng, người đó là nguyên nhân; nếu lá đó nằm gần cuối hàng, người đó là kết quả. Hướng người đó quay mặt cho biết họ đang hướng về điều gì.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Có hoặc không: trải bài ba lá',
  when: 'Bạn dùng trải bài này cho câu hỏi đóng. Lenormand trả lời có hoặc không dễ hơn tarot, vì mỗi lá đã mang sẵn sắc thái tốt hoặc xấu.',
  ask: 'Bạn hãy đặt một câu hỏi đóng về một sự việc. Trước khi rút, bạn hình dung xem một chữ "có" trên thực tế sẽ trông như thế nào.',
  pos: [['1–3 · Sắc thái', 'Bạn đếm số lá tốt và số lá xấu. Hai hoặc ba lá tốt cho ra câu trả lời có, còn hai hoặc ba lá xấu cho ra câu trả lời không. Lá trung tính nhận sắc thái từ lá đứng bên cạnh.'],
        ['"Có" mạnh', 'Chìa Khoá, Mặt Trời và Cỏ Ba Lá có sức nặng lớn hơn phép đếm. Riêng Chìa Khoá gần như luôn là một chữ "có" chắc chắn, dù nó rơi vào vị trí nào.'],
        ['"Không" mạnh', 'Quan Tài, Ngọn Núi, Lưỡi Hái, Đàn Chuột và Cây Thánh Giá có sức nặng lớn hơn phép đếm theo chiều ngược lại. Riêng Ngọn Núi mang nghĩa rằng bạn không đi được bằng con đường này.']],
  read: 'Ở bước một, bạn nói ra câu trả lời. Ở bước hai, bạn đọc ba lá như một hàng để giải thích vì sao. Trong Lenormand, một câu có hoặc không luôn đi kèm lý do.',
  note: 'Chỉ có chín lá xấu và tám lá tốt được mọi sách thống nhất, và bảng sắc thái trong tab Lenormand cho bạn biết đó là những lá nào. Bạn hãy đếm các lá đã được thống nhất và coi phần còn lại là trung tính.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Chín lá xếp thành ô vuông',
  when: 'Trải bài này cho bạn bức tranh đầy đủ về một sự việc mà bạn không cần trải cả Grand Tableau. Đây là trải bài tiêu chuẩn của Lenormand cho những câu hỏi nghiêm túc.',
  ask: 'Bạn hãy hỏi rộng về một sự việc. Bạn rải ba hàng, mỗi hàng ba lá, theo chiều từ trái sang phải và từ trên xuống dưới.',
  pos: [['Lá giữa (5)', 'Đây là trọng tâm của trải bài. Bạn đọc lá này trước, vì mọi lá khác đều bổ nghĩa cho nó.'],
        ['Hàng trên (1–3)', 'Hàng này cho biết điều bao trùm sự việc, tức là quá khứ hoặc những gì bạn đã biết.'],
        ['Hàng giữa (4–6)', 'Hàng này mô tả hiện tại, và đây là hàng quan trọng nhất.'],
        ['Hàng dưới (7–9)', 'Hàng này cho biết điều nằm bên dưới hoặc phía trước, tức là kết quả hoặc những gì còn ẩn.'],
        ['Các cột', 'Cột trái mang nghĩa quá khứ hoặc nguyên nhân, cột giữa mang chính sự việc, còn cột phải mang nghĩa tương lai hoặc kết quả.'],
        ['Hai đường chéo', 'Hai đường chéo đều đi qua lá giữa, và chúng mô tả những ảnh hưởng ngầm.'],
        ['Bốn góc (1, 3, 7, 9)', 'Bạn đọc bốn góc chung với nhau như bản tóm tắt của cả ô vuông.']],
  read: 'Bạn đọc theo trình tự: lá giữa, hàng giữa, hai hàng còn lại, ba cột, hai đường chéo, rồi bốn góc. Mỗi lượt đọc phải làm rõ thêm cùng một câu trả lời chứ không được tạo ra một câu trả lời mới.',
  note: 'Nếu một lượt đọc mâu thuẫn với tất cả các lượt trước, bạn đang suy diễn chứ không còn đọc bài nữa. Bạn hãy quay lại lá giữa.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau với trọn 36 lá',
  when: 'Bạn dùng trải bài này để nhìn tổng quan cả cuộc sống, hoặc để xem một chuyện có rất nhiều phần. Đây là phương pháp đầy đủ nhất của Lenormand, và cũng là phương pháp mất nhiều thời gian học nhất.',
  ask: 'Bạn không đặt một câu hỏi hẹp ở đây. Bạn trải cả bộ bài để nó mô tả toàn cảnh, rồi bạn trả lời từng câu hỏi cụ thể từ chính bức tranh đó.',
  pos: [['Cách bày', 'Bạn bày cả 36 lá thành bốn hàng tám lá, cộng một hàng cuối gồm bốn lá đặt chính giữa bên dưới. Bạn rải bài từ trái sang phải và từ trên xuống dưới.'],
        ['Tìm lá đại diện', 'Bạn tìm lá Quý Ông hoặc lá Quý Bà, tuỳ theo người bạn đang xem. Cả trải bài xoay quanh vị trí của lá này.'],
        ['Các lá kề', 'Những lá chạm vào lá đại diện, kể cả theo đường chéo, mang ý nghĩa quan trọng nhất. Bạn đọc chúng trước tiên.'],
        ['Trước và sau', 'Lá nằm phía trước lá đại diện cho biết điều sắp tới, còn lá nằm phía sau cho biết quá khứ. Lá nằm bên trên cho biết điều đang bận tâm, còn lá nằm bên dưới cho biết điều đang nâng đỡ hoặc đang đè nặng.'],
        ['Các "ngôi nhà"', 'Mỗi vị trí trong 36 ô còn mang nghĩa của lá bài mang số tương ứng. Ô 24 là nhà của Trái Tim, nên bất cứ lá nào rơi vào ô đó đều nói về tình cảm.'],
        ['Bước mã', 'Những lá cách lá đại diện đúng một bước đi của quân mã trong cờ vua mang ảnh hưởng ngầm. Đây là kỹ thuật nâng cao, và bạn nên để dành nó cho về sau.'],
        ['Soi chiếu', 'Các lá đối xứng với nhau trong cùng một hàng, và các lá nằm ngay trên và ngay dưới nhau, đều bổ nghĩa cho nhau.']],
  read: 'Bạn đọc theo từng lớp: lá đại diện cùng các lá kề, rồi hàng chứa lá đại diện, rồi ngôi nhà của chủ đề bạn hỏi, rồi bốn góc bảng. Bạn trả lời từng câu hỏi từ cùng một bức tranh thay vì cố đọc lần lượt cả 36 lá.',
  note: 'Bạn không nên bắt đầu từ trải bài này. Bạn học cặp bài, hàng ba lá và ô chín lá trước, vì Grand Tableau chỉ là những kỹ thuật đó lặp lại 36 lần.' }

];
