/* ============================ spreads ============================ */
/* How many cards to draw for which kind of question, where each card goes, and
   what each position means.
   `lay` is a list of [col, row] grid slots -- and optionally a third entry 'r'
   for a card laid crosswise. The renderer turns that into a diagram, so a
   layout is described once and drawn identically in both languages.
   `kinds` drives the question-type filter. `sys` keeps the two systems apart. */

const SPREADS = { en: [], vi: [] };

/* ---- shared geometry, so both languages draw the same picture ---- */
const LAY = {
  one:    [[0, 0]],
  two:    [[0, 0], [1, 0]],
  three:  [[0, 0], [1, 0], [2, 0]],
  four:   [[0, 0], [1, 0], [2, 0], [3, 0]],
  five:   [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]],
  choice: [[1, 0], [0, 1], [0, 2], [2, 1], [2, 2]],
  rel7:   [[0, 0], [0, 1], [0, 2], [2, 0], [2, 1], [2, 2], [1, 1]],
  celtic: [[1, 1], [1, 1, 'r'], [1, 2], [0, 1], [1, 0], [2, 1], [3, 3], [3, 2], [3, 1], [3, 0]],
  box9:   [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2]],
  gt:     (function () {
    const a = [];
    for (let r = 0; r < 4; r++) for (let c = 0; c < 8; c++) a.push([c, r]);
    for (let c = 2; c < 6; c++) a.push([c, 4]);
    return a;
  }())
};

/* ============================ English ============================ */

SPREADS.en = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'Daily practice, and any question small enough to answer in a sentence. Also the right size when you have already read a spread and just need one more piece of information.',
  ask: '"What do I most need to know about ___ today?" Keep it open. A single card answers a *what*, badly answers a *should I*, and cannot answer a *when*.',
  pos: [['The answer', 'The whole reading. Read the image first and what you notice about it, then the keywords, then the upright or reversed meaning. Do not reach for a second card to soften the first one.']],
  read: 'One card is not a lesser reading — it is a more disciplined one. If the card seems to say nothing, the usual cause is that the question was too vague to be answered.',
  note: 'Never re-draw because you did not like the answer. If you genuinely need more, draw a clarifier and say out loud that that is what you are doing.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — situation, action, outcome',
  when: 'The everyday workhorse. Any question where you want to know what is going on, what to do about it, and where it leads. This is the spread to reach for when you are unsure which spread to use.',
  ask: '"Where does ___ stand, what should I do, and where does that lead?" One subject, three angles.',
  pos: [['1 · Situation', 'What is actually happening now — not what you fear or hope. If a Major lands here, the matter is bigger than the question you asked.'],
        ['2 · Action', 'What is yours to do. This position is advice, so read it as an instruction rather than a prediction.'],
        ['3 · Outcome', 'Where the current path leads *if the advice in position 2 is followed*. It is a projection, not a fixed fate.']],
  read: 'Read left to right as a sentence. Then check the balance across all three: heavy Majors mean the situation is not fully in your hands; all Minors of one suit means the whole matter lives in that one area of life.',
  note: 'Position 3 answers "if nothing changes." That is what makes position 2 worth acting on.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Yes / No — five cards',
  when: 'A genuine closed question with two possible answers. Use it sparingly: most questions worth asking are not yes/no questions, and forcing them into this shape wastes the reading.',
  ask: 'The question must be answerable with yes or no, and must be about one thing. "Will he text me this week?" works. "Will he text me and does he love me?" does not.',
  pos: [['1–5 · The tally', 'Deal five cards face up in a row. Count upright against reversed: three or more upright is yes, three or more reversed is no. Five to nothing in either direction is emphatic.'],
        ['The Majors', 'Any Major Arcana in the row carries double weight in the count — the matter is not entirely in human hands.'],
        ['The middle card', 'Card 3 is the heart of the answer. Even when the tally says yes, this card tells you what kind of yes it is.'],
        ['The suits', 'A row dominated by one suit tells you which area actually decides the outcome — Cups for feeling, Swords for what is said, Pentacles for practical reality, Wands for whether anyone acts.']],
  read: 'Give the tally first, then immediately explain it using card 3 and the suit balance. A bare yes or no is not a reading; it is a coin toss with pictures.',
  note: 'If you do not read reversals, this method does not work. Use the three-card spread instead and answer the question from the meaning.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Timing — four periods',
  when: '"When will it happen?" Tarot is poor at naming dates and good at describing sequence, so this spread asks *what happens in each period* rather than *which date*.',
  ask: 'Decide the unit before you shuffle and say it out loud: four weeks, or four months, or four quarters. Changing the unit after you see the cards is how readings become meaningless.',
  pos: [['1 · First period', 'What this stretch of time holds. If the thing you asked about appears here, it is close.'],
        ['2 · Second period', 'The next stretch. Watch for movement cards — Wands, Knights, the Chariot, the Wheel — which show things actually shifting.'],
        ['3 · Third period', 'The stretch after that. A run of stillness here (Fours, the Hanged Man, Seven of Pentacles) means the wait is longer than hoped.'],
        ['4 · Fourth period', 'The end of the window you asked about. If nothing has arrived by here, the honest answer is "not within this window" — say so.']],
  read: 'Find the card that answers the question and read the position it landed in. That is the timing. If no card answers it, the honest reading is that the event is not in this window, and the client is better served by hearing that than by a comforting guess.',
  note: 'Never promise a date. Give the period, give the conditions, and say plainly that timing is the least reliable thing tarot does.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Two roads — a decision',
  when: 'A real either/or: two jobs, stay or leave, tell them or say nothing. It compares two futures instead of predicting one.',
  ask: 'Name both options out loud before you shuffle, and assign one to the left branch and one to the right. Do not decide which is which after seeing the cards.',
  pos: [['1 · You now', 'Where you stand, and what you are actually deciding between — which is often not what you said it was.'],
        ['2 · Road A, first step', 'What immediately follows if you take the first option.'],
        ['3 · Road A, where it leads', 'Where that road arrives. Read it together with card 2 as one movement.'],
        ['4 · Road B, first step', 'What immediately follows if you take the second option.'],
        ['5 · Road B, where it leads', 'Where that road arrives.']],
  read: 'Compare the two branches as pairs, not as four separate cards. The cleaner reading is usually not "which branch is nicer" but "which branch is honest about its cost" — a road with a hard first step and a good end often beats an easy start.',
  note: 'The cards do not choose. They describe two futures; the decision stays with the person who asked.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Two sides — the relationship',
  when: 'Any two-person question where you need both sides separately: a couple, a situationship, a falling-out, even a working relationship. Its strength is that it refuses to blend the two people together.',
  ask: 'Name who is on the left and who is on the right before shuffling. The left column is usually the person asking.',
  pos: [['1 · You: feeling', 'What you actually feel, underneath what you say you feel.'],
        ['2 · You: thinking', 'What you tell yourself about this. Often at odds with card 1, and that gap is the reading.'],
        ['3 · You: doing', 'How you are actually behaving — what the other person sees.'],
        ['4 · Them: feeling', 'What they feel. Read it plainly; do not soften it because the person asking is in the room.'],
        ['5 · Them: thinking', 'How they are framing this to themselves.'],
        ['6 · Them: doing', 'What they are actually doing, which is the only part you have evidence for.'],
        ['7 · Between you', 'The relationship itself as a third thing — the shared ground, or what stands in it.']],
  read: 'Read down each column first, then across. The most useful comparison is card 3 against card 6: what each side is *doing*. Feelings can be misread; behaviour is what actually happens.',
  note: 'If cards 4–6 are all courts or all Cups, you are reading their temperament rather than their intent — consider a clarifier for what they intend to do.' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross — ten cards',
  when: 'A large, tangled situation that a three-card spread cannot hold. Do not use it as a default — ten cards on a simple question produce noise, not depth.',
  ask: 'One situation, broadly framed: "Show me what is happening with ___." The Celtic Cross answers a landscape, not a question.',
  pos: [['1 · The heart', 'The core of the matter as it stands.'],
        ['2 · Crossing', 'Laid across card 1. What complicates it — sometimes an obstacle, sometimes help you did not ask for.'],
        ['3 · Beneath', 'The root. What is underneath this and probably older than it.'],
        ['4 · Behind', 'What is passing out of the situation — recent past, still exerting a pull.'],
        ['5 · Above', 'What is in the open: the goal, the ideal, or what everyone can see.'],
        ['6 · Before', 'What is coming next, in the near term.'],
        ['7 · Yourself', 'How you are showing up in this — your stance, not your feelings.'],
        ['8 · Environment', 'Other people, and the conditions around you that you do not control.'],
        ['9 · Hopes and fears', 'Traditionally both at once, because they are usually the same card seen from two sides.'],
        ['10 · Outcome', 'Where this is heading, given everything above. Read it last, and read it against card 1.']],
  read: 'Read the cross (1–6) as the situation and the staff (7–10) as your relationship to it. If cards 1 and 10 tell the same story, the matter is settled. If they contradict each other, card 9 usually explains why.',
  note: 'Do not attempt this until three cards feel easy. Ten positions you half-remember are worse than three you know.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Clarifiers — one or two extra',
  when: 'A single position in a finished spread is genuinely unreadable, or a card has several branching meanings and you need to know which branch applies. This is a technique, not a spread.',
  ask: 'Point at the specific card and ask a specific question about it: "What does the Seven of Swords mean *here*?" Never "tell me something better."',
  pos: [['1 · Clarifier', 'Read this as an adjective attached to the original card, not as a new answer. It modifies; it does not replace.'],
        ['2 · Second clarifier', 'Only if the first genuinely did not land. Two is the limit.']],
  read: 'Say out loud, before drawing, what would count as an answer. That single habit is what separates clarifying from fishing.',
  note: 'Drawing until you like the answer is the most common way readers lose their own trust in the deck. Two clarifiers, then stop.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'One card',
  when: 'A card of the day, or one very narrow question. Lenormand cards are nouns, so a single card gives you a subject with no sentence around it.',
  ask: 'Ask for a thing, not a feeling: "What is the day about?" A single Lenormand card names a topic and stops there.',
  pos: [['The subject', 'The noun. Take it literally first — Ship means travel or distance before it means anything symbolic.']],
  read: 'One card is the weakest Lenormand reading, because the whole system works by combination. If you can draw two instead, draw two.',
  note: 'Do not read Lenormand cards the way you read tarot. There is no reversal and no inner journey — the card is an object in your life.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Two cards — the pair',
  when: 'The fundamental unit of Lenormand, and the technique every larger spread is built from. Use it for one specific question with one specific answer.',
  ask: 'One narrow question. The pair gives you a noun and a modifier, so the answer arrives as a short phrase, not an essay.',
  pos: [['1 · The subject', 'The noun. This is what the answer is about.'],
        ['2 · The modifier', 'This describes card 1. Heart + Mountain is blocked love; Mountain + Heart is an obstacle to do with the heart — the order changes the meaning.']],
  read: 'Say the pair out loud as two words joined: "letter + coffin" becomes "bad news in writing." If you cannot say it in one short phrase, you are overthinking it.',
  note: 'This is the single most important habit in Lenormand: read pairs, always, before you read individual cards.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Three cards — the line',
  when: 'The everyday Lenormand reading. It answers a question with a full sentence and stays small enough to read cleanly.',
  ask: 'One clear question about one matter. Three cards is enough for a situation and its direction.',
  pos: [['1 · Subject', 'What the matter is. Often the person or thing you asked about.'],
        ['2 · Centre', 'The heart of the answer. In a three-card line the middle card carries the most weight, and it is also modified by both neighbours.'],
        ['3 · Direction', 'Where it is going, or what it results in.']],
  read: 'Read it three ways: as one sentence left to right; as the pair 1+2; and as the pair 2+3. Where all three readings agree, you have your answer. Where they disagree, card 2 decides.',
  note: 'Timing lives in the cards, not the positions — Rider is days, Ship is months, Anchor is lasting. A three-card line can answer "when" if a timing card lands in it.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Five cards — the line',
  when: 'A fuller answer to one question: background, the matter itself, and where it goes. The best all-purpose Lenormand spread once pairs feel natural.',
  ask: 'One question, asked more broadly than in a three-card line. Five cards can hold a cause and an outcome as well as the subject.',
  pos: [['1 · Background', 'What lies behind this — the past, or the setting the matter sits in.'],
        ['2 · What is developing', 'Read as a pair with card 1 and with card 3.'],
        ['3 · The centre', 'The core of the answer. Everything else in the line describes this card.'],
        ['4 · What is coming', 'Read as a pair with card 3 and with card 5.'],
        ['5 · Outcome', 'Where it lands.']],
  read: 'Read the centre first, then the pairs either side of it, then the two ends against each other. Cards 1 and 5 as a pair often give the shortest summary of the whole reading.',
  note: 'Where the Man or the Woman lands in the line matters: near the start they are the cause, near the end they are the result, and the direction they face shows what they are turned towards.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Yes / No — three cards',
  when: 'A closed question. Lenormand answers yes/no more comfortably than tarot does, because the cards carry a settled positive or negative tone.',
  ask: 'One closed question about one thing. Decide before drawing what a yes would actually look like in real life.',
  pos: [['1–3 · The tone', 'Count the positive against the negative cards. Two or three positive is yes; two or three negative is no. Neutral cards take their tone from the cards beside them.'],
        ['The strong yes', 'Key, Sun and Clover override the tally. Key especially is close to a definitive yes wherever it lands.'],
        ['The strong no', 'Coffin, Mountain, Scythe, Mice and Cross override it the other way. Mountain in particular means "not by this route."']],
  read: 'Give the answer, then read the three cards as a line to explain *why* — a Lenormand yes/no should always come with its reason attached.',
  note: 'Only nine negative cards and eight positive ones are agreed on by every source; the tone list in the Lenormand tab shows which, and which cards are argued over. Count the agreed ones and treat the rest as neutral. For a yes/no that explains itself, use the French Cross below.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Nine cards — the box',
  when: 'A full picture of one situation, without the commitment of a Grand Tableau. The standard "serious question" spread in Lenormand.',
  ask: 'One situation, asked broadly. Deal three rows of three, left to right, top to bottom.',
  pos: [['Centre (5)', 'The heart of the matter. Read this card first — everything else in the box modifies it.'],
        ['Top row (1–3)', 'What is above the situation: the past, or what is known and in the open.'],
        ['Middle row (4–6)', 'The present. The most important line in the box.'],
        ['Bottom row (7–9)', 'What is underneath or ahead: the outcome, or what is hidden.'],
        ['Columns', 'Left column is the past or the cause; centre column is the matter itself; right column is the future or the result.'],
        ['Diagonals', 'Both diagonals cross the centre card and describe hidden influences on it.'],
        ['Corners (1, 3, 7, 9)', 'Read the four corners together as a summary of the whole box.']],
  read: 'Work in this order: centre card, then the middle row, then the other rows, then the columns, then the diagonals, then the corners. Each pass should sharpen the same answer rather than produce a new one.',
  note: 'If a pass contradicts everything before it, you have started interpreting instead of reading. Go back to the centre card.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau — all 36',
  when: 'A whole-life reading, or a situation with many moving parts. The full Lenormand method, and the one that takes longest to learn.',
  ask: 'You do not ask a narrow question here. You lay the whole deck out and let it describe the landscape — then answer specific questions from within it.',
  pos: [['The layout', 'All 36 cards: four rows of eight, then a final row of four centred beneath. Deal left to right, top to bottom.'],
        ['Find the significator', 'Locate the Man or the Woman — whichever represents the person you are reading for. The reading is organised around where they landed.'],
        ['Near cards', 'The cards immediately touching the significator, including diagonals, are the most important in the whole spread. Read them first.'],
        ['Direction', 'What lies in front of the significator is ahead of them; what lies behind is past. Above is what is on their mind, below is what is grounding or weighing on them.'],
        ['Houses', 'Each of the 36 positions also carries the meaning of the card that "belongs" to it — position 24 is the House of the Heart, so whatever lands there speaks about love.'],
        ['Knighting', 'The cards a chess knight\'s move away from the significator carry hidden influences. Advanced; leave it until the rest is solid.'],
        ['Mirroring', 'Cards facing each other across a row, and cards directly above and below, comment on one another.']],
  read: 'Read in layers: significator and its neighbours, then its row, then the houses of whatever you were asked about, then the corners of the tableau. Answer one question at a time from the same layout rather than trying to read all 36 cards in order.',
  note: 'Do not start here. Work through pairs, three-card lines and the nine-card box first — the Grand Tableau is those same techniques applied thirty-six times.' }

];

/* ============================ Vietnamese ============================ */

SPREADS.vi = [

/* ---------------------------------------------------------- tarot ---- */
{ id: 'tarot-1', sys: 'tarot', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Dùng để luyện mỗi ngày, và cho những câu hỏi đủ nhỏ để trả lời trong một câu. Cũng là cỡ đúng khi bạn đã luận xong một trải bài và chỉ cần thêm một mẩu thông tin.',
  ask: '"Hôm nay điều mình cần biết nhất về ___ là gì?" Hãy để câu hỏi mở. Một lá trả lời tốt câu hỏi *cái gì*, trả lời dở câu hỏi *có nên không*, và không trả lời được câu hỏi *khi nào*.',
  pos: [['Câu trả lời', 'Đây là toàn bộ trải bài. Hãy nhìn hình trước và ghi nhận điều bạn thấy, rồi mới tới từ khóa, rồi mới tới nghĩa xuôi hoặc ngược. Đừng với tay rút lá thứ hai chỉ để làm dịu lá thứ nhất.']],
  read: 'Một lá không phải là trải bài kém hơn — nó là trải bài kỷ luật hơn. Nếu lá bài như không nói gì, nguyên nhân thường là câu hỏi quá mơ hồ để có thể trả lời.',
  note: 'Đừng bao giờ rút lại vì không thích câu trả lời. Nếu thật sự cần thêm, hãy rút lá làm rõ và nói rõ ra rằng bạn đang làm điều đó.' },

{ id: 'tarot-3', sys: 'tarot', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá — tình huống, hành động, kết quả',
  when: 'Trải bài dùng hằng ngày. Hợp với mọi câu hỏi mà bạn muốn biết chuyện gì đang xảy ra, nên làm gì, và điều đó dẫn tới đâu. Khi không biết nên dùng trải bài nào, hãy dùng cái này.',
  ask: '"Chuyện ___ đang ở đâu, mình nên làm gì, và điều đó dẫn tới đâu?" Một chủ đề, ba góc nhìn.',
  pos: [['1 · Tình huống', 'Điều đang thật sự diễn ra — không phải điều bạn sợ hay hy vọng. Nếu một lá Ẩn Chính rơi vào đây, chuyện này lớn hơn câu hỏi bạn đặt ra.'],
        ['2 · Hành động', 'Phần thuộc về bạn. Đây là vị trí lời khuyên, nên hãy đọc nó như một chỉ dẫn chứ không phải một lời tiên đoán.'],
        ['3 · Kết quả', 'Con đường hiện tại dẫn tới đâu *nếu lời khuyên ở lá 2 được làm theo*. Đây là một dự phóng, không phải một định mệnh đã chốt.']],
  read: 'Đọc từ trái sang phải như một câu văn. Rồi kiểm tra thế trận của cả ba: nhiều Ẩn Chính nghĩa là chuyện không hoàn toàn nằm trong tay bạn; ba lá Ẩn Phụ cùng một chất nghĩa là toàn bộ câu chuyện nằm gọn trong đúng lĩnh vực đó.',
  note: 'Lá 3 trả lời cho tình huống "nếu không có gì thay đổi". Chính vì thế lá 2 mới đáng để làm theo.' },

{ id: 'tarot-yesno', sys: 'tarot', kinds: ['yesno'], n: 5, lay: LAY.five,
  name: 'Có / Không — năm lá',
  when: 'Một câu hỏi đóng thật sự, chỉ có hai đáp án. Hãy dùng dè dặt: phần lớn câu hỏi đáng hỏi đều không phải câu hỏi có/không, và ép chúng vào khuôn này là phí cả trải bài.',
  ask: 'Câu hỏi phải trả lời được bằng có hoặc không, và phải hỏi về một chuyện thôi. "Tuần này anh ấy có nhắn tin không?" thì được. "Anh ấy có nhắn tin không và anh ấy có yêu mình không?" thì không.',
  pos: [['1–5 · Đếm', 'Lật năm lá thành một hàng. Đếm xuôi so với ngược: từ ba lá xuôi trở lên là có, từ ba lá ngược trở lên là không. Năm-không thì là câu trả lời rất dứt khoát.'],
        ['Các lá Ẩn Chính', 'Bất kỳ lá Ẩn Chính nào trong hàng đều tính điểm gấp đôi — chuyện này không hoàn toàn nằm trong tay con người.'],
        ['Lá giữa', 'Lá 3 là trái tim của câu trả lời. Ngay cả khi kết quả đếm là có, lá này cho biết đó là kiểu "có" như thế nào.'],
        ['Các chất bài', 'Một hàng nghiêng hẳn về một chất cho biết lĩnh vực nào thật sự quyết định kết quả — Cốc là cảm xúc, Kiếm là lời nói, Tiền là thực tế, Gậy là liệu có ai chịu hành động không.']],
  read: 'Đưa kết quả đếm trước, rồi giải thích ngay bằng lá 3 và thế trận chất bài. Một chữ "có" hay "không" trơ trọi không phải là luận bài; đó là tung đồng xu có kèm hình.',
  note: 'Nếu bạn không luận lá ngược thì cách này không dùng được. Hãy dùng trải bài ba lá và trả lời câu hỏi bằng ý nghĩa của bài.' },

{ id: 'tarot-time', sys: 'tarot', kinds: ['timing'], n: 4, lay: LAY.four,
  name: 'Thời điểm — bốn giai đoạn',
  when: '"Khi nào chuyện đó xảy ra?" Tarot dở trong việc gọi tên ngày tháng và giỏi trong việc mô tả trình tự, nên trải bài này hỏi *mỗi giai đoạn có gì* thay vì *ngày nào*.',
  ask: 'Hãy quyết định đơn vị trước khi xào bài và nói to lên: bốn tuần, hay bốn tháng, hay bốn quý. Đổi đơn vị sau khi đã thấy bài là cách nhanh nhất để trải bài trở nên vô nghĩa.',
  pos: [['1 · Giai đoạn một', 'Khoảng thời gian này chứa điều gì. Nếu thứ bạn hỏi xuất hiện ngay đây thì nó đang rất gần.'],
        ['2 · Giai đoạn hai', 'Khoảng tiếp theo. Hãy để ý các lá chuyển động — Gậy, các Kỵ Sĩ, Cỗ Xe, Bánh Xe — vì chúng cho thấy mọi thứ thật sự đang dịch chuyển.'],
        ['3 · Giai đoạn ba', 'Khoảng sau đó nữa. Một loạt lá đứng yên ở đây (các lá Bốn, Người Treo Ngược, Bảy Tiền) nghĩa là phải đợi lâu hơn mong đợi.'],
        ['4 · Giai đoạn bốn', 'Cuối khung thời gian bạn hỏi. Nếu tới đây vẫn chưa có gì tới, câu trả lời trung thực là "không nằm trong khung này" — và hãy nói thẳng như vậy.']],
  read: 'Tìm lá trả lời cho câu hỏi rồi đọc xem nó rơi vào vị trí nào. Đó chính là thời điểm. Nếu không lá nào trả lời, thì cách luận trung thực là sự việc không nằm trong khung này — và khách được phục vụ tốt hơn khi nghe điều đó thay vì một lời đoán cho êm tai.',
  note: 'Đừng bao giờ hứa một ngày cụ thể. Hãy đưa giai đoạn, đưa điều kiện, và nói thẳng rằng thời điểm là thứ tarot làm kém tin cậy nhất.' },

{ id: 'tarot-choice', sys: 'tarot', kinds: ['decision'], n: 5, lay: LAY.choice,
  name: 'Hai con đường — một quyết định',
  when: 'Một lựa chọn A hay B thật sự: hai công việc, ở lại hay rời đi, nói ra hay im lặng. Nó so sánh hai tương lai thay vì dự đoán một.',
  ask: 'Hãy gọi tên cả hai phương án trước khi xào bài, và gán một phương án cho nhánh trái, một cho nhánh phải. Đừng quyết định cái nào là cái nào sau khi đã thấy bài.',
  pos: [['1 · Bạn lúc này', 'Bạn đang đứng ở đâu, và bạn đang thật sự chọn giữa những gì — thường không phải thứ bạn nói ra.'],
        ['2 · Đường A, bước đầu', 'Điều xảy ra ngay sau đó nếu bạn chọn phương án thứ nhất.'],
        ['3 · Đường A, dẫn tới đâu', 'Con đường đó đi tới đâu. Hãy đọc chung với lá 2 như một chuyển động duy nhất.'],
        ['4 · Đường B, bước đầu', 'Điều xảy ra ngay sau đó nếu bạn chọn phương án thứ hai.'],
        ['5 · Đường B, dẫn tới đâu', 'Con đường đó đi tới đâu.']],
  read: 'Hãy so sánh hai nhánh theo cặp, đừng so như bốn lá rời. Cách luận sạch hơn thường không phải "nhánh nào dễ chịu hơn" mà là "nhánh nào trung thực về cái giá của nó" — một con đường bước đầu khó nhưng kết thúc đẹp thường hơn hẳn một con đường khởi đầu êm.',
  note: 'Bài không chọn thay. Bài mô tả hai tương lai; quyết định vẫn thuộc về người hỏi.' },

{ id: 'tarot-rel7', sys: 'tarot', kinds: ['love'], n: 7, lay: LAY.rel7,
  name: 'Hai phía — mối quan hệ',
  when: 'Mọi câu hỏi hai người mà bạn cần tách bạch hai phía: một cặp đôi, một mối mập mờ, một lần giận nhau, kể cả quan hệ đồng nghiệp. Sức mạnh của nó là nó không cho phép trộn hai người vào làm một.',
  ask: 'Hãy gọi tên ai ở cột trái và ai ở cột phải trước khi xào bài. Cột trái thường là người đi hỏi.',
  pos: [['1 · Bạn: cảm thấy', 'Điều bạn thật sự cảm thấy, nằm dưới điều bạn nói là mình cảm thấy.'],
        ['2 · Bạn: suy nghĩ', 'Điều bạn tự nói với mình về chuyện này. Thường vênh với lá 1, và chính khoảng vênh đó là phần đáng luận.'],
        ['3 · Bạn: hành động', 'Bạn đang cư xử thế nào trên thực tế — tức là phần người kia nhìn thấy.'],
        ['4 · Họ: cảm thấy', 'Họ cảm thấy gì. Hãy luận thẳng; đừng làm nhẹ đi chỉ vì người hỏi đang ngồi ngay đó.'],
        ['5 · Họ: suy nghĩ', 'Họ đang tự lý giải chuyện này ra sao.'],
        ['6 · Họ: hành động', 'Họ đang thật sự làm gì — và đây là phần duy nhất bạn có bằng chứng.'],
        ['7 · Giữa hai người', 'Bản thân mối quan hệ như một thực thể thứ ba — phần đất chung, hoặc thứ đang nằm chắn giữa.']],
  read: 'Đọc dọc từng cột trước, rồi mới đọc ngang. Phép so sánh hữu ích nhất là lá 3 với lá 6: mỗi bên đang *làm* gì. Cảm xúc có thể bị đọc sai; hành vi mới là thứ thật sự diễn ra.',
  note: 'Nếu ba lá 4–6 toàn là bài Hoàng gia hoặc toàn Cốc, bạn đang luận tính khí của họ chứ chưa luận ý định — hãy cân nhắc rút thêm một lá làm rõ họ định làm gì.' },

{ id: 'tarot-celtic', sys: 'tarot', kinds: ['general', 'advanced'], n: 10, lay: LAY.celtic,
  name: 'Celtic Cross — mười lá',
  when: 'Một tình huống lớn và rối mà ba lá không chứa nổi. Đừng dùng nó làm mặc định — mười lá cho một câu hỏi đơn giản chỉ tạo ra nhiễu, không tạo ra chiều sâu.',
  ask: 'Một tình huống, đặt vấn đề rộng: "Cho tôi thấy chuyện gì đang diễn ra với ___." Celtic Cross trả lời một bức tranh, không trả lời một câu hỏi.',
  pos: [['1 · Trái tim vấn đề', 'Cốt lõi của sự việc như nó đang là.'],
        ['2 · Lá chắn ngang', 'Đặt nằm ngang trên lá 1. Thứ làm phức tạp thêm — đôi khi là trở ngại, đôi khi là sự giúp đỡ bạn không xin.'],
        ['3 · Bên dưới', 'Gốc rễ. Điều nằm dưới chuyện này và nhiều khả năng đã có từ trước nó.'],
        ['4 · Phía sau', 'Thứ đang đi ra khỏi tình huống — quá khứ gần, vẫn còn níu lại.'],
        ['5 · Bên trên', 'Thứ ở ngoài sáng: mục tiêu, lý tưởng, hoặc điều ai cũng nhìn thấy.'],
        ['6 · Phía trước', 'Thứ sắp tới, trong ngắn hạn.'],
        ['7 · Chính bạn', 'Bạn đang xuất hiện thế nào trong chuyện này — tư thế của bạn, không phải cảm xúc của bạn.'],
        ['8 · Môi trường', 'Người khác, và những điều kiện quanh bạn mà bạn không kiểm soát.'],
        ['9 · Hy vọng và nỗi sợ', 'Theo truyền thống là cả hai cùng lúc, vì thường chúng là một lá bài nhìn từ hai phía.'],
        ['10 · Kết quả', 'Chuyện này đang đi tới đâu, xét toàn bộ những gì ở trên. Đọc nó sau cùng, và đọc nó đối chiếu với lá 1.']],
  read: 'Đọc phần chữ thập (1–6) như là tình huống, và phần cột (7–10) như là quan hệ của bạn với tình huống đó. Nếu lá 1 và lá 10 kể cùng một câu chuyện thì sự việc đã an bài. Nếu chúng mâu thuẫn, lá 9 thường giải thích vì sao.',
  note: 'Đừng đụng tới trải bài này khi ba lá còn chưa nhuần. Mười vị trí nhớ lơ mơ còn tệ hơn ba vị trí nắm chắc.' },

{ id: 'tarot-clarify', sys: 'tarot', kinds: ['general'], n: 2, lay: LAY.two,
  name: 'Lá làm rõ — rút thêm một hoặc hai',
  when: 'Khi một vị trí trong trải bài đã xong thật sự không luận nổi, hoặc khi một lá có nhiều nhánh nghĩa và bạn cần biết nhánh nào đang áp dụng. Đây là một kỹ thuật, không phải một trải bài.',
  ask: 'Hãy chỉ đúng vào lá đó và hỏi một câu cụ thể về nó: "Bảy Kiếm ở *đây* nghĩa là gì?" Đừng bao giờ hỏi "cho tôi một câu trả lời đẹp hơn".',
  pos: [['1 · Lá làm rõ', 'Hãy đọc lá này như một tính từ gắn vào lá gốc, không phải một câu trả lời mới. Nó bổ nghĩa; nó không thay thế.'],
        ['2 · Lá làm rõ thứ hai', 'Chỉ rút khi lá đầu thật sự không giải quyết được. Hai là giới hạn.']],
  read: 'Trước khi rút, hãy nói to xem thế nào thì được tính là một câu trả lời. Chỉ riêng thói quen đó đã tách bạch giữa việc làm rõ và việc rút bừa cho tới khi vừa ý.',
  note: 'Rút mãi cho tới khi thích câu trả lời là cách phổ biến nhất khiến người luận mất niềm tin vào chính bộ bài của mình. Hai lá làm rõ, rồi dừng.' },

/* ------------------------------------------------------- lenormand ---- */
{ id: 'len-1', sys: 'len', kinds: ['general'], n: 1, lay: LAY.one,
  name: 'Một lá',
  when: 'Lá của ngày, hoặc một câu hỏi cực hẹp. Bài Lenormand là danh từ, nên một lá cho bạn một chủ thể mà không có câu văn nào quanh nó.',
  ask: 'Hãy hỏi về một sự vật, đừng hỏi về một cảm giác: "Hôm nay là ngày của chuyện gì?" Một lá Lenormand gọi tên một chủ đề rồi dừng lại ở đó.',
  pos: [['Chủ thể', 'Danh từ. Hãy hiểu theo nghĩa đen trước — Con Thuyền nghĩa là đi xa hoặc khoảng cách, trước khi nó mang bất cứ nghĩa biểu tượng nào.']],
  read: 'Một lá là cách luận Lenormand yếu nhất, vì cả hệ thống này vận hành bằng sự kết hợp. Nếu có thể rút hai lá thay vì một, hãy rút hai.',
  note: 'Đừng luận bài Lenormand theo lối luận tarot. Không có lá ngược và không có hành trình nội tâm — lá bài là một vật thể trong đời bạn.' },

{ id: 'len-2', sys: 'len', kinds: ['general', 'love', 'career'], n: 2, lay: LAY.two,
  name: 'Hai lá — cặp bài',
  when: 'Đơn vị nền tảng của Lenormand, và là kỹ thuật mà mọi trải bài lớn hơn đều được dựng lên từ đó. Dùng cho một câu hỏi cụ thể có một câu trả lời cụ thể.',
  ask: 'Một câu hỏi hẹp. Cặp bài cho bạn một danh từ và một từ bổ nghĩa, nên câu trả lời tới dưới dạng một cụm ngắn, không phải một bài luận.',
  pos: [['1 · Chủ thể', 'Danh từ. Đây là thứ mà câu trả lời nói về.'],
        ['2 · Từ bổ nghĩa', 'Lá này mô tả lá 1. Trái Tim + Ngọn Núi là tình yêu bị chặn; Ngọn Núi + Trái Tim là một chướng ngại liên quan tới chuyện tình cảm — đổi thứ tự là đổi nghĩa.']],
  read: 'Hãy đọc to cặp bài như hai từ ghép lại: "lá thư + quan tài" thành "tin xấu bằng văn bản". Nếu bạn không nói được nó trong một cụm ngắn, nghĩa là bạn đang nghĩ quá nhiều.',
  note: 'Đây là thói quen quan trọng nhất trong Lenormand: luôn luôn đọc theo cặp, trước khi đọc từng lá riêng.' },

{ id: 'len-3', sys: 'len', kinds: ['general', 'love', 'career'], n: 3, lay: LAY.three,
  name: 'Ba lá — hàng ngang',
  when: 'Cách luận Lenormand dùng hằng ngày. Nó trả lời một câu hỏi bằng một câu hoàn chỉnh mà vẫn đủ nhỏ để luận sạch.',
  ask: 'Một câu hỏi rõ ràng về một chuyện. Ba lá là đủ cho một tình huống và hướng đi của nó.',
  pos: [['1 · Chủ thể', 'Sự việc là gì. Thường là người hoặc thứ bạn đang hỏi tới.'],
        ['2 · Lá giữa', 'Trái tim của câu trả lời. Trong hàng ba lá, lá giữa nặng ký nhất, và nó cũng được bổ nghĩa bởi cả hai lá bên cạnh.'],
        ['3 · Hướng đi', 'Chuyện này đi tới đâu, hoặc nó dẫn tới kết quả gì.']],
  read: 'Đọc theo ba cách: như một câu từ trái sang phải; như cặp 1+2; và như cặp 2+3. Chỗ nào cả ba cách đọc đều đồng ý thì đó là câu trả lời. Chỗ nào chúng vênh nhau thì lá 2 quyết định.',
  note: 'Thời điểm nằm ở lá bài chứ không nằm ở vị trí — Kỵ Mã là vài ngày, Con Thuyền là vài tháng, Mỏ Neo là lâu dài. Một hàng ba lá vẫn trả lời được câu "khi nào" nếu có lá chỉ thời gian rơi vào.' },

{ id: 'len-5', sys: 'len', kinds: ['general', 'love', 'career', 'decision'], n: 5, lay: LAY.five,
  name: 'Năm lá — hàng ngang',
  when: 'Một câu trả lời đầy đủ hơn cho một câu hỏi: bối cảnh, chính sự việc, và nó đi về đâu. Đây là trải bài Lenormand đa dụng tốt nhất, một khi đọc cặp đã thành phản xạ.',
  ask: 'Một câu hỏi, đặt rộng hơn so với hàng ba lá. Năm lá chứa được cả nguyên nhân lẫn kết quả bên cạnh chủ thể.',
  pos: [['1 · Bối cảnh', 'Điều nằm phía sau chuyện này — quá khứ, hoặc khung cảnh mà sự việc đang nằm trong đó.'],
        ['2 · Điều đang hình thành', 'Đọc thành cặp với lá 1 và với lá 3.'],
        ['3 · Lá trung tâm', 'Cốt lõi của câu trả lời. Mọi lá còn lại trong hàng đều đang mô tả lá này.'],
        ['4 · Điều đang tới', 'Đọc thành cặp với lá 3 và với lá 5.'],
        ['5 · Kết quả', 'Chuyện này đáp xuống đâu.']],
  read: 'Đọc lá trung tâm trước, rồi tới các cặp hai bên nó, rồi đối chiếu hai đầu hàng với nhau. Cặp lá 1 và lá 5 thường cho bản tóm tắt ngắn nhất của cả trải bài.',
  note: 'Vị trí của lá Người Đàn Ông hoặc Người Phụ Nữ trong hàng rất quan trọng: gần đầu hàng thì họ là nguyên nhân, gần cuối hàng thì họ là kết quả, và hướng họ quay mặt cho biết họ đang hướng về điều gì.' },

{ id: 'len-yesno', sys: 'len', kinds: ['yesno'], n: 3, lay: LAY.three,
  name: 'Có / Không — ba lá',
  when: 'Một câu hỏi đóng. Lenormand trả lời có/không thoải mái hơn tarot, vì các lá của nó mang sẵn một sắc thái tích cực hoặc tiêu cực đã định.',
  ask: 'Một câu hỏi đóng về một chuyện. Trước khi rút, hãy xác định xem một chữ "có" thì trên thực tế sẽ trông như thế nào.',
  pos: [['1–3 · Sắc thái', 'Đếm số lá tích cực so với tiêu cực. Hai hoặc ba lá tích cực là có; hai hoặc ba lá tiêu cực là không. Lá trung tính lấy sắc thái từ các lá bên cạnh.'],
        ['Chữ "có" mạnh', 'Chìa Khóa, Mặt Trời và Cỏ Ba Lá vượt lên trên kết quả đếm. Riêng Chìa Khóa gần như là một chữ "có" dứt khoát ở bất cứ đâu nó rơi vào.'],
        ['Chữ "không" mạnh', 'Quan Tài, Ngọn Núi, Lưỡi Hái, Đàn Chuột và Cây Thánh Giá cũng vượt lên trên kết quả đếm, theo chiều ngược lại. Riêng Ngọn Núi nghĩa là "không phải bằng đường này".']],
  read: 'Đưa câu trả lời, rồi đọc ba lá thành một hàng để giải thích *vì sao* — một chữ có/không trong Lenormand luôn phải đi kèm lý do của nó.',
  note: 'Chỉ có chín lá tiêu cực và tám lá tích cực là mọi nguồn đều đồng ý; bảng sắc thái ở tab Lenormand cho biết đó là lá nào, và lá nào còn tranh cãi. Hãy đếm những lá đã thống nhất và coi phần còn lại là trung tính. Muốn một câu có/không tự giải thích được, dùng trải French Cross bên dưới.' },

{ id: 'len-9', sys: 'len', kinds: ['general', 'love', 'career', 'advanced'], n: 9, lay: LAY.box9,
  name: 'Chín lá — ô vuông',
  when: 'Một bức tranh đầy đủ về một tình huống, mà không phải cam kết trải cả Grand Tableau. Đây là trải bài "câu hỏi nghiêm túc" tiêu chuẩn của Lenormand.',
  ask: 'Một tình huống, hỏi rộng. Chia ba hàng ba lá, rải từ trái sang phải, từ trên xuống dưới.',
  pos: [['Trung tâm (5)', 'Trái tim của sự việc. Hãy đọc lá này trước — mọi lá còn lại trong ô đều đang bổ nghĩa cho nó.'],
        ['Hàng trên (1–3)', 'Thứ ở phía trên tình huống: quá khứ, hoặc những gì đã biết và đang ở ngoài sáng.'],
        ['Hàng giữa (4–6)', 'Hiện tại. Đây là hàng quan trọng nhất của ô.'],
        ['Hàng dưới (7–9)', 'Thứ ở phía dưới hoặc phía trước: kết quả, hoặc những gì còn ẩn.'],
        ['Các cột', 'Cột trái là quá khứ hoặc nguyên nhân; cột giữa là chính sự việc; cột phải là tương lai hoặc kết quả.'],
        ['Hai đường chéo', 'Cả hai đường chéo đều đi qua lá trung tâm và mô tả các ảnh hưởng ngầm lên nó.'],
        ['Bốn góc (1, 3, 7, 9)', 'Đọc bốn góc cùng nhau như một bản tóm tắt của cả ô.']],
  read: 'Hãy làm theo thứ tự này: lá trung tâm, rồi hàng giữa, rồi các hàng còn lại, rồi các cột, rồi hai đường chéo, rồi bốn góc. Mỗi lượt đọc phải làm sắc thêm cùng một câu trả lời, chứ không phải sinh ra một câu trả lời mới.',
  note: 'Nếu một lượt đọc mâu thuẫn với tất cả những lượt trước, nghĩa là bạn đã bắt đầu suy diễn thay vì luận bài. Hãy quay lại lá trung tâm.' },

{ id: 'len-gt', sys: 'len', kinds: ['advanced'], n: 36, lay: LAY.gt,
  name: 'Grand Tableau — cả 36 lá',
  when: 'Một trải bài tổng quan cả cuộc sống, hoặc một tình huống có rất nhiều bộ phận chuyển động. Đây là phương pháp Lenormand đầy đủ, và cũng là thứ lâu học nhất.',
  ask: 'Ở đây bạn không hỏi một câu hẹp. Bạn trải cả bộ bài ra và để nó mô tả toàn cảnh — rồi trả lời từng câu hỏi cụ thể từ bên trong bức tranh đó.',
  pos: [['Cách bày', 'Cả 36 lá: bốn hàng tám lá, rồi một hàng cuối bốn lá đặt giữa bên dưới. Rải từ trái sang phải, từ trên xuống dưới.'],
        ['Tìm lá đại diện', 'Xác định lá Người Đàn Ông hoặc Người Phụ Nữ — lá nào đại diện cho người bạn đang luận. Cả trải bài được tổ chức quanh vị trí họ rơi vào.'],
        ['Các lá kề', 'Những lá chạm trực tiếp vào lá đại diện, kể cả theo đường chéo, là những lá quan trọng nhất trong cả trải bài. Đọc chúng trước tiên.'],
        ['Hướng', 'Thứ nằm phía trước lá đại diện là điều đang ở phía trước họ; thứ nằm phía sau là quá khứ. Phía trên là điều họ đang bận tâm, phía dưới là điều đang nâng đỡ hoặc đang đè lên họ.'],
        ['Các "ngôi nhà"', 'Mỗi trong 36 vị trí còn mang nghĩa của lá bài "thuộc về" vị trí đó — ô số 24 là Ngôi Nhà của Trái Tim, nên lá nào rơi vào đó cũng nói về chuyện tình cảm.'],
        ['Nước mã', 'Những lá cách lá đại diện đúng một nước đi của quân mã cờ vua mang các ảnh hưởng ngầm. Kỹ thuật nâng cao; hãy để dành cho tới khi phần còn lại đã vững.'],
        ['Soi chiếu', 'Các lá đối diện nhau qua một hàng, và các lá nằm ngay trên và ngay dưới nhau, đều bình luận lẫn nhau.']],
  read: 'Hãy đọc theo lớp: lá đại diện và các lá kề nó, rồi hàng của nó, rồi ngôi nhà của chủ đề được hỏi, rồi bốn góc của bảng. Trả lời từng câu hỏi một từ cùng một bố cục, thay vì cố đọc tuần tự cả 36 lá.',
  note: 'Đừng bắt đầu từ đây. Hãy đi qua cặp bài, hàng ba lá và ô chín lá trước — Grand Tableau chính là những kỹ thuật đó được áp dụng ba mươi sáu lần.' }

];
