/* ============================ UI strings ============================
   Vietnamese is the first language of the app. Keep every line short and
   spoken; the reader is a client on a phone, not a student. */
const STR = {
  vi: {
    lang: 'EN',
    nav: { home: 'Trang chủ', pick: 'Rút bài', learn: 'Học', book: 'Đặt lịch', me: 'Tôi' },

    feedTitle: 'Dự đoán mới',
    feedEmpty: 'Chưa có bài nào. Quay lại sau nhé.',
    feedOffline: 'Đang xem bản đã lưu. Mở mạng để cập nhật.',
    pinned: 'Ghim',
    readMore: 'Đọc thêm',
    readLess: 'Thu gọn',
    share: 'Chia sẻ',
    copied: 'Đã sao chép',
    forYouIf: 'Dành cho bạn nếu',
    forYou: 'Dành cho bạn',
    initials: 'tên bắt đầu bằng',
    signs: 'cung',
    cardsDrawn: 'Lá bài trong bài này',
    ctaPick: 'Rút một lá cho riêng bạn',
    ctaBook: 'Đặt lịch xem bài',
    backToFeed: 'Về trang chủ',
    notFound: 'Không tìm thấy bài này.',
    helloGuest: 'Chào bạn',
    hello: (n) => 'Chào ' + n,
    setupProfile: 'Cho Nabu biết ngày sinh và điều bạn quan tâm. Trang chủ sẽ chọn nội dung hợp với bạn.',
    setupBtn: 'Tạo hồ sơ',
    yourSign: 'Cung Mặt Trời của bạn',
    signCard: 'Lá tarot của cung bạn',
    lifePath: 'Số đường đời',
    readSign: 'Đọc về cung của bạn',
    forInterests: 'Có thể bạn quan tâm', horoMonth: 'Dự đoán tháng này', horoWeek: 'Dự đoán tuần này', horoNeedBirthday: 'Nhập ngày sinh ở mục Tôi để xem dự đoán theo cung của bạn.', horoUpdating: 'Dự đoán đang được cập nhật. Bạn quay lại sau nhé.', horoSource: 'Theo', horoUpdated: 'cập nhật',

    pickToday: 'Rút một lá bài hôm nay',
    pickTitle: 'Năng lượng hiện tại của bạn',
    pickIntro: 'Hít một hơi thật sâu. Nghĩ về hôm nay. Rồi chạm vào một lá bài.',
    focusLabel: 'Bạn đang nghĩ về',
    focus: { general: 'Chung', love: 'Tình cảm', work: 'Công việc', study: 'Học tập', money: 'Tiền bạc' },
    tapACard: 'Chạm vào một lá',
    redraw: 'Xào lại và rút lá khác',
    yourCard: 'Lá bài của bạn',
    energyNow: 'Năng lượng lúc này',
    energyLine: (kws) => 'Lúc này bạn đang mang năng lượng: ' + kws + '.',
    cardSays: 'Lá bài nói gì',
    onTheCard: 'Trên lá bài',
    shadow: 'Mặt trái cần để ý',
    shadowLine: (kws) => 'Nếu năng lượng này quá đà, nó thành: ' + kws + '.',
    focusHead: (f) => 'Nếu bạn đang nghĩ về ' + f.toLowerCase(),
    noFocus: 'Chưa có bài giảng riêng cho chủ đề này với lá này. Bạn đọc phần năng lượng ở trên nhé.',
    quickNote: 'Đây là lời nhắn nhanh từ một lá bài. Muốn hiểu rõ chuyện của bạn, hãy đặt lịch xem bài đầy đủ.',
    shareCard: 'Chia sẻ lá bài',
    bookWithCard: 'Đặt lịch xem sâu hơn',
    learnCard: 'Đọc kỹ về lá này',
    shareText: (name, kws) => 'Lá bài hôm nay của mình: ' + name + '. Năng lượng: ' + kws + '. Xem lá bài này và rút thử tại ',

    learnTitle: 'Kho kiến thức',
    learnIntro: 'Tarot, Lenormand, chiêm tinh, manifestation và bói toán.',
    cats: { tarot: 'Tarot', lenormand: 'Lenormand', astro: 'Chiêm tinh', manifest: 'Manifestation', fortune: 'Bói toán' },
    catSub: { tarot: '78 lá + 13 trải bài · 300.000đ / 6 tháng', lenormand: '36 lá + 7 trải bài · 300.000đ / 6 tháng', astro: '12 cung, hành tinh, nhà', manifest: 'cách làm + giới hạn', fortune: 'thần số, chỉ tay, bài Tây' },
    courses: 'Khóa học', freeReads: 'Đọc miễn phí', lessonsIntro: (n) => 'Khóa học gồm ' + n + ' bài. Học theo thứ tự, mỗi bài một tuần là vừa.', markDone: 'Đánh dấu đã học xong', lessonDone: 'Đã học xong', journeyHint: 'Chạm vào một lá để mở trang của lá đó.', lenGridHint: 'Cả 36 lá. Chạm để xem từng lá.',
    aiIntro: 'Hỏi Nabu AI về điều bạn đang xem. Càng cụ thể càng tốt.', aiIntroLesson: 'Chỗ nào trong bài chưa hiểu, hỏi Nabu AI ở đây.', aiPlaceholder: 'Ví dụ: lá này nói gì về chuyện tình cảm của mình?', aiAsk: 'Hỏi', aiOnline: 'trả lời bằng AI', aiBuiltin: 'trả lời từ kho kiến thức', aiNote: 'Nabu AI trả lời cả câu hỏi thường lẫn tarot, chiêm tinh, thần số học, và tra cứu mạng khi cần. Chuyện riêng quan trọng, bạn đặt lịch với Nabu.', aiFallback: 'AI đang bận, đây là câu trả lời từ kho kiến thức.',
    aiSugCard: ['Lá này nói gì về tình cảm của mình?', 'Mình có nên tiếp tục không?', 'Khi nào chuyện này xảy ra?'], aiSugLesson: ['Ẩn Chính khác Ẩn Phụ thế nào?', 'Lá hoàng gia là ai?', 'Nếu mình không hiểu một lá thì làm sao?'], aiSugSign: ['Cung này hợp với cung nào?', 'Cung này trong tình yêu thế nào?', 'Mặt Trăng ở cung này là sao?'], aiSugNumbers: ['Số đường đời của mình nói gì?', 'Năm nay của mình là năm gì?', 'Số vận mệnh theo tên mình là gì?'], aiSugGeneral: ['Gã Khờ nghĩa là gì?', 'Sư Tử hợp với Bảo Bình không?', 'Số đường đời của mình?'],
    aiCardGeneral: (n) => 'Lá ' + n + ' đang nói về năng lượng chung của bạn lúc này.', aiCardFocus: (n, f) => 'Với câu hỏi về ' + f.toLowerCase() + ', lá ' + n + ' nói thế này:', aiCardWhy: 'Lá này mang năng lượng:', aiCardShadow: 'Mặt trái cần để ý:', aiYes: (n) => 'Nếu hỏi có hay không: ' + n + ' thiên về CÓ, nhưng một lá không quyết định được. Muốn rõ hơn, hãy đặt lịch xem bài.', aiNo: (n) => 'Nếu hỏi có hay không: ' + n + ' thiên về KHÔNG, hoặc chưa phải lúc. Một lá không quyết định được; muốn rõ hơn, hãy đặt lịch xem bài.', aiMaybe: (n) => 'Nếu hỏi có hay không: ' + n + ' không nghiêng hẳn về bên nào. Câu trả lời tuỳ vào việc bạn làm tiếp theo.', aiTiming: 'Về thời gian, một lá chỉ gợi ý nhịp, không cho ngày chính xác.', aiFound: 'Mình tìm thấy trong khóa học:', aiLessonNone: 'Mình chưa thấy phần nào khớp. Bạn thử hỏi bằng tên lá bài, hoặc một từ khóa trong bài học nhé.', aiChem: (a, b) => a + ' và ' + b + ':', aiCompatYes: 'Đây là một trong những cặp thường được xem là hợp.', aiCompatWork: 'Không nằm trong nhóm dễ hợp nhất, nhưng cung chỉ là một phần; bản đồ sao đầy đủ mới nói được nhiều hơn.', aiAbout: (n) => 'Về ' + n + ':', aiGeneralHelp: 'Mình chưa có câu trả lời sẵn cho câu này. Mình trả lời tốt nhất khi câu hỏi nhắc đến một lá bài, một cung hoàng đạo, một hành tinh, một nhà, một con giáp hay một con số.', aiOfflineHint: 'Chuyện riêng của bạn thì đặt lịch với Nabu để được xem kỹ.', aiBooking: 'Bạn xem bảng giá và chọn giờ ở mục Đặt lịch. Chọn gói, chọn giờ trống trên lịch, rồi gửi cho Nabu.',
    compatHead: { same: (a, b) => a + ' và ' + b + ': cùng một cung, nên rất dễ hiểu nhau. Câu trả lời ngắn là có, hai bạn hợp, miễn là đừng giống nhau cả ở tật xấu.', opposite: (a, b) => a + ' và ' + b + ' là hai cung đối diện nhau trên vòng hoàng đạo. Câu trả lời ngắn là có, hai bạn hút nhau rất mạnh, nhưng phải học cách cân bằng vì mỗi bên là mặt còn thiếu của bên kia.', good: (a, b) => a + ' và ' + b + ': câu trả lời ngắn là có, đây là một trong những cặp được xem là hợp nhau.', ok: (a, b) => a + ' và ' + b + ': khá hợp. Hai cung không cùng nguyên tố nhưng nuôi được nhau.', work: (a, b) => a + ' và ' + b + ': hợp được, nhưng phải cố gắng. Hai cung đứng ở góc vuông với nhau, nên dễ va chạm về cách làm.', neutral: (a, b) => a + ' và ' + b + ': ở mức trung bình. Không thuộc nhóm dễ hợp nhất, cũng không thuộc nhóm hay xung đột.' },
    compatWhy: { same: 'Lý do:', opposite: 'Lý do:', good: 'Lý do:', ok: 'Lý do:', work: 'Lý do:', neutral: 'Lý do:' },
    compatBring: (a, ka, b, kb) => a + ' mang vào mối quan hệ sự ' + ka + ', còn ' + b + ' mang sự ' + kb + '.', compatTipGood: 'Lời khuyên: hãy giữ cho mối quan hệ có chút thử thách và đừng lười giao tiếp, vì cặp dễ hợp thường chủ quan.', compatTipOpp: 'Lời khuyên: hãy xem điểm khác biệt là thứ bổ sung cho mình thay vì thứ phải sửa ở người kia.', compatTipWork: 'Lời khuyên: hãy nói rõ nhu cầu của mình bằng lời, đừng đợi người kia đoán. Cung Mặt Trời chỉ là một phần; bản đồ sao đầy đủ sẽ nói được nhiều hơn.',
    compatWhich: (a) => a + ' thường hợp nhất với:', compatAsk: 'Bạn muốn xem cặp cụ thể nào thì nhắc tên cung kia trong câu hỏi nhé.',
    strengths: 'Điểm mạnh', challenges: 'Điểm cần để ý', compat: 'Thường hợp với', moonSign: 'Mặt Trăng ở cung này', risingSign: 'Cung Mọc ở cung này',
    numExpr: 'Số vận mệnh (theo tên)', numSoul: 'Số linh hồn', numPers: 'Số nhân cách', numYear: 'Năm cá nhân', numBirthday: 'Số ngày sinh', numName: 'Họ tên đầy đủ (khai sinh)', numNameHint: 'Tính theo bảng Pythagoras, bỏ dấu tiếng Việt, Đ đọc là D.',
    fortuneIntro: 'Năm cách xem cũ, làm mới bằng hình. Chạm để chơi thử.', readMoreTitle: 'Đọc thêm', numIntro: 'Chạm vào một số để xem nó nói gì. Số của bạn được đánh dấu.', numTap: 'Chạm vào một số ở trên.', numYours: 'Số của bạn', numCycle: 'Vòng 9 năm của bạn', numCycleHint: 'Mỗi năm cá nhân là một bước trong vòng 9 năm. Năm 1 gieo, năm 9 gặt và buông.', numHow: 'Cách tính',
    palmIntro: 'Chạm vào một đường trên bàn tay, hoặc chọn tên bên dưới. Xem tay thuận là "hiện tại", tay còn lại là những gì bạn mang theo từ khi sinh ra.', palmLines: 'Các đường', palmMounts: 'Các gò', palmShapes: 'Bốn hình dáng tay', palmShapesHint: 'Nhìn lòng bàn tay vuông hay dài, ngón ngắn hay dài. Đây là bước đầu tiên của mọi lần xem tay.',
    pcIntro: 'Bài Tây có hai cách đọc. Cách truyền thống có bộ nghĩa riêng cho 52 lá, đã dùng từ trước khi tarot phổ biến. Cách thứ hai mượn nghĩa Ẩn Phụ của tarot, vì hai bộ bài cùng một gốc: Cơ là Cốc, Rô là Tiền, Chuồn là Gậy, Bích là Kiếm. Chọn một lá để xem cả hai.', pcPick: 'Chọn một lá bài Tây', pcNote: 'Bài Tây thiếu Ẩn Chính và chỉ có ba lá hình mỗi chất, nên J thường được đọc như Kỵ Sĩ (một số người đọc như Tiểu Đồng), Q như Nữ Hoàng, K như Đức Vua.', pcTrad: 'Nghĩa truyền thống', pcTarotWay: 'Đọc theo tarot',
    teaIntro: 'Chạm vào từng vùng của tách để biết vị trí nói gì. Bên dưới là các hình thường gặp.', teaZones: { rim: 'Gần miệng', mid: 'Giữa tách', bottom: 'Đáy tách', handle: 'Gần quai' }, teaZoneText: { rim: 'Gần miệng tách: chuyện sắp tới, trong vài ngày hay vài tuần.', mid: 'Giữa tách: vài tuần đến vài tháng nữa.', bottom: 'Đáy tách: chuyện xa hơn, hoặc gốc rễ của vấn đề.', handle: 'Gần quai: chuyện liên quan trực tiếp đến bạn. Đối diện quai: người khác, bên ngoài.' }, teaSymbols: 'Các hình thường gặp', teaPractice: 'Thử một lần', teaPracticeHint: 'Bấm để nhận một hình ngẫu nhiên ở một vị trí, rồi tập đọc.', teaDraw: 'Rút một hình',
    animalIntro: 'Chạm vào một con giáp trên vòng. Con giáp của bạn được đánh dấu.', animalYours: 'con giáp của bạn', animalTrio: 'Tam hợp', animalClash: 'Tứ hành xung', animalYears: 'Các năm',
    reportTitle: 'Báo lỗi app', reportIntro: 'Có gì hiển thị sai, bấm không được, hay chữ khó hiểu? Kể cho Nabu ở đây.', reportWhat: 'Bạn gặp lỗi gì?', reportPlaceholder: 'Bạn đang ở màn hình nào, bấm vào đâu, và điều gì xảy ra?', reportContact: 'Cách liên lạc lại (không bắt buộc)', reportAuto: 'App tự đính kèm thông tin này để Nabu tìm lỗi nhanh hơn:', reportSend: 'Gửi báo lỗi', reportViaIg: 'Gửi qua Instagram', reportNeed: 'Bạn mô tả lỗi trước nhé.', reportSent: 'Đã gửi tới Nabu. Cảm ơn bạn!', reportNoChannel: 'Bạn cần đăng nhập để gửi trực tiếp, hoặc dùng mục Liên hệ bên dưới.', reportMsgHead: 'Báo lỗi app Nabu Tarot:', reportLink: 'Báo lỗi', rights: 'All rights reserved.', demoTag: 'Học thử miễn phí', demoIntro: 'Hai bài đầu mở sẵn để bạn xem cách học. Mở khóa để xem trọn bộ.', lessonN: (n) => 'Bài ' + n, lesson1: 'Tổng quan và cách học', lesson2: 'Lá bài đầu tiên', courseTabs: { cards: 'Các lá bài', spreads: 'Trải bài', guides: 'Bài đọc' },
    months6: 'tháng', adminAccess: 'Tài khoản quản trị của Nabu: toàn bộ khóa học đang mở.', accessUntil: (d) => 'Bạn có quyền xem đến ' + d + '.', courseExpired: (d) => 'Mã của bạn đã hết hạn ngày ' + d + '. Mua lại để xem tiếp.',
    buyCourse: 'Mua khóa học qua Instagram', buyHint: 'Tin nhắn mua khóa đã được sao chép. Sau khi chuyển khoản, Nabu gửi bạn mã mở khóa. Nhập mã ở dưới.',
    buyMsg: (n, p, m) => 'Chào Nabu, mình muốn mua ' + n + ' (' + p + ', ' + m + ' tháng).', unlock: 'Mở khóa', unlocked: 'Đã mở khóa', badCode: 'Mã không đúng. Bạn kiểm tra lại nhé.',
    myCourses: 'Khóa học của tôi', enterCode: 'Nhập mã mở khóa', noCourses: 'Bạn chưa có khóa học nào.', activeUntil: (d) => 'đang mở, đến ' + d, expiredOn: (d) => 'hết hạn ' + d,
    recommended: 'Gợi ý cho bạn',
    allCards: 'Tất cả các lá',
    majors: 'Ẩn Chính', minors: 'Ẩn Phụ',
    upright: 'Nghĩa xuôi', reversed: 'Nghĩa ngược',
    kwPos: 'Từ khóa tích cực', kwNeg: 'Từ khóa tiêu cực',
    questions: 'Các câu hỏi thường gặp',
    astroOf: 'Tương ứng chiêm tinh',
    lenTone: { pos: 'Tích cực', neu: 'Trung tính', neg: 'Tiêu cực' },
    lenCore: 'Nghĩa chính', lenLove: 'Tình cảm', lenWork: 'Công việc', lenWho: 'Chỉ người', lenTime: 'Thời gian', lenCombo: 'Cặp lá', lenCard: 'Lá bài Tây',
    lenNote: 'Lenormand là hệ khác tarot, có cách đọc riêng.',
    signDates: 'Ngày', element: 'Nguyên tố', mode: 'Tính chất', ruler: 'Sao chủ',
    signAbout: 'Tính cách', signLove: 'Trong tình cảm', signWork: 'Trong công việc', signTip: 'Lời nhắn',
    signCards: 'Lá tarot của cung này',
    astroNote: '12 cung, các hành tinh, 12 nhà và góc chiếu. Chạm vào một cung để đọc kỹ.',
    spreadWhen: 'Dùng khi nào', spreadAsk: 'Hỏi thế nào', spreadPos: 'Các vị trí', spreadRead: 'Cách đọc', spreadNote: 'Lưu ý',
    numerology: 'Thần số học của bạn',
    lifePathOf: (n) => 'Số đường đời ' + n,
    enterBirthday: 'Nhập ngày sinh ở mục Tôi để xem số đường đời và cung của bạn.',
    animal: 'Con giáp',
    animalNote: 'Tính theo năm dương lịch. Nếu bạn sinh trước Tết thì thuộc con giáp của năm trước.',

    bookTitle: 'Đặt lịch xem bài',
    priceTitle: 'Bảng giá', priceIntro: 'Chọn gói hợp với câu hỏi của bạn. Giá tính theo buổi, thanh toán chuyển khoản.',
    chooseService: '1. Chọn dịch vụ', serviceHint: 'Chạm vào gói bạn muốn xem. Chọn được nhiều gói một lúc. Chạm lại để bỏ.', needService: 'Bạn chọn ít nhất một gói dịch vụ trước nhé.', bookTip: 'Chạm vào một gói để chọn. Bạn có thể chọn nhiều gói cùng lúc. Nếu đổi ý, chỉ cần chạm vào gói đó thêm một lần nữa để bỏ chọn.', cartTitle: 'Các gói bạn đã chọn', cartEmpty: 'Bạn chưa chọn gói nào.', cartNeedsTopic: 'chưa chọn chủ đề', msgTotal: 'Tổng', topicFor: 'Chủ đề cho', topicNone: 'Phần này chỉ hiện khi bạn chọn một gói 1 chủ đề sẵn ở bước 1. Mỗi gói như vậy sẽ có một ô chọn chủ đề riêng.',
    optional: 'không bắt buộc', birthTime: 'Giờ sinh', birthHint: 'Tử vi cần giờ sinh càng chính xác càng tốt.', needBirth: 'Tử vi cần ngày sinh của bạn.',
    msgService: 'Dịch vụ', msgBirth: 'Ngày giờ sinh',
    chooseTopic: '2. Chọn chủ đề cho gói 1 chủ đề sẵn',
    presetTopics: 'Chủ đề sẵn',
    topicHint: 'Chỉ dành cho gói "1 chủ đề sẵn": chọn một trong 5 chủ đề, mỗi chủ đề là 5 câu hỏi Nabu sẽ trải bài. Bấm vào chủ đề để xem câu hỏi. Chuyện khác bạn ghi ở phần thông tin bên dưới.',
    ownTopic: 'Câu hỏi riêng',
    ownTopicHint: 'Bạn tự viết câu hỏi của mình.',
    chooseTime: '3. Chọn giờ hẹn',
    timeHint: (tz) => 'Chạm vào một ngày có chấm hồng, rồi chọn giờ (' + tz + '). Giờ nào đã có người đặt sẽ bị gạch.',
    noSlots: 'Ngày này không còn chỗ.',
    pickDay: 'Chọn một ngày có chấm hồng.',
    yourPick: 'Bạn chọn',
    yourDetails: '4. Thông tin của bạn',
    yourName: 'Tên bạn (hoặc biệt danh)',
    yourNote: 'Bạn muốn hỏi thêm gì?',
    notePlaceholder: 'Kể ngắn gọn chuyện của bạn, hoặc câu hỏi bạn muốn hỏi.',
    sendVia: '5. Gửi cho Nabu',
    sendHint: 'Tin nhắn được sao chép sẵn. Bấm vào ứng dụng, rồi dán vào ô chat.',
    sendInApp: 'Gửi yêu cầu đặt lịch',
    sending: 'Đang gửi...',
    sentOk: 'Đã gửi. Nabu sẽ xác nhận sớm. Bạn xem lại trong mục Tôi.',
    newsTitle: 'Bài viết', newsIntro: 'Tất cả bài Nabu đã đăng: dự đoán, chia sẻ, thông báo. Gõ để tìm.', searchPosts: 'Tìm trong bài viết…', noMatch: 'Không có bài nào khớp.', allPostsBtn: (n) => 'Xem tất cả bài viết (' + n + ')', watchOn: (s) => 'Xem video trên ' + s,
    addImage: 'Ảnh', addVideo: 'Video', videoPrompt: 'Dán link video (YouTube, Facebook, TikTok, Instagram):', imgNeedCloud: 'Bạn cần đăng nhập tài khoản admin để tải ảnh lên.', imgTooBig: 'Ảnh quá lớn, thử ảnh nhỏ hơn.', imgAdded: 'Đã thêm ảnh vào bài.', wrapPlaceholder: 'chữ', boxLabel: 'Hộp', formatHint: 'Chọn chữ rồi bấm B / U / H để in đậm, gạch dưới, tô sáng. H2 là tiêu đề nhỏ, Hộp là ô tiêu đề riêng. Ảnh tải thẳng vào bài; video dán link.',
    contactTitle: 'Liên hệ', contactLink: 'Liên hệ', contactIntro: 'Viết vài dòng cho Nabu, rồi chọn kênh bạn muốn gửi.', contactWhat: 'Bạn muốn nhắn gì?', contactPlaceholder: 'Ví dụ: mình muốn hỏi về gói xem bài, hoặc góp ý cho app…', contactChoose: 'Gửi qua:', contactApp: 'Nhắn trong app Nabu Tarot', contactNeed: 'Bạn viết vài dòng trước nhé.', contactSent: 'Đã gửi tới Nabu. Bạn xem trả lời trong mục Tôi.', contactCopied: 'Tin nhắn đã được sao chép. Dán vào ô chat khi ứng dụng mở lên.',
    addToCalendar: 'Thêm vào lịch điện thoại', calendarHint: 'Lịch điện thoại sẽ nhắc bạn trước 24 giờ, 6 giờ, 1 giờ và 15 phút.', cancelBooking: 'Huỷ lịch', changeTitle: 'Đổi giờ hẹn', changeIntro: 'Chọn giờ mới bên dưới. Nabu sẽ duyệt lại trước khi giờ mới có hiệu lực.', currentSlot: 'Giờ hiện tại', sendChange: 'Gửi yêu cầu đổi giờ', changeSent: 'Đã gửi yêu cầu đổi giờ. Nabu sẽ duyệt lại sớm.', cancelSent: 'Đã gửi yêu cầu huỷ. Nabu sẽ xác nhận lại.', confirmCancel: 'Bạn muốn huỷ lịch hẹn này?', newSlotLabel: 'Giờ mới', adminApplyChange: 'Duyệt giờ mới', adminKeep: 'Giữ giờ cũ', adminApplyCancel: 'Duyệt huỷ', adminKeepBooking: 'Giữ lịch', reminderOn: 'Bật nhắc lịch hẹn trên máy này', reminderHint: 'Khi app đang mở, bạn sẽ được nhắc trước 24 giờ, 6 giờ, 1 giờ và 15 phút. Để chắc chắn, hãy thêm lịch hẹn vào lịch điện thoại.', upcoming: 'Lịch hẹn sắp tới', remindTitle: (w) => 'Lịch hẹn với Nabu ' + w, inHours: (h) => 'còn ' + h + ' giờ nữa', inMinutes: (m) => 'còn ' + m + ' phút nữa', allDays: 'Tất cả', bkOn: (d) => 'Lịch ngày ' + d, aiSettings: 'Cài đặt Nabu AI', aiKeyLabel: 'Khoá Gemini API (Google AI Studio)', aiKeyHint: 'Dán khoá vào đây và bấm lưu: mọi người dùng app sẽ được Nabu AI trả lời bằng Gemini, có tra cứu mạng khi còn hạn mức. Khoá được lưu trên đám mây của app, không nằm trong mã nguồn. Để trống thì app dùng bộ trả lời sẵn có.', aiKeySaved: 'Đã lưu. Nabu AI đang dùng Gemini.', saveKey: 'Lưu khoá', emojiBtn: 'Biểu tượng cảm xúc', imgTooBigChat: 'Ảnh quá lớn cho tin nhắn, thử ảnh nhỏ hơn.',
    saveSlot: 'Lưu giờ hẹn', changeSlot: 'Đổi giờ', slotSaved: 'Đã lưu giờ hẹn', summaryTitle: 'Tóm tắt yêu cầu', showMsg: 'Xem tin nhắn sẽ gửi', bkItems: 'Gói đã chọn',
    doneTitle: 'Đã gửi yêu cầu đặt lịch', doneBody: 'Nabu sẽ xem và xác nhận sớm. Bạn theo dõi trạng thái trong mục Tôi và sẽ nhận thông báo khi Nabu trả lời.', doneMe: 'Xem lịch hẹn của tôi', doneHome: 'Về trang chủ', doneMore: 'Đặt thêm lịch khác',
    draftKept: 'Lựa chọn của bạn được lưu tự động trên máy này, rời đi rồi quay lại vẫn còn.', openInLibrary: 'Đọc đầy đủ trong Kho kiến thức',
    aiGreet: 'Chào bạn! Mình là Nabu AI. Bạn có thể hỏi mình về một lá bài, một cung hoàng đạo, con số của bạn, hay bảo mình rút một lá cho hôm nay.', aiDrew: (n) => 'Mình rút cho bạn một lá: ' + n + '.', aiDrawHint: 'Muốn rút bài đầy đủ hơn, bạn vào mục Rút bài nhé.', aiSignOf: (s) => 'Với cung ' + s + ' của bạn:', aiThanks: 'Không có gì! Bạn cần gì cứ hỏi tiếp nhé.', aiTodayMoon: (m) => 'Hôm nay trăng đang ở pha ' + m + '.',
    needLogin: 'Bạn cần đăng nhập để gửi trong app. Hoặc gửi qua Instagram bên dưới.',
    viaInstagram: 'Nhắn qua Instagram',
    viaMessenger: 'Nhắn qua Messenger',
    viaZalo: 'Nhắn qua Zalo',
    viaEmail: 'Gửi email',
    copyMsg: 'Chỉ sao chép tin nhắn',
    needTopic: 'Bạn chọn một chủ đề trước nhé.',
    needSlot: 'Bạn chọn giờ hẹn trước nhé.',
    msgHello: 'Chào Nabu, mình muốn đặt lịch xem bài.',
    msgTopic: 'Chủ đề',
    msgTime: 'Giờ hẹn',
    msgName: 'Tên',
    msgNote: 'Câu hỏi thêm',
    msgCard: 'Lá mình vừa rút trong app',
    howItWorks: 'Cách đặt lịch',
    aboutTitle: 'Về Nabu Tarot',
    dow: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    months: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'],

    meTitle: 'Hồ sơ của bạn',
    meIntro: 'Ngày sinh và điều bạn quan tâm giúp trang chủ chọn đúng nội dung cho bạn.',
    localOnly: 'Hồ sơ đang lưu trên máy này.',
    accountsSoon: 'Nabu chưa bật đăng nhập. Khi bật, bạn đăng nhập bằng Google, Facebook hoặc email và mật khẩu; hồ sơ, tin nhắn và lịch hẹn sẽ đi theo bạn. Hiện hồ sơ lưu trên máy này.', accountsOff: 'Đăng nhập chưa mở.',
    signIn: 'Đăng nhập',
    signInWith: { google: 'Tiếp tục với Google', facebook: 'Tiếp tục với Facebook', email: 'Tiếp tục với email' },
    signOut: 'Đăng xuất',
    emailLabel: 'Email', passwordLabel: 'Mật khẩu',
    createAccount: 'Tạo tài khoản', haveAccount: 'Đã có tài khoản? Đăng nhập', noAccount: 'Chưa có tài khoản? Tạo mới',
    forgot: 'Quên mật khẩu', resetSent: 'Đã gửi email đặt lại mật khẩu.', authFbOff: 'Đăng nhập Facebook chưa mở: Meta yêu cầu Nabu đăng ký một ứng dụng nhà phát triển trước. Bạn dùng Google hoặc email giúp Nabu nhé.', authProviderOff: 'Cách đăng nhập này chưa được bật. Bạn dùng Google hoặc email nhé.', authDomain: 'Địa chỉ app chưa được Firebase cho phép. Nabu cần thêm angelale0211.github.io vào Authorized domains.', authCancelled: 'Bạn đã đóng cửa sổ đăng nhập.', authOtherProvider: 'Email này đã đăng ký bằng cách khác. Bạn đăng nhập bằng cách đó nhé.', authNetwork: 'Không có kết nối mạng. Bạn thử lại sau nhé.',
    authFail: 'Đăng nhập không thành công',
    displayName: 'Tên hiển thị',
    birthday: 'Ngày sinh',
    interests: 'Bạn quan tâm điều gì?',
    saveProfile: 'Lưu hồ sơ',
    saved: 'Đã lưu',
    myBookings: 'Lịch hẹn của tôi',
    noBookings: 'Bạn chưa có lịch hẹn nào.',
    status: { requested: 'Chờ xác nhận', confirmed: 'Đã xác nhận', declined: 'Không nhận', cancelled: 'Đã huỷ', change_requested: 'Chờ duyệt giờ mới', cancel_requested: 'Chờ duyệt huỷ' },
    messages: 'Nhắn tin với Nabu',
    messagesIntro: 'Nabu trả lời trong app. Bạn sẽ thấy chấm đỏ khi có tin mới.',
    messagesSoon: 'Nhắn tin trong app sẽ mở khi Nabu bật tài khoản. Bây giờ bạn nhắn qua Instagram nhé.',
    typeMsg: 'Viết tin nhắn...', sendPhoto: 'Gửi ảnh', holdToRecord: 'Bấm để ghi âm, bấm lại để gửi', recording: 'Đang ghi âm… bấm 🎤 lần nữa để gửi.', uploading: 'Đang gửi…', noMic: 'Máy này không cho ghi âm.', fileTooBig: 'Ảnh quá lớn (tối đa 8 MB).',
    send: 'Gửi',
    noMsgs: 'Chưa có tin nhắn. Bạn cứ hỏi, Nabu sẽ trả lời.',
    themeTitle: 'Giao diện', themes: { auto: 'Theo điện thoại', light: 'Sáng', dark: 'Tối' }, themeHint: 'Theo điện thoại: app tự đổi sáng/tối cùng máy của bạn.',
    installTitle: 'Cài app lên điện thoại',
    install: 'Trên iPhone: mở bằng Safari, bấm Chia sẻ, chọn "Thêm vào MH chính". Trên Android: bấm menu ⋮ rồi "Cài đặt ứng dụng".',
    dismiss: 'Đóng', tourMini: 'Hướng dẫn dùng app', tourOpen: 'Xem lại',
    offlineReady: 'App đã sẵn sàng dùng offline.',

    adminTitle: 'Bảng điều khiển',
    adminIntro: 'Trang này chỉ dành cho Nabu.',
    adminTabs: { posts: 'Bài đăng', schedule: 'Lịch rảnh', bookings: 'Đặt lịch', inbox: 'Tin nhắn', codes: 'Mã học' },
    codesIntro: 'Khách chuyển khoản xong, bạn tạo mã ở đây và gửi cho họ. Mã có ngày hết hạn ghi sẵn bên trong.', codeCourse: 'Khóa', codeStart: 'Bắt đầu từ', codeMonths: 'Số tháng', makeCode: 'Tạo mã', codeUntil: 'Hết hạn',
    token: 'GitHub token',
    tokenHint: 'Token chỉ lưu trên máy này. Xem README để tạo token.',
    saveToken: 'Lưu token',
    postDate: 'Ngày',
    postTitle: 'Tiêu đề',
    postBody: 'Nội dung',
    bodyHint: 'Cách một dòng trống để xuống đoạn.',
    postTitleEn: 'Tiêu đề (English, không bắt buộc)',
    postBodyEn: 'Nội dung (English, không bắt buộc)',
    postCards: 'Lá bài trong bài (chạm để chọn)',
    postTopics: 'Bài này hợp với ai quan tâm',
    searchCard: 'Tìm lá bài',
    markInitials: 'Tên bắt đầu bằng (cách nhau bằng dấu phẩy)',
    markSigns: 'Cung',
    pinPost: 'Ghim lên đầu',
    preview: 'Xem trước',
    publish: 'Đăng bài',
    publishing: 'Đang đăng...',
    published: 'Đã đăng. Trang của mọi người sẽ cập nhật trong vài phút.',
    publishFail: 'Đăng không thành công',
    copyJson: 'Sao chép JSON',
    existing: 'Bài đã đăng',
    edit: 'Sửa',
    del: 'Xoá',
    confirmDel: 'Xoá bài này?',
    newPost: 'Bài mới',
    needBody: 'Bài cần có tiêu đề và nội dung.',
    needToken: 'Bạn cần dán token trước.',
    weekly: 'Giờ rảnh mỗi tuần',
    weeklyHint: 'Chạm vào giờ để bật/tắt. Mỗi giờ là một buổi.',
    blocked: 'Ngày nghỉ',
    blockedHint: 'Những ngày này không nhận lịch dù có giờ rảnh.',
    addDay: 'Thêm ngày',
    bookedSlots: 'Giờ đã có khách',
    bookedHint: 'Khách đặt qua Instagram thì bạn thêm vào đây để giờ đó không hiện nữa.',
    leadDays: 'Nhận lịch sớm nhất sau (ngày)',
    horizonDays: 'Mở lịch trước (ngày)',
    saveSchedule: 'Lưu lịch rảnh', cloudContent: 'Bài đăng và lịch rảnh được lưu thẳng lên đám mây của app. Bạn bấm lưu là khách thấy ngay, không cần mã GitHub.',
    scheduleSaved: 'Đã lưu lịch. Khách sẽ thấy sau vài phút.',
    bookingsIntro: 'Yêu cầu khách gửi trong app. Xác nhận thì giờ đó tự khoá.',
    confirm: 'Xác nhận', decline: 'Từ chối',
    needFirebase: 'Mục này cần bật tài khoản (Firebase). Xem README.',
    adminLogin: 'Đăng nhập bằng email quản trị để xem mục này.',
    inboxEmpty: 'Chưa có cuộc trò chuyện nào.', inboxIntro: 'Mỗi dòng là một người. Chạm vào để mở riêng cuộc trò chuyện với người đó.', youLabel: 'Bạn', guestLabel: 'Khách', ownThread: 'tài khoản của bạn', ownThreadHint: 'Đây là hộp thư thử của chính tài khoản bạn. Tin nhắn của khách nằm trong bảng điều khiển, mục Tin nhắn, mỗi người một cuộc trò chuyện riêng.', adminSummary: 'Dành cho Nabu', unreadMsgs: 'tin nhắn chưa đọc', newBookings: 'lịch hẹn mới chờ xác nhận', openAdmin: 'Mở bảng điều khiển', enableNotif: 'Bật thông báo', notifOn: 'Thông báo đã bật. Bạn sẽ được báo khi có tin nhắn hoặc lịch hẹn mới.', notifDenied: 'Trình duyệt đang chặn thông báo của app. Bạn mở cài đặt trang web và cho phép thông báo nhé.', notifUnsupported: 'Trình duyệt này chưa hỗ trợ thông báo. Trên iPhone, bạn thêm app vào màn hình chính rồi mở lại từ đó.', notifHint: 'Bạn sẽ nhận thông báo khi có tin nhắn hoặc lịch hẹn mới, kể cả khi app đang chạy nền. Trên iPhone cần thêm app vào màn hình chính trước.', notifNewMsg: 'Tin nhắn mới từ ', notifNewBooking: 'Lịch hẹn mới từ ',
    reply: 'Trả lời',
    back: 'Quay lại',

    suitOf: { major: 'Ẩn Chính', wands: 'Gậy', cups: 'Cốc', swords: 'Kiếm', pentacles: 'Tiền' },
    zodiac: ['Bạch Dương', 'Kim Ngưu', 'Song Tử', 'Cự Giải', 'Sư Tử', 'Xử Nữ', 'Thiên Bình', 'Bọ Cạp', 'Nhân Mã', 'Ma Kết', 'Bảo Bình', 'Song Ngư'],
    dateFmt: (d) => d.getDate() + ' tháng ' + (d.getMonth() + 1) + ', ' + d.getFullYear(),
    dateShort: (d) => d.getDate() + '/' + (d.getMonth() + 1)
  },

  en: {
    lang: 'VI',
    nav: { home: 'Home', pick: 'Pick a card', learn: 'Learn', book: 'Book', me: 'Me' },

    feedTitle: 'Latest readings',
    feedEmpty: 'Nothing posted yet. Come back soon.',
    feedOffline: 'Showing the saved copy. Go online to update.',
    pinned: 'Pinned',
    readMore: 'Read more',
    readLess: 'Show less',
    share: 'Share',
    copied: 'Copied',
    forYouIf: 'For you if',
    forYou: 'For you',
    initials: 'your name starts with',
    signs: 'sign',
    cardsDrawn: 'Cards in this reading',
    ctaPick: 'Pick a card of your own',
    ctaBook: 'Book a reading',
    backToFeed: 'Back to home',
    notFound: 'This post was not found.',
    helloGuest: 'Hello',
    hello: (n) => 'Hello ' + n,
    setupProfile: 'Tell Nabu your birthday and what you care about. The home screen will pick content for you.',
    setupBtn: 'Set up my profile',
    yourSign: 'Your Sun sign',
    signCard: 'The tarot card of your sign',
    lifePath: 'Life path number',
    readSign: 'Read about your sign',
    forInterests: 'You may also like', horoMonth: 'This month\'s forecast', horoWeek: 'This week\'s forecast', horoNeedBirthday: 'Enter your birthday under Me to see the forecast for your sign.', horoUpdating: 'The forecast is being updated. Please check back soon.', horoSource: 'From', horoUpdated: 'updated',

    pickToday: 'Pick a card today',
    pickTitle: 'Your energy right now',
    pickIntro: 'Take a deep breath. Think about today. Then tap a card.',
    focusLabel: 'On your mind',
    focus: { general: 'General', love: 'Love', work: 'Work', study: 'Study', money: 'Money' },
    tapACard: 'Tap a card',
    redraw: 'Shuffle and pick again',
    yourCard: 'Your card',
    energyNow: 'Energy right now',
    energyLine: (kws) => 'Right now you carry this energy: ' + kws + '.',
    cardSays: 'What the card says',
    onTheCard: 'On the card',
    shadow: 'The shadow side',
    shadowLine: (kws) => 'When this energy runs too hot, it turns into: ' + kws + '.',
    focusHead: (f) => 'If ' + f.toLowerCase() + ' is on your mind',
    noFocus: 'No lecture notes for this topic with this card yet. Read the energy section above.',
    quickNote: 'This is a quick message from one card. For your own situation, book a full reading.',
    shareCard: 'Share this card',
    bookWithCard: 'Book a deeper reading',
    learnCard: 'Read about this card',
    shareText: (name, kws) => 'My card today: ' + name + '. Energy: ' + kws + '. See this card and draw your own at ',

    learnTitle: 'Knowledge library',
    learnIntro: 'Tarot, Lenormand, astrology, manifestation and fortune telling.',
    cats: { tarot: 'Tarot', lenormand: 'Lenormand', astro: 'Astrology', manifest: 'Manifestation', fortune: 'Fortune telling' },
    catSub: { tarot: '78 cards + 13 spreads · 300.000đ / 6 months', lenormand: '36 cards + 7 spreads · 300.000đ / 6 months', astro: '12 signs, planets, houses', manifest: 'methods + limits', fortune: 'numbers, palms, playing cards' },
    courses: 'Courses', freeReads: 'Free to read', lessonsIntro: (n) => 'The course has ' + n + ' sessions. Take them in order, about one a week.', markDone: 'Mark as done', lessonDone: 'Done', journeyHint: 'Tap a card to open its page.', lenGridHint: 'All 36 cards. Tap one to open it.',
    aiIntro: 'Ask Nabu AI about what you are looking at. The more specific, the better.', aiIntroLesson: 'Anything in this lesson unclear? Ask Nabu AI here.', aiPlaceholder: 'For example: what does this card say about my love life?', aiAsk: 'Ask', aiOnline: 'answered by AI', aiBuiltin: 'answered from the knowledge base', aiNote: 'Nabu AI answers everyday questions as well as tarot, astrology and numerology, and looks things up online when needed. For anything personal and important, book a reading with Nabu.', aiFallback: 'AI is busy; this answer comes from the knowledge base.',
    aiSugCard: ['What does this card say about my love life?', 'Should I keep going?', 'When will this happen?'], aiSugLesson: ['How do Majors differ from Minors?', 'Who are the court cards?', 'What if I do not understand a card?'], aiSugSign: ['Which signs suit this sign?', 'How is this sign in love?', 'What does the Moon in this sign mean?'], aiSugNumbers: ['What does my life path say?', 'What kind of year is this for me?', 'What is my destiny number from my name?'], aiSugGeneral: ['What does The Fool mean?', 'Do Leo and Aquarius get along?', 'What is my life path?'],
    aiCardGeneral: (n) => n + ' speaks about your general energy right now.', aiCardFocus: (n, f) => 'For a question about ' + f.toLowerCase() + ', ' + n + ' says:', aiCardWhy: 'The card carries this energy:', aiCardShadow: 'The shadow to watch:', aiYes: (n) => 'As a yes-or-no: ' + n + ' leans YES, but one card cannot decide it. For a clear answer, book a reading.', aiNo: (n) => 'As a yes-or-no: ' + n + ' leans NO, or not yet. One card cannot decide it; for a clear answer, book a reading.', aiMaybe: (n) => 'As a yes-or-no: ' + n + ' does not lean either way. The answer depends on what you do next.', aiTiming: 'On timing, one card only hints at a pace, never an exact date.', aiFound: 'Found in the course:', aiLessonNone: 'Nothing matched yet. Try a card name or a keyword from the lesson.', aiChem: (a, b) => a + ' and ' + b + ':', aiCompatYes: 'This is one of the pairs usually seen as a good match.', aiCompatWork: 'Not among the easiest pairs, but the Sun sign is one part; the full chart says much more.', aiAbout: (n) => 'About ' + n + ':', aiGeneralHelp: 'I do not have a ready answer for that. I answer best when the question names a card, a sign, a planet, a house, a zodiac animal or a number.', aiOfflineHint: 'For your own situation, book a reading with Nabu.', aiBooking: 'See the price list and pick a time under Book. Choose a package, a free slot on the calendar, then send it to Nabu.',
    compatHead: { same: (a, b) => a + ' and ' + b + ' are the same sign, so you understand each other easily. The short answer is yes, you match, as long as you do not share the same faults.', opposite: (a, b) => a + ' and ' + b + ' sit opposite each other on the zodiac. The short answer is yes, the attraction is strong, but you have to learn balance, because each of you is the missing half of the other.', good: (a, b) => a + ' and ' + b + ': the short answer is yes, this is one of the pairs usually seen as a good match.', ok: (a, b) => a + ' and ' + b + ': a fairly good match. The two signs are not the same element, but they feed each other.', work: (a, b) => a + ' and ' + b + ': it can work, but it takes effort. The two signs sit at a square angle, so you tend to clash over how things should be done.', neutral: (a, b) => a + ' and ' + b + ': an average match. Not among the easiest pairs, and not among the ones that clash most either.' },
    compatWhy: { same: 'Why:', opposite: 'Why:', good: 'Why:', ok: 'Why:', work: 'Why:', neutral: 'Why:' },
    compatBring: (a, ka, b, kb) => a + ' brings ' + ka + ' into the relationship, while ' + b + ' brings ' + kb + '.', compatTipGood: 'Advice: keep a little challenge alive and do not get lazy about talking, because easy matches tend to take each other for granted.', compatTipOpp: 'Advice: treat the differences as what completes you rather than what needs fixing in the other person.', compatTipWork: 'Advice: say what you need in words instead of waiting to be guessed. The Sun sign is only one part; the full chart says much more.',
    compatWhich: (a) => a + ' usually matches best with:', compatAsk: 'Name the other sign in your question if you want to check a specific pair.',
    strengths: 'Strengths', challenges: 'Watch out for', compat: 'Usually gets on with', moonSign: 'Moon in this sign', risingSign: 'Rising in this sign',
    numExpr: 'Expression number (from your name)', numSoul: 'Soul urge number', numPers: 'Personality number', numYear: 'Personal year', numBirthday: 'Birthday number', numName: 'Full name (as on your birth certificate)', numNameHint: 'Pythagorean table; Vietnamese tone marks dropped, Đ read as D.',
    fortuneIntro: 'Five old ways of reading, made visual. Tap to try one.', readMoreTitle: 'Read more', numIntro: 'Tap a number to see what it says. Your number is marked.', numTap: 'Tap a number above.', numYours: 'Your numbers', numCycle: 'Your 9-year cycle', numCycleHint: 'Each personal year is a step in a 9-year cycle. Year 1 plants, year 9 harvests and lets go.', numHow: 'How it is counted',
    palmIntro: 'Tap a line on the hand, or pick a name below. Read the dominant hand as "now" and the other as what you were born with.', palmLines: 'Lines', palmMounts: 'Mounts', palmShapes: 'The four hand shapes', palmShapesHint: 'Is the palm square or long, are the fingers short or long? This is the first step of every reading.',
    pcIntro: 'Playing cards can be read two ways. Traditional cartomancy has its own set of meanings for the 52 cards, in use since before tarot decks were common. The second way borrows the tarot Minors, because both decks share one root: Hearts are Cups, Diamonds Pentacles, Clubs Wands, Spades Swords. Pick a card to see both.', pcPick: 'Pick a playing card', pcNote: 'A playing-card deck has no Majors and only three court cards per suit, so the Jack is usually read as the Knight (some readers use the Page), the Queen as the Queen and the King as the King.', pcTrad: 'Traditional meaning', pcTarotWay: 'Read through tarot',
    teaIntro: 'Tap each zone of the cup to see what the position means. The common shapes are below.', teaZones: { rim: 'Near the rim', mid: 'Middle', bottom: 'Bottom', handle: 'Near the handle' }, teaZoneText: { rim: 'Near the rim: soon, within days or weeks.', mid: 'Middle of the cup: weeks to months away.', bottom: 'Bottom: further away, or the root of the matter.', handle: 'Near the handle: about you directly. Opposite the handle: other people, outside events.' }, teaSymbols: 'Common shapes', teaPractice: 'Try one', teaPracticeHint: 'Tap for a random shape in a random zone, then practise reading it.', teaDraw: 'Draw a shape',
    animalIntro: 'Tap an animal on the wheel. Yours is marked.', animalYours: 'your animal', animalTrio: 'Trio (tam hợp)', animalClash: 'Clash (tứ hành xung)', animalYears: 'Years',
    reportTitle: 'Report a problem', reportIntro: 'Something looks wrong, a button does nothing, or a text is confusing? Tell Nabu here.', reportWhat: 'What went wrong?', reportPlaceholder: 'Which screen you were on, what you tapped, and what happened.', reportContact: 'How to reach you (optional)', reportAuto: 'The app attaches this so Nabu can find the bug faster:', reportSend: 'Send report', reportViaIg: 'Send through Instagram', reportNeed: 'Describe the problem first.', reportSent: 'Sent to Nabu. Thank you!', reportNoChannel: 'Direct sending is not switched on yet. The message is copied; please send it through Instagram.', reportMsgHead: 'Nabu Tarot app bug report:', reportLink: 'Report a problem', rights: 'All rights reserved.', demoTag: 'Free preview', demoIntro: 'The first two lessons are open so you can see how the course works. Unlock to read everything.', lessonN: (n) => 'Lesson ' + n, lesson1: 'Overview and how to learn', lesson2: 'The first card', courseTabs: { cards: 'The cards', spreads: 'Spreads', guides: 'Guides' },
    months6: 'months', adminAccess: 'Admin account: every course is open for Nabu.', accessUntil: (d) => 'Your access runs until ' + d + '.', courseExpired: (d) => 'Your code expired on ' + d + '. Buy again to continue.',
    buyCourse: 'Buy the course on Instagram', buyHint: 'The purchase message is copied. After the transfer, Nabu sends you an unlock code. Enter it below.',
    buyMsg: (n, p, m) => 'Hi Nabu, I would like to buy the ' + n + ' (' + p + ', ' + m + ' months).', unlock: 'Unlock', unlocked: 'Unlocked', badCode: 'That code is not right. Please check it.',
    myCourses: 'My courses', enterCode: 'Enter an unlock code', noCourses: 'You have no courses yet.', activeUntil: (d) => 'active until ' + d, expiredOn: (d) => 'expired ' + d,
    recommended: 'Suggested for you',
    allCards: 'All cards',
    majors: 'Major Arcana', minors: 'Minor Arcana',
    upright: 'Upright', reversed: 'Reversed',
    kwPos: 'Positive keywords', kwNeg: 'Negative keywords',
    questions: 'Frequently asked questions',
    astroOf: 'Astrological link',
    lenTone: { pos: 'Positive', neu: 'Neutral', neg: 'Negative' },
    lenCore: 'Core meaning', lenLove: 'Love', lenWork: 'Work', lenWho: 'As a person', lenTime: 'Timing', lenCombo: 'Pairs', lenCard: 'Playing card',
    lenNote: 'Lenormand is a different system from tarot with its own way of reading.',
    signDates: 'Dates', element: 'Element', mode: 'Mode', ruler: 'Ruler',
    signAbout: 'Character', signLove: 'In love', signWork: 'At work', signTip: 'A note',
    signCards: 'Tarot cards of this sign',
    astroNote: 'The 12 signs, the planets, the 12 houses and the aspects. Tap a sign to read more.',
    spreadWhen: 'When to use it', spreadAsk: 'How to ask', spreadPos: 'Positions', spreadRead: 'How to read it', spreadNote: 'Note',
    numerology: 'Your numerology',
    lifePathOf: (n) => 'Life path ' + n,
    enterBirthday: 'Enter your birthday under Me to see your life path number and sign.',
    animal: 'Zodiac animal',
    animalNote: 'Counted by calendar year. If you were born before Lunar New Year, you belong to the previous animal.',

    bookTitle: 'Book a reading',
    priceTitle: 'Prices', priceIntro: 'Pick the package that fits your question. Prices are per session, paid by bank transfer.',
    chooseService: '1. Choose a service', serviceHint: 'Tap the package you want. You can pick several. Tap again to remove one.', needService: 'Choose at least one package first.', bookTip: 'Tap a package to select it. You can choose as many as you like. Changed your mind? Simply tap the package once more to deselect it.', cartTitle: 'Your chosen packages', cartEmpty: 'No package chosen yet.', cartNeedsTopic: 'topic not chosen', msgTotal: 'Total', topicFor: 'Topic for', topicNone: 'This step appears once you choose a 1 preset topic package in step 1. Each such package gets its own topic picker.',
    optional: 'optional', birthTime: 'Time of birth', birthHint: 'Tử vi needs the birth time as exact as possible.', needBirth: 'Tử vi needs your birth date.',
    msgService: 'Service', msgBirth: 'Birth date and time',
    chooseTopic: '2. Choose the topic for each preset-topic package',
    presetTopics: 'Set topics',
    topicHint: 'Only for the "1 preset topic" package: pick one of the five topics, each a set of five questions Nabu lays cards for. Tap a topic to see its questions. Anything else goes in the details below.',
    ownTopic: 'Your own question',
    ownTopicHint: 'Write your own question.',
    chooseTime: '3. Choose a time',
    timeHint: (tz) => 'Tap a day with a pink dot, then a time (' + tz + '). Times already taken are crossed out.',
    noSlots: 'No free slots on this day.',
    pickDay: 'Choose a day with a pink dot.',
    yourPick: 'Your pick',
    yourDetails: '4. Your details',
    yourName: 'Your name (or nickname)',
    yourNote: 'Anything to add?',
    notePlaceholder: 'A few lines about your situation, or the question you want to ask.',
    sendVia: '5. Send to Nabu',
    sendHint: 'The message is copied for you. Open the app, then paste it into the chat.',
    sendInApp: 'Send booking request',
    sending: 'Sending...',
    sentOk: 'Sent. Nabu will confirm soon. You can check it under Me.',
    newsTitle: 'Posts', newsIntro: 'Everything Nabu has posted: readings, thoughts, announcements. Type to search.', searchPosts: 'Search the posts…', noMatch: 'No post matches.', allPostsBtn: (n) => 'See all posts (' + n + ')', watchOn: (s) => 'Watch on ' + s,
    addImage: 'Image', addVideo: 'Video', videoPrompt: 'Paste a video link (YouTube, Facebook, TikTok, Instagram):', imgNeedCloud: 'Sign in with the admin account to upload images.', imgTooBig: 'Image too large, try a smaller one.', imgAdded: 'Image added to the post.', wrapPlaceholder: 'text', boxLabel: 'Box', formatHint: 'Select text, then tap B / U / H for bold, underline, highlight. H2 is a small heading, Box a separate title box. Images upload straight into the post; videos are pasted as links.',
    contactTitle: 'Contact us', contactLink: 'Contact', contactIntro: 'Write a few lines to Nabu, then choose where to send them.', contactWhat: 'Your message', contactPlaceholder: 'For example: a question about a package, or feedback on the app…', contactChoose: 'Send via:', contactApp: 'Message inside the Nabu Tarot app', contactNeed: 'Write a few lines first.', contactSent: 'Sent to Nabu. Replies show under Me.', contactCopied: 'Your message is copied. Paste it into the chat when the app opens.',
    addToCalendar: 'Add to my phone calendar', calendarHint: 'Your phone calendar will remind you 24 hours, 6 hours, 1 hour and 15 minutes before.', cancelBooking: 'Cancel booking', changeTitle: 'Change the time', changeIntro: 'Pick a new time below. Nabu reviews it before the new time takes effect.', currentSlot: 'Current time', sendChange: 'Send the change request', changeSent: 'Change request sent. Nabu will review it soon.', cancelSent: 'Cancellation request sent. Nabu will confirm it.', confirmCancel: 'Cancel this booking?', newSlotLabel: 'New time', adminApplyChange: 'Approve new time', adminKeep: 'Keep old time', adminApplyCancel: 'Approve cancellation', adminKeepBooking: 'Keep booking', reminderOn: 'Turn on booking reminders on this device', reminderHint: 'While the app is open you are reminded 24 hours, 6 hours, 1 hour and 15 minutes before. To be safe, add the booking to your phone calendar.', upcoming: 'Upcoming booking', remindTitle: (w) => 'Reading with Nabu ' + w, inHours: (h) => 'in ' + h + ' hours', inMinutes: (m) => 'in ' + m + ' minutes', allDays: 'All', bkOn: (d) => 'Bookings on ' + d, aiSettings: 'Nabu AI settings', aiKeyLabel: 'Gemini API key (Google AI Studio)', aiKeyHint: 'Paste the key here and save: every user gets Nabu AI answered by Gemini, with web search while the quota lasts. The key lives in the app cloud, not in the source code. Leave it empty to use the built-in answers.', aiKeySaved: 'Saved. Nabu AI now uses Gemini.', saveKey: 'Save key', emojiBtn: 'Emoji', imgTooBigChat: 'Image too large for a message, try a smaller one.',
    saveSlot: 'Save this time', changeSlot: 'Change', slotSaved: 'Time saved', summaryTitle: 'Your request', showMsg: 'Show the message that will be sent', bkItems: 'Packages',
    doneTitle: 'Booking request sent', doneBody: 'Nabu will review it and confirm soon. Follow the status under Me; you will be notified when Nabu replies.', doneMe: 'See my bookings', doneHome: 'Back to home', doneMore: 'Book another reading',
    draftKept: 'Your choices are saved on this device automatically, so you can leave and come back.', openInLibrary: 'Read the full guide in the library',
    aiGreet: 'Hi! I am Nabu AI. Ask me about a card, a zodiac sign, your numbers, or tell me to draw a card for today.', aiDrew: (n) => 'I drew a card for you: ' + n + '.', aiDrawHint: 'For a fuller draw, open the Pick a card tab.', aiSignOf: (s) => 'For your sign, ' + s + ':', aiThanks: 'You are welcome! Ask me anything else.', aiTodayMoon: (m) => 'Today the Moon is in its ' + m + ' phase.',
    needLogin: 'Sign in to send inside the app, or send through Instagram below.',
    viaInstagram: 'Message on Instagram',
    viaMessenger: 'Message on Messenger',
    viaZalo: 'Message on Zalo',
    viaEmail: 'Send an email',
    copyMsg: 'Just copy the message',
    needTopic: 'Choose a topic first.',
    needSlot: 'Choose a time first.',
    msgHello: 'Hi Nabu, I would like to book a reading.',
    msgTopic: 'Topic',
    msgTime: 'Time',
    msgName: 'Name',
    msgNote: 'Extra question',
    msgCard: 'The card I just drew in the app',
    howItWorks: 'How booking works',
    aboutTitle: 'About Nabu Tarot',
    dow: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],

    meTitle: 'Your profile',
    meIntro: 'Your birthday and interests help the home screen pick the right content for you.',
    localOnly: 'Your profile is saved on this device.',
    accountsSoon: 'Nabu has not switched sign-in on yet. Once on, you sign in with Google, Facebook or email and password, and your profile, messages and bookings follow you. For now the profile stays on this device.', accountsOff: 'Sign-in is not open yet.',
    signIn: 'Sign in',
    signInWith: { google: 'Continue with Google', facebook: 'Continue with Facebook', email: 'Continue with email' },
    signOut: 'Sign out',
    emailLabel: 'Email', passwordLabel: 'Password',
    createAccount: 'Create account', haveAccount: 'Have an account? Sign in', noAccount: 'No account? Create one',
    forgot: 'Forgot password', resetSent: 'Password reset email sent.', authFbOff: 'Facebook sign-in is not open yet: Meta requires Nabu to register a developer app first. Please use Google or email.', authProviderOff: 'This sign-in method is not switched on. Please use Google or email.', authDomain: 'Firebase has not allowed this address yet. Nabu needs to add angelale0211.github.io to Authorized domains.', authCancelled: 'You closed the sign-in window.', authOtherProvider: 'This email is registered with a different method. Please sign in that way.', authNetwork: 'No network connection. Please try again.',
    authFail: 'Sign-in failed',
    displayName: 'Display name',
    birthday: 'Birthday',
    interests: 'What do you care about?',
    saveProfile: 'Save profile',
    saved: 'Saved',
    myBookings: 'My bookings',
    noBookings: 'You have no bookings yet.',
    status: { requested: 'Awaiting confirmation', confirmed: 'Confirmed', declined: 'Declined', cancelled: 'Cancelled', change_requested: 'New time awaiting approval', cancel_requested: 'Cancellation awaiting approval' },
    messages: 'Message Nabu',
    messagesIntro: 'Nabu replies inside the app. A red dot shows when there is something new.',
    messagesSoon: 'In-app messaging opens once Nabu turns on accounts. For now, message on Instagram.',
    typeMsg: 'Write a message...', sendPhoto: 'Send a photo', holdToRecord: 'Tap to record, tap again to send', recording: 'Recording… tap 🎤 again to send.', uploading: 'Sending…', noMic: 'This device does not allow recording.', fileTooBig: 'Photo too large (8 MB max).',
    send: 'Send',
    noMsgs: 'No messages yet. Ask away, Nabu will answer.',
    themeTitle: 'Appearance', themes: { auto: 'Match my phone', light: 'Light', dark: 'Dark' }, themeHint: 'Match my phone: the app switches with your phone\'s light or dark setting.',
    installTitle: 'Install on your phone',
    install: 'iPhone: open in Safari, tap Share, then "Add to Home Screen". Android: tap the ⋮ menu, then "Install app".',
    dismiss: 'Close', tourMini: 'How to use the app', tourOpen: 'Show again',
    offlineReady: 'The app is ready to use offline.',

    adminTitle: 'Dashboard',
    adminIntro: 'This page is for Nabu only.',
    adminTabs: { posts: 'Posts', schedule: 'Availability', bookings: 'Bookings', inbox: 'Inbox', codes: 'Codes' },
    codesIntro: 'Once a client has paid, make a code here and send it to them. The expiry date is built into the code.', codeCourse: 'Course', codeStart: 'Starts', codeMonths: 'Months', makeCode: 'Make code', codeUntil: 'Expires',
    token: 'GitHub token',
    tokenHint: 'The token stays on this device only. See the README to create one.',
    saveToken: 'Save token',
    postDate: 'Date',
    postTitle: 'Title',
    postBody: 'Text',
    bodyHint: 'Leave a blank line to start a new paragraph.',
    postTitleEn: 'Title (English, optional)',
    postBodyEn: 'Text (English, optional)',
    postCards: 'Cards in this post (tap to select)',
    postTopics: 'Who this post is for',
    searchCard: 'Find a card',
    markInitials: 'Name starts with (comma separated)',
    markSigns: 'Signs',
    pinPost: 'Pin to top',
    preview: 'Preview',
    publish: 'Publish',
    publishing: 'Publishing...',
    published: 'Published. Everyone\'s feed updates within a few minutes.',
    publishFail: 'Publishing failed',
    copyJson: 'Copy JSON',
    existing: 'Published posts',
    edit: 'Edit',
    del: 'Delete',
    confirmDel: 'Delete this post?',
    newPost: 'New post',
    needBody: 'A post needs a title and some text.',
    needToken: 'Paste a token first.',
    weekly: 'Weekly free hours',
    weeklyHint: 'Tap an hour to turn it on or off. Each hour is one session.',
    blocked: 'Days off',
    blockedHint: 'No bookings on these days even if hours are set.',
    addDay: 'Add a day',
    bookedSlots: 'Taken slots',
    bookedHint: 'Bookings made through Instagram go here so the slot disappears.',
    leadDays: 'Earliest booking after (days)',
    horizonDays: 'Open calendar ahead (days)',
    saveSchedule: 'Save availability', cloudContent: 'Posts and availability are saved straight to the app cloud. Save, and clients see it at once; no GitHub token needed.',
    scheduleSaved: 'Saved. Clients see it within a few minutes.',
    bookingsIntro: 'Requests sent inside the app. Confirming locks the slot.',
    confirm: 'Confirm', decline: 'Decline',
    needFirebase: 'This section needs accounts turned on (Firebase). See the README.',
    adminLogin: 'Sign in with an admin email to see this section.',
    inboxEmpty: 'No conversations yet.', inboxIntro: 'One row per person. Tap a row to open that conversation on its own.', youLabel: 'You', guestLabel: 'Guest', ownThread: 'your own account', ownThreadHint: 'This is the test inbox of your own account. Messages from clients live in the dashboard under Inbox, one conversation per person.', adminSummary: 'For Nabu', unreadMsgs: 'unread messages', newBookings: 'new bookings awaiting confirmation', openAdmin: 'Open the dashboard', enableNotif: 'Turn on notifications', notifOn: 'Notifications are on. You will be told about new messages and bookings.', notifDenied: 'The browser is blocking notifications for the app. Open the site settings and allow them.', notifUnsupported: 'This browser does not support notifications. On iPhone, add the app to the home screen and open it from there.', notifHint: 'You will be notified about new messages and bookings, even when the app is in the background. On iPhone, add the app to the home screen first.', notifNewMsg: 'New message from ', notifNewBooking: 'New booking from ',
    reply: 'Reply',
    back: 'Back',

    suitOf: { major: 'Major', wands: 'Wands', cups: 'Cups', swords: 'Swords', pentacles: 'Pentacles' },
    zodiac: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'],
    dateFmt: (d) => d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
    dateShort: (d) => d.getDate() + '/' + (d.getMonth() + 1)
  }
};

/* Nabu Tarot's five preset topics. Fixed brand copy: never paraphrase. */
const TOPICS = [
  { id: 1, icon: '💗', interest: 'love', name: { vi: 'Tình cảm hiện tại', en: 'Current relationship' },
    q: { vi: ['Năng lượng hiện tại của mối quan hệ này là gì?', 'Người ấy hiện đang có cảm xúc như thế nào với mình?', 'Người ấy nhìn nhận mình và mối quan hệ này ra sao?', 'Trở ngại lớn nhất giữa hai người hiện tại là gì?', 'Mối quan hệ có xu hướng phát triển thế nào trong 1–3 tháng tới?'],
         en: ['What is the current energy of this relationship?', 'How does this person feel about me right now?', 'How do they see me and this relationship?', 'What is the biggest obstacle between us right now?', 'How is the relationship likely to develop in the next 1–3 months?'] } },
  { id: 2, icon: '💔', interest: 'ex', name: { vi: 'Người cũ', en: 'An ex' },
    q: { vi: ['Người ấy hiện nghĩ gì về mình?', 'Họ còn tình cảm với mình không?', 'Vì sao họ chưa chủ động liên lạc?', 'Có khả năng hai người liên lạc hoặc gặp lại nhau không?', 'Mình nên tiếp tục chờ đợi hay buông bỏ?'],
         en: ['What do they think of me now?', 'Do they still have feelings for me?', 'Why have they not reached out?', 'Is there a chance we get in touch or meet again?', 'Should I keep waiting or let go?'] } },
  { id: 3, icon: '💗', interest: 'crush', name: { vi: 'Mập mờ - Crush', en: 'Situationship / crush' },
    q: { vi: ['Người ấy có cảm xúc gì với mình?', 'Họ có nhận ra tình cảm của mình không?', 'Ý định của họ đối với mình là gì?', 'Điều gì đang ngăn mối quan hệ này tiến triển thêm?', 'Khả năng hai người trở thành một cặp trong thời gian tới như thế nào?'],
         en: ['What do they feel for me?', 'Do they notice my feelings?', 'What are their intentions with me?', 'What is holding this back from going further?', 'How likely are we to become a couple soon?'] } },
  { id: 4, icon: '⭐', interest: 'work', name: { vi: 'Công việc', en: 'Career' },
    q: { vi: ['Tình hình công việc hiện tại của mình đang ở đâu?', 'Điểm mạnh nào mình nên tận dụng?', 'Trở ngại lớn nhất trong công việc hiện tại là gì?', 'Cơ hội đáng chú ý nào có thể xuất hiện sắp tới?', 'Mình nên làm gì để phát triển sự nghiệp tốt hơn?'],
         en: ['Where is my work situation right now?', 'Which strength should I lean on?', 'What is the biggest obstacle at work right now?', 'What notable opportunity may come up soon?', 'What should I do to grow my career?'] } },
  { id: 5, icon: '✉️', interest: 'study', name: { vi: 'Học tập', en: 'Study' },
    q: { vi: ['Tình trạng học tập hiện tại của mình như thế nào?', 'Điểm yếu nào đang ảnh hưởng đến kết quả học tập?', 'Điểm mạnh nào mình nên tận dụng?', 'Hướng học tập nào phù hợp hơn với bản thân mình?', 'Mình nên thay đổi gì để đạt kết quả tốt hơn?'],
         en: ['How is my study going right now?', 'Which weakness is hurting my results?', 'Which strength should I lean on?', 'Which study path suits me better?', 'What should I change to do better?'] } }
];
