/* ============================ UI strings ============================
   Vietnamese is the first language of the app. Keep every line short and
   spoken; the reader is a client on a phone, not a student. */
const STR = {
  vi: {
    lang: 'EN',
    nav: { home: 'Trang chủ', pick: 'Rút bài', learn: 'Học', book: 'Đặt lịch', me: 'Tôi' },

    feedTitle: 'Dự đoán mới',
    feedEmpty: 'Chưa có bài nào. Quay lại sau nhé.',
    feedOffline: 'Đang xem bản đã lưu. Mở mạng để cập nhật.',
    pinned: 'Ghim',
    readMore: 'Đọc thêm',
    readLess: 'Thu gọn',
    share: 'Chia sẻ',
    copied: 'Đã sao chép',
    forYouIf: 'Dành cho bạn nếu',
    forYou: 'Dành cho bạn',
    initials: 'tên bắt đầu bằng',
    signs: 'cung',
    cardsDrawn: 'Lá bài trong bài này',
    ctaPick: 'Rút một lá cho riêng bạn',
    ctaBook: 'Đặt lịch xem bài',
    backToFeed: 'Về trang chủ',
    notFound: 'Không tìm thấy bài này.',
    helloGuest: 'Chào bạn',
    hello: (n) => 'Chào ' + n,
    setupProfile: 'Cho Nabu biết ngày sinh và điều bạn quan tâm. Trang chủ sẽ chọn nội dung hợp với bạn.',
    setupBtn: 'Tạo hồ sơ',
    yourSign: 'Cung Mặt Trời của bạn',
    signCard: 'Lá tarot của cung bạn',
    lifePath: 'Số đường đời',
    readSign: 'Đọc về cung của bạn',
    forInterests: 'Theo điều bạn quan tâm',

    pickTitle: 'Năng lượng hiện tại của bạn',
    pickIntro: 'Hít một hơi thật sâu. Nghĩ về hôm nay. Rồi chạm vào một lá bài.',
    focusLabel: 'Bạn đang nghĩ về',
    focus: { general: 'Chung', love: 'Tình cảm', work: 'Công việc', study: 'Học tập', money: 'Tiền bạc' },
    tapACard: 'Chạm vào một lá',
    redraw: 'Xào lại và rút lá khác',
    yourCard: 'Lá bài của bạn',
    energyNow: 'Năng lượng lúc này',
    energyLine: (kws) => 'Lúc này bạn đang mang năng lượng: ' + kws + '.',
    cardSays: 'Lá bài nói gì',
    onTheCard: 'Trên lá bài',
    shadow: 'Mặt trái cần để ý',
    shadowLine: (kws) => 'Nếu năng lượng này quá đà, nó thành: ' + kws + '.',
    focusHead: (f) => 'Nếu bạn đang nghĩ về ' + f.toLowerCase(),
    noFocus: 'Chưa có bài giảng riêng cho chủ đề này với lá này. Bạn đọc phần năng lượng ở trên nhé.',
    quickNote: 'Đây là lời nhắn nhanh từ một lá bài. Muốn hiểu rõ chuyện của bạn, hãy đặt lịch xem bài đầy đủ.',
    shareCard: 'Chia sẻ lá bài',
    bookWithCard: 'Đặt lịch xem sâu hơn',
    learnCard: 'Đọc kỹ về lá này',
    shareText: (name, kws) => 'Lá bài hôm nay của mình: ' + name + '. Năng lượng: ' + kws + '. Rút thử ở ',

    learnTitle: 'Kho kiến thức',
    learnIntro: 'Tarot, Lenormand, chiêm tinh, manifestation và bói toán. Đọc từng phần ngắn, không cần theo thứ tự.',
    cats: { tarot: 'Tarot', lenormand: 'Lenormand', astro: 'Chiêm tinh', manifest: 'Manifestation', fortune: 'Bói toán' },
    catSub: { tarot: '78 lá + 13 trải bài · 200.000đ / 6 tháng', lenormand: '36 lá + 7 trải bài · 200.000đ / 6 tháng', astro: '12 cung, hành tinh, nhà', manifest: 'cách làm + giới hạn', fortune: 'thần số, chỉ tay, bài Tây' },
    courses: 'Khóa học', freeReads: 'Đọc miễn phí', courseTabs: { cards: 'Các lá bài', spreads: 'Trải bài', guides: 'Bài đọc' },
    months6: 'tháng', accessUntil: (d) => 'Bạn có quyền xem đến ' + d + '.', courseExpired: (d) => 'Mã của bạn đã hết hạn ngày ' + d + '. Mua lại để xem tiếp.',
    buyCourse: 'Mua khóa học qua Instagram', buyHint: 'Tin nhắn mua khóa đã được sao chép. Sau khi chuyển khoản, Nabu gửi bạn mã mở khóa. Nhập mã ở dưới.',
    buyMsg: (n, p, m) => 'Chào Nabu, mình muốn mua ' + n + ' (' + p + ', ' + m + ' tháng).', unlock: 'Mở khóa', unlocked: 'Đã mở khóa', badCode: 'Mã không đúng. Bạn kiểm tra lại nhé.',
    myCourses: 'Khóa học của tôi', enterCode: 'Nhập mã mở khóa', noCourses: 'Bạn chưa có khóa học nào.', activeUntil: (d) => 'đang mở, đến ' + d, expiredOn: (d) => 'hết hạn ' + d,
    recommended: 'Gợi ý cho bạn',
    allCards: 'Tất cả các lá',
    majors: 'Ẩn Chính', minors: 'Ẩn Phụ',
    upright: 'Nghĩa xuôi', reversed: 'Nghĩa ngược',
    kwPos: 'Từ khóa tích cực', kwNeg: 'Từ khóa tiêu cực',
    questions: 'Các câu hỏi thường gặp',
    astroOf: 'Tương ứng chiêm tinh',
    lenTone: { pos: 'Tích cực', neu: 'Trung tính', neg: 'Tiêu cực' },
    lenCore: 'Nghĩa chính', lenLove: 'Tình cảm', lenWork: 'Công việc', lenWho: 'Chỉ người', lenTime: 'Thời gian', lenCombo: 'Cặp lá', lenCard: 'Lá bài Tây',
    lenNote: 'Lenormand là hệ khác tarot, có cách đọc riêng. Nghĩa ở đây theo dòng Petit Lenormand phổ thông.',
    signDates: 'Ngày', element: 'Nguyên tố', mode: 'Tính chất', ruler: 'Sao chủ',
    signAbout: 'Tính cách', signLove: 'Trong tình cảm', signWork: 'Trong công việc', signTip: 'Lời nhắn',
    signCards: 'Lá tarot của cung này',
    astroNote: 'Tương ứng tarot – chiêm tinh theo hệ Golden Dawn (Book T, 1888). Tính cách các cung viết theo cách hiểu phổ thông.',
    badges: { doc: 'Có nguồn rõ', conv: 'Nhiều người dùng', own: 'Tự đặt ra' },
    spreadWhen: 'Dùng khi nào', spreadAsk: 'Hỏi thế nào', spreadPos: 'Các vị trí', spreadRead: 'Cách đọc', spreadNote: 'Lưu ý',
    numerology: 'Thần số học của bạn',
    lifePathOf: (n) => 'Số đường đời ' + n,
    enterBirthday: 'Nhập ngày sinh ở mục Tôi để xem số đường đời và cung của bạn.',
    animal: 'Con giáp',
    animalNote: 'Tính theo năm dương lịch. Nếu bạn sinh trước Tết thì thuộc con giáp của năm trước.',

    bookTitle: 'Đặt lịch xem bài',
    priceTitle: 'Bảng giá', priceIntro: 'Chọn gói hợp với câu hỏi của bạn. Giá tính theo buổi, thanh toán chuyển khoản.',
    chooseService: '1. Chọn dịch vụ', serviceHint: 'Chạm vào gói bạn muốn. Giá ghi bên cạnh.', needService: 'Bạn chọn một gói dịch vụ trước nhé.',
    optional: 'không bắt buộc', birthTime: 'Giờ sinh', birthHint: 'Tử vi cần giờ sinh càng chính xác càng tốt.', needBirth: 'Tử vi cần ngày sinh của bạn.',
    msgService: 'Dịch vụ', msgBirth: 'Ngày giờ sinh',
    chooseTopic: '2. Chọn chủ đề',
    presetTopics: 'Chủ đề sẵn',
    topicHint: 'Mỗi chủ đề là trải bài 5 lá. Bấm để xem 5 câu hỏi.',
    ownTopic: 'Câu hỏi riêng',
    ownTopicHint: 'Bạn tự viết câu hỏi của mình.',
    chooseTime: '3. Chọn giờ hẹn',
    timeHint: (tz) => 'Giờ hiển thị theo ' + tz + '. Chấm hồng là ngày còn chỗ.',
    noSlots: 'Ngày này không còn chỗ.',
    pickDay: 'Chọn một ngày có chấm hồng.',
    yourPick: 'Bạn chọn',
    yourDetails: '4. Thông tin của bạn',
    yourName: 'Tên bạn (hoặc biệt danh)',
    yourNote: 'Bạn muốn hỏi thêm gì?',
    notePlaceholder: 'Kể ngắn gọn chuyện của bạn, hoặc câu hỏi bạn muốn hỏi.',
    sendVia: '5. Gửi cho Nabu',
    sendHint: 'Tin nhắn được sao chép sẵn. Bấm vào ứng dụng, rồi dán vào ô chat.',
    sendInApp: 'Gửi yêu cầu đặt lịch',
    sending: 'Đang gửi...',
    sentOk: 'Đã gửi. Nabu sẽ xác nhận sớm. Bạn xem lại trong mục Tôi.',
    needLogin: 'Bạn cần đăng nhập để gửi trong app. Hoặc gửi qua Instagram bên dưới.',
    viaInstagram: 'Nhắn qua Instagram',
    viaMessenger: 'Nhắn qua Messenger',
    viaZalo: 'Nhắn qua Zalo',
    viaEmail: 'Gửi email',
    copyMsg: 'Chỉ sao chép tin nhắn',
    needTopic: 'Bạn chọn một chủ đề trước nhé.',
    needSlot: 'Bạn chọn giờ hẹn trước nhé.',
    msgHello: 'Chào Nabu, mình muốn đặt lịch xem bài.',
    msgTopic: 'Chủ đề',
    msgTime: 'Giờ hẹn',
    msgName: 'Tên',
    msgNote: 'Câu hỏi thêm',
    msgCard: 'Lá mình vừa rút trong app',
    howItWorks: 'Cách đặt lịch',
    aboutTitle: 'Về Nabu Tarot',
    dow: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    months: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'],

    meTitle: 'Hồ sơ của bạn',
    meIntro: 'Ngày sinh và điều bạn quan tâm giúp trang chủ chọn đúng nội dung cho bạn.',
    localOnly: 'Hồ sơ đang lưu trên máy này.',
    accountsSoon: 'Đăng nhập để lưu hồ sơ, nhắn tin và xem lịch hẹn đang được Nabu chuẩn bị. Hiện hồ sơ lưu trên máy này.',
    signIn: 'Đăng nhập',
    signInWith: { google: 'Tiếp tục với Google', facebook: 'Tiếp tục với Facebook', email: 'Tiếp tục với email' },
    signOut: 'Đăng xuất',
    emailLabel: 'Email', passwordLabel: 'Mật khẩu',
    createAccount: 'Tạo tài khoản', haveAccount: 'Đã có tài khoản? Đăng nhập', noAccount: 'Chưa có tài khoản? Tạo mới',
    forgot: 'Quên mật khẩu', resetSent: 'Đã gửi email đặt lại mật khẩu.',
    authFail: 'Đăng nhập không thành công',
    displayName: 'Tên hiển thị',
    birthday: 'Ngày sinh',
    interests: 'Bạn quan tâm điều gì?',
    saveProfile: 'Lưu hồ sơ',
    saved: 'Đã lưu',
    myBookings: 'Lịch hẹn của tôi',
    noBookings: 'Bạn chưa có lịch hẹn nào.',
    status: { requested: 'Chờ xác nhận', confirmed: 'Đã xác nhận', declined: 'Không nhận', cancelled: 'Đã huỷ' },
    messages: 'Nhắn tin với Nabu',
    messagesIntro: 'Nabu trả lời trong app. Bạn sẽ thấy chấm đỏ khi có tin mới.',
    messagesSoon: 'Nhắn tin trong app sẽ mở khi Nabu bật tài khoản. Bây giờ bạn nhắn qua Instagram nhé.',
    typeMsg: 'Viết tin nhắn...',
    send: 'Gửi',
    noMsgs: 'Chưa có tin nhắn. Bạn cứ hỏi, Nabu sẽ trả lời.',
    themeTitle: 'Giao diện', themes: { auto: 'Theo điện thoại', light: 'Sáng', dark: 'Tối' }, themeHint: 'Theo điện thoại: app tự đổi sáng/tối cùng máy của bạn.',
    installTitle: 'Cài app lên điện thoại',
    install: 'Trên iPhone: mở bằng Safari, bấm Chia sẻ, chọn "Thêm vào MH chính". Trên Android: bấm menu ⋮ rồi "Cài đặt ứng dụng".',
    dismiss: 'Đóng',
    offlineReady: 'App đã sẵn sàng dùng offline.',

    adminTitle: 'Bảng điều khiển',
    adminIntro: 'Trang này chỉ dành cho Nabu.',
    adminTabs: { posts: 'Bài đăng', schedule: 'Lịch rảnh', bookings: 'Đặt lịch', inbox: 'Tin nhắn', codes: 'Mã học' },
    codesIntro: 'Khách chuyển khoản xong, bạn tạo mã ở đây và gửi cho họ. Mã có ngày hết hạn ghi sẵn bên trong.', codeCourse: 'Khóa', codeStart: 'Bắt đầu từ', codeMonths: 'Số tháng', makeCode: 'Tạo mã', codeUntil: 'Hết hạn',
    token: 'GitHub token',
    tokenHint: 'Token chỉ lưu trên máy này. Xem README để tạo token.',
    saveToken: 'Lưu token',
    postDate: 'Ngày',
    postTitle: 'Tiêu đề',
    postBody: 'Nội dung',
    bodyHint: 'Cách một dòng trống để xuống đoạn.',
    postTitleEn: 'Tiêu đề (English, không bắt buộc)',
    postBodyEn: 'Nội dung (English, không bắt buộc)',
    postCards: 'Lá bài trong bài (chạm để chọn)',
    postTopics: 'Bài này hợp với ai quan tâm',
    searchCard: 'Tìm lá bài',
    markInitials: 'Tên bắt đầu bằng (cách nhau bằng dấu phẩy)',
    markSigns: 'Cung',
    pinPost: 'Ghim lên đầu',
    preview: 'Xem trước',
    publish: 'Đăng bài',
    publishing: 'Đang đăng...',
    published: 'Đã đăng. Trang của mọi người sẽ cập nhật trong vài phút.',
    publishFail: 'Đăng không thành công',
    copyJson: 'Sao chép JSON',
    existing: 'Bài đã đăng',
    edit: 'Sửa',
    del: 'Xoá',
    confirmDel: 'Xoá bài này?',
    newPost: 'Bài mới',
    needBody: 'Bài cần có tiêu đề và nội dung.',
    needToken: 'Bạn cần dán token trước.',
    weekly: 'Giờ rảnh mỗi tuần',
    weeklyHint: 'Chạm vào giờ để bật/tắt. Mỗi giờ là một buổi.',
    blocked: 'Ngày nghỉ',
    blockedHint: 'Những ngày này không nhận lịch dù có giờ rảnh.',
    addDay: 'Thêm ngày',
    bookedSlots: 'Giờ đã có khách',
    bookedHint: 'Khách đặt qua Instagram thì bạn thêm vào đây để giờ đó không hiện nữa.',
    leadDays: 'Nhận lịch sớm nhất sau (ngày)',
    horizonDays: 'Mở lịch trước (ngày)',
    saveSchedule: 'Lưu lịch rảnh',
    scheduleSaved: 'Đã lưu lịch. Khách sẽ thấy sau vài phút.',
    bookingsIntro: 'Yêu cầu khách gửi trong app. Xác nhận thì giờ đó tự khoá.',
    confirm: 'Xác nhận', decline: 'Từ chối',
    needFirebase: 'Mục này cần bật tài khoản (Firebase). Xem README.',
    adminLogin: 'Đăng nhập bằng email quản trị để xem mục này.',
    inboxEmpty: 'Chưa có cuộc trò chuyện nào.',
    reply: 'Trả lời',
    back: 'Quay lại',

    suitOf: { major: 'Ẩn Chính', wands: 'Gậy', cups: 'Cốc', swords: 'Kiếm', pentacles: 'Tiền' },
    zodiac: ['Bạch Dương', 'Kim Ngưu', 'Song Tử', 'Cự Giải', 'Sư Tử', 'Xử Nữ', 'Thiên Bình', 'Bọ Cạp', 'Nhân Mã', 'Ma Kết', 'Bảo Bình', 'Song Ngư'],
    dateFmt: (d) => d.getDate() + ' tháng ' + (d.getMonth() + 1) + ', ' + d.getFullYear(),
    dateShort: (d) => d.getDate() + '/' + (d.getMonth() + 1)
  },

  en: {
    lang: 'VI',
    nav: { home: 'Home', pick: 'Pick a card', learn: 'Learn', book: 'Book', me: 'Me' },

    feedTitle: 'Latest readings',
    feedEmpty: 'Nothing posted yet. Come back soon.',
    feedOffline: 'Showing the saved copy. Go online to update.',
    pinned: 'Pinned',
    readMore: 'Read more',
    readLess: 'Show less',
    share: 'Share',
    copied: 'Copied',
    forYouIf: 'For you if',
    forYou: 'For you',
    initials: 'your name starts with',
    signs: 'sign',
    cardsDrawn: 'Cards in this reading',
    ctaPick: 'Pick a card of your own',
    ctaBook: 'Book a reading',
    backToFeed: 'Back to home',
    notFound: 'This post was not found.',
    helloGuest: 'Hello',
    hello: (n) => 'Hello ' + n,
    setupProfile: 'Tell Nabu your birthday and what you care about. The home screen will pick content for you.',
    setupBtn: 'Set up my profile',
    yourSign: 'Your Sun sign',
    signCard: 'The tarot card of your sign',
    lifePath: 'Life path number',
    readSign: 'Read about your sign',
    forInterests: 'Based on your interests',

    pickTitle: 'Your energy right now',
    pickIntro: 'Take a deep breath. Think about today. Then tap a card.',
    focusLabel: 'On your mind',
    focus: { general: 'General', love: 'Love', work: 'Work', study: 'Study', money: 'Money' },
    tapACard: 'Tap a card',
    redraw: 'Shuffle and pick again',
    yourCard: 'Your card',
    energyNow: 'Energy right now',
    energyLine: (kws) => 'Right now you carry this energy: ' + kws + '.',
    cardSays: 'What the card says',
    onTheCard: 'On the card',
    shadow: 'The shadow side',
    shadowLine: (kws) => 'When this energy runs too hot, it turns into: ' + kws + '.',
    focusHead: (f) => 'If ' + f.toLowerCase() + ' is on your mind',
    noFocus: 'No lecture notes for this topic with this card yet. Read the energy section above.',
    quickNote: 'This is a quick message from one card. For your own situation, book a full reading.',
    shareCard: 'Share this card',
    bookWithCard: 'Book a deeper reading',
    learnCard: 'Read about this card',
    shareText: (name, kws) => 'My card today: ' + name + '. Energy: ' + kws + '. Try it at ',

    learnTitle: 'Knowledge library',
    learnIntro: 'Tarot, Lenormand, astrology, manifestation and fortune telling. Short pieces, read in any order.',
    cats: { tarot: 'Tarot', lenormand: 'Lenormand', astro: 'Astrology', manifest: 'Manifestation', fortune: 'Fortune telling' },
    catSub: { tarot: '78 cards + 13 spreads · 200.000đ / 6 months', lenormand: '36 cards + 7 spreads · 200.000đ / 6 months', astro: '12 signs, planets, houses', manifest: 'methods + limits', fortune: 'numbers, palms, playing cards' },
    courses: 'Courses', freeReads: 'Free to read', courseTabs: { cards: 'The cards', spreads: 'Spreads', guides: 'Guides' },
    months6: 'months', accessUntil: (d) => 'Your access runs until ' + d + '.', courseExpired: (d) => 'Your code expired on ' + d + '. Buy again to continue.',
    buyCourse: 'Buy the course on Instagram', buyHint: 'The purchase message is copied. After the transfer, Nabu sends you an unlock code. Enter it below.',
    buyMsg: (n, p, m) => 'Hi Nabu, I would like to buy the ' + n + ' (' + p + ', ' + m + ' months).', unlock: 'Unlock', unlocked: 'Unlocked', badCode: 'That code is not right. Please check it.',
    myCourses: 'My courses', enterCode: 'Enter an unlock code', noCourses: 'You have no courses yet.', activeUntil: (d) => 'active until ' + d, expiredOn: (d) => 'expired ' + d,
    recommended: 'Suggested for you',
    allCards: 'All cards',
    majors: 'Major Arcana', minors: 'Minor Arcana',
    upright: 'Upright', reversed: 'Reversed',
    kwPos: 'Positive keywords', kwNeg: 'Negative keywords',
    questions: 'Frequently asked questions',
    astroOf: 'Astrological link',
    lenTone: { pos: 'Positive', neu: 'Neutral', neg: 'Negative' },
    lenCore: 'Core meaning', lenLove: 'Love', lenWork: 'Work', lenWho: 'As a person', lenTime: 'Timing', lenCombo: 'Pairs', lenCard: 'Playing card',
    lenNote: 'Lenormand is a different system from tarot with its own way of reading. Meanings follow the mainstream Petit Lenormand tradition.',
    signDates: 'Dates', element: 'Element', mode: 'Mode', ruler: 'Ruler',
    signAbout: 'Character', signLove: 'In love', signWork: 'At work', signTip: 'A note',
    signCards: 'Tarot cards of this sign',
    astroNote: 'Tarot–astrology links follow the Golden Dawn system (Book T, 1888). Sign characters follow common usage.',
    badges: { doc: 'Documented', conv: 'Common practice', own: 'One reader\'s system' },
    spreadWhen: 'When to use it', spreadAsk: 'How to ask', spreadPos: 'Positions', spreadRead: 'How to read it', spreadNote: 'Note',
    numerology: 'Your numerology',
    lifePathOf: (n) => 'Life path ' + n,
    enterBirthday: 'Enter your birthday under Me to see your life path number and sign.',
    animal: 'Zodiac animal',
    animalNote: 'Counted by calendar year. If you were born before Lunar New Year, you belong to the previous animal.',

    bookTitle: 'Book a reading',
    priceTitle: 'Prices', priceIntro: 'Pick the package that fits your question. Prices are per session, paid by bank transfer.',
    chooseService: '1. Choose a service', serviceHint: 'Tap the package you want. The price is next to it.', needService: 'Choose a package first.',
    optional: 'optional', birthTime: 'Time of birth', birthHint: 'Tử vi needs the birth time as exact as possible.', needBirth: 'Tử vi needs your birth date.',
    msgService: 'Service', msgBirth: 'Birth date and time',
    chooseTopic: '2. Choose a topic',
    presetTopics: 'Set topics',
    topicHint: 'Each topic is a five-card spread. Tap to see the five questions.',
    ownTopic: 'Your own question',
    ownTopicHint: 'Write your own question.',
    chooseTime: '3. Choose a time',
    timeHint: (tz) => 'Times are in ' + tz + '. A pink dot means free slots.',
    noSlots: 'No free slots on this day.',
    pickDay: 'Choose a day with a pink dot.',
    yourPick: 'Your pick',
    yourDetails: '4. Your details',
    yourName: 'Your name (or nickname)',
    yourNote: 'Anything to add?',
    notePlaceholder: 'A few lines about your situation, or the question you want to ask.',
    sendVia: '5. Send to Nabu',
    sendHint: 'The message is copied for you. Open the app, then paste it into the chat.',
    sendInApp: 'Send booking request',
    sending: 'Sending...',
    sentOk: 'Sent. Nabu will confirm soon. You can check it under Me.',
    needLogin: 'Sign in to send inside the app, or send through Instagram below.',
    viaInstagram: 'Message on Instagram',
    viaMessenger: 'Message on Messenger',
    viaZalo: 'Message on Zalo',
    viaEmail: 'Send an email',
    copyMsg: 'Just copy the message',
    needTopic: 'Choose a topic first.',
    needSlot: 'Choose a time first.',
    msgHello: 'Hi Nabu, I would like to book a reading.',
    msgTopic: 'Topic',
    msgTime: 'Time',
    msgName: 'Name',
    msgNote: 'Extra question',
    msgCard: 'The card I just drew in the app',
    howItWorks: 'How booking works',
    aboutTitle: 'About Nabu Tarot',
    dow: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],

    meTitle: 'Your profile',
    meIntro: 'Your birthday and interests help the home screen pick the right content for you.',
    localOnly: 'Your profile is saved on this device.',
    accountsSoon: 'Sign-in for saving your profile, messaging and bookings is being set up by Nabu. For now the profile stays on this device.',
    signIn: 'Sign in',
    signInWith: { google: 'Continue with Google', facebook: 'Continue with Facebook', email: 'Continue with email' },
    signOut: 'Sign out',
    emailLabel: 'Email', passwordLabel: 'Password',
    createAccount: 'Create account', haveAccount: 'Have an account? Sign in', noAccount: 'No account? Create one',
    forgot: 'Forgot password', resetSent: 'Password reset email sent.',
    authFail: 'Sign-in failed',
    displayName: 'Display name',
    birthday: 'Birthday',
    interests: 'What do you care about?',
    saveProfile: 'Save profile',
    saved: 'Saved',
    myBookings: 'My bookings',
    noBookings: 'You have no bookings yet.',
    status: { requested: 'Awaiting confirmation', confirmed: 'Confirmed', declined: 'Declined', cancelled: 'Cancelled' },
    messages: 'Message Nabu',
    messagesIntro: 'Nabu replies inside the app. A red dot shows when there is something new.',
    messagesSoon: 'In-app messaging opens once Nabu turns on accounts. For now, message on Instagram.',
    typeMsg: 'Write a message...',
    send: 'Send',
    noMsgs: 'No messages yet. Ask away, Nabu will answer.',
    themeTitle: 'Appearance', themes: { auto: 'Match my phone', light: 'Light', dark: 'Dark' }, themeHint: 'Match my phone: the app switches with your phone\'s light or dark setting.',
    installTitle: 'Install on your phone',
    install: 'iPhone: open in Safari, tap Share, then "Add to Home Screen". Android: tap the ⋮ menu, then "Install app".',
    dismiss: 'Close',
    offlineReady: 'The app is ready to use offline.',

    adminTitle: 'Dashboard',
    adminIntro: 'This page is for Nabu only.',
    adminTabs: { posts: 'Posts', schedule: 'Availability', bookings: 'Bookings', inbox: 'Inbox', codes: 'Codes' },
    codesIntro: 'Once a client has paid, make a code here and send it to them. The expiry date is built into the code.', codeCourse: 'Course', codeStart: 'Starts', codeMonths: 'Months', makeCode: 'Make code', codeUntil: 'Expires',
    token: 'GitHub token',
    tokenHint: 'The token stays on this device only. See the README to create one.',
    saveToken: 'Save token',
    postDate: 'Date',
    postTitle: 'Title',
    postBody: 'Text',
    bodyHint: 'Leave a blank line to start a new paragraph.',
    postTitleEn: 'Title (English, optional)',
    postBodyEn: 'Text (English, optional)',
    postCards: 'Cards in this post (tap to select)',
    postTopics: 'Who this post is for',
    searchCard: 'Find a card',
    markInitials: 'Name starts with (comma separated)',
    markSigns: 'Signs',
    pinPost: 'Pin to top',
    preview: 'Preview',
    publish: 'Publish',
    publishing: 'Publishing...',
    published: 'Published. Everyone\'s feed updates within a few minutes.',
    publishFail: 'Publishing failed',
    copyJson: 'Copy JSON',
    existing: 'Published posts',
    edit: 'Edit',
    del: 'Delete',
    confirmDel: 'Delete this post?',
    newPost: 'New post',
    needBody: 'A post needs a title and some text.',
    needToken: 'Paste a token first.',
    weekly: 'Weekly free hours',
    weeklyHint: 'Tap an hour to turn it on or off. Each hour is one session.',
    blocked: 'Days off',
    blockedHint: 'No bookings on these days even if hours are set.',
    addDay: 'Add a day',
    bookedSlots: 'Taken slots',
    bookedHint: 'Bookings made through Instagram go here so the slot disappears.',
    leadDays: 'Earliest booking after (days)',
    horizonDays: 'Open calendar ahead (days)',
    saveSchedule: 'Save availability',
    scheduleSaved: 'Saved. Clients see it within a few minutes.',
    bookingsIntro: 'Requests sent inside the app. Confirming locks the slot.',
    confirm: 'Confirm', decline: 'Decline',
    needFirebase: 'This section needs accounts turned on (Firebase). See the README.',
    adminLogin: 'Sign in with an admin email to see this section.',
    inboxEmpty: 'No conversations yet.',
    reply: 'Reply',
    back: 'Back',

    suitOf: { major: 'Major', wands: 'Wands', cups: 'Cups', swords: 'Swords', pentacles: 'Pentacles' },
    zodiac: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'],
    dateFmt: (d) => d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
    dateShort: (d) => d.getDate() + '/' + (d.getMonth() + 1)
  }
};

/* Nabu Tarot's five preset topics. Fixed brand copy: never paraphrase. */
const TOPICS = [
  { id: 1, icon: '💗', interest: 'love', name: { vi: 'Tình cảm hiện tại', en: 'Current relationship' },
    q: { vi: ['Năng lượng hiện tại của mối quan hệ này là gì?', 'Người ấy hiện đang có cảm xúc như thế nào với mình?', 'Người ấy nhìn nhận mình và mối quan hệ này ra sao?', 'Trở ngại lớn nhất giữa hai người hiện tại là gì?', 'Mối quan hệ có xu hướng phát triển thế nào trong 1–3 tháng tới?'],
         en: ['What is the current energy of this relationship?', 'How does this person feel about me right now?', 'How do they see me and this relationship?', 'What is the biggest obstacle between us right now?', 'How is the relationship likely to develop in the next 1–3 months?'] } },
  { id: 2, icon: '💔', interest: 'ex', name: { vi: 'Người cũ', en: 'An ex' },
    q: { vi: ['Người ấy hiện nghĩ gì về mình?', 'Họ còn tình cảm với mình không?', 'Vì sao họ chưa chủ động liên lạc?', 'Có khả năng hai người liên lạc hoặc gặp lại nhau không?', 'Mình nên tiếp tục chờ đợi hay buông bỏ?'],
         en: ['What do they think of me now?', 'Do they still have feelings for me?', 'Why have they not reached out?', 'Is there a chance we get in touch or meet again?', 'Should I keep waiting or let go?'] } },
  { id: 3, icon: '💗', interest: 'crush', name: { vi: 'Mập mờ - Crush', en: 'Situationship / crush' },
    q: { vi: ['Người ấy có cảm xúc gì với mình?', 'Họ có nhận ra tình cảm của mình không?', 'Ý định của họ đối với mình là gì?', 'Điều gì đang ngăn mối quan hệ này tiến triển thêm?', 'Khả năng hai người trở thành một cặp trong thời gian tới như thế nào?'],
         en: ['What do they feel for me?', 'Do they notice my feelings?', 'What are their intentions with me?', 'What is holding this back from going further?', 'How likely are we to become a couple soon?'] } },
  { id: 4, icon: '⭐', interest: 'work', name: { vi: 'Công việc', en: 'Career' },
    q: { vi: ['Tình hình công việc hiện tại của mình đang ở đâu?', 'Điểm mạnh nào mình nên tận dụng?', 'Trở ngại lớn nhất trong công việc hiện tại là gì?', 'Cơ hội đáng chú ý nào có thể xuất hiện sắp tới?', 'Mình nên làm gì để phát triển sự nghiệp tốt hơn?'],
         en: ['Where is my work situation right now?', 'Which strength should I lean on?', 'What is the biggest obstacle at work right now?', 'What notable opportunity may come up soon?', 'What should I do to grow my career?'] } },
  { id: 5, icon: '✉️', interest: 'study', name: { vi: 'Học tập', en: 'Study' },
    q: { vi: ['Tình trạng học tập hiện tại của mình như thế nào?', 'Điểm yếu nào đang ảnh hưởng đến kết quả học tập?', 'Điểm mạnh nào mình nên tận dụng?', 'Hướng học tập nào phù hợp hơn với bản thân mình?', 'Mình nên thay đổi gì để đạt kết quả tốt hơn?'],
         en: ['How is my study going right now?', 'Which weakness is hurting my results?', 'Which strength should I lean on?', 'Which study path suits me better?', 'What should I change to do better?'] } }
];
