/* ============================ UI strings ============================
   Vietnamese is the first language of the app. Keep every line short and
   spoken; the reader is a client on a phone, not a student. */
const STR = {
  vi: {
    lang: 'EN',
    nav: { feed: 'Dự đoán', pick: 'Rút bài', book: 'Đặt lịch' },

    feedTitle: 'Dự đoán mới',
    feedEmpty: 'Chưa có bài nào. Quay lại sau nhé.',
    feedOffline: 'Đang xem bản đã lưu. Mở mạng để cập nhật.',
    pinned: 'Ghim',
    readMore: 'Đọc thêm',
    readLess: 'Thu gọn',
    share: 'Chia sẻ',
    copied: 'Đã sao chép',
    forYouIf: 'Dành cho bạn nếu',
    initials: 'tên bắt đầu bằng',
    signs: 'cung',
    cardsDrawn: 'Lá bài trong bài này',
    ctaPick: 'Rút một lá cho riêng bạn',
    ctaBook: 'Đặt lịch xem bài',
    backToFeed: 'Về trang dự đoán',
    notFound: 'Không tìm thấy bài này.',

    pickTitle: 'Năng lượng hiện tại của bạn',
    pickIntro: 'Hít một hơi thật sâu. Nghĩ về hôm nay. Rồi chạm vào một lá bài.',
    focusLabel: 'Bạn đang nghĩ về',
    focus: { general: 'Chung', love: 'Tình cảm', work: 'Công việc', study: 'Học tập', money: 'Tiền bạc' },
    tapACard: 'Chạm vào một lá',
    redraw: 'Xào lại và rút lá khác',
    yourCard: 'Lá bài của bạn',
    energyNow: 'Năng lượng lúc này',
    energyLine: (kws) => 'Lúc này bạn đang mang năng lượng: ' + kws + '.',
    cardSays: 'Lá bài nói gì',
    onTheCard: 'Trên lá bài',
    shadow: 'Mặt trái cần để ý',
    shadowLine: (kws) => 'Nếu năng lượng này quá đà, nó thành: ' + kws + '.',
    focusHead: (f) => 'Nếu bạn đang nghĩ về ' + f.toLowerCase(),
    noFocus: 'Chưa có bài giảng riêng cho chủ đề này với lá này. Bạn đọc phần năng lượng ở trên nhé.',
    source: 'Ý nghĩa lá bài theo bài giảng của Thu Anh (kênh Tự Học Tarot cùng Thu Anh).',
    quickNote: 'Đây là lời nhắn nhanh từ một lá bài. Muốn hiểu rõ chuyện của bạn, hãy đặt lịch xem bài đầy đủ.',
    shareCard: 'Chia sẻ lá bài',
    bookWithCard: 'Đặt lịch xem sâu hơn',
    shareText: (name, kws) => 'Lá bài hôm nay của mình: ' + name + '. Năng lượng: ' + kws + '. Rút thử ở ',

    bookTitle: 'Đặt lịch xem bài',
    chooseTopic: 'Chọn chủ đề',
    presetTopics: 'Chủ đề sẵn',
    topicHint: 'Mỗi chủ đề là trải bài 5 lá. Bấm để xem 5 câu hỏi.',
    ownTopic: 'Câu hỏi riêng',
    ownTopicHint: 'Bạn tự viết câu hỏi của mình.',
    yourName: 'Tên bạn (hoặc biệt danh)',
    yourNote: 'Bạn muốn hỏi thêm gì?',
    notePlaceholder: 'Kể ngắn gọn chuyện của bạn, hoặc câu hỏi bạn muốn hỏi.',
    sendVia: 'Gửi tin nhắn đặt lịch',
    sendHint: 'Tin nhắn được sao chép sẵn. Bấm vào ứng dụng, rồi dán vào ô chat.',
    viaInstagram: 'Nhắn qua Instagram',
    viaMessenger: 'Nhắn qua Messenger',
    viaZalo: 'Nhắn qua Zalo',
    viaEmail: 'Gửi email',
    copyMsg: 'Chỉ sao chép tin nhắn',
    needTopic: 'Bạn chọn một chủ đề trước nhé.',
    msgHello: 'Chào Nabu, mình muốn đặt lịch xem bài.',
    msgTopic: 'Chủ đề',
    msgName: 'Tên',
    msgNote: 'Câu hỏi thêm',
    msgCard: 'Lá mình vừa rút trong app',
    howItWorks: 'Cách đặt lịch',
    aboutTitle: 'Về Nabu Tarot',

    adminTitle: 'Đăng bài dự đoán',
    adminIntro: 'Trang này chỉ dành cho Nabu. Bài đăng ở đây hiện ngay trên trang Dự đoán của mọi người.',
    token: 'GitHub token',
    tokenHint: 'Token chỉ lưu trên máy này. Xem README để tạo token.',
    saveToken: 'Lưu token',
    postDate: 'Ngày',
    postTitle: 'Tiêu đề',
    postBody: 'Nội dung',
    bodyHint: 'Cách một dòng trống để xuống đoạn.',
    postTitleEn: 'Tiêu đề (English, không bắt buộc)',
    postBodyEn: 'Nội dung (English, không bắt buộc)',
    postCards: 'Lá bài trong bài (chạm để chọn)',
    searchCard: 'Tìm lá bài',
    markInitials: 'Tên bắt đầu bằng (cách nhau bằng dấu phẩy)',
    markSigns: 'Cung',
    pinPost: 'Ghim lên đầu',
    preview: 'Xem trước',
    publish: 'Đăng bài',
    publishing: 'Đang đăng...',
    published: 'Đã đăng. Trang của mọi người sẽ cập nhật trong vài phút.',
    publishFail: 'Đăng không thành công',
    copyJson: 'Sao chép JSON',
    existing: 'Bài đã đăng',
    edit: 'Sửa',
    del: 'Xoá',
    confirmDel: 'Xoá bài này?',
    newPost: 'Bài mới',
    needBody: 'Bài cần có tiêu đề và nội dung.',
    needToken: 'Bạn cần dán token trước.',

    install: 'Thêm vào màn hình chính: bấm Chia sẻ, rồi chọn "Thêm vào MH chính".',
    dismiss: 'Đóng',
    offlineReady: 'App đã sẵn sàng dùng offline.',
    suitOf: { major: 'Ẩn Chính', wands: 'Gậy', cups: 'Cốc', swords: 'Kiếm', pentacles: 'Tiền' },
    zodiac: ['Bạch Dương', 'Kim Ngưu', 'Song Tử', 'Cự Giải', 'Sư Tử', 'Xử Nữ', 'Thiên Bình', 'Bọ Cạp', 'Nhân Mã', 'Ma Kết', 'Bảo Bình', 'Song Ngư'],
    dateFmt: (d) => d.getDate() + ' tháng ' + (d.getMonth() + 1) + ', ' + d.getFullYear()
  },

  en: {
    lang: 'VI',
    nav: { feed: 'Readings', pick: 'Pick a card', book: 'Book' },

    feedTitle: 'Latest readings',
    feedEmpty: 'Nothing posted yet. Come back soon.',
    feedOffline: 'Showing the saved copy. Go online to update.',
    pinned: 'Pinned',
    readMore: 'Read more',
    readLess: 'Show less',
    share: 'Share',
    copied: 'Copied',
    forYouIf: 'For you if',
    initials: 'your name starts with',
    signs: 'sign',
    cardsDrawn: 'Cards in this reading',
    ctaPick: 'Pick a card of your own',
    ctaBook: 'Book a reading',
    backToFeed: 'Back to readings',
    notFound: 'This post was not found.',

    pickTitle: 'Your energy right now',
    pickIntro: 'Take a deep breath. Think about today. Then tap a card.',
    focusLabel: 'On your mind',
    focus: { general: 'General', love: 'Love', work: 'Work', study: 'Study', money: 'Money' },
    tapACard: 'Tap a card',
    redraw: 'Shuffle and pick again',
    yourCard: 'Your card',
    energyNow: 'Energy right now',
    energyLine: (kws) => 'Right now you carry this energy: ' + kws + '.',
    cardSays: 'What the card says',
    onTheCard: 'On the card',
    shadow: 'The shadow side',
    shadowLine: (kws) => 'When this energy runs too hot, it turns into: ' + kws + '.',
    focusHead: (f) => 'If ' + f.toLowerCase() + ' is on your mind',
    noFocus: 'No lecture notes for this topic with this card yet. Read the energy section above.',
    source: 'Card meanings follow Thu Anh\'s lectures (channel Tự Học Tarot cùng Thu Anh). Her readings are in Vietnamese.',
    quickNote: 'This is a quick message from one card. For your own situation, book a full reading.',
    shareCard: 'Share this card',
    bookWithCard: 'Book a deeper reading',
    shareText: (name, kws) => 'My card today: ' + name + '. Energy: ' + kws + '. Try it at ',

    bookTitle: 'Book a reading',
    chooseTopic: 'Choose a topic',
    presetTopics: 'Set topics',
    topicHint: 'Each topic is a five-card spread. Tap to see the five questions.',
    ownTopic: 'Your own question',
    ownTopicHint: 'Write your own question.',
    yourName: 'Your name (or nickname)',
    yourNote: 'Anything to add?',
    notePlaceholder: 'A few lines about your situation, or the question you want to ask.',
    sendVia: 'Send the booking message',
    sendHint: 'The message is copied for you. Open the app, then paste it into the chat.',
    viaInstagram: 'Message on Instagram',
    viaMessenger: 'Message on Messenger',
    viaZalo: 'Message on Zalo',
    viaEmail: 'Send an email',
    copyMsg: 'Just copy the message',
    needTopic: 'Choose a topic first.',
    msgHello: 'Hi Nabu, I would like to book a reading.',
    msgTopic: 'Topic',
    msgName: 'Name',
    msgNote: 'Extra question',
    msgCard: 'The card I just drew in the app',
    howItWorks: 'How booking works',
    aboutTitle: 'About Nabu Tarot',

    adminTitle: 'Post a reading',
    adminIntro: 'This page is for Nabu only. Posts made here appear on everyone\'s Readings tab.',
    token: 'GitHub token',
    tokenHint: 'The token stays on this device only. See the README to create one.',
    saveToken: 'Save token',
    postDate: 'Date',
    postTitle: 'Title',
    postBody: 'Text',
    bodyHint: 'Leave a blank line to start a new paragraph.',
    postTitleEn: 'Title (English, optional)',
    postBodyEn: 'Text (English, optional)',
    postCards: 'Cards in this post (tap to select)',
    searchCard: 'Find a card',
    markInitials: 'Name starts with (comma separated)',
    markSigns: 'Signs',
    pinPost: 'Pin to top',
    preview: 'Preview',
    publish: 'Publish',
    publishing: 'Publishing...',
    published: 'Published. Everyone\'s feed updates within a few minutes.',
    publishFail: 'Publishing failed',
    copyJson: 'Copy JSON',
    existing: 'Published posts',
    edit: 'Edit',
    del: 'Delete',
    confirmDel: 'Delete this post?',
    newPost: 'New post',
    needBody: 'A post needs a title and some text.',
    needToken: 'Paste a token first.',

    install: 'Add to Home Screen: tap Share, then "Add to Home Screen".',
    dismiss: 'Close',
    offlineReady: 'The app is ready to use offline.',
    suitOf: { major: 'Major', wands: 'Wands', cups: 'Cups', swords: 'Swords', pentacles: 'Pentacles' },
    zodiac: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'],
    dateFmt: (d) => d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  }
};

/* Nabu Tarot's five preset topics. Fixed brand copy: never paraphrase. */
const TOPICS = [
  { id: 1, icon: '💗', name: { vi: 'Tình cảm hiện tại', en: 'Current relationship' },
    q: { vi: ['Năng lượng hiện tại của mối quan hệ này là gì?', 'Người ấy hiện đang có cảm xúc như thế nào với mình?', 'Người ấy nhìn nhận mình và mối quan hệ này ra sao?', 'Trở ngại lớn nhất giữa hai người hiện tại là gì?', 'Mối quan hệ có xu hướng phát triển thế nào trong 1–3 tháng tới?'],
         en: ['What is the current energy of this relationship?', 'How does this person feel about me right now?', 'How do they see me and this relationship?', 'What is the biggest obstacle between us right now?', 'How is the relationship likely to develop in the next 1–3 months?'] } },
  { id: 2, icon: '💔', name: { vi: 'Người cũ', en: 'An ex' },
    q: { vi: ['Người ấy hiện nghĩ gì về mình?', 'Họ còn tình cảm với mình không?', 'Vì sao họ chưa chủ động liên lạc?', 'Có khả năng hai người liên lạc hoặc gặp lại nhau không?', 'Mình nên tiếp tục chờ đợi hay buông bỏ?'],
         en: ['What do they think of me now?', 'Do they still have feelings for me?', 'Why have they not reached out?', 'Is there a chance we get in touch or meet again?', 'Should I keep waiting or let go?'] } },
  { id: 3, icon: '💗', name: { vi: 'Mập mờ - Crush', en: 'Situationship / crush' },
    q: { vi: ['Người ấy có cảm xúc gì với mình?', 'Họ có nhận ra tình cảm của mình không?', 'Ý định của họ đối với mình là gì?', 'Điều gì đang ngăn mối quan hệ này tiến triển thêm?', 'Khả năng hai người trở thành một cặp trong thời gian tới như thế nào?'],
         en: ['What do they feel for me?', 'Do they notice my feelings?', 'What are their intentions with me?', 'What is holding this back from going further?', 'How likely are we to become a couple soon?'] } },
  { id: 4, icon: '⭐', name: { vi: 'Công việc', en: 'Career' },
    q: { vi: ['Tình hình công việc hiện tại của mình đang ở đâu?', 'Điểm mạnh nào mình nên tận dụng?', 'Trở ngại lớn nhất trong công việc hiện tại là gì?', 'Cơ hội đáng chú ý nào có thể xuất hiện sắp tới?', 'Mình nên làm gì để phát triển sự nghiệp tốt hơn?'],
         en: ['Where is my work situation right now?', 'Which strength should I lean on?', 'What is the biggest obstacle at work right now?', 'What notable opportunity may come up soon?', 'What should I do to grow my career?'] } },
  { id: 5, icon: '✉️', name: { vi: 'Học tập', en: 'Study' },
    q: { vi: ['Tình trạng học tập hiện tại của mình như thế nào?', 'Điểm yếu nào đang ảnh hưởng đến kết quả học tập?', 'Điểm mạnh nào mình nên tận dụng?', 'Hướng học tập nào phù hợp hơn với bản thân mình?', 'Mình nên thay đổi gì để đạt kết quả tốt hơn?'],
         en: ['How is my study going right now?', 'Which weakness is hurting my results?', 'Which strength should I lean on?', 'Which study path suits me better?', 'What should I change to do better?'] } }
];
