/* Vietnamese card names and text (The Learner's Deck). */
const LANGS = ['en', 'vi'];

const LEX = {
  en: {
    numbers: ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'],
    courts: ['Page', 'Knight', 'Queen', 'King'],
    suitNames: { major: 'Major Arcana', wands: 'Wands', cups: 'Cups', swords: 'Swords', pentacles: 'Pentacles' },
    elements: { wands: 'Fire', cups: 'Water', swords: 'Air', pentacles: 'Earth' },
    courtTag: 'Court',
    pipName: (n, s) => `${n} of ${s}`,
    courtName: (c, s) => `${c} of ${s}`
  },
  vi: {
    numbers: ['Át', 'Hai', 'Ba', 'Bốn', 'Năm', 'Sáu', 'Bảy', 'Tám', 'Chín', 'Mười'],
    courts: ['Tiểu Đồng', 'Kỵ Sĩ', 'Nữ Hoàng', 'Đức Vua'],
    suitNames: { major: 'Ẩn Chính', wands: 'Gậy', cups: 'Cốc', swords: 'Kiếm', pentacles: 'Tiền' },
    elements: { wands: 'Lửa', cups: 'Nước', swords: 'Khí', pentacles: 'Đất' },
    courtTag: 'Hoàng gia',
    pipName: (n, s) => `${n} ${s}`,
    courtName: (c, s) => `${c} ${s}`
  }
};

const MAJORS_VI = [
["Gã Khờ","khởi đầu · niềm tin · ngây thơ · bước nhảy",
 "Một chàng trai mặc áo hoa văn bước về phía mép vực, mặt ngước lên vầng mặt trời trắng. Một tay cầm đóa hồng trắng, vai vác chiếc túi buộc đầu gậy, và một chú chó trắng nhỏ chồm lên bên gót chân.",
 "Lá bài này nói về khởi đầu của một điều gì đó khi bạn chưa có bằng chứng nào rằng nó sẽ thành. Ở đây, niềm tin đi trước chứng cứ, và bạn có được thứ tự do rất riêng của người chưa có gì để mất.",
 "Lá ngược cho thấy bạn đang liều lĩnh, hoặc đúng điều ngược lại: bạn không chịu nhúc nhích chỉ vì nhìn xuống thấy vực quá sâu."],
["Nhà Ảo Thuật","ý chí · tập trung · nguồn lực · hiện thực hóa",
 "Nhà Ảo Thuật một tay giơ lên trời, một tay chỉ xuống đất, dấu vô cực lơ lửng trên đầu. Trên bàn trước mặt ông là một cây gậy, một chiếc cốc, một thanh kiếm và một đồng tiền, tức là đủ cả bốn chất.",
 "Bạn đã có sẵn mọi công cụ mà tình huống này đòi hỏi. Việc cần làm không phải là kiếm thêm, mà là chĩa tất cả những gì đang có vào đúng một việc.",
 "Lá ngược cho thấy tài năng đang bị vung vãi vào quá nhiều thứ, hoặc tài thuyết phục đang bị dùng để thao túng."],
["Nữ Tư Tế","trực giác · điều chưa lộ · cái biết bên trong",
 "Bà ngồi giữa một cột đen và một cột trắng, vầng trăng lưỡi liềm dưới chân, tấm màn thêu quả lựu buông sau lưng, và cuộn thư trong lòng chỉ lộ ra một nửa.",
 "Câu trả lời đã có nhưng chưa nổi lên. Bạn hãy chờ, lắng nghe bên trong, và đừng ép điều gì phải lộ ra, dù là từ chính bạn hay từ người khác.",
 "Lá ngược cho thấy bạn đang gạt bỏ linh cảm của chính mình, hoặc một bí mật đã được giữ quá lâu so với lúc nó còn có ích cho ai đó."],
["Hoàng Hậu","sung túc · nuôi dưỡng · sáng tạo · giác quan",
 "Một người phụ nữ đội vương miện giữa cánh đồng lúa mì đang chín, vòng mười hai ngôi sao trên đầu, bên cạnh là tấm khiên hình trái tim mang ký hiệu sao Kim.",
 "Có điều gì đó đang lớn lên và chủ yếu cần được nuôi chứ không cần sửa. Lá bài này nói về sự phì nhiêu theo mọi nghĩa: sáng tạo, thể chất, đủ đầy vật chất, và niềm vui hưởng thụ mà không thấy áy náy.",
 "Bạn đang yêu thương đến mức ngột ngạt, bí tắc trong sáng tạo, hoặc dồn hết sự chăm sóc cho mọi thứ trừ chính mình."],
["Hoàng Đế","cấu trúc · quyền lực · ranh giới",
 "Một vị vua có râu ngồi trên ngai đá chạm đầu cừu đực, tay cầm quyền trượng hình chữ ankh, sau lưng là dãy núi trơ trọi.",
 "Trật tự được áp lên hỗn loạn bằng luật lệ, kỷ luật và sự che chở. Đây là lá bài của người ra quyết định, và của ranh giới khiến mọi thứ còn lại trở nên khả thi.",
 "Lá ngược cho thấy sự cứng nhắc và áp chế, hoặc ngược lại, hoàn toàn không có cấu trúc nào, khiến mọi thứ chông chênh."],
["Giáo Hoàng","truyền thống · giảng dạy · thiết chế",
 "Một vị mặc lễ phục đội vương miện ba tầng giơ tay ban phước cho hai tu sĩ cạo đỉnh đầu. Dưới chân ông là hai chiếc chìa khóa bắt chéo.",
 "Con đường đã được thiết lập, và có một người đủ tư cách truyền dạy nó. Lá bài này nói về việc học trong một dòng truyền thừa, và về giá trị của việc làm đúng như xưa nay vẫn làm.",
 "Lá ngược cho thấy một giáo điều đã hết thời, hoặc một lời gọi thật sự để bạn phá bỏ lề thói."],
["Tình Nhân","kết hợp · lựa chọn · giá trị",
 "Một người nam và một người nữ đứng trần dưới thiên thần có cánh giữa nắng chói. Sau lưng nàng là con rắn quấn thân cây; sau lưng chàng là cái cây bốc lửa.",
 "Lá bài này nói về một cuộc gặp thật sự giữa hai bên, và về một lựa chọn phơi bày điều bạn thật sự coi trọng, chứ không phải điều bạn nói là mình coi trọng.",
 "Lá ngược cho thấy hai bên đang lệch pha, một quyết định đang bị né tránh, hoặc một mối quan hệ mà sức nặng dồn hết về một phía."],
["Cỗ Chiến Xa","động lực · kiểm soát · chiến thắng",
 "Một người mặc giáp đứng trên cỗ xe dưới mái vòm điểm sao, do một nhân sư đen và một nhân sư trắng kéo. Trong tranh không hề có dây cương.",
 "Bạn tiến tới được nhờ giữ hai lực đối nghịch trên cùng một hướng. Ý chí đang thắng hoàn cảnh, ít nhất là lúc này.",
 "Bạn đang bị kéo về hai phía cùng lúc, hoặc đang lao đi mà không ai cầm lái."],
["Sức Mạnh","can đảm · kiên nhẫn · sức mạnh mềm",
 "Một người phụ nữ áo trắng thong thả khép hàm sư tử bằng tay không, dấu vô cực trên đầu. Nàng không hề gắng sức.",
 "Bạn gây ảnh hưởng bằng sự dịu dàng và bền bỉ thay vì bằng vũ lực. Lá bài còn có một nghĩa nhẹ nhàng hơn: bạn làm chủ ham muốn của chính mình thay vì của người khác.",
 "Lá ngược cho thấy bạn đang hoài nghi bản thân, hoặc đang dùng sức ép ở nơi lẽ ra chỉ cần kiên nhẫn."],
["Ẩn Sĩ","tịch liêu · tìm kiếm · ánh sáng bên trong",
 "Một ông lão khoác áo choàng trên đỉnh núi tuyết giơ cao chiếc đèn lồng có ngôi sao sáu cánh cháy bên trong, chống mình trên cây gậy dài.",
 "Bạn chủ động rút lui để tự tìm câu trả lời của mình. Đây là một quãng để học, để yên tĩnh, và để cố ý không hỏi ý đám đông.",
 "Lá ngược cho thấy sự cô lập đã hóa thành né tránh, hoặc bạn đang chối bỏ một bàn tay thật lòng chìa ra."],
["Bánh Xe Số Phận","chu kỳ · bước ngoặt · vận may",
 "Một bánh xe lớn khắc chữ T-A-R-O quay giữa trời. Nhân sư ngự phía trên, con rắn trườn xuống một bên, con chó rừng leo lên bên kia, và bốn sinh vật có cánh đang đọc sách ở bốn góc.",
 "Hoàn cảnh đổi thay theo nhịp riêng của nó. Bạn hãy đi theo vòng quay, thay vì bám chặt một nan hoa và đòi nó phải ở mãi trên đỉnh.",
 "Lá ngược cho thấy một nhịp đi xuống, sự chống cự trước một thay đổi vốn đã bắt đầu, hoặc đơn giản là bạn đang sai thời điểm."],
["Công Lý","công bằng · nhân quả · sự thật",
 "Một nhân vật đội vương miện ngồi giữa hai cây cột, một tay cầm thanh kiếm dựng thẳng, tay kia giữ cán cân thăng bằng tuyệt đối.",
 "Mọi thứ được cân đo chính xác và hậu quả đang tới. Lá bài này nói về một quyết định buộc phải trung thực chứ không phải tử tế.",
 "Lá ngược cho thấy sự thiên vị, một sổ sách bị lệch, hoặc một trách nhiệm đã được né tránh thành công, ít nhất là lúc này."],
["Người Treo Ngược","treo lơ lửng · đảo chiều · buông bỏ",
 "Một người đàn ông bình thản treo mình bằng một mắt cá chân trên thân cây sống hình chữ T, chân còn lại bắt chéo ra sau, quầng sáng bao quanh đầu.",
 "Đây là một khoảng dừng có chủ ý. Câu trả lời đến từ việc lộn ngược góc nhìn, chứ không phải từ việc đẩy mạnh hơn theo hướng bạn vốn đang đi.",
 "Lá ngược cho thấy sự trì hoãn đang khoác áo chiêm nghiệm, hoặc một hy sinh mà bạn không nhận lại được gì."],
["Cái Chết","kết thúc · chuyển tiếp · dọn sạch",
 "Một bộ xương mặc giáp đen cưỡi ngựa trắng đi ngang vị vua đã ngã. Lá cờ của nó mang đóa hồng trắng, và mặt trời mọc lên giữa hai tòa tháp nơi chân trời.",
 "Một điều gì đó chấm dứt hẳn để điều tiếp theo có chỗ tồn tại. Lá bài này gần như không bao giờ được hiểu theo nghĩa đen, và điều nó báo gần như không thương lượng được.",
 "Lá ngược cho thấy bạn đang bám lấy điều đã xong, hoặc một kết thúc đang bị kéo dài lâu hơn mức cần thiết rất nhiều."],
["Điều Độ","cân bằng · pha trộn · chừng mực",
 "Một thiên thần có cánh, một chân trên bờ một chân dưới nước, rót chất lỏng qua lại giữa hai chiếc cốc theo một đường vòng lẽ ra không thể có.",
 "Bạn kiên nhẫn chỉnh đi chỉnh lại cho đến khi tỷ lệ vừa đúng. Sự chữa lành và hồi phục cần bao nhiêu thời gian thì sẽ lấy bấy nhiêu.",
 "Lá ngược cho thấy sự thái quá, sự nóng vội, hoặc hai thành phần đơn giản là không thể hòa vào nhau."],
["Ác Quỷ","trói buộc · thôi thúc · bóng tối",
 "Một sinh vật có sừng ngồi xổm trên bệ đá, ngôi sao năm cánh lộn ngược giữa trán. Bên dưới, một người nam và một người nữ bị xích, nhưng sợi xích lỏng đến mức có thể nhấc thẳng ra khỏi cổ.",
 "Một sự dính mắc đang điều khiển bạn: một thói quen, một cơn thèm, một mối quan hệ mà bạn tự nhủ mình không thể rời. Chi tiết sợi xích lỏng lẻo chính là toàn bộ thông điệp.",
 "Lá ngược cho thấy bạn nhìn ra sợi xích đúng như nó vốn là, và có động thái đầu tiên để gỡ nó ra."],
["Tòa Tháp","sụp đổ đột ngột · vỡ lẽ",
 "Tia sét đánh bay chiếc vương miện khỏi đỉnh tháp cao. Lửa phụt ra từ các ô cửa và hai người lao đầu rơi xuống bóng tối.",
 "Một công trình dựng trên nền giả dối đổ xuống rất nhanh. Sự sụp đổ này đau đớn nhưng làm sáng tỏ mọi việc, và một khi đã bắt đầu thì không còn lựa chọn nào khác.",
 "Lá ngược cho thấy một tai họa được tránh trong gang tấc, hoặc một sự sụp đổ mà bạn đang kéo dài đến kiệt sức."],
["Ngôi Sao","hy vọng · hồi sinh · dẫn đường",
 "Một người phụ nữ trần quỳ bên hồ nước, một bình rót nước xuống đất, bình kia rót ngược trở lại hồ. Trên đầu là một ngôi sao lớn và bảy ngôi sao nhỏ đang cháy sáng.",
 "Đây là sự bình yên sau đổ nát. Niềm tin được phục hồi, và bạn có cảm giác rõ ràng về hướng đi thuộc về mình. Lá bài này thường đến ngay sau lá Tòa Tháp.",
 "Bạn đang nản lòng, niềm tin mòn dần, và bạn để tuột mất sợi chỉ mình đang lần theo."],
["Mặt Trăng","bất định · giấc mơ · méo mó",
 "Vầng trăng có gương mặt nhỏ những giọt sương xuống con đường chạy giữa hai tòa tháp. Một con chó và một con sói tru lên, và một con tôm càng bò lên từ mặt hồ.",
 "Địa hình không rõ ràng và cách bạn đọc nó có thể sai. Nỗi sợ, trí tưởng tượng và bản năng cùng lên tiếng một lúc, trong bóng tối.",
 "Sương mù tan dần, hoặc một sự dối trá cuối cùng cũng lộ ra ánh sáng."],
["Mặt Trời","sáng rõ · sức sống · thành công",
 "Một đứa trẻ cưỡi ngựa trắng dưới vầng mặt trời rực rỡ khổng lồ, lá cờ đỏ bay phấp phới phía sau, và một bức tường hoa hướng dương làm nền.",
 "Mọi thứ đơn giản là tốt đẹp, và ai cũng thấy được. Lá bài này mang năng lượng, hơi ấm và niềm vui thật thà, và là lá bài ít rắc rối nhất trong cả bộ.",
 "Lá ngược cho thấy nhiệt huyết đang mờ đi, thành công bị trì hoãn, hoặc sự lạc quan chỉ được diễn ra chứ không được cảm thấy thật."],
["Phán Xét","tính sổ · thức tỉnh · tiếng gọi",
 "Một thiên thần thổi kèn giữa tầng mây và những bóng người xám đứng dậy từ các cỗ quan tài mở nắp, hai tay giang rộng.",
 "Đây là một cuộc tổng kết. Bạn nhìn thấy trọn vẹn cả cung đường của một điều gì đó cùng lúc, và đáp lại tiếng gọi mà bạn không thể vờ như chưa từng nghe.",
 "Lá ngược cho thấy bạn đang tự trách mình quá nặng, hoặc nghe rõ tiếng gọi mà vẫn làm ngơ."],
["Thế Giới","hoàn tất · trọn vẹn · hợp nhất",
 "Một vũ công quấn dải lụa tím đứng giữa vòng nguyệt quế. Con bò, con sư tử, con đại bàng và một thiên thần chiếm bốn góc tranh.",
 "Chu kỳ khép lại đúng cách. Lá bài này nói về sự đến nơi, và về năng lực chỉ có được khi bạn đã đi trọn cả vòng.",
 "Lá ngược cho thấy mọi việc suýt nữa là xong: một đầu mối vẫn còn bỏ ngỏ, hoặc một sự khép lại mà ai đó đang giữ lại không trao."]
];

const MINORS_VI = {
wands:{ pips:[
 ["Một bàn tay vươn ra từ đám mây, trao một cành cây đang nảy lộc, lá vẫn còn rơi lả tả.","Đây là một tia lửa, đợt dâng đầu tiên của ham muốn làm ra điều gì đó. Năng lượng này còn thô và chưa nhắm vào đâu cả.","Lá ngược cho thấy một khởi đầu hụt, hoặc năng lượng không biết đổ vào đâu."],
 ["Một người đàn ông đứng trên tường thành của chính mình, tay cầm quả địa cầu, nhìn ra xa khỏi bức tường do mình dựng lên.","Bạn hoạch định vượt ra ngoài những gì đang nắm trong tay. Bạn chọn chân trời rộng hơn thay vì chân trời dễ chịu hơn.","Bạn đang chơi an toàn, hoặc những kế hoạch của bạn không bao giờ rời khỏi mặt bàn."],
 ["Một người đứng trên vách đá nhìn những con thuyền dong buồm ra khơi.","Những nỗ lực đầu tiên đã lên đường và không còn trong tay bạn nữa. Lá bài này nói về sự mở rộng, và về quãng chờ đợi sau khi bạn đã phóng một thứ gì đó đi.","Lá ngược cho thấy sự trì hoãn, sự chờ đợi trong bồn chồn, hoặc một kế hoạch được đặt ra quá nhỏ."],
 ["Bốn cây cột kết hoa tạo thành cổng chào trước tòa lâu đài; bên dưới, những người dự hội giơ cao những bó hoa.","Đây là một ngưỡng cửa đáng dừng lại để đánh dấu: sự trở về, sự ổn định, hoặc một cột mốc đạt được cùng với người khác.","Lá ngược vẫn mang nghĩa đó nhưng lặng lẽ hơn: một cuộc ăn mừng bị hoãn lại, hoặc chỉ được giữ riêng cho mình."],
 ["Năm chàng trai vung gậy trong một trận ẩu đả giả, lộn xộn và không ra hàng lối.","Lá bài này nói về va chạm và cạnh tranh. Ai cũng nói chồng lên lời người khác, và rốt cuộc không ai được lắng nghe.","Lá ngược cho thấy xung đột đang được né tránh, hoặc một cuộc tranh cãi dai dẳng cuối cùng cũng lắng xuống."],
 ["Một kỵ sĩ đội vòng nguyệt quế đi giữa đám đông reo hò, trên cây gậy cũng có một vòng nguyệt quế.","Lá bài này nói về sự công nhận công khai. Đây là chiến thắng mà người khác nhìn thấy và thừa nhận.","Lá ngược cho thấy sự công nhận đang bị giữ lại, hoặc một thành công nghe rỗng tuếch ngay khi bạn đã cầm được nó."],
 ["Một người đứng trên gò cao chống đỡ sáu cây gậy chĩa lên từ phía dưới.","Bạn giữ vững vị trí dưới áp lực. Bạn hãy bảo vệ thứ mình đã dựng nên, vì bạn đang ở thế cao hơn.","Bạn đang bị áp đảo, hoặc đang nhường lại phần đất lẽ ra phải giữ."],
 ["Tám cây gậy bay giữa trời quang trên một dòng sông. Trong tranh không có bóng người nào.","Tốc độ đến một cách đột ngột. Tin tức, những chuyến đi và mọi thứ ập tới cùng lúc sau một quãng dài đứng yên.","Mọi thứ ách tắc, hoặc năng lượng tản ra tám hướng."],
 ["Một người đàn ông quấn băng tựa vào cây gậy, mắt canh hàng rào, chuẩn bị sẵn cho đợt tiếp theo.","Bạn rã rời nhưng vẫn đứng vững. Chỉ còn một đợt nữa thôi, và sự đề phòng của bạn là do trả giá mà có.","Lá ngược cho thấy bạn đang đa nghi thái quá, hoặc một sự kiệt sức mà bạn đã phớt lờ quá lâu."],
 ["Một người còng lưng lê bước dưới bó mười cây gậy.","Bạn đang quá tải. Bạn đã ôm hết mọi việc vào người, và với cách ôm này, gánh nặng đúng là quá sức thật.","Bạn đặt bớt xuống một thứ. Cuối cùng bạn cũng giao việc cho người khác, hoặc từ chối việc tiếp theo."]],
 court:[
 ["Một thiếu niên đội mũ cắm lông đứng giữa sa mạc, chăm chú nhìn cây gậy trong tay.","Lá bài này báo một niềm hào hứng mới, hoặc một tin tức mở màn cho điều gì đó. Bạn được phép làm kẻ mới bắt đầu.","Bạn đang bồn chồn, nói lớn, và thật ra chưa bắt đầu gì cả."],
 ["Một hiệp sĩ đội mũ cắm chùm lông phi tới trên con ngựa chồm lên, gậy giơ cao.","Lá bài này nói về hành động táo bạo và phiêu lưu. Bạn cố tình lên đường khi kế hoạch còn chưa đầy đủ.","Lá ngược cho thấy sự hấp tấp và cháy sạch: bạn bắt đầu một thứ mà bạn vốn không định làm cho xong."],
 ["Một người phụ nữ đội vương miện cầm đóa hướng dương, con mèo đen ngồi dưới chân, mắt nhìn thẳng ra phía trước.","Nữ Hoàng Gậy ấm áp, tự tin và có sức hút. Bà biết rõ mình muốn gì và khiến người khác cũng muốn điều đó.","Sự mãnh liệt đã hóa thành đòi hỏi, hoặc lòng tự tin đã trở nên dễ vỡ."],
 ["Một vị vua có râu ngồi trên ngai chạm hình kỳ giông, tay cầm cây gậy đang trổ hoa.","Đức Vua Gậy có tầm nhìn cộng với đủ uy quyền để khiến người khác tin vào nó. Ông là một thủ lĩnh bẩm sinh, nhưng thiếu kiên nhẫn với tiểu tiết.","Lá ngược cho thấy sự bốc đồng ở quy mô lớn, sự độc đoán, hoặc những lời hứa chạy nhanh hơn khả năng thực hiện."]]},
cups:{ pips:[
 ["Một bàn tay dâng chiếc ly tràn đầy, chim bồ câu sà xuống trong lòng ly, năm dòng nước trào ra ngoài.","Lá bài này nói về một sự mở lòng: tình cảm được trao đi, một mối gắn kết bắt đầu, một cảm xúc chưa bị làm hỏng.","Bạn đang khép chặt lòng, hoặc một cảm xúc đang bị dằn xuống dứt khoát."],
 ["Một người nam và một người nữ nâng cốc thề nguyện với nhau dưới cây trượng có cánh.","Lá bài này nói về sự thừa nhận lẫn nhau giữa hai người. Đó là sự đồng hành, sự làm lành, hoặc một thỏa ước mà cả hai bên đều thật lòng.","Lá ngược cho thấy sự mất cân bằng, một vết rạn, hoặc một người đang gánh cả mối quan hệ."],
 ["Ba người phụ nữ nâng cốc thành vòng tròn, nhảy múa giữa mùa gặt.","Lá bài này nói về tình bạn và sự ăn mừng. Đó là niềm vui thật sự khi có người bên cạnh, thay vì vui một mình.","Lá ngược cho thấy chuyện ngồi lê đôi mách, sự quá đà, hoặc một nhóm bạn đã trở nên gượng gạo."],
 ["Một người ngồi khoanh tay dưới gốc cây, làm ngơ chiếc cốc được đưa ra từ đám mây.","Bạn đang bất mãn và chán chường. Có thứ đang được trao mà bạn không sao khiến mình muốn nó.","Bạn chợt nhận ra thứ đang được trao. Sự thờ ơ bắt đầu tan."],
 ["Một người khoác áo choàng đau buồn trước ba chiếc cốc đã đổ. Hai chiếc còn đứng vững phía sau, không ai để ý tới.","Lá bài này nói về mất mát, và về cách nỗi đau khiến bạn chỉ nhìn vào thứ đã mất. Hai chiếc cốc còn đứng chính là toàn bộ thông điệp.","Bạn quay đầu lại. Sự chấp nhận bắt đầu, và bàn tay giúp đỡ được đón nhận."],
 ["Một đứa trẻ trao cho đứa khác chiếc cốc đầy hoa trong khu vườn có tường bao.","Lá bài này nói về hoài niệm và sự ngây thơ. Lòng tốt từ quá khứ quay trở lại, hoặc một người từ quá khứ trở về.","Bạn đang mắc kẹt trong ký ức cũ, hoặc cuối cùng cũng đặt được nó xuống."],
 ["Bảy chiếc cốc lơ lửng trong mây, đựng một tòa lâu đài, châu báu, vòng nguyệt quế, một con rắn và một bóng người trùm vải.","Bạn có quá nhiều lựa chọn, và phần lớn trong đó là mộng tưởng. Bạn hãy chọn lấy một và biến nó thành thật, nếu không sẽ không có lựa chọn nào thành thật cả.","Lá ngược cho thấy sự sáng rõ đang tới, hoặc mộng tưởng đang bị lộ nguyên hình."],
 ["Một người quay lưng khỏi tám chiếc cốc xếp chồng, đi về phía núi, dưới vầng trăng khuyết bóng.","Bạn rời bỏ một thứ vốn cũng ổn nhưng chưa đủ. Đây là một cuộc ra đi có chủ ý, và bạn phải trả giá bằng chính mình.","Lá ngược cho thấy bạn quay trở lại, hoặc không sao khiến mình rời đi được."],
 ["Một người đàn ông mãn nguyện ngồi trước dãy chín chiếc cốc xếp vòng cung, khoanh tay, hài lòng với chính mình.","Lá bài này nói về sự thỏa lòng. Một điều ước thành hiện thực, và bạn hưởng niềm vui mà mình xứng đáng có. Theo truyền thống, đây là lá bài của điều ước.","Lá ngược cho thấy bạn đang tự mãn, hoặc đạt được điều ước rồi mới thấy nó không làm mình thỏa mãn."],
 ["Một đôi vợ chồng giang tay hướng về cầu vồng mười chiếc cốc, trong khi hai đứa trẻ nhảy múa bên cạnh.","Lá bài này nói về sự viên mãn trong toàn cảnh: gia đình, cảm giác thuộc về, và hạnh phúc trụ được với thời gian.","Lá ngược cho thấy một bề mặt hoàn hảo với một khoảng trống có thật bên dưới."]],
 court:[
 ["Một thiếu niên áo lam thản nhiên nhìn con cá vừa hiện ra trong chiếc cốc của mình.","Lá bài này báo một rung động mới mềm mại, một lời mời, hoặc một ý tưởng từ trí tưởng tượng đáng để bạn đi theo.","Lá ngược cho thấy sự thất thường, hoặc những cảm xúc đáng lẽ phải nói ra lại bị giữ lại."],
 ["Một hiệp sĩ cưỡi ngựa đi chậm, chìa chiếc cốc về phía trước như một lời dâng tặng.","Lá bài này nói về sự lãng mạn và một cách tiếp cận đầy nhã nhặn. Bạn đi theo trái tim ở nhịp thong thả.","Lá ngược cho thấy một lời đề nghị không có gì đằng sau, hoặc một lý tưởng không bao giờ chạm đất."],
 ["Một nữ hoàng đăm đăm nhìn vào chiếc cốc có nắp chạm trổ bên mép nước, hoàn toàn đắm chìm.","Nữ Hoàng Cốc có sự thấu cảm sâu và trí tuệ cảm xúc. Bà có thể ôm lấy cảm xúc của người khác mà không chìm trong đó.","Lá ngược cho thấy bạn đang quá tải, đang hút hết tâm trạng của mọi người vào mình, hoặc sự quan tâm đã hóa thành kiểm soát."],
 ["Một vị vua cầm cốc và quyền trượng, ngồi trên ngai trôi giữa biển động, áo bào vẫn khô.","Cảm xúc được cảm nhận trọn vẹn nhưng không nắm quyền điều khiển. Đức Vua Cốc giữ được sự vững vàng giữa giông bão của người khác.","Lá ngược cho thấy sự đè nén, thao túng, hoặc sự bình tĩnh chỉ có ở bề ngoài."]]},
swords:{ pips:[
 ["Một bàn tay nắm chặt thanh kiếm dựng thẳng, đỉnh kiếm đội vòng nguyệt quế và lá cọ, sáu giọt rơi xuống.","Đây là một ý nghĩ sắc và rõ. Sự thật chém xuyên qua mọi thứ, hoặc một quyết định đã được đưa ra và không xét lại.","Mọi thứ rối loạn, hoặc sự sáng rõ bị dùng làm vũ khí."],
 ["Một người phụ nữ bịt mắt cầm hai thanh kiếm bắt chéo, ngồi bên mặt nước dưới ánh trăng.","Đây là một thế bế tắc được giữ có chủ ý. Bạn không chịu nhìn thẳng vào một lựa chọn mà bạn vốn đã biết.","Dải băng bịt mắt được gỡ ra, và thế bế tắc vỡ, theo hướng này hay hướng kia."],
 ["Ba thanh kiếm xuyên qua một trái tim đỏ trên nền mưa xám.","Đây là nỗi đau lòng trần trụi, và thường là chính những lời nói đã gây ra nó. Lá bài này không làm dịu đi điều gì cả.","Cơn đau dịu bớt. Bạn đang chủ động xử lý nỗi buồn thay vì chỉ ngồi lì trong đó."],
 ["Một hiệp sĩ nằm như pho tượng trên mộ đá, ba thanh kiếm treo phía trên và một thanh nằm bên dưới.","Đây là sự nghỉ ngơi bắt buộc. Bạn hồi phục, lui về, và có một khoảng dừng trước hiệp sau. Đây không phải là thất bại.","Bạn đang bồn chồn, kiệt sức, hoặc quay lại cuộc chơi quá sớm."],
 ["Một gã cười khẩy gom kiếm về mình trong khi hai người khác quay lưng bỏ đi.","Bạn thắng với giá phải trả không đáng. Đây là một cuộc xung đột mà không bên nào bước ra sạch sẽ.","Bạn làm lành, hoặc chấp nhận thua và bước tiếp."],
 ["Người lái đò chống sào đưa con thuyền chở một hành khách trùm đầu và sáu thanh kiếm về phía bờ nước lặng hơn.","Đây là một chuyến vượt khó để rời khỏi rắc rối. Từ đây mọi thứ sẽ yên hơn, nhưng bạn đã phải rời đi mới có được điều đó.","Hành lý được mang theo cùng. Cuộc dời đi này không giải quyết được gì, vì vấn đề cũng đi theo."],
 ["Một người lén rời khỏi khu trại, ôm theo năm thanh kiếm, để lại hai thanh cắm dưới đất.","Lá bài này nói về mưu mẹo và né tránh. Bạn thoát được một vố, nhưng còn hai thanh kiếm bạn không mang nổi.","Bạn bị phát hiện, hoặc quyết định nói thật."],
 ["Một người phụ nữ bị trói và bịt mắt đứng giữa tám thanh kiếm cắm xuống bùn.","Bạn cảm thấy bị mắc kẹt trong một tình huống thật ra lỏng lẻo hơn bạn tưởng rất nhiều. Những thanh kiếm đó không phải là một chiếc lồng.","Bạn nhìn ra lối thoát. Dây trói lỏng dần."],
 ["Một người ngồi bật dậy trên giường, hai tay ôm mặt; chín thanh kiếm treo trên bức tường phía sau.","Đây là nỗi lo lúc ba giờ sáng. Cảm giác sợ hãi là thật, nhưng mức độ của nó không thật đến vậy.","Đoạn tệ nhất đang qua đi, hoặc cuối cùng bạn cũng nói ra với một ai đó."],
 ["Một người nằm úp mặt với mười thanh kiếm cắm sau lưng, trong lúc bình minh rạng lên trên mặt nước.","Bạn chạm đáy, và chạm một cách rất kịch. Mọi việc thật sự không thể tệ hơn được nữa, trong khi mặt trời đã bắt đầu lên.","Bạn hồi phục. Bạn sống sót, và từ chối để mình bị kết liễu."]],
 court:[
 ["Một thiếu niên vung kiếm trên gò cao lộng gió, ngoái nhìn qua vai.","Lá bài này nói về sự tò mò và những câu hỏi sắc bén. Bạn thu thập thông tin, đôi khi trước cả khi biết để làm gì.","Lá ngược cho thấy sự rình mò, sự hoài nghi cay nghiệt, hoặc lời nói được dùng để cứa vào người khác."],
 ["Một hiệp sĩ lao thẳng vào cơn gió lớn, kiếm giơ cao, ngựa phi hết sức.","Kỵ Sĩ Kiếm nhanh, thẳng và hay tranh luận. Anh lao thẳng vào trọng tâm và không giảm tốc vì cảm xúc của ai.","Bạn hung hăng, vụng về, hoặc xông lên nhầm hẳn ngọn đồi."],
 ["Một nữ hoàng nghiêm nghị ngồi trên tầng mây, kiếm dựng thẳng, một tay chìa ra.","Nữ Hoàng Kiếm có sự sáng rõ không ướt át. Bà nói thẳng một cách tử tế nhưng không hề làm nhẹ đi. Bà là người đã đi qua chuyện gì đó.","Lá ngược cho thấy sự lạnh lùng, sự cay đắng, hoặc thói phê phán đã trở thành tính cách."],
 ["Một vị vua cầm kiếm hơi nghiêng, trên ngai chạm hình những con bướm.","Đức Vua Kiếm có óc phán đoán và uy quyền trí tuệ. Ông luôn chọn nguyên tắc thay vì sở thích.","Lá ngược cho thấy sự cai trị lạnh lùng, việc coi tranh luận như môn thể thao, hoặc việc dùng quyền lực để thắng chứ không phải để phân định."]]},
pentacles:{ pips:[
 ["Một bàn tay dâng đồng tiền vàng phía trên khu vườn có tường bao, cổng vườn mở ra hướng núi.","Lá bài này báo một cơ hội sờ được: một lời mời, một công việc, hoặc một hạt mầm thịnh vượng có thật.","Lá ngược cho thấy một cơ hội bị bỏ lỡ, hoặc một kế hoạch không có nền móng bên dưới."],
 ["Một chàng trai vừa nhảy vừa tung hứng hai đồng tiền trong vòng dây hình vô cực, trong khi những con tàu cưỡi trên sóng lớn.","Bạn cân đối các đầu việc và giữ cho mọi thứ tiếp tục chạy. Bạn linh hoạt, nhưng chỉ vừa đủ.","Bạn đánh rơi một thứ. Bạn ôm đồm quá nhiều và sắp phải trả giá."],
 ["Một người thợ điêu khắc đứng trên bệ trong nhà thờ lớn, bàn bạc với hai người đang cầm bản vẽ.","Lá bài này nói về sự hợp tác giữa những người có nghề. Công việc được ghi nhận và được phát triển tiếp bởi những người biết rõ mình đang nhìn gì.","Lá ngược cho thấy công sức bỏ ra không đồng đều, hoặc một nhóm đang kéo về những hướng khác nhau."],
 ["Một người đội vương miện ôm chặt một đồng tiền vào ngực, đứng lên hai đồng khác, và đội thăng bằng một đồng trên đầu.","Bạn giữ thật chặt. Bạn có sự an toàn, sự tích cóp và sự kiểm soát, nhưng phải trả giá bằng việc không còn cựa quậy được.","Bạn nới lỏng bàn tay, hoặc mất thứ mình đang giữ dù bạn có muốn hay không."],
 ["Hai người hành khất đi qua ô cửa kính màu đang sáng đèn giữa trời tuyết, một người chống nạng.","Lá bài này nói về sự túng quẫn, và về cảm giác rất riêng của người đứng ngoài trong khi người khác đang ấm. Sự giúp đỡ ở gần hơn vẻ ngoài của nó.","Sự hồi phục bắt đầu, hoặc cuối cùng bạn cũng chịu mở lời nhờ giúp."],
 ["Một thương nhân một tay giữ cán cân thăng bằng, tay kia thả những đồng xu xuống cho hai người đang quỳ.","Lá bài này nói về cho và nhận. Lòng hào phóng là thật, và sự chênh lệch quyền lực bên trong nó cũng thật.","Lá ngược cho thấy sự cho đi kèm điều kiện, nợ nần, hoặc sự cho đi chỉ chạy theo một chiều."],
 ["Một người đàn ông tựa vào cán cuốc, ngắm giàn cây trĩu những đồng tiền mà anh chưa hái.","Bạn dừng lại để đánh giá một khoản đầu tư dài hơi. Lá bài này nói về sự kiên nhẫn, và về câu hỏi thành thật rằng có nên tiếp tục hay không.","Bạn đang nóng ruột, hoặc công sức lâu nay đã đổ vào nhầm thửa ruộng."],
 ["Một người thợ ngồi ở bàn, đục từng đồng tiền một, bảy đồng đã xong, một đồng còn trên tay.","Sự lặp lại đang biến thành tay nghề. Đây là đoạn giữa không hề hào nhoáng của quá trình giỏi lên thật sự.","Bạn đang làm ẩu, hoặc một công việc đã bị rút cạn hết ý nghĩa."],
 ["Một người phụ nữ đứng trong khu vườn có tường bao đầy giàn nho chín, tay đặt lên con chim ưng đang bịt mũ.","Đây là sự sung túc do chính bạn tạo ra. Lá bài này nói về sự độc lập, và về niềm vui được hưởng nó theo cách của riêng mình.","Lá ngược cho thấy sự lệ thuộc, hoặc của cải đến mà không kèm theo chút tự do nào."],
 ["Ba thế hệ và hai con chó đứng dưới vòm cổng; mười đồng tiền phủ kín bức tranh.","Lá bài này nói về của cải bền vững: di sản, gia đình, và những cấu trúc sống lâu hơn cả người đã dựng nên chúng.","Lá ngược cho thấy mâu thuẫn gia đình vì tiền bạc, hoặc bạn chỉ nghĩ xa được đến hết tháng này."]],
 court:[
 ["Một thiếu niên đứng giữa cánh đồng xanh, nâng niu đồng tiền bằng cả hai tay và chăm chú ngắm nó.","Tiểu Đồng Tiền là một người học trò. Lá bài này báo một hướng đi mới và thiết thực, được coi trọng đủ để bạn học cho tới nơi tới chốn.","Lá ngược cho thấy sự trì hoãn, hoặc kiến thức học xong không bao giờ được đem ra dùng vào việc gì."],
 ["Một hiệp sĩ mặc giáp ngồi bất động trên con ngựa ô nặng nề, chìa đồng tiền ra phía trước.","Kỵ Sĩ Tiền bài bản và đáng tin. Anh chậm và không có gì hào hứng, nhưng rồi việc sẽ xong. Đây là vị hiệp sĩ duy nhất không di chuyển.","Lá ngược cho thấy sự trì trệ, sự cố chấp, hoặc một công việc đã trở nên buồn tẻ."],
 ["Một nữ hoàng ngồi trên ngai chạm hình hoa trái và dê, nâng đồng tiền trong lòng, con thỏ nhỏ dưới chân.","Nữ Hoàng Tiền mang sự chăm sóc thiết thực. Bà tháo vát và vững chân trên mặt đất, và khiến những người quanh mình được an toàn về vật chất.","Bạn đang làm quá sức, chăm sóc đến mức ngột ngạt, hoặc lo cho tất cả mọi người trừ chính mình."],
 ["Một vị vua khoác áo bào thêu dây nho đặt một tay lên đồng tiền, tòa lâu đài phía sau lưng.","Đức Vua Tiền làm chủ thế giới vật chất. Ông mang đến của cải, sự ổn định, và một chỗ dựa thật sự đáng tin.","Lá ngược cho thấy sự tham lam, việc kiểm soát người khác bằng tiền, hoặc chủ nghĩa vật chất cố chấp."]]}
};

/* English keeps the original wording, untouched. */

const DECKTEXT = { en: { majors: MAJORS, minors: MINORS }, vi: { majors: MAJORS_VI, minors: MINORS_VI } };
