/* Vietnamese card names and text (The Learner's Deck). */
const LANGS = ['en', 'vi'];

const LEX = {
  en: {
    numbers: ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'],
    courts: ['Page', 'Knight', 'Queen', 'King'],
    suitNames: { major: 'Major Arcana', wands: 'Wands', cups: 'Cups', swords: 'Swords', pentacles: 'Pentacles' },
    elements: { wands: 'Fire', cups: 'Water', swords: 'Air', pentacles: 'Earth' },
    courtTag: 'Court',
    pipName: (n, s) => `${n} of ${s}`,
    courtName: (c, s) => `${c} of ${s}`
  },
  vi: {
    numbers: ['Át', 'Hai', 'Ba', 'Bốn', 'Năm', 'Sáu', 'Bảy', 'Tám', 'Chín', 'Mười'],
    courts: ['Tiểu Đồng', 'Kỵ Sĩ', 'Nữ Hoàng', 'Đức Vua'],
    suitNames: { major: 'Ẩn Chính', wands: 'Gậy', cups: 'Cốc', swords: 'Kiếm', pentacles: 'Tiền' },
    elements: { wands: 'Lửa', cups: 'Nước', swords: 'Khí', pentacles: 'Đất' },
    courtTag: 'Hoàng gia',
    pipName: (n, s) => `${n} ${s}`,
    courtName: (c, s) => `${c} ${s}`
  }
};

const MAJORS_VI = [
["Gã Khờ","khởi đầu · niềm tin · ngây thơ · bước nhảy",
 "Một chàng trai mặc áo hoa văn bước về phía mép vực, mặt ngước lên vầng mặt trời trắng. Một tay cầm đóa hồng trắng, vai vác chiếc túi buộc đầu gậy, và một chú chó trắng nhỏ chồm lên bên gót chân.",
 "Khởi đầu của một điều gì đó khi bạn chưa có bằng chứng nào rằng nó sẽ thành. Niềm tin đi trước chứng cứ, và thứ tự do rất riêng của người chưa có gì để mất.",
 "Liều lĩnh — hoặc đúng điều ngược lại: không chịu nhúc nhích chỉ vì nhìn xuống thấy vực quá sâu."],
["Nhà Ảo Thuật","ý chí · tập trung · nguồn lực · hiện thực hóa",
 "Một tay giơ lên trời, một tay chỉ xuống đất, dấu vô cực lơ lửng trên đầu. Trên bàn trước mặt là một cây gậy, một chiếc cốc, một thanh kiếm và một đồng tiền — đủ cả bốn chất.",
 "Bạn đã có sẵn mọi công cụ mà tình huống này đòi hỏi. Việc cần làm không phải là kiếm thêm, mà là chĩa tất cả những gì đang có vào đúng một việc.",
 "Tài năng vung vãi vào quá nhiều thứ, hoặc tài thuyết phục bị dùng để thao túng."],
["Nữ Tư Tế","trực giác · điều chưa lộ · cái biết bên trong",
 "Bà ngồi giữa một cột đen và một cột trắng, vầng trăng lưỡi liềm dưới chân, tấm màn thêu quả lựu buông sau lưng, và cuộn thư trong lòng chỉ lộ ra một nửa.",
 "Câu trả lời đã có nhưng chưa nổi lên. Hãy chờ, lắng nghe bên trong, và đừng ép điều gì phải lộ ra — dù là từ chính bạn hay từ người khác.",
 "Gạt bỏ linh cảm của chính mình, hoặc một bí mật được giữ quá lâu so với lúc nó còn có ích cho ai đó."],
["Hoàng Hậu","sung túc · nuôi dưỡng · sáng tạo · giác quan",
 "Một người phụ nữ đội vương miện giữa cánh đồng lúa mì đang chín, vòng mười hai ngôi sao trên đầu, bên cạnh là tấm khiên hình trái tim mang ký hiệu sao Kim.",
 "Có điều gì đó đang lớn lên và chủ yếu cần được nuôi chứ không cần sửa. Sự phì nhiêu theo mọi nghĩa — sáng tạo, thể chất, đủ đầy vật chất, và niềm vui hưởng thụ mà không thấy áy náy.",
 "Yêu thương đến ngột ngạt, bí tắc sáng tạo, hoặc dồn hết chăm sóc cho mọi thứ trừ chính mình."],
["Hoàng Đế","cấu trúc · quyền lực · ranh giới",
 "Một vị vua có râu ngồi trên ngai đá chạm đầu cừu đực, tay cầm quyền trượng hình chữ ankh, sau lưng là dãy núi trơ trọi.",
 "Trật tự được áp lên hỗn loạn: luật lệ, kỷ luật, sự che chở. Lá bài của người ra quyết định, và của cái ranh giới khiến mọi thứ còn lại trở nên khả thi.",
 "Cứng nhắc và áp chế — hoặc hoàn toàn không có cấu trúc nào, khiến mọi thứ chông chênh."],
["Giáo Hoàng","truyền thống · giảng dạy · thiết chế",
 "Một vị mặc lễ phục đội vương miện ba tầng giơ tay ban phước cho hai tu sĩ cạo đỉnh đầu. Dưới chân ông là hai chiếc chìa khóa bắt chéo.",
 "Con đường đã được thiết lập, và một người đủ tư cách truyền dạy nó. Học trong một dòng truyền thừa, và giá trị của việc làm đúng như xưa nay vẫn làm.",
 "Giáo điều đã hết thời, hoặc một lời gọi thật sự để phá bỏ lề thói."],
["Tình Nhân","kết hợp · lựa chọn · giá trị",
 "Một người nam và một người nữ đứng trần dưới thiên thần có cánh giữa nắng chói. Sau lưng nàng là con rắn quấn thân cây; sau lưng chàng là cái cây bốc lửa.",
 "Một cuộc gặp thật sự giữa hai bên, và một lựa chọn phơi bày điều bạn thật sự coi trọng, chứ không phải điều bạn nói là mình coi trọng.",
 "Lệch pha, một quyết định bị né tránh, hoặc một mối quan hệ mà sức nặng dồn hết về một phía."],
["Cỗ Chiến Xa","động lực · kiểm soát · chiến thắng",
 "Một người mặc giáp đứng trên cỗ xe dưới mái vòm điểm sao, do một nhân sư đen và một nhân sư trắng kéo. Trong tranh không hề có dây cương.",
 "Sự tiến tới có được nhờ giữ hai lực đối nghịch trên cùng một hướng. Ý chí thắng hoàn cảnh, ít nhất là lúc này.",
 "Bị kéo về hai phía cùng lúc, hoặc lao đi mà không ai cầm lái."],
["Sức Mạnh","can đảm · kiên nhẫn · sức mạnh mềm",
 "Một người phụ nữ áo trắng thong thả khép hàm sư tử bằng tay không, dấu vô cực trên đầu. Nàng không hề gắng sức.",
 "Gây ảnh hưởng bằng sự dịu dàng và bền bỉ thay vì bằng vũ lực. Và bản nhẹ nhàng hơn của điều đó: làm chủ ham muốn của chính mình thay vì của người khác.",
 "Hoài nghi bản thân, hoặc dùng sức ép ở chỗ lẽ ra chỉ cần kiên nhẫn."],
["Ẩn Sĩ","tịch liêu · tìm kiếm · ánh sáng bên trong",
 "Một ông lão khoác áo choàng trên đỉnh núi tuyết giơ cao chiếc đèn lồng có ngôi sao sáu cánh cháy bên trong, chống mình trên cây gậy dài.",
 "Chủ động rút lui để tự tìm câu trả lời của mình. Một quãng để học, để yên tĩnh, và cố ý không hỏi ý đám đông.",
 "Sự cô lập đã hóa thành né tránh, hoặc chối bỏ một bàn tay thật lòng chìa ra."],
["Bánh Xe Số Phận","chu kỳ · bước ngoặt · vận may",
 "Một bánh xe lớn khắc chữ T-A-R-O quay giữa trời. Nhân sư ngự phía trên, con rắn trườn xuống một bên, con chó rừng leo lên bên kia, và bốn sinh vật có cánh đang đọc sách ở bốn góc.",
 "Hoàn cảnh đổi thay theo nhịp riêng của nó. Hãy đi theo vòng quay, thay vì bám chặt một nan hoa và đòi nó phải ở mãi trên đỉnh.",
 "Một nhịp đi xuống, sự chống cự trước thay đổi vốn đã bắt đầu, hoặc đơn giản là sai thời điểm."],
["Công Lý","công bằng · nhân quả · sự thật",
 "Một nhân vật đội vương miện ngồi giữa hai cây cột, một tay cầm thanh kiếm dựng thẳng, tay kia giữ cán cân thăng bằng tuyệt đối.",
 "Mọi thứ được cân đo chính xác và hậu quả đang tới. Một quyết định buộc phải trung thực chứ không phải tử tế.",
 "Thiên vị, một sổ sách lệch, hoặc trách nhiệm bị né thành công — ít nhất là lúc này."],
["Người Treo Ngược","treo lơ lửng · đảo chiều · buông",
 "Một người đàn ông bình thản treo mình bằng một mắt cá chân trên thân cây sống hình chữ T, chân còn lại bắt chéo ra sau, quầng sáng bao quanh đầu.",
 "Một khoảng dừng có chủ ý. Câu trả lời đến từ việc lộn ngược góc nhìn, chứ không phải từ việc đẩy mạnh hơn theo hướng bạn vốn đang đi.",
 "Sự trì hoãn khoác áo chiêm nghiệm, hoặc một hy sinh mà chẳng nhận lại được gì."],
["Cái Chết","kết thúc · chuyển tiếp · dọn sạch",
 "Một bộ xương mặc giáp đen cưỡi ngựa trắng đi ngang vị vua đã ngã. Lá cờ của nó mang đóa hồng trắng, và mặt trời mọc lên giữa hai tòa tháp nơi chân trời.",
 "Một điều gì đó chấm dứt hẳn để điều tiếp theo có chỗ tồn tại. Gần như không bao giờ hiểu theo nghĩa đen, và gần như không thương lượng được.",
 "Bám lấy điều đã xong, hoặc một kết thúc bị kéo dài lâu hơn mức cần thiết rất nhiều."],
["Điều Độ","cân bằng · pha trộn · chừng mực",
 "Một thiên thần có cánh, một chân trên bờ một chân dưới nước, rót chất lỏng qua lại giữa hai chiếc cốc theo một đường vòng lẽ ra không thể có.",
 "Kiên nhẫn chỉnh đi chỉnh lại cho đến khi tỷ lệ vừa đúng. Sự chữa lành và hồi phục cần bao nhiêu thời gian thì sẽ lấy bấy nhiêu.",
 "Thái quá, nóng vội, hoặc hai thành phần đơn giản là không thể hòa vào nhau."],
["Ác Quỷ","trói buộc · thôi thúc · bóng tối",
 "Một sinh vật có sừng ngồi xổm trên bệ đá, ngôi sao năm cánh lộn ngược giữa trán. Bên dưới, một người nam và một người nữ bị xích — và sợi xích lỏng đến mức có thể nhấc thẳng ra khỏi cổ.",
 "Một sự dính mắc đang điều khiển bạn: một thói quen, một cơn thèm, một mối quan hệ mà bạn tự nhủ mình không thể rời. Chi tiết sợi xích lỏng lẻo chính là toàn bộ thông điệp.",
 "Nhìn ra sợi xích đúng như nó vốn là, và có động thái đầu tiên để gỡ nó ra."],
["Tòa Tháp","sụp đổ đột ngột · vỡ lẽ",
 "Tia sét đánh bay chiếc vương miện khỏi đỉnh tháp cao. Lửa phụt ra từ các ô cửa và hai người lao đầu rơi xuống bóng tối.",
 "Một công trình dựng trên nền giả dối đổ xuống rất nhanh. Đau đớn, làm sáng tỏ, và một khi đã bắt đầu thì không có lựa chọn nào khác.",
 "Một tai họa tránh được trong gang tấc, hoặc một sự sụp đổ mà bạn đang kéo dài đến kiệt sức."],
["Ngôi Sao","hy vọng · hồi sinh · dẫn đường",
 "Một người phụ nữ trần quỳ bên hồ nước, một bình rót nước xuống đất, bình kia rót ngược trở lại hồ. Trên đầu là một ngôi sao lớn và bảy ngôi sao nhỏ đang cháy sáng.",
 "Sự bình yên sau đổ nát. Niềm tin được phục hồi, và cảm giác rõ ràng về hướng đi thuộc về mình — thường đến ngay sau lá Tòa Tháp.",
 "Nản lòng, niềm tin mòn dần, để tuột mất sợi chỉ mình đang lần theo."],
["Mặt Trăng","bất định · giấc mơ · méo mó",
 "Vầng trăng có gương mặt nhỏ những giọt sương xuống con đường chạy giữa hai tòa tháp. Một con chó và một con sói tru lên, và một con tôm càng bò lên từ mặt hồ.",
 "Địa hình không rõ ràng và cách bạn đọc nó có thể sai. Nỗi sợ, trí tưởng tượng và bản năng cùng lên tiếng một lúc, trong bóng tối.",
 "Sương mù tan dần, hoặc một sự dối trá cuối cùng cũng lộ ra ánh sáng."],
["Mặt Trời","sáng rõ · sức sống · thành công",
 "Một đứa trẻ cưỡi ngựa trắng dưới vầng mặt trời rực rỡ khổng lồ, lá cờ đỏ bay phấp phới phía sau, và một bức tường hoa hướng dương làm nền.",
 "Mọi thứ đơn giản là tốt đẹp, và ai cũng thấy được. Năng lượng, hơi ấm, niềm vui thật thà — lá bài ít rắc rối nhất trong cả bộ.",
 "Nhiệt huyết mờ đi, thành công bị trì hoãn, hoặc sự lạc quan được diễn ra chứ không được cảm thấy."],
["Phán Xét","tính sổ · thức tỉnh · tiếng gọi",
 "Một thiên thần thổi kèn giữa tầng mây và những bóng người xám đứng dậy từ các cỗ quan tài mở nắp, hai tay giang rộng.",
 "Một cuộc tổng kết. Bạn nhìn thấy trọn vẹn cả cung đường của một điều gì đó cùng lúc, và đáp lại tiếng gọi mà bạn không thể vờ như chưa từng nghe.",
 "Tự trách mình quá nặng, hoặc nghe rõ tiếng gọi mà vẫn làm ngơ."],
["Thế Giới","hoàn tất · trọn vẹn · hợp nhất",
 "Một vũ công quấn dải lụa tím đứng giữa vòng nguyệt quế. Con bò, con sư tử, con đại bàng và một thiên thần chiếm bốn góc tranh.",
 "Chu kỳ khép lại đúng cách. Sự đến nơi, và năng lực chỉ có được khi đã đi trọn cả vòng.",
 "Suýt nữa là xong — một đầu mối còn bỏ ngỏ, hoặc một sự khép lại mà ai đó đang giữ lại không trao."]
];

const MINORS_VI = {
wands:{ pips:[
 ["Một bàn tay vươn ra từ đám mây, trao một cành cây đang nảy lộc, lá vẫn còn rơi lả tả.","Một tia lửa: đợt dâng đầu tiên của ham muốn làm ra điều gì đó. Năng lượng thô, chưa nhắm vào đâu cả.","Một khởi đầu hụt, hoặc năng lượng không biết đổ vào đâu."],
 ["Một người đàn ông đứng trên tường thành của chính mình, tay cầm quả địa cầu, nhìn ra xa khỏi bức tường do mình dựng lên.","Hoạch định vượt ra ngoài những gì đang nắm trong tay. Chọn chân trời rộng hơn thay vì chân trời dễ chịu hơn.","Chơi an toàn, hoặc những kế hoạch không bao giờ rời khỏi mặt bàn."],
 ["Một người đứng trên vách đá nhìn những con thuyền dong buồm ra khơi.","Những nỗ lực đầu tiên đã lên đường và không còn trong tay bạn nữa. Sự mở rộng, và quãng chờ đợi sau khi đã phóng một thứ gì đó đi.","Trì hoãn, chờ đợi trong bồn chồn, hoặc một kế hoạch đặt ra quá nhỏ."],
 ["Bốn cây cột kết hoa tạo thành cổng chào trước tòa lâu đài; bên dưới, những người dự hội giơ cao những bó hoa.","Một ngưỡng cửa đáng dừng lại để đánh dấu — sự trở về, sự ổn định, một cột mốc đạt được cùng với người khác.","Vẫn điều đó nhưng lặng lẽ hơn: một cuộc ăn mừng bị hoãn lại hoặc chỉ giữ riêng cho mình."],
 ["Năm chàng trai vung gậy trong một trận ẩu đả giả, lộn xộn và chẳng ra hàng lối.","Va chạm và cạnh tranh. Ai cũng nói chồng lên lời người khác; rốt cuộc chẳng ai được nghe.","Xung đột được né đi, hoặc một cuộc tranh cãi dai dẳng cuối cùng cũng lắng xuống."],
 ["Một kỵ sĩ đội vòng nguyệt quế đi giữa đám đông reo hò, trên cây gậy cũng có một vòng nguyệt quế.","Sự công nhận công khai. Chiến thắng mà người khác nhìn thấy và thừa nhận.","Sự công nhận bị giữ lại, hoặc một thành công nghe rỗng tuếch ngay khi đã cầm được nó."],
 ["Một người đứng trên gò cao chống đỡ sáu cây gậy chĩa lên từ phía dưới.","Giữ vững vị trí dưới áp lực. Hãy bảo vệ thứ bạn dựng nên — bạn đang ở thế cao hơn.","Bị áp đảo, hoặc nhường lại phần đất lẽ ra phải giữ."],
 ["Tám cây gậy bay giữa trời quang trên một dòng sông. Không có bóng người nào.","Tốc độ đến đột ngột. Tin tức, những chuyến đi, và mọi thứ ập tới cùng lúc sau một quãng dài đứng yên.","Ách tắc, hoặc năng lượng tản ra tám hướng."],
 ["Một người đàn ông quấn băng tựa vào cây gậy, mắt canh hàng rào, chuẩn bị sẵn cho đợt tiếp theo.","Rã rời nhưng vẫn đứng vững. Còn một đợt nữa thôi, và sự đề phòng ấy là do trả giá mà có.","Đa nghi thái quá, hoặc một sự kiệt sức mà bạn đã phớt lờ quá lâu."],
 ["Một người còng lưng lê bước dưới bó mười cây gậy.","Quá tải. Bạn đã ôm hết vào người, và ôm kiểu này thì đúng là quá sức thật.","Đặt bớt xuống một thứ. Cuối cùng cũng giao việc cho người khác, hoặc từ chối việc tiếp theo."]],
 court:[
 ["Một thiếu niên đội mũ cắm lông đứng giữa sa mạc, chăm chú nhìn cây gậy trong tay.","Một niềm hào hứng mới, hoặc một tin tức mở màn cho điều gì đó. Sự cho phép được làm kẻ mới bắt đầu.","Bồn chồn, nói lớn, và thật ra chưa bắt đầu gì cả."],
 ["Một hiệp sĩ đội mũ cắm chùm lông phi tới trên con ngựa chồm lên, gậy giơ cao.","Hành động táo bạo và phiêu lưu. Cố tình lên đường khi kế hoạch còn chưa đầy đủ.","Hấp tấp và cháy sạch — bắt đầu thứ mà bạn vốn không định làm cho xong."],
 ["Một người phụ nữ đội vương miện cầm đóa hướng dương, con mèo đen ngồi dưới chân, mắt nhìn thẳng ra phía trước.","Ấm áp, tự tin, có sức hút. Biết rõ mình muốn gì và khiến người khác cũng muốn điều đó.","Sự mãnh liệt đã hóa thành đòi hỏi, hoặc lòng tự tin đã trở nên dễ vỡ."],
 ["Một vị vua có râu ngồi trên ngai chạm hình kỳ giông, tay cầm cây gậy đang trổ hoa.","Tầm nhìn cộng với đủ uy quyền để khiến người khác tin vào nó. Một thủ lĩnh bẩm sinh, thiếu kiên nhẫn với tiểu tiết.","Bốc đồng ở quy mô lớn, độc đoán, hoặc lời hứa chạy nhanh hơn khả năng thực hiện."]]},
cups:{ pips:[
 ["Một bàn tay dâng chiếc ly tràn đầy, chim bồ câu sà xuống trong lòng ly, năm dòng nước trào ra ngoài.","Một sự mở lòng — tình cảm được trao đi, một mối gắn kết bắt đầu, một cảm xúc chưa bị làm hỏng.","Khép chặt lòng, hoặc một cảm xúc bị dằn xuống dứt khoát."],
 ["Một người nam và một người nữ nâng cốc thề nguyện với nhau dưới cây trượng có cánh.","Sự thừa nhận lẫn nhau giữa hai người. Sự đồng hành, sự làm lành, một thỏa ước mà cả hai bên đều thật lòng.","Mất cân bằng, một vết rạn, hoặc một người gánh cả mối quan hệ."],
 ["Ba người phụ nữ nâng cốc thành vòng tròn, nhảy múa giữa mùa gặt.","Tình bạn và sự ăn mừng. Niềm vui thật sự khi có người bên cạnh, thay vì vui một mình.","Chuyện ngồi lê đôi mách, quá đà, hoặc một nhóm bạn đã trở nên gượng gạo."],
 ["Một người ngồi khoanh tay dưới gốc cây, làm ngơ chiếc cốc được đưa ra từ đám mây.","Bất mãn và chán chường. Có thứ đang được trao mà bạn không sao khiến mình muốn nó.","Chợt nhận ra thứ đang được trao. Sự thờ ơ bắt đầu tan."],
 ["Một người khoác áo choàng đau buồn trước ba chiếc cốc đã đổ. Hai chiếc còn đứng vững phía sau, không ai để ý tới.","Mất mát, và cái cách nỗi đau khiến bạn chỉ nhìn vào thứ đã mất. Hai chiếc cốc còn đứng chính là toàn bộ thông điệp.","Quay đầu lại. Sự chấp nhận bắt đầu, và bàn tay giúp đỡ được đón nhận."],
 ["Một đứa trẻ trao cho đứa khác chiếc cốc đầy hoa trong khu vườn có tường bao.","Hoài niệm và sự ngây thơ. Lòng tốt từ quá khứ quay trở lại, hoặc một người từ quá khứ trở về.","Mắc kẹt trong ký ức cũ — hoặc cuối cùng cũng đặt nó xuống."],
 ["Bảy chiếc cốc lơ lửng trong mây, đựng một tòa lâu đài, châu báu, vòng nguyệt quế, một con rắn và một bóng người trùm vải.","Quá nhiều lựa chọn, mà phần lớn là mộng tưởng. Hãy chọn lấy một và biến nó thành thật, nếu không sẽ chẳng cái nào thành thật cả.","Sự sáng rõ đang tới, hoặc mộng tưởng bị lộ nguyên hình."],
 ["Một người quay lưng khỏi tám chiếc cốc xếp chồng, đi về phía núi, dưới vầng trăng khuyết bóng.","Rời bỏ một thứ vốn cũng ổn nhưng chưa đủ. Một cuộc ra đi có chủ ý, và phải trả giá bằng chính mình.","Quay trở lại, hoặc không sao khiến mình rời đi được."],
 ["Một người đàn ông mãn nguyện ngồi trước dãy chín chiếc cốc xếp vòng cung, khoanh tay, hài lòng với chính mình.","Sự thỏa lòng. Một điều ước thành hiện thực và niềm vui do mình xứng đáng có — theo truyền thống, đây là lá bài của điều ước.","Tự mãn, hoặc đạt được điều ước rồi mới thấy nó chẳng làm mình thỏa mãn."],
 ["Một đôi vợ chồng giang tay hướng về cầu vồng mười chiếc cốc, trong khi hai đứa trẻ nhảy múa bên cạnh.","Sự viên mãn trong toàn cảnh — gia đình, cảm giác thuộc về, hạnh phúc trụ được với thời gian.","Một bề mặt hoàn hảo với một khoảng trống có thật bên dưới."]],
 court:[
 ["Một thiếu niên áo lam thản nhiên nhìn con cá vừa hiện ra trong chiếc cốc của mình.","Một rung động mới mềm mại, một lời mời, hoặc một ý tưởng từ trí tưởng tượng đáng để đi theo.","Thất thường, hoặc những cảm xúc đáng lẽ phải nói ra lại bị giữ lại."],
 ["Một hiệp sĩ cưỡi ngựa đi chậm, chìa chiếc cốc về phía trước như một lời dâng tặng.","Sự lãng mạn và một cách tiếp cận đầy nhã nhặn. Đi theo trái tim ở nhịp thong thả.","Một lời đề nghị chẳng có gì đằng sau, hoặc lý tưởng không bao giờ chạm đất."],
 ["Một nữ hoàng đăm đăm nhìn vào chiếc cốc có nắp chạm trổ bên mép nước, hoàn toàn đắm chìm.","Sự thấu cảm sâu và trí tuệ cảm xúc. Có thể ôm lấy cảm xúc của người khác mà không chìm trong đó.","Quá tải, hút hết tâm trạng của mọi người vào mình, hoặc sự quan tâm đã hóa thành kiểm soát."],
 ["Một vị vua cầm cốc và quyền trượng, ngồi trên ngai trôi giữa biển động, áo bào vẫn khô.","Cảm xúc được cảm nhận trọn vẹn nhưng không nắm quyền điều khiển. Sự vững vàng giữa giông bão của người khác.","Đè nén, thao túng, hoặc sự bình tĩnh chỉ có ở bề ngoài."]]},
swords:{ pips:[
 ["Một bàn tay nắm chặt thanh kiếm dựng thẳng, đỉnh kiếm đội vòng nguyệt quế và lá cọ, sáu giọt rơi xuống.","Một ý nghĩ sắc và rõ. Sự thật chém xuyên qua, hoặc một quyết định đã đưa ra và không xét lại.","Rối loạn, hoặc sự sáng rõ bị dùng làm vũ khí."],
 ["Một người phụ nữ bịt mắt cầm hai thanh kiếm bắt chéo, ngồi bên mặt nước dưới ánh trăng.","Một thế bế tắc được giữ có chủ ý. Không chịu nhìn thẳng vào một lựa chọn mà bạn vốn đã biết.","Dải băng bịt mắt được gỡ ra; thế bế tắc vỡ, theo hướng này hay hướng kia."],
 ["Ba thanh kiếm xuyên qua một trái tim đỏ trên nền mưa xám.","Nỗi đau lòng trần trụi, và thường là những lời nói đã gây ra nó. Lá bài này không làm dịu đi điều gì cả.","Cơn đau dịu bớt. Nỗi buồn đang được xử lý chủ động thay vì chỉ ngồi lì trong đó."],
 ["Một hiệp sĩ nằm như pho tượng trên mộ đá, ba thanh kiếm treo phía trên và một thanh nằm bên dưới.","Sự nghỉ ngơi bắt buộc. Hồi phục, lui về, khoảng dừng trước hiệp sau — không phải thất bại.","Bồn chồn, kiệt sức, hoặc quay lại cuộc chơi quá sớm."],
 ["Một gã cười khẩy gom kiếm về mình trong khi hai người khác quay lưng bỏ đi.","Thắng với cái giá không đáng. Một cuộc xung đột mà không bên nào bước ra sạch sẽ.","Làm lành, hoặc chấp nhận thua và bước tiếp."],
 ["Người lái đò chống sào đưa con thuyền chở một hành khách trùm đầu và sáu thanh kiếm về phía bờ nước lặng hơn.","Một chuyến vượt khó để rời khỏi rắc rối. Từ đây mọi thứ sẽ yên hơn, nhưng bạn đã phải rời đi mới có được điều đó.","Hành lý mang theo cùng; một cuộc dời đi chẳng giải quyết được gì vì vấn đề cũng đi theo."],
 ["Một người lén rời khỏi khu trại, ôm theo năm thanh kiếm, để lại hai thanh cắm dưới đất.","Mưu mẹo và né tránh. Thoát được một vố — và hai thanh kiếm bạn không mang nổi.","Bị phát hiện, hoặc quyết định nói thật."],
 ["Một người phụ nữ bị trói và bịt mắt đứng giữa tám thanh kiếm cắm xuống bùn.","Cảm giác bị mắc kẹt trong một tình huống thật ra lỏng lẻo hơn bạn tưởng rất nhiều. Những thanh kiếm ấy không phải là cái lồng.","Nhìn ra lối thoát. Dây trói lỏng dần."],
 ["Một người ngồi bật dậy trên giường, hai tay ôm mặt; chín thanh kiếm treo trên bức tường phía sau.","Nỗi lo lúc ba giờ sáng. Cảm giác sợ hãi là thật; còn mức độ của nó thì không.","Đoạn tệ nhất đang qua đi, hoặc cuối cùng cũng nói với một ai đó."],
 ["Một người nằm úp mặt với mười thanh kiếm cắm sau lưng, trong lúc bình minh rạng lên trên mặt nước.","Chạm đáy, và chạm một cách rất kịch. Thật sự không thể tệ hơn được nữa, mà mặt trời thì đã bắt đầu lên.","Hồi phục. Sống sót, và từ chối để mình bị kết liễu."]],
 court:[
 ["Một thiếu niên vung kiếm trên gò cao lộng gió, ngoái nhìn qua vai.","Sự tò mò và những câu hỏi sắc bén. Thu thập thông tin, đôi khi trước cả khi biết để làm gì.","Rình mò, hoài nghi cay nghiệt, hoặc lời nói dùng để cứa vào người khác."],
 ["Một hiệp sĩ lao thẳng vào cơn gió lớn, kiếm giơ cao, ngựa phi hết sức.","Nhanh, thẳng và hay tranh luận. Lao thẳng vào trọng tâm và không giảm tốc vì cảm xúc của ai.","Hung hăng, vụng về, hoặc xông lên nhầm hẳn ngọn đồi."],
 ["Một nữ hoàng nghiêm nghị ngồi trên tầng mây, kiếm dựng thẳng, một tay chìa ra.","Sự sáng rõ không ướt át. Thẳng thắn được nói ra tử tế nhưng không hề làm nhẹ đi. Người đã đi qua chuyện gì đó.","Lạnh lùng, cay đắng, hoặc thói phê phán đã trở thành tính cách."],
 ["Một vị vua cầm kiếm hơi nghiêng, trên ngai chạm hình những con bướm.","Óc phán đoán và uy quyền trí tuệ. Luôn chọn nguyên tắc thay vì sở thích.","Cai trị lạnh lùng, coi tranh luận như môn thể thao, hoặc dùng quyền lực để thắng chứ không phải để phân định."]]},
pentacles:{ pips:[
 ["Một bàn tay dâng đồng tiền vàng phía trên khu vườn có tường bao, cổng vườn mở ra hướng núi.","Một cơ hội sờ được — một lời mời, một công việc, một hạt mầm thịnh vượng có thật.","Một cơ hội bị bỏ lỡ, hoặc một kế hoạch không có nền móng bên dưới."],
 ["Một chàng trai vừa nhảy vừa tung hứng hai đồng tiền trong vòng dây hình vô cực, trong khi những con tàu cưỡi trên sóng lớn.","Cân đối các đầu việc và giữ cho mọi thứ tiếp tục chạy. Linh hoạt, nhưng chỉ vừa đủ.","Đánh rơi một thứ. Ôm đồm quá nhiều và sắp phải trả giá."],
 ["Một người thợ điêu khắc đứng trên bệ trong nhà thờ lớn, bàn bạc với hai người đang cầm bản vẽ.","Sự hợp tác giữa những người có nghề. Công việc được ghi nhận và được phát triển tiếp bởi những người biết mình đang nhìn cái gì.","Công sức bỏ ra không đồng đều, hoặc một nhóm kéo về những hướng khác nhau."],
 ["Một người đội vương miện ôm chặt một đồng tiền vào ngực, đứng lên hai đồng khác, và đội thăng bằng một đồng trên đầu.","Giữ thật chặt. An toàn, tích cóp, kiểm soát — đổi bằng cái giá là không còn cựa quậy được.","Nới lỏng bàn tay, hoặc mất nó dù bạn có muốn hay không."],
 ["Hai người hành khất đi qua ô cửa kính màu đang sáng đèn giữa trời tuyết, một người chống nạng.","Sự túng quẫn, và cái cảm giác rất riêng của người đứng ngoài trong khi người khác đang ấm. Sự giúp đỡ ở gần hơn vẻ ngoài của nó.","Sự hồi phục bắt đầu, hoặc cuối cùng cũng chịu mở lời nhờ giúp."],
 ["Một thương nhân một tay giữ cán cân thăng bằng, tay kia thả những đồng xu xuống cho hai người đang quỳ.","Cho và nhận. Lòng hào phóng là thật, và sự chênh lệch quyền lực bên trong nó cũng thật.","Cho kèm điều kiện, nợ nần, hoặc sự cho đi chỉ chạy theo một chiều."],
 ["Một người đàn ông tựa vào cán cuốc, ngắm giàn cây trĩu những đồng tiền mà anh chưa hái.","Dừng lại để đánh giá một khoản đầu tư dài hơi. Sự kiên nhẫn, và câu hỏi thành thật rằng có nên tiếp tục hay không.","Nóng ruột, hoặc công sức lâu nay đổ vào nhầm thửa ruộng."],
 ["Một người thợ ngồi ở bàn, đục từng đồng tiền một, bảy đồng đã xong, một đồng còn trên tay.","Sự lặp lại đang biến thành tay nghề. Đoạn giữa chẳng hào nhoáng gì của quá trình giỏi lên thật sự.","Làm ẩu, hoặc một công việc đã bị rút cạn hết ý nghĩa."],
 ["Một người phụ nữ trong khu vườn có tường bao đầy giàn nho chín, tay đặt lên con chim ưng đang bịt mũ.","Sự sung túc do chính mình tạo ra. Sự độc lập, và niềm vui được hưởng nó theo cách của riêng mình.","Sự lệ thuộc, hoặc của cải đến mà không kèm theo chút tự do nào."],
 ["Ba thế hệ và hai con chó đứng dưới vòm cổng; mười đồng tiền phủ kín bức tranh.","Của cải bền vững — di sản, gia đình, những cấu trúc sống lâu hơn cả người đã dựng nên chúng.","Mâu thuẫn gia đình vì tiền bạc, hoặc chỉ nghĩ xa được đến hết tháng này."]],
 court:[
 ["Một thiếu niên đứng giữa cánh đồng xanh, nâng niu đồng tiền bằng cả hai tay và chăm chú ngắm nó.","Một người học trò. Một hướng đi mới, thiết thực, được coi trọng đủ để học cho tới nơi tới chốn.","Trì hoãn, hoặc kiến thức học xong không bao giờ đem ra dùng vào việc gì."],
 ["Một hiệp sĩ mặc giáp ngồi bất động trên con ngựa ô nặng nề, chìa đồng tiền ra phía trước.","Bài bản và đáng tin. Chậm, không có gì hào hứng, nhưng rồi việc sẽ xong — vị hiệp sĩ duy nhất không di chuyển.","Trì trệ, cố chấp, hoặc một công việc đã trở nên buồn tẻ."],
 ["Một nữ hoàng ngồi trên ngai chạm hình hoa trái và dê, nâng đồng tiền trong lòng, con thỏ nhỏ dưới chân.","Sự chăm sóc thiết thực. Tháo vát và vững chân đất; khiến những người quanh mình được an toàn về vật chất.","Làm quá sức, chăm đến ngột ngạt, hoặc lo cho tất cả mọi người trừ chính mình."],
 ["Một vị vua khoác áo bào thêu dây nho đặt một tay lên đồng tiền, tòa lâu đài phía sau lưng.","Sự làm chủ thế giới vật chất. Của cải, sự ổn định, và một chỗ dựa thật sự đáng tin.","Tham lam, kiểm soát người khác bằng tiền, hoặc chủ nghĩa vật chất cố chấp."]]}
};

/* English keeps the original wording, untouched. */

const DECKTEXT = { en: { majors: MAJORS, minors: MINORS }, vi: { majors: MAJORS_VI, minors: MINORS_VI } };
